== Capítulo I. Conocimiento Espiritual

[quote.scripture, , Juan 17:3]
____
Y esta es la vida eterna: que te conozcan a ti, el único Dios verdadero,
y a Jesucristo, a quien has enviado.
____

Yo busqué y viajé (desde mi infancia) en pos del
verdadero conocimiento de Dios y de Su Cristo,
y nada de lo que encontré me satisfizo.
Pero habiéndolo encontrado al fin (a través de la tierna
misericordia del Señor y guía de Su Espíritu) y sido satisfecho,
hallándolo ser la vida eterna, la verdadera comida, el poder vivo, el reposo puro,
el gozo y la salvación de mi alma,
no puedo dejar de testificar de ello a los que han gastado su dinero
en lo que no es pan y su salario en lo que no satisface.

Nosotros (algunos al menos) hemos gastado tanto de nuestro
dinero y trabajo como han hecho los que ahora nos desprecian.^
footnote:[Él habla de los cristianos profesantes, y más particularmente,
de sus líderes y sacerdotes que fueron educados en escuelas de educación superior,
y quienes mantenían a los Cuáqueros en desprecio.]
Y algunos de nosotros (lo digo en el temor del Señor y en el verdadero sentido,
sin jactancia) hemos tenido tanto de lo que ellos se alimentan y de lo que llaman pan,
como ellos tienen ahora.
Sin embargo, cuando el Señor nos llevó a la verdadera balanza,
encontramos que eso no era pan,
ni capaz de darle al alma verdadera satisfacción. El verdadero
pan no era lo que nosotros entonces llamábamos pan,
sino uno que habíamos pasado por alto y que no conocíamos.
Pues la vida eterna que está escondida con el Padre,
es manifestada en el Hijo y dada a conocer al alma, es el verdadero pan que no perece.
Tal pan perdurará cuando todo el conocimiento literal y externo de Dios
fracase y no satisfaga el hambre del alma que busca la sustancia misma.

Ahora, es el deseo de mi corazón atraer la mente de los hombres al sentido de la verdad,
al sentido de lo que es la sustancia misma, para que en verdad conozcan el pan,
conozcan las aguas vivas,
vengan a ellas y beban y encuentren a Cristo en ellas
como un pozo de agua que salta para vida eterna.
Por lo tanto,
ha estado en mi corazón hacer la siguiente pregunta y las indagaciones que siguen.
El que pueda responder correctamente estas preguntas debe conocer en verdad la sustancia,
pero el que no pueda responder, puede descubrir por este medio que no sabe correctamente,
y así esperar en Dios recibir el conocimiento de ello,
e ir a Él en busca de la vida eterna que Él da gratuitamente.

Los judíos estaban confundidos acerca del Mesías por venir,
debido al conocimiento literal que tenían de la ley y los profetas.
En realidad,
ellos quedaron lejos del verdadero conocimiento del Mesías por
causa del entendimiento que tenían de las profecías concernientes
a Él. La mayoría de los hombres que profesan a Cristo hoy,
están igualmente confundidos con respecto al conocimiento
que tiene que ver con el cuerpo externo,
la carne y la sangre de Cristo,
de acuerdo a lo que ellos entienden que dicen las Escrituras.
Por tanto,
el velo permanece sobre sus corazones también y no pueden ver la vida
eterna ni la sustancia más de lo que pudieron hacerlo los judíos,
sino que por su conocimiento externo y literal, son mantenidos alejados de la sustancia.

Ahora bien, el anhelo ferviente de mi corazón ante el Señor es el siguiente:
Que quite el velo de todos los corazones que sinceramente desean la verdad,
y abra el verdadero ojo en ellos para que puedan ver al Deseado
y Amado de sus almas y sean conducidos por Él en el verdadero viaje,
fuera del yo y hacia el reino.
¡Oh, qué puedan a la tierra de los vivos,
donde la comida de vida es ingerida y donde los manantiales vivos fluyen!
Allí están los viñedos que no plantamos, las moradas que no edificamos,
y donde el fruto de la plantación de Dios (el vino del reino) es bebido; es decir,
bebido de nuevo en el reino con el Padre y el Hijo en el Espíritu,
quienes son Uno y todo ahí.

=== Una Pregunta a los Profesantes del Cristianismo

La pregunta no es si ellos conocen lo que se dice de Cristo en las Escrituras,
sino si lo conocen salvadoramente, verdaderamente, vívidamente y poderosamente.
Sí, ellos pueden saber lo que se dice de Él,
y aún así no conocer a Aquel de quien se dicen esas cosas.
Así sucedió con los escribas y fariseos,
pues ellos conocían lo que se decía de Cristo en la ley y los profetas,
pero no Lo conocieron cuando apareció en el cuerpo de carne.
De igual manera,
los hombres pueden conocer hoy lo que los apóstoles y evangelistas han
dicho con respecto a Su aparición en el cuerpo de carne (Su nacimiento,
circuncisión, bautismo, predicación, doctrina, milagros, muerte, resurrección, ascensión,
intercesión, etc.), y sin embargo, no conocer a Aquel de quien se dicen estas cosas.
Sí,
ellos pueden saber lo que se dice con respecto a la Palabra que era desde el principio,
y aún así no conocer a la Palabra, al Poder, ni a la Vida misma.

Desde el testimonio de los apóstoles,
la forma o camino del enemigo no ha sido negar directamente a Cristo,
sino llevar a los hombres a un conocimiento de Cristo que no salva.
Así como el enemigo reconoció a Cristo cuando apareció en el cuerpo de carne diciendo:
"`Yo sé quién eres,
el Santo de Dios,`" así ha usado para su beneficio
(desde entonces) reconocer esa apariencia externa.
Él no se opone a esta aparición externa, ni al conocimiento de los hombres,
ni al entendimiento de las Escrituras que los confirman en este.
Pero del conocimiento salvador, del conocimiento verdadero, del conocimiento vivo,
del poderoso conocimiento de la verdad, __a ese__ se opone siempre,
pues es el único que revierte y destruye su reinado
en el hombre y lo saca de su alcance.

Hay una vasta diferencia entre conocer las descripciones
con respecto a una cosa y conocer la cosa misma.
Y también hay una gran diferencia entre creer las descripciones
con respecto a una cosa y creer en la cosa que es descrita.

Las cosas espirituales no pueden ser conocidas salvadoramente, excepto uniéndose a ellas,
recibiéndolas.
Un hombre no puede conocer verdaderamente al Espíritu de Dios mediante
las palabras que son dichas con respecto a Él. Antes que nada,
él debe experimentar algo del Espíritu para conocerlo verdaderamente, pues la paz,
el gozo, la vida, el poder, etc., sobrepasan el entendimiento.
Por tanto,
un hombre no puede conocer estas cosas correctamente
al leer o comprender mucho acerca de ellas,
sino al salirse de sí mismo y viajar adonde ellas son dadas y manifestadas.
Únicamente así podrá entrar en conocimiento de ellas.
Y si la paz que da Cristo, el gozo, la vida,
y el poder no pueden ser conocidos mediante descripciones literales,
¿cómo podría ser conocido Cristo mediante descripciones externas y literales,
siendo Él la plenitud de todo, la fuente de todas ellas, el tesoro de toda perfección,
en Quien se esconden todas las riquezas y tesoros de la sabiduría y del conocimiento?

El verdadero conocimiento está en una Semilla,
en la que el hombre puede recibir la capacidad de conocer,
y en la que el Padre (de Quien vino la Semilla) enseña.
Esta es la manera en que Él nos enseña:
Haciéndonos uno con lo que enseña. De esta forma aprendemos a Cristo:
Naciendo de Él y vistiéndonos de Él. Así conocemos Su justicia, Su vida, Su sabiduría,
Su poder: Recibiendo una medida de ellas,
la cual da la capacidad de discernir y reconocer la plenitud.
En esto recibimos el entendimiento de las Escrituras y conocemos
a la Semilla de la mujer (la que hiere la cabeza de la serpiente):
Recibiendo a la Semilla,
experimentando Su crecimiento en nosotros y Su poder sobre el enemigo.
Entonces conocemos la cosa misma.

De igual modo conocemos la mujer que da a luz esta Semilla según el Espíritu,
la cual es la Jerusalén de arriba.
También conocemos y reconocemos verdaderamente,
a la Semilla que fue dada a luz externamente según la carne.
Sabemos que esta Semilla es: La Semilla de Abraham, la Semilla de David según la carne,
y la Semilla de Dios según el poder de una vida indestructible.
Y somos enseñados por Dios a dar el debido honor a cada una:
A la Semilla de Dios en primer lugar y a la Semilla de David en segundo lugar.^
footnote:[Aquí Penington habla de las dos naturalezas de Cristo,
Quien fue plenamente Dios de acuerdo a la Semilla de Dios y plenamente
hombre de acuerdo a la Semilla de Abraham y David.]
Estaba la Semilla que hizo la obra, la Semilla que era la vida misma,
y estaba la Semilla en la que Él hizo la obra,
la Semilla que fue formada en una vasija como la nuestra, pero sin pecado.
En esta vasija apareció el Cordero puro en el poder puro de vida,
el cual mantuvo la vasija pura,
y así Él (que iba a ser las primicias) tuvo el honor por encima de todos Sus hermanos,
siendo ungido con óleo de alegría más que a sus compañeros.

Pero nosotros también nacimos de la misma Semilla.
Él es formado en nosotros,
nosotros formados de Él. Nosotros también somos de Su carne y sangre,
como Él lo fue de las nuestras.
Al ser así formados,
sentirlo crecer en nosotros y recibir el entendimiento de Él y en Él,
llegamos a conocerlo y a entender las Palabras de las Escrituras concernientes
a Él. Al experimentar y conocer al Cordero en nuestras vasijas,
también conocemos lo que era el Cordero en Su vasija.

Así conocemos las cosas en la certeza y demostración del Espíritu de Dios, es decir,
en la luz que brilla de Él y en la vida que Él engendra.
Nosotros hablamos de las cosas tal como son, como las sentimos ser en la verdadera vida,
la cual el Espíritu de Cristo ha engendrado en nosotros.
Con respecto a las Escrituras podemos decir, verdaderamente, que ahora creemos,
no tanto por el relato de las cosas concernientes a Cristo que encontramos en ellas,
sino porque hemos visto y recibido la cosa de la cual hablan las Escrituras.
Y encontramos que esta es, efectivamente, la Sustancia misma, el Cristo de Dios mismo,
el Inmaculado, la Vestidura viva de justicia y salvación,
en donde Dios no encuentra falta y en la que el alma aparece sin culpa
delante de Él. Con respecto a Este podemos decir palabras de Su naturaleza,
palabras de Su virtud, palabras de Su vida, poder y justicia.
Estas son palabras que la carne no puede oír,
pero que el que es nacido de Dios reconoce y entiende naturalmente.
¿Por qué? Porque él conoce la naturaleza de la cosa
y recibe las palabras en el sabor de la misma.
¿Puede la vida negar la vida?
¿Puede el nacimiento de vida negar lo que brota del mismo vientre?
No, no.
Los niños nacidos de la sabiduría justifican la sabiduría en sus varios brotes y apariciones,
pero lo que la niega es el nacimiento según la letra,
el nacimiento según el conocimiento literal y externo de las cosas,
el nacimiento de la sabiduría comprensiva del hombre.
Este nacimiento, en realidad,
critica y blasfema la sabiduría incomprensible en sus incomprensibles caminos,
y quiere restringir la vida para que sea lo que ellos pueden
percibir o comprender mediante la letra con respecto a ella.

Esta puede ser una gran evidencia para los profesantes, de que ellos, en realidad,
no conocen a Cristo en Su naturaleza, Espíritu,
vida y poder porque no hablan de Él como personas que hayan experimentado la sustancia,
ni hablan a partir del presente sentido y conocimiento de ella,
sino como personas que sólo ponen de manifiesto una noción que han recibido en su entendimiento.
Y sin embargo, en esto también fallan,
porque no hablan de Cristo como las Escrituras verdaderamente
lo presentan (cuando se compara una cosa con la otra),
sino sólo lo que han entendido burdamente con respecto a Él de algunas Escrituras,
tal como hicieron los judíos externos.

Ahora, amigos, si ustedes tienen este conocimiento vivo y espiritual,
y lo mantienen en Aquel que es verdadero,
entonces admítanlo y confiésenlo (tal como es expresado en las Escrituras,
y como Dios lo ha hecho surgir hoy en Su pueblo) para que se manifieste
que son de Él. Hay un entendimiento y una sabiduría del hombre,
y hay un Testigo de Dios que da juicio verdadero.
El hombre (en su mejor esfuerzo) sólo juzga según
le parecen las cosas a partir de las Escrituras,
pero el Testigo de Dios juzga las cosas de Dios en la demostración del Espíritu,
según son sentidas y conocidas que están en Él.

Pero si no tienen este conocimiento espiritual,
sino que por largo tiempo le han dado su dinero y trabajo a eso que no es pan,
ni les puede dar verdadera satisfacción,
¡entonces vengan a las aguas y reciban lo que es dado gratuitamente,
sin dinero y sin precio! ¡Oh, vendan todo por la perla,
por el conocimiento que es de vida, por el conocimiento que es vida! "`Yo soy el camino,
y la verdad, y la vida,`" dijo Cristo, conocer esto es vida eterna.
Así, pues, esperen sentir en ustedes la roca que es puesta como fundamento, es decir,
a la Semilla de Dios, la vida de Cristo, el Espíritu de Cristo revelado en ustedes,
y a sus almas nacidas de Él y edificadas sobre Él. ¡Oh,
si pudieran salir de su propio entendimiento,
si pudieran sentir y recibir el amor de mi corazón y conocer
el dolor de parto que sufre mi alma por ustedes,
para que nazcan de la verdad,
la conozcan y la reciban como está en Jesús y como
es sentida en el Espíritu y en su propio poder puro!

=== Cristo Conocido Externamente e Internamente

Ahora, un poco más,
para quitar los escrúpulos y prejuicios de las mentes de aquellos
que a veces han sido tocados por el poder de la verdad,
y han tenido el testimonio de Dios al alcance de sus corazones,
pero en los que después el enemigo ha levantado una
niebla y puesto estorbos en sus caminos,
suscitando en ellos pensamientos duros contra nosotros.
Es decir,
desnudaré mi corazón para sacar eso de las mentes de los sinceros
de corazón (quienes en la guía de Dios podrían ver este documento):^
footnote:[Las siguientes afirmaciones se hacen en respuesta a lo que era
una crítica común (aunque falsa) contra Penington y los primeros cuáqueros,
a saber,
que ellos enseñaban a Cristo sólo como una vida interior
o una luz que obraba en el corazón,
pero negaban o rechazaban la obra externa de Cristo consumada en Su cuerpo natural.)]

[.numbered]
1+++.+++ Nosotros efectivamente reconocemos que la Palabra de Dios (el
unigénito del Padre) tomó un cuerpo de carne de la virgen María;
Él era de la simiente de David, según las Escrituras,
e hizo la voluntad del Padre en dicho cuerpo,
en obediencia santa a Él tanto en la vida como en la muerte.

[.numbered]
2+++.+++ Que Él ofreció la carne y la sangre de ese cuerpo (aunque no sólo eso,
porque también derramó Su alma, derramó Su vida) como sacrificio u ofrenda por el pecado,
un sacrificio para el Padre, y en él gustó la muerte por todos los hombres.
Es sobre la consideración de Dios de este sacrificio por el pecado y Su aceptación,
que los pecados de los creyentes son perdonados,
para que Dios pueda ser el justo y el justificador del que cree en Jesús,
o es de la fe de Jesús.

[.numbered]
3+++.+++ Nosotros reconocemos lo que es atribuido al cuerpo de Cristo en su debido lugar,
según lo que las Escrituras le atribuyen,
lo cual es a través y por causa de eso que habitaba y actuaba en este,
pues lo que santificaba y mantenía el cuerpo puro
(y hacía todo aceptable en Él) era la vida,
la santidad y la justicia del Espíritu.
Y lo mismo que mantuvo Su vasija pura es lo que nos limpia a nosotros hoy.
Porque el hombre fue excluido de esta virtud viva y poder por causa de la caída,
pero a través del verdadero conocimiento de la muerte de Cristo,
el camino es abierto de nuevo y el hombre es llevado a él para ser bautizado, lavado,
limpiado, santificado, hecho apto y llenado de vida.

De esto podríamos hablar con más claridad y sencillez
si los hombres pudieran oír nuestras palabras.
Pero si les hemos hablado cosas terrenales (en parábolas
y figuras) adecuadas a sus entendimientos y no creen,
¿cómo creerán si les habláramos cosas celestiales,
o si les habláramos claramente del Padre, en Quien está toda la vida del Hijo,
y toda la virtud y salvación que el Hijo alguna vez
tuvo de Él? Los judíos debían aprender en tipos,
figuras y sombras hasta que Cristo viniera, y venido Cristo,
Él también les enseñó mediante semejanzas y comparaciones de las cosas.
Los apóstoles escribieron y les hablaron mucho a
personas que acababan de salir de ese estado,
en un lenguaje adecuado a dicho estado.
Pero el que entra en la sustancia misma y es enseñado ahí por el Espíritu,
después de haber crecido y haber sido capacitado se le enseña
claramente la naturaleza de las cosas celestiales.
Entonces las palabras de los apóstoles (con respecto a las
cosas profundas de Dios) que son misteriosas para los demás,
son manifiestas y claras para él. Sí,
el Señor le enseña cosas que las palabras no pueden pronunciar.
La paz de Dios, el gozo de Su Espíritu, la vida y el poder del Señor Jesucristo;
Su sabiduría, Su justicia y Sus caminos puros y preciosos de santificación del corazón;
la tierna misericordia, fidelidad y rico amor del Padre, etc.,
estas cosas son experimentadas en forma tal,
que no pueden ser pronunciadas a ningún hombre.
En realidad,
ellas no son aprendidas (ni podrían ser aprendidas
nunca) a partir de palabras acerca de las cosas,
sino más bien, mediante la consciencia y experiencia de la cosa misma.
El Señor (en Quien están las profundidades de la vida y Quien da
el sentido y entendimiento de las cosas profundas del Espíritu)
revela estas cosas en él y se las manifiesta a él.

Esta es la manera correcta y excelente de conocimiento: Entrar en unión,
entrar en la cosa misma, aprender en la unión, ver y conocer en la cosa.
Esta es la forma con la que el Señor les enseña a todos Sus hijos en el nuevo pacto:
Mediante la vida interna, mediante la luz pura en el interior,
por la demostración interna de Su Espíritu, por el poder y la virtud de la verdad misma.
El que está en el Hijo tiene alguna medida de esta vida,
pero el que no tiene alguna medida de esta vida no está en el Hijo,
sino en una habladuría solamente y en un conocimiento sabio de las cosas según la carne,
el cual perecerá junto con aquel que permanezca ahí. Pues ningún hombre puede
ser salvo sino entrando al conocimiento que es de la naturaleza pura,
eterna, viva y salvadora.
¿Puede salvar a un hombre la opinión que tenga acerca de Cristo a partir de las Escrituras?
No, porque no es más que una opinión o juicio del hombre,
a menos que él esté en la vida y poder de la cosa misma.
Sólo entonces es verdad efectiva para él, y conocimiento correcto en él. De otro modo,
no es más que conocimiento falso, un conocimiento que no someterá su corazón a la verdad,
pues su asiento no está en el corazón sino en su cabeza,
haciéndolo sabio y capaz de oponerse a la verdad ahí. Tal
conocimiento falso lleva al hombre a un estado de condenación,
ira y miseria más allá de los paganos,
y lo hace más difícil de tratar por la luz y poder de la verdad que al pagano mismo.

¡Por tanto, consideren sus caminos,
oh profesantes del cristianismo! ¡No desprecien la mano que está extendida
hacia ustedes en el amor de Dios y en los movimientos y guía de Su Espíritu,
Quien se compadece de ustedes en gran manera! ¡Dejen que
alcance lo Suyo en ustedes y disperse sus comprensiones,
imaginaciones y concepciones acerca de los significados de las
Escrituras (que son como cadenas de muerte y tinieblas sobre ustedes),
para que puedan venir a Aquel en quien está la vida y da
vida gratuitamente a todos los que acudan a Él! ¡Oh,
observen qué barras de hierro había en el camino de los escribas y fariseos!
Ellos no querían ir a Él para tener vida; en realidad, no podían así como estaban.
Sin embargo, hay barras más grandes en sus caminos; sí,
es más difícil para muchos de ustedes venir a Él de lo que fue para ellos.
Mi deseo sincero ante el Señor por ustedes es,
que Él quite las piedras de tropiezo de sus caminos,
que golpee y derribe la carne en ustedes y que los despoje de todo
el conocimiento que tienen de las Escrituras según la carne.
Sólo entonces sabrán cómo entender, honrar y hacer uso de ellas también,
pero hasta entonces,
no podrán evitar usarlas tanto contra sus propias almas como contra Cristo y Su verdad.

Ahora bien, habiendo sentido y conocido efectivamente la cosa en nuestros corazones,
y habiendo visto también las trampas y redes que el enemigo les pone a ustedes,
por medio de las cuales los mantiene alejados del verdadero pan
y del verdadero vino del reino (como nos alejó anteriormente),
¿cómo podemos guardar silencio?
¿Cómo podemos sino testificarles (en el amor y las
persuasiones del Espíritu del Señor) de la verdad,
vida y poder que hemos sentido en Jesús,
aunque al hacerlo se conviertan en nuestros enemigos?
No es nuestro deseo o fin llevarlos a otra opinión o forma externa,
sino a que puedan sentir la cosa misma,
a conocer con certeza qué es la verdad y a permanecer
en eso que nunca fue engañado ni engañó a ninguno.
Oh, ¿por qué deben vagar en las opiniones oscuras e incertidumbres de la noche?
¿Por qué no prefieren venir a eso,
donde la luz del día brota y a partir de lo cual brilla?
¿Puede el hombre natural (que tiene sus ojos) ser
engañado acerca de la luz del día natural?
¿No conoce él la luz del día tanto por haberla visto
como por haberla distinguido de las tinieblas?
Diez mil veces más seguro e internamente satisfecho
está aquel que es nacido del día espiritual,
que es sacado a luz en dicho día y que ve,
vive y camina espiritualmente en él. En realidad,
no hay duda en aquel que ha crecido en la cosa misma,
pues tiene la seguridad de la fe (la cual está muy por encima de la seguridad
del sentido o de la razón externa) y la seguridad del entendimiento.
¡Oh, bendito es aquel que tiene un ojo para ver, un oído para oír,
un corazón para entender las cosas que Dios ha revelado
por Su Espíritu en este nuestro día,
el camino vivo que ha hecho manifiesto,
la Semilla de vida que ha levantado de la tumba de muerte!

Pero el que critica y habla mal de esta luz (quien ni entrará,
ni dejará a otros) está lejos de recibir la bendición o bienaventuranza de esta Semilla.
Tal hombre crece en la naturaleza y espíritu equivocados,
el espíritu cuyo fin es ser quemado junto con todo
lo que está en unión con él y crece de él. Por tanto,
salgan de ese espíritu,
salgan de esa mente oscura y de esa naturaleza que nunca vio ni puede ver la verdad,
sino que establece opiniones y semejanzas de las cosas en lugar de ellas.
Vengan a recibir la unción que es dada con y en la Semilla
que es levantada en algunos y visitada en muchos,
en este día del amor y tierna misericordia del Señor. Vengan Al que los vivos,
sensatos y redimidos cantan alabanzas,
y en quien esperan una fresca manifestación de Su poder y de Su gloria en ellos cada día.

Ahora amigos, si ustedes quieren conocer correctamente o creer correctamente,
deben conocer y creer en Aquel que estaba con el Padre antes que el mundo fuera,
quien era el Salvador, el Jesús y el Cristo desde la eternidad.
¿Qué lo hace un Salvador?
¿No es el poder de salvación que mora en Él? Que Él tomara
un cuerpo no produjo ninguna alteración en Él,
ni le agregó nada.
Fue necesario que lo tomara sólo para cumplir la voluntad de Dios en dicho cuerpo,
y para que lo ofreciera como sacrificio en Su propia vida y Espíritu al Padre.
¡Esto lo creemos firmemente!
Y sin embargo, no podemos dejar de añadir, que la virtud, el valor, el mérito,
la excelencia de lo que fue hecho por Él __en__ el cuerpo no fue __del__ cuerpo,
sino que estaba en Él antes del tiempo, en el tiempo,
y estará después del tiempo y para siempre.
Sí, es Él a quien correctamente le pertenecen el nombre Jesús y Cristo,
aún antes de que tomara el cuerpo.
Él desplegó en dicho cuerpo la virtud salvadora que tenía desde antes,
que pertenecía a la naturaleza, a la unción en Él,
ya sea que salvara a alguien con ella o no.
Esta virtud, esta vida, este Espíritu, esta naturaleza Suya es la comida, la justicia,
la vestidura de vida y salvación que Él (a través de la muerte del cuerpo) hizo,
y preparó un camino vivo para que el alma pueda venir, comer y vestirse.

Difícilmente puedo dejar de hablar de estas cosas por causa de ustedes,
para que a través de mis palabras puedan llegar a experimentar
eso que es capaz de darles el entendimiento santo.
¡Oh, si pudieran venir a la verdadera consciencia y experiencia de la verdad,
y pudieran ver quién los ha cegado,
cómo los ha cegado y cómo los ha alimentado con cáscaras y comida seca,
en lugar de aquella que tiene la savia verdadera y viva en ella!
Porque mientras vean y juzguen en lo que está equivocado, necesariamente juzgarán mal,
tanto a sí mismos como a los demás;
ustedes no podrán evitar juzgar equivocadamente la verdad misma,
ni las palabras dichas con respecto a ella (sean las del pasado o de ahora).
De esta manera se exponen y se colocan bajo el juicio justo de la verdad misma, es decir,
la del Hijo y la de la luz de Su día,
la cual tiene poder del Padre para juzgar toda falsa apariencia, engaño y engañador.

=== Rechazando la Aparición Interna de Cristo

Le ha placido al Señor,
que así como manifestó a Su Cristo gloriosamente antes de la apostasía,
manifestarlo así otra vez.
Pues Él no sólo nació (en la carne) de la virgen María,
sino también en el Espíritu de la "`mujer vestida del Sol,`" la cual tenía
la luna bajo sus pies y sobre su cabeza una corona de doce estrellas.
Ella también dio a luz un hijo varón,
quien iba a regir a todas las naciones con una vara de hierro.
(Apocalipsis 12)

Ahora, de esta aparición y venida del Señor Jesucristo,
y del fresco alumbramiento de Su vida y poder en Su cuerpo, la iglesia,
hay muchos testigos que lo han visto,
sentido y gustado con los ojos y sentidos que son de Dios y del nuevo nacimiento.
De esto (en el amor y buena voluntad de Dios) y de
las persuasiones y demandas de Su Espíritu,
dan testimonio a otros para que ellos también puedan llegar a ver
la gloria y brillo de Su día y regocijarse en él. Porque,
en verdad, es un día internamente glorioso en el Espíritu,
para los que son vivificados y reunidos en el Pastor vivo y Obispo del alma,
mediante el brazo eterno de Su poder.
Feliz el ojo que ve las cosas que ellos ven,
el oído que oye lo que ellos oyen y el corazón que entiende las
cosas que Dios ha revelado en y para ellos por Su Espíritu.

Gloriosa fue la aparición de Cristo en la carne,
pero había obstáculos en el camino de los judíos para que no pudieran conocerlo,
reconocerlo, creer en Él, ni recibirlo.
Y gloriosa es también la administración de Su vida
en el Espíritu en este día de Su poder,
pero hoy también hay obstáculos puestos en el camino de aquellos a quienes Él es enviado,
que hace que tropiecen y no se rindan a Él ni lo dejen entrar.
Pero bendito aquel que no halló tropiezo en Cristo entonces,
y bendito el que no halle tropiezo en Él hoy,
porque el que halle tropiezo en Aquel que es la vida y da vida,
y se tropiece con la manera presente por la que Dios ha escogido dar vida,
¿cómo vivirá? Esta es la causa de que muchos pobres
corazones se lamenten y se denigren en la tierra,
y giman debido a sus pecados,
y teman por causa de la fuerza del enemigo y por las corrupciones de sus propios corazones,
que están continuamente dispuestos a entregarlos en su mano.
Estos no conocen Al que ha extendido Su brazo y ha venido en Su poder para liberar,
sino que están prejuiciados contra la forma en la que Él ha liberado y libera.
Realmente no conocen la voz que llama: "`Vengan a mí. Yo soy la resurrección y la vida.
El que crea en mí recibirá mi fuerza, y aunque sea débil, será como David,
y aunque sea inmundo,
encontrará las aguas que brotan de mi pozo para purificarlo y nutrirlo para vida eterna.`"

¡Cuán tiernamente visitó Cristo a los judíos en los días de Su
carne! ¡Cuán poderosamente y en la verdadera autoridad de Dios,
predicó entre ellos! ¡Qué poderosas obras mostró! Sin embargo, ellos no pudieron creer.
¿Por qué? El enemigo había entrado en ellos con sus tentaciones
y había obtenido algo en sus mentes de naturaleza contraria,
para así mantener fuera el sentido, conocimiento y reconocimiento de Él. De este modo,
cuando los corazones de aquellos fueron superados
por Su poder y por Su dulce y preciosa doctrina,
y estaban listos para conceder que Él en efecto era el Cristo,
el enemigo levantó un argumento u otro para predisponerlos
contra Él y hacerlos retroceder de reconocerlo o recibirlo.

"`Este hombre no es de Dios,`" dicen algunos, "`porque no guarda el día de reposo.`"
Él no puede ser un profeta, dicen otros, porque "`es de Galilea,
de donde no se levanta profeta.`"
Él "`no puede`" ser Cristo, dice un tercero, porque "`sabemos de dónde es,
pero cuando el Cristo venga, nadie sabrá de dónde es.`"
Él no es santo, estricto ni celoso de acuerdo a la ley, dicen otros, sino un flojo,
"`un comilón, y bebedor de vino, amigo de publicanos y de pecadores.`"
Él no les enseña a Sus discípulos a ayunar ni a orar,
como los fariseos hicieron con los suyos,
y Juan (quien fue generalmente considerado un profeta) hizo con los de él. Él
los justifica cuando arrancan espigas el día de reposo y así los anima a quebrantarlo,
en lugar de observarlo y guardarlo estrictamente de acuerdo a la ley de Dios.
Él es un "`blasfemo,`" dicen algunos, "`haciéndose igual a Dios.`"
Él critica a los más estrictos y celosos hombres que tenemos, es decir,
a nuestros maestros e intérpretes de la ley y profetas, llamándolos "`hipócritas,
sepulcros blanqueados, guías ciegos,`" etc., y pronuncia ayes contra ellos.
A los que son hijos de Abraham, Él los llama hijos del diablo y dice:
"`El que hace pecado, esclavo es del pecado, pero si el Hijo los libertare,
serán verdaderamente libres.`"
Que si queremos tener vida en nosotros,
debemos creer en Él y comer Su carne y beber Su sangre.
(¿Enseñó Moisés o alguno de los profetas alguna vez tal doctrina?) Otra vez dice:
"`Si alguno guarda mis palabras,
nunca verá la muerte,`" mientras que Abraham y los profetas,
que creyeron en Dios y guardaron Sus palabras, están muertos.
Esto hizo que ellos concluyeran que tenía un demonio.
(Juan 8:52) Por tanto,
¿cómo podían ellos entenderlo cuando dijo que Él era "`el buen pastor, y la puerta, etc.,
y "`que todos los que vinieron antes que Él eran ladrones y salteadores`"?
¿No verían esto como un testimonio de Sí mismo y un intento por establecerse?
Y cuando dijo: "`De cierto, de cierto os digo: Antes que Abraham fuese,
yo soy,`" ¿no estaban listos para apedrearlo por decir algo
falso e imposible (tal como les pareció a ellos),
siendo que todavía no tenía cincuenta años? Y luego por Sus milagros,
habiendo de antemano concluido que era un hombre malo, pecador,
quebrantador del día de reposo, blasfemo, engañador del pueblo, etc.,
¡cuán fácil fue para ellos endurecerse contra Él y concluir que
había hecho estas cosas mediante la ayuda y asistencia del diablo!
En realidad,
fueron muchos los argumentos (y algunos aparentemente fuertes e incuestionables)
que formaron la sabiduría y el entendimiento en ellos contra Cristo,
por los que se justificaron a sí mismos en su rechazo a Él.

Estas cosas son pasadas y pueden ser fácilmente condenadas
por los que ahora actúan en el mismo espíritu,
pero el mismo espíritu bajo un nuevo aspecto,
aún se opone a la verdad en su presente aparición y dispensación,
y agita a los hombres a ofender y blasfemar ese santo nombre y
poder (mediante el cual los que creen son salvados y santificados).

Bueno, ¿qué les diré? ¡Oh,
qué puedan discernir espíritus! ¡Qué puedan ver de qué espíritu son y a quién
sirven en oposición a la presente dispensación de vida de Dios! ¡Qué puedan ver
cómo leen las Escrituras fuera de esa luz en la que fueron escritas,
y cómo las tuercen contra Aquel que las escribió! Así se
hacen a sí mismos sabios y fuertes en la sabiduría equivocada
y en el conocimiento contra el Señor y contra Su Cristo,
a quien Él ha puesto sobre Su monte santo de Sión y ahí aparece (aunque no lo vean).
Pues Sión ahora no es natural o según la carne (porque
el día ha venido y las sombras se han ido).
Más bien, Sión es el monte santo de Dios en Espíritu,
sobre el que fue edificada la Jerusalén celestial, la que se revela,
desciende y está descendiendo del cielo,
y en la que muchos de los ciudadanos celestiales moran ya y más están llegando a morar.
Porque serán reunidos desde el este, el oeste,
el norte y el sur para sentarse con Abraham,
Isaac y Jacob en el reino que no puede ser sacudido.
Este reino fue recibido por los cristianos anteriormente
(antes de la apostasía) y ahora es recibido otra vez.

=== El Cristo Que Murió en Jerusalén

Nosotros, los comúnmente llamados Cuáqueros,
somos un pueblo a quien el Señor ha sacado del estado errante, de muchas profesiones,
de varios estados esparcidos y condiciones,
y nos ha reunido en una medida del reposo eterno donde hemos hallado esa vida,
poder y manifestación del Espíritu eterno,
con el que nunca antes estuvimos claramente familiarizados.
Y ahora, habiendo gustado esto, habiendo conocido esto,
habiendo sentido esto y llegado a un deleite real de esto (en algún grado,
de acuerdo a nuestras varias medidas), no nos es posible ocultar este tesoro.
Más bien,
en los movimientos de Su vida y del poder del Espíritu hemos sido
impelidos a testificar de ello a los que son dejados atrás,
y que aún se arrastran bajo la carga de la corrupción
y claman debido al pecado y a la esclavitud.

Ahora bien, esto es lo que hemos hallado con frecuencia:
Que nuestro testimonio no ha sido recibido en el
mismo Espíritu y amor en el que ha salido.
El enemigo, haciendo uso de su sutileza,
ha levantado prejuicios contra nosotros como si negáramos al Cristo que murió en Jerusalén,
profesándolo sólo en palabras, pero negándolo en realidad y sustancia.

Para aclarar este asunto,
nosotros hemos solemnemente profesado ante los ojos del Señor Dios, estas dos cosas:

[.numbered]
__Primero,__
que nosotros realmente reconocemos en nuestros corazones
a ese Cristo que vino en el cumplimiento del tiempo,
en ese cuerpo preparado, para hacer la voluntad del Padre (Su venida al mundo, doctrina,
milagros, sufrimientos, muerte, resurrección, etc.),
tal como está expresado en la letra de las Escrituras.

[.numbered]
__Segundo,__ que no reconocemos a otro Cristo más que a ese,
ni predicamos ninguna otra cosa como el Cristo,
además de Aquel que apareció entonces y se manifestó en carne.

Entonces, debe ser investigado por los profesantes,
cuál es la razón de que aún permanezcan sus prejuicios acerca de nosotros.
Porque sin duda,
si ellos supieran y reconocieran lo mismo que nosotros (en el Espíritu y en el poder,
vida y amor que son de la verdad),
este prejuicio y estos duros pensamientos no podrían permanecer.
Pero si ellos mismos no conocen a Cristo en el Espíritu
(sino sólo de acuerdo a la descripción de la letra),
no es de extrañarse que hayan perdido tanto al Espíritu
como la verdadera intención y significado de la letra.

En efecto,
el Señor me ha mostrado varias veces que ellos mismos
son culpables del mismo cargo que nos achacan,
es decir,
negar a ese Cristo que murió en Jerusalén. Porque el que conoce las palabras
de las Escrituras según las comprende o concibe en los razonamientos de su mente,
no espera que le sean reveladas en el Espíritu.
Este pone sus propias concepciones, razonamientos e imaginaciones,
o una imagen en su mente con respecto a las cosas del Espíritu,
pero pierde la cosa misma.

Nadie puede en verdad llamar a Jesús Señor excepto por el Espíritu.
No obstante,
cualquier hombre moderadamente serio y que pesa las Escrituras en la mente natural,
puede aprender a reconocer la venida de Cristo al mundo, que Él es Señor y Rey, etc.,
y puede llamarlo Señor. De hecho,
tal hombre puede encender un gran calor en sus afectos hacia Cristo (aunque sin la vida,
sin el Espíritu),
pero todo esto no es más que una imagen que se forma en su mente
desde su lectura de las Escrituras y desde sus propias observaciones.
Pero llamar a Jesús Señor en verdad,
es algo que proviene de la experiencia de Su virtud eterna en el Espíritu,
de hallar que las Escrituras le son abiertas por el Espíritu
y en una Semilla que está por encima de la razón,
que abarca la razón y la confunde y la lleva a nada.

Otra vez, no hay verdadero conocimiento de Cristo, ni conocimiento vivo,
ni conocimiento salvador, ni conocimiento que tenga virtud eterna,
salvo ese que es recibido y retenido en la medida de luz dada por Dios a la criatura.
Tal conocimiento es sostenido en la fe que es un don,
en la gracia que es sobrenatural y espiritual,
mientras que la parte racional no es más que natural.
Aquellos que han recibido el entendimiento espiritual saben que es distinto al natural.
Además, por experiencia,
encontramos una clara distinción entre las Escrituras escudriñadas por
los razonamientos de la mente (y las prácticas tomadas de ahí) y las Escrituras
reveladas por el Espíritu y experimentadas en la vida.

Ahora bien,
los profesantes generalmente no reciben su conocimiento de Cristo del Espíritu,
o de las Escrituras reveladas en el Espíritu (y por lo tanto, no conocen la cosa misma,
sino únicamente una descripción de la cosa que la parte
racional del hombre puede beber de la letra de las Escrituras).
Esto se manifiesta en el hecho de que ellos no son capaces (en espíritu y entendimiento)
de distinguir entre la cosa misma y la vestidura con la que estaba vestida,
aunque las Escrituras son muy claras al respecto.
¡Hablen de Cristo de acuerdo al relato de la letra y ellos podrán decir algo,
pero hablen de la sustancia, del espíritu mismo de la cosa,
y allí tartamudearán y balbucearán y mostrarán claramente que no saben lo que es!

Las Escrituras expresamente distinguen entre Cristo y la vestidura que usó,
entre el que vino y el cuerpo en el que vino,
entre la sustancia que estaba cubierta y el velo que la cubría. "`¡He aquí, que vengo,
me has preparado cuerpo!`"
Aquí está claramente Él y el cuerpo en el que vino.
Estaba la vasija externa y la vida interna.
Nosotros ciertamente conocemos esta vida y jamás podríamos llamar a la vestidura corporal,
Cristo, sino a aquello que apareció y habitó en dicho cuerpo.
Ahora, si ustedes en verdad conocen al Cristo de Dios,
dígannos claramente qué fue lo que apareció en el cuerpo,
y si eso no era el Cristo antes que tomara el cuerpo,
el Cristo después que tomara el cuerpo y el Cristo para siempre.

¡Oh, Amigos! ¡Examinen su conocimiento de Cristo,
y su fe y conocimiento de las Escrituras,
y sus oraciones también! Porque es fácil perder la sustancia
viva en todo esto y encontrarse sólo con una sombra.
La sombra puede agradar la parte terrenal y hacer una gran
demostración en el entendimiento natural y en los afectos,
pero no satisface al alma que ha nacido según el Espíritu,
la cual sigue clamando (donde el alma está despierta) tras la verdad, sustancia,
vida y virtud que provienen del Espíritu de Dios.

=== Un Guía Fiel en el Camino de la Verdad

Algo debe descender de Dios al corazón del hombre
para que cambie su corazón y lo redima para Dios,
o no podrá ser salvo.
Él debe recibir una Semilla, nacer de una Semilla nueva e incorruptible,
o no podrá ser renovado de su naturaleza y estado corruptos.
Él debe nacer de agua y del Espíritu de Dios, o no podrá entrar en el reino de Dios.

Esta es la verdadera religión: A saber,
experimentar y estar sujeto a ese poder que redime
para Dios y rompe el poder del maligno en el corazón,
primero expulsándolo,
y luego tomando posesión de la vasija y llenándola del tesoro santo.

[.discourse-part]
Pregunta: Pero, ¿cómo puede un hombre encontrarse con algo así?

[.discourse-part]
Respuesta: La Escritura, que da un testimonio fiel acerca de la verdad, dice que Cristo,
la Palabra de fe que los apóstoles predicaron, está cerca.
Por tanto, un hombre no necesita decir: "`¿Quién subirá o bajará para traerla?`"
Porque, "`Cerca de ti está la palabra,
en tu boca y en tu corazón.`" Esta es esa Palabra que reconcilia con Dios,
que corta y mata la enemistad mediante el poder de la cruz y levanta la Semilla.

[.discourse-part]
Pregunta: Pero, ¿cómo la conoceré y la recibiré?

[.discourse-part]
Respuesta: Hay una Semilla dada al corazón que es contraria al pecado,
que descubre el pecado, que testifica contra el pecado y que aleja la mente de él,
y que equipa con una habilidad nueva y santa a los que esperan en el Señor en ella.
Aquel que presta atención a esta Semilla, la escucha,
se vuelve de lo que ella muestra que es malo (en su luz pura e
infalible) y sigue lo que ella muestra que es bueno (en la voluntad,
fuerza y habilidad que es de ella), este verdaderamente la recibe.
Luego, al esperar en la Semilla y sujetarse a ella diariamente, crecerá en ella,
aumentará en el conocimiento de ella,
se familiarizará con ella y recibirá de ella más cada día. Así,
el hombre cuyo camino era vil,
cuyo corazón fue formado en maldad y llenado de corrupción,
y que diariamente produce pecado y frutos para muerte,
encontrará estas cosas (mediante la luz pura y las instrucciones santas de la
vida) purgadas de él. Hallará a Cristo formado en él y los santos frutos de justicia
producidos a través de su vasija por el poder y el Espíritu de Cristo,
para la gloria de Dios el Padre.

Y luego, estando en Cristo,
estando en la semilla de la vida de Cristo y actuando en ella, hay paz en el alma,
reposo de sus enemigos y de los juicios de Dios,
y aceptación del Padre en lo que el alma es y obra así.

Entonces el mundo perseguirá y odiará excesivamente,
porque esta alma que se somete a Dios así y es cambiada por Él así, no es del mundo,
sino del Padre, quien la engendró en Cristo y la formó a Su imagen y semejanza.
Pero aquel que ponga su mano en el arado (comience a sentir algo de Dios,
se someta a eso y guste de la paz y pureza de eso) no mire atrás al mundo,
ni se preocupe de las tentaciones y oposición con las que
se topará provenientes de esa naturaleza y espíritu,
ya sea en sí mismo o en otros.
Porque si lo hace, nunca será capaz de seguir,
sino que consultará con carne y sangre y terminará regresando a Egipto.
Ahí perderá la corona que está guardada para los que pasan a través del desierto,
a través de las pruebas,
a través de las tentaciones y diversos ejercicios hasta el final de su viaje.

Este es el camino de la vida en breve,
y feliz aquel que experimenta Al que lo guía en este y fielmente Lo sigue hasta el final.
Pero hay otra pregunta que brota en mi corazón que dice:

[.discourse-part]
Pregunta:
¿Cómo puede un hombre llegar a tener sus pecados lavados por la sangre de Cristo?

[.discourse-part]
Respuesta: Al entrar en la luz y caminar en la luz que descubre la sangre,
el único lugar donde es rociada por Dios y sentida por el alma,
él puede recibir la limpieza que es por medio de ella.
Esto es acorde al testimonio de las Escrituras en 1 Juan 1:7, "`Pero si andamos en luz,
como él está en luz, tenemos comunión unos con otros,
y la sangre de Jesucristo su Hijo nos limpia de todo pecado.`"
Por la luz, las tinieblas son disipadas, y en la luz,
la corrupción y la inmundicia son lavadas por la sangre,
y el alma (mente y consciencia) es limpiada de ellas.

"`Este es el mensaje que hemos oído de él, y os anunciamos: Dios es luz,
y no hay ningunas tinieblas en él.`" (versículo 5) ¿Entonces qué? Entonces,
los que deseen conocer a Dios y caminar con Dios deberán (por la virtud de Su
verdad) volverse de las tinieblas a la luz y del poder de Satanás a Dios,
como en Hechos 26:18. Y en esa luz se encontrarán con el
Padre y con Su Hijo Jesucristo y tendrán comunión con ellos,
(versículo 3),
y serán lavados (tanto con agua como con sangre)
y guardados limpios y puros ante los ojos de Dios.

[.discourse-part]
Pregunta: Pero, ¿cómo llego a entrar en la luz y cómo puedo caminar en ella?

[.discourse-part]
Respuesta: Cristo es la luz.
Él es la luz del mundo, la luz de los hombres, la luz de la vida.
Ustedes no necesitan decir en sus corazones:
"`¿Quién subirá al cielo o descenderá al abismo por Él?`" Porque Él está cerca,
en sus bocas y en sus corazones.
Esta es la palabra de fe, en la cual deben creer, amar y obedecer, para que en el amor,
fe y obediencia de esta, sus corazones sean circuncidados y puedan vivir.
Este es el evangelio de nuestra salvación, es decir, este Cristo, esta palabra, esta luz,
esta vida, la cual redime del pecado,
destruye al destructor y pone en libertad el alma para que sirva y viva para
el Señor. Este fue el mensaje que los apóstoles tenían que entregar en sus días,
como en Romanos 10:8. Este también fue el mensaje de Moisés,
cuando habló con respecto al nuevo pacto.
Porque Moisés no sólo entregó el antiguo pacto,
sino que también habló con respecto al nuevo, es decir,
de otro pacto diferente al del Monte Horeb.
(Deuteronomio 29:1) Y la palabra de ese otro pacto
no era la ley escrita en tablas de piedra,
sino la palabra cerca, en la boca y en el corazón. (Capítulo 30:14)

Ahora, todo hombre que quiera ser santificado y heredar el reino de Dios,
debe nacer de la voluntad de Dios.
Debe negar su propia voluntad (como Cristo cuando dijo: "`No mi voluntad,
sino que la tuya sea hecha`"); esa voluntad debe ser crucificada.
Él debe sufrir en la carne,
morir a la carne y vivir en y para la naturaleza santa y Espíritu de Dios.
Al oír la palabra que está cerca, en la boca y en el corazón, y sujetarse a ella,
un hombre llega a nacer de la voluntad pura.
Esta corta su propia voluntad día a día y levanta la voluntad y naturaleza de Dios en él,
a través de lo cual es cambiado y santificado, y llega a ser una nueva criatura.
Pues la vieja criatura está compuesta del viejo entendimiento y voluntad,
pero la nueva criatura está compuesta de lo nuevo.

"`¿Con qué limpiará el joven su camino?
Con guardar tu palabra,`" dijo David.
¿Cuál palabra era esa?
¿Era la palabra del antiguo pacto o la palabra que está cerca,
en la boca y en el corazón? "`Tu palabra,`" dice él, "`es lámpara a mis pies,
y lumbrera a mi camino.`"
¿Cuál palabra era esa, la palabra del primer pacto o la palabra del segundo?
"`La ley de Jehová es perfecta, que convierte el alma.`"
¿Cuál ley es esa?
"`El testimonio de Jehová es fiel, que hace sabio al sencillo.`"
¿Cuál testimonio es ese?
"`Los mandamientos de Jehová son rectos,
que alegran el corazón.`" ¿Cuáles mandamientos son esos?
(¿No eran pesados y gravosos los mandamientos del
antiguo pacto?) "`El precepto de Jehová es puro,
que alumbra los ojos.`"
¿Cuál precepto es ese?
¡Oh, si los hombres pudieran leer! ¡Oh,
si los hombres pudieran ver la cosa que es pura y purifica,
que es justa y justifica! ¡Después que los hombres la han visto,
hay un gran camino por delante que caminar,
pero cuán lejos están los que no la han visto siquiera,
sino que están en las tinieblas y prejuicios de esa
naturaleza y espíritu que es contrario a ello!

Ahora, si el Señor, en Su tierna misericordia y amor por sus almas,
los lleva a una consciencia de ella,
y comienzan a sentir esta palabra preciosa y escrutadora
descubriéndoles cualquier mal en ustedes,
ya sea en sus corazones o sus caminos, ¡oh, no discutan! ¡No razonen contra ella!
Antes bien, bendigan al que descubre, inclínense ante el Hijo, obedezcan de inmediato,
sigan fielmente al Cordero en ello,
para que no sea quitada Su luz de ustedes y las tinieblas
y la sabiduría disputadora los alcance.

Cristo no es de este mundo y Él saca del mundo, saca de las vanidades de este mundo,
caminos, costumbres, modas, etc.
El hombre no puede servir a Cristo y al mundo.
¿Puede un hombre nacer del Padre, ser engendrado por Él, fuera del espíritu del mundo,
y sin embargo, vivir en eso, caminar en eso, en lo que no es del Padre?
¿Puede un hombre nacer de Dios, y sin embargo, todavía vivir en lo que es del mundo,
que proviene de la parte mundana, es de la parte mundana,
se alimenta y complace la parte mundana en el hombre, pero no agrada al Padre?
¿Puede ese hombre que no es del mundo, sino verdaderamente del Padre,
hacer algo que defienda los deseos de la carne,
los deseos de los ojos o la vanagloria de la vida, ya sea en él mismo o en otros?
¿Acaso no saca el Espíritu del Señor (donde Él es escuchado)
de estos deseos y de todas las cosas que son de estos?
Por tanto, consideren bien cuál será el costo y cuán difícil será seguir a Cristo,
para que ustedes que desean ser del Señor puedan
recibir ayuda y fuerza de Él para ser fieles,
para que en Su fuerza puedan vencer todo lo que se interpone entre ustedes y la vida.

=== Algunas afirmaciones Con Respecto a la Semilla y al Camino de la Vida

[.numbered.emphasized]
1+++.+++ Que es una tarea grande y difícil llegar a la capacidad
de conocer y recibir la verdad.

No es cosa difícil tomar cualquier religión que el hombre encuentre en el mundo.
Leer las Escrituras y creer lo que está relatado ahí (según
el entendimiento que el hombre tenga de ellas),
creer que él tiene la luz y la ayuda del Espíritu en su lectura y entendimiento,
aplicarse también a la práctica y observancia de lo que piensa que es requerido,
aspirar a la santidad, etc., esto no es algo difícil.
Todo hombre serio y que busca religión de algún tipo,
puede llegar hasta aquí. Pero nada de esto administra
la verdadera capacidad de conocer y recibir la verdad,
y aquel que desee encontrarla deberá ir más allá de esto.

[.numbered.emphasized]
2+++.+++ Que lo que da la verdadera capacidad es la Semilla de vida que proviene de Dios,
únicamente ahí y en ningún otro lugar,
el hombre puede encontrarla y recibir la verdad.

Esta semilla es la Semilla del reino, o la levadura celestial,
con la que la mente debe ser en alguna medida leudada,
antes de que pueda llegar a la verdadera capacidad de entendimiento y recibir la verdad.
En esta levadura debe permanecer y crecer,
si quiere permanecer y crecer en el verdadero conocimiento.

[.numbered.emphasized]
3+++.+++ Que de esa Semilla y en esa Semilla son dadas todas las cosas.

No sólo son dados y recibidos la verdadera luz y
conocimiento del Señor Jesucristo en esta Semilla,
sino también la verdadera fe, el verdadero amor, la verdadera santificación,
la verdadera justificación, la verdadera paz, el verdadero gozo, etc.
Y lo que no se reciba ni se sostenga aquí, no es de la verdad,
sino una prenda de la propia formación del hombre y no la cubierta del Espíritu.

[.numbered.emphasized]
4+++.+++ Que el Espíritu mismo siembra esta Semilla y es recibido en esta Semilla.

El que recibe esta Semilla y nace de esta Semilla, recibe y nace del Espíritu.
El que no la recibe ni nace de ella, tampoco ha recibido ni ha nacido del Espíritu,
sino que permanece en la imaginación y arrogancia
acerca de las cosas de Dios y no está en la verdad,
según está en Jesús.

[.numbered.emphasized]
5+++.+++ Que en esta Semilla es hecho el nuevo pacto con el alma y se entra en él.

El que recibe esta Semilla de la mano de Dios,
recibe la vida y entra en el pacto de vida,
siente el temor puro en el que Dios limpia el corazón
y mediante el cual Él mantiene el corazón limpio.
Aquí el alma experimenta las leyes de Dios diariamente
escritas por el dedo del Espíritu de Dios,
y siente el poder y el sentido del Espíritu enseñar y causar obediencia.
Por tanto,
el yugo que es difícil para la naturaleza transgresora
(al estar separada de la vida y del poder),
es fácil (y puedo decir natural) para el que es nacido de esta naturaleza.
Pues al estar muerto con Cristo y resucitado con Cristo,
y transformado en la naturaleza de Cristo (mediante la Semilla que es de Él),
puede decir como Cristo dijo (por el mismo poder y Espíritu de Cristo que obra en él):
"`¡He aquí que vengo a hacer Tu voluntad, oh Dios; esta es mi comida y mi bebida, sí,
mi gran deleite.
En verdad, tu ley está escrita en medio de mi corazón!`"

[.numbered.emphasized]
6+++.+++ Que entre aquellos que son reunidos en esta Semilla y permanecen en la experiencia,
luz y vida de dicha Semilla, hay gran amor y unidad.

Ellos son de una mente, un corazón, un alma, un espíritu, una vida,
reunidos en una demostración de la verdad.
No hay discordia, ni duda, ni disensión, etc.
Todo eso está afuera, en el mundo, en la sabiduría terrenal,
en las profesiones y andanzas terrenales,
pero está excluido de la Semilla de verdad y de aquellos
que están reunidos y permanecen en ella.

[.numbered.emphasized]
7+++.+++ Que todos los que no están reunidos en esta Semilla,
ni caminan o viven en ella,
todavía están en las tinieblas y se apartan del poder puro de Dios.

Estos se paran y caminan en lugares resbalosos, y aunque su camino pueda parecer recto,
y su estado y condición seguros (con respecto a Dios) ante sus propios ojos y juicio,
realmente no es así,
sino que están en un sueño concerniente a la verdad y no en la verdad misma.
Y por extraña que parezca tal afirmación con respecto a ellos en el presente, aún así,
ciertamente la sentirán ser así después,
cuando el Señor mediante Su poderosa voz y la aparición
brillante de Su Espíritu los despierte.
Porque muchas cosas pasan como verdad ahora para los hombres en la oscuridad,
las cuales se desvanecerán como humo delante de la luz del día. Y luego,
sólo aquello que es verdad tendrá la gloria y alabanza de ser considerado así. Entonces,
¿qué será de esos que confundieron la verdad y no están vestidos con la
vestidura pura de boda (la vida y justicia sin mancha del Hijo)?

[.numbered.emphasized]
8+++.+++ Que para los que ven en la luz de esta Semilla,
es descubierta la montaña de la casa del Señor.

Los que permanecen y crecen en la montaña de la casa del Señor,
la conocen y la experimentan establecida por encima de todas
las montañas y exaltada por encima de todas las colinas;
de todo conocimiento terrenal, religiones terrenales, caminos terrenales,
adoraciones terrenales, espíritus y mentes terrenales, etc.
Todo esto, en su exaltación y gloria más grande, está muy por debajo.
En esta montaña es la fiesta de las grosuras y de los vinos bien refinados, es decir,
del fruto de la vid que alegra y refresca el corazón mismo de Dios.
Pues el Padre, el Hijo y el Espíritu son revelados aquí,
en la casa y tabernáculo santos que son edificados ahí. Aquí Ellos hacen Su fiesta,
manifiestan las riquezas de Su naturaleza, espíritu y vida preciosa,
en lo cual se alimentan con el alma y le dan al alma
favor y habilidad para alimentarse con Ellos.
Porque en esta comida está la vida, fuerza, justicia y gozo del reino dado y recibido.

[.numbered.emphasized]
9+++.+++ Que es esta misma Semilla en el corazón la que descubre la iniquidad,
la reprende, testifica contra ella y lucha con la mente para volverla de ella
y para esperar la vida y el poder que vienen de lo alto.

En esa Semilla está la naturaleza divina, es decir, la naturaleza del Espíritu de Dios,
la que siempre ha estado contra el pecado y siempre lo estará.
En todas sus apariciones testifica contra el pecado,
y en amor a la criatura,
se esfuerza para convencerla de lo que es contrario a Dios y de
atraerla a esa fuerza y virtud divinas que detienen el pecado,
lo remontan y lo sacan de la mente y de la naturaleza de la criatura.
Porque no hay salvación sino por la cruz y el yugo de nuestro Señor Jesucristo.
En dicha cruz está el poder para crucificar los afectos
y pasiones que guían al pecado y a la muerte,
los cuales no dejarán de tentar y desviar hasta que el alma
sea reunida en unidad con eso que es contrario a ellos.
De modo que, esto es lo principal en la religión:
Conocer a Cristo revelado en el alma como el estandarte contra la corrupción,
y ser reunido bajo Su bandera, la cual es la cruz.

[.numbered.emphasized]
10+++.+++ Que el modo verdadero y cierto del conocimiento de las cosas de Dios,
está en la fe y obediencia a esta Semilla.

No es mediante el razonamiento y la consideración de las
cosas en la mente (según la manera de los hombres),
como el hombre llega a conocer las cosas espirituales,
sino sólo en la medida que ellas son reveladas por
Dios de manera espiritual al que cree y obedece.
Ellas le son reveladas en su creencia, en su obediencia, en su espera, en su santo temor,
en su desconfianza de sí mismo y al sentir su propia insuficiencia,
ya sea para alcanzarlas como para retenerlas.
Ellas son conocidas sólo en la medida que el Señor Dios las manifiesta
en el creyente y lo preserva en el sentido de ellas.
"`El que hace mi voluntad, conocerá mi doctrina,`" dice Cristo.
Esta es la manera.
¿Desean ustedes conocer lo que Dios requiere de ustedes, si esto o aquello es así o no?
¡Pongan la mirada en esta Semilla en ustedes! ¡Pongan la mirada en la luz pura y santa,
los toques y guías internos de esta Semilla pura y divina!
Esto les pondrá de manifiesto lo que es adecuado
para ustedes conocer en sus presentes estados,
y no deben desear más,
sino que como un niño debe descansar contentos con la porción de conocimiento
y fuerza que el Padre sabio y tierno juzga adecuado para ustedes.
En la medida que sus estados crezcan capaces de recibir más,
Él no fallará en administrarlo.
Lo que Él les da es bueno, oportuno y apropiado para ustedes,
de lo que se pueden alimentar con seguridad y disfrutarlo en la consciencia y temor
de Él. Pero si ustedes insisten en pos de lo que Él no quiere que ustedes conozcan todavía,
entrarán en la voluntad y sabiduría de la carne.
Allí encontrarán disputas, descontentos, murmuraciones,
malos ánimos y disposiciones de las mentes,
los cuales se incrementarán y crecerán sobre ustedes para su propio daño.
