== Capítulo 2. Algunas Piedras de Tropiezo Eliminadas / del Camino del Sencillo de Corazón

El Padre, en quien está toda la virtud y el poder de redención,
envió a Su Hijo a reunir a las ovejas esparcidas y perdidas de la casa de Israel,
y no solo eso,
también lo dio "`para luz de los gentiles y salvación hasta lo último de la tierra.`"
El Padre, quien lo envió a predicar el evangelio,
lo ungió y lo llenó de Su Espíritu para que pudiera predicar el evangelio,
según la escritura de Isaías 61:1 - 3.

[quote.scripture]
____
El Espíritu de Jehová el Señor está sobre mí, porque me ungió Jehová;
me ha enviado a predicar buenas nuevas a los abatidos,
a vendar a los quebrantados de corazón, a publicar libertad a los cautivos,
y a los presos apertura de la cárcel; a proclamar el año de la buena voluntad de Jehová,
y...a consolar a todos los enlutados; etc.`"
____

[.discourse-part]
Pregunta: ¿Pero cómo llegaron a encontrar estos mansos, estos quebrantados de corazón,
estos cautivos,
estos encerrados en prisión y estos enlutados la redención
y las bendiciones que Cristo les predicó? O,
¿de qué manera llegaron a recibir y a participar de estas bendiciones provenientes de Él?

[.discourse-part]
Respuesta: Por fe.
Esto es lo que mostraron todas las sanidades externas que Él hizo,
al ser concedidas según la fe.
("`Si crees, verás la gloria de Dios.`"
"`Tu fe te ha sanado.`"
"`Oh, mujer, grande es tu fe;
hágase contigo como quieres.`") De esta misma manera son
otorgadas y recibidas por el alma todas Sus sanidades internas,
es decir, mediante la fe.

[.discourse-part]
Pregunta: Pero, ¿cómo llegaron ellos a tener fe?
O, ¿cómo puede alguien tener fe en el poder redentor?

[.discourse-part]
Respuesta:
Les es otorgada por Dios en el sentido o la consciencia que proviene de
Él. Su Palabra sale de Su boca y hay un testigo de Él en el corazón. Cuando
la Palabra alcanza al Testigo inmediatamente introduce un sentido^
footnote:[Es decir, una consciencia, reconocimiento, percepción.]
verdadero, y en dicho sentido engendra fe.
Entonces,
esta Palabra al ser mezclada con fe (la que es de
Su propio engendramiento) en aquellos que la oyen,
empieza la obra de vida y redención en el corazón donde aún no ha comenzado,
o la continúa en el corazón en donde ya ha comenzado.
Es así como la fe tiene una obra,
una obra que va desde el principio que el corazón se vuelve a Dios hasta el final,
y el que permanece en la fe hasta el final encuentra la obra consumada.

[.discourse-part]
Objeción:
Pero esta fe es otorgada sólo a unos pocos que Dios ha elegido y no a todos los hombres.

[.discourse-part]
Respuesta: Dios ha enviado Su evangelio para que sea predicado a toda criatura.
Su Palabra es capaz de alcanzar al Testigo y de obrar
este sentido o consciencia en cada criatura.
Entonces, en los que haya un sentido forjado, y escuchen a Dios en dicho sentido,
Él obra fe en ellos.
Y a los que esperen en la Palabra,
escuchen la Palabra y mantengan sus mentes ahí en el Señor,
Él les hablará paz y los mantendrá en paz, sacándolos cada día y cada vez más,
del alcance y del poder de eso que los perturba.

[.discourse-part]
Pregunta: ¿Descansa todo el nuevo pacto sobre Dios y no requiere nada de la criatura?
O, ¿requiere Dios algo de la criatura en el nuevo pacto?

[.discourse-part]
Respuesta: Considérenlo bien.
En el nuevo pacto Dios requiere de la criatura lo que Él también da.
¿Acaso no requiere Él la fe y el ejercicio de esa fe,
la que Él mismo obra y da al alma a partir del poder y de la demostración de Su verdad?
El nuevo pacto requiere más de la criatura de lo que alguna vez requirió el antiguo,
pero no lo requiere de la criatura cuando es débil en el estado caído,
sino cuando es enseñada,
fortalecida y capacitada para caminar con Dios en y mediante el poder del pacto.
En realidad, toda forma de santidad y justicia de corazón,
vida y conducta son requeridas en y por el nuevo pacto.
Porque así como el Señor obra todas las cosas en la criatura,
así debe obrar la criatura todo en el Señor, de acuerdo a esa bien conocida escritura:
"`...obrad vuestra propia salvación con temor y temblor.
Porque Dios es el que en vosotros obra, así el querer como el hacer,
según su buena voluntad.`"
(Versión RV 1602 P.) Y aunque la criatura no puede hacer nada que sea bueno en sí mismo,
al crecer en la vida y habilidad que son de Dios,
puede hacer todas las cosas a través de Cristo que la fortalece.

[.discourse-part]
Pregunta: ¿Por qué se dice que Cristo fue ungido para predicar el evangelio a los pobres,
mansos, quebrantados de corazón, cautivos, encarcelados y enlutados?
¿No dio Dios a Su Hijo en amor a todos?
¿No fue hecho por Él un rescate y una propiciación para todos?
¿No fue ungido para predicar el evangelio a todos?
¿Por qué entonces está limitado y restringido aquí a algunos?

[.discourse-part]
Respuesta: Es cierto,
Dios tiene un interés general por toda la humanidad en la dádiva y unción de Su Hijo.
Aún así, hay algunos que están en mejor capacidad de recibir, es decir,
aquellos que ya tienen una consciencia de la falta
de Dios y que jadean y anhelan en pos de Él. En realidad,
hay algunos que están gravemente enfermos en el alma y profundamente heridos en el espíritu,
quienes en la tristeza y miseria de su condición
claman en voz alta por la ayuda del Médico.
Ahora bien, el ojo y el corazón del Señor están especialmente inclinados hacia estos,
y por tanto,
les mandó a Sus profetas que instruyeran y consolaran a estos con respecto a la salvación,
la curación, el aceite de alegría y el Mesías por venir.
Y cuando vino el Mesías, fue enviado de un lado a otro a buscarlos, a hacerles compañía,
a ayudarlos y aliviarlos '`habiéndole sido dada lengua de sabios para que hablara una
palabra oportuna a estos cansados y afligidos.`' Estos no son como la tierra común,
áspera, sin labrar, nudosa y escabrosa, sino una tierra preparada para la Semilla,
por lo que la reciben fácil y naturalmente.

Es cierto que el evangelio es predicado también a los demás, como a la distancia,
y ellos pueden recibirlo si están dispuestos a escuchar,
esperar y separarse de lo que primero se debe separar,
pero estos tienen una gran distancia que viajar.
No obstante, los débiles, desesperados, enlutados, cautivos, etc., están cerca del reino,
cerca de lo que abre y deja entrar en la vida.
Estos son rápidamente alcanzados, ablandados y llevados al sentido,
o a la consciencia en la que (con gozo) reciben la fe,
y con la fe también el poder que trae justicia y salvación a sus almas.
Sin embargo, el enemigo está muy ocupado con estos también, oscureciéndolos,
perturbándolos y doblegándolos para poder mantenerlos en las dudas, temores,
cadenas y grilletes, en la prisión,
lejos de la libertad y curación que la palabra de unción trae.

Ahora presten atención: Dios es real para con todos.
Él desea la vida y la salvación de todos,
y que ninguna alma que haya creado alguna vez sea destruida;
no es natural para Él. Y por la manera que Él expone Su salvación,
está listo para encontrarse con cualquier hombre.
¿Acaso hay alguien a quién Él no invite?
¿Y donde está la persona que no tiene oportunidad de entrar
en la invitación? ¿No es Su palabra un martillo?
¿Quién no puede romperse?
¿No es fuego?
¿La corrupción de quién no puede quemarse?
¿No es agua, vino y sangre?
¿Quién no puede lavarse y nutrirse?
Por lo tanto, que ningún hombre piense en culpar a Dios por su muerte,
porque en esto será engañado y Dios probará ser verdadero.
Pues Dios ha dicho:
"`La destrucción del hombre es por causa de sí mismo,`" por lo que el hombre
que le eche alguna culpa a Dios por no haberlo ayudado más con Su poder,
es un mentiroso.
Tampoco, que ningún hombre culpe a Dios por endurecerlo, porque Dios no endurece a nadie,
excepto al que primero rechaza y aflige el poder
y el amor que lo ablandarían y suavizarían. Es verdad,
nosotros somos la arcilla y Dios el alfarero,
¿acaso no puede el alfarero hacer el tipo de vasija que quiera con su arcilla?
Esta parábola fue dada por el Espíritu del Señor al Israel de antaño,
¿pero qué uso le dio el Señor? ¿Les dijo Él: "`Hagan lo que quieran;
a algunos de ustedes los desecharé y a otros les mostraré misericordia,
porque así lo he determinado`"? ¡No, no fue así! Sino más bien:
"`Tengo este poder sobre ustedes, por tanto, no me provoquen.`"
(Leer Jeremías 18)

¿Acaso no era Dios excesivamente tierno con Su pueblo externo en el pacto externo?
¿Alguna vez los entregó al dolor y sufrimientos sin
una gran provocación de parte de ellos?
Él "`...no aflige ni entristece voluntariamente a los hijos de los hombres.`"
El Espíritu del Señor nunca falló en hacer lo que le correspondía,
al volverlos de la iniquidad hacia Dios en ese pacto.

Algo se levanta en mi corazón en este momento,
que tal vez pueda aclarar más esto en las mentes de algunos.

Caín fue el primer hombre malvado del que leemos, y sin embargo,
¡cuán tierno fue el Señor para con él, es decir,
con el que no sacrificó según el Espíritu, sino según la carne y mató a su hermano Abel!
Ahora,
¿puede algún hombre poner la maldad de Caín en la
voluntad o en el decreto y propósito de Dios?
¿No habría podido él haberlo hecho bien?
¿No habría podido sacrificar a Dios en la fe, así como su hermano Abel?
Si él hubiera hecho bien y ofrecido en la fe,
¿no habría encontrado perdón y aceptación del Señor? Dios no acepta la persona del hombre;
Dios no rechaza la persona del hombre.
Pero hay una Semilla que Él ha escogido,
y reunir al hombre en esta Semilla es Su deleite y Su obra, tal como es el deleite,
naturaleza y obra del otro espíritu dispersar lejos de esta Semilla a los hombres.

Ahora bien, es en esta Semilla que Dios nos acepta, y no fuera de ella.
Sí, en esta Semilla serán benditas todas las familias de la tierra,
según sean recogidas en ella y permanezcan en ella.
Esta Semilla es la Palabra que está cerca, en la boca y en el corazón,
tanto de judíos como de gentiles.
Y cuando es escuchada, Ella escribe la ley del Espíritu de vida en el corazón,
tanto de judíos como de gentiles.
Conforme ellos se convierten en hijos, el Espíritu del Padre es derramado,
el Espíritu de adopción que clama _Abba Padre_ tanto en judíos como en gentiles.

Ahora bien,
la misericordia del Señor perdura para siempre hacia la Semilla de los justos,
y Su justicia e indignación hacia la semilla de los malhechores.
Un hombre (simplemente considerado) no es ni justo ni malhechor,
sólo cuando es reunido y engendrado en la raíz y espíritu de alguno de estos.
Todo hombre tiene un día para la vida de su alma,
y el poder y la misericordia están cerca de él para
ayudarlo a viajar de la muerte a la vida.
¡Feliz aquel que es enseñado por Dios para hacer uso de ese día!

=== Con Respecto a la Elección y a la Condenación

Que ningún hombre se confunda acerca del misterio de la elección y la condenación,
el cual no puede ser entendido por los que están
fuera de la cosa en la que es hecho manifiesto.
Déjenme sólo decir lo siguiente por el momento: Faraón e Israel, Esaú y Jacob,
Ismael e Isaac, etc.; estos eran parábolas que hablaban de algo interior.
¿Qué era Faraón? ¿No era el opresor del Israel de Dios?
¿Qué era Esaú? ¿No era el primer nacimiento, el que vendió la primogenitura y la herencia?
¿Qué era Ismael?
¿No era el nacimiento según la carne?
Estos son rechazados y echados por Dios para siempre, pero el Israel espiritual,
el Jacob espiritual, el Isaac espiritual son aceptados.

¿Hablaré de esto aún más claramente?
No es la criatura la que es rechazada por su Hacedor,
sino algo en la criatura y la criatura en ese algo.
No es la criatura (simplemente) la que es elegida, sino algo^
footnote:[Es decir, Cristo, el Escogido]
en la criatura y la criatura en ese algo.
Ahora, cuando una persona entra en lo elegido, la elección es iniciada en ella,
y en la medida que permanece ahí, permanece en la elección,
y en la medida que lo elegido es asegurado en esa persona,
son asegurados su llamado y elección. Pero cuando una persona se aparta de lo elegido,
se aparta de la elección rumbo a la condenación, y si continua apartada,
hacia la completa impenitencia y dureza, perderá para siempre la elección. Por tanto,
la condenación y el sello de la condenación le serán asegurados.
Dios no hace acepción de personas;
dondequiera que una persona reciba Su santa Semilla y en ella obre justicia,
será aceptada por Él;
y la que reciba la semilla maligna y en ella obre maldad e injusticia,
será rechazada con esa semilla.

[.discourse-part]
Objeción:
Pero yo pensaba que el hombre y sus obras habían
sido completamente excluidas por el pacto de gracia,
pero parece que este toma en consideración ambas cosas.

[.discourse-part]
Respuesta: El hombre está completamente excluido del pacto de gracia por sí mismo,
mientras esté en sí mismo, en su propia capacidad,
separado de la novedad de vida y de la capacidad que son del nuevo pacto.
Pero no está excluido cuando es renovado y recibe un nuevo ser, vida,
virtud y habilidad en el nuevo pacto.
Aquí es requerido mucho de él, y todo lo que haga en esta nueva vida es aprobado,
reconocido y aceptado por Dios.
Aquí el verdadero judío tiene alabanza de Dios.
(Romanos 2:29) Él es elogiado por su fe y por su obediencia en la fe.
Él es elogiado por amar al Señor su Dios con todo
su corazón y a su prójimo como a sí mismo,
y por lavar sus vestiduras en la sangre del Cordero
y mantenerlas limpias en la misma sangre,
mientras que otros contaminan las propias.
Él es alabado por Sus acciones y naturaleza misericordiosas hacia Cristo en Sus miembros,
mientras que otros son rudos y crueles;
por su vigilancia contra las trampas y tentaciones,
mientras que otros se apresuran hacia ellas.
Sí, y por su rechazo y separación de toda impiedad y deseos mundanos, es decir,
los deseos de la carne, de los ojos y de la vanidad de la vida,
nada de lo cual es del Padre, sino del espíritu del mundo.
Así que (noten bien), aunque el hombre está excluido en su naturaleza y estado corruptos,
no así el nuevo hombre,
no el hombre en la regeneración. Pero el hombre deberá ser regenerado, y por tanto,
deberá entrar en el pacto de vida, permanecer y ser hallado en el pacto de vida,
en la naturaleza, en la justicia, en la santidad y en el poder del mismo,
si alguna vez Dios lo va a aprobar.

La diferencia en cada hombre se debe a la gracia, no a algo de sí mismo,
porque el hombre no puede hacer nada que sea bueno, no por sí mismo,
sino sólo por la gracia,
la única capaz de obrar lo que es bueno en él y hacer que él obre en lo bueno.
Así, cuando la gracia lo alcanza, lo atrae,
le da vida y lo hace responder a la gracia (en la virtud,
vida y obediencia que provienen de la gracia),
así continua la obra de gracia en él. Entonces hay
condenación para el que no responde a la gracia,
y justificación y alabanza para el que responde a la gracia.
Sin embargo, toda esta capacidad no se levanta de él mismo, sino de la gracia,
y por lo tanto, los que son justificados, santificados y coronados por la gracia,
hacen bien al echar sus coronas a los pies del Cordero en el trono de gracia,
dándole honor y gloria Al que es digno y a Su gracia que lo ha forjado todo en ellos.

Si algún hombre quiere conocer esto verdaderamente y con certeza,
que no corra hacia las disputas de la mente y del cerebro,
sino que llegue a una experiencia de corazón. ¿Han
encontrado alguna vez la gracia de Dios en sus corazones?
¿Han encontrado sus corazones, en algún momento,
creyendo y obedeciendo en y a través de la fuerza de la gracia?
¿Han encontrado sus corazones, en otro momento, negligentes o rebeldes contra la gracia?
Cuando fueron rebeldes, ¿no fueron condenados?
Y cuando creyeron y obedecieron, ¿a quién le perteneció el honor, a ustedes o a la gracia?
¿Pueden responder a esto?
Bien, así como es en ustedes,
es el caso entre los hombres piadosos e impíos. Así como había
una diferencia cuando ustedes obedecían la gracia y la desobedecían,
así es la diferencia entre el hombre no regenerado y el regenerado.
Cuando ustedes no obedecían, eso que llamaba a la obediencia los condenaba;
así hace en ellos.
Cuando ustedes obedecían, claramente sentían que la alabanza no era de ustedes,
sino que le pertenecía a la gracia que obraba en ustedes;
así es también en el hombre regenerado, en quien el Señor obra por Su gracia,
y quien obra su salvación a través de Él, haciendo su llamado y elección seguros.
Dejen su conocimiento cerebral y lleguen a la verdadera
experiencia (donde los misterios de Dios son hechos manifiestos),
y esta pronto será fácil y clara para ustedes.
Estas cosas no fueron designadas por Dios para ser
descubiertas por la sabiduría disputadora del hombre,
porque Dios, que da el conocimiento,
las esconde de esa parte y las entrega al nacimiento
inocente y simple de Su propio Espíritu.

[.discourse-part]
Objeción: Pero cuando el Padre atrae, ¿puede alguien resistirse o sostenerse?
¿No hace el poder del Señor que cualquiera hacia quien Él ejerza Su poder, se disponga?

[.discourse-part]
Respuesta:
El poder de Dios es grande y tiene dominio sobre todo espíritu malo que tienta,
sobre toda la corrupción, apostasía y retirada del corazón;
pero el Padre no salva al hombre mediante un acto tan absoluto de Su poder.
Más bien, el poder del Señor obra en y según el modo que Él lo haya designado.
De esta manera el diablo tiene libertad y poder de tentar,
oponerse y resistir la palabra de Dios.
Los que lo oyen y entran en la tentación y trampa que él coloca,
dejan que su poder se apodere de ellos y se apartan de la virtud,
operación y fuerza del poder de Dios.
Aún así, sigue siendo cierto que el Señor no sólo comienza Su obra en el hombre,
sino que también la lleva a cabo en el día de Su poder, dando no sólo el querer,
sino también el hacer lo que es correcto y agradable a Sus ojos.
Pero aún, esto es en y de acuerdo a Su propio modo y pacto.

[.discourse-part]
Objeción: Si Dios extiende Su poder para salvar y el diablo interrumpe y detiene Su obra,
entonces parece que el diablo es más fuerte que Dios.
¿Es el diablo más fuerte que Dios?
Si no lo es, ¿cómo puede él oponerse y resistir a Dios en la obra de Su poder?

[.discourse-part]
Respuesta: No, el diablo no es más fuerte que Dios; aunque es muy fuerte.
Pero si el corazón deja entrar al enemigo,
aflige al Espíritu y hace retroceder Su poder en
la forma en la que está designado que obre,
entonces el diablo puede ser más dominante en él que el poder de Dios.
Pero en los que creen, son obedientes y se sujetan al poder de Dios,
Su poder es mucho más fuerte en ellos para defender y llevar a cabo Su obra,
que el poder del diablo para obrar en contra y estorbarla.

Hay objeciones también relacionadas con el libre albedrío y la caída de la gracia,
que están muy adheridas en el espíritu de muchos y no las pueden superar.
Pero le ha placido al Señor aclarar estas cosas para nosotros
y satisfacer nuestros corazones con respecto a ellas,
para que no haya en nosotros ninguna dificultad o duda sobre esto.

Con respecto al libre albedrío: Sabemos, por Dios,
que el hombre en su estado caído está espiritualmente muerto
y que no tiene voluntad propia para hacer el bien,
sino que su entendimiento y su voluntad están tanto
oscurecidos como aprisionados por el enemigo.
No obstante, en Cristo hay libertad y en Su palabra hay poder y vida.
Y cuando esta palabra alcanza el corazón y suelta las cadenas del enemigo,
no sólo engendra la libertad de mente hacia el bien, sino una inclinación,
deseo y respiración tras este.
Entonces el Padre atrae y el alma (al sentir la atracción) responde en cierta medida,
y al venir a Él de esta manera es bienvenida por Cristo y aceptada por el Padre.
Pero a pesar de todo esto, el enemigo tentará el alma y puede que ella lo oiga,
lo deje entrar y caiga en la tentación,
y por eso retroceda después de haber puesto su mano en el arado.
Ahora, el hombre que "`retrocediere, no agradará a mi alma,`" dice el Señor. Y,
"`ninguno que poniendo su mano en el arado y mira hacia atrás,
es apto para el reino de Dios.`"

Con respecto a caer de la gracia:
El Señor nos muestra qué es lo que tiende a caer y qué no puede caer.
Cristo no puede caer, y lo que está reunido en Él,
se para firme en Él y permanece en Él (participando así de Su preservación),
no puede caer.
Nada puede irrumpir en el poder que preserva en el camino señalado,
pero es posible salir y perecer fuera de él. Fuera de los límites
del pacto no se experimentan la preservación ni el poder del pacto,
pero al venir a Cristo en las persuasiones del Padre,
en la consciencia y fe que Él engendra, y al permanecer con Aquel que atrajo,
en la consciencia y fe que Él diariamente engendra de nuevo
(porque Él renueva el pacto y la misericordia diariamente,
y guarda el pacto y la misericordia para siempre),
se experimentan el poder y la preservación. Aquí la mano del Padre rodea el alma,
de la cual nadie puede arrebatarla.
Ahora el que siente y experimenta estas cosas todos los días,
el que ve y siente diariamente cómo puede caer y cómo no puede caer,
cómo se encuentra con la preservación y cómo la pierde,
cómo permanece en el poder puro (el cual es la frontera de este pacto
santo) y cómo vaga fuera de dicho poder hacia las fronteras de otro pacto,
espíritu y poder, ciertamente conoce estas cosas.
Pero otros hombres (quienes no tienen experiencia de la cosa misma) sólo pueden adivinarlas,
y se esfuerzan por comprenderlas con esa parte que Dios ha excluido de ellos.

Ahora consideren esta parábola con la que voy a concluir.
Aunque el sol natural y externamente visible se levanta muy alto sobre la tierra,
el que es naturalmente ciego no puede verlo ni participar de su luz.
Así también, aunque el Sol espiritual, el Sol de justicia,
el Sol del mundo interior se levanta muy alto y aparece brillantemente en muchas nubes,
los que son espiritualmente ciegos no pueden discernirlo,
ni cosechar los beneficios de Su luz, ni participar de la salud en sus alas.

=== Una Exhortación a los Desolados y Angustiados

Ahora es el tiempo aceptable, ahora es el día de salvación. Ahora se levanta la vida,
ahora brilla la luz para guiar de las tinieblas y muerte a la tierra de los vivos.
¡Oh,
despierten ustedes los que duermen en el polvo de la tierra! ¡Levántense
de entre los muertos y Cristo les dará luz para caminar a lo largo
de la senda de los vivos! ¡Vengan Al que el Padre ha sellado,
Al que es la vida y la da gratuitamente a todo el que llega! ¡Sí,
Él da abundantemente a los que esperan en Él y caminan fielmente en Su pacto! ¡Oh,
por tanto, entren en pacto con Él! ¡Presten atención a las palabras de Sus labios,
las cuales engendran un verdadero sentir, y en dicho sentir se mueve Su vida,
y en los movimientos de Su vida se experimentan las persuasiones del Padre!

Presten atención a los pequeños movimientos y agitaciones
en ustedes que va tras eso que es eterno,
pues Él no sofocará ningún deseo que esté verdaderamente tras Él (Su naturaleza es apreciarlo).
Y pueblo, tomen en cuenta lo siguiente (es un testimonio verdadero):
La puerta de la vida ya está abierta por Aquel que tiene la llave y el poder,
para que el que quiera pueda entrar.
Y a ustedes, afligidos dolientes, que están buscando el camino a Sión,
llorando la ausencia de Su Amado, en Cuya presencia están la vida y la redención,
la resurrección de los muertos y la victoria sobre el pecado,
¿qué les diré? Oigan las noticias de júbilo: La apostasía ha terminado.
Ahora, no estoy diciendo que la apostasía en general haya terminado.
No, no.
Hay muchas aflicciones, plagas,
juicios y terribles truenos por venir sobre las personas y naciones,
antes que sientan que ha terminado.
Sino que ha terminado en algunas vasijas que están sobre la tierra.
El hombre de pecado, el malvado,
el hijo de perdición ha sido descubierto por el Espíritu del Señor. Ha sido perseguido,
consumido y destruido por el aliento de Su boca y por el brillo de Su aparición en algunos.
Sí, la iglesia ha salido del desierto y el hijo varón junto con ella,
pues ella no viene sin su Amado,
sino apoyada en Él. Él es conocido por ella como el que
gobierna con Su cetro de oro y con Su vara de hierro,
que derriba al espíritu corrupto, egoísta, terco y terrenal, y levanta al que es manso,
tierno, humilde, inclinado y oprimido.

Ahora bien, como dijo Cristo cuando predicaba en los días de Su carne:
"`Hoy se ha cumplido esta Escritura delante de vosotros.`"
(Lucas 4:21) ¿Acaso no fue cumplida entonces externamente entre los judíos externos?
¿Hubo algún enfermo, o débil, o ciego, o cojo,
o leproso o poseído por demonios al que Cristo no estuviera listo a curar?
¿No anduvo haciendo el bien y buscándolos para curarlos?
¡Así es ahora en el Espíritu y poder del Señor entre los judíos espirituales!
"`Hoy se ha cumplido espiritualmente esta Escritura delante de vosotros.`"
Sí, lo que Él hizo entonces externamente, es experimentado hoy en espíritu,
hecho entre ustedes interna y espiritualmente.
¿Cuántos que antes eran ciegos ven ahora?
¿Cuántos que antes eran sordos oyen ahora?
Los que antes eran cojos ahora caminan, el leproso ahora está limpio,
los muertos ahora están resucitados, el mudo ahora habla.
El pobre, el vacío,
el desnudo ahora están vestidos y llenos de las riquezas y tesoros del reino eterno.
¿Acaso no puede ser verdaderamente dicho, por muchos corazones pobres y afligidos,
que el desierto y los lugares solitarios son alegres ahora?
¿Que el que una vez estuvo seco por la sequía y esterilidad,
ahora siente las fuentes vivas, el desbordamiento del río puro y claro de vida,
cuyas corrientes alegran la ciudad de Dios?
De hecho, algunos pueden decir ahora: "`¿Dónde está ahora la naturaleza envidiosa,
cruel y a semejanza del dragón? ¿No hay una nueva
creación? ¿No hay un nuevo cielo y una nueva tierra,
y no han sido hechas nuevas todas las cosas en ellos?
¿No han pasado todas las cosas viejas de la noche y de las tinieblas,
y no han sido hechas nuevas todas las cosas en este día que el Señor ha formado
en los corazones que han recibido y han sido sujetados a Su luz?

Y ahora,
¿qué les impide levantar sus cabezas y ver la venida
del Hijo del hombre en las nubes en las que viene,
y participar de la redención,
virtud y poder de Su aparición? ¿Qué son las nubes en las que viene?
¿Es Su venida externa?
O, ¿son las nubes externas?
O, ¿es Su venida interna y espiritual en diez mil de Sus santos?
(Judas 1:14)^
footnote:[La mayoría de las versiones traducen este pasaje: "`He aquí,
el Señor viene con decenas de millares de sus santos.`"
(RVG) Pero la palabra en el original griego es __en__ y no __con__.]
¿No vio Enoc que Él iba a venir de esta manera para juzgar al mundo?
¿No viene Él "`para ser glorificado en sus santos`"? (2
Tesalonicenses 1:10) ¿No deben ellos juzgar al mundo;
ellos en Él y Él en ellos?
¡Oh, lean correctamente; lean con el Espíritu y con Su entendimiento!
Entonces la verdad de la letra será manifestada y brillará en ustedes.
Nada se interpone en sus caminos,
sino la falta del ojo espiritual para ver Su aparición espiritual
en algunos (y así esperarla en ustedes mismos),
es decir, el ojo de la fe,
el cual (conforme el Señor lo abre) ve el poder y la gloria invisibles.

Les tengo que decir lo siguiente en el verdadero sentido y entendimiento.
Vengan a la luz de los gentiles,
vengan a eso que Dios ha dispensado al gentil como al judío:
La Palabra (o Mandamiento) que está cerca,
en la boca y en el corazón. Esta Palabra ha sido la más baja de todas,
despreciada por todos, y sin embargo, está en el corazón de Dios exaltarla sobre todo,
porque está por encima de todo.
Esta es de la que el hombre huyó en el jardín cuando el velo cayó sobre
él. Es a la que todas las sombras de la ley debían apuntar y mostrar.
Conforme el hombre es llevado a ella de nuevo,
así brota en él y experimenta la poderosa redención de la Palabra eterna.
Sí, el que oye la voz de esta, aunque esté muy muerto en delitos y pecados,
sentirá brotar la vida en él y el pacto de vida revelado internamente.
Esta es la única verdad, la única palabra pura y eterna y camino al Padre,
la cual era desde el principio y permanece igual hasta el final.
Es la única puerta,
por la que todos han entrado a la vida y por la que todos todavía entran,
y no hay ninguna otra.
¡Bendito para siempre Aquel que la ha hecho tan manifiesta y clara en este nuestro día,
y benditos los que la ven y entran en la vida por ella!

=== La Visita del Amor Tierno y Recto

El asunto principal en la verdadera religión es recibir a la Semilla de vida de Dios,
por la que la mente puede ser cambiada,
el corazón capacitado para entender los misterios de Su reino,
y ver y andar en el camino de vida.
Este es el clamor de las almas de los justos: Que ellos permanezcan,
crezcan y caminen con el Señor en esta Semilla, y que otros que también respiran tras Él,
sean reunidos en la misma Semilla y sientan la virtud de la misma.

Sin embargo, hay uno que se interpone en el camino para estorbar esta obra del Señor,
quien con gran sutileza se esfuerza por mantener a las almas cautivas,
y prejuiciarlas contra las apariciones vivas y preciosas del poder redentor del Señor.

Una de las maneras principales por las que lo hace es,
levantando en ellas un temor a ser engañadas y traicionadas, y entonces,
en lugar de obtener más, pierden lo poco que tienen de Dios.
Yo fui probado por largo tiempo con este temor.
Cuando la vida se movía en mi corazón,
este temor era levantado en mí para que yo no me
atreviera a creer que lo que sentía era de Dios,
a pesar de que había un verdadero toque de Su virtud vivificadora, cálida,
convincente y avivadora en él.

Para que los que respiran en pos del Señor puedan escapar de esta trampa, ¡oh,
tienen que esperar, llorar y clamarle a Él,
para que Él escriba Su temor puro en sus corazones y les enseñe cuándo temer,
cómo temer y a qué temer!
A medida que esto sea realizado en ellos,
verán que tienen más razones para temer su estado presente,
que temerle a eso que (en la calidez vivificante y virtud
de Dios) viene a producir un cambio en su estado presente.
Sí, entonces verán cómo el enemigo los hace temer donde no hay nada que temer,
y cómo les impide temer lo que todos los hombres deben temer.
Y esto es, ciertamente, lo que más deberían temer:
A no oír el llamado del Espíritu del Señor a salir de Babilonia,
y no oír ni ocuparse del llamado de Su Espíritu hacia Sión, el monte santo de Dios,
hacia el que Él guía a Su pueblo en el día de la revelación
y manifestación de Su glorioso amor y poder.

¡Oh, por tanto, amigos míos, ustedes que anhelan al Señor,
ustedes que desean sentir el poder de Su verdad,
esperen que la Semilla de vida que proviene de Él sea revelada
en ustedes! ¡Esperen el temor puro que proviene de la Semilla,
para que puedan sentir al Señor escribiendo Su temor, Su temor puro,
santo y protector en sus corazones, y conozcan el camino que lleva a Él,
y vengan y se unan a Él en la Semilla y nunca se separen de Él!
El temor del Señor que se levanta de la Semilla de Su vida,
hará esto en ustedes, sin falta, cuando lo reciban de Él. Pero el otro temor,
el temor que engendra el enemigo no lo hará,
sino que será un obstáculo en sus caminos hasta que el Señor
lo saque de ustedes a través de Su santo poder.

Y ahora, respóndanme una pregunta sinceramente, como delante de Dios:
¿Han llegado a Sión, o están al menos viajando hacia allí recta y verdaderamente?
¿Alguna vez han conocido a alguno de los viajeros, con quien hayan estado familiarizados,
que pueda (en verdad) decir que haya llegado a Sión? Los
cristianos en los tiempos primitivos llegaron a Sión,
y conocieron y moraron con Dios y con Cristo ahí. Estos conocían Jerusalén,
el edificio celestial, la ciudad del Dios vivo.
¿Oh, dónde están ustedes?
¿Han salido ya de Babilonia?
¿Conocen ya el desierto y los intrincados senderos en él,
a través de los cuales sólo Dios puede guiar el alma?
¡Oh, salgan, salgan de su lugar actual (en la guía del Espíritu de Dios),
a menos que puedan decir, en la verdadera e infalible luz, que están en su reposo,
en el verdadero reposo de sus almas; es decir, en el reino eterno,
el que no puede ser sacudido,
el que los cristianos primitivos recibieron y en el que encontraron entrada!

Amigos,
déjenme decirles algo más (porque en este momento
mi corazón está abierto para ustedes por el Señor).
Cuando el alma en sus viajes llega a Sión,
se experimenta la ley del Espíritu de vida en Cristo Jesús,
la que libera de la ley del pecado y muerte.
Y entonces no hay más clamor por el cuerpo de pecado como había antes,
sino una bendición de Aquel que ha liberado y diariamente libera de este.
Sí,
el alma conoce y siente la eliminación del cuerpo
de pecado y a Cristo colocado en su lugar.
Porque, mis amigos,
el alma experimenta varios estados en sus viajes
verdaderos y discernibles hacia la tierra santa.
Como por ejemplo:

[.numbered-group]
====

[.numbered]
1+++.+++ Hay un estado de oscuridad y esclavitud egipcia,
en el que el poder de la muerte reina y gobierna en el corazón,
sometiéndolo al pecado y a la muerte.
Aquí el alma está en la tumba y bajo muerte, cautiverio y esclavitud,
incluso en medio de todas sus profesiones de religión, conversación de Dios y de Cristo,
lectura de las Escrituras, observación de ordenanzas y deberes, etc.

[.numbered]
2+++.+++ Hay un estado de desierto,
en el que la fuerza del cautiverio es en alguna medida rota,
el corazón es atraído a ocuparse de las guías de vida y
a seguir en pos del Señor a través de las pruebas,
a través de los entrenamientos,
a través de los diversos ejercicios con los que el Señor tiene a bien ejercitarlo.

Aquí la misericordia y la bondad del Señor son experimentadas,
como también el engaño y la traición del corazón. Este es
el lugar de la humillación y del quebrantamiento,
en el que el alma diariamente siente cuán indispuesta y desacostumbrada está al yugo,
el que debe quebrar el espíritu y someterlo a Dios.
Aquí el Señor le muestra al alma lo que es su corazón,
para que Él pueda humillarlo y a la postre hacerle bien.
Aquí la misma ley de Dios aparece débil,
debido a la fuerza de la carne que aún no está sometida.
Aquí hay lamentos, gemidos y clamores al Señor noche y día,
tanto por la violencia y multitud de enemigos, como por la rebelión,
desconfianza e incredulidad del corazón.

[.numbered]
3+++.+++ Hay un estado de reposo, un estado de paz, un estado de vida, un estado de poder,
un estado de gracia, un estado de dominio, en la vida y a través del poder del Señor,
en el que la ley de vida es manifestada en dominio
en el corazón sobre la ley del pecado y muerte.
Hay un reino eterno, donde reinan Dios y Cristo,
en el que Dios pisotea a Satanás bajo los pies del
alma y la hace rey y sacerdote en el Hijo de Su amor,
y donde el alma siente que es una con el Amado y aceptada en Él.

====

Amigos, mi ferviente deseo es que ustedes conozcan este reino, viajen fielmente hacia él,
sientan y entren en el reinado de Cristo en él,
se sienten en lugares celestiales en Cristo Jesús y hereden la sustancia.
¡Qué experimenten la reunión con Cristo en el nombre y se sienten en el nombre,
donde el enemigo no puede tocarlos, sino más bien,
donde sienten la preservación y la poderosa vida
y dominio de esa Semilla que está sobre el enemigo,
en la que y por la que el Señor dispersa al enemigo,
hiriendo la cabeza de la serpiente! ¡Qué puedan conocer
el precioso y glorioso edificio de vida en el Espíritu,
es decir, el de la santa casa y ciudad de Dios,
donde las murallas son salvación y las puertas alabanza!
Para este fin está en mi corazón, proveniente del Señor, escribirles estas cosas.
¡Que el Señor Dios de misericordia les abra la puerta de entrada a estas cosas!
Porque no hay más que una puerta de vida, no hay otra, la cual es Cristo, la Semilla.
Esta Semilla es revelada en el interior para romper la sabiduría,
fuerza y cabeza de la serpiente ahí. En la medida que Él las rompe,
allí (y no más allá) se experimentan la verdadera redención y libertad.

¡Oh,
qué puedan recibir el entendimiento del Señor y ser enseñados por Él a
negarse y a separarse del entendimiento que no es de Él! ¡Qué puedan ver
las cosas (de Él y en Su luz) que no han visto aún! ¡Qué conozcan (por
experiencia) lo que debe vivir y lo que debe morir en ustedes,
y puedan sentir el levantamiento de sus almas de
la tumba a través de la Semilla inmortal de Dios,
y que toda su sabiduría y conocimiento (incluso el
de las cosas de Dios) sean llevados a la muerte!

=== Con Respecto a las Ordenanzas

Ahora, al parecer,
el gran asunto que ustedes tienen en contra de nosotros con respecto
a las ordenanzas tiene que ver con el bautismo en agua,
con partir el pan externo y beber el vino externo.
Concerniente a esto tengo dos o tres pesadas interrogantes para considerar seriamente:

[.discourse-part]
__Interrogante 1:__ ¿Eran estas cosas en sí mismas las cosas del reino,
o eran representaciones de algo relacionado con el reino,
como lo eran las sombras bajo la ley?
Por tanto,
aún cuando ellas pudieron haber tenido un uso y servicio
en el tiempo que la ley estaba desapareciendo,
¿deberían tener un lugar absoluto en el día del evangelio?
Porque conforme el día amanece e irrumpe, las sombras se desvanecen.
¿Qué debe hacer la sombra cuando eso que ella representa llega?
¿Qué lugar hay para las sombras en la sustancia, en el reino eterno?

Ahora,
aunque el apóstol Pablo consintió en cuanto a la circuncisión por el bien de los judíos,
la circuncisión externa no iba a permanecer.
Él también consintió en cuanto al bautismo de Juan, es decir,
el bautismo en agua (porque este no era el bautismo de Cristo, siendo el Suyo,
el del Espíritu Santo y fuego).
Aún así, el apóstol bendijo a Dios porque no había hecho uso de este,
y dijo que él no había sido enviado a bautizar.
¿Con qué no había sido enviado a bautizar?
Bueno, __no con agua,__ no con el bautismo de Juan.
Él fue enviado a bautizar con el bautismo de Cristo, es decir, a bautizar en el nombre,
en el Espíritu, en el poder (y también lo fueron todos los apóstoles),
así como también a predicar el evangelio.
(Gálatas 3:5; Mateo 28:19)

Luego, en cuanto a la cena,
¿no era esta una sombra de la verdadera y sustancial cena del Señor?
¿No hablaba externamente de partir el verdadero pan y beber el
verdadero vino (el fruto de la vid de la vida) en el reino de Dios?
¿Acaso no se había acercado este reino en los tiempos de Juan,
y los discípulos de Cristo acaso no debían orar que viniera?
¿No experimentaron los apóstoles su venida (aquellos que estaban en el poder, vida,
justicia y gozo eterno)?
Porque noten: La promesa no sólo era de un reino de gloria en el más allá,
cuando el cuerpo esté tendido,
sino que ellos debían recibir el reino y experimentar la entrada (una
entrada abundante) en dicho reino eterno otorgada a ellos incluso entonces.
Ellos debían comer pan en el reino y beber vino en el reino,
es decir el nuevo pan y el nuevo vino, recién salidos de la mesa del Señor. En realidad,
ellos debían comer con el Señor, en Su presencia,
según la promesa de que Él vendría y moraría en ellos,
caminaría en ellos y cenaría con ellos y ellos con Él. Y así,
ellos en su día y nosotros en nuestro día (¡bendito
sea el nombre del Señor nuestro Dios!),
comemos y bebemos el pan y el vino celestiales del reino con Cristo.

[.discourse-part]
__Interrogante 2:__ ¿No se ha abusado mucho de estas cosas externas,
y no se ha aparecido el espíritu anticristiano en ellas y las ha magnificado?
Y ciertamente, cuando son magnificadas por ese espíritu no son de Cristo ni para Cristo.

Consideren bien qué era ese patio exterior que Dios les dio a los gentiles,
(ver Apocalipsis 11:2) y cuáles eran la adoración y las ordenanzas del patio exterior.
Consideren si ellas son requeridas por el Señor de los judíos internos,
los que son de la circuncisión en el corazón y han llegado a heredar la sustancia.

[.discourse-part]
__Interrogante 3:__ ¿Tienen alguna virtud estas cosas en sí mismas, sin que Dios las requiera?
¿Puede el agua externa lavar el alma?
¿Pueden el pan y el vino externos alimentarla o refrescarla?
Es cierto que si Dios requiere que un hombre lave su cuerpo con agua, debe sujetarse,
y habrá beneficio para él en esa sujeción. Pero en sí mismo sólo es un ejercicio corporal,
y sin que Dios lo requiera, no sería más que culto voluntario^
footnote:[Culto voluntario es un término usado para referirse a cualquier tipo de adoración
que provenga de los recursos del hombre y que sea de acuerdo a la voluntad del hombre.
Ver Col.
2:23.]
que no le aprovecha para nada.

Ahora, bien, el Señor nunca ha requerido esto de nosotros,
más bien nos ha mostrado la verdadera agua con la que nuestras
almas y cuerpos tienen la necesidad de ser lavados,
y el pan y el vino con los que deben ser alimentados y refrescados.
Al seguir al Señor en concordancia a como Él nos ha guiado y ha requerido de nosotros,
hemos hallado reconciliación, vida, reposo, paz y gozo con nuestro Padre,
y refrescamiento puro proveniente de Él.

[.discourse-part]
__Interrogante 4:__ Con respecto a los deberes,
estos son los dos grandes deberes que se nos han enseñado:
Amar al Señor nuestro Dios con todo nuestro corazón, alma y espíritu,
y amar a nuestro prójimo como a nosotros mismos.
Estos los aprendemos al creer en Aquel que Dios envió,
y al recibir de Él la Semilla de vida.
En el crecimiento de esta Semilla en nosotros, vivimos y somos hechos uno con Él,
y somos partícipes de la capacidad que es de Él.
Porque no alcanzamos esto por obra de nosotros mismos,
sino por la obra de Su poderosa vida en nosotros,
a través de Su misericordia hacia nosotros.
Él nos circuncida, Él corta la enemistad,
Él lleva a sujeción la vieja naturaleza y espíritu en nosotros, y entonces,
brota lo nuevo y somos renovados en eso.
Ahí aprendemos y somos capacitados para amar al Señor, a Sus hijos y a Sus criaturas; sí,
a todo lo que es de Él. Este amor nos constriñe a
obedecer al Señor y a negarlo todo por Él,
para que podamos soportar cualquier cosa a través de Su fuerza (excepto el pecado,
la corrupción, la incredulidad y desobediencia a Él). Sí,
esto nos hace tan tiernos hacia Él,
que preferiríamos separarnos del mundo entero que perder
la integridad y la sujeción de nuestros espíritus a Él,
en la cosa más pequeña que Él requiera de nosotros.
Su verdad (y nuestro testimonio al respecto) en todos los sentidos,
nos es más querida que nuestras vidas y que todos
los goces y placeres de este mundo presente.

A partir de estos dos grandes deberes fluyen muchos otros hacia Dios, tales como:
Temerle a Él con el temor que no es enseñado por los preceptos de los hombres,
sino con el temor que Él escribe en nuestros corazones.
Esperar en Él noche y día en Su templo, es decir, en el lugar santo de Su edificio.
Invocarlo a Él en el movimiento, guía, voluntad y ayuda de Su Espíritu (porque, de hecho,
una vez que aprendemos de Dios, somos enseñados a no orar más según la carne,
ni según la voluntad, sabiduría o manera del hombre).
Ser sensibles a Su bondad y a darle gracias en cada condición.

En esto sentimos Su presencia y aceptación,
mientras el Señor no sea olvidado por nosotros.
Porque cuando comemos y bebemos, caminamos fuera de la casa o nos quedamos en ella,
Lo sentimos cerca, nuestros corazones Lo reconocen, se inclinan ante Él, esperan en Él,
Lo bendicen y alaban Su nombre.
También hablamos palabras sobre Él o para Él con la voz externa,
cada vez que Él las da y las requiere de nosotros.
Pero en verdad, no nos atrevemos a llevar sacrificios propios,
ni a encender un fuego o chispa propia, sino que esperamos el aliento santo,
al Espíritu y poder de nuestro Dios para que Él realice
todo en nosotros y por medio de nosotros.

Pero ahora,
porque no oramos en ciertos momentos establecidos (como anteriormente hacíamos),
ni pronunciamos palabras antes y después de las comidas como antes,
se ofenden con nosotros y dicen que negamos este deber.
No, no.
Nosotros no le negamos a Dios la oración que procede del nacimiento inmortal,
pero decimos y claramente experimentamos lo siguiente: Orar es un don,
y la habilidad del mismo está en el Espíritu de Dios.
"`Pues qué hemos de pedir como conviene,
no lo sabemos,`" ni tenemos el poder en nosotros para orar cuando o según queramos.
Pero en el Espíritu Santo, en Su respiración en nosotros está nuestra habilidad,
y tenemos que esperar en Él, el movimiento y respiración de Su Espíritu.
No debemos orar a partir de nosotros mismos, ni en nuestras propias voluntades o tiempos,
sino en los del Padre.
Verdaderamente,
es algo muy serio hablarle a Dios correctamente en oración. La carne debe
estar en silencio delante de Él y yacer quieta y baja en Su presencia,
para que la fuente pura sea abierta,
la respiración pura respire y la voz pura sea emitida.
Pues Dios no oye pecadores, sino a los que son nacidos de Él y hacen Su voluntad.
Cada alma debe experimentar esto de acuerdo a su medida,
como Cristo lo experimentó en plenitud.
No hay servicio correcto a Dios,
ni realización de ningún deber u ordenanza de adoración a Él correcta,
excepto en la medida de la misma vida y Espíritu con que Cristo le sirvió a Él.

Ahora, yo no sólo reconozco el estado de los judíos en su integridad,
el de los cristianos primitivos en la de ellos,
y lo que el Señor ha hecho irrumpir en nuestro día,
sino también reconozco todas las apariciones del Señor en
los santos mártires y testigos que Él levantó y habilitó,
para que dieran testimonio de Su verdad y en contra
de las prácticas anticristianas de muchos,
a lo largo de toda la noche de la apostasía. También reconozco toda la obra de
Dios en mi propio corazón y en los corazones de otros en tiempos pasados.
Pero el Señor me ha mostrado que hay una gran mezcla
en los deseos y esfuerzos de los hombres tras Él,
y que el espíritu maligno mediante su sutileza a menudo se abre paso en ellos,
y vuelve el mismo celo y fervor de la mente (a través de
prejuicios y malentendidos) contra el Señor y Su verdad.
Ahora bien,
este es un estado muy peligroso y hay algunos (aunque inconscientes) en este estado,
haciendo algo contra el Señor, contra Su Cristo, Su verdad, Su pueblo, por lo cual,
si alguna vez les fueran abiertos los ojos, llorarían amargamente;
pero si sus ojos no les son abiertos, sino que continúan en la luz equivocada (es decir,
por medio de la luz de lo que ellos mismos han reunido, imaginado y concebido),
¿adónde los conducirá, y cuál será su fin?

¡Oh,
si ustedes pudieran oír! ¡Si pudieran temer correctamente! ¡Si pudieran considerar
correctamente! ¡Si pudieran experimentar la vida y poder del Señor cerca de ustedes,
la Palabra de vida cerca de ustedes, tan cerca incluso,
como han experimentado al enemigo y sus tentaciones!
Entonces podrían ser partícipes y experimentar con
gozo la virtud y redención de esta Palabra! ¡Oh,
si alguna vez pudieran mirar correctamente Al que han traspasado y traspasan diariamente,
y que no pueden dejar de traspasar hasta que los juicios justos
del Señor sean derramados sobre la cabeza del transgresor en ustedes!
Entonces el Señor será esperado, temido y sujetado al camino de Sus juicios,
y ustedes sentirán la obra de refinamiento terminada, la escoria quemada,
el templo preparado, la vasija sacada del horno! ¿Luego qué? Bueno,
cuando el Señor haya edificado Sión, preparado Su templo, limpiado Su casa,
¿acaso no aparecerá ahí en Su gloria?
¿No se convertirá en una casa de oración, de oración pura y alabanzas puras?
¿Se ofrecerá ahí algún sacrificio cojo o ciego?
¿No estará ahí, en verdad, la hermosura de la santidad?
¿No será la aparición del Señor más gloriosa de la que alguna
vez sucedió en el templo y ordenanzas bajo la ley?
¿No sentirá cada piedra viva en este edificio al
Dios de vida y poder verdaderamente presente,
y no sólo sentirá la tierra,
sino también los mismos cielos derretidos delante de Él y acabados,
y que nada queda sino la luz pura y la vida del Cordero?

=== Con Respecto al Reposo del Evangelio

¿Qué es el reposo del evangelio?
¿Qué es el día de reposo del evangelio?
¿Es una sombra como lo fue el de la ley?
O, ¿es la sustancia de lo que la ley sólo era sombra?

"`La ley fue dada por Moisés.`" Moisés, por mandato de Dios,
dio bajo la ley las sombras de las cosas celestiales.
"`Pero la gracia y la verdad vinieron por Jesucristo.`"
El verdadero día de reposo, el verdadero descanso, la ley del Espíritu de vida,
en y para los verdaderos judíos,
vienen por Él. La ley de Moisés tenía la sombra de las cosas buenas por venir, es decir,
las cosas buenas del evangelio, el cual saca a la luz la vida e inmortalidad,
y lleva el alma al disfrute y posesión de las cosas celestiales mismas.

El apóstol discute el caso de ambos reposos (Hebreos 4),
tanto del séptimo día de reposo como de la tierra de reposo,
mostrando que ninguno de ellos era la sustancia, sino los descansos que debían pasar.
Él muestra que además de estos, quedaba un reposo, quedaba un día de reposo,
una tierra de reposo, de los cuales, estos dos (tanto el día de reposo externo,
como la tierra de reposo bajo la ley) no eran más que figuras.

¿Para quiénes quedaba este reposo?
Bueno, quedaba para los verdaderos judíos, para los creyentes,
para la circuncisión espiritual en los tiempos del evangelio.
"`Pero,`" dice él, "`los que hemos creído entramos en el reposo.`"
La fe da entrada, la fe del Hijo, la fe que está en el poder,
la fe que es victoria y da victoria sobre el pecado y el mundo,
la que mueve montañas y dificultades que se interponen
en el camino y da entrada al reposo del evangelio.
La fe, que proviene y es del poder de la vida indestructible, somete el pecado,
derriba el yo, recoge al hombre en una nueva semilla,
engendra al hombre en una nueva semilla, hace que él viva y actúe en una nueva semilla, etc.
En la medida que el hombre llegue aquí y dicha vida se levante y tenga poder en él,
en esa misma medida hace que él repose de sus propias obras,
espere a Dios y lo experimente en y a través de Cristo,
para obrarlo todo y ser todo en él.

El apóstol Pedro también habla de este reposo y declara cómo se alcanza, es decir,
al sufrir en la carne.
"`...pues quien ha padecido en la carne,
terminó con el pecado`" (1 Pedro 4:1). Es de la parte carnal,
de los movimientos en la carne de donde se levanta el pecado.

"`Entonces, la concupiscencia, después que ha concebido, da a luz el pecado.`"
Ahora Cristo ha preparado y señalado una cruz, un yugo espiritual para derribar la carne,
el cual provoca gran sufrimiento en la carne para el que
lo pone sobre él. Negar toda impiedad y toda lujuria,
movimiento, deseo y deleite mundano de la mente y naturaleza carnales,
es un sufrimiento doloroso para la parte carnal.
Pero el que ha tomado la cruz por completo,
sentido el minucioso trabajo de ella y sufrido en la carne
la separación y crucifixión de todo lo que es de la carne,
entonces eso que busca hacerlo pecar llega a ser asesinado en él, y él deja de pecar.
Entonces está en el reposo y guarda el reposo plenamente,
y experimenta que el yugo y la cruz que una vez fueron pesados para él,
se han vuelto fáciles y agradables,
al ser desgastada esa parte en él para la que eran dolorosos.

Ahora, el que está en alguna medida liberado,
ese que en alguna medida ha sufrido de esta manera,
encuentra un poco de reposo y en alguna medida puede guardar el día de reposo.
Sí, en la fe,
el bebé más débil (que permanece ahí) no puede evitar guardar el día de reposo,
ofrecer sacrificios y realizar los servicios del mismo al Señor. Porque
la adoración del nuevo pacto no se relaciona con los tiempos y días externos,
sino que es en el Espíritu, en la verdad, en el nombre, poder y sustancia,
en el día que el Señor ha hecho y hace en los espíritus de Su pueblo.
Y esta escritura es experimentada en los que son nacidos del Espíritu,
viven en el Espíritu y caminan según el Espíritu:
"`Porque el pecado no se enseñoreará de vosotros; pues no estáis bajo la ley,
sino bajo la gracia.`"
¿Quiénes no están bajo la ley, sino bajo la gracia?
Bueno, los que son reunidos por la gracia,
los que oyen la voz de Dios en la gracia atrayéndolos y capacitándolos para seguir.
Estos son a los que la gracia cubre y protege del poder y dominio del pecado;
ellos están bajo ella, son refugiados, salvados y preservados por ella.

El que es nacido de Dios no peca, sino que obedece la gracia,
pero el que comete pecado es siervo del pecado y todavía
no ha sido liberado de él por la gracia y poder del Hijo.
Sí,
el Hijo da en Su día esa libertad del pecado y del poder de Satanás.
Los que están fuera de la luz de Su día ni siquiera pueden creer,
pero los que son reunidos en la luz del día y caminan en ella,
experimentan la ley del Espíritu de vida en Cristo
Jesús haciéndolos libres de la ley del pecado y muerte.
¿No ha venido el más fuerte que el hombre fuerte,
con Su ley y poder de una vida indestructible?
¿No manifestará Él Su dominio en el corazón sobre la ley del pecado y muerte?
Sí, conforme la ley del vida es recibida y se le permite entrar, ella opera, conquista,
somete y rebalsa la ley del pecado y muerte.

Y si Dios, por el poder y aliento de Su Santo Espíritu, con Su ley viva y poderosa,
mata el pecado y la muerte en el corazón, ¿los volverá a revivir?
No, no; después de esto están en verdad muertos,
y el reino y reinado de Cristo son experimentados en dicha alma.
Entonces, el nacimiento de vida es experimentado.
El niño varón es experimentado gobernando con vara de hierro,
haciendo añicos todos los movimientos y tentaciones
para corrupción y todo lo que quiera profanar,
para que no puedan entrar en la mente.
La mente es guardada continuamente en la paz pura,
en el gozo inefable y en el reposo del Hijo.
Ahí esto es tan verdaderamente experimentado internamente,
como alguna vez fue disfrutado o esperado por los judíos externamente,
que el cuerno de salvación del Señor rompe todos los cuernos de los opresores.
Él da reposo al alma de los enemigos alrededor, para que ya sin temor de ellos,
le sirva al Señor en santidad y justicia todos los días de su vida.

Hay muchos buenos deseos en muchas personas,
pero también hay un gran error de juicio y un deambular
para arriba y para abajo de la verdad,
por falta de lo que es capaz de mantener la mente
en el Señor y guiarla en el camino correcto.
Algunos corren a esas montañas y sacrifican ahí,
otros corren a aquella colina y ofrendan ahí,
pero muy pocos conocen el verdadero lugar de reposo o el lugar de la verdadera adoración.
En estos errores ellos no pueden experimentar aceptación del Señor. ¡Oh,
si ellos conocieran lo aceptable,
la manera aceptable de adoración y pudieran aparecer delante del Señor
ahí! Entonces podrían empezar en eso que es sustancial (en el Espíritu,
vida y poder del evangelio),
y llegar a heredar y sentarse en lo que es sustancial y eterno.
