== Capítulo 3. Una Defensa de la Verdad Santa y del Pueblo Santo de Dios

Lo siguiente es la respuesta a los pasajes principales
de una carta que recibí y que respondí,
antes de mi encarcelamiento en Reading Jail (donde
he estado encarcelado por más de un año y medio,
sin haber quebrantado ninguna ley o dado razón de mi parte).
Estoy comprometido en espíritu a dar una respuesta a esto,
y a ofrecerles a otros lo que el Señor me ha dado.

[.discourse-part]
Objeción: Él objeta en su carta,
que nosotros negamos la redención por la sangre de Cristo.

[.discourse-part]
Respuesta: ¡Oh! ¿Cómo justificará él esta acusación ante Dios?
¡Porque nadie reconoce tan correcta y plenamente
la redención mediante la sangre de Cristo,
como el Señor nos ha enseñado a hacerlo!
Pues nosotros en verdad reconocemos la sangre de Cristo,
tanto externamente como internamente; tanto como fue derramada en la cruz,
así como es rociada en nuestras consciencias.
Nosotros experimentamos la virtud limpiadora de la
sangre en el pacto eterno y en la luz que es eterna,
fuera de la cual, los hombres sólo tienen una idea de ella,
pero no la experimentan o conocen verdaderamente.

[.discourse-part]
Objeción:
Él alega que la justificación es un acto único de
gracia que Dios pasa gratuitamente sobre el hombre,
acto que lo declara justo.

[.discourse-part]
Respuesta: El que verdaderamente experimenta la salvación en Cristo Jesús,
la experimenta como un acto continuo de gracia.
La gracia aparece al alma, la gracia enseña, la gracia capacita,
la gracia obra un cambio en el corazón de su estado natural y sin gracia.
Luego,
la gracia (o Dios mediante Su gracia en y a través de Jesucristo)
perdona los pecados que fueron cometidos antes.
Porque aunque el Señor me visita con vida,
me vivifica por ella y opera un cambio en mi corazón y estado,
aún sigue siendo Su misericordia aceptarme y pasar por alto (por amor de Su nombre),
mi deudas y transgresiones anteriores contra Él. De hecho,
el nuevo pacto es en su totalidad, un pacto de gracia y misericordia.
La dádiva de Cristo, la atracción de la mente hacia Él,
la aceptación y justificación que están en Él, etc., son obras de gracia y misericordia.
Por tanto,
el Israel espiritual puede correctamente cantar la
canción en la tierra de santidad y redención:
"`¡Oh, alaben al Señor!
Porque Él es bueno y Su misericordia es para siempre!`"

[.discourse-part]
Objeción: Él pregunta: "`¿Esperan ustedes cumplir la ley mediante su obediencia?`"

[.discourse-part]
Respuesta: Nosotros no consideramos que la ley de Moisés, que fue dada al judío externo,
sea la dispensación del nuevo pacto, o la ley del Espíritu de vida en Cristo Jesús. Pero,
es cierto que la justicia de la ley es cumplida en aquellos que están en el nuevo pacto,
y que tienen la ley de Dios escrita en sus corazones,
Su temor puesto ahí (el que evita que se separen de Él),
y Su Espíritu colocado dentro de ellos para hacer que caminen
en Sus caminos y guarden Sus estatutos y juicios.
Estos viven en el Espíritu y no caminan según la carne, sin embargo,
no magnifican ni afirman su propia obediencia (ni la llaman su propia justicia),
sino que reconocen a Aquel de quien proviene su obediencia.
Pues en la medida de Su gracia y verdad viva, el alma es una con Él,
y todo lo que Él es y todo lo que Él ha hecho, les pertenece a ellos.
Él mismo es la justicia de todo lo que está en Él,
y los que permanecen en Él participan de Su justicia día tras día,
la cual fluye en ellos como un arroyo.

Parece que él pasa algunas cosas (las cuales le hablé en tierno
amor y peso de espíritu) como el mero juicio del hombre en su día,
pero que tenga cuidado, porque cuando comparezca ante Dios,
entonces encontrará que era el juicio del Espíritu de Dios
en la luz de Su día. Este día es interno y espiritual,
al que los creyentes deben acercarse y que se aproxima a cada corazón,
mientras la noche se consume y pasa.
Todos los verdaderos cristianos y creyentes deben esperar que la noche desaparezca,
que el día esclarezca y el lucero de la mañana salga en sus corazones.

En cuanto a sus comentarios acerca de la voluntad de Dios hecha en el cielo,
¿acaso no existen aquí en la tierra los que viven en el cielo?
¿Acaso no están aquí aquellos cuya ciudadanía está en el cielo, es decir,
aquellos que experimentan la santa verdad de Dios,
que son remontados por encima del espíritu de este mundo,
habitan en el Santo Espíritu de Dios y caminan en la luz como Dios está en luz?
El infierno no está lejos de los malvados,
ni el cielo está lejos de los que son renovados en el espíritu de sus mentes,
los que experimentan la desaparición de las cosas viejas y la nueva creación en Cristo.
¡Oh, si él pudiera mirar y ver cómo ha torcido esas escrituras (Salmo 85:9-11;
Isaías 4:2; Efesios 2:6) según sus propias imaginaciones!

[.discourse-part]
Objeción:
Él alega que nosotros consideramos toda religión y profesión cristiana en el mundo,
por debajo de nosotros y carnal.

[.discourse-part]
Respuesta: Ciertamente nosotros magnificamos la verdad, la vida, la unción,
la aparición espiritual e interna de nuestro Señor Jesucristo,
a la cual hemos sido vueltos.
Y todo otro conocimiento, fe, profesión y religión que no se levante de esto,
no podemos evitar llamarlo carnal.
Porque el Espíritu iluminador del Señor nos ha dado este testimonio para
declarar contra todos los profesantes muertos y teóricos de esta edad,
que edifican a partir de la letra de las Escrituras (o más bien,
de sus comprensiones de la letra) fuera de la vida.
Todos estos celebran el nombre de Cristo de "`fundamento`"
y "`piedra angular,`" pero rehúsan,
rechazan, niegan y se vuelven de la piedra angular misma.
No tienen ni la habilidad ni la paciencia para probar lo que Él es en Su aparición pura,
preciosa, viva, poderosa y gloriosa, en la luz espiritual de Su día interior,
después de la larga y espesa oscuridad de la noche previa.
¡Y ay de nosotros si no testificáramos así! Pues es por
esta causa que hemos nacido y fuimos traídos al mundo,
para testificar la aparición presente de nuestro Dios y Su Cristo
en este día. ¡Gloria a Aquel que nos ha llamado y escogido,
y nos ha hecho (en una verdadera y preciosa medida
y grado de Su propia vida pura) fieles en esto!

[.discourse-part]
Objeción: Entonces él objeta como sigue:
"`En lugar de palmearnos en la espalda y ministrarnos en nuestro viaje,
ustedes obstruyen nuestra marcha y caen sobre nuestra retaguardia.
En lugar de servir al reino de Cristo,
niegan los primeros principios del evangelio y descartan por completo
la esperanza de la segunda aparición y reino de Cristo,
no admitiendo ningún otro Salvador o ningún otro reino,
además de la Semilla o luz en ustedes mismos.`"

[.discourse-part]
Respuesta: "`Dios es luz, y no hay ningunas tinieblas en él`" (1 Juan 1:5);
este es el mensaje del evangelio.
Cristo, que es uno con el Padre,
es uno y la misma luz con Él. Nosotros confesamos que no buscamos a otro además de Él,
ni otro reino además del reino que es revelado en Él,
porque el reino que es revelado y manifestado en y por Él, es el reino espiritual,
eterno y perpetuo, y no hay otro.
No decimos que la plenitud o la gloria completa del reino,
esté ya revelada o sea disfrutada por nosotros; no.
Nosotros confesamos no tener más que las arras en comparación, sólo una medida,
una proporción. Pero esta medida es de la misma naturaleza y género de la plenitud misma,
y todo lo que es de Cristo, de Su Espíritu, de Su naturaleza,
tiene el poder de salvación. La medida de Su gracia que aparezca en cualquier corazón,
por pequeña que sea, trae salvación con ella.
El toque más pequeño de Su dedo, tiene vida pura y virtud salvadora en él. Sin embargo,
esta medida no es distinta o está separada de la plenitud, por lo tanto no es otra,
aunque no sea la plenitud.

En cuanto a negar los primeros principios del evangelio, eso es propio de ustedes.
Porque, ¿no niegan ustedes esa luz que es el fundamento de todo,
en la que y por la que todos los misterios del reino de Dios son vistos?
Y sin esta luz,
¿no establecen ustedes un conocimiento teórico e intelectual de su propia concepción,
comprensión y compilación de la letra (aunque nadie puede entender la letra,
excepto cuando entra y permanece en la luz)?
Esto nosotros lo hemos experimentado anteriormente,
porque nosotros estábamos adivinando e imaginando cosas con respecto a la letra,
hasta que fuimos vueltos a la luz del Espíritu de Dios.

En cuanto a descartar la esperanza del reino de Cristo,
el Señor sabe que está lejos de nosotros.
Porque nosotros mismos Lo bendecimos por lo que ya ha aparecido de Su reino,
y aguardamos y esperamos una mayor y más plena aparición de este.
Sin embargo, confesamos lo siguiente: No esperamos otro Espíritu, otro Cristo, otra luz,
otra vida, otro poder ni otro reino, además de Aquel que ya ha aparecido.
Pues Cristo es nuestro Rey y reino, ambos,
y la más pequeña medida recibida de Su vida y Espíritu (comprada con la pérdida de todo,
y así adquirida y poseída),
no es menos que la perla de gran precio y el reino celestial para el que lo disfruta.

De hecho, es muy importante experimentar ese trono, al que el trono de David señalaba,
y a Cristo sentado en él. Su reino, Su trono,
no son de esta naturaleza externa y mundana, sino de la interior y espiritual,
y Su trono está en Su reino y templo, donde Él reina y es adorado.
Él que llega a experimentar a Satanás vencido y expulsado,
también experimenta a Cristo dentro y sentado en Su trono.
¡Oh, si los hombres renunciaran a su sueño acerca de la gloria celestial,
y vinieran a este reino, mediante la guía del Espíritu de Dios,
donde la gloria es revelada.

[.discourse-part]
Objeción: Él dice que Cristo va a aparecer sin relación con el pecado para salvación.

[.discourse-part]
Respuesta: Se lo concedo,
pero ¿cuándo y cómo? ¿No aparece Él internamente sin relación con el pecado para salvación,
a los que han esperado, se han apresurado y llegado al día interior?
¿No aparece Cristo internamente sin relación con el pecado para salvación,
en el día de Su propio Espíritu?
¿No es sacada a la luz la gloriosa salvación del evangelio en el día del evangelio?

[.discourse-part]
Objeción: Él añade, "`¿Están los logros de ustedes más allá de los de Pablo,
quien encontró que en él (es decir, en su carne) no moraba el bien,
y que el deseo de su carne era contra el Espíritu para que no pudiera hacer lo que quería?`"

[.discourse-part]
Respuesta: Por un tiempo Pablo experimentó dicho estado, en el que se sentía carnal,
vendido al pecado.
En ese estado él no encontraba cómo hacer lo que era bueno, sino lo que odiaba;
que la ley del pecado era fuerte (en sus miembros) contra la ley de vida en su mente.
Él llama este estado, el estado de esclavitud a la ley del pecado en sus miembros,
y un estado miserable.
(Romanos 7:23-24)

Pero, ¿nunca experimentó Pablo otro estado?
¿Nunca experimentó la virtud y poder del nuevo pacto, es decir,
la ley del Espíritu de vida y el poder en esta,
liberándolo de la fuerza y esclavitud de la ley del pecado en sus miembros?
Juan habló de hombres jóvenes que eran fuertes y que habían vencido al maligno.
(Leer 1 Juan 2:13) ¿No logró Pablo mismo ese estado?
Él mandó a otros que fueran fuertes en el Señor y en el poder de Su fuerza;
les mostró cómo resistir en ella y así vencer.
¿No lo experimentó y atestiguó él mismo?
Él dijo que él había peleado la buena batalla y que era más que vencedor.
¿Era él entonces un esclavo de la ley del pecado en sus miembros?
Él dijo que él lo podía todo en Cristo que lo fortalecía. ¿No era este
un estado diferente de aquel en el que descubrió que sólo podía desear,
pero no hacer, el bien que deseaba, sino sólo el mal que odiaba?
¡Bendito sea el Señor,
que muchos experimentan hoy un mayor estado de redención y liberación del pecado,
que ese estado de esclavitud que Pablo expresa ahí,
bajo el cual antes gemía y se quejaba!
De hecho,
Pablo no estaba en ese estado de esclavitud cuando
escribió la epístola a la iglesia en Roma,
sino que conocía el dominio de la gracia sobre el pecado,
y mandó que la iglesia se sujetara a la gracia y no le diera lugar al pecado,
sino que presentaran sus miembros como siervos a la justicia para santidad.
(Capítulo 6)

En el otro lugar,
donde él habla de la carne que desea contra el Espíritu
y el Espíritu contra la carne (Gálatas 5:17),
él ahí no habla de sí mismo, sino de los gálatas,
quienes estaban en un estado débil y bajo,
y habían caído del Espíritu y poder del evangelio,
por haber permitido que entrara lo que era contrario a este.
Y entonces, él se esfuerza por reunirlos de nuevo en el Espíritu,
y les pide que vivan en el Espíritu y anden en el Espíritu,
para que no satisfagan los deseos de la carne.
Porque en el nuevo pacto, el hombre es enseñado en la virtud y poder del pacto,
a fin de que aprenda día a día y crezca a diario fuera del engaño hacia la verdad,
hasta que llegue a ser un verdadero israelita, en quien no haya engaño. Y así,
en esta guerra espiritual,
la casa de Saúl se va haciendo más y más débil y la de David más y más fuerte,
hasta que el reino de Saúl es finalmente derrocado y completamente destruido,
y el reino de David establecido en justicia por los siglos de los siglos.
Entonces Jerusalén, el edificio santo, la ciudad del pueblo vivo,
la ciudad de justicia (la habitación de justicia y monte de santidad) es conocida,
y es experimentada como una habitación tranquila,
en la que hay paz en todas sus fronteras.
Entonces la mente es plenamente fijada en el Señor en todas las situaciones,
y Él la mantiene en perfecta paz.
Por nada está afanosa,
sino que da a conocer sus peticiones delante de Dios en toda oración y ruego,
con acción de gracias.
Y la paz de Dios que sobrepasa todo entendimiento,
guarda el corazón y la mente a través de Cristo Jesús.

Sin ninguna duda,
el apóstol había aprendido (cuando enseñaba a otros) a estar contento
en cualquiera que fuera su situación. Él sabía cómo vivir humildemente,
cómo tener abundancia, etc.
¡Cuán glorioso estado! ¡Qué estado puro, de vida pura,
en el corazón! Y qué tal si añadiera: ¡Qué perfecto estado!
El apóstol Santiago dice: "`Mas tenga la paciencia su obra completa,
para que seáis perfectos y cabales,
sin que os falte cosa alguna`" (Santiago 1:4). Cuando Pablo había aprendido así a Cristo,
de modo que la abundancia no podía enaltecerlo,
ni ninguna necesidad abatirlo o hacer que se quejara o desconfiara,
¿qué le hacía falta de ese estado perfecto?

[.discourse-part]
Objeción: Él afirma:
"`De ustedes se han levantado hombres que han alzado audazmente
el estándar contra las verdades selladas y experimentadas del evangelio,
más que cualquier otro de los que yo haya leído u oído.`"

[.discourse-part]
Respuesta:
Nosotros somos un pueblo (muchos de nosotros) que ha atravesado
grandes angustias por falta del Señor nuestro Dios,
y hemos esperado y anhelado mucho Su aparición viva y poderosa.
En cuanto a mí, lo que puedo decir es,
que si esta aparición del Señor no hubiera sido en el poder y en la evidencia y demostración
de Su Espíritu en mi alma (alcanzando y respondiendo a eso en mí que era de Él),
no habría podido reconocerla,
pues yo estaba profundamente celoso de ella y prejuiciado contra ella.
Pero desde que mi mente se ha vuelto a la Palabra pura de vida, es decir,
a la Palabra que estaba en el principio (lo digo como en la presencia del Señor),
Esta ha tenido efectos singulares en mi corazón. La luz me ha escudriñado tanto,
como nunca antes había sido escudriñado bajo todas mis anteriores profesiones del cristianismo.
El Señor me ha dado un discernimiento verdadero y puro de las cosas de Su reino,
en la luz que es verdadera y pura.
Me he encontrado con sorprendentes vivificaciones de Su Espíritu,
y la fe que está en Su poder celestial y da victoria y dominio
en Él. El amor que me ha dado no es un concepto,
sino el que brota de Su circuncisión de mi corazón y es consistente con Su naturaleza,
la cual mana pura y naturalmente hacia Él,
hacia los de Su imagen y hacia todas sus criaturas.
De hecho, este amor brota hacia los que por amor de Su nombre, me tienen por enemigo.

Yo también podría mencionar la paciencia y fidelidad a Su verdad,
con el espíritu de longanimidad,
del que testifica Su Espíritu en mí que es de una
naturaleza muy particular (junto con otras cosas).
Yo no estoy solo en esto, ni soy el principal, sino que tengo muchos iguales.
En realidad,
hay muchos que me superan por mucho en la imagen celestial y divina de mi Padre.
Los frutos están en concordancia con la raíz de vida en nosotros,
y así son reconocidos por todo que nos miran con el verdadero ojo,
el ojo que Dios da y abre.

Ahora, el mismo que ha trabajado internamente en nosotros,
también ha requerido algunas conductas y expresiones externas de nosotros.
Las cuales son tontas y débiles para el ojo de la sabiduría del hombre,
pero han sido escogidas por Dios para esconder la gloria de esta vida,
del ojo que no puede discernirla, sino que desprecia el día de las cosas pequeñas.^
footnote:[Penington aquí se refiere a algunas formas externas
a las que los cuáqueros se sintieron guiados a vestir,
hablar y vivir,
contrario a las orgullosas y exaltantes costumbres y tradiciones del hombre de su época.
Aunque estas cosas externas jugaron un papel en el testimonio de los cuáqueros,
contra el orgullo y la religión centrada en el hombre de su tiempo,
de ninguna manera eran el corazón de la fe de ellos,
ni lo que principalmente los distinguía de otros profesantes cristianos.]
Aunque esta es la más pequeña parte de nuestra religión
(aún así nos sometemos a ella porque es de Dios,
a quien no nos atrevemos a desobedecer en lo más mínimo),
el espíritu que es contrario a Dios nos menosprecia,
como si esto fuera todo o al menos lo principal en lo que diferimos de otros.
Pero tristemente, nosotros diferimos de ustedes en lo principal.
Pues nosotros sostenemos nuestra religión tal como la recibimos de Dios,
en la luz y vida de Su Espíritu.
Ustedes, sin embargo, sostienen la de ustedes tal como la comprenden de la letra.
Cristo es nuestra roca y fundamento, tal como es internamente revelado,
pero Él es el de ustedes sólo como es externamente concebido.
Nosotros creemos con la fe que es de la naturaleza de Aquel en quien creemos,
cuya fe es poderosa a través de Dios y obra sobre todos los poderes de las tinieblas,
dando victoria sobre todos ellos.
Pero ustedes creen con una fe que estima la victoria
imposible mientras estemos en el mundo.
Y así como nuestra raíz es diferente,
así también todo lo que crece en nosotros difiere de lo crece de la de ustedes.

Para cerrar agregaré unas pocas palabras de Filipenses 3:3,
"`Porque nosotros somos la circuncisión,
los que en Espíritu servimos a Dios y nos gloriamos en Cristo Jesús,
no teniendo confianza en la carne.`"
Es precioso experimentar esta escritura cumplida en el corazón,
experimentar eso que circuncida y corta internamente
el prepucio del corazón. Porque este prepucio,
en efecto, está sobre el corazón y lo cubre,
hasta que es cortado por la aparición interna de la vida y del poder del Señor Jesucristo,
revelado internamente.
Entonces, cuando esto es hecho, uno puede verdadera y conscientemente decir,
que es un judío en el interior.
¿Cómo es eso?
¿Cómo se puede probar esto?
¡Porque se está circuncidado internamente! ¡Porque se ha
sentido ese cuchillo interior que circuncida el corazón,
se ha soportado el dolor y el corte, y que ha sido circuncidado por este!
Lo que se interponía entre uno y el Señor es cortado, el velo es quitado,
la terquedad e independencia de Dios es removida, la pared de separación es derribada,
y ahora se está en verdadera unidad de Espíritu y comunión con Dios; es decir,
con el Padre y el Hijo, en el único Espíritu Santo donde son Uno.

Ahora él puede postrarse delante del Padre de nuestro
Señor Jesucristo y adorarlo en Su propio Espíritu,
día a día, en la vida nueva y fresca.
Ahora el regocijo está en Cristo Jesús, a quien el Padre ha enviado,
tanto externamente en un cuerpo de carne para cumplir la santa voluntad,
como internamente en Su Espíritu y poder al corazón,
para destruir las obras del diablo ahí. Él no puede dejar de regocijarse,
tanto en lo que el Señor hizo en Su cuerpo de carne por uno,
como en lo que hace mediante Su Espíritu y poder en él.

¡Oh, bendito sea el Señor porque lo siento cerca! ¡Siento a Su Espíritu cerca,
Su vida cerca, Su poder cerca, Su virtud pura cerca, Su sabiduría santa cerca,
Su justicia cerca, Su redención cerca; pues Él es mi roca,
mi fuerza y mi salvación día a día! No tengo confianza en la carne,
en lo que soy ni en lo que puedo hacer según la carne, no;
mi confianza está en Aquel que me ha debilitado, me ha despojado,
me ha empobrecido y me ha llevado a nada en mí mismo,
para que yo pueda ser todo lo que soy en Él,
y lo encuentre a Él hecho todo para mí. Él es mi paz, Él es mi vida, Él es mi justicia,
Él es mi santidad, Él es la imagen en la que soy renovado.
En Él está mi aceptación para con el Padre.
Él es mi abogado, Él es mi esperanza y gozo para siempre.
Él ha destruido en mí lo que era contrario a Dios y lo mantiene subyugado para siempre.
Él es mi Pastor,
Su brazo me ha recogido y me rodea día a día. Yo reposo bajo la sombra de Sus alas,
de las que la virtud sanadora de Su salud salvadora cae sobre mi espíritu día a día. ¡Oh,
no puedo expresarle a ningún hombre lo que Él es para mí! Pero,
¡bendito sea el Señor porque lo siento cerca, su justicia cerca,
Su salvación a diario revelada delante del ojo que Él ha abierto en mí,
en esa consciencia verdadera y viva con la que Él me ha vivificado!

Y ahora, usted que tiene altos conceptos,
y un conocimiento rico e intelectual con respecto a estas cosas, pero no a la cosa misma,
la vida misma, el Espíritu mismo, el pacto nuevo y vivo,
y la ley de vida misma en la que sólo Cristo es vívidamente revelado, ¡cuán pobre,
miserable, ciego y desnudo está,
en medio de todo su conocimiento tradicional y pretendidas experiencias!

Venga ahora y esté en silencio un momento,
y termine con la amargura de espíritu y con la injuria de la obra
y pueblo del Señor. Porque el Señor conoce y hará manifiesto,
tanto quienes son Suyos como quienes no.
Todas las piedras vivas son de Él,
pero los grandes profesantes de las palabras de las Escrituras,
que están sin el Espíritu y vida de las Escrituras, no; nunca lo fueron,
ni nunca serán reconocidos por Él.

Venga y aprenda de Dios a distinguir por medio de Su vida, por Su unción,
por la regla eterna e infalible, y no por _palabras sin vida._
Aquí es donde ha estado el gran error y la gran equivocación
por todas las edades y generaciones.
El gran engaño ha estado por mucho tiempo (y sigue estándolo),
en una forma de piedad sin poder.
Asegúrese de no estar engañado de esta manera, porque si usted pierde el poder que salva,
no puede evitar perecer para siempre.
¿Y qué si la aparición del Espíritu y poder de nuestro Señor Jesucristo
internamente (que es la que salva) es tan extraña para sus sentidos,
entendimiento y juicio,
como lo fue Su aparición externa para el pueblo de
los judíos? ¡Tenga cuidado de los espíritus de ellos,
guárdese de sus juicios!
Porque ellos juzgaron según la apariencia de las cosas,
las cuales imaginaron y concibieron a partir de las Escrituras,
pero no juzgaron con el juicio verdadero y justo,
el que sólo los hijos de la verdadera sabiduría pueden.

=== El Amanecer del Día Espiritual

Hay cuatro o cinco cosas muy preciosas que fueron generalmente
experimentadas entre los verdaderos cristianos,
en los días de los apóstoles, las cuales están mencionadas juntas en Hebreos 6:4-5.

[.numbered.emphasized]
Primera: Ellos fueron verdaderamente iluminados.

Los ministros del evangelio fueron enviados por Cristo,
para que volvieran a los hombres de las tinieblas a la luz,
y del poder de Satanás a Dios.
(Hechos 26:18; 1 Juan 1:5) Ellos fueron fieles en sus ministerios, y de verdad,
volvieron a los hombres de las tinieblas y poder de Satanás,
a la luz del Santo Espíritu de Dios.
La iglesia fue iluminada por Él y recibió poder a través de Él,
así llegaron a ser hijos de la luz y a caminar en la luz como Dios está en luz.

[.numbered.emphasized]
Segunda: Ellos gustaron del don celestial.

¿Cuál es el don celestial que Cristo les da a los
que vienen a Él y se convierten en Sus ovejas?
Les da vida, vida eterna.
(Juan 10:27-28) Él los saca de la muerte y les da
un sabor y degustación de la vida que es eterna.
Esto fue de lo que los apóstoles testificaron, es decir,
de la vida que fue manifestada en el cuerpo de carne de nuestro Señor Jesucristo.
(1 Juan 1:2) A los que se vuelven de las tinieblas a Su luz,
Él les da a degustar la misma vida.

[.numbered.emphasized]
Tercera: Ellos fueron hechos partícipes del Espíritu Santo.

El evangelio es el día en que la semilla espiritual brota,
y se derrama el Espíritu Santo sobre ellos.
¡El estado de la ley era un estado de siervos; el evangelio es un estado de hijos!
Puesto que los verdaderos creyentes en Cristo son hijos,
Dios envió al Espíritu de Su Hijo a los corazones de ellos para que clame: "`Abba,
Padre.`"

[.numbered.emphasized]
Cuarta: Ellos gustaron de la buena Palabra de Dios.

Es decir, de esa Palabra que estaba en el principio del mundo,
la que es injertada en los corazones de los que verdaderamente creen;
la Palabra capaz de salvar el alma.

[.numbered.emphasized]
Quinta: Ellos gustaron los poderes del siglo venidero.

El poder de la vida indestructible, del que Cristo es Ministro,
y según el cual Él ministra vida en ese templo santo, verdadero, vivo,
interno y espiritual,
el que Él establece y erige para morada de Dios en Su propio Espíritu.

Ahora, estas cosas se han perdido grandemente,
a lo largo de la apostasía y de la noche de oscuridad
que ha venido sobre el estado cristiano.
Porque no ha habido nadie capaz de volver al pueblo
hacia esa luz a la que los apóstoles dirigieron.
Nadie ha podido decirles a los hombre dónde brilla la luz,
ni dónde deben expectarla ni esperarla.
Nadie ha sido capaz de dirigir a los hombres a la Semilla del reino interior,
a la Palabra de fe, la Palabra del reino que está cerca, en el corazón y la boca.
Mucho menos capaces aun,
de instruir a los hombre en cómo podrían conocerla
y distinguirla de todas las otras semilla,
y cómo distinguir la voz del Pastor de todas las otras voces.
Sucedió, entonces, que aunque a veces Dios visitaba y abría los corazones de los hombres,
calentándolos un poquito mediante el aliento que salía de Él mismo,
ellos aún no sabían cómo volverse al Señor y esperar en Él,
para ser preservados en el don y medida de Su propia gracia.
Por tanto, la buena Semilla ha sido en gran parte robada de ellos,
y el edificio que ha sido levantado en ellos no ha
sido el edificio de vida según el Espíritu,
sino el edificio de sabiduría o conocimiento de las cosas de Dios según la carne.
Y así,
el edificio que ha sido levantado en los espíritus de los hombres ha sido Babilonia,
en lugar de Sión.

Sin embargo, el Señor ha tenido un remanente durante toda la apostasía,
que ha experimentado el verdadero engendramiento de vida,
y que en alguna medida ha tenido un sentido y ha gustado las cosas celestiales.
Estos han llorado en busca de ese estado que una vez fue disfrutado,
y han sentido la falta de este al viajar de monte a collado buscando su lugar de reposo,
acerca del cual nadie ha podido informarlos correctamente.

Pero ahora, por el bien de estos, ¡Dios finalmente ha aparecido! "`¿Cómo ha aparecido?`"
alguien puede preguntar.
Bueno: El que es la luz ha aparecido internamente,
haciendo que Su luz brille internamente, haciendo que Su vida brote internamente,
para que el que es la luz, el que es la vida, el que es la verdad,
sea sentido y experimentado en Sus propias visitas, irrupciones y apariciones internas.
Porque Dios es Espíritu y Su aparición es espiritual, Su día es espiritual,
Su reino es espiritual, Su luz es espiritual, Su vida es espiritual,
Su lucero de la mañana es espiritual;
y así Su día amanece y Su lucero se levanta en el corazón.

De esta manera, la Aurora de lo alto nos visitó,
a nosotros los sentados en tinieblas y en la región de sombra de muerte.
Aquí nos hemos encontrado con lo que los apóstoles se encontraron,
con la misma luz de vida, el mismo Espíritu y poder iluminador,
hemos sido iluminados por Él y hemos gustado del mismo don.

La misma gracia que se les apareció y los enseñó a ellos,
también se nos ha aparecido y nos ha enseñado,
y de ella hemos aprendido las mismas lecciones,
en el mismo pacto de vida en el que ellos aprendieron.
Ahora nosotros podemos poner nuestro sello al testimonio de ellos,
en el mismo Espíritu en que lo dieron,
y testificar de la misma vida eterna y del mismo aceite santo y unción,
porque nuestros ojos han sido abiertos y mantenidos abiertos por Él. Y
aunque hay grandes disputas acerca de nuestro testimonio en nuestros días
(y los actuales profesantes se levantan contra nosotros,
tal como los antiguos profesantes lo hicieron contra ellos), todavía,
si algún hombre llega correctamente a distinguir en sí mismo entre
lo que Dios engendra en el corazón y todos los otro nacimientos,
pronto confesará que nuestro testimonio es de Dios y es
dado en la autoridad y por la comisión de Su propio Espíritu.
La verdadera sabiduría es justificada por los hijos que nacen de ella,
aunque el nacimiento carnal no la reconozca (ni pueda).
El nacimiento carnal puede reconocer las dispensaciones
anteriores (según el relato de ellas en la letra),
pero no puede reconocer la vida ni el poder del presente don.

Yo he experimentado mucho rompimiento en mí por la poderosa mano del Señor,
y una separación de mucho (aunque no demasiado) por amor de Cristo.
El Señor ha traído el día de angustia y de juicio interno sobre mi corazón.
Él se ha levantado para sacudir terriblemente la parte carnal en mí (sí,
y qué si dijera que los poderes del cielo también han sido sacudidos),
para hacerme capaz de recibir e introducirme en ese reino que no puede ser sacudido.
Y ahora, lo que Dios ha sacudido y eliminado de mí, veo que otros lo están edificando,
porque piensan que nunca será sacudido en ellos.
Pero los tales no conocen el día del Señor, ni el terrible escrutinio de Su luz pura,
ni la operación de Su poder, el cual no perdonará en uno lo que ha reprobado, condenado,
sacudido y volcado en otro.
El que conoce a la Piedra viva interna y llega a Él como una piedra viva,
y es edificado sobre la revelación de Su Espíritu,
vida y poder (revelado internamente contra el poder de las tinieblas), no es engañado.
Todo el que edifica de otro modo (quiero decir,
sobre un conocimiento externo con respecto a Cristo y no sobre la vida interna),
su edificio no será capaz de permanecer de pie en el día del Señor. Deseo
que ellos tengan un sentido de esto a tiempo y que no perezcan para siempre,
sino más bien, que experimenten la vida y el poder de nuestro Señor Jesucristo,
el cual redime y preserva fuera del estado que lleva
a la muerte por los siglos de los siglos.
Amén.
