== Capítulo 4 La Verdad Desnuda Ofrecida a Modo de Preguntas y Respuestas

Pregunta: ¿Qué hace la luz internamente en los corazones de los que la reciben,
creen en ella y se rinden a ella?

Respuesta:
Hace todo lo que es necesario hacer desde la salida del
alma del Egipto espiritual hasta la tierra de reposo,
y todo lo que es necesario para su crecimiento y preservación ahí.

Primero, ilumina.
Muestra lo que es malo y también lo que es bueno, según la medida y proporción de ella,
y de acuerdo a cómo Dios la hace brillar en el corazón.
Pone al descubierto el misterio de las tinieblas,
el misterio de la impiedad, el misterio de la iniquidad,
el misterio del engaño en todas sus misteriosas obras;
pues nada se esconde de la luz de Aquel a quien tenemos que dar cuenta.
También descubre el misterio de la piedad, el misterio de la santidad,
el camino puro y el mandamiento de vida,
y le da a todos los verdaderos creyentes la experiencia
de que "`su mandamiento es vida eterna.`"
No hay nada que el corazón desee conocer de Dios,
que esta luz no haga manifiesto a su debido tiempo.
Ella abre el misterio mismo de las Escrituras,
da el correcto entendimiento y aplicación de las promesas,
y cumple sus profecías en el corazón.

Segundo, no sólo manifiesta lo bueno y lo malo,
sino que también inclina la mente a escoger lo bueno y a rechazar lo malo.
Ella aleja de lo malo y atrae hacia lo bueno, sí,
y hace que el alma se ofrezca voluntariamente en el día de Aquel que es la luz,
aparece en la luz y revela Su poder ahí. Hay una calzada,
un camino (mencionado en Isaías 35:8) llamado '`camino de santidad,`' el cual
el impuro no puede discernir ni transitar por él. Pero la luz del Señor Jesucristo,
la medida de gracia y verdad con la que Él alumbra a los hombres,
manifiesta y guía en este camino de manera tal,
que los que son enseñados y guiados por Él caminen en él y no se extravíen.

Tercero, ella dispersa las tinieblas y quebranta el poder del enemigo,
haciendo que el alma sea una con Aquel que es todo poder y lo da abundantemente.
En realidad,
se les da poder a los hijos de la luz para que lleguen a ser hijos en la luz,
se les da poder para que lleguen a ser reyes y sacerdotes para Dios,
se les da poder para que reinen en el dominio de Su vida, en el dominio de Su verdad,
sobre el pecado, sobre la muerte, sobre el engaño,
y para que ofrezcan sacrificios santos y vivos a Dios.

¿Qué diré? La luz es una con Cristo; es de Su Espíritu y naturaleza celestiales.
Abre camino para Él, guía a Él, llena de Él,
lleva a la unidad y comunión tanto con el Padre como con el Hijo,
donde abundan la paz que sobrepasa el entendimiento,
el gozo inefable y la plenitud de gloria.
Este es el mensaje del evangelio: Que Dios es luz.
Los que están reunidos en esta luz y permanecen en ella,
están reunidos y permanecen en unidad y comunión con el Padre y con el Hijo.

David tenía una gran consciencia y una gran experiencia
de esta luz del Espíritu Santo de Dios,
y de Su verdad enviada, manifestada y revelada en su interior,
tal como se ve en el Salmo 51:6, y de nuevo en su vehemente oración en el Salmo 43:3-4,

"`Envía tu luz y tu verdad; éstas me guiarán; me conducirán a tu santo monte,
y a tus moradas.
Entraré al altar de Dios, al Dios de mi alegría y de mi gozo; y te alabaré con arpa,
oh Dios, Dios mío.`"

Cuando la luz brilla y la verdad brota en el corazón,
en definitiva guían Al que es verdadero, guían a la colina santa del Señor,
a Su montaña santa.
De hecho, guían al altar interior,
donde los que sirven y adoran en el altar exterior no tienen derecho a comer;
donde es experimentada el arpa con la que el Altísimo es alabado, es decir,
el arpa interior, de la que el arpa externa de David no era más que una figura.
Por eso los que llegan al monte santo de Dios,
a la montaña de la casa del Señor y al edificio santo que fue levantado,
invitan y animan a otros a caminar en esa luz que los condujo a ellos allí,
donde se disfruta la comunión con Dios,
la unidad entre sí y las bendiciones de vida y paz.
(Isaías 2:5)

Pero, ¿qué debería decir yo de la suficiencia de la luz
y de la gracia del Espíritu de nuestro Señor Jesucristo,
o de lo que es capaz de hacer?
Únicamente diré esto: Que así como la plenitud fue suficiente para Cristo,
para prepararlo para la obra que tenía que hacer,
así es suficiente la medida de gracia y verdad que Él le otorga a cada hombre.
"`Mi gracia es suficiente para ti,`" le dijo Dios a Pablo, y así lo es para cada hombre.
No hay falta de suficiencia en la Gracia de Dios, en la Semilla del reino,
en la Perla de gran precio, en la Levadura santa, en la Sal celestial.
Ciertamente,
la virtud y la fuerza de esta son más grandes de lo que el enemigo es capaz de resistir.
Aquel que se mantenga en dicha suficiencia y no se aparte de ella,
sentirá la vida y el poder brotando de ella para vivificarlo y llevarlo
a través de todo lo que Dios requiera de él. Pues el agua que Cristo da
es una fuente que salta (en aquel a quien es dada) para vida eterna.
Esta agua es capaz de lavar,
de nutrir y de llenar de virtud viva el alma del que la espera y participa de ella.
Todas las naciones de los que son salvos deben caminar en la luz del Espíritu de Dios.
A esta luz deben volverse los hombres, en ella deben ser reunidos,
a ella deben ser trasladados (es decir,
del reino de las tinieblas a la admirable luz del Hijo).
Y al ser cambiados por ella (en la naturaleza de esta) llegan a ser luz en el Señor,
y deben caminar en la luz como Dios está en la luz.
(1 Juan 1:7)

Pregunta:
¿Cómo llega a ser iluminada la mente y la candela del Señor establecida en el alma?

Respuesta: Al hacer Dios que Su candela brille ahí,
y que la mente se vuelva a ella y se rinda para ser ejercitada por ella.

El poder del Señor alcanza a Su Semilla pura de luz y vida en el corazón,
en los tiempos de Su benevolencia.
Luego, a medida que la mente se vuelve a dicha Semilla, va siendo consciente de ella,
y está dispuesta a dejarla entrar y a volverse una con ella,
(sufriendo con ella y llevando Su cruz).
Entonces la Semilla crece ahí, y Su luz,
que estaba escondida y abrumada bajo la tierra (bajo la sabiduría, voluntad,
conocimiento, deseos... terrenales) también llega a brillar.
Sí, y como resultado, la vida es más y más vivificada,
y la levadura santa más y más extendida.
La tierna planta del renombre de Dios crece rápido
hacia el reino de justicia al ser apreciada;
al no ser afligida, despreciada,
sofocada o herida por darle paso y dejar entrar lo que es contrario a ella.
De hecho, crece hasta convertirse en un árbol de justicia,
bajo la sombra del cual se sienta el alma en paz y reposo,
y es defendida y nutrida con lo que es puro, vivo y está lleno de savia y virtud.
Así se fortalece en el Señor y en el poder de Su fuerza,
contra el poder y la fuerza de las tinieblas.

Todos los hombre pueden experimentar esto (al principio
en cierta medida y en grado pequeño,
y después más y más),
conforme llegan a palpar lo que es de Dios y a fortalecerse en el poder de Su fuerza,
y se unen y rinden a Él. Porque entonces eso que es de Dios estará
oponiéndose y purgando todo lo que es de una naturaleza contraria,
y esparciéndose en el corazón con su propia naturaleza.
Como resultado de esto, la Semilla que era la más pequeña se convertirá en la más grande,
y lo que era lo más bajo de todo (y de hecho,
pisoteado) se levantará en dominio y poder sobre todo y lo someterá todo.
De modo que la ciudad enaltecida, la enaltecida edificación de la sabiduría carnal,
y de pecado e iniquidad en el corazón,
será humillada y hollada por los pies de la Semilla.

Pregunta: ¿Por qué se reduce la luz o la candela del Señor en algunos,
hasta que eventualmente se extingue o se apaga?
¿Cómo ocurre esto?

Respuesta: Porque la descuidan, desprecian y sofocan,
al prestarles oídos y darles paso a los movimientos y tentaciones del espíritu contrario.
Porque tal como el Espíritu del bien detiene y expulsa el mal cuando entra,
así también el mal detiene y expulsa el bien cuando se le deja entrar.
Por tanto, cuando se le da paso a la naturaleza filistea,
esta detiene el pozo interior que Jacob había cavado y abierto.

Hay un tiempo cuando la vida es un misterio, una fuente sellada,
y hay un tiempo cuando Dios quita el sello de la fuente y abre
el misterio en el corazón. ¡Entonces se debe tener mucho cuidado!
El alma debe mantenerse muy baja en el temor puro,
para que pueda continuar en la bondad de Dios y caminar digna de Su amor,
a fin de que la fuente permanezca abierta,
fluyan de la tierra santa los manantiales puros y no sean sellados ni cerrados otra vez.
Porque hay algunos que se rebelan contra la luz y moran en tierra seca.
A otros que siempre se resistieron y afligieron al Espíritu de Dios,
Él los dejó y no luchó más con ellos,
y los entregó a un sentido y juicio reprobados con respecto a las cosas de Dios.
Y aquellos que no mejoran el buen talento de Dios,
se les quita lo que una vez les fue dado.
Sí, la candela de los impíos será apagada en un momento u otro,
entonces quedarán en silencio en las tinieblas,
y sus bocas no podrán decir nada nunca más contra Dios, Su verdad, ni Su pueblo.

Por lo tanto,
todos los hombres deben prestar atención para no ser descuidados con la gracia de Dios,
o despreciar el día de la visitación que Dios les
hace por medio de la santa luz de Su Espíritu.
Porque si Dios quita el talento o apaga la candela interior,
¿quién puede encenderla de nuevo?
¡Oh, cuánto sufrió el pobre David, el hombre conforme al corazón de Dios,
cuando dejó entrar en él la tentación del enemigo!
"`No me eches de delante de Ti,`" dijo,
"`y no quites de mí tu santo Espíritu.`"
Él perdió su estado en el momento,
y aquí habla como un hombre en peligro de ser completamente desecho.
Pero después llegó al consuelo y seguridad de que
Dios le restauraría el gozo de su salvación,
encendería su candela y alumbraría sus tinieblas de nuevo.

No ignoro las dudas y disputas que hay en las mentes de los hombres acerca de
este testimonio que damos (a partir de cierto conocimiento y verdadera experiencia),
con respecto a la luz con la que Dios alumbra las almas.
Al principio, cuando apareció el testimonio,
la mayoría no admitía tal cosa como una luz procedente de Dios en los hombres,
la cual los convencería y reprendería por el pecado.
Y ahora, aunque hay muchos que están de acuerdo con esto,
aún no pueden creer que esa luz sea una medida de la gracia y verdad que viene por Jesucristo,
y que en ella la suficiencia y poder de Dios son revelados contra la fuerza
y poder de Satanás. Pero que consideren seriamente lo siguiente:

En primer lugar, quiénes son los que han testificado y testifican de esta luz.
Son personas que generalmente han sido profundamente ejercitadas en la religión,
personas que han leído las Escrituras con mucha diligencia y oración,
esperando que Dios les conceda el verdadero, cierto y claro entendimiento de las mismas.
Son personas (muchas de ellas) que tienen experiencia en la mayoría, si no todas,
las persuasiones y denominaciones separadas,
pero que nunca encontraron la respuesta al clamor de sus almas,
ni (de manera satisfactoria) ese nacimiento que respiraba
en ellos en pos del Señor noche y día.

En segundo lugar, consideren el múltiple testimonio de estas personas.
Primero, que fueron vueltas por el Señor a esta luz (es decir,
por Su Espíritu Santo y el resplandor y brote de Su Semilla preciosa en ellas),
y se les mostró que dicha luz era de Dios.
Segundo, que al volverse a ella se encontraron con la presencia,
aparición y poder del Señor obrando en sus corazones.
Tercero, que esta luz no sólo les descubrió el pecado en ellas,
sino que también lo resistió poderosamente, peleó contra él y lo sometió;
lo que ninguna luz ni poder, además de la luz y poder del Espíritu de Dios, pueden hacer.
Cuarto, que la vida del Hijo se manifiesta y se revela en esta luz,
y que en ella llegan a ver, saborear y tocar la Palabra de vida eterna.
Quinto, que en dicha luz experimentan la limpieza por medio de la sangre del Cordero,
el pacto eterno hecho con ellas (es decir, las misericordias firmes de David),
y el cumplimiento de la promesa santa y preciosa; y que por dicha promesa,
son hechas partícipes de la naturaleza divina,
experimentan la entrada en la ciudad santa y beben
de las corrientes del río de cristal puro,
que refresca y alegra la ciudad de nuestro Dios.
Finalmente, por no mencionar más,
que el Señor les ha mostrado cómo esta misma luz había estado antes con ellas,
incluso en los días de su anterior profesión religiosa,
y cómo había obrado Dios en ellas por medio de esta luz en el pasado,
aunque en ese entonces no la conocieran.
Pero que ahora ven que cualquier habilidad que tenían
para entender cualquier cosa de Dios correctamente,
o para orar, o para cosechar algún beneficio verdadero de las Escrituras,
era a través del movimiento de esta luz en ellas, por la cual Dios incluso entonces,
y en alguna medida, alumbraba y vivificaba sus mentes.

En tercer lugar, consideren de nuevo, si la luz del Espíritu de Cristo,
o la gracia y verdad que vienen por medio de Jesucristo,
no tiene esta propiedad de descubrir, convencer y reprender el pecado.
No hay duda de que la ley del Espíritu de vida en Cristo Jesús,
aún en la más pequeña manifestación de ella,
es de esa naturaleza que descubre y pelea contra la ley
del pecado y muerte dondequiera que la encuentre.
Y consideren si el Consolador, el Espíritu Santo de verdad,
quien saca de todo error y falsedad e introduce en toda verdad,
no debe ser conocido por esto también, es decir,
por convencer al mundo de pecado y reprenderlo internamente,
y por consolar a los santos en su viaje de salida del pecado y Sus batallas contra este.

En cuarto lugar,
consideren si hay algo que pueda convencer de pecado además
de la luz del Santo Espíritu de Dios brillando en el corazón.
La ley externa puede hacer una declaración externa de pecado,
sí,
pero no alcanza el corazón ni la consciencia salvo por el resplandor de la luz interior.
Ni tampoco puede alcanzar el entendimiento,
a menos que Dios abra el corazón y deje claro en
el mismo la convicción de Su luz y poder.
De esto tenemos experiencia con los judíos. Porque aunque los profetas
fueron enviados con cierta evidencia y demostración del Espíritu de Dios,
los judíos no llegaron al convencimiento,
sino que se opusieron a ellos y se justificaron a
sí mismos contra la voz y Palabra del Señor. De hecho,
los ojos de ellos estaban cerrados, lo mismo que sus oídos,
y sus corazones estaban endurecidos tal como leemos en Jeremías capítulo 2 y otros lugares.
¡No hay maldad demasiado grande por la que un hombre
endurecido no esté dispuesto a abogar,
defender y justificarse en ella!
Sí, y aunque Dios les abriera el entendimiento a los hombres en alguna medida,
de modo que no pudieran dejar de confesar que en
general ciertas cosas son malas (como el orgullo,
avaricia, embriaguez, desenfreno, mentira, jurar, etc.), aún así, y con frecuencia,
no pueden ver o reconocer que estas cosas están en ellos.
Todo lo contrario, crean toda clase de cubiertas y excusas para esconderse detrás,
a menos que la luz interior y el Espíritu del Señor escudriñen
sus corazones y les ponga estas cosas de manifiesto.

En quinto lugar, consideren el peso de las siguientes dos escrituras,
y no conciban otro significado para ustedes,
ni quiten el significado e intención del Santo Espíritu de Dios en ellas.
La primera es del apóstol Pablo en Efesios 5:13-14, "`Mas todas las cosas,
cuando son puestas en evidencia por la luz, son hechas manifiestas;
porque la luz es lo que manifiesta todo.
Por lo cual dice: Despiértate, tú que duermes&hellip;,`" etc.
A todo hombre le es mandado despertar,
porque todo hombre tiene alguna proporción de ese don en él, que si lo escucha,
lo reprenderá, levantará, despertará,
y sacará de entre los muertos hacia Aquel que da la luz
y la hace brillar en él. La otra escritura es Gálatas 5:17,
donde el apóstol habla de la carne que es contra
el Espíritu y del Espíritu que es contra la carne,
y que estos se oponen entre sí. ¿Acaso no contendió el Espíritu
de Dios contra el mundo antiguo (leer Génesis 6:3),
no sólo contra los hijos de Dios que se habían corrompido,
sino contra el resto de la carne?
¿Y qué es lo que ha contendido contra los hombres impíos desde entonces,
y sigue luchando contra los malvados?
¿No es el mismo Espíritu bueno?
Además,
¿qué es lo que internamente resiste y desea contra
la voluntad y esfuerzos del Espíritu de Dios?
¿Acaso no es la carne?
Así que aquí están las dos semillas (contrarias entre sí) cerca del hombre;
pues el hombre es una criatura que legítimamente le pertenece al Señor,
en quien el destructor ha obtenido entrada,
y gobierna por medio de la ley del pecado y muerte.
Entonces el Creador del hombre lo busca y encuentra a Su enemigo en él,
y emite internamente una ley en el corazón contra dicho enemigo.
En la medida que un hombre la oiga, crea en ella y la reciba, se levanta una lucha,
un esfuerzo en él entre estas dos semillas contrarias,
para que no pueda hacer lo que desea.
Eso que lucha contra el pecado en cualquier hombre y lo perturba debido al pecado,
reprendiéndolo y condenándolo por ello,
es de una naturaleza diferente a la de la carne (la que alberga el pecado),
y contraria a esta.

En sexto lugar,
consideren el gran amor de Dios por la humanidad y el gran cuidado que tiene de ella.
Primero, con respecto a sus cuerpos.
¡Cuánto provee Él para los cuerpos de toda la humanidad!
Él desea que ningún cuerpo sea herido ni destruido,
sino que a todos los alimenta y nutre,
dando abundante provisión y fructíferas temporadas.
Él hace que Su sol brille y que Su lluvia caiga sobre todo.
Luego, en cuanto a sus almas.
¡Él sabe cuán preciosas son y lo que es la pérdida de una!
Sí, Dios sabe cuán ansioso está el devorador de destruir y por tanto,
se coloca a Sí mismo contra él. Dios es el Padre de los
espíritus y Su Hijo el Pastor y Obispo de las almas,
cuya naturaleza es reunir y salvar.
Es dicho expresamente de Dios, por el testimonio del Espíritu de verdad,
que Él desea que todos sean salvos y lleguen al conocimiento de la verdad.
Y aunque les fue dicho a los judíos que Dios era como un alfarero y ellos como arcilla,
y que Él podía hacerlos vasijas de honra o deshonra según su voluntad (Jeremías 18:6),
aún así esto fue dicho para este fin: Para invitarlos y animarlos a someterse a Él,
y pudieran ser hechos por Él vasijas de honor, tal como se lee en el versículo 11.

Ahora consideren si Dios es tan tierno con respecto a las
almas como lo es con respecto a los cuerpos de los hombres,
¿acaso no hace provisión para el alma como la hace para el cuerpo?
¿Acaso no desea que el alma viva y que sea alimentada tanto como es alimentado el cuerpo?
Si es así,
con toda seguridad la luz de Su Santo Espíritu brilla internamente en todas las naciones,
y la gracia y el poder que salvan se manifiestan en todo lugar, es decir,
en alguna medida, en cada corazón. Y con toda seguridad,
la carne y la sangre del Hijo de Dios, que es la comida del alma, son ofrecidas a todos.
Porque ciertamente, el Señor no es un amo duro para con ninguno,
como el siervo negligente en cada dispensación está listo a decir.
Pues Dios pasó por alto los tiempos de la ignorancia y tinieblas,
siendo muy tierno para con todos los hombre en ese estado.
De hecho,
si el hombre se volviera y prestara atención aunque fuera un poquito
a lo que es de Él (según la medida de entendimiento que da Dios),
eso sería reconocido y aceptado,
incluso en medio de una gran cantidad de tinieblas y maldad obrando contra ello.

¡Oh, si los hombres pudieran morir a sí mismos, es decir,
a su propia sabiduría y prudencia, y no apoyarse en sus propios entendimientos,
ni idolatrar sus propias comprensiones y conceptos,
sino esperar hasta recibir el entendimiento que procede de Dios,
quien da generosamente de Su sabiduría verdadera a los que piden y esperan
correctamente! ¿Y cómo da Dios verdadera sabiduría y entendimiento?
¿No es mediante el resplandor de Su luz en el corazón? ¡Oh,
si los hombres se volvieran internamente,
e internamente murieran a esa sabiduría y prudencia
de las que Dios esconde para siempre las cosas!
El que quiera ser verdaderamente sabio primero debe hacerse ignorante,
para que llegue a ser sabio.
No debe esforzarse en aprender las cosas del reino de Dios
en la forma que comprende la sabiduría y prudencia del hombre,
sino en sentir el engendramiento de la vida en el corazón, y en ese,
recibir algo del entendimiento nuevo y celestial.
Él debe morir a su propio entendimiento y dejar de
conocer las cosas de Dios según la carne.
Debe convertirse en un bebé, en un necio,
y recibir e inclinarse a lo que su propia sabiduría
llamaría necedad y consideraría debilidad.
Pero el otro nacimiento (que es engendrado y nace
de Dios) sabrá y diariamente experimentará eso,
como la sabiduría y poder de Dios para salvación.

Algunas Aclaraciones a Modo de Preguntas y Respuestas

El verdadero conocimiento y la verdadera experiencia,
especialmente con respecto a las cosas necesarias, son de gran importancia para el alma,
tales como: Conocer el verdadero fundamento, la piedra angular,
la cual Dios coloca en Su Sión espiritual; y la Jerusalén celestial,
que es la madre de todo el que nace de Dios.
Ser reunidos fuera del espíritu de este mundo que es vanidad y falsedad,
para ser recogidos en el Espíritu de Dios, el cual es verdad y no miente.
Experimentar la edificación del templo santo en el que Dios aparece y es adorado;
la comunión celestial con el Padre y el Hijo en la
luz pura que brilla de Ellos en el corazón;
la única fe, la única circuncisión, el único bautismo, la única agua de vida,
el único pan, la única copa de salvación, etc.

Ahora bien, las cosas del reino están en total disposición del Rey.
Por tanto, cualquiera que quiera entender correctamente,
deberá recibir el entendimiento de Él; cualquiera que quiera arrepentirse correctamente,
deberá recibir el arrepentimiento de Él; cualquiera que quiera creer correctamente,
deberá recibir la fe de Él; cualquiera que quiera oír y ver correctamente,
deberá recibir el oído y el ojo de Él; cualquiera que quiera ir a Él y recibirlo,
deberá experimentar ese nuevo corazón siendo formado en él,
con el cual y por el cual Él es recibido.
Los hombres se equivocan y se confunden grandemente
acerca del conocimiento y religión del evangelio,
al comenzar en él sin el espíritu y poder del evangelio.

Por tanto, el hombre que no desee ser engañado y perder su alma para siempre,
que preste atención a cómo comienza,
cómo permanece y cómo prosigue en su religión. Los judíos tenían que permanecer
en la revelación del Espíritu de Dios y Su poder externamente.
El estado de los cristianos, el estado del nuevo pacto,
descansa sobre la revelación del Espíritu de Dios y Su poder internamente.
Pues nadie puede engendrar un nuevo nacimiento para Dios internamente,
excepto Su propio Espíritu y poder obrando internamente en el corazón. Así que, ustedes,
los que deseen vivir con Dios para siempre y no caer
de la presencia y gloria de Su poder,
pongan atención a las siguientes tres cosas:

En primer lugar, presten atención a las visitas internas de Dios,
y a Su deseo de hacer un cambio real en ustedes.
No me refiero a un cambio de una idea a otra en sus mentes,
sino a un cambio de una naturaleza y espíritu a otra Naturaleza y Espíritu en sus corazones.
Esta es la gran obra,
la que nada sino el poder de Dios (que levantó a Jesús de los muertos)
puede efectuar en los corazones de los hijos de los hombres.

Ahora bien, para que esto sea forjado en ustedes,
esperen la aparición y obra de ese poder que diariamente lo efectúa más y más,
en los que se unen a dicho poder y se rinden a sus operaciones.
¡Sí, esperen sentir ese poder engendrando algo de su propia naturaleza en ustedes,
leudándolos en su naturaleza por medio de la levadura pura y celestial,
con la que Dios desea leudar sus corazones!
Sí, sientan su comienzo desde la verdadera raíz, desde la Semilla santa,
desde la Semilla del reino.
Luego esperen sentir a esa Semilla creciendo en ustedes,
para que así como el comienzo es puro, el crecimiento también lo sea.

Ahora bien, después de que el Padre los haya visitado,
engendrado algo en ustedes y leudado en alguna medida para que haya verdadera vida,
verdadero sentido, verdadera hambre, verdaderas respiraciones,
entonces (en segundo lugar),
estén vigilantes y esperen hasta aprender del verdadero Maestro,
cómo llegar a las verdaderas aguas,
para que beban de ellas y no de un charco sucio de su propia formación o de la de otros.

Finalmente, después de que Dios haya hecho Su pacto con ustedes, les haya hablado paz,
les haya dado algo del poder, la justicia y el gozo del reino,
y haya establecido el santo cerco y muro de salvación alrededor de ustedes,
cuiden de no ir tras ninguna lujuria, ningún deseo de la carne,
ninguna tentación del enemigo.
Manténganse dentro de los límites sagrados,
no toquen nada muerto ni impuro para que no sean contaminados,
ni se aparten gradualmente de Aquel que es puro.

Pregunta: ¿El Espíritu iluminador y santificador es uno y el mismo Espíritu o no?

Respuesta:
El Espíritu que ilumina y el Espíritu que santifica es uno y el mismo Espíritu,
y la iluminación del Espíritu es para santificación. La
misma luz que descubre las tinieblas también las persigue.
En la medida que esta luz sea recibida y se esté sometido a ella,
así es purificada la mente.
Pues la luz no sólo tiene la propiedad de alumbrar,
sino también la de limpiar y santificar.
La razón por la que los hombres no son cambiados,
justificados y santificados en y por esta luz, es debido a que ellos no la aman,
ni le llevan sus corazones y obras.
Por eso la luz se mantiene sólo como la que los reprende y condena,
y no como la que los justifica y santifica.

Pregunta: ¿Cómo escribe Dios Su ley en el corazón?

Respuesta: Por medio de Su Espíritu y poder obrando ahí,
mediante los cuales crea un nuevo corazón y escribe la nueva ley, es decir,
la ley del Espíritu de vida en Cristo Jesús. Está escrito:
"`Las costas esperarán su ley.`"
¿La ley de quién? La ley del Mesías, la ley de la gracia, la que da dominio,
la ley de la unción, la ley del nuevo nacimiento, la ley de la Semilla santa.
"`Su Semilla permanece en él.`" (1 Juan 3:9). En dicha Semilla
está la nueva naturaleza y la nueva ley,
ambas.
Ahora consideren, ¿qué es la ley del pecado?
¿Qué es la ley de la muerte?
¿Cómo es escrita en el corazón? ¿Cómo la escribe el enemigo ahí,
si no es por su espíritu y naturaleza corruptos?
¿Acaso no escribe Dios, mediante Su Santo Espíritu y naturaleza, la nueva ley,
la ley de vida,
en los corazones de los que son renovados y hechos sensibles
a las impresiones de Su poder santo y vivificador?
Cada movimiento y persuasión de Su Espíritu es, entonces,
una ley para los que han nacido del Espíritu y han sido enseñados
por Dios a ver y a caminar según el Espíritu vivificador.

Pregunta: ¿Qué es la verdadera iglesia evangélica?

Respuesta:
Es la compañía de los verdaderos creyentes en el Espíritu y poder del Señor Jesucristo.
Es la compañía de los verdaderos judíos, judíos internos, judíos en Espíritu,
los de la verdadera circuncisión,
a quienes el Padre ha buscado y hecho verdaderos adoradores en el interior;
los que el Padre ha reunido para el nombre y reunido en el nombre del Señor Jesús,
para que le ofrezcan sacrificios espirituales a través
de Él. Es la compañía de piedras vivas,
las que han recibido vida de Él, la Piedra angular,
y que se reúnen a esperar y adorar al Padre en la luz y Espíritu que han
recibido de Él. ¡Esta es la iglesia santa o asamblea viva del Nuevo Testamento,
y benditos los que son de ella!
Porque los que son añadidos por el Espíritu de Dios
y poder a esta iglesia y permanecen en ella,
ciertamente serán salvos.

Pregunta: ¿Cuál es el camino seguro e infalible de la salvación?

Respuesta: Es un camino nuevo y vivo; es tal camino,
que sólo los vivos pueden caminar en él. Es un camino santo, en el que sólo los limpios,
rescatados y redimidos del Señor pueden dar un paso en él. El camino,
la vida y la verdad son uno.
¡Benditos los que lo encuentran y caminan en él! En términos claros y expresos,
el camino es el Señor Jesús, la luz del Señor Jesús, la vida del Señor Jesús,
el Espíritu del Señor Jesús, la verdad tal como está en Él, Su sabiduría, Su poder,
Él mismo, el pacto o límite santo entre Dios y el alma.
Él que viene a Él, viene en el camino.
El que permanece en Él, permanece en el camino.
El que camina en Él, camina en el camino.

Pregunta: ¿Cómo salva Cristo el alma?

Respuesta: Visitando internamente, tocando la puerta internamente,
haciendo que la luz de la vida brille internamente;
alumbrando y vivificando internamente, y quebrantando la fuerza del enemigo internamente;
sacando de la región y sombra de tinieblas internamente, a la región y camino de luz.
Es por la luz y poder de Su Espíritu que Él engendra un hijo de luz.
Él saca a este hijo de luz de Egipto, de la tierra de oscuridad; de Sodoma,
la tierra inmunda y sucia; de Babilonia, la tierra y ciudad de confusión,
y lo lleva a la luz donde Él y Su Padre moran.
Este hijo de luz no es de la naturaleza de tinieblas,
sino de la naturaleza de luz en el Señor, y camina en la luz como Él está en la luz.
Y Él lo preserva y lo salva cada día más,
por medio de un mayor brillo y obra de la luz y vida en él.

Pregunta: ¿Qué es la regeneración o el nuevo nacimiento?

Respuesta: Es un cambio interno, por medio del Espíritu y poder del Dios vivo,
en Su propia naturaleza.
Es un ser engendrado por Su Espíritu, nacido de Su Espíritu;
engendrado y nacido de la naturaleza misma de Su Espíritu.
("`Lo que es nacido del Espíritu, Espíritu es.`"
Juan 3) Es un cambio que Dios hace,
por el mismo poder con el que levantó a nuestro Señor Jesucristo de la tumba,
en los corazones de los que Él visita, quienes son conscientes,
reciben y se sujetan a Su vida, luz y poder interior.

Pregunta: ¿Qué es la verdadera santidad?

Respuesta: Es esa naturaleza santa y esas acciones santas, que surgen de la raíz santa;
todo lo demás no es más que imitación de la santidad, no es la verdadera santidad.
El árbol debe ser hecho bueno primero,
y entonces el fruto será bueno también. Hay muchas imitaciones de la verdadera
santidad en varias profesiones de religión en el mundo,
pero no se va a encontrar verdadera santidad (ni justicia tampoco),
excepto en los árboles de la plantación de Dios,
en las ramas que son injertadas por Él en la verdadera vid y en el árbol de olivo,
cuya fuerza de virtud y santidad radica en la savia que reciben de Él día a día.

Pregunta: ¿Cuáles son mayores,
las obras que hizo Cristo externamente en los cuerpos
de los hombres en los días de Su carne,
o lo que hace internamente en las mentes y espíritus de los hombres
mediante la poderosa aparición y operación de Su Espíritu?
Porque Cristo dijo que los que creyeran en Él harían la obras que Él hizo,
e incluso mayores, debido a que Él iba al Padre.
(Juan 14:12)

Respuesta: Sin ninguna duda, es mayor alcanzar el alma,
vivificarla y sacarla de la tumba de muerte.
Curar la ceguera, la sordera, la dureza y la enfermedad del alma es mayor que lo externo;
de hecho, esto fue testificado por lo externo.

Pregunta: ¿Qué es el yugo o la cruz de Cristo?

Respuesta: Es interna, porque lo que se crucifica es principalmente interno.
Es ese don de Dios, esa luz de Su Espíritu que es contraria a las tinieblas,
contraria a todo lo que es corrupto, que desea y pelea contra eso.
Al ser recibida, al estar sometidos a ella, al ser llevada pacientemente,
la cruz elimina la vida de la carne, la voluntad y sabiduría de la carne,
y todos los razonamientos y estratagemas sutiles de la parte carnal.
Así es como la carne llega a languidecer y a morir,
y la planta de Dios en el interior es aliviada de su carga.
Al permanecer bajo la cruz, el alma entra en la verdadera, pura y perfecta libertad,
donde es libre para la santidad y la justicia, y a la vez,
es atada y encadenada en cuanto a toda libertad para la carne,
y en cuanto a todo tipo de impureza e injusticia.

Pregunta: ¿Cómo puede un hombre "`hacer firme su llamado y elección`"? (2 Pedro 1:10)

Respuesta: Al hacer firme el don de Dios para él; es decir,
asegurando la Semilla para él,
en la que está el llamado y la elección. Porque lo que Dios elige es la Semilla,
la Semilla santa, la Semilla interna, la Semilla del Espíritu de Dios,
y la criatura según se une a la Semilla.
Dios no desea que nadie perezca, sino que todos lleguen al conocimiento de Cristo,
la verdad,
quien es la Semilla y en quien se encuentra la elección.
Su consejo santo a los hombres es:
"`hagan firme su llamado y elección.`" Entonces,
la manera de hacer firme el llamado y la elección es asegurando el Don,
asegurando la Semilla, asegurando la Levadura, asegurando la Perla,
la que Dios jamás rechazará, ni a ninguno que sea hallado en verdadera unión con Ella,
y en el amor y obediencia a Ella.
Por tanto, cuando Dios visite con poder (con Su poderoso don),
ríndanse a la verdad en lo íntimo, entren en ella, habiten en ella,
para que puedan experimentar su virtud y su naturaleza que libera de todo lo que esclaviza,
y luego, manténganse firmes en la libertad con la que Cristo el Señor los hace libres.
Aquí experimentarán su llamado y su elección día a día,
y hallarán que ambos están sellados y seguros para ustedes en esa verdad,
en esa luz celestial y en esa Semilla santa que provino de Dios y es de Él,
la que Él se deleita en reconocer y jamás rechazará.

Pregunta: ¿Qué es la verdadera oración?

Respuesta: La oración es la respiración que brota del verdadero nacimiento,
del sentido vivo que Dios da al verdadero nacimiento.
Hay un Espíritu de oración y súplica dado por Dios a Sus hijos para luchar y
prevalecer con Él. Toda oración que brota de ese Espíritu y es dada por Él,
es verdadera oración. Cualquier otra oración no es correcta ni verdadera,
sino en el mejor de los casos, es una imitación de la verdadera.
"`Pues qué hemos de pedir como conviene, no lo sabemos,
pero el Espíritu mismo intercede por nosotros con gemidos indecibles.`"

Pregunta: ¿Qué es el verdadero arrepentimiento?

Respuesta: Es el arrepentimiento que da Cristo,
a quien Dios ha exaltado para que sea Príncipe y
Salvador y dé arrepentimiento y perdón de pecados.
(Hechos 5:31) No está en poder del hombre arrepentirse,
pues su corazón es duro e impenitente.
El poder de Dios es el que ablanda, enternece y cambia el corazón. Por tanto,
hay una gran diferencia entre la percepción y la tristeza de la naturaleza del hombre,
y la percepción y la tristeza que da Dios al corazón que Él renueva y cambia.
Lo primero es de la naturaleza terrenal, lo segundo es de la naturaleza celestial.
Uno es como el rocío temprano o la nube de la mañana que pasa pronto,
el otro está escrito en el corazón nuevo y permanece.
En el verdadero arrepentimiento hay un dolor y una tristeza reales por
causa de la naturaleza corrupta y por todas las obras muertas de la carne,
y un volverse de ellas y un deseo de no entrometerse más con ellas.
Este es el arrepentimiento que es don del Señor Jesucristo.

Pregunta: ¿Qué es la verdadera fe?

Respuesta: Las Escrituras hablan de una nueva creación en Cristo.
En realidad todos los verdaderos creyentes lo son, y tienen la habilidad, la facultad,
la potestad de creer que vienen de Aquel que los crea de nuevo.
Existe algo que es llamado '`fe`' en los hombres no regenerados,
pero esa no es la fe de la que estoy hablando ahora.
Yo hablo de esa fe que es la dádiva de Dios para lo que nace de Él,
lo que se genera de Él. "`Porque a ustedes les es dado no sólo creer,`" etc.
(Filipenses 1:29) Noten, "`les es dado creer.`"
¡Oh, esta dádiva sagrada!
Esta fe del nuevo nacimiento es la fe que agrada a Dios, prevalece con Él,
purifica el corazón, da entrada a Dios e interés en Su poder y promesas,
da victoria sobre la naturaleza mundana y sobre todos los enemigos del alma.
¡Bendito sea el Señor por otorgar e incrementar esta fe en los corazones de Sus hijos!

Pregunta: ¿Qué es la obediencia?

Respuesta:
La verdadera obediencia es la que fluye del verdadero
entendimiento de la voluntad de Dios,
y de la naturaleza santa que Él engendra en el corazón.
Es la obediencia que fluye del verdadero sentido,
del verdadero entendimiento y de la verdadera fe.
No hay nacimiento que pueda creer correctamente excepto uno,
ni hay nacimiento que pueda obedecer correctamente,
excepto el único que cree correctamente.
El verdadero creer viene de la virtud vivificadora del Espíritu
de Dios (cualquier otra fe no es más que fe muerta),
y la verdadera obediencia está en la novedad del Espíritu.
(Romanos 6:4;
7:6) El hombre puede esforzarse por entender y obedecer todos los días de su vida,
pero no puede hacer ninguna de las dos cosas, excepto cuando es vivificado,
enseñado y habilitado por el Señor. "`Enséñame, oh Jehová,
el camino de tus estatutos`" (Salmo 119:33).

Hay una senda mística de vida.
El camino de sabiduría, el camino de santidad, la habilidad santa de obedecer la verdad,
está escondida de todos los seres vivos, de toda la humanidad,
salvo para los que son engendrados y criados por Él en la santa habilidad y misterio
de sujetarse al Señor. "`Tu pueblo se te ofrecerá voluntariamente en el día de tu poder.`"
El poder de Dios es el que obra el querer en el corazón,
y es el mismo poder el que también obra el hacer.
Nadie puede aprender el querer o el hacer correctamente,
excepto en la medida que se familiarice con ese poder,
sea unido a ese poder y sienta ese poder obrando en él. Aquí, en el nacimiento de arriba,
la verdadera fe y obediencia llegan a ser tan naturales,
como lo son la incredulidad y la desobediencia para el nacimiento de la carne.

Pregunta: ¿Qué son las buenas obras?

Respuesta: Las buenas obras son las que fluyen del buen Espíritu de Dios,
las obras que son hechas en Dios.
Las obras del nuevo nacimiento, de la nueva criatura, son buenas obras;
mientras que todas las obras de la carne son malas, aunque estén muy finamente pintadas.
Todos los pensamientos, imaginaciones y razonamientos de la carne; todo el deseo,
la actividad y la búsqueda de la carne para descubrir a Dios y sus cosas celestiales,
junto con todos sus sacrificios, es corrupto y maligno,
pues tienen la levadura maligna de la naturaleza maligna en ellos.
¡Hagan el árbol bueno o su fruto jamás será bueno!
Por tanto, sólo las buenas obras que fluyen del árbol bueno, de la raíz buena,
son buenas obras.
Aquí todas las obras de la carne,
por muy gloriosas y atractivas que sean para el ojo del hombre,
son excluidas por la vara de medir de Dios,
por la plomada de justicia y verdadero juicio de Dios.
Toda obra del Espíritu de Dios, la más pequeña obra de fe,
la mínima obra del verdadero amor,
el más pequeño brillo de la vida en el corazón y la rendición a esta,
es reconocido por Dios como proveniente de Él y obrado en Él,
quien da tanto el querer como el hacer por Su buena voluntad.

El que ha obedecido a la luz con la que Dios lo ha alumbrado, ha recibido la luz,
mora en la luz y camina en la luz.
El Espíritu del Dios vivo está cerca de él, mora con Él,
obra en él y lleva sus obras a la luz donde se manifiesta que son hechas en Dios.
Pero las obras del que está fuera de la luz interior del Espíritu de Dios,
no son hechas en Dios.
Puede que hagan un hermoso espectáculo en la carne (al ojo carnal),
pero no son buenas ante los ojos de Dios.
El camino y las obras del hombre errado a menudo son correctas a sus propios ojos,
pero bendito aquel cuyo camino y obras son buenas y correctas ante los ojos del Señor,
ante el juicio de Su luz y Espíritu escrutador e infalible.

Pregunta: ¿Cuál es el verdadero amor?

Respuesta: El amor que se levanta de la naturaleza que Dios engendra,
y de la circuncisión de corazón que Él hace quitándolo de la otra naturaleza.
El amor es altamente elogiado y admirado, y hay muchos que lo pretenden,
pero nadie tiene el verdadero amor,
sino el que ha nacido de Dios y ha sido circuncidado
por Él. "`Y circuncidará Jehová tu Dios tu corazón,
y el corazón de tu descendencia,
para que ames a Jehová tu Dios con todo tu corazón y con toda tu alma,
a fin de que vivas`" (Deuteronomio 30:6). Noten,
el verdadero amor se levanta de la verdadera circuncisión,
y cuánto más circuncidado tenga un hombre su corazón de la naturaleza carnal,
y más haya crecido en la naturaleza pura y celestial, más ama.
Dios es amor, y cuánto más cerca esté alguien de Él y más participe de Él,
más llega a ser amor en el Señor, y más enseñado es por Dios a amar al Señor su Dios,
a su prójimo en el Espíritu y a toda la humanidad,
la cual es de su sangre (porque "`de una sangre ha
hecho todo el linaje de los hombres`") según la carne,
o según una consideración natural.

Pregunta: ¿Cuál es el conocimiento del nuevo pacto?

Respuesta: Es el conocimiento que da Dios al nuevo nacimiento,
pues a este pertenece el nuevo pacto y el conocimiento del mismo.
Porque el conocimiento del reino de Dios es dado
al que es verdaderamente engendrado por Dios,
al verdadero discípulo de Cristo; pero a otros no les es dado.
En el caso del judío externo (del primer nacimiento, del nacimiento según la carne),
los labios del sacerdote debían preservar el conocimiento,
y el hombre tenía que buscar la ley en su boca.
Bajo este pacto Dios envió a los profetas para que les hablaran,
y Él les enseñaba por medio de ellos.
Pero con respecto al judío interno, a los hijos del nuevo pacto,
los hijos de la Jerusalén de arriba, con respecto a Su descendencia fue profetizado,
que todos ellos debían ser enseñados por el Señor.
Todos debían oír y conocer la voz del Pastor,
todos debían ser reunidos para el Pastor y Obispo del alma
y ser enseñados por Él. A fin de que en este pacto nuevo,
santo y vivo, Dios mismo sea el Pastor, Dios mismo sea el Maestro, no sólo del mayor,
sino también del menor.
(Hebreos 8) Estos son enseñados a conocer al Señor y a conocer a Su hijo,
a venir a Su Hijo y amar al Padre y al prójimo.
Por tanto, el que es enseñado por Dios tiene el verdadero conocimiento,
el conocimiento vivo, el conocimiento sustancial, el conocimiento de la cosa misma,
el de la vida eterna misma.
Los que no son enseñados de esta manera (sino que solamente
aprenden de la descripción y relato literal de las cosas),
no tienen el conocimiento del nuevo pacto, el conocimiento de la cosa misma,
sino únicamente un conocimiento externo,
al que se aferra y comprende el primer nacimiento.

Pregunta: ¿Qué es el temor del nuevo pacto?

Respuesta: Es el temor que Dios pone en los corazones de Sus hijos,
que limpia sus corazones y evita que se alejen de Él. Hay una gran diferencia
entre el temor que puede ser aprendido de los preceptos en el exterior,
y el temor que pone Dios en los corazones de Sus
hijos que proviene de la raíz de vida en el interior.
Este temor es de naturaleza celestial y es el don
gratuito de Dios para Su propio nacimiento celestial,
y para nadie más. Porque ningún hombre puede alcanzar este
temor por medio de sus propios pensamientos o razonamientos,
sino sólo mediante el brote de vida que proviene de Dios.
El que quiera tener este temor, debe conocer el lugar de la sabiduría y esperar en él,
y cuando lo tenga, pronto el temor comenzará a hacerlo sabio para con la salvación,
y lo enseñará a separarse del mal que es causa de destrucción. (Job 28:28)

Pregunta: ¿Qué es la verdadera esperanza?

Respuesta: Es fijar la mente en el Señor,
es que el nacimiento celestial se fije en su Padre.
Ahora bien, nosotros debemos distinguir entre esperanza y esperanza.
Existe la esperanza del hipócrita o falso nacimiento, cuya esperanza perecerá;
y está la esperanza del verdadero nacimiento, la cual nunca fallará ni avergonzará,
porque este nacimiento es enseñado por Dios a esperar correctamente.

Con respecto a la esperanza, está el terreno de la esperanza y la esperanza misma.
El terreno de la esperanza es el amor de Dios, la verdad de Dios, la fidelidad de Dios,
la gracia de Dios, Su Semilla, Su Cristo experimentado en el interior.
Está la verdad de ser de Él, de estar unido a Él,
en Él y Él en mí. Este es el terreno de mi seguridad de la gloria y de la herencia eternas,
el cual es seguro para la Semilla y para todos los que son de la Semilla y están en ella.
Por tanto, al conocer a Cristo en mi interior, sentir a Cristo en mi interior,
vivir en Él y Él en mí, tengo un ancla segura y firme detrás del velo,
sobre la cual ni las tormentas, tempestades, pruebas o tentaciones,
presentes o por venir, tienen poder.

Luego está la esperanza, la esperanza misma; es decir,
la realidad de fijar la mente en el Señor, de apoyarse en el Señor,
de retirarse fuera de todo pensamiento, razonamiento o búsqueda externa,
hacia la vida interior;
de sentir algo surgir de dicha vida en lo que el alma pueda confiar o esperar,
más allá de toda apariencia externa.
Esta esperanza nunca engaña ni avergüenza a los que son
enseñados por Dios a fijar sus mentes en Él. No,
aunque el estado sea tinieblas y no se vea luz,
debajo de las tinieblas aún hay algo en lo que el
niño y siervo del Señor puede fijar la mente,
hasta que Él aparezca y haga que la luz salga de la oscuridad.
Porque la luz es sembrada para los justos y el gozo para los rectos,
aún en sus condiciones más oscuras, tristes y angustiosas,
en todas las cuales el Señor está cerca y todavía queda motivo para esperar en Él.

Pregunta: ¿Cuál es el verdadero gozo?

Respuesta: Es el gozo que fluye de la presencia de Dios,
de la obra de Su poder en el corazón y de la segura expectativa
que da Él de plena herencia y gloria de vida eterna.
Cuando el novio está presente, cuando el alma es reunida en casa con Él,
está casada con Él, en unión con Él, en la comunión santa y viva, entonces hay gozo.
De hecho, cuando Él aparece contra los enemigos del alma,
y se levanta contra ellos quebrantándolos y esparciéndolos; cuando da cosas buenas,
y llena de vida, llena de amor,
llena de virtud y prepara banquete para el alma en presencia del Padre, ¡oh,
qué plenitud de gozo hay en el corazón! "`En tu presencia hay plenitud de gozo;
delicias a tu diestra para siempre,`" dijo el salmista.
(Salmo 16:11)

Cristo les dijo a Sus discípulos que debido a Su partida ellos iban a estar tristes,
pero que Él los volvería a ver,
que sus corazones se gozarían y que nadie podría quitarles el gozo.
(Juan 16:22) ¿Cómo o cuándo se cumplió esto?
¿Por qué estaban ellos afligidos?
¿Acaso no era por la pérdida de Su presencia externa,
que había sido tan dulce y consoladora para ellos?
¿Cómo volvería a ellos?
¿Acaso no sería por medio del Consolador?
¿No sería mediante Su presencia interna y espiritual,
para que Aquel que había estado con ellos ahora estuviera en ellos?
Antes habían conocido a Cristo con ellos, ahora debían conocerlo en ellos,
al Padre en ellos, y a ellos en Él. Este es Emanuel, el estado del evangelio,
Dios con nosotros, morando con nosotros, levantando Su tabernáculo en nosotros,
viviendo en nosotros,
caminando en nosotros y nosotros viviendo y caminando
en Él. Cuando los apóstoles llegaron a este estado,
entonces llegaron a experimentar el gozo del Espíritu Santo, es decir,
el gozo inefable y la plenitud de gloria.
Por tanto, este estado del evangelio es un estado de gozo y regocijo en el Señor,
en Su gloriosa y viva presencia y en la gloria de Su poder.
Porque ahora la verdadera luz brilla internamente en el corazón y la vida se manifiesta,
y los que entran en la manifestación de ella, entran en la unión santa,
en la comunión santa con el Padre y con el Hijo,
donde está el gozo y donde el gozo es completo.

Pregunta: ¿Cuál es la correcta pobreza de espíritu y la verdadera humildad?

Respuesta: La verdadera pobreza de espíritu y humildad,
brotan de la misma raíz de donde se levantan la fe, el amor, la paz,
el gozo y las otras cosas celestiales, y son de la misma naturaleza.

Ahora bien, hay una humildad voluntaria,
una pobreza voluntaria (de espíritu) a la que un
hombre puede abocarse y formar en sí mismo,
por medio de su propia obra y razonamientos.
Esto no es verdadero, sino una imagen falsa, una falsificación de lo verdadero.
Pero hay una pobreza que surge cuando Dios vacía y despoja la criatura,
y hay una humildad que brota del nuevo corazón y de la nueva naturaleza.
Este es el tipo correcto,
es perdurable y permanece incluso en medio de las riquezas y gloria del reino.
Porque así como Cristo fue pobre en espíritu delante de Su Padre,
y humilde de corazón en medio de toda la plenitud que recibía de Él,
así sucede con los que son del mismo nacimiento y de la misma naturaleza de Cristo.
Están llenos de humildad y vestidos con humildad,
en medio de todas las gracias y riquezas celestiales
con las que Dios los llena y los adorna.
Si ellos se mantienen en la fe, en la verdad, en la luz y poder,
toda jactancia en o según la carne queda excluida,
y se mantiene la mente en la verdadera humildad y pobreza de espíritu.
Así el Señor de vida es el único exaltado,
y la criatura es mantenida humilde delante de Él y baja para siempre, y es nada,
excepto cuando el Señor se complace en llenarla.

Conclusión

Los que deseen conocer, experimentar, disfrutar y ser testigos de estas cosas,
deben ocuparse de aquella Semilla en la que todas estas están envueltas,
y de donde brotan y crecen.
El reino, el trono, el poder están en la Semilla.
El que es unido a la Semilla y permanece en ella, recibe poder de la Semilla y vence.
Este heredará todas las cosas "`y yo seré su Dios,
y él será mi hijo`" (Apocalipsis 21:7). No debe estar
temeroso o ser incrédulo de la derrota del pecado,
o de la de los enemigos de su alma,
sino depender del omnipotente y todo suficiente poder de Dios.
Porque la Semilla le dará victoria sobre el pecado y le enseñará a no tocar lo impuro,
para que sea santo como el Señor su Dios es santo.
En verdad,
es bueno para los hijos celestiales participar de la vida divina
y de la naturaleza celestial de su Padre y llegar a ser como Él.
