== Capítulo 5. Las Experiencias

=== Prefacio

El Padre, en Su amor, nos ha llevado a Su Hijo,
y el Hijo en el mismo amor nos ha llevado de regreso al Padre,
y ahora el amor fluye más natural y abundantemente desde el Padre,
en y a través del Hijo.
Dondequiera que el corazón sea circuncidado,
de ahí regresa verdadera y naturalmente el amor a Él,
para que el Señor nuestro Dios sea amado con todo el corazón y con toda el alma,
y nada sea considerado demasiado bueno para sacrificarle a Él,
ni excesivo para sufrir por Él. ¡Oh,
el amor puro que brota y fluye entre el Padre celestial y el niño espiritual!
El mejor amor que se pueda encontrar en este mundo (entre los hombres
de este mundo) no es digno de ser una sombra de este.

De esta Fuente no sólo brotan manantiales y arroyos
de vida para refrescar nuestros propios corazones,
sino también testimonios con respecto a la vida que sentimos y de la que participamos,
y testimonios con respecto a nuestros viajes de la tierra de tinieblas,
a través del valle de lágrimas, a nuestro lugar de reposo.
Muchas veces estos manan en nosotros para el bien
de otros y las cosas que siguen son de esa naturaleza.
Porque no es para mi propio bien que estos brotan en mí en ese momento,
sino para darles a conocer a otros la misericordia que el Señor me ha mostrado,
el camino por el que Él me ha guiado,
y lo que Él me ha dado a probar y a experimentar en el trayecto.
Habiéndolos recibido del Señor para este fin (para
hablar de ellos a otros en amor y ternura de espíritu),
mi corazón se entrega libremente a Él en esto.
En lo cual no aspiro a nada sino Su gloria pura,
y el bien de las almas a quienes Él se complacerá
en extender Su favor y mostrar Su misericordia,
al abrirles el misterio celestial de vida y salvación.

En realidad, mi herida era profunda y parecía incurable,
pero bendito sea el Señor que me ha dado a conocer al Médico capaz,
para quien ninguna enfermedad es demasiado difícil.
Él ciertamente puede curar toda enfermedad,
y aliviar y rescatar a todos los que están cautivos y son oprimidos por el diablo,
aquellos que vienen a Él y esperan en Él en el camino
de Sus juicios justos y tiernas misericordias.
Porque después de toda mi religión y profundas pruebas,
experiencias y conocimientos internos, llegué a tal pérdida de lo que alguna vez tuve,
que sentí de manera palpable que no conocía al Señor,
y continué en pos de Él gimiendo y llorando.
¡Oh, la luz pura, la preciosa vida, la dulce presencia de mi Dios que mi alma no tenía,
a tal punto que mi verdor se convirtió en sequedades de verano,
y mis huesos se secaron y se marchitaron!
Pero al fin, el Señor en Su bondad,
sopló sobre mis huesos secos y sentí que la vida pasó de Él a mí,
y los días de profunda tristeza y angustia fueron finalmente olvidados,
porque el niño varón había sido concebido y dado a luz.
Y ahora, ¿dónde está el cilicio?
¿Dónde están las cenizas?
¡Oh, hay belleza en la vida,
en lugar de cenizas en el estado sin vida! ¡Hay un vestido de alabanza,
en lugar del espíritu de pesadez! ¡Oh, gloria,
gloria Al que venda a los heridos y quebrantados
de corazón! ¡Gloria al Redentor de los cautivos,
al Reparador de brechas, al Edificador de los desgastados y desolados!

[.alt]
==== I. Con respecto a la Semilla del Reino

Con respecto a la Semilla del reino esto es lo que he experimentado:
Que no consiste en palabras o ideas de la mente, sino en algo interior;
es una sustancia interior y espiritual en el corazón tan real internamente en Su género,
como lo son las otras semillas externamente según su género.
Al ser recibida por fe, esta Semilla echa raíces en el hombre (en su corazón,
en su tierra, tras ser arada y preparada para Ella), crece en el interior,
y produce fruto en el interior tan verdadera y realmente,
como cualquier semilla externa lo hace externamente.
Esta Semilla es conocida por Su oposición y enemistad contra la simiente de la serpiente,
y contra todas las semillas del mal en los corazones de los hombres.
Las descubre, hace que la mente se aparte de ellas, pelea contra ellas,
las hiere y las vence en todos aquellos que La reciben.
También deja entrar Su propia naturaleza santa, que como levadura o sal santa,
expulsa lo que es impuro e injusto, lo que es oscuro y muerto, y sazona el alma con luz,
con vida, con gracia, con la santidad y justicia de la verdad.

[.alt]
==== II. Con Respecto a la Comida del Alma

La comida del alma es la comida que la nutre, la misma que le da vida.
Cada palabra procedente de la boca de Dios, cada movimiento, cada vivificación,
cada operación de Su Espíritu es vida y nutre el
alma (que la recibe y se alimenta de ella) con vida.
El maná espiritual, el agua espiritual del pozo o fuente santa, la leche de la palabra,
la carne y sangre del Hijo del Dios vivo, Sus palabras que son espíritu y vida,
todo nutre el nacimiento vivo para vida eterna.
¿Cómo llega a vivir un hombre al principio, sino por oír la voz del que da vida?
¿Y cómo llega a vivir un hombre después y a crecer en la vida, sino por oír la misma voz?
"`Inclinad vuestro oído, y venid a mí; oíd,
y vivirá vuestra alma,`" (Isaías 55:3) He experimentado que esto también me da vida,
me nutre y me fortalece en la vida, es decir,
me comunica vida fresca desde la Fuente viva.
Por tanto, mi vida no está en mí mismo,
ni en nada que yo pueda comprender con respecto a Cristo, no; sino en ser unido a Él,
en ser injertado en Él (la raíz santa, el verdadero árbol de olivo), en Su Espíritu.
Así, por medio de la savia que brota en mí desde Él,
mi vida es mantenida e incrementada en mí día a día. ¡Gloria a Su nombre para siempre!

[.alt]
==== III. Con Respecto al Poder de Dios

Con respecto al poder de Dios, esto es lo que he experimentado:
Que es el poder de Dios el que hace la obra en el alma.
Este engendra para Dios, saca de la tierra de tinieblas,
conduce a través de todas las marañas y preserva en medio de todas ellas.
Derriba el viejo edificio de pecado e iniquidad (tanto interna como externamente,
tanto en el corazón como en la vida y conducta), y levanta el edificio nuevo y santo.
Da el querer, da el obedecer, da la habilidad de creer y sufrir.
¡Oh, bendito sea el Señor por el día de Su poder,
el cual ha irrumpido internamente! ¡Benditos los que experimentan
la ministración de la vida en el interior,
del poder de vida internamente!
Porque en la vida, en la Semilla de vida está el poder santo que se manifiesta,
aparece y obra en la medida que gana terreno en la criatura,
ejercitando en ella la virtud y fuerza que diariamente recibe del Padre.

[.alt]
==== IV. Con Respecto a las Tentaciones

Con respecto a las tentaciones, esto es lo que he experimentado:
Que la fuerza y el dolor de ellas, en cuanto al alma, radica en que el alma las mire.
Porque Dios revela Su fuerza en Sus hijos contra el tentador,
la cual nunca les fallará al esperarla pacientemente y confiar en ella.
El Señor no desea que ni siquiera el más pequeño caiga en tentación y pecado,
sino que se mantenga vigilante y unido a eso que
lo preservará fuera de toda tentación y pecado.
"`Mirad a mí, y sed salvos, todos los términos de la tierra.`"
Esto es universalmente cierto.
"`¡Mírenme a Mí, confíen en Mí y no se miren a sí mismos,
ni confíen en sí mismos! ¡No miren al enemigo, no teman al enemigo, porque Yo,
en la medida que mantengan firmes sus ojos sobre Mí,
los salvaré de cada trampa y de cada tentación!`" ¿Qué pasa si el enemigo entra
como una inundación? Si el Espíritu del Señor levanta un estandarte contra él,
¿puede prevalecer?
¿Y si lanza dardos de fuego?
¿No los apagará todos el escudo de la fe?
¿Acaso no es toda la armadura de Dios suficiente para defender
y mantener a salvo el alma de todos ellos?
Si el enemigo es resistido correctamente (es decir,
en la fe verdadera en el poder que está obrando contra el enemigo en el alma),
¿no se levanta el poder del Señor y lo esparce,
y fortalece y establece el alma en la gracia y verdad?
¡Oh, no miren al enemigo! ¡No dejen entrar los razonamientos de la mente,
más bien manténganse en la paciencia,
manténganse en el temor puro y en el juicio santo
y vivo! ¡Únicamente sean lo que son en la Semilla,
en el nuevo nacimiento, en la vida que Dios ha engendrado en ustedes,
porque entonces estarán a salvo, estarán en el nombre del Señor, que es la torre fuerte!
Es cierto que el enemigo puede hacer ruido en ustedes con sus deseos,
con sus tentaciones, con sus inundaciones, con sus tormentas, con sus dardos de fuego,
pero no puede entrar a la habitación de ustedes.
El espíritu de tinieblas,
el príncipe de las tinieblas está excluido de la tierra de los vivos.
¡Permanezcan ahí! ¡Habiten en la luz, caminen en la luz, como Dios está en la luz,
y el enemigo nunca tendrá poder sobre ustedes!

[.alt]
==== V. Con Respecto a la Oración

He experimentado que la oración es la respiración del nacimiento
engendrado por Dios hacia el Padre de vida que lo engendró,
quien por medio de Su Espíritu le da a conocer su condición y sus necesidades,
y le da clamores perceptibles por ellas.
Porque así como no está en poder del hombre engendrarse a sí mismo para Dios,
tampoco puede orar a Dios en su propia voluntad y tiempo,
sino únicamente cuando Dios derrama el Espíritu de oración y súplica sobre él,
y mediante Su Espíritu lo enseña y le ayuda a orar como debe.
"`Y por cuanto sois hijos, Dios envió a vuestros corazones el Espíritu de su Hijo,
el cual clama: ¡Abba, Padre!`"

Yo he tenido experiencia del hombre natural y del hombre espiritual,
y de los clamores y oraciones de cada uno.
Y esto es lo que me ha sido enseñado y he aprendido de Dios:
Que la oración del evangelio es la oración del nacimiento
que es engendrado por el Espíritu y poder del evangelio,
que ora en el Espíritu y en el surgimiento de la vida y poder santos.
De esta manera, la oración lucha correctamente con Dios y prevalece,
obteniendo las misericordias y bendiciones por las que lucha
con Él. Porque este niño tiene acceso a Dios en la fe,
a través del Espíritu Santo de vida que le abre camino para
que obtenga gracia y misericordia en el tiempo de necesidad.
Y es también a través de este Espíritu,
que ora a Dios y prevalece ante Él a favor de otros.
Como está escrito: "`Porque la oración eficaz del justo, puede mucho.`"

[.alt]
==== VI. Con respecto a la Justificación y Santificación

Le ha placido al Señor, en Su tierna misericordia, darme la experiencia de lo siguiente:

Primera, que es el mismo Cristo, el mismo Espíritu, la misma vida, la misma sabiduría,
el mismo poder, la misma bondad, amor y misericordia, la misma agua, la misma sangre,
tanto lo que justifica como lo que santifica.

Segunda,
que la justificación y la santificación son tanto de la gracia como a través de la gracia.
Así es en el principio y así es todo el tiempo.
"`Por gracias sois salvos,`" dice el apóstol.
Toda la obra de salvación es comenzada y llevada a cabo por la gracia.
Es a través de ella que Dios visita y alcanza el alma con su vivificante virtud y poder.
Él regenera por medio de la gracia, y a través de ella justifica, santifica, etc.
Así que, en la medida que continúa la obra, "`¡gracia,
gracia!`" debe ser el ruego Al que hace la obra;
desde que pone Su fundamento y afirma el alma en este,
hasta que coloca Su piedra superior.
(Zacarías 4:6-7)

Tercera, que la fe y la obediencia son de la misma naturaleza, y siempre van juntas,
así que donde hay fe, también hay obediencia, y donde hay obediencia, hay fe.
La obediencia fluye de la fe y no puede existir sin ella,
pues la naturaleza y virtud mismas de la fe están en ella.
Y la fe es obediencia.
Pues este es el mandamiento de Dios,
que el alma crea en Aquel (y en Sus apariciones) que Él ha enviado a salvar.
De hecho, este creer es obediencia Al que lo manda.
Esta fe y esta obediencia son santas y justas a los ojos de Dios,
y a través de ellas (pero no sin ellas) el alma es tanto justificada como santificada.

Cuarta, que las obras de la fe, las obras de la nueva vida,
no son las obras de la ley u obras del antiguo pacto.
Y que las obras de la fe no son excluidas de la justificación,
como sí lo son las obras del antiguo pacto.
Pues he descubierto que el Señor,
quien ha condenado y excluido todos los actos que
yo haya sido capaz de hacer por mí mismo,
aún justifica y acepta lo que Su Espíritu y santo poder hacen en
mí. Estas no son de la misma naturaleza que las obras de la ley,
ni son consideradas de esa naturaleza ante los ojos del Señor,
porque Él distingue entre raíz y raíz. Todo lo que brota de la raíz santa,
Él lo justifica como santo; todo lo que se levanta de la raíz impía,
Él lo condena como impío.

Quinta, que por la ley de la fe toda jactancia es excluida de la totalidad de la obra,
tanto de la justificación como de la santificación. Porque, ¿cuál es la ley de la fe?
¿No es su ley ir a recoger todo del Hijo y hacerlo todo en el Hijo?
¿No es dejar el yo y su propia habilidad,
y realizar todas las cosas en la novedad del Espíritu,
en la habilidad que da Dios y continúa suministrando,
en y a través de Su gracia y misericordia, al alma que está en el Señor Jesucristo?
Aquí corren todas las venas de la vida, todos los arroyos del nuevo pacto.
Aquí no hay jactancia de la criatura, ni puede haber,
porque todas las habilidades y fuerza del hombre son excluidas,
y lo que es dado por Dios está en todos y lo hace todo.
Sin embargo, todo judío interior "`tiene alabanza de Dios.`"
(Romanos 2:29) Su fe es elogiada, su amor es elogiado, su fidelidad es elogiada,
su celo por el Señor, su obediencia al Señor, su paciencia en el sufrimiento es elogiado, etc.
Pero nada de esto redunda en alabanza y honor para su carne,
sino para el Espíritu y gracia de Dios en él. De modo que
la carne es humillada y mantenida en el polvo para siempre,
y sólo Dios es exaltado en el corazón en el día de Su poder puro.

El que verdaderamente cree entra en el reposo.
¿Cómo en el reposo?
¿De qué reposa?
Bueno, de sus propias obras, de las obras de la carne.
Sí, reposa de las obras del antiguo pacto,
de las obras que surgen de su propia habilidad,
de las obras en las que no puede ser justificado con la justificación del evangelio.
Pero, ¿cesa él de las obras de la fe?
¿Cesa él del trabajo del amor?
¿Cesa él de la obediencia a cualquier cosa que Dios requiera?
No, más bien empieza a obrar y a trabajar en la viña y su trabajo no es en vano en el Señor.

[.alt]
==== VII. Con Respecto a la Fe

Con respecto a la naturaleza,
virtud y operaciones de la fe he experimentado varias cosas,
algunas de las cuales (según sienta que brotan vívidamente
en mi corazón) las puedo mencionar en este momento.

En primer lugar, esto lo he experimentado a menudo:
Que es cosa difícil creer verdadera y correctamente.
Es fácil creer en los conceptos con respecto a Dios y a Cristo, pero creer en Dios,
creer en Cristo, creer en Aquel que levantó a Jesús, creer en la luz,
vida y poder que fluyen de Jesús, esto en verdad es difícil,
debido a la gran oscuridad e ignorancia en las que
ha caído el hombre a través de la transgresión.

En segundo lugar, también he experimentado esto:
Que la fe es don de Dios y que ella fluye del poder de Su vida.
Primero hay un movimiento vivificador,
un toque del poder santo y puro del Señor al corazón. Luego,
sólo cuando el hombre es tocado y vivificado en,
por y a través de esa virtud que fluye en él,
puede creer en eso que lo toca y lo vivifica.

En tercer lugar, que la fe nunca está en el poder del hombre, no;
siempre está en la virtud y poder de la vida del Hijo,
para que el que quiera creer correctamente,
espere sentir la vida del Hijo revelada en él y la fe fluyendo de Él.
Porque la verdadera creencia brota de la vida de la raíz santa,
y es del fluir y brote de esa vida que la fe recibe su nutrición y virtud día a día.

En cuarto lugar, he observado lo siguiente en mis viajes:
Que cuando la sabiduría terrenal y sus conceptos se meten en la mente,
y son mantenidos en ella fuera de la experiencia de la vida,
son un gran obstáculo para la fe.
Porque estos fortalecen y nutren esa parte del hombre que
debe debilitarse y morir si alguna vez el verdadero nacimiento
de la vida reinará en el corazón. El hombre debe morir,
el hombre debe cesar, su entendimiento y su sabiduría deben ser reducidos a nada.
Sin embargo,
después de haber recibido el golpe y la herida del
Espíritu Santo y poder de Dios (es decir,
la herida que dirige a la muerte),
buscará vida de nuevo (intentando sanar su herida mortal) y la alimentará
por medio de los mismos conceptos que salían de la
vida y poder que en medida lo habían matado.
De esta manera el judío externo encuentra su vida en el conocimiento externo,
en la ley externa, en la letra que mata.
Porque en realidad,
las descripciones y el conocimiento externo de las cosas matan y embotan más y más,
a menos que el hombre entre en la vida y virtud interior.
"`Si viven en el Espíritu, caminen en el Espíritu,`" dijo el apóstol.
El hombre no puede vivir en el conocimiento externo acerca
del Espíritu y del poder de una vida indestructible.
El que quiera vivir verdaderamente, debe vivir en el Espíritu mismo,
y el que quiera caminar correctamente en Su camino,
debe caminar en el Espíritu en el que recibió la vida.

En quinto lugar, he observado esto también:
Que el enemigo dejará en paz y no molestará al alma que
tiene una fe intelectual (la fe que carece de virtud viva),
en cuanto a Cristo, Sus sufrimientos, muerte, resurrección, ascensión, intercesión,
justificación por medio de Él, etc.
En cambio, este luchará desesperadamente contra la verdadera fe,
contra la fe en el verdadero poder, contra la fe en la luz de la vida.
¡Oh,
cuántos ataques dolorosos y agudos acomete contra la fe que recibe su virtud de Dios
y hace que el alma viva para Dios! ¡Cuánto dolor hay en el alma cuando la fe es débil
y el enemigo viene contra ella con la fuerza de sus ataques y tentaciones! "`Señor,
aumenta nuestra fe,`" dijeron los discípulos prudentes.

En sexto lugar,
que es en el temor puro (no el que es enseñado por los preceptos de los hombres,
sino el que Dios pone en el corazón) que la fe tiene su fuerza y ejercita su fuerza.
¡Oh, quien conociera el valor inapreciable de este temor!
El poder de la fe, el poder de la vida, el poder de la salvación,
de la preservación eterna, todo es revelado en él. Por tanto,
cuando el Señor habla de proveer para Sus hijos un nuevo pacto dice:
"`Pondré mi temor en el corazón de ellos, para que no se aparten de mí.`"

Ahora le corresponde a cada uno considerar profundamente de qué naturaleza es su fe,
y qué virtud hay en ella.
Qué puede hacer esta en y a través del poder del Señor para él. Si en
verdad recoge la verdadera y viva nutrición cada día. Si libera
el alma y le da victoria sobre aquello que la fe fue designada vencer.
Porque aquel que a través de la fe vence lo que es contrario a Dios, recibe la herencia,
y aquel que pelea la buena batalla de la fe, vence.
Pero el que no venza a los enemigos que se interponen en su camino,
con toda certeza será estorbado por ellos para que no alcance el fin de su viaje.

[.alt]
==== VIII. Con Respecto a la Obediencia

En primer lugar, que la verdadera obediencia, la obediencia del evangelio,
fluye de la vida, fluye de la fe viva.
Si yo pudiera obedecer todas las cosas que Dios requiere de mí,
no me satisfaría a menos que sintiera que mi obediencia fluye del nacimiento
de Su vida en mí. "`Mi Padre hace todo en mí,`" dijo Cristo.
Este era el consuelo de Cristo; y sentir a Cristo haciéndolo todo en el alma,
es el consuelo de todos los que creen verdaderamente en Él.

En segundo lugar, que la verdadera obediencia, la obediencia del evangelio,
es natural para el nacimiento que nace de Dios.
No es natural para la carne ni para la sabiduría del hombre,
negarse a sí mismo o tomar la cruz,
pero sí es natural para el nacimiento que nace del Espíritu de Dios.
"`Lo que es nacido del Espíritu,
espíritu es,`" y es natural para este nacimiento estar familiarizado
con lo que es espiritual y ser ejercitado por ello.

En tercer lugar, que honrar,
agradar y responder a la voluntad del Señor es el
objetivo apropiado de los verdaderos obedientes.
¡Oh,
cuánto se deleitan haciendo la voluntad de Dios! "`Yo tengo
una comida que vosotros no sabéis,`" dice Cristo.
Hacer la voluntad era Su comida y bebida,
y es la comida y bebida para todos los que son de Su naturaleza y Espíritu.
Si yo nunca experimentara otra recompensa aparte del deleite de la obediencia,
no podría dejar de testificar que en el obedecer la ley de vida pura,
y guardar los santos estatutos y mandamientos del Espíritu de Dios,
hay una gran recompensa.
Y que también hay una corona y una cosecha después de esta vida,
de todo lo que es sembrado para el Espíritu.

¡Bendito el que se encuentra con el poder de la vida que le permite obedecer,
y bendito el que es obediente y se sujeta a dicho poder!
Porque el que verdaderamente cree en Cristo es vuelto
por Él a Su luz y al poder de Su Padre,
y en la sujeción a este se experimenta toda la paz, el crecimiento, el gozo,
la bendición, etc.

[.alt]
==== IX. Con Respecto a la Cruz de Cristo

Esto es lo que he experimentado con respecto a la cruz de nuestro Señor Jesucristo:
Que ella es algo interno y espiritual,
y que produce efectos internos y espirituales en la mente.
Porque la cruz de Cristo es la que mata la enemistad
en la mente y crucifica al mundo y sus pasiones.
"`Pero lejos esté de mí gloriarme, sino en la cruz de nuestro Señor Jesucristo,
por quien el mundo me es crucificado a mí, y yo al mundo,`" dijo el apóstol.
Noten, eso que es contrario al mundo y crucifica al mundo, es la cruz.
Sólo la cruz tiene ese poder, nada más; así que no hay nada más en qué gloriarse.
"`Porque el deseo de la carne es contra el Espíritu,
y el del Espíritu es contra la carne; y éstos se oponen entre sí.`" Esta es la cruz:
El Espíritu, el cual es contrario a la carne, el cual hace morir la carne,
en la obediencia del cual la carne es crucificada.
"`Mas si por el Espíritu hacéis morir las obras de la carne,
viviréis.`" Todo lo que es del Espíritu y está en Él, es contrario a la carne.
La luz del Espíritu es contraria a las tinieblas de la carne.
La santidad del Espíritu es contraria a la impiedad del corazón corrupto.
La vida del Espíritu es contraria a la vida (o más bien, muerte) que está en pecado.
El poder del Espíritu es contrario al poder que está en Satanás y su reino.
La sabiduría de Dios es contraria y locura para la sabiduría del hombre.
Sí, la nueva criatura, la que nace del Espíritu de Dios,
es contraria y es muerte para la vieja criatura.
Aquel que sale de su propia sabiduría, voluntad, pensamientos y razonamientos,
y llega al discernimiento del Espíritu de Dios,
a sentir Su engendramiento de vida en el corazón, espera y recibe consejo ahí,
este es enseñado a negarse a sí mismo,
y a unirse y tomar eso por medio de lo cual Cristo diariamente
crucifica y somete en él todo lo que es contrario a Dios.

Aquí sucede la batalla de la fe y el verdadero viaje bajo la cruz,
por el que los enemigos (que se levantan para oponerse
en el camino) son conquistados y vencidos.
Porque en la cruz es revelado el poder, el poder preservador, el poder guiador,
el poder conquistador de Aquel que cabalga en conquista
para conquistar a Sus enemigos espirituales,
en los corazones de Sus hijos.
Estos conocen Su voz y se someten a Él, y diariamente se niegan a sí mismos,
tomando Su cruz y siguiéndolo.
¡Ay de aquellos que están a gusto en Sion con lo que es contrario a Dios,
pero bendiciones sobre aquellos cuya morada está bajo la cruz y
no experimentan tranquilidad excepto en lo que esta permite!
Ella hará que la verdad, vida, santidad, justicia, fe, obediencia, mansedumbre,
paciencia, amor, separación del pecado,
comunión con el Señor y todos los frutos del Espíritu,
sean tan naturales para ellos en el estado renovado como
alguna vez les fue el pecado en el estado corrupto.
Porque hubo un tiempo en el que Pablo se quejó de su cautiverio,
y de como hacía lo que odiaba,
pero después de haber experimentado el poder de la
cruz y ser crucificado juntamente con Cristo,
no podía hacer nada contra la verdad, sino sólo por la verdad.
Sí,
habiendo llegado a ser un conquistador y habiendo
vencido a los enemigos que se interponían en su camino,
entonces podía hacer todas las cosas a través de Cristo que lo fortalecía.

La causa de tantas quejas y tanto lamento por el
predominio del enemigo (a través de las tentaciones,
pecado y corrupción), es porque la cruz de Cristo, la que es el poder de Dios,
es desconocida o no es tomada.
Esta es la razón por la que muchos que por un tiempo tienen buena apariencia,
después quedan en nada (son como higos fuera de temporada o como grano sobre los terrados,
que brotan apresuradamente, pero pronto se marchitan),
porque nunca aprendieron o se aferraron correctamente a la cruz.
Pues sólo la cruz tiene el poder de Dios para derribar y mantener sometido
lo que es contrario a Él. Pero fuera de la sujeción a la cruz de Cristo,
no hay experiencia de salvación o de preservación por parte del Señor. Fuera de los
límites de la cruz el enemigo tiene poder para recobrar y traer de regreso bajo su dominio.
Cualquiera que en su viaje deje la cruz atrás retrocede a la perdición,
y no puede viajar en la fe viva,
ni en la novedad de la obediencia hacia la salvación del alma.

[.alt]
==== X. Con Respecto al Misterio de la Vida y al Misterio de la Comunión que Está en Ella.

Dios está escondido del hombre en tanto este permanezca en el estado pecaminoso y caído,
y ningún hombre puede encontrarlo o conocerlo,
excepto cuando a Él le plazca revelarse a Sí mismo por medio de Su propio bendito Espíritu.
Cuando Cristo apareció en los días de Su carne, la carne y sangre no pudieron revelarlo,
sólo Su Padre.
Él es hoy el mismo que era ayer.
Él no debe ser conocido ahora, excepto en el mismo Espíritu,
en Su propia gracia y verdad, en la medida de Su propia vida.
Los muertos no pueden conocerlo, sino sólo aquellos que son Sus ovejas,
los que han sido vivificados por Él y han recibido la vida de Él.

Ahora bien, esta vida es un misterio,
nadie puede entenderla excepto aquellos que participan de ella.
¿Puede un hombre que está naturalmente muerto,
saber qué significa la vida de la naturaleza?
No más de lo que puede un hombre que está espiritualmente muerto,
saber qué significa la vida del Espíritu.
El hombre natural puede obtener las palabras que salieron de la vida,
declararlas y recomendarlas,
y hacer grandes declaraciones acerca de la fama de la sabiduría,
pero la cosa misma está escondida para él. ¡Sí,
cuán estrecha es la puerta a través de la cual entra el nacimiento,
y por la que nadie más puede entrar!
El sabio y entendido, aprendiz y escrutador según la carne (incluso de las Escrituras,
ya que ellos pueden poner sobre ellas significados y así comprenderlas),
son excluidos en todas las épocas.
Pero hay un bebé nacido de la verdad desnuda (nacido
de la sencillez pura) a quien Dios le permite entrar.

La comunión de los santos existe en la vida y en la luz, la cual es un misterio.
La comunión no es externa, sino interna.
Los que se reúnen en un lugar externo no están en comunión,
sólo los que se reúnen en la vida interior y en el Espíritu.
"`Los que adoran al Padre deben adorarlo en Espíritu y en verdad.`"
Ahí está la adoración y ahí están los adoradores.
Los que están en el Espíritu y en la verdad, los que se reúnen en Espíritu y en verdad,
están reunidos en el único lugar espiritual, por decirlo así. Por tanto,
no tenemos comunión con ningún hombre según la carne,
ni con ningún hombre según la apariencia,
pero tenemos comunión en el juicio justo del Espíritu, sólo con los que son del Espíritu.
De hecho,
somos tiernos cuando hay al menos un comienzo de la obra de Dios en cualquier corazón;
sí, donde apenas hay una convicción del entendimiento.
Pero los que aceptan nuestros principios en palabras o apariencia externa,
no son verdaderamente uno de nosotros,
sino aquellos que son internamente cambiados por ellos en el corazón.

[.alt]
==== XI. Con Respecto al Incremento del Reino

¿Acaso no era la gran doctrina de Cristo predicar el reino?
¿Y cómo lo predicó? ¿No lo predicó como una semilla, como un grano de mostaza?
¿No comparó esta Semilla espiritual con levadura, con una perla de gran precio,
con un tesoro escondido en un campo, con una moneda de plata perdida, etc.? ¡Oh,
cuán feliz es el que conoce y disfruta la cosa misma que Cristo
predicó! Todos los profetas profetizaron con respecto a Él,
y cuando vino, esta era Su doctrina:
Que los hombres deben ocuparse de esta preciosa Semilla, cuidarla, comprarla, poseerla,
sentirla plantada y creciendo en ellos, y a ellos mismos injertados y creciendo en Ella.

Ahora, hay muchos que hablan sobre el reino,
pero hay pocos viajeros hacia él. Sólo el que es
un verdadero viajero y encuentra su reposo ahí,
puede conocer con certeza y experimentar verdaderamente
lo que es ser hallado en el reino.
Esta es la razón por la que muchos (que parecen ser sabios
y entendidos) no pueden recibir nuestro testimonio:
Porque no conocen la Semilla ni Su voz,
con respecto a la cual y por medio de la cual testificamos.
Pero la sabiduría es justificada por sus hijos, y los que conocen la voz del Pastor,
experimentan Su aparición presente en nuestro día,
la cual es contraria a la sabiduría y conocimiento de todas las demás semillas y nacimientos.
"`El que tenga oídos para oír, que oiga.`"
Sin embargo, el que no tiene el oído verdadero, no puede oír el verdadero testimonio,
aunque le sea declarado a menudo.
Pero bendito el que conoce y no tropieza con las apariciones
de la Semilla y poder de la vida en su propio corazón,
sino que se vuelve de las tinieblas a la luz,
y del poder de Satanás a la manifestación del Espíritu
de Dios ahí. Porque el fin de las palabras (incluso,
las propias instrucciones de Cristo en los días de Su carne),
es volver a los hombres a la vida y al poder santo de donde provienen las palabras.
El verdadero viaje del alma es hacia eso,
esperando en el Señor en el camino de Sus juicios y tiernas misericordias,
para experimentar el traslado de las tinieblas a la luz
y del reino de Satanás al reino del amado Hijo,
cuyo reino al principio no es más que un grano de mostaza.

Y ahora, que cada corazón serio se examine: ¿Conoces el reino?
¿Está creciendo la Semilla en ti?
¿Se está extendiendo en ti?
¿Estás en Ella como en un reino?
¿La sientes empequeñecerte?
¿Estás en unidad con Ella?
¿Te habla paz del Señor? ¿Está derribada la pared de separación en ti?
¿Está hecho de los dos un hombre nuevo?
¿Sientes lo que es contrario a Cristo sometido en ti mediante Su poder?
¿Sientes Su naturaleza santa, Su vida santa y Su Espíritu Santo reinando en ti?
¿Experimentas la escritura que dice:
"`Mas si por el Espíritu hacéis morir las obras de la carne, viviréis`"?

¡Ah, cuánto hablan los hombres de Cristo y del poder de Dios, y sin embargo,
se pierden el efecto y la obra de Su poder en ellos!
La fe es algo poderoso, da victoria (la verdadera fe da victoria).
Ella dispersa lo que se interpone, da acceso real a Dios y deja entrar Su virtud pura,
fresca y viva en el corazón.

El amor es algo poderoso, constriñe a obedecer,
y el corazón que está circuncidado para amar al Señor Dios, ¡oh,
cuánta vida fluye de Él en este!

¡Oh, salgan de los conceptos vacíos y vengan a la ministración del Espíritu,
donde el conocimiento es vivo, la fe victoriosa, el amor puro e inmaculado,
la adoración verdaderamente espiritual, es decir,
que fluye y es comprendida en la vida y virtud del Espíritu! ¡Oh,
qué todos los que verdaderamente respiran en pos del Señor,
sean reunidos en la ministración del Espíritu, sean encontrados allí y habiten ahí! Amén.

=== Unas Pocas Palabras con Respecto al Verdadero Cristo

[.discourse-part]
Pregunta: ¿Cómo puede ser conocida la aparición interna y espiritual de Cristo?

[.discourse-part]
Respuesta:
La aparición interna debe ser conocida de la misma forma y por los mismos medios,
con los que fue conocida Su aparición externa: Por revelación del Padre.
Porque "`nadie conoce al Hijo sino el Padre, y aquel a quien el Padre se lo revele.`"
Cuando Simón Pedro confesó que Él era el Cristo, el Hijo del Dios vivo, Él le dijo:
"`Bienaventurado eres, Simón, hijo de Jonás, porque no te lo reveló carne ni sangre,
sino mi Padre que está en los cielos`" (Mateo 16:17). Ahora,
si nadie pudo conocer a Cristo en Su aparición en la carne (a pesar
de las muchas manifiestas y expresas profecías acerca de Él),
sino aquellos a quienes el Padre se los reveló,
¿cómo conocerá alguno Su aparición interna y espiritual,
a menos que sea enseñado por el Padre, y oiga y aprenda de Él?

El verdadero Cristo es conocido por la manifestación de Su vida en el interior,
por la plenitud de gracia y verdad que habita en Él y se muestra,
para que sea discernido por el ojo interno y espiritual en el hombre.
Él es conocido por Su voz y llamado a la puerta.
Sus ovejas conocen Su voz.
Él habla en la autoridad del Padre (no como los escribas,
ni como los sabios y entendidos terrenales).
Él habla en la evidencia y demostración del Espíritu de Dios.
Las palabras que Él habla son Espíritu y vida, y los que oyen Su voz, viven.
¡Oh, los azotes de Su mano sobre los tiernos y sensatos corazones y consciencias! ¡Oh,
Sus secretas reprensiones, sus secretas instrucciones,
su secreta vivificación e iluminación!

Él es conocido por medio de Su bautismo, es decir,
por Su bautismo en Su propio Espíritu y poder.
Mientras las personas estaban expectantes y se preguntaban
en sus corazones si Juan era o no el Cristo,
Juan respondió al asunto diciéndoles cómo podrían discernir y conocer al verdadero Cristo.
Dijo: No soy yo, que bautizo sólo con agua,
sino el que "`bautice con el Espíritu Santo y fuego,
y en cuya mano esté el aventador,`" etc.
(Lucas 3:15-17) El que conoce Al que bautiza interna y espiritualmente,
Al que tiene el aventador y purga y avienta la era,
recogiendo el trigo y quemando la paja, ¿no conoce interna,
verdadera y espiritualmente a Cristo?
El que conoce a la Palabra viva y eficaz, que es más cortante que espada de dos filos,
que penetra hasta partir el alma y el espíritu, y los huesos y las coyunturas,
y que discierne los pensamientos y las intenciones del corazón,
¿no conoce a la "`Palabra que estaba en el principio, la cual era con Dios`"?

Él es conocido por Sus poderosas obras.
"`Porque las obras que el Padre me dio para que cumpliese, las mismas obras que yo hago,
dan testimonio de mí,
que el Padre me ha enviado`" (Juan 5:36). Cuando Juan envió
a dos de sus discípulos a Jesús con la pregunta:
"`¿Eres tú el que había de venir, o esperaremos a otro?`"
Cristo los mandó ir y contarle a Juan las cosas que habían visto y oído:
"`Los ciegos ven, los cojos andan, los leprosos son limpiados, los sordos oyen,
los muertos son resucitados, y a los pobres es anunciado el evangelio;
y bienaventurado es aquel que no halle tropiezo en mí`" (Lucas
7:22-23). "`Pues esto es lo maravilloso`" dijo el ciego,
"`que vosotros no sepáis de dónde sea,
y a mí me abrió los ojos`" (Juan 9:30). El que tiene el poder y muestra el poder internamente,
abre el ojo interno, el oído interno, libera la lengua interna,
hace que los pies internos caminen en el camino de vida
y que las manos internas obren las obras de Dios,
este es el Mesías, el Salvador, la Palabra de vida, el Hijo del Dios vivo.
Los que creen en Él, en Su Espíritu, en Su poder, en Su aparición interna,
tienen al Testigo en sí mismos, el testimonio vivo,
el que nadie puede apagar o quitar de ellos.
¡Oh, Él ha abierto mis ojos, Él ha abierto mi corazón, Él me ha levantado de la tumba,
Él me ha dado vida eterna! ¡Él me ha cambiado internamente,
me ha creado internamente por medio de la obra de Su poderosa fuerza!
Ahora yo vivo cada día, y soy preservado y crezco por el mismo poder.
Siento Su vida, Su virtud, Su poder, Su presencia día a día. Él está conmigo,
Él vive en mí, y yo no vivo para mí mismo, sino sintiéndolo a Él vivir en mí,
descubriendo la vida que brota de Él en mí y a través de
mí. En esto radica toda mi habilidad y fuerza para siempre.
