== Capítulo 6. Un Llamado al Verdadero Cristianismo

Somos un pueblo que Dios ha reunido,
que largamente habíamos esperado Su aparición y sufrido
grande aflicción por la falta de ella;
al menos muchos de nosotros.

[.discourse-part]
Pregunta: Pero algunos preguntan,
¿qué aparición del gran Dios y Salvador les hacía falta a ustedes?

[.discourse-part]
Respuesta:
Nos faltaba que la presencia y el poder de Su Espíritu
fueran internamente manifestados en nuestros espíritus.
Teníamos, por decirlo así, lo que podíamos reunir de la letra,
y nos esforzábamos en practicar lo que leíamos en la letra,
pero carecíamos del poder de lo alto, carecíamos de la vida,
carecíamos de la presencia y comunión con nuestro Amado,
carecíamos del conocimiento de la Semilla celestial,
carecíamos del conocimiento del reino celestial y de la entrada a este,
y del dominio y reinado santos del Señor de vida sobre la carne,
el pecado y la muerte en nosotros.

[.discourse-part]
Pregunta: ¿Cómo les apareció Dios?

[.discourse-part]
Respuesta: El Sol de justicia se levantó en nosotros, la Aurora de lo alto,
la Estrella de la mañana nos visitó a tal punto,
que realmente vimos y sentimos la luz y el resplandor del día interior en nuestros espíritus,
como alguna vez sentimos las tinieblas de la noche interior.

[.discourse-part]
Pregunta: ¿Cómo los reunió Dios?

[.discourse-part]
Respuesta: Mediante la voz de Su Hijo, por medio del brazo de Su Hijo,
por la virtud de la luz y vida de Su Hijo internamente
revelada y obrando en nuestros corazones.
Esto nos liberó internamente de las tinieblas, de las ataduras del pecado e iniquidad,
del poder del captor y destructor,
y volvió nuestras mentes internamente hacia nuestro Señor y Salvador,
para que nos ocupáramos de Su aparición interna, de Sus brillos internos,
de Sus vivificaciones internas,
todo lo cual era vivo proveniente de Dios y lleno de virtud.
A medida que íbamos siendo conscientes de todas estas cosas, nos uníamos a ellas,
las recibíamos y nos rendíamos a ellas,
así íbamos siendo partícipes de la virtud de todas y experimentábamos
el rescate y redención de nuestras almas.
Para que cuando oyéramos la voz del Hijo y lo siguiéramos,
lo encontráramos siendo el camino al Padre y fuéramos
recogidos por Él en la casa del Padre,
donde hay suficiente pan y lugares de descanso y paz para todos los hijos del Altísimo.

Con respecto a la bendita Semilla de verdad,
de la que hemos tenido experiencia y testificamos (porque,
¿cómo podríamos ocultar tan rico tesoro y aún así ser fieles a Dios?),
no es algo nuevo en sí mismo, aunque últimamente es revelada más claramente,
y las mentes de los hombres son dirigidas y guiadas a ella más claramente,
que en épocas pasadas.
Esta Semilla no es otra más que aquella de la que Cristo mismo predicó abundantemente,
quien predicó el reino, quien predicó la verdad que hace libre,
quien predicó usando muchas parábolas y comparaciones.
A veces habló de una pequeña semilla,
a veces habló de una perla o de un tesoro escondido, a veces de levadura o de sal,
a veces de una pieza de plata perdida, etc.
Ahora, ¿qué es todo esto y dónde se encuentra?
¿Qué es esto que es como una semilla pequeña, una perla, etc., y dónde se encuentra?
¿Qué es el campo?
¿No es el mundo, y no está el mundo establecido en el corazón del hombre?
¿Cuál es la casa que debe ser barrida y en la que la candela debe alumbrar?
¿No es esta casa, o corazón, donde están los muchos enemigos?
Los enemigos del hombre, dice Cristo, son los de su propia casa.

El testimonio con respecto a todo esto en verdad era precioso para nosotros,
pero encontrar y experimentar la cosa testificada fue mucho más precioso.
Y lo siguiente lo decimos en perfecta verdad de corazón,
y en el más tierno amor a las almas de las personas: Que quienquiera que lo intente,
encontrará que esta cosa pequeña, que esta pequeña semilla del reino, es un reino,
es una perla, es un tesoro celestial,
es la levadura de vida que leuda el corazón con vida,
y con el más preciado aceite y ungüento de sanidad y salvación.
Así que nosotros no testificamos algo nuevo,
sino la verdad y gracia que eran desde el principio,
que siempre estuvieron en Jesucristo nuestro Señor y Salvador,
y que son dispensadas por Él en todas las edades y generaciones.
Porque es Él quien vivifica,
renueva y cambia los corazones de los verdaderos
creyentes en Su aparición interna y espiritual,
y el que, de esta manera,
destruye a los enemigos en sus propias casas y los salva de ellos.
Porque en realidad, no hay salvación para la criatura,
sin destruir en la criatura lo que trae muerte y destrucción espiritual sobre ella.
El Israel antiguo fue salvado por la destrucción de sus enemigos externos,
y el Israel de ahora (el nuevo Israel,
el Israel interno) es salvado por la destrucción de los enemigos internos.
¡Oh,
si las personas pudieran salir de su propia sabiduría y esperar la sabiduría de Dios,
para que en ella lleguen a ver la gloria, excelencia,
virtud y tesoros de vida extremadamente ricos que
están envueltos en esta Semilla de vida!
Entonces la recibirían, se rendirían a ella y llegarían a participar de ella.

Con respecto a las doctrinas, nosotros no tenemos nuevas doctrinas que sostener.
Las doctrinas expuestas en las Sagradas Escrituras son las doctrinas que creemos.
Y esto sella para nosotros aún más nuestra creencia en esta Semilla,
porque encontramos que ella es la llave por la que Dios abre las Escrituras para nosotros,
y pone en nuestros corazones el sentido vivo y la evidencia de ellas.
Podemos ver y hemos sentido a quién le pertenecen la maldición y la ira,
y también a quién le pertenecen el amor, la misericordia, la paz,
la bendición y las preciosas promesas.
Hemos sido llevados por el Santo Espíritu de Dios y poder, a través de los juicios,
a la misericordia y participación de las preciosas promesas.
Entonces, ¿por qué publicaríamos alguna nueva fe o alguna nueva doctrina?
En realidad, no tenemos ninguna que publicar,
pues nuestro único objetivo es llevar a los hombres a la antigua Semilla de verdad,
y al correcto entendimiento y práctica de la antigua doctrina apostólica y fe santa,
que fue entregada a los santos en otro tiempo.
Los conceptos de la cabeza sólo causan disputas, pero el conocimiento del corazón,
la experiencia del corazón, el palpable poder vivo de Dios en el interior,
la evidencia y demostración de Su Espíritu en lo íntimo, ponen fin a las disputas,
y por medio de eso que es nuevo y vivo,
establece a los hombres en el viaje interior y ejercicio de espíritu.

Ahora, muchos se sienten ofendidos por nosotros,
porque no predicamos más puntos doctrinales,
o no hacemos más referencia a la historia de Cristo con respecto a Su muerte,
resurrección, ascensión, etc.
Pues en realidad,
nuestra declaración y testimonio son principalmente con respecto a la Semilla,
y nuestro deseo es dirigir y guiar las mentes de los hombres a ella.
Por tanto,
a fin de ofrecer un relato claro de esto (según le plazca al Señor
abrir mi corazón en este momento en amor y buena voluntad),
y satisfacer y eliminar los prejuicios donde sea que estén, diré en resumen lo siguiente:

En primer lugar,
después de experimentar una gran pérdida debido a
nuestro conocimiento literal de las cosas,
Dios nos ha dado experiencia y nos ha encomendado a testificar del misterio,
de la vida escondida,
de la aparición interna y espiritual de nuestro Señor
y Salvador Jesucristo revelando Su poder internamente,
destruyendo a los enemigos internamente y haciendo
Su obra internamente en el corazón. ¡Oh,
esto fue un sonido jubiloso para nuestras almas, es decir,
las buenas nuevas del levantamiento de esa vida y
poder en el interior que pueden hacer eso!
Ahora bien, esta aparición interior Suya fue posterior a Su aparición en la carne,
y es la dispensación permanente y duradera del evangelio, es decir,
es la aparición de Cristo en Su Espíritu y poder
en el interior de los corazones de los Suyos.
Para que en tanto nos ocupemos de esta, y seamos fieles en este asunto,
cuidemos nuestra obra particular y seamos fieles en lo que
Dios nos ha llamado y ha requerido de nosotros claramente.

En segundo lugar, la necesidad de publicar la otra no es tan grande como lo era antes.
El relato histórico con respecto a Cristo es generalmente creído y recibido,
por todas las personas que profesan el cristianismo.
Su muerte, Sus milagros, Su resurrección, Su ascensión, Su intercesión, etc.,
es generalmente creído por todas las personas.
Pero se pierden el misterio, no conocen la vida escondida,
y están separadas de la vida de Dios en medio de
su aceptación y reconocimiento literal de esas cosas.

En tercer lugar, el conocimiento de estas (doctrina, historia, etc.),
sin el conocimiento del misterio, no es suficiente para llevar a dichas personas a Dios.
Porque muchos se conforman con lo que han reunido
y comprendido del relato con respecto a la cosa,
en lugar de la cosa misma,
y por eso nunca llegan al sentido de su verdadera necesidad o de cómo buscarla correctamente.
Entonces, muchas son edificadoras y muchas se levantan muy alto en religión,
en una forma de conocimiento y práctica,
pero no están familiarizadas con la Roca de las edades,
no tienen el verdadero conocimiento y entendimiento del Fundamento y Piedra angular.
Quiero decir, tienen una noción de Cristo como la roca,
una noción de Él como la piedra del fundamento,
pero nunca llegan vívidamente a sentirlo como la roca,
a experimentarlo internamente colocado como la piedra del fundamento en sus corazones,
y a conocerse a sí mismas como piedras vivas en Él y edificadas
sobre Él. ¿Dónde se siente esto sino dentro?
Y aquellos que sienten esto dentro, ¿no sienten a Cristo dentro?
¿Puede alguien que lo siente a Él dentro,
negar que Él es la fuerza de vida y la esperanza de gloria?
Bueno, es cierto una vez más (espiritualmente ahora, como literalmente entonces),
que "`la piedra que desecharon los edificadores`" (Cristo dentro,
a quien los edificadores de esta época desechan),
"`ha venido a ser la cabeza del ángulo.`"
Él teje en este día, Su cuerpo santificado, Su cuerpo vivo, la iglesia,
más gloriosamente que en las épocas y generaciones anteriores.
¡Bendito sea el nombre de nuestro Dios!

En cuarto lugar, el misterio, la vida escondida, la aparición de Cristo en Espíritu,
abarca el conocimiento externo, así que este no se pierde o se niega,
más bien se encuentra, se discierne y se reconoce más clara y abundantemente.
Porque lo interno debía ser después de lo externo,
y de esta manera abarcar lo que estaba antes.
Pablo no perdió nada del excelente conocimiento de Cristo cuando dijo:
"`De manera que nosotros de aquí en adelante a nadie conocemos según la carne;
y aun si a Cristo conocimos según la carne,
ya no lo conocemos así.`" Si él no conocía a Cristo según la carne,
¿cómo lo conocía? Bueno,
conforme el Padre lo revelaba internamente en él. Él lo conocía en Su Espíritu y poder.
Él conocía internamente Su muerte, conocía internamente Su resurrección,
conocía internamente el Espíritu, virtud y poder de este.
Él conocía la cosa en el misterio, en su propio corazón. ¡Oh,
qué precioso conocimiento! ¡Sí,
la excelencia de este conocimiento de mi Señor y Salvador Jesucristo!
¿Qué es el conocimiento externo más exacto y literal sin este?

¿Entonces qué? ¿Ahora niego o menosprecio el externo?
No, sino que lo tengo aquí, en lo interno.
Porque por la vida y las enseñanzas internas del Espíritu de Dios,
soy enseñado y capacitado para valorar aquella gloriosa aparición externa,
y manifestación de vida y poder de Dios en la carne
celestial (como la he llamado a menudo en mi corazón),
pues la vida habitaba en dicha carne de modo tal, que incluso era una con ella.
Sin embargo, todavía era un velo y el misterio estaba detrás de ella,
pero el ojo de vida mira el misterio a través del velo y lo atraviesa (por decirlo así),
para que se pueda contemplar su gloria en el interior.

=== El Camino de Paz

[quote.scripture]
____
Y no conocieron camino de paz. --Romanos 3:17
____

Hay un camino de paz, de verdadera paz con Dios,
quien es adversario de todo lo que es impío e injusto.
Aquellos que han sido impíos e injustos, que han sido despertados, perturbados,
y no han podido encontrar reposo (sino que han encontrado los severos
y justos juicios de la ira del Señor sobre sus espíritus noche y día),
después de que Él finalmente les abrió sus oídos,
y los llevó del camino impío e injusto al camino santo y justo,
han encontrado tanto la vida como la paz en este.

Ahora bien,
el apóstol menciona aquí dos clases de personas (o dos estados)
que no han conocido ni pueden conocer el camino de paz con Dios.
Porque el Señor es adversario de ambas, y un día les hablará confusión a ambas,
cuando sus almas y consciencias sean escrutadas y juzgadas por Él.

Uno es el estado profano o estado gentil, el cual carece del sentido de Dios,
no le presta atención a ninguna aparición de Él,
ni a ninguna voz interior de Su Espíritu,
ni a la escritura de Su ley sobre su corazón. Estos no conocían el camino
en el que el corazón es interna y espiritualmente circuncidado y renovado,
perdonado del pecado y obtiene paz.

El otro es el estado profesante o estado del judío externo,
aquel que puede estudiar la letra y dedicarse a conformarse externamente a la letra,
pero que no conoce al Espíritu, ni el poder interior.
Estos difieren grandemente del estado gentil o profano,
tanto en apariencia externa como en su propia estimación,
pero están sobre el mismo terreno que los gentiles,
y no conocen más del camino de paz que los otros.

[.discourse-part]
Pregunta: Pero, ¿cuál es el camino de paz, que ni el profano,
ni ningún tipo de profesante fuera de la vida y del poder,
nunca conocieron ni pueden conocer?

[.discourse-part]
Respuesta: Es un camino interno, un camino para los judíos internos,
en el que los internamente renovados y circuncidados caminan.
Es un camino santo o santificado para que los santificados caminen.
Es un camino vivo, el cual nadie sino los vivos pueden encontrar.
Es un camino nuevo, el cual nadie sino aquellos a quienes Dios le has dado el ojo nuevo,
pueden ver.
Es un camino que Dios prepara y establece,
en el que conduce los espíritus de los hombres (de los que Lo oyen),
y por el que guía los pies de Sus santos.
Es un camino recto y estrecho,
el que ningún deseo de la carne ni sabiduría de la carne puede descubrir,
o entrar en él. ¡Oh, cuán pequeño, cuán bajo, cuán pobre, cuán vacío,
cuán desnudo debe ser aquel que entra en este camino y camina en él! Muchos
pueden buscarlo y pensar que pueden encontrarlo y caminar en él,
pero pocos podrán,
tal como ha dicho nuestro Señor. Aquí la circuncisión externa no vale nada,
y la falta de dicha circuncisión no es un estorbo.
Aquí el ejercicio corporal para poco es provechoso.
Aquí hay una nueva creación y la cruz de Cristo lo es todo, el poder de Dios lo es todo,
y el que camina de acuerdo a esta regla,
la paz es sobre él y sobre todo el Israel de Dios.
Pero el que no conoce esta regla, ni camina de acuerdo a esta regla,
la paz no está sobre él, ni es parte del Israel interno de Dios,
de aquellos que reciben la potestad de ser hechos hijos,
y reciben la ley del Espíritu de vida en Cristo Jesús,
quien es la regla interna del Israel interno.

Este era el camino de paz desde el principio, este es el camino de paz todavía,
y no hay otro.
En ser creado de nuevo en Cristo Jesús, ser injertado en Él, permanecer en Él,
tener la circuncisión de la carne (el cuerpo del pecado de la carne eliminado) por medio
de la circuncisión de Cristo (hecha internamente en el corazón sin manos),
caminar no según la carne sino según el Espíritu, es decir, en la novedad del Espíritu,
están la vida y la paz, el reposo y el gozo para siempre.
¡Qué el Señor en Su tierna misericordia les dé a los hombres un sentido de esto,
y guíe a los hombres a esto más y más! Amén.

=== El Fin de Todo

Hay un nacimiento que no nace de carne, ni de voluntad de carne,
ni de voluntad de hombre, sino de Dios.
(Juan 1:13) Este nacimiento que nace del Espíritu, es espíritu.
(Juan 3:6) Este nacimiento que nace del Espíritu y que es espíritu,
tiene una vida y una forma de conocimiento adecuadas para su naturaleza y ser,
que están muy por encima del hombre.
Su vida es en el Espíritu,
su caminar es en el Espíritu y su conocimiento es según la manera del Espíritu,
muy por encima de la manera de concebir o comprender del hombre.
El nacimiento mismo es un misterio para el hombre,
y su manera de conocer es una manera que está completamente escondida para el hombre.
Porque este conocimiento es la evidencia y demostración del Espíritu de Dios,
por medio del resplandor de Su luz en el corazón: "`En tu luz veremos la luz.`"
El verdadero nacimiento conoce el significado de esto.

Ahora bien, hay una parte sabia y entendida en el hombre,
de cuya vista Dios esconde Su reino y la gloria celestial del mismo.
Pero también hay un bebé a quien Dios le revela Sus misterios.
La carne y sangre no pueden revelar, pero el Padre puede y lo hace a Sus hijos,
pues Él es el maestro de todos ellos en el pacto nuevo y vivo,
en el que desde el más pequeño hasta el más grande lo conocerán.
Está el día del hombre y está el día de Dios.
En el día del hombre, este reúne conocimiento según su manera carnal de comprender;
y en el día de Dios,
Él da conocimiento mediante los resplandores de la luz de Su propio Espíritu eterno.
En el día del hombre, ¡cómo se devana los sesos el hombre sabio y entendido,
y trabaja arduamente por mera vanidad!
Pero en el día de Dios, ¡cómo cubre el conocimiento del Señor la tierra,
así como las aguas cubren el mar!
Cuando la Aurora de lo alto visita internamente,
cuando el Señor enciende la candela internamente,
¡cuán claro es el conocimiento del Señor y cuánto abunda entonces! ¡Oh,
cuánta diferencia hay entre las comprensiones y conceptos
del hombre con respecto a Cristo,
y la revelación de Cristo que da Dios internamente! ¡Cuánta diferencia
hay entre el acercamiento del hombre a Cristo según sus propias comprensiones,
y su acercamiento a Cristo en las persuasiones y
enseñanzas celestiales del Padre! (Juan 6:45)

¡Oh, si el nacimiento de vida fuera sentido en los corazones de los hombres,
para que pudieran conocer el día de Dios,
el reino de Dios y los tesoros de sabiduría que están escondidos en Cristo,
y que siempre lo estarán a menos que Cristo sea internamente revelado y formado en el
corazón! Puede que muchos tengan una noción de que Cristo se está formando en ellos,
pero ¡oh, sentir esto internamente!
Ahí está la dulzura, seguridad, vida, paz y justicia del Señor Jesucristo,
y está el gozo del verdadero cristiano para siempre.
¡Vengan,
toda clase de profesantes tiernos! ¡Salgan de ustedes
mismos y entren en el Espíritu de Dios,
en la verdad de Dios,
para que puedan experimentar lo que es estar en el Espíritu y en la verdad,
lo que es vivir ahí y experimentar las cosas ahí,
adorar ahí y tener comunión con el Padre y con el
Hijo ahí! El pobre es el que recibe el evangelio,
el pobre es el que recibe el reino, el pobre es el que recibe el poder,
el pobre es el que recibe la justicia y la salvación de nuestro Señor Jesucristo.
Ustedes son demasiado ricos en sus propias comprensiones y en el
conocimiento reunido a partir de sus propios conceptos literales,
como para aprender a esperar correctamente, a recibir de Él Su oro, Su vestido,
Su colirio.
¿Qué placer tiene para nosotros testificar contra ustedes?
Si no fuera por obediencia a nuestro Dios y amor a sus almas, no lo haríamos.
Estamos contentos y satisfechos de ser del rebaño pequeño y despreciado,
el que alimenta el Pastor dándole a cada uno Su porción diaria de alimento, vida, paz,
justicia y gozo.
Es nuestro amor por ustedes,
la razón por la que no queremos que gasten su dinero en aquello que no es pan,
ni su esfuerzo en aquello que no satisfará al alma verdaderamente hambrienta y despierta.
Deseamos que se alimenten de la sustancia, de la vida misma,
de la dulzura y grosura de la casa de Dios,
donde ninguno de Sus hijos carece de lo que pueda necesitar o anhelar.
¡Oh,
si ustedes tuvieran el entendimiento de nuestro amor! ¡Si comprendieran
y experimentaran verdaderamente el amor de Dios,
no podrían evitar tener el entendimiento de nuestro amor también,
porque este proviene de Él y fluye hacia ustedes en Su voluntad y tiernos movimientos!

¿Aman ustedes a Dios?
¿Están sus corazones circuncidados para amar a Dios?
Si no es así, ustedes no aman verdaderamente.
Si ustedes amaran Al que engendra,
amarían a los engendrados por Él. El amor de ustedes
es hacia sus propias ideas y comprensiones de Dios,
no hacia la naturaleza de Él, porque si amaran Su naturaleza (esa naturaleza santa,
celestial y espiritual, tal como está en Él),
no podrían dejar de amarla en Sus hijos también. Bueno,
nuestro Dios es amor y Él nos ha enseñado a amar incluso a nuestros enemigos,
y a luchar con nuestro Dios por ellos, para que si fuera posible,
les elimine las escamas de sus ojos y les dé arrepentimiento para reconocer la
verdad como está en Jesús. Aquí conocerán que la verdad es viva y poderosa,
más eficaz y operativa (internamente purificadora, santificadora, sí,
y justificadora también) de lo que nadie sabe,
sino aquellos que han nacido de Dios y son mantenidos vivos por Él.

=== Los Hechos y Sufrimientos del Pueblo Despreciado Llamado Cuáqueros

Primero,
muchos consideran que los actos de ellos provienen de un
principio natural y de acuerdo al pacto de obras,
y no de la gracia y don gratuitos del Espíritu de Dios.

Ahora bien, con respecto a esto puedo hablar con cierta fidelidad,
como alguien que ha tenido una larga experiencia con este principio,
y que ha experimentado la gracia y tierna misericordia del Señor desde la infancia.
En realidad, ha sucedido así conmigo:
Desde mi niñez he sentido que todo lo que ha sido hecho en mí, o por medio de mí,
y que es bueno, viene de la gracia y misericordia de Dios hacia mí,
y he clamado "`gracia, gracia, misericordia,
misericordia`" al Señor continuamente por ello.
Y así, descubrí que cuando me volvía a Su verdad en lo íntimo,
la gracia y el tierno amor de Dios eran tanto lo
que me volvían como lo que me mantenían vuelto,
haciendo que la verdad brotara en mí día a día y que a través de ella se me diera capacidad.
Pero, oh, nadie sabe (además de los que han tenido experiencia),
cuánto hemos sido debilitados en la parte natural,
ni cuán pobres hemos sido hechos para que podamos recibir el evangelio.
¡Oh, cuán pobres somos mantenidos en nosotros mismos,
para que podamos gozar las riquezas y herencia del reino!
Diariamente experimentamos que Él nos salvó y nos salva,
no por obras de justicia que hayamos hecho, sino por Su misericordia,
por el lavamiento de la regeneración y la renovación del Espíritu Santo.
Sí, Dios ha escrito Su ley en nuestros corazones,
ha colocado Su temor en ellos y ha puesto Su Espíritu
dentro de nosotros para que nos ilumine y vivifique,
y nos haga caminar en Sus caminos, nos haga guardar Sus estatutos y juicios,
y nos haga cumplirlos.
Todo '`hacer morir`' el pecado y toda negación de los deseos de la carne,
además de toda ejecución de lo que es santo y aceptable a los ojos del
Señor (como lo es todo lo que procede de Su propio Espíritu Santo),
es del nuevo pacto y realizado por el funcionamiento del mismo.
No es por el funcionamiento de la parte natural misma, no,
sino por la operación del Espíritu de vida en el nuevo nacimiento,
usando la parte natural sólo como instrumento Suyo.
De modo que nadie critique las obras que Dios produce en nosotros
(quien nos ha creado de nuevo en Cristo Jesús para buenas obras),
para que no menosprecie al Espíritu Santo y poder del Dios vivo,
en quien estas son forjadas y mediante el cual estas son manifestadas.

Luego, en cuanto a nuestros sufrimientos, en realidad son dones que recibimos de Dios,
de modo que podemos decir verdaderamente,
que nos es dado por el Señor nuestro Dios no sólo creer en Su Hijo,
sino padecer por Su causa.
Es sólo en la buena consciencia delante de Dios y por medio de la ayuda del Señor,
que sufrimos,
de modo que la paciencia y mansedumbre con que sufrimos no son de nosotros mismos,
sino de Él. Cada vez que el Señor permite que nos sobrevengan aflicciones o sufrimientos,
nuestros ojos están hacia Él y entramos en ellos en Su temor,
conociendo nuestra propia incapacidad para atravesarlos,
y mirándolo en busca de fortaleza.
Y mientras estamos en ellos, diariamente Lo miramos para que nos fortalezca,
y cuando en muchas ocasiones hemos sido muy débiles en nosotros mismos,
de inmediato o muy poco después, hemos sentido una gran fortaleza en el Señor. Además,
pasados nuestros sufrimientos,
después de que el Señor ha estado con nosotros todo el tiempo y
nos ha llevado a través de ellos en la paz y el gozo de Su Espíritu,
no miramos hacia atrás con jactancia,
como si hubiéramos sido algo o hubiéramos hecho algo por nosotros mismos.
Más bien, nos inclinamos delante del Señor y Lo bendecimos,
al ver cómo ha estado con nosotros,
y cómo nos ha sostenido con la mano derecha de Su justicia.

Por tanto, que nadie critique, tergiverse o denigre nuestros sufrimientos,
a través de los cuales nuestro Dios nos ha ayudado,
y por los que nosotros Le damos gracias con corazón humilde.
Pues no podemos dejar de dar gracias a Dios todos los días,
porque el recuerdo agradecido y la experiencia de ellos
están escritos en nuestros corazones por el dedo de Su Espíritu.
¡Oh, si todos los tipos de personas,
a quienes amamos y por las que sufrimos dolores de parto,
experimentaran la aparición interna y las visitas del Pastor y Salvador de nuestras
almas! ¡Vuélvanse a Él (mirando en la verdadera fe hacia Él) y sean salvos!
Yo les digo, en ternura de espíritu, ¡oh,
no nos paguen tan equivocadamente por nuestro amor y verdad de corazón hacia ustedes!
Nuestro amor verdaderamente proviene del Dios de amor.
Nosotros no podríamos amarlos como lo hacemos, si nuestro Dios no nos hubiera enseñado.
Ni podríamos buscarlos como lo hacemos, en ternura de corazón,
si no fuéramos instrumentos en la mano del Pastor de Israel.
La luz de la que testificamos, la cual sentimos brillar en nosotros,
no es otra cosa que la verdadera y segura luz del Sol de justicia,
la cual Dios ha hecho brillar en nuestros corazones, quien además ama a la humanidad,
y hace que brille en los rincones más oscuros de la tierra.
La vida por medio de la cual somos vivificados y resucitados del pecado y la transgresión,
y la potestad que hemos recibido de llegar a ser hijos de Dios,
provienen de Aquel que es la fuente de vida y tiene toda potestad en el cielo y la tierra.
¡Ojalá recibieran el bendito testimonio! ¡Ojalá el brazo del Señor se revelara en ustedes!
¡Ojalá pudieran sentir y experimentar al Salvador obrando Su salvación en ustedes,
atando al hombre fuerte en ustedes,
y echándolo de ustedes junto con todos sus bienes! ¡Oh,
que ya en ustedes no se encuentre lugar para el malvado,
que ninguno de sus deseos o vanos pensamientos se alojen en sus corazones,
sino experimenten y sean testigos del nuevo corazón, del corazón limpio,
del corazón puro, en el que Dios mora, sí,
y experimenten el ojo que ve Al que es invisible!

=== Un Llamado al Verdadero Cristianismo

Es fácil profesar a Cristo, pero ser un verdadero cristiano es algo muy precioso,
y muchas tribulaciones y profundas aflicciones se deben atravesar antes de alcanzarlo.

La eterna felicidad y salvación ahora dependen del verdadero cristianismo.
No dependen sólo de tener el nombre de '`cristiano,`'
o de profesar tales y cuales doctrinas cristianas,
sino de tener la naturaleza del cristianismo, de ser renovados por el Espíritu de Cristo,
de recibir al Espíritu, caminar en el Espíritu y manifestar los frutos del Espíritu.
¡Sí, en realidad esto es ser cristiano,
y todos deben tener cuidado de no quedar cortos de esto!
Ahora bien,
debido a que hay una disputa acerca del cristianismo
(en cuanto a quien es el cristiano correcto),
le corresponde a cada hombre preocuparse por sí mismo,
para recibir de Dios y ser hecho por Él,
eso que nadie sino el verdadero cristiano puede ser.
Siendo que he tenido alguna experiencia de esto,
que he entendido cuál es el estado del cristiano y qué lo acompaña,
quiero establecer las siguientes cosas que el verdadero cristiano conoce,
experimenta y disfruta internamente.

Primero, el que es una nueva criatura es sin duda un verdadero cristiano.
El que es regenerado, el que es renovado en el espíritu de su mente por Cristo Jesús,
el que es nuevamente creado a la imagen santa y celestial,
el que ha sentido el poder del Espíritu de Dios engendrándolo de nuevo,
formándolo de nuevo, sacándolo de la vieja naturaleza e imagen del primer Adán,
e introduciéndolo en la naturaleza e imagen del segundo Adán (quien es el Espíritu vivificante),
es, en efecto, un cristiano.

Segundo, el que está en el nuevo pacto es el verdadero cristiano.
El hombre que ha tenido sed del agua viva, ha oído el llamado a las aguas de vida,
ha oído la voz del que da vida y ha recibido vida de Él (al tomar su cruz y seguirlo),
es sin duda una oveja de Cristo, a quien el Pastor reconoce y cuida.

Tercero, el que es internamente circuncidado con la circuncisión hecha sin manos,
es judío en el interior, es cristiano en el interior (ante los ojos de Dios).
Este ha sentido al Espíritu y poder del Señor, se regocija en Cristo Jesús,
y es uno de los adoradores a quienes Dios ha buscado y ha
enseñado a adorarlo en la vida y Espíritu de Su Hijo.

Cuarto, el que es internamente lavado con agua limpia, con el agua interna,
es judío en el interior, es cristiano en el interior.
Dios prometió derramar agua limpia sobre Su Israel y que serían limpios.
El que tiene el agua limpia internamente derramada sobre él,
la que lava y limpia internamente, es sin discusión, uno del Israel interno de Dios.

Quinto,
el que se alimenta del pan de vida interno y bebe
el agua de vida de su propio pozo o cisterna,
sin duda está vivo.
El que es invitado a la cena de las bodas del Cordero, y acude y cena con el Cordero,
es de la misma naturaleza y espíritu con Él. Aquel con quien Cristo cena,
que ha oído a Cristo tocando a su puerta,
Le ha abierto y Lo ha recibido para que purifique su corazón, more en él y cene con él,
de modo que come pan en el reino, bebe vino en el reino,
participa de los manjares suculentos que Dios hace para Su Israel en Su monte santo,
es sin duda, de Cristo y participa de todo esto en y a través de Él.

Sexto, el que vive la vida cristiana, no anda según la carne, sino según el Espíritu,
ni satisface los deseos de la carne,
sino que tiene la ley de Dios escrita en su corazón y Su temor puesto dentro de él,
es en verdad un cristiano.
Al que le ha sido dado el Espíritu Santo para instruirlo y guiarlo a que responda
a la santa ley escrita en su corazón (a la cual la mente carnal no se sujeta,
ni puede sujetarse), es sin la menor duda espiritual; es un verdadero cristiano.

Séptimo, el que vive por fe, conoce la fe que es don de Dios,
la ha recibido y vive por ella, es un verdadero cristiano.
Tal hombre no puede hacer nada por sí mismo, no;
sólo por fe en ese poder santo que lo hace todo en él, de modo que vive,
cree y obedece desde la raíz santa de vida, la que hace que la vida brote en él,
que el amor brote en él,
que la mansedumbre y la paciencia del Cordero broten en él y que toda gracia
brote en él. El hombre que vive en esta forma está sin ninguna duda,
injertado en la verdadera vid, en el verdadero árbol de olivo.
La verdadera raíz lo sostiene y ministra savia en él, y es una rama verdadera, fresca,
verde y viva de la verdadera vid, del árbol de olivo santo.

Muchas cosas más podrían ser mencionadas,
ya que son conocidas y sentidas por experiencia entre aquellos que son verdaderos cristianos,
pero estas las mencioné para dar una probadita.
El que conoce y siente estas cosas puede también conocer y sentir el resto;
el que no conoce o siente estas, no conocerá o sentirá el resto,
incluso si fueran mencionadas muchas más. La manera de sentir estas cosas
y de llegar a ser un verdadero cristiano (y crecer en la vida cristiana),
es sintiendo la Semilla del reino (la cual es el principio del reino,
el principio del verdadero cristianismo), y luego, sintiéndola permanecer.
Este es el sello constante del cristianismo en mi
corazón. Estas son las verdaderas y seguras evidencias,
día a día, de la naturaleza y espíritu del cristianismo,
manifestándose a sí mismas interna e innegablemente.

Y ahora, teniendo al Testigo en mí, testificando Su propia obra y Su propio nacimiento,
¿de qué valor son los testimonios de hombres contra esto?
El cristianismo es un misterio,
y el verdadero cristiano es el que tiene abierto el ojo interno,
con el que es enseñado por Dios a penetrar en lo que consiste el cristianismo.
Han existido muchos cristianos hechos por los hombres, y otros hechos por Dios y Cristo.
¡Oh,
que los hombres tengan cuidado de que cuando Dios
venga a diferenciar entre ovejas y ovejas,
(entre cristianos y cristianos),
sean hallados parte de lo que la voluntad de Dios reconoce como ovejas de su rebaño! Oh,
qué seamos hechos capaces de soportar la prueba de Su juicio escrutador,
de su ojo puro e imparcial,
y no seamos hallados como aquellos que aún son hacedores de iniquidad,
que no han sido creados nuevamente en Cristo Jesús para buenas obras y, por tanto,
que no son verdaderamente de Él.
