== Capítulo 7. A los Judíos Según la Carne y Según el Espíritu

=== Primero: A la Semilla de Abraham Según la Carne

¡Oh, la gloria de tu estado externo,
tú que eras el pueblo al que una vez Dios escogió y amó,
y a quien manifestó Su poder y presencia más que a todos los demás
pueblos! ¡Tu tierra era la gloria de todas las tierras,
a la que Dios te llevó sacándote de Egipto por medio de Su brazo extendido,
y atravesando el terrible desierto en el que fuiste tentado, probado y ejercitado! ¡Oh,
qué leyes, estatutos y justos juicios te dio Dios,
como ninguna otra nación tenía! ¡Qué templo tenías para presentarte delante de Dios,
y el arca del pacto, los sacerdotes santos, los reyes y profetas! ¡Oh,
cuán cerca estaba Dios de ti para que le preguntaras,
y cuán listo estaba Él para oír tus oraciones en todo lo que le pidieras!
El eterno Dios era tu refugio,
y debajo estaban los brazos eternos (el Señor era tu roca y tú
fuiste edificado sobre Él). Él echó de delante de ti al enemigo,
y mientras el brazo del Señor los destruía tú habitabas confiado.
Él era para ti fuente de agua viva y Sus cielos destilaban grosura sobre ti.
¡Bienaventurado tú, oh Israel! ¡Quién como tú,
pueblo salvado por Jehová! Y en verdad habría seguido siendo así para ti,
si no hubieras desatendido a la Roca que te engendró,
y olvidado al Dios que te formó. Pues tu gloria no debía ser quitada de ti,
sino sorbida en una gloria mayor,
en la que habrías tenido la primera y más importante participación,
si no hubieras (por tu casi constante rebelión e
incredulidad) provocado al Señor contra ti.
Porque Él fue movido no sólo a afligirte,
sino finalmente a desecharte por completo de ser el pueblo,
y a escoger otro en tu lugar que le diera mejores frutos al Señor de la viña,
de lo que tú habías hecho.

Sin embargo, cuando tu estado era glorioso,
ese no era el estado de la gloria verdaderamente duradera y sustancial,
sino un estado o representación en sombra de la misma.
Tu día de gloria no era el día del Mesías, el día de la eterna luz interior,
en el que sólo el Señor es exaltado internamente en los corazones de todos,
donde Él derriba todo lo que es contrario a la luz de Su día. Tu día no
era más que el día de las sombras externas de la sustancia celestial,
y cuando ese día (el día de la sustancia y de la gloria en el interior) brilló,
tus sombras, o estado de sombra,
fue destinado a desaparecer y a ser sorbido en la
sustancia pura y reino espiritual del Mesías.

Tu nacimiento de Abraham según la carne no era el nacimiento
que iba a heredar la promesa en el reino del Mesías. Hay,
sin embargo, un nacimiento interior del Espíritu, que nace según la fe de Abraham,
que viaja internamente como lo hizo Abraham externamente,
y que busca en el interior una tierra y una ciudad cuyo arquitecto y constructor es Dios.
A este pertenecen el reino y las promesas espirituales.

Tu circuncisión no era más que la circuncisión externa, la circuncisión de la carne;
esa no era la circuncisión del corazón. La circuncisión
del corazón es para el judío interior,
la que de hecho,
la Escritura requería de ti (porque había algo cerca
de ti que te habría circuncidado así,
si hubieras escuchado y te hubieras rendido a ello, Deuteronomio 30:14). Pero tú,
como pueblo, no estabas circuncidado así,
sino que eras un pueblo de dura cerviz (como Moisés y los profetas se quejaron de ti),
incircuncisos de corazón y oídos,
resistiendo al Espíritu de Dios en sus propios corazones y en los profetas,
hasta que el Señor fue provocado a quitarte tanto la visión como al profeta.

El Egipto donde tus padres eran esclavos y el faraón los oprimía,
no era sino el Egipto externo y el faraón externo.
Hay un Egipto interno, en el que la semilla espiritual en el hombre interior, el alma,
está en esclavitud.
Hay un faraón espiritual que oprime la semilla espiritual en el Egipto espiritual,
y está el brazo del Todopoderoso internamente extendido,
para quebrantar la fuerza del faraón interno,
traspasar a Leviatán la serpiente tortuosa y liberar al alma de su cautiverio.

De igual forma, el desierto por el que tus padres fueron conducidos,
no era más que el desierto externo,
donde fueron tentados y probados por el Señor de muchas maneras,
para que Él pudiera hacerles bien al final.
Pero el Israel interno, después de que es sacado del Egipto interno,
es tratado en el desierto interno.
Aquí son juzgados según la carne,
y eso que no entra ni hereda la buena tierra es arrasado en ellos.
Aquí son tratados en el horno de aflicción,
sus inmundicias son purgadas por el espíritu de juicio y quemadas.
Entonces la nación justa, la que ha recibido la ley santa e interna y guarda la verdad,
puede entrar en la buena tierra, ciudad y reino del Mesías,
y heredar las benditas promesas de vida y salvación allí.

Moisés, tu gran profeta, era tipo del grande, perpetuo e inconmovible Profeta,
a quien Dios levantaría como a Moisés,
quien daría Su ley interna como Moisés dio la externa,
y conduciría a todo el Israel espiritual como Moisés condujo al Israel externo.
Su palabra debía ser oída y permanecer en todas las cosas que Él le dijera a Su pueblo,
y cualquiera que no oyera ni obedeciera a este Profeta,
tendría que ser cortado de entre el pueblo santo, espiritual e internamente vivo.
(Deuteronomio 18:15)

Josué, quien sucedió a Moisés, condujo hacia un reposo figurativo;
él no era más que una figura de Aquel que internamente guía al reposo interno y espiritual,
al que los verdaderos judíos (quienes son internamente creados y formados por Dios,
y son un pueblo dispuesto en el día de Su poder) entran.

La columna de nube y la columna de fuego en el desierto,
no eran más que figuras de la columna de nube y fuego espiritual,
mediante la que el Israel espiritual es guiado y defendido en el
glorioso día del evangelio del Espíritu y poder de Dios.
Lean Isaías capítulo 4, que habla del día del evangelio,
y de la columna y nube de fuego que sería creada en este,
y de la defensa que estaría sobre toda la gloria interna y espiritual.

La tierra de Canaán, la tierra y el reino externos de Israel,
no eran sino figuras de la tierra y reino internos del Israel
interno en los días del Mesías. Esta es la tierra de Judá,
en la que se canta cántico debido a la fuerte ciudad interna,
en la que Dios designa la salvación como muros y antemuros.
A esta ciudad entra la nación justa que guarda la verdad.
(Isaías 26)

Los reyes externos en esa tierra, y particularmente David,
no eran más que tipos del Rey espiritual, del David espiritual,
a quien Dios levantaría para el pueblo espiritual
que busca al Señor su Dios y a David su rey.
Él será el pastor y gobernante espiritual de ellos,
Aquel a quien Dios ha designado para que los alimente en la integridad de Su corazón,
y los guíe por medio de la habilidad de Sus manos,
quien es Rey de justicia y paz internamente,
y ministra justicia y paz a las ovejas y corderos de Sus pastos.

Los sacerdotes externos (incluso los sumos sacerdotes),
no eran más que una representación del gran Sumo Sacerdote de Dios,
quien sería sacerdote para siempre según el orden de Melquisedec.
(Salmo 110:4)

El pacto externo (hecho desde el monte Sinaí externo, en el otorgamiento de la ley,
estatutos y ordenanzas santos,
mediante los cuales ellos debían vivir y deleitarse en Dios en su estado externo),
no era sino una sombra del pacto interno y espiritual,
el nuevo y eterno pacto que Dios hace con Su pueblo
interno y espiritual en los postreros días.

La ley externa, que estaba escrita y grabada en tablas de piedra,
no era más que una sombra de la ley interna,
la que Dios pone en los hijos del nuevo pacto,
a fin de que no necesiten buscar externamente aprender el conocimiento de Dios,
Su voluntad ni Su ley.
Más bien, el Israel espiritual encuentra la ley escrita dentro de él,
y las costas que esperan la ley del Espíritu de vida, por la ley del Mesías,
reciben la ministración de la ley (en el Espíritu y poder del Mesías) que esperan.

El Monte Sión externo, sobre el que Salomón construyó el templo externo (aquel rey sabio,
justo y pacífico), era una figura de la montaña interna,
sobre la que es construida la casa interna en los días del evangelio,
en los días del Mesías; a esta montaña sube y adora el pueblo espiritual.
Esta es Sión y Jerusalén (es decir, el Sión interno y espiritual),
de las que la ley y la palabra del Señor salen en los días del Mesías.
Aquí la casa espiritual de Jacob acuerda caminar en la luz del Señor,
quien envía Su luz y verdad, y los conduce a Su monte santo y a Su tabernáculo.

El tabernáculo y el templo externos, santificados por Dios para morar y aparecer ahí,
eran una sombra del lugar de habitación de Dios en el interior del hombre;
"`Yo moraré en ellos.`"
Dios no mora en casas o templos hechos por manos; ese no es el lugar de Su reposo,
como dice el profeta Isaías. Más bien, el Alto y Sublime que habita en la eternidad,
cuyo trono es el cielo y la tierra el estrado de Su pie,
también habita con el que es de espíritu humilde y contrito,
para revivir el espíritu del humilde y el corazón del contrito.

Los días de reposo externos no eran el Día de reposo perpetuo o reposo del evangelio;
esos fueron dados como señal. Pues el día de redención del pecado,
el día de reposo del pecado, el día en el que cesan las obras de la carne,
el día en el que Dios es todo y hace todo internamente mediante Su Espíritu y poder,
en el que sólo Él es exaltado,
es el Día de reposo que el Señor ha hecho para el Israel espiritual,
en el cual ellos se alegran y se gozan.

De la misma manera,
el incienso y los sacrificios no eran el incienso ni los sacrificios eternos,
sino sombras de los mismos.
Porque las oraciones de los santos,
cuando Dios derrama el Espíritu de oración y súplica sobre ellos, y ellos oran en Él,
es el incienso: "`Sea puesta mi oración delante de Ti como incienso,
el alzar de mis manos como la ofrenda de la tarde.`"
Este era el incienso y la ofrenda pura que debían ser ofrecidos
al nombre de Dios entre los gentiles en todo lugar,
porque Su nombre debe ser grande entre ellos, como predice Malaquías. Y,
¿qué dijo David cuando el Espíritu de Dios y la visión santa
estaban sobre él? "`Sacrificio y ofrenda no te agrada;
has abierto mis oídos; holocausto y expiación no has demandado.
Entonces dije: He aquí, vengo; en el rollo del libro está escrito de mí:
El hacer tu voluntad, Dios mío, me ha agradado,
y tu ley está en medio de mi corazón. Los sacrificios de Dios son
el espíritu quebrantado (desgarren sus corazones y no sus vestiduras,
y vuélvanse al Señor su Dios).
Al corazón contrito y humillado no despreciarás tú, oh Dios.`"
La ofrenda de alabanza a Dios desde un corazón sincero
y el correcto ordenamiento de la vida,
son los sacrificios que complacen a Dios.
Porque los sacrificios no eran lo que Dios requería principalmente del Israel externo,
sino: "`Obedezcan Mi voz.`"
Porque la obediencia es mejor que todos los sacrificios,
y el prestar atención que la grosura de carneros escogidos.

Además,
esos sacrificios externos no podían eliminar o quitar el pecado de la consciencia,
pero Aquel que vino a hacer la voluntad de Dios y a ponerle fin a esos
sacrificios y oblaciones (los cuales no eran más que externos e imperfectos),
lava y quita los pecados del interior,
y también trae justicia eterna donde Su luz brilla
y Su vida pura brota internamente en el corazón.

Ahora esta es la sustancia de todas las sombras, es decir, la Luz eterna,
la Palabra eterna, el Hijo del Dios vivo (Quien es luz como el Padre es luz),
la Palabra cerca en la boca y el corazón,
la Palabra del nuevo pacto a la que Moisés dirigió a tus padres (Deuteronomio 30),
y por medio de la que el Señor habla y ha hablado a lo largo y ancho del mundo.
(Salmo 50) Es por esta Palabra que Dios enseña a todo hombre que escucha Su voz,
que haga justicia, ame misericordia y camine humildemente con su Dios,
como es expresado por el profeta Miqueas.

Ahora a ustedes judíos de la línea externa de Abraham,
(cuyo regreso al Señor mi alma anhela fervientemente,
y por lo que he orado vehementemente al Señor),
hay unas cuantas preguntas de peso en mi corazón:

[.discourse-part]
__Pregunta 1:__ ¿Cómo llegó a clamar David en pos del Dios vivo,
"`como el ciervo brama por las corrientes de las aguas`"? ¿Acaso
no era por la virtud vivificante de esta Palabra interna,
a la que Moisés, el hombre de Dios, había dirigido la mente?
Lean el Salmo 119 y vean cómo respiraba él por vivificaciones de esta Palabra,
de la que todo depende.
Ahora bien, si ustedes llegan a experimentar esta Palabra y la vivificación de la misma,
y siguen al Señor en ella, pronto conocerán el día del Mesías y la gloria de Su reino,
el cual no es externo, transitorio, ni de una naturaleza perecedera, sino interno,
espiritual y eterno (como David bien lo sabía y habló conscientemente,
ver Salmo 145 y otros lugares).

[.discourse-part]
__Pregunta 2:__ ¿Cuáles son las aguas a las que toda alma sedienta está invitada?
(Isaías 55) ¿Acaso no son las aguas del Mesías? ¿Acaso no son las aguas que fluyen de
los pozos de salvación? (Isaías 12) ¿No tiene que sacar el Israel espiritual agua espiritual
de los pozos del Salvador en los días del Mesías? ¿Qué es venir a estas aguas?
¡Ojalá lo conocieran por experiencia!
Pero quiero decirles lo siguiente, a partir de una experiencia verdadera y cierta,
que si ustedes toman nota de esta Palabra de vida, la que Dios ha colocado cerca,
en sus bocas y corazones, inclinan su oído a Ella,
y se apartan de lo que es reprobado en ustedes conforme los atrae a Sí misma,
sus almas pronto van a llegar a vivir.
Y El que les da vida hará un pacto eterno con ustedes, es decir,
las misericordias firmes de David, pero deben estar quietos y escuchar al Testigo,
Líder y Comandante internamente en sus corazones,
para que puedan ser preservados en el pacto y disfrutar las bendiciones del mismo.
Vean Isaías 55.

[.discourse-part]
__Pregunta 3:__ ¿No vino el Mesías en el tiempo establecido,
en el tiempo establecido por el Espíritu Santo de profecía? ¿No
vino en un cuerpo preparado para hacer la voluntad de Dios?
¿No hizo Él Su voluntad?
Y después de obedecer a Su Padre, ¿no fue cortado, aunque no por Sí mismo?
(Daniel 9:26) Y después de ser cortado, ¿no fueron ustedes (Israel natural) desolados?
¿Por qué fueron desolados?
¿Por qué vino sobre ustedes, como nunca antes, semejante golpe?
¡Considérenlo!
Lean Daniel 9:24 hasta el final del capítulo, y que el que lea, entienda.

[.discourse-part]
__Pregunta 4:__
¿Cuál era esa maldición y sobre quien cayó? "`Que la mesa
delante de ellos se convierta en lazo,`" etc.
(Salmo 69) ¿No fue sobre los que le dieron a beber al Mesías hiel y vinagre,
de quien David era figura, y de quien él habló en el Espíritu?
¿Cuyos ojos siempre son oscurecidos?
¿No permanece el velo sobre toda tu nación? ¿Conocen la montaña interna,
donde el velo que cubre es destruido en el día y en la luz internos del Mesías? ¿De
qué les sirve leer a Moisés y a los profetas cuando el velo permanece sobre ustedes,
y no pueden ver lo que debe ser abolido, y está abolido,
por el amanecer del glorioso día del Mesías? Aquí existe un judaísmo,
existe una circuncisión, existe un Día de reposo, existe un reposo, etc.,
para el pueblo interno y espiritual, que permanecerán y nunca serán abolidos.

[.discourse-part]
__Pregunta 5:__ ¿Cuál fue ese pueblo y nación con la que Dios los provocó a celos?
(Deuteronomio 32) ¿Acaso no fue el pueblo espiritual, la santa nación interna,
el verdadero judío, a quien Dios tomó de entre los gentiles?
¿No fueron aquellos en quienes Él apareció y para quienes era Dios y Padre,
cuando apartó y abandonó a los judíos externos y dejó que fueran desolados?

[.discourse-part]
__Pregunta 6:__ ¿Quiénes son los que tendrán hambre cuando los siervos de Dios coman,
y sed cuando los siervos de Dios beban, y vergüenza cuando Sus siervos se regocijen?
¿No están las almas de ustedes hambrientas y sedientas por falta de sustento espiritual,
con el que el Dios vivo satisface a Sus siervos en Su santa montaña interna?
¿Acaso no están avergonzados de sus expectativas del Mesías,
mientras que los siervos del Señor se regocijan en Él, Príncipe y Salvador de ellos,
y Lo experimentan diariamente como Líder y Comandante de ellos?
¿Cuál es el pueblo a quien el Señor ha matado y desolado?
(¿No son ustedes un pueblo muerto para Dios, separado de Su vida, Espíritu y poder,
muertos en sus conceptos y prácticas literales?) Y, ¿cuáles son los siervos del Señor,
a quienes Él ha llamado por otro nombre, es decir,
un nombre que ustedes nunca conocieron?
Vean Isaías 66. Consideren, cómo durante todo su día Dios les extendió Sus manos,
y ustedes fueron rebeldes y no quisieron oír. Pero ya ha llegado la noche sobre ustedes,
y su visitación, como pueblo, hace mucho tiempo que terminó. Vean Lucas 19:44

[.discourse-part]
__Pregunta 7:__ Ahora que el pueblo interno y el pacto interno, el nuevo pacto,
han sido manifestados,
¿alguna vez serán ustedes reconocidos o considerados de nuevo como el pueblo externo,
de acuerdo a su pacto externo?
¿Acaso no les fallarán todas esas expectativas para siempre?
Ustedes han buscado de generación en generación la venida y aparición del Mesías externamente,
según una manera externa, pero Su venida y aparición ahora son internas.
Porque Él establece Su reino, Su reino eterno,
en Sus santos y gobierna internamente en sus corazones; es ahí donde el Mesías,
la simiente de la mujer, hiere la cabeza de la serpiente.

¡Ojalá conocieran la sustancia! ¡Ojalá conocieran la Palabra
de vida en el corazón y se volvieran a ella,
y se mantuvieran fieles y obedientes día a día! Entonces La sentirían
demoliendo y asolando el poder del pecado y la corrupción en sus corazones.
Esta es la consolación, esperanza y gozo del Israel interno y espiritual.
¡Oh, que puedan ser hechos partícipes de este Israel,
y que el prolongado cautiverio externo y desolación
puedan al fin terminar en libertad y redención interna!
Amén.

=== Segundo: A la Semilla Espiritual de Abraham

[quote.scripture, , Génesis. 49:10]
____
No será quitado el cetro de Judá, ni el legislador de entre sus pies,
hasta que venga Siloh; y a él se congregarán los pueblos.
____

El anciano Jacob, en el espíritu de profecía, vio que Judá iba a tener el cetro,
el poder real, y que no se iba a apartar de este,
que iba a ser su derecho y que el legislador iba a ser suyo hasta que viniera Siloh.^
footnote:[El término "`Siloh`" en Génesis 49:10 proviene de una palabra oscura hebrea,
que se interpreta de diversas maneras como "`el enviado,`"
"`la semilla`" o "`el pacífico y próspero.`"
Cualquiera que sea la traducción correcta,
la palabra es universalmente aceptada como una referencia al Mesías.]
Entonces el derecho de reinar y de dar leyes a Su pueblo sería de Siloh,
a quienes Él recogería del reino de las tinieblas y del poder de Satanás,
en Su propio reino interno, espiritual y eterno.
Este era el verdadero Rey, el Rey de Dios,
a quien Él establecería sobre el monte santo del Sión espiritual,
y todas las reuniones santas, internas,
y espirituales del pueblo tienen que '`congregarse a Él.`'

"`A ruina, a ruina, a ruina lo reduciré, y esto no será más,
hasta que venga aquel cuyo es el derecho,
y yo se lo entregaré`" (Ezequiel 21:27). Su dominio no pasará,
el cetro y el poder legislador no pasarán de Él como pasó de Judá,
y Su reino jamás será destruido.
(Daniel 7:14) Porque Dios le dará el trono de David
Su padre y reinará sobre la casa de Jacob para siempre,
y Su reino no tendrá fin.

[.discourse-part]
Pregunta: Pero, ¿quiénes son las personas que '`se congregarán a Él`'?

[.discourse-part]
Respuesta:
Las personas que oigan Su voz y vengan a Su llamado recibirán la instrucción de sabiduría,
y sentirán la atracción del poder y de la virtud del Padre en el día de Su poder.
Está escrito en los profetas:
"`Y todos tus hijos serán enseñados por Jehová.`"
Todo el que es enseñado y aprende del Padre,
viene al Hijo, viene al Mesías, viene a Siloh, a la Palabra eterna,
a la Palabra de vida en el corazón.

[.discourse-part]
Pregunta: ¿Fueron excluidos entonces los judíos de esta congregación?

[.discourse-part]
Respuesta: No, ellos debían '`congregarse a Siloh,`' al igual que otros.
En realidad, el Señor les tenía una especial consideración,
pues el evangelio les fue predicado primero a ellos.
A ellos se les hizo la primera oferta o la primera invitación a la gloria espiritual.
Ellos eran los hijos de los profetas y del pacto que Dios hizo con sus padres.
Dios, habiendo levantado a Su Hijo Jesús, Lo envió a bendecirlos,
para que cada uno de ellos se volviera de sus iniquidades.
Y si la nación entera se hubiera vuelto de sus iniquidades, habría sido reunida por Él,
y se habría deleitado en la bendición de Su día y reino.
Porque realmente, la primera congregación fue entre ellos,
y la primera gloriosa iglesia del evangelio se ubicó en Jerusalén,
donde el Espíritu y poder del Señor Jesús irrumpieron eminente y maravillosamente,
y la gran gracia vino sobre todos.
Pero la nación en general no se '`congregó a Siloh,`'
ni se colocó bajo Su cetro ni bajo Su gobierno,
sino únicamente un remanente de la nación. Así que, cuando estos fueron reunidos,
el resto fue desechado,
la bandera fue llevada entre los gentiles y la gran reunión fue entre ellos.

[.discourse-part]
Pregunta:
¿Cómo es manifiesto que la gran '`congregación a Siloh`' iba a ser entre los gentiles?

[.discourse-part]
Respuesta: Por muchas expresas profecías de las Escrituras y promesas al Mesías,
que declaran que Él debía tener a los gentiles por herencia
y posesión. Cuando Dios estableció a Su rey,
al Mesías,
sobre el monte santo del Sión espiritual (a pesar
de toda la furia de los paganos contra Él,
y a pesar de la inútil imaginación del pueblo judío
al pensar que podían mantener Su cuerpo en la tumba,
el de Aquel que era la resurrección y la vida), ¿qué le dice el Señor a Él? "`Pídeme,
y te daré por herencia las naciones,
y como posesión tuya los confines de la tierra`" (Salmo 2:8). "`Regocíjate, oh estéril,
la que no daba a luz; levanta canción y da voces de júbilo,
la que nunca estuvo de parto.`"
El Señor dijo en otro lugar: "`Poca cosa es que Tú seas Mi siervo,
para levantar las tribus de Jacob y para restaurar a los que quedaron de Israel.
También Te haré luz de las naciones,
para que Mi salvación alcance hasta los confines de la tierra`" (Isaías 49:6; NBLH).
De nuevo el Señor dice más adelante: "`Porque desde la salida del sol hasta su puesta,
Mi nombre será grande entre las naciones,
y en todo lugar se ofrecerá incienso a Mi nombre, y ofrenda pura;
porque grande será Mi nombre entre las naciones,
dice el Señor de los ejércitos`" (Malaquías 1:11; NBLH).
"`Porque más son los hijos de la desamparada que los de la casada,
ha dicho Jehová`" (Isaías 54:1). ¿Quién era la casada?
¿Quién era la madre en los días del primer pacto?
¿No era la Jerusalén de abajo?
Y, ¿quién era entonces la desolada y estéril?
¿No era otra Jerusalén, la cual es libre y madre de todos los hijos espirituales?
¿Por qué tenía que regocijarse y cantar,
sino porque se iba a extender a la mano derecha y a la mano izquierda,
y su descendencia iba a heredar las naciones y habitar las ciudades desoladas?
(Versículo 3) Porque en realidad, el pacto del monte Sinaí dio a luz un gran pueblo,
del que la Jerusalén de abajo era la madre;
y el pacto hecho después aún era estéril y no había dado
a luz un pueblo para el Señor. Pero este segundo pacto,
y la Jerusalén de arriba,
iban a tener un tiempo en el que la Semilla de ella heredaría las naciones, y el Hacedor,
el Esposo, sería llamado el Dios de toda la tierra.
(Versículo 5)

Lean también Gálatas 4 y vean cómo el apóstol de los gentiles expone el misterio,
mostrando cuál es la mujer libre con sus hijos libres,
y cuál es la esclava con sus hijos de esclavitud.
Porque los hijos de esclavitud son arrojados en el día de
Dios y en el resplandor de Su celestial luz interior,
y no pueden heredar el glorioso reino del evangelio con los hijos de la libre.

Consideren ahora: ¿Cuáles personas alcanzaron misericordia en el tiempo del primer pacto?
¿Acaso no fueron los judíos? Y,
¿cuáles personas no alcanzaron misericordia (pues no eran pueblo),
sino que fueron dejadas fuera del amor y misericordia del primer pacto?
¿No fueron los gentiles?
¿Acaso no prometió el Señor que Él tendría "`misericordia de los que no habían
alcanzado misericordia`"? ¿No prometió Él decirles a los que no eran Su pueblo:
"`Tú eres mi pueblo,`" y que ellos le dirían:
"`mi Dios`"? (Vean Oseas 2:23 y compárenlo con Romanos
9:26) ¿No fue esto gloriosamente cumplido una vez?
¿No se cumplió gloriosamente de nuevo ahora al visitarlos
otra vez con el sonido fresco del evangelio eterno,
tal como fue prometido?
(Apocalipsis 14:6-7)

Pero, ¿por qué debería yo mencionarles más escrituras con respecto a esto,
cuando ustedes tienen una larga, plena, cierta y diaria experiencia de esto,
en eso que es puro y vivo?
Porque ustedes (Israel espiritual) han sido engendrados
por Su Espíritu a Su propia imagen y naturaleza,
y han recibido al Espíritu de adopción en el que
claman "`Abba Padre,`" al Padre de los espíritus.
Él los encontró en una tierra extraña,
bajo gran cautiverio y separación de Él. Ustedes han estado espiritualmente en Egipto,
en Sodoma, en Babilonia, pero la misericordia del Señor los ha seguido hasta ahí,
el brazo del Señor los ha alcanzado ahí y ha herido al Dragón. Sí,
Aquel a quien el Señor ha dado como luz a los gentiles, ha brillado para ustedes ahí,
en medio de su oscuridad.
Porque Dios envió entre ustedes al Profeta, como a Moisés,
según Deuteronomio 18:15 (aunque muy por encima de Moisés). Al oírlo,
Él los sacó de Egipto, y con la vara de Su poder hizo señales,
maravillas y hechos invencibles para romper ese poder que los mantenía cautivos y oprimidos.
Ustedes han experimentado el viaje, las pruebas y tentaciones en el desierto espiritual,
la caída de los cadáveres que debían caer ahí,
y la guía santa de la columna de nube y fuego a través de todas las marañas y peligros.
Ciertamente, los fieles entre ustedes, los probados y preparados entre ustedes,
han pasado el Jordán, el río de juicio puro, hacia la buena tierra.

Ustedes han llegado a experimentar a David y a Salomón
(que son uno en Espíritu) como su Rey,
quien gobierna en justicia y les ministra eterna paz.
Tienen al Sumo Sacerdote ahí, no según el orden de Aarón,
sino según el orden de Melquisedec; quien es el eterno Sumo Sacerdote de Dios,
no según la ley de un mandamiento carnal, sino según el poder de una vida indestructible.
Y ahora Sus labios preservan el conocimiento de la
ley para ustedes en el poder de esa vida indestructible.
Él ministra para ustedes y en ustedes en ese poder indestructible,
intercede con poder y eficacia,
y rocía sobre ustedes la sangre del pacto que quita el pecado de sus corazones y consciencias.
Así que ustedes conocen el estado del judío interno,
la tierra y el reino internos y santos,
y la circuncisión interna que es necesaria antes de entrar en esa tierra.
Ustedes conocen al Cordero interno, la Pascua interna,
el monte Sión y la Jerusalén internos, el incienso y los sacrificios internos,
el tabernáculo, el templo y el arca del pacto internos, el pan de la proposición interno,
el maná interno, la vara que reverdeció interna,
el candelero y las lámparas internas que nunca se apagan en el templo de Dios.
¿Qué más debería decir?
Todo lo que aquel pueblo debía ser externamente, en una forma y estado externo,
Dios los ha hecho a ustedes en la sustancia.
Lo que Dios habría sido externamente para ellos (si sólo
hubieran obedecido Su voz y guardado Sus estatutos y juicios),
es lo que Él es internamente para ustedes, los llamados,
escogidos y fieles seguidores del Cordero.
¡Ustedes son los que internamente disfrutan las bendiciones y promesas de ellos! ¡Oh,
la gloria del estado de ustedes ante el ojo que está abierto para verlo!

Ahora bien, algo permanece en mi corazón para ustedes.
¡Recuerden cuán grande pacto ha preparado Dios para hacer con ustedes,
cuando inclinen sus oídos a Él y sean guiados por Él en este santo acuerdo!
Pues no es un pacto débil, como era el antiguo, sino un pacto lleno de virtud y poder,
que los capacita para hacer lo que Dios requiera de ustedes.
Noten lo que tiene: Pone el temor de Dios en ustedes;
no el temor que es enseñado por los preceptos del hombre,
el que el hombre puede dejar entrar en su mente carnal,
sino el que Dios coloca como el tesoro de vida en el corazón. Como está escrito:
"`el temor de Jehová será su tesoro`" (Isaías 33:6). ¡Ojalá conocieran el valor
inapreciable de Su tesoro! ¡Cómo limpia el corazón y lo mantiene limpio,
y no permitirá que la mente que es sazonada con él y guardada por él,
se aparte del Dios vivo! ¡Este temor protege de la incredulidad, de la desobediencia,
y no permitirá que el alma se entrometa en ninguna aparición del mal! ¡Oh, precioso,
glorioso, bendito tesoro! ¡Feliz el hombre que siempre teme con este temor!

Otra cosa preciosa que tiene este pacto,
es la ley escrita en el corazón. Porque esta ley estará tan cerca, sí,
incluso más cerca que el pecado,
en el corazón que es tierno y que tiene la ley del Espíritu de
vida escrita en él. ¿Quién sabe lo que es tener la ley de amor,
la ley de vida, la ley del Espíritu, la ley de fe, la ley de una nueva obediencia,
vívidamente escrita por Dios en el corazón? ¡En realidad nadie lo sabe,
sino aquellos en quienes Dios la escribe!
Y estos no pueden evitar el deseo de tenerla cada
día y más abundantemente escrita en sus corazones,
por el dedo bendito de Dios.
Pero este pacto aún tiene más:
La colocación de Su propio Espíritu en el interior de ellos,
para que sea una fuente de vida ahí, una fuente de fuerza y sabiduría,
a fin de que estén cada vez más dispuestos en el día de Su poder.
Este Espíritu hará que caminen en Sus caminos, guarden Sus estatutos y juicios,
y los cumplan, para que así el Señor su Dios los bendiga y se deleite en ellos.

Oh, ¿quién no anhelaría,
y quien no tomaría la cruz y la vergüenza para disfrutar la gloria de este estado?
¡Oh,
lo que Dios ha hecho por un pobre y despreciado remanente entre los gentiles!
¡Quién no desearía guardar este bendito pacto con el Señor,
para disfrutar plenamente al Señor,
para experimentar en Su amorosa bondad y eterna justicia el matrimonio con el Hacedor,
y para que toda injusticia e inmundicia sean quitadas,
eliminadas y separadas del corazón para siempre! ¡Ah,
el espíritu virgen que el Cordero ama y se deleita en casarse!
"`El que se une al Señor un Espíritu es.`"
El que se une al Señor y es un Espíritu con Él, debe deshacerse de todo lo que es viejo,
malo, inmundo y corrupto en él.

¡Oh, quién estaría dispuesto a perder el precioso temor del pacto,
el cual es limpio y dura para siempre,
y mantiene limpio y casto para el Señor para siempre! ¡Quién estaría dispuesto
a perder una sola ley que Dios desea escribir en los corazones de Sus hijos,
sabiendo que cada ley es una ley de vida y que transforma la mente en la naturaleza
del Legislador! ¡Quién querría afligir al Espíritu de Dios que es nuestro Consolador,
o apagar lo que enciende la llama pura de amor y vida en nuestros corazones!
¡Cómo podría uno de Sus queridos y tiernos hijos estar dispuesto a afligirlo,
manifestando descuido y desobediencia hacia El que nos da a beber del río de Su placer!

=== Unas Palabras para Inglaterra, Mi País de Origen

¡Oh, tierra de mi nacimiento! ¡Oh, mis queridos compatriotas!
El poder puro del Señor está sobre mí y los manantiales de vida están abiertos en mí,
y entre muchas otras cosas, me derrito en amor y deseos por el bienestar de ustedes.
Está en mi corazón decirles esto: Si yo ahora les testificara de la verdad de una perla,
una perla celestial, una perla eterna, ¿no estarían dispuesto a oírme?
Si les dijera que sus corazones son el campo, o la tierra, donde está escondida,
¿no estarían dispuestos a considerarla?
Si se les predicara el evangelio eterno de nuevo,
el que tiene verdaderas nuevas de redención del pecado,
¿no estarían dispuestos a escucharlo?
Si el reino de Dios y la justicia de Cristo han de ser revelados en el interior,
¿no estarían dispuestos a aprender a esperar ahí, y a rogarle a Dios que les abra el ojo,
el único que puede ver cuando aparezcan?

Ciertamente, la visitación de Dios está sobre esta nación de manera especial;
Su luz y poder están irrumpiendo en ella contra la
oscuridad y poder del espíritu de Satanás,
el que ha cautivado y aún cautiva a muchos.
Ustedes desean libertad externa y el disfrute de sus derechos externos,
pero ¿no quieren ser libres internamente?
¿No desean ser libres de la naturaleza y espíritu vulgares,
terrenales y egoístas en los que el hombre (habiendo
caído de Dios y de Su gloria) se ha degenerado?
¿Acaso no son el poder de Dios y la vida de Cristo capaces de restaurar al hombre?
El que creó al hombre al principio, tan glorioso y a Su propia imagen,
¿no puede crearlo de nuevo?
¡Escuchen, mis queridos compatriotas!
El poder que crea de nuevo está siendo revelado,
y los que lo reciben (y son como barro en las manos del gran Alfarero,
rindiéndose para ser formados por Él) son diariamente
creados de nuevo en un carácter santo,
celestial, inocente, vivo, tierno y justo.
Son inclinados cada día más y más a ser del Señor en este día de Su poder,
y a recibir la potestad de ser hechos hijos,
y la fuerza contra los enemigos de sus almas.
Porque la gloriosa obra de redención que Dios ha comenzado en ellos,
es llevada a cabo por el brazo de Su fuerza,
para el consuelo de ellos y para alabanza eterna de Él.

Hay un Egipto espiritual y una Sodoma espiritual, tal como los hubo externamente.
También hay un desierto espiritual y un Canaán espiritual,
y el brazo del poder de Dios ha sido revelado interna y espiritualmente en ese Egipto,
desierto y Canaán espirituales, tan ciertamente como fue revelado en lo externo.
¿No han leído de un judío interno, de una circuncisión interna, de una levadura interna,
y de guardar la fiesta de los panes sin levadura, es decir,
del pan que no está leudado con pecado?
El que come del pan sin levadura,
este lo limpia de la levadura del pecado y lo leuda con vida y santidad;
pues es pan santo y vivo.
Este es el pan que descendió del cielo, del que los que se alimentan de él viven,
y los que viven se alimentan de él. Y aunque son muchos,
al alimentarse de este pan llegan a ser un solo pan, un cuerpo vivo,
que consiste en una Cabeza viva y en miembros vivos.
Pues la misma vida y naturaleza pura y celestial que están en la Cabeza,
son comunicadas por Él a los miembros.

Pero cómo encontraremos eso, puede que pregunten algunos.
Les diré cómo lo encontramos nosotros y cómo nadie que barra
la casa y haga una búsqueda diligente y fiel puede perderlo.
Eso que está en el corazón del hombre, que vuelve contra el pecado, descubre el pecado,
aleja del pecado; Eso donde Dios ministra ayuda contra el pecado;
Eso es la perla escondida, Eso es el reino escondido,
en Eso la justicia de Dios es revelada de fe a fe en todos
los que reciben y se rinden a esta santa levadura.
Esta Semilla es de la naturaleza de Dios y Cristo.
Esta es una medida de Su luz, de Su vida pura.
Esta es la ley y el mandamiento eterno que Dios escribe
en los corazones de Su Israel espiritual.
Porque el judío interno tiene tablas internas donde es escrita la ley interna,
para que la lea el ojo interno.

¡Oh, cuán cerca está Dios internamente del pueblo interno en este nuestro día! ¡Oh,
la gloria pura ha irrumpido! ¡Pero, ay,
los hombres están en sus varios tipos de sueños y no prestan atención de esta!
¿Qué hará el Señor para despertar esta nación? ¿De qué manera aparecerá Su poder
para derribar la injusticia y levantar la justicia en los espíritus de la gente?
¿No creen que el Señor haya estado trabajando?
¡Oh, presten atención de la obra del Señor, ustedes hijos de los hombres,
y esperen sentir la verdad cerca! ¡Participen de la virtud y del poder vivos de esta,
para que puedan sentir sus corazones creados de nuevo,
que los cielos viejos y la tierra vieja en el interior, donde habita la injusticia,
pasen, y experimenten los nuevos cielos y la nueva tierra internos,
donde habita la justicia! ¡Oh,
que todos sean conscientes internamente en el corazón de Su presencia, poder,
reino y gobierno justo,
desde el rey que se sienta en el trono hasta el mendigo que se sienta en el muladar!

¡Ciertamente, el hombre no fue hecho para sí mismo! ¡Ciertamente,
no fue hecho como la criatura que es ahora, sino a la imagen santa de Dios,
con amor en su corazón hacia Dios sobre todo, y con amor hacia su prójimo,
como se ama a sí mismo!
Oh, ¿de qué sirven las religiones y profesiones de aquellos en donde este amor no es hallado?
El Señor está restaurando Su imagen y sacando a la luz otra vez,
la religión verdadera y pura; la perla, la verdad, la contienen y la abarcan.
¡Oh,
compren la perla! ¡Compren la preciosa verdad! ¡Vendan todo lo que es contrario a ella,
por ella! ¡Tomen la cruz contra todo lo que es contrario en ustedes,
conforme la luz lo manifieste en ustedes!
Entonces tendrán la gratuita posesión de esta en sus corazones,
y la sentirán ser una raíz de vida, un tesoro de vida, un pozo de vida,
del que el agua viva brotará para vida eterna en ustedes diariamente.
Amén.

=== La Verdadera Iglesia y Ministerio Bajo el Evangelio

[.discourse-part]
Pregunta: ¿Cuál es la verdadera iglesia, o la iglesia del evangelio,
o la iglesia de acuerdo al nuevo pacto?
(Porque había un antiguo pacto y una iglesia de acuerdo a este, bajo la ley;
y hay un nuevo pacto y una iglesia de acuerdo a este, bajo el evangelio).

[.discourse-part]
Respuesta: Para responder esto, vamos a indagar y a considerar qué es el nuevo pacto,
y luego aflorará más fácilmente, qué es la iglesia de acuerdo al nuevo pacto.

El nuevo pacto, según escrituras claras,
y según la experiencia manifiesta en este bendito día del resplandor
de la luz del evangelio en los corazones de los hombres,
es lo siguiente: Que Dios coloca Su ley en el interior de Su pueblo,
la escribe en sus corazones, se convierte en su Dios y hace de ellos Su pueblo,
les enseña a todos a conocerlo (internamente y por experiencia),
desde el menor hasta el mayor,
es propicio a sus injusticias y no recuerda más sus pecados e iniquidades.
(Jeremías 31:33-34; Hebreos 8:10-12)

Ahora bien, si este es el nuevo pacto (el pacto de la iglesia del evangelio),
entonces los que caminan en este pacto como pueblo de Dios, son la iglesia.
Estos tienen la ley puesta por Dios en su interior, escrita en sus corazones,
y según esta ley y este pacto, tienen a Dios como su Dios,
ellos son Su pueblo y son enseñados por Él a conocerlo (como está escrito:
"`Y todos tus hijos serán enseñados por Jehová,`" Isaías 54:13;
Juan 6:45). Dios ha sido propicio con ellos y no recuerda más sus pecados e iniquidades,
habiendo sido limpiados de sus consciencias por medio de la sangre del pacto
eterno (lo que la sangre de los toros y machos cabríos nunca pudo hacer).

De modo que,
la iglesia del Nuevo Testamento (o iglesia del evangelio) es la iglesia del judío interno,
tal como la iglesia de la ley era la iglesia del judío externo.
Esta es la iglesia de los adoradores internos,
de los adoradores en Espíritu y en verdad (Juan 4:23),
tal como la iglesia de la ley era la iglesia de los adoradores externos.
Esta es la iglesia de los internamente circuncidados,
tal como la iglesia de la ley era la iglesia de los externamente circuncidados.
(Romanos 2:29) Es la iglesia de los que son internamente santos,
tal como la iglesia de la ley era la iglesia de los externamente santos.
Es la iglesia de los que ofrecen incienso y sacrificios internos,
tal como la iglesia de la ley era la iglesia de los
que ofrecían incienso y sacrificios externos.
Es la iglesia de los internamente redimidos del Egipto interno,
de las tinieblas y poder de Satanás internos,
tal como la iglesia de la ley era la iglesia de los que fueron
redimidos del Egipto externo y del poder del faraón externo.
Es la iglesia que tiene el arca interna (Apocalipsis 11:19), la presencia interna,
el maná interno, etc.,
tal como la iglesia externa de los judíos tenía estas cosas externamente.

[.discourse-part]
Pregunta:
¿Cuál es el verdadero ministerio del evangelio y
quiénes son los verdaderos ministros del evangelio?

[.discourse-part]
Respuesta: Son aquellos a quienes Cristo envía en el Espíritu y poder de Su Padre,
a reunir y a edificar esta iglesia del nuevo pacto.
A Cristo se le había entregado todo el poder en el
cielo y en la tierra para este mismo fin:
Reunir, defender y edificar Su iglesia.
Él mandó que Sus apóstoles esperaran el mismo poder,
y aún envía a Sus ministros en el mismo poder,
para que sean ministros competentes del evangelio,
el cual no consiste en palabras sino en poder, es decir,
en poder de Dios para salvación. (Romanos 1:16) El nuevo pacto no descansa en la letra,
sino en el Espíritu y en el poder.
Aquellos que son ministros de dicho pacto, deben recibir la vida,
el Espíritu y el poder de Cristo, de lo contrario,
no pueden nutrir ni edificar a Sus miembros.
Deben predicar y ministrar la palabra en este poder, Espíritu y vida, de lo contrario,
no son capaces de sacar a otros del mundo para reunirlos en el nuevo pacto.

Cristo, el Señor de Su iglesia, el fundamento de vida en Su iglesia, la roca eterna,
es una piedra viva y Su iglesia está construida de piedras vivas.
¿Puede alguien ministrarles vida o edificarlas en la vida, el Espíritu y el poder,
además de aquellos que están en la vida,
Espíritu y poder que reciben de la Cabeza para vivificar
y edificar aun más a los miembros vivos?
La leche que nutre al bebé vivo es viva, y debe venir pura del pecho de vida,
y no estar adulterada con la sabiduría del hombre o las invenciones del cerebro.
¿Qué deben ser entonces el pan, el vino y el agua del reino,
de lo que los hijos y herederos del reino deben alimentarse y estar satisfechos?
Los ministros del evangelio son administradores de esta vida celestial,
de este Espíritu celestial, de este poder celestial,
de este tesoro celestial que tienen en vasos de barro,
y que Dios les permite presentar para alimentar a Sus corderos y ovejas.
Cristo le dijo a Pedro: "`¿Me amas más que estos?`"
Pedro le respondió: "`Sí, Señor, tú sabes que te amo.`"
Si es así: "`Apacienta mis corderos, apacienta mis ovejas,`" le dijo Cristo.
Pero, ¿cómo los apacentaría? ¿Con qué debía alimentarlos?
Cristo dijo: "`Todo poder me es dado en el cielo y en la tierra,
y estoy por ascender al Padre para recibir la plenitud de Su Espíritu.
Si esperan, ustedes recibirán abundantemente del mismo Espíritu y poder, y entonces,
en ese Espíritu y poder,
podrán apacentar mis corderos y mis ovejas que son engendrados
y reunidos a Mí. Pero aparte de este Espíritu y poder,
nadie puede alimentarlos o edificarlos,
porque esto es lo único con lo que deben ser alimentados y sobre lo que deben ser edificados.`"

De hecho, un hombre puede ser ministro de la letra, ministro de la ley,
sin el Espíritu y sin poder.
Pero tal hombre no puede ministrar el evangelio, porque este no consiste en letra,
sino en Espíritu.
(2 Corintios 3) Y la fe que se engendra en el evangelio,
no está fundada en la sabiduría del hombre, sino en el poder de Dios.
El estado del evangelio, la iglesia del evangelio, el edificio del evangelio,
comienza en el poder, continúa en el poder y termina o se perfecciona en el poder.
Todo el ministerio del evangelio es participar de este poder y ministrar en él,
de lo contrario, no se puede hacer nada en esta obra.
Jesucristo nuestro Señor comenzó la obra en este poder,
y nadie puede llevarla adelante sin dicho poder.
El Señor Dios de gloria puso el fundamento:
"`He aquí que Yo he puesto en Sion por fundamento...`" (Isaías 28:16;
1 Pedro 2:4-6) Sólo el Espíritu vivificante puede hacer piedras vivas y espirituales.
Sólo el Señor puede edificarlas por medio de la operación de este Espíritu y poder.
Y los que son verdaderos ministros del evangelio,
deben esperar diariamente que este poder venga de Dios, para poder ministrar en él.

[.discourse-part]
Pregunta: ¿Cuál es la manutención de los ministros de Cristo,
o cuál debe ser la manutención de los verdaderos ministros bajo el evangelio?

[.discourse-part]
Respuesta: Cristo, quien los ha enviado a ministrar en Su nombre, ha provisto para ellos;
y los que son Sus verdaderos ministros están satisfechos con lo que Él les ha provisto.
(Mateo 10:10) Estos son cuidadosos de no hacer que el evangelio,
que debe ser una bendición interna, sea gravoso externamente para nadie.
La mente del verdadero ministro está al servicio de Cristo: Cómo serle fiel a Él,
reunir almas para Él,
alimentar a otros con el pan de vida de Él. No está interesado
en lo que obtendrá de los hombres por hacerlo,
porque dichos ministros no codician el oro, la plata, etc., del hombre.

=== El Evangelio Eterno

El bendito mensaje que los apóstoles (enviados por Cristo a predicar
el evangelio) oyeron de Cristo y debían declarar a otros era:
"`Dios es luz,
y no hay ningunas tinieblas en él`" (1 Juan 1:5). El propósito de Cristo al enviarlos
con este mensaje era (al predicarlo en la evidencia y demostración del Espíritu de Dios),
que abrieran los ojos de los hombres,
los volvieran de las tinieblas a la luz y del poder de Satanás a Dios,
para que pudieran recibir perdón de pecados y una herencia entre los que
están siendo santificados por la fe que es en Él. (Hechos 26:18)

Ahora bien,
cuando el ojo de la mente es abierto y la mente es
vuelta de las tinieblas internas a la luz interna,
y del poder de Satanás al poder de Dios (el cual es revelado en la luz),
el alma llega a ver en la luz (sobre las tinieblas y sobre
Satanás que la oscureció) las cosas de Dios y de Su reino.

En primer lugar, el alma ve Al que es la roca, el fundamento santo de Dios,
el fundamento santo de vida en el alma, la piedra viva,
por la que todas las otras piedras reciben vida.
Estas son enseñadas por Dios a ir a Él, la piedra viva, a ser edificadas sobre Él,
a llegar a ser casa de Dios y una nueva creación en Él. (1 Pedro 2:5;
2 Corintios 5:17) Aquí, en esta luz, nadie se pierde la verdadera venida,
ni deja de oír la voz del Padre,
ni deja de ser atraído y enseñado por Él a venir al Hijo.
(Juan 6:44-45)

En segundo lugar, aquí es experimentado el verdadero estado judío,
el estado del judío interno, la circuncisión interna y la verdadera adoración (es decir,
la adoración al Padre en Espíritu y verdad).
Porque el judío interno es hijo de la luz, engendrado en la luz,
redimido de las tinieblas, quien habita y camina en la luz como Dios está en la luz.
(1 Juan 1:7) La circuncisión no es un acto carnal,
sino la eliminación de lo que es carnal en la mente,
por medio del Espíritu y poder de Cristo.
La adoración del evangelio o la adoración del judío interno,
es la adoración a Dios en la novedad de la vida de Su Hijo.

En tercer lugar,
aquí se halla el verdadero arrepentimiento de la naturaleza muerta y de las obras muertas,
el cual ningún hombre puede alcanzar por sí mismo,
pues es dado por Dios a través de Su Hijo.
Porque Dios ha designado que Cristo sea Príncipe y Salvador,
para dar arrepentimiento y perdón de pecados.
(Hechos 5:31) Aquí el arrepentimiento es esperado, recibido y conocido.
Porque el verdadero arrepentimiento no es dado a los hombres
que están en las tinieblas y aman las tinieblas,
sino a los que se vuelven a la luz; a ellos es dado arrepentimiento para vida.
(Hechos 11:18; comparado con el capítulo 26: 17-18)

En cuarto lugar, aquí la verdadera fe, el precioso don de fe es recibido,
por medio de la cual los hombres creen en Aquel que da vida
y reciben vida de Él. Esta es la fe que da entrada a Dios,
da victoria sobre el mundo y sobre todo lo que es contrario a Dios.
En efecto, la fe que es dada en la luz hace esto,
pero la fe que el hombre tiene en las tinieblas no lo hace.

En quinto lugar, aquí es experimentada la cruz de Cristo; ella es algo interno,
vivo y espiritual,
que crucifica eficazmente al hombre que la toma y la lleva
cada día contra todo lo que es terrenal y pecaminoso.
Entonces la Semilla pura y la vida de Cristo brotan en Su tierra,
y se levantan sobre el mundo y todo lo mundano.
(Gálatas 6:14)

En sexto lugar, aquí el amor puro brota en el corazón,
tanto en El que engendra como en el que es engendrado.
En la luz no hay sino amor, pero en las tinieblas no se puede encontrar verdadero amor;
y el amor que se puede encontrar ahí es de la naturaleza de enemistad.
Es la luz de la verdad la que purifica el corazón del amor fingido.
(1 Pedro 1:22; Deuteronomio 30:6)

En séptimo lugar, aquí son experimentadas la paciencia y la mansedumbre del Cordero,
y el alma es adornada con ellas.
El Cordero es la luz del mundo y aquellos que son hechos corderos por Él,
participan de Su naturaleza dulce y mansa al aprender de Él a ser mansos y humildes
de corazón. Así tienen esa paciencia y mansedumbre de Él que ningún otro puede alcanzar.
(Mateo 11:29)

En octavo lugar, en la luz son cumplidas y experimentadas las preciosas promesas,
que hacen de aquellos que participan de ellas (en los que
son cumplidas) partícipes de la naturaleza divina.
Porque la naturaleza divina no es experimentada en las tinieblas,
sino en Aquel que es luz.
El hombre (que es tinieblas) no puede participar de las
promesas que pertenecen a los hijos de la luz.
Pero cuando por la operación del poder de Dios su estado y su naturaleza cambian,
y ya no es más tinieblas, sino luz en el Señor,
entonces tiene participación en las promesas que son hechas a los hijos de luz.
(Efesios 5:8; 2 Pedro 1:4)

En noveno lugar, en la luz se recibe la santa unción,
se oye la voz de Cristo y es hecho el nuevo pacto eterno con el alma (Isaías 55:3),
es decir, las misericordias firmes de David.
Es escrita en la mente la ley del nuevo pacto (la
ley del Espíritu de vida en Cristo Jesús),
y es puesto en el corazón el temor santo del nuevo pacto, que limpia y mantiene limpio.
El bendito Espíritu del Padre es dado y recibido,
el cual da el poder de llegar a ser hechos hijos
de Dios al hacerlos caminar en Sus caminos,
guardar Sus estatutos y juicios, y hacerlos.
¡Ojalá los hijos de los hombres oyeran y entendieran
esta preciosa y amorosa bondad del Señor,
y pusieran su confianza bajo la sombra de Sus alas,
y experimentaran lo que es estar satisfechos con
la grosura de la casa espiritual de Su evangelio,
y tomaran del río de Sus placeres y en Su luz vieran la luz! (Salmo 36:7-9)

En décimo lugar, en esta luz son experimentados la verdadera iglesia,
el verdadero evangelio, la iglesia del Nuevo Testamento.
Esta es la iglesia de los hijos de luz, el edificio construido en la luz;
dicha iglesia está en Dios el Padre y en el Señor Jesucristo (2 Tesalonicenses 1:1),
en Quienes dichos hijos son juntamente edificados para morada de Dios a través del Espíritu.
(Efesios 2:22) Sí, en Él todo el edificio, bien coordinado,
crece para ser un templo santo en el Señor. (Efesios 2:21) Y todo
el que ha sido reunido fuera de las tinieblas y llevado a la luz,
el que camina en la luz y permanece en la luz,
es edificado sobre el fundamento de los apóstoles y profetas,
siendo la principal piedra del ángulo Jesucristo mismo.
(Efesios 2:20) De manera que, ya no son extranjeros ni advenedizos,
sino conciudadanos con los santos y miembros de la casa de Dios.
(Efesios 2:19)

La iglesia del evangelio es la casa espiritual de Jacob,
la cual camina en la luz del Señor. (Isaías 2:5) Estos suben a la montaña del Señor
(a esa que es revelada en lo postrero de los tiempos como la montaña de Dios,
es decir, el monte Sión espiritual, Hebreos 12:22), a la casa del Dios de Jacob,
donde Él enseña Sus caminos a Su pueblo espiritual, los judíos internos,
y ellos aprenden a caminar en Sus sendas.
Porque de esta Sión saldrá la ley del Espíritu de vida en Cristo Jesús (en los
días del evangelio) y la Palabra del Señor provendrá de esta Jerusalén. (Isaías
2:3) Porque la Jerusalén que es de arriba es libre,
la cual es madre de todos los hijos nacidos del Espíritu de Dios.
(Gálatas 4:26; Juan 3:6) Al ser ella la madre de todos ellos,
los nutre con la Palabra de vida que sale de ella y sus hijos la conocen.
(Mateo 11:19) ¡Ojalá todos, tanto católicos como protestantes,
conocieran esta verdadera madre iglesia, la madre de todos los vivos,
la que nutre con la ley viva y Palabra de vida eterna!
