== Capítulo 8. El Testimonio de la Verdad

=== Con Respecto a la Verdadera Iglesia y Ministerio

Hay un gran ruido en el mundo acerca de la iglesia y el ministerio.
Muchos afirman qué es, muchos dudan y preguntan sobre eso,
y algunos están verdadera y correctamente satisfechos,
al haber recibido el conocimiento de esto de parte de Dios,
quien no es engañado al respecto, ni engaña a nadie,
sino que da el verdadero entendimiento de estas y otras
cosas a los que esperan en Él correctamente (es decir,
en Su temor y en el silencio de la parte sabia carnal).
Ahora bien, tengo un testimonio que dar con respecto a estas cosas,
el cual ese oído que es de Dios puede oír, y a ese oído deseo hablarle.

La verdadera iglesia es el cuerpo espiritual de Cristo.
La iglesia es la esposa de Cristo y Él es el esposo.
La cabeza está viva y también lo están los miembros del cuerpo.
La cabeza está ungida,
y el aceite con el que la cabeza está ungida desciende sobre todo el cuerpo,
y aquel sobre el que dicho aceite no desciende, no es parte del cuerpo.
Ahora, ninguna cosa externa puede hacer que uno sea miembro de dicho cuerpo, y menos aún,
ninguna cosa, forma, profesión o práctica externa puede forjar la iglesia.
La iglesia bajo la ley estaba compuesta de cosas externas, de una reunión externa,
de la circuncisión externa, de la ley externa, adoración externa, etc.
Pero el evangelio es el estado de la sustancia, el estado de las cosas invisibles,
de personas invisiblemente reunidas por el Espíritu en la vida y poder de Dios,
internamente circuncidadas, internamente bautizadas con el Espíritu Santo y fuego,
que adoran internamente en Espíritu y verdad,
y se inclinan ante el sonido y nombre del Señor Jesús. Y
todo lo que es de la naturaleza externa bajo el evangelio,
es producido y preservado por el poder de la aparición interna, y al morar en este.
Por tanto, la iglesia ahora es:
El pueblo reunido por la vida y Espíritu del Señor.
El pueblo reunido por el poder de lo alto,
que permanece en el poder, actúa en el poder,
adora en el poder y se mantiene en el orden santo y gobierno de
vida mediante el poder (tanto internamente en sus propios corazones,
como externamente en sus asambleas y vidas).

Cristo fue hecho rey, sacerdote y profeta, no según la ley de un mandamiento carnal,
sino según el poder de una vida indestructible.
Es en este poder que Él reúne, gobierna y preserva Su iglesia,
y ministra en ella desde y por medio de Su Espíritu y poder.
Ahora, si encuentran este poder de la vida indestructible,
si encuentran al pueblo que se reúne por este poder y en este poder en cualquier lugar,
ahí habrán encontrado la iglesia, ahí habrán encontrado el cuerpo vivo,
ahí habrán encontrado a Cristo la cabeza, cuyo dominio y fuerza están sobretodo,
y contra quien las puertas del hades no pueden prevalecer.

Es lo mismo para los ministros de esta iglesia.
Quiero decir,
lo que manifiesta la iglesia es lo mismo que manifiesta a los ministros de esta.
Porque estos también son de Dios, son llamados por Él,
reciben poder de Él y permanecen y ministran en dicho poder.
Por tanto, tres cosas se requieren de un verdadero ministro,
sin las cuales no puede ser recto o ejecutar su oficio correctamente:

[.numbered-group]
====

[.numbered]
1+++.+++ Deben ser llamados por Dios.
El ministro bajo la ley estaba autorizado por su llamado y nombramiento de Dios.
Cristo mismo no tomó el honor por Sí mismo,
sino que fue llamado por Dios para este sacerdocio, tal como Aarón lo fue para el suyo.
Así también los apóstoles y ministros, en su declaración del evangelio,
fueron llamados y nombrados por Cristo.

[.numbered]
2+++.+++ Deben recibir capacidad y poder de Dios.
Los ancianos que debían ayudar a Moisés tenían que recibir de su Espíritu.
Bajo la ley, los sacerdotes debían ser ungidos con aceite literal externo,
y los ministros del evangelio deben ser ungidos con aceite espiritual interno.
La obra de ellos es espiritual, ¿cómo pueden llevarla a cabo sino por la unción,
mediante esa presencia, guía, vida, virtud y poder del Espíritu que se muestra en ellos?
Los apóstoles mismos, aquellos que habían sido enseñados por Cristo,
que conocían Su manera de vivir y Su doctrina,
que fueron testigos oculares de lo que debían declarar,
y que habían recibido autoridad y comisión de parte de Él, con todo,
no debían salir con solo el llamado y la comisión recibidos,
sino que tenían que esperar el poder de lo alto.
Sólo hasta que recibieron el Espíritu y poder,
fueron hechos ministros competentes del nuevo pacto, no de la letra,
sino del Espíritu y poder.

[.numbered]
3+++.+++ Deben permanecer en el poder, mantenerse en el poder, sentir el movimiento,
virtud y asistencia del poder en toda su obra y servicio.
No deben derribar, ni edificar,
ni velar o vigilar sobre el rebaño en su propia sabiduría, en su propio espíritu,
en su propia voluntad, sino sólo en la unción, en la luz y guía del Señor. Esta reunión,
este edificio, esta obra del Señor comienza sin carne, separada del hombre,
y la carne debe mantenerse fuera de todo lo que se lleva a cabo.

====

En efecto, si los ministros del evangelio no están en el Espíritu, ni en la vida,
ni en el poder, ¿cómo pueden ministrar a la naturaleza,
al espíritu y a la vida en el cuerpo (incluso a los más pequeños de los miembros)?
Ellos pueden ministrar conocimiento externo a la sabiduría y entendimiento del hombre,
pero esa no es la comida que se le debe ministrar a la iglesia,
ni es la parte en el hombre que debe ser alimentada por el verdadero ministro.
Por el contrario,
los ministros del evangelio deben ministrarles la
vida (comida viva) que proviene de la fuente viva,
de la cabeza, del Espíritu de Cristo en ellos, a los miembros particulares bajo su cargo.
Así que deben ser buenos administradores y pastores del rebaño,
dándole a cada uno su porción apropiada a su debido tiempo.

Consideremos ahora: No era poca cosa ser ministro bajo la ley.
Era fácil equivocarse y ministrar de forma inapropiada.
Era fácil equivocarse en la letra si no se tenía gran cuidado
y prudencia para mantenerse estrictamente en ella.
Pero es algo mucho más difícil ministrar bajo el evangelio,
recibir el poder para ministrar en el poder a lo que es engendrado y nacido del poder.

Este ministerio es precioso y es de Dios dondequiera que se encuentre,
pero sólo aquellos que son de Dios pueden oír y recibir este ministerio.
(1 Juan 4:6) El oído incircunciso no puede oír,
ni tampoco el sabio y entendido según la carne,
porque la sabiduría de Dios es necedad para el hombre,
y los misterios del reino (el misterio de Su vida y de la verdadera piedad)
son acertijos y locura para el ojo de su sabiduría. En efecto,
el hombre está apartado de Dios y está retenido con cadenas de oscuridad
y corrupción. El que quiera conocer la verdadera iglesia o ser de ella,
y oír la voz de Dios en Su verdadero ministerio,
primero debe tomar la cruz contra esa parte en él que no es de Dios,
y recibir de Dios el ojo que ve y el oído que oye.

[.discourse-part]
Objeción: Se objeta contra nosotros, que esto que testificamos,
expresamos y practicamos es un nuevo camino surgido últimamente,
que no se había conocido,
ni del que se había escuchado en el mundo hasta hace algunos años.

[.discourse-part]
Respuesta: Cuando la luz eterna resplandece de las tinieblas es, en efecto,
nueva para los que estaban agobiados y sepultados en las tinieblas de la noche,
y por tanto, nunca la habían visto, ni habían oído de ella antes.
Sin embargo, no es nueva en sí misma, sino la misma que era desde el principio.

Esta Semilla de vida, esta Simiente de bendición,
es la misma que se prometió al principio, la que heriría la cabeza de la serpiente.
Es la misma que se le prometió a Abraham, cuando se le predicó el evangelio.
Es la misma que salvó a todos (los que creyeron en ella) bajo la ley;
porque no eran los tipos, ni las sombras,
ni las ordenanzas externas las que salvaban el alma entonces, sino la Semilla,
quien era el Salvador desde el principio,
es el Salvador a lo largo del tiempo y lo será hasta el final.
Los apóstoles también predicaron la Semilla, la Palabra de fe, a Cristo el camino,
a Cristo el poder.
Sí, y durante todo el tiempo de la apostasía,
esta Semilla ha sido la que ha preservado a los testigos,
salvándolos de ser tragados por las tinieblas y manteniéndolos vivos en su testimonio.
De ninguna otra cosa predican hoy los que están en la verdad,
aquellos que son levantados por el poder de Dios en ella para dar testimonio de ella.
Esta es la Semilla de la que ha brotado la vida en cualquiera que ha sentido la vida,
en todas las edades y generaciones.
Esta es la raíz y renuevo de David, la estrella brillante de la mañana.
Esta es el deseo de todas las naciones (¡ojalá ellas conocieran su deseo!). Y si ustedes,
quien quiera que sean, han sentido algo de Dios en algún momento,
ya sea en la lectura de las Escrituras, al escuchar un ministro,
en las respiraciones privadas, etc., fue la Semilla la que les dio sentir en ese estado,
desear al Señor, volverse de la vanidad, anhelar la comunión con Él, etc.
¡Ojalá estuvieran ahí ahora, tal como estuvieron en el pasado!
Pues no hay otra cosa de la que les testifiquemos (o a la que deseemos atraerlos),
más que de eso que era la raíz y fuerza de sus vidas en aquellos días.

Por lo tanto, regresen a la vida; conozcan lo que anteriormente les dio vida.
¿Ha seguido adelante?
¡Entonces no se queden atrás, continúen! ¡Oh, conozcan al Cordero que es el líder!
Porque este es el gran deber de los deberes: Seguirlo dondequiera que vaya.
En Su tierna misericordia, Él puede visitarlos en Egipto, Sodoma, Babilonia,
pero estos lugares no son Su reposo,
ni deben ser considerados de esa manera sólo porque en una ocasión apareció, visitó,
tocó y refrescó el alma ahí. Su lugar de habitación es Sión,
Su ciudad santa es Jerusalén, donde los cristianos moraban con Él antes de la apostasía,
y donde los que son redimidos de la apostasía van a morar de nuevo.

Por lo tanto, no pierdan más tiempo en disputas, pensamientos, razonamientos,
ni consultas con la mente que nunca aconsejará al alma para bien.
Más bien,
esperen en el Señor para que puedan llegar (a través
de Su guía) al verdadero conocimiento de Su Semilla,
a sentir en el corazón la naturaleza de Su luz y vida eterna.
Esto le pondrá fin a las discusiones, sí;
dispersará la mente disputadora y resolverá poderosamente
la controversia en el sentido puro y demostración del Espíritu.
El que conoce algo de esto, permanezca ahí, espere ahí, viva ahí,
more ahí y respire al Padre ahí,
vigilando detenidamente eso que lo sacaría de ahí
y arrastraría la mente hacia otro camino,
sabiduría y espíritu.
¡Oh, pobre alma, si el Señor toca tu corazón y abre tu ojo, verás a tu Amado,
que es "`distinguido entre diez mil`" y que no hay nada como Él,
en excelencia de naturaleza!
En verdad, esto es sentido,
experimentado y testificado para ustedes en el amor y en la verdad.

No son las palabras de la letra, ni guardar todo lo que está en la letra, lo que da vida;
Su voz es la que da vida.
Las palabras que Él habla (en cualquier momento) son Espíritu y vida.
Por tanto, es de esto de lo que vivimos, no del pan que podamos hacer,
ni de las cosas que podamos reunir o comprender de la letra,
sino de las palabras que salen de la boca de Dios.
Ahora, esta Semilla es Su boca, en y a través de ella les habla a nuestras almas,
las que temen delante de Él y esperan en Él en Su propia ordenanza eterna y perpetua.
Aquí nos encontramos en la sustancia, en la vida, en la frescura,
en la pureza y en el poder.
Este testimonio les es dado en el amor de Dios, desde Su tierno corazón,
el cual conoce el presente estado de ustedes, sus necesidades, sus andanzas,
sus profundos prejuicios y dureza contra Su verdad.
Sin embargo,
Él recuerda los días de la juventud de ustedes y no puede dejar de buscarlos,
ni de llorar por ustedes.
Oh, ¿cuándo se van a volver?
¿Cuándo van a oír? ¿Cuándo van a esperar sentir la vida en el Espíritu?

=== Una Palabra de Advertencia

La siguiente es una advertencia para los que son
tocados por el poder de la Verdad en algún momento,
de cómo pueden escuchar y dejar entrar al enemigo después, y como resultado,
hacer que la buena Semilla sea robada,
el verdadero sentido perdido y la mente saturada de prejuicios y tropiezos.

Cuando la Verdad de Dios es recibida en el interior,
se descubre que es una naturaleza viva y poderosa que obra potentemente ahí para
la limpieza y redención del corazón. Esto es ciertamente experimentado;
es decir, así como la mente unida al engaño es contaminada,
la mente unida a la verdad de Dios es purificada por Su poder y virtud.
Ahora,
después de haber sentido esto y de haber sido llenados del
amor y buena voluntad de Dios hacia las almas de los demás,
¿qué podemos hacer sino testificarles a otros que necesitan
la verdad de Dios (y su propiedad y virtud purificadoras)?

Ahora bien, cuando el Señor toca Su trompeta con poder y vida,
muchas veces penetra profundamente a través del velo
terrenal y alcanza lo Suyo en el interior,
lo cual, al ser alcanzado, responde al testimonio diciendo: "`¡Es Verdad!`"
Aquí comienza la obra de Dios en el corazón, cuando el alma es tocada con Su verdad,
la siente internamente y cede en alguna medida ante la virtud y poder vencedores de ella.

Pero luego llega '`el sutil,`' cuyo plan y trabajo
es socavar y volcar la obra de Dios en el alma.
Él genera dudas, celos y cuestionamientos, tanto con respecto a nosotros,
como con respecto a la doctrina enseñada por nosotros,
al sugerir en la mente que esta no es de Dios.
De esta manera el enemigo lleva la disputa a otra parte
del hombre (además del lugar por el que la verdad entró),
y ahí fácilmente influencia la mente para que juzgue contra su anterior
sentimiento y se vuelva de la obra que fue comenzada por Dios.
De esta forma muchos pobres corazones son enredados y llevados de vuelta al cautiverio;
los corazones de aquellos que habían comenzado a sentir los movimientos
de la verdad ahí (en donde está el poder de redención),
y que los habría redimido así como a otros,
si la hubieran recibido en el amor de ella y se hubieran sometido a ella.

Es precioso recibir de Dios el espíritu de discernimiento,
el cual da la capacidad de diferenciar Su Espíritu del espíritu de engaño. Sí,
es imposible ser preservados en el Espíritu y camino correctos,
excepto en la medida en que Este es sentido.
Porque,
¿de qué otra manera puede ser recibido el Señor en
todos los movimientos y operaciones de Su Espíritu?
O, ¿de qué manera se puede apartar del espíritu contrario, con todos sus sutiles engaños,
tergiversaciones y razonamientos en la mente,
a menos que haya un discernimiento en la verdadera luz del Señor,
que me dé la capacidad de diferenciar qué es de uno y qué es del otro?

Y ustedes que no desean ser engañados, sumérjanse profundamente,
por debajo de los pensamientos, razonamientos y consultas de la mente terrenal,
para que puedan encontrar algo del reino y del poder (lo
cual lleva consigo su propia evidencia y demostración),
ser reunidos en ello y descubrir ahí un sentido,
conocimiento y juicio que no puede ser engañado, ni puede engañar. Pues la religión pura,
el conocimiento puro, el juicio correcto, la fe viva,
se originan en el poder y demostración del Espíritu
y deben permanecer dentro de estos límites.
Estas cosas están separadas de la carne, apartadas del hombre, fuera de su voluntad,
fuera de su sabiduría, fuera del alcance de la comprensión del hombre.
El que no abandona este ámbito, nunca se encuentra con la vida, poder,
ni virtud de la verdad.
Puede que encuentre un cuerpo de conceptos y conocimientos formados,
y hable del hombre caído y de la restauración por
medio de Cristo (incluso de manera muy exacta,
de acuerdo con una descripción literal), pero la vida,
el verdadero conocimiento y la poderosa virtud, son completamente otra cosa,
y se encuentran en otra tierra, adonde el hombre no puede viajar,
excepto en la medida que sea despojado de sí mismo, formado de nuevo,
hecho y engendrado en Otro.

Por lo tanto, ustedes que desean al Señor (que desean ser de Él,
sentir que Él es de ustedes y conocer Su verdad en la vida y poder de esta),
esperen la demostración de Su Espíritu.
Aprendan a distinguir internamente entre las enseñanzas de Su Espíritu
y las enseñanzas de otro espíritu a partir de la letra.

[.discourse-part]
Pregunta: Pero, ¿cómo puedo yo, que soy débil y estoy lleno de dudas y temores,
mantenerme en el sentido de la verdad y tener la certeza de que no soy engañado?

[.discourse-part]
Respuesta: Para ustedes,
que se hacen esta pregunta en la rectitud y sencillez de sus corazones,
tengo algo que decirles:

[.numbered-group]
====

[.numbered]
1+++.+++ Consideren cómo fueron tocados, cómo fueron alcanzados;
examinen cuál oído fue abierto en ustedes,
y respiren al Señor que mantenga ese oído abierto en ustedes y el otro cerrado.
Pues les puedo asegurar en la verdad de Dios,
que con el oído que el Señor abrió a la verdad (el que sintieron
que Su Espíritu abrió y dejó entrar la verdad),
digo, con ese oído nunca dejarán entrar algo que sea contrario a la verdad.
Pero si el enemigo abre el otro oído, el oído que quiere oír sus prejuicios, celos,
dudas, temores y tentaciones, y los dejan entrar,
expulsará lo que entró por el otro oído. Ahora, ¿no pueden distinguir, oh pobres almas,
entre lo que trajo algún sentido de la verdad en ustedes
y lo que se levanta en ustedes contra la verdad?
¡Teman delante del Señor! ¡Vigilen y oren, para que cuando el tentador venga,
no entren con él en la tentación y pierdan así su unión y crecimiento en lo que es invaluable!

[.numbered]
2+++.+++ Mantengan su ojo y corazón en el valor inapreciable de lo que sintieron.
¡Oh, recuerden cuán fresco, cuán cálido y cuán vivo era, cómo llegó, cómo venció,
cómo derritió! El recuerdo de esto (aferrado en la mente) será una fortaleza
contra las tentaciones y sutiles estratagemas del enemigo.

[.numbered]
3+++.+++ No se inmiscuyan en las cosas que el enemigo arroja en sus mentes.
No consideren si son ciertas o no.
El que considera una tentación (en muchos casos) la ha dejado entrar y ya está vencido.
Cuando Eva escuchó lo que dijo la serpiente,
¡cuán pronto se perdió y murió! El enemigo muchas
veces trae tentaciones más allá del estado,
capacidad y habilidad del alma para discernirlas.
En el momento, esas cosas son demasiado elevadas para ustedes.
Aún no han recibido una medida de vida de Dios por medio de la cual discernirlas,
y si corren más allá de su medida y buscan comprobar en
sus mentes las cosas que están más allá de su alcance,
con seguridad correrán hacia la trampa.

[.numbered]
4+++.+++ El discernimiento de estas cosas en el momento no sería de gran ventaja para ustedes,
como podrían estar creyendo.
¿Por qué? Porque el enemigo tiene muchas tentaciones
y artimañas del mismo tipo (como de otros tipos también),
las cuales traería una tras otra.
Cuando él trae una segunda, una tercera, etc.,
lo que los envolvió para que consideraran la primera,
los envolverá también a considerar el resto.
Por lo tanto, el camino correcto es mantenerse fuera de él,
en el sentido recto de lo que el Señor ha formado en ustedes.
Pues en esa medida el Señor está con ustedes,
y al permanecer ahí están fuera del alcance del enemigo.
Pero al ser atraídos por el enemigo a considerar las cosas que están fuera de su alcance,
se exponen a sus trampas.

[.numbered]
5+++.+++ Consideren lo que se les prohibió o lo que se les requirió,
en el tiempo cuando sentían la calidez de Dios.
Porque en la experiencia de la calidez de Dios,
hay una voz celestial y en el corazón una visión celestial,
aunque el enemigo intente volver la mente, tanto como es capaz, para que las ignoren.
En esos momentos, a menudo es descubierto algo de la naturaleza y curso mundanos,
o algo de la voluntad de Dios es manifestado.
Ven que algo que hacen o que han hecho no es del Padre, sino del mundo,
y que tal vez haya algo del Padre a lo que saben que tienen que someterse,
pero tienen miedo de la cruz, o de la vergüenza, o prefieren tener primero más claridad.
¡Oh, recuerden esto más tarde!
Si alguna vez quieren recibir vida, unirse a la verdad de Dios,
recibir Su Espíritu y poder, y establecerse ahí,
entonces sean obedientes a la visión celestial.
No consulten con carne ni sangre, sino obedezcan eso que fue prohibido o requerido,
sea poco o mucho.
Esta es la manera correcta, en la que sus mentes deben ser ejercitadas;
y si sus mentes son ejercitadas fielmente ahí,
el Señor los fortalecerá contra el tentador cuando
llegue con sus tentaciones y sutiles objeciones.
Pero si desfallecen aquí y no son fieles en lo poco, es probable que no reciban más,
ni experimenten la preservación del Señor en lo poco.
En realidad esta es la razón del fracaso de muchos,
porque no han recibido y amado esa cosa pequeña que les fue hecha manifiesta,
sino que se complacieron en la injusticia y persistieron en el disfrute
del espíritu del mundo (tanto en sí mismos como en los demás),
cuando fueron llamados por el Señor a dejarlo y salir de él.

[.numbered]
6+++.+++ Esperen las renovaciones de vida y el verdadero entendimiento en ustedes,
que vienen de Dios.
Esperen otra visita, esperen otro toque y demostración de Su Espíritu.
¿Dónde lo encontraron antes?
Vayan ahí de nuevo, esperen ahí de nuevo,
busquen al Señor para mantener sus espíritus hasta que Él aparezca otra vez.

¡Pero tengan cuidado, de que antes de que la luz se levante de nuevo,
antes de que la vida se mueva otra vez,
se hayan ido adonde ya no puedan reconocerlas ni
recibirlas por haber escuchado las tentaciones!
Porque el camino del Señor, el camino experimentado es, que después que Él llega,
después de los toques de Su verdad, llega el tentador con sus razonamientos, engaños,
semejanzas, etc.
En ese momento el Señor los está probando,
para ver cuánto quieren aferrarse sus corazones a Él. Si ustedes desatienden la tentación,
si se mantienen alejados del enemigo, Él aparecerá de nuevo para fortalecerlos,
consolarlos, revelarse más y conducirlos más lejos en el camino de vida,
más cerca del poder y pureza de este.
Pero si retroceden del lugar donde Él comenzó a obrar,
el alma del Señor no se agradará en aparecer más en ustedes, u obrar más en ustedes.

====

Les diré algo: Si ustedes no dejan entrar las tentaciones del enemigo, y bajo las nubes,
bajo las tormentas, bajo las tempestades, bajo los confusos razonamientos, temores,
dudas y dificultades, se mantienen mirando al Señor y esperando en Él,
y durante ese tiempo no hacen una alianza con el enemigo oponiéndose a Dios,
entonces el Señor ciertamente aparecerá. Y cuando
Él aparezca verán uno de estos dos efectos:
Que el poder de las objeciones o tentaciones del enemigo es tan quebrantado,
que ya no les prestarán atención;
o que dichas objeciones o tentaciones son respondidas por
la aparición y luz del Espíritu del Señor de manera tal,
que estarán satisfechos con respecto a ellas.
Ahora, cuál de estos es el mejor para ustedes, el Señor Dios lo sabe,
y de seguro lo recibirán en el momento.
Él no los dejará, sino que los apoyará en secreto durante ese tiempo,
mientras sus ojos y mentes estén hacia Él.

Cuando la luz y poder del Señor se levantan,
estos dispersan y quiebran en pedazos (en la mente) lo que antes era muy poderoso,
y como resultado, al alma no le importa más,
considerar o saber aquello que el enemigo le había
hecho creer que era muy necesario saber.
Porque, noten lo siguiente: Lo que me hace crecer es la experiencia de vida,
la consciencia de la presencia y poder del Señor conmigo, el conocimiento vivo,
el conocimiento que vivifica y da vida.
Ahora bien, cuando la vida brota, cuando la luz brilla, cuando el Señor,
en el poder y en las preciosas visitas de Su verdad alcanza mi corazón,
esto está presente conmigo.
Entonces,
¿qué importancia tienen para mí esas objeciones y
prejuicios que el enemigo arroja en mi mente?
¡Ninguna,
no puedo prestarles atención por estar absorto en otra cosa de una naturaleza más profunda!
Pues he descubierto por experiencia, que todo lo que me preocupaba,
que todo lo que dudaba se desvanece en un momento,
cuando lo que le pone fin a todos los pensamientos,
razonamientos y disputas está presente y prevalece en mí.

De nuevo,
en otras ocasiones al Señor le complace (cuando le parece bien) abrir
la mente y dejarla entrar en la luz de aquellas cosas (la mente que espera
en Él y deja esas cosas en paz hasta que sea Su tiempo),
que por sí misma nunca habría podido penetrar.
También he visto las objeciones y tropiezos con respecto a este precioso pueblo,
con respecto a la Semilla, camino, doctrina, prácticas...de ellos,
reveladas a mí en la clara luz de Dios y en las santas demostraciones de Su Espíritu.
En realidad, he visto manifiestamente y he sido plenamente satisfecho,
de que lo que era objetado en mi propio corazón y es objetado en los corazones de otros,
ha salido del sutil acusador de los hermanos,
quien da falso testimonio contra ellos y quiere arrastrar a tantos como pueda,
para que participen en su falso testimonio y se conviertan
en falsos testigos contra Dios,
Su verdad y Su pueblo.

Por tanto, tengan cuidado todos ustedes,
los que desean encontrar el reposo y satisfacción de sus almas en Él,
que no sean prejuiciados contra el camino por el que Dios ha determinado
obrar en ustedes y en todos los demás. Pues Él ha enviado a Su
Hijo para dar vida y no dará vida por ningún otro.
Él ha determinado que Su Hijo sea recibido como una semilla, como una semilla de vida,
y aunque sea como la más pequeña semilla de mostaza,
aún así debe ser recibido de esta manera.
En esta pequeña semilla, en Su baja aparición, el Hijo tiene la presencia de Dios con Él,
Su poder y autoridad, y lo que Él requiera, enseñe, prohíba, etc., debe ser obedecido.
Pero nadie sobre la tierra puede reconocer o someterse a esto,
a menos que también sea como un niño; sí,
como un niño muy pequeño. El espíritu del hombre, la sabiduría del hombre,
el conocimiento del hombre, la religión del hombre, el celo del hombre, etc.,
son demasiado grandes para entrar aquí. Los hombres son demasiado sabios,
demasiado entendidos,
demasiado ricos en escrituras y experiencias como para someterse a esto, es decir,
como lo fueron los escribas y fariseos en la aparición,
doctrinas y predicaciones de Cristo,
cuando Él apareció entre ellos en aquel cuerpo de carne.
Por tanto, entren en el verdadero sentimiento,
salgan del conocimiento muerto y entren en el vivo, donde la vida, poder, justicia, sí,
la paz y gozo del reino son gustados,
y en alguna medida experimentados por aquellos que se inclinan
en espíritu delante de la menor y más pequeña aparición de Jesús;
delante del más bajo grado y medida de Aquel,
cuya vida es Rey y Señor sobre la muerte para siempre.

=== Una Objeción Contra la Luz

[.discourse-part]
Objeción: Muchos creen, y en dicha creencia objetan contra nosotros,
que lo que nosotros llamamos luz o semilla no es
más que la consciencia natural del hombre.^
footnote:[Esta era una crítica común contra las enseñanzas de los primeros
cuáqueros con respecto a la semilla o luz de Cristo que mora en el interior.
Se objetaba que la luz a la que ellos dirigían los corazones y mentes de los hombres,
no era más que la consciencia natural.
Sin embargo,
los cuáqueros entendían la clara distinción que hay entre la consciencia
natural (una facultad del alma creada) y la eterna luz de Cristo que brilla,
convence y enseña desde __dentro de__ la consciencia.
Para un trato exhaustivo de esta objeción,
ver '`La Quinta y Sexta Proposición,`' sección 16,
de __Apología de la Verdadera Divinidad Cristiana__, de Robert Barclay.
(Disponible a través de Quaker Heritage Press impreso y en línea).]

[.discourse-part]
Respuesta: Yo puedo admitir que lo que nosotros llamamos luz, en un sentido, es natural,
pero no en el sentido que ellos piensan.
La luz, en realidad, es una semilla de la naturaleza de Dios, de la naturaleza de Cristo,
pero no de la naturaleza del hombre.
Es lo que se levanta en el hombre como un testigo
contra el hombre cuando este cae y transgrede.
Es una luz que en verdad brilla dentro de su consciencia,
pero que existe antes de que su consciencia fuera, y es de una naturaleza superior.
El hombre es terrenal (con su entendimiento, conocimiento, razón, juicio, consciencia),
pero la luz que brilla en él (es decir, en su corazón oscuro, duro, no regenerado,
terrenal) es celestial, por lo tanto,
sus tinieblas no pueden comprenderla aunque brille en ellas.

¿Desean ustedes (en el verdadero entendimiento) saber qué es esta luz?
Entonces experiméntenla.
Salgan de las tinieblas que están en ustedes y entren donde esa luz habita,
entonces la conocerán en verdad y serán capaces de juzgarla mejor.
Ahora les diré cómo sabemos nosotros que ella es la luz del nuevo pacto:
Porque la hallamos develando el nuevo pacto para
nosotros e introduciéndonos en él. También,
porque la hallamos mostrándonos los pecados contra el nuevo pacto,
equipándonos con poder de Dios contra ellos y preservándonos fuera de estos.
Con esta demostración, nuestros corazones están en verdad satisfechos.
Sí, podríamos decir mucho más con respecto a esta luz,
pero su propio testimonio resuelve plenamente el asunto para total satisfacción del alma,
donde quiera que este sea escuchado y sentido.

[.offset]
**Algunas Preguntas y Respuestas con Respecto al Nuevo Pacto,**
para exponer la naturaleza y forma de este,
tal como es por experiencia sentido en el corazón y testificado en las Sagradas Escrituras.

[.discourse-part]
Pregunta: ¿Qué es el nuevo pacto?

[.discourse-part]
Respuesta: Es un nuevo acuerdo entre Dios y el alma,
diferente del acuerdo anterior que había entre Dios y el
pueblo de los judíos. Es un pacto precioso y glorioso,
que contiene preciosas promesas por parte de Dios,
y que es tan fácilmente obtenible por parte de la criatura, como es posible.
Es el pacto de amor eterno de Dios; de vida, paz y reposo del alma.
Es el poder del Señor extendido al alma para liberarla de Egipto,
llevarla a través del desierto, introducirla en la Tierra Santa,
y darle su apropiada posesión y herencia ahí,
guardándola en dicha tierra contra todos sus enemigos.
Sí, este pacto contiene cosas muy preciosas,
de las que el alma tiene gran necesidad y se regocija
en el conocimiento y presencia de estas,
tales como: La ley de Dios escrita en el corazón, el temor de Dios puesto en el interior,
sí,
la colocación de Su propio Espíritu dentro para que
sea la fuente de vida y fortaleza ahí,
por medio del cual hace que el alma camine en Sus caminos,
y la guarda para que no se aparte de Él. De igual manera,
en este pacto Dios se convierte en el maestro que crea en el alma la capacidad de aprender,
obedecer y beneficiarse.
En este pacto hay perdón de la iniquidad y olvido de los pecados,
con la destrucción y desarraigo de lo que causaba el pecado,
y la curación de la apostasía del alma.

[.discourse-part]
Pregunta: ¿Cómo es hecho este pacto con el alma?

[.discourse-part]
Respuesta: En Cristo, la Semilla; Él es todo en este pacto.
Él es la luz del pacto, Él es la vida del pacto, Él es el poder del pacto,
Él es la justicia y santificación del pacto.
Al entrar en Él, el alma entra a este pacto, al permanecer en Él,
el alma permanece en este pacto, al crecer en Él, el alma crece en este pacto.

[.discourse-part]
Pregunta: ¿Es este un pacto absolutamente gratis?
O, ¿hay términos o condiciones que se requieren del alma en este?

[.discourse-part]
Respuesta: Es absolutamente gratis en su propia naturaleza.
Viene del amor gratuito de Dios, contiene el amor gratuito de Dios,
es ofrecido gratuitamente a todos los que se les ofrece,
es dado gratuitamente a todos los que se les da.
No hay precio,
no se requiere nada de la criatura para entrar en él. Todo lo que se requiere es que
la criatura lo reciba y se rinda a Dios en él. Pero al recibirlo y rendirse a este,
le será requerido mucho a la criatura, sin lo cual,
nunca llegará a recibir verdaderamente el pacto,
a permanecer en él o a cosechar las bendiciones contenidas
en él. Las Escrituras testifican de esto abundantemente,
junto con las experiencias de aquellos que conocen
y sienten la naturaleza y virtud del pacto.

[.discourse-part]
Pregunta: ¿Qué se requiere en este pacto según las Escrituras,
y según las experiencias de los que entran en él
y cosechan los frutos y beneficios de este?

[.discourse-part]
__Respuesta: 1.__ Se requiere que cuando el Señor llame, que cuando el Señor vivifique,
que cuando el Señor toque el corazón, abra el oído y dé la facultad y habilidad de oír,
entonces sea oído diligentemente.
El oído que Dios ha abierto debe ser mantenido abierto para Él,
y debe mantenerse cerca del poder por medio del cual abre un oído y cierra el otro,
y esperar al Señor en este.
De esta manera, el verdadero oído será más y más abierto por Él,
y el otro oído (el cual se inclina a oír y deja entrar
al enemigo) será cada vez más cerrado.

¿Quién hay entre nosotros que no haya sentido al Señor Dios requiriendo esto de nosotros?
Y en la medida que hayamos respondido a Su requisito,
en esa medida la obra de Dios ha continuado en nosotros.
En la medida que no hayamos respondido a Su requisito,
en esa medida la obra ha ido hacia atrás y no hacia adelante.
La Escritura da testimonio de lo mismo, como en Isaías 55:1-3,
donde se proclama el pacto gratuito, y sin embargo, hay algo que se requiere:
"`&hellip;Oídme atentamente, y comed del bien, y se deleitará vuestra alma con grosura.
Inclinad vuestro oído, y venid a mí; oíd, y vivirá vuestra alma;
y haré con vosotros pacto eterno, las misericordias firmes a David.`"

[.numbered-group]
====

[.numbered]
2+++.+++ Se requiere arrepentimiento;
se requiere volverse de la naturaleza y espíritu viejos e inmundos y no tocarlos más,
y asirse a eso que tiene poder contra estos y preserva de estos.
Esto también es sentido y experimentado hoy como un requisito de Dios,
como también testifican los antiguos, según 2 Corintios 6:17-18,
"`...y no toquéis lo inmundo; y yo os recibiré, y seré para vosotros por Padre,
y vosotros me seréis hijos e hijas, dice el Señor Todopoderoso.`"

[.numbered]
3+++.+++ Se requiere fe, creer el testimonio de la verdad y recibir el bautismo del Espíritu.
Aquel que quiera entrar en este pacto,
debe creer el testimonio del evangelio (el registro de Dios con respecto
a Su Hijo) con la fe que viene de Él. Este debe ser circuncidado,
bautizado, renovado y cambiado por Él. El que hace esto será salvo,
tal como lo prometió Cristo (Marcos 16). Y nadie será salvo de otra manera,
como lo prometió Aquel que tiene el poder de la vida y de la salvación.

[.numbered]
4+++.+++ Se requiere obediencia al evangelio,
sujeción a Cristo en el gobierno de Su Espíritu y guardar Sus mandamientos.
Pues tal como el primer pacto requería la obediencia propia al mismo,
así el segundo pacto requiere la obediencia propia a este.
Y así como no había salvación o permanencia en el primer pacto sin la obediencia a este,
tampoco hay en el segundo, sin la obediencia a dicho pacto.

====

Aquel que quiera disfrutar la paz, justicia, justificación, vida y poder de este pacto,
debe vivir en el Espíritu, caminar en el Espíritu y cumplir la voluntad del Espíritu.
Debe mantenerse en la Semilla y en la unción, para que el maligno no lo pueda tocar,
ni el obstaculizador, asesino y destructor de la vida en el corazón tenga poder sobre él,
como sí tiene poder sobre cualquiera que está fuera de los límites de este pacto.
Porque dentro del pacto está todo lo bueno, pero fuera de él está lo malo;
están los peligros, las tentaciones, las trampas, la muerte y destrucción del alma.
Y cualquiera que deambule fuera del pacto, no puede evitar encontrarse con esto.
Por lo tanto, se debe tener mucho cuidado de permanecer en eso que ha reunido,
en eso que ha vivificado, en eso que da el verdadero sentido y entendimiento,
y que mantiene fuera de lo incorrecto.
¡Cuán tierno, cuán gratuito era el amor de Cristo a Sus discípulos!
Sin embargo, les ordenó que permanecieran en Su amor y les dijo cómo debían hacerlo:
"`Si guardareis mis mandamientos, permaneceréis en mi amor;
así como yo he guardado los mandamientos de mi Padre, y permanezco en su amor.`"

[.discourse-part]
Pregunta: Pero, ¿cómo podrá realizar el alma todas estas cosas?
¿Son demandadas al alma para que las realice en su propia fuerza,
o se encarga Dios de realizarlas y obrarlas en ella?

[.discourse-part]
Respuesta: Absolutamente no en la fuerza,
voluntad o sabiduría del alma (pues estas cosas están
eternamente excluidas de este pacto),
sino en la fuerza, vida y poder que fluyen de Dios en el pacto.

[.discourse-part]
Pregunta: Entonces, ¿cómo recibirá el alma esta fuerza, vida y poder?

[.discourse-part]
Respuesta: Abrazándolo conforme llega, asiéndose a ello, anhelándolo,
llorando y esperándolo pacientemente.
No despreciando lo pequeño, ni buscando más antes de que lo pequeño sea recibido,
sino que con agradecimiento, hospedando los comienzos de la vida,
los comienzos de las sagradas instrucciones,
las primeras separaciones del espíritu y naturaleza de este mundo, en lo que sea.
Aquel que no discute acerca de estas cosas, sino que las recibe tal como aparecen,
velando en la luz en sencillez y nobleza,
será bendecido por el Señor y se encontrará con el
deseo de su alma en el tiempo del Señor,
cuando el Señor haya adecuado y preparado su corazón para ellas.

Ahora bien, esta puerta es tan pequeña y estrecha, es un comienzo tan pobre y bajo,
que la sabiduría del hombre no puede entrar.
Y si hubiera una pequeña entrada a través de ella (por el poder vencedor de la vida),
aún así, la sabiduría del hombre, a menudo y rápidamente,
querrá hacer retroceder al alma de nuevo.
El hombre sabio dice:
'`¡Déjenme conocer primero la doctrina! ¡Primero entenderé la doctrina
a fondo antes de cambiar mi camino actual!`' No,
dice Cristo: '`El que hace Su voluntad,
conocerá la doctrina.`' (Juan 7:17) Ustedes conocerán un poquito,
lo cual alcanzará sus corazones.
Ahí deben comenzar y al ser fieles ahí, conocerán más de la doctrina.
Pero si no son fieles,
tropezarán y serán prejuiciados contra la doctrina y nunca la podrán conocer.
¡Oh, el misterio de la vida! ¡Oh, el camino oculto de este, el cual nadie puede aprender,
sino aquellos a quienes el Padre enseña! Sin embargo,
muchos piensan aprender en la mente que siempre ha estado y que siempre estará excluida.
'`Si Cristo pusiera Su doctrina delante de ellos,
y la hiciera apta para sus entendimientos, entonces la recibirían.`' No, no;
ellos deben inclinarse ante Cristo, ante Su nombre, ante Su poder, Su voluntad,
Su manera de manifestar Su verdad, porque Él no se inclinará ante los de ellos.

[.discourse-part]
Pregunta: ¿Cuáles son los pecados contra este pacto y qué efectos tienen?

[.discourse-part]
Respuesta:
Los pecados contra el pacto son principalmente incredulidad
en el poder y desobediencia a dicho poder,
los cuales son de una naturaleza más profunda que los pecados contra el primer pacto,
y tienen efectos más peligrosos.
El rechazo a este pacto es más peligroso que el rechazo
al pacto de Moisés. El quebrantamiento del pacto aquí,
es decir, el volverse de Dios (por causa de un corazón incrédulo),
es más peligroso que el quebrantamiento al primer pacto.

[.discourse-part]
Pregunta: Pero, ¿puede ser quebrantado este pacto?
¿No se ha encargado Dios de todo en él?

[.discourse-part]
Respuesta: Este pacto es un acuerdo entre Dios y el alma,
en el que le son requeridas cosas al alma,
a través de la vida y fuerza que fluyen de este.
El alma puede escuchar al enemigo y no al Señor,
puede caminar según la carne y no según el Espíritu,
puede codiciar un alto conocimiento y cosas escondidas del
reino (como los antiguos que curiosearon dentro del arca),
puede retirarse del Señor en aquellos aspectos en
los que anteriormente se había rendido a Él, etc.
Ahora, estas y otras cosas similares son violaciones al pacto, son pecados contra este,
que atraen juicios sobre el alma en el momento y
que al final darán como resultado un total abandono,
a menos que mediante los juicios,
sea traída de regreso al acuerdo con el Señor en verdad y rectitud.

Es cierto que el Señor hace todo en el pacto según Su buena voluntad,
pero Él ha determinado una forma de obrar la vida y la felicidad del alma,
y Se complace en aferrarse a esta forma.
Su forma es Cristo, Su semilla.
De esta Semilla fluye todo el amor, misericordia, cuidado y ternura de Dios.
A esta semilla debe venir el alma, y en ella debe permanecer,
para que pueda disfrutar y poseer estas cosas.
Pero si el enemigo saca (por cualquier medio) el alma de ahí,
la saca de su propia vida y fuerza,
y de las dulces bendiciones e influencias del pacto santo y gratuito.
Ahora, el Señor no le ha dado poder al enemigo para forzar al alma a salir del pacto,
más bien le da poder al alma para que permanezca con Él ahí,
y si en la hora de angustia ella clama a Él,
Él ayuda al indefenso y levanta un estandarte contra el enemigo.

Todo el que desee la dulzura de este pacto, la vida, virtud y bendiciones de este,
¡esperen sentir y recibir algo de Dios, y en ese don aprendan a temer delante de Él,
a caminar como es digno de Él, y a no contristar o provocar a Su Espíritu!
Porque Él tiene el poder de la vida y de la muerte en Su mano,
y de quien tenga causa suficiente, Él puede apartarse y cortar.
Y de quien quiera,
Él puede extender misericordia en la medida y por el tiempo que le plazca,
porque es Suya y puede hacer lo que quiera con ella.
Sólo sepan esto: Dios es amor; Dios es ternura, infinita ternura.
Sí, Su compasión está más allá de la imaginación o de la comprensión,
y odia dejar por fuera.
Él no puede desechar a las pobres y tristes almas que claman a Él,
sienten su necesidad de Él y Lo anhelan.
Pero los sabios, confiados y que presumen de su propia comprensión de las Escrituras,
que piensan que están a salvo por virtud del pacto,
aunque son enemigos de la luz del pacto en sus mentes,
están fuera del pacto en el presente (caminando en sus propias imaginaciones y concepciones),
y en el mayor peligro de todos los que conozco.
Ojalá el Señor en Su misericordia haga que Su luz brille, que Su vida se levante,
que Su poder se manifieste, y de este modo,
los introduzca y preserve en Su pacto según Su buena voluntad.
Amén.

[.discourse-part]
Pregunta: ¿Cuál es la casa de Israel y la de Judá,
con quienes este nuevo pacto debe ser hecho?
¿Es el Israel y Judá según la carne, es decir, el Israel y Judá según el antiguo pacto,
o según el nuevo pacto?

[.discourse-part]
Respuesta: Cuando el antiguo pacto pasó,
el reconocimiento de Israel y Judá según la carne también pasó. El nuevo
pacto está adaptado y hecho con el nuevo Israel y Judá. Así que ahora,
como dijo el apóstol: "`No es judío el que lo es exteriormente,
ni es la circuncisión la que se hace exteriormente en la carne;
sino que es judío el que lo es en lo interior,`" etc.
Este evangelio derriba la distinción externa entre el judío y el gentil,
y levanta otra distinción interna en ambos,
de modo que las promesas y bendiciones no son para uno u otro en el antiguo estado,
sino para ambos conforme son reunidos y brotan en la nueva Semilla.

[.discourse-part]
Pregunta: ¿Es este pacto sin falta?
¿Repara los defectos que encontró Dios en el primer pacto?
¿Preserva este pacto de manera más firme en Él que el otro?
¿Acaso no es posible apostatar de él?

[.discourse-part]
Respuesta: Sí, es sin falta.
Repara los defectos del otro.
Preserva más firmemente en Dios.
No hay posibilidad de apostatar de él,
por parte de aquellos en quienes está plenamente
hecho y que están establecidos en él. Sin embargo,
durante el paso y el viaje, el alma que no es fiel ni vigilante,
corre peligro de ser arrastrada de lo que le da derecho y entrada al pacto.
Pues así como el comienzo es en la fe y en la obediencia, así deben ser la continuación,
el crecimiento y el progreso.
Y así se predicó el evangelio: "`El que creyere y fuere bautizado, será salvo.`"
Este "`creyere`" no sólo incluye el creer del comienzo, sino la continuación del mismo;
el creer hasta el fin.
Porque así dice la promesa y la palabra de Cristo:
"`El que persevere hasta el fin será salvo.`"
Pero si algún hombre retrocede del Señor, de Su Espíritu,
y regresa al camino de muerte con el otro espíritu,
el alma del Señor no se agradará de él.

[.discourse-part]
Objeción: Entonces este pacto es como el primero,
depende de la criatura y es tan defectuoso como lo era el otro.

[.discourse-part]
Respuesta: No, este pacto no depende de la criatura, sino del amor,
misericordia y poder de Dios que no tienen límites en este pacto.
Depende de la Semilla de Su vida,
del poder de Su Espíritu gratuitamente dispensado a la criatura.
No obstante, la criatura que quiera cosechar y disfrutar esto,
debe entrar en él en la fe y poder de la Semilla
y permanecer en la misma fe y poder con Ella.
Pues Dios no obliga a nadie a entrar, sino que persuade y da el querer.

Tampoco obliga a nadie a quedarse, sino que persuade y pone el deseo de permanecer.
Esta es Su manera de obrar en el día de Su poder.
Ahora bien, si el alma escucha al otro espíritu y sus persuasiones, se sale del Señor,
no quiere escuchar ni ser ganada de nuevo,
el amor y placer del Señor se volverán de ella, según la ley de este pacto.
Porque este pacto tiene una ley en concordancia con
su naturaleza (de acuerdo a la cual obra el Señor),
así como el otro pacto también tenía una.
Busquen en las Escrituras con respecto a esto.
¿Hay alguna promesa de salvación aparte de ir al Hijo?
O, ¿hay una promesa para los que llegan y no permanecen?
¿No les dijo Cristo a Sus propios discípulos que así como estaban en la vid, en Su amor,
así debían permanecer ahí? Esta fue la ley que Su Padre le dio,
y es la misma ley que Él les dio a ellos.
Es natural para el hombre desviarse,
y si se sale del pacto donde están la vida y la virtud,
¿cómo no va a perder la vida y la virtud de ello?
Por tanto, el Señor ha provisto en este pacto lo que sanará las rebeliones,
lo que preservará poderosamente, etc.
Sin embargo, el hombre debe venir al pacto (debe venir al Hijo,
debe venir a las aguas) y también debe permanecer ahí. Aún así,
no se requiere que él haga esto por sí mismo,
de acuerdo a la ley y dirección del antiguo pacto,
sino que lo haga en esa nueva habilidad que está en la nueva Semilla de vida,
en donde diariamente la recibe.
Sí, esta nueva habilidad está con él y cerca de él,
diariamente llevándolo a la vida y preservándolo en ella,
y dentro de los límites del pacto,
de la misma manera que el tentador está arrastrándolo a pecar contra el pacto,
y por tanto, arrastrándolo a la muerte.

[.discourse-part]
Pregunta: ¿Qué promete hacer Dios por la nueva casa de Israel y Judá en este nuevo pacto?

[.discourse-part]
Respuesta: Promete poner Sus leyes en sus mentes y escribirlas en sus corazones.
(¡Oh, feliz aquel que experimenta estas leyes, esta mente,
este corazón y esta manera de escritura!) Él promete
ser el Dios de ellos y que ellos serán Su pueblo.
Promete convertirse en el Maestro de ellos, y tal Maestro que todos lo conocerán,
desde el menor hasta el mayor.
Promete quitar lo que puede obstaculizar las cosas buenas del pacto,
porque Él será misericordioso a sus injusticias y no se
acordará nunca más de sus pecados ni iniquidades.

=== La Razón del Mal Entendimiento de las Escrituras

[.discourse-part]
Pregunta:
¿Cuál es el fundamento del mal entendimiento y tergiversación
de las Escrituras por parte de los hombres?

[.discourse-part]
Respuesta:
__1+++.+++ La falta de familiaridad con el Espíritu de Dios
y de la forma correcta de esperar en Él,
para recibir el verdadero entendimiento de ellas.__
Es posible que los hombres vayan tan lejos como para saber y confesar
que el Espíritu del Señor es el único que revela las cosas de Dios,
y el único intérprete correcto de Sus propias palabras, y sin embargo,
el mismo hombre que confiesa esto puede que no conozca verdadera
y claramente al Espíritu del Señor. Puede que no sepa cuando está
recibiendo la interpretación de una escritura del Espíritu,
de su propio entendimiento o de un espíritu contrario.
Porque hay otro espíritu cerca del hombre, cuya naturaleza,
obra y deleite es hacer que él malentienda y haga mal uso de las Escrituras,
y puede traérselas de manera cordial y clara,
con el propósito de engañarlo y extraviarlo.
Ahora, el que abraza y recibe todo lo que se levanta en su interior,
fácilmente se topa con la trampa del enemigo.
Por tanto, el hombre debe vigilar, esperar, temer y orar,
para poder discernir entre la naturaleza y voz del Espíritu
de Dios y las del espíritu del enemigo en él,
y así, (en la luz del Señor) saber cuando habla el Señor,
y también cuando se esfuerza por hablar como el Señor el misterioso espíritu de engaño.

[.numbered-group]
====

[.numbered]
2+++.+++ __La falta de familiaridad con la verdad de Dios en el amor, vida y poder de esta.__
Porque para el que conoce la verdad y ha recibido
de Dios la cosa de la que hablan las Escrituras,
¡cuán fácil le resulta entender las palabras que hablan de dicha cosa!
Pero aquel que tiene conocimiento de la cosa únicamente a partir de palabras,
¡cuán fácil le resulta malentender las palabras!

[.numbered]
3+++.+++ __Las opiniones, entendimientos,
formas y prácticas que los hombres han adoptado en
las tinieblas y con las que sus mentes están involucradas,
son un gran obstáculo para la correcta comprensión de las Escrituras.__
Porque ha habido un día nublado y oscuro, o una gran noche de tinieblas sobre la tierra,
en donde la luz que conduce al reposo del alma no
ha brillado claramente en los espíritus de los hombres.
Y así, en esta nublada oscuridad,
los hombres han vagado de una montaña a una colina buscando su lugar de reposo.
Ahora, algunos se han establecido en una montaña y otros en otra;
algunos en una colina y otros en otra, diciendo:
'`Aquí está el lugar de reposo.`' Y cuando el Espíritu del Señor viene y exclama:
"`Levantaos y andad, porque no es este el lugar de reposo,
pues está contaminado,`" no pueden oír. ¿Por qué? Porque ya han
creído lo contrario y piensan que han encontrado su reposo.

====

=== Algunas Preguntas con Respecto al Engaño y a los Engañadores

En la verdad no hay engaño; los que están en la verdad están fuera del engaño,
y al permanecer en ella, están fuera del alcance de los engañadores.
Pero los que están fuera de la verdad ya están en el engaño,
y día a día son más propensos a ser más engañados y a ayudar a engañar a otros.

[.discourse-part]
Pregunta: ¿Qué es el engaño y quiénes son los engañadores?

[.discourse-part]
Respuesta: Eso que parece la verdad, pero no lo es,
es el engaño. Y aquellos que tienen apariencia de piedad, pero no tienen el Espíritu,
vida y poder de esta, son los engañadores.

[.discourse-part]
Pregunta: ¿Quiénes son los más susceptibles al engaño?

[.discourse-part]
Respuesta: El simple, el despreocupado, el descuidado, el crédulo;
los que no esperan en el Señor en la luz, poder y demostración de Su Espíritu.
Estos (a través de buenas palabras,
discursos agradables y apariencia de las cosas) son
fácilmente apartados de la verdad misma,
y llevados a una semejanza o parecido de esta.

[.discourse-part]
Pregunta: ¿En qué tiempo ocurre el engaño?

[.discourse-part]
Respuesta: Durante la noche; durante el tiempo nublado y oscuro;
cuando el enemigo ha levantado su bruma y neblina en las mentes de los hombres.
Él engaña sus corazones durante este tiempo.

[.discourse-part]
Pregunta: Y ahora, ¿es de noche o de día?

[.discourse-part]
Respuesta: Es de noche para algunos y de día para otros.
Donde se ha levantado la luz,
ahí es de día. Donde la noche cubre y posee las mentes de los hombres, ahí es de noche.

[.discourse-part]
Pregunta: ¿Cómo puede saber un hombre si es de noche o de día para él?

[.discourse-part]
Respuesta: Cuando al esperar siente algo de la vida de Dios levantarse en él,
se vuelve y escucha Su testimonio.

[.discourse-part]
Pregunta:
¿Cómo puede salir un hombre de la oscuridad de la noche a la luz y brillo del día?

[.discourse-part]
Respuesta:
Uniéndose a los primeros destellos y brotes de la luz en
él. La más pequeña luz de la verdad tiene la misma naturaleza,
virtud y propiedades que la más grande.
Aunque no sea igual en medida, aún es del mismo género.
El que quiera llegar a la más grande medida,
debe empezar con la más pequeña. La luz pone de manifiesto;
el día descubre tanto las cosas de la noche como del día.

¿Han descubierto algo de alguno de los dos géneros,
sea del que es bueno o del que es malo?
¿Sea del que es de la naturaleza mundana y del maligno,
o del que es de la naturaleza celestial y del Santo?
Entonces únanse inmediatamente a la virtud,
fuerza y poder de eso que hace el descubrimiento,
y sus espíritus encontrarán ahí una entrada a la
luz del día. Y al continuar fielmente en esta,
la luz brotará en ustedes más y más cada día,
hasta que haya sacado sus espíritus de la negrura, oscuridad y engaño de la noche,
y los haya reunido en la belleza, brillo y verdad del día.

[.discourse-part]
Pregunta: ¿Cómo puede ser guardado un hombre del engaño y de los engañadores?

[.discourse-part]
Respuesta: Al permanecer en eso que se lo revela y lo protege de ellos.
Al morar en esa luz, en esa vida, en ese poder y en esa verdad, a la que no pueden entrar.
Porque en Dios, en Su Semilla, en Su naturaleza, el maligno no puede encontrar nada,
ni tampoco puede entrar.
El que permanece en Él está a salvo en Él, pero el que se sale de la vida,
se sale de la luz, se sale de la Semilla, se sale del poder que preserva,
se sale de la santa unción que mantiene el ojo abierto,
y fácilmente tropieza y se enreda en el engaño de la injusticia.

=== Una Pregunta con Respecto a los Milagros Respondidos

[.discourse-part]
Pregunta: Si esta es una nueva dispensación de la vida y poder de Dios, es decir,
de la predicación del evangelio eterno otra vez después de la apostasía,
¿por qué dicha predicación no es acompañada ahora con milagros externos,
como lo fue anteriormente?
Digo milagros _externos,_ porque en realidad está acompañado con milagros internos.
Pues el cojo que no podía poner un pie en el camino de vida, ahora camina;
los ojos que estaban ciegos han sido abiertos, y ahora ven;
los oídos que estaban sordos han sido destapados, y ahora oyen;
los leprosos internamente, que estaban llenos de pecado y corrupción, han sido lavados,
limpiados y sanados por el poder puro.
Sí, los muertos internamente han sido vivificados,
levantados y vueltos Al que vive para siempre; han recibido vida de Él,
viven en Él y con Él. Ahora, estas son cosas poderosas, milagros maravillosos, es decir,
la sustancia tanto de los milagros que fueron hechos bajo la ley,
como los que Cristo mismo obró externamente.
Porque la sanidad externa no es la verdadera salvación, vida, ni poder, en realidad;
estos milagros externos apuntan a lo que debe obrar internamente,
para que el hombre ponga su expectativa en los milagros internos, los conozca,
espere en ellos, y sea hecho partícipe de la salud y salvación internas.
Sin embargo, viendo que a Cristo le plació exponer Su poder externamente,
con el fin de señalar y dar testimonio de lo interno, ¿por qué no lo hace ahora?

[.discourse-part]
Respuesta: Porque la naturaleza de la presente dispensación no lo requiere.
Pues la presente dispensación de vida es,
llevar a los hombres a la Semilla de Vida que está dentro de ellos (la
cual es la suma y sustancia de todas las dispensaciones anteriores).
Y para llevarlos a Ella,
no tiene que haber algo de una naturaleza externamente milagrosa,
sino sólo el testimonio, demostración e iluminación del Espíritu en el interior.^
footnote:[Al decir esto,
Penington no está negando la existencia de milagros
externos en la presente era del evangelio.
Simplemente está argumentando que tales milagros no son necesarios ahora,
para confirmar o establecer las verdades del nuevo pacto.
De hecho,
es bien sabido que varios milagros y sanidades notables
acompañaron el ministerio de George Fox,
y de algunos otros de los primeros Amigos.]

Ahora bien, en el tiempo en que la ley externa debía ser recibida,
el Señor vio la necesidad de confirmarla mediante milagros externos.
Luego, en los días de los profetas sucedió lo mismo,
mientras esta dispensación se mantuvo vigente, hasta la venida de Cristo.
Posteriormente, cuando Cristo vino en el cuerpo preparado por el Padre,
le plació al Señor confirmar por medio de demostraciones
externas y visibles de Su poder en Él,
que este era Él. De igual manera sucedió después con los apóstoles,
al tener que predicar y testificarle al mundo la doctrina con respecto a esa aparición,
le plació al Señor y vio bueno, confirmarla también por medio de milagros.
Pero ahora no hay una nueva doctrina que predicar.
La doctrina con respecto a Cristo es la misma ahora que la de entonces,
exactamente la misma que predicaron los apóstoles.
Tampoco hay necesidad de confirmarla ahora,
pues en general es creída entre los profesantes cristianos de todos los tipos.
Porque, ¿quién duda del nacimiento de Cristo, predicación, vida santa,
muerte (al ofrecerse a Sí mismo como sacrificio por el pecado), resurrección, ascensión,
que está sentado a la diestra del Padre, etc.? No obstante,
bajo todo este conocimiento los hombres aún esconden sus pecados,
sus deseos y corrupciones, sirviendo no al Señor (ni verdaderamente temiéndole,
creyéndole, ni obedeciéndole), sino a Sus enemigos, corrompiéndose como los paganos.
Estos son cristianos de palabra,
pero en cuanto a caminar en santidad en el poder
de una vida indestructible están tan lejos,
como el mismo pagano.

Así que, el Señor ahora ha visitado al mundo en este estado,
y ha enviado lo que juzgó necesario para él en dicho estado, que es,
no un ministerio que predique de nuevo la misma doctrina
(bajo la cual el mundo cristiano se ha corrompido),
sino uno que apunte a la Semilla de vida,
en la cual están la luz y el poder para revelar,
guiar y eliminar esa corrupción. Y de este ministerio sale el poder
para alcanzar el corazón y levantar al Testigo en todo el que teme
al Señor. De este modo el Testigo interno lo confirma,
la mente es internamente satisfecha, y llega a conocer la verdad y a volverse a ella.

Ahora bien, esto (y su efecto) está más allá de los milagros externos,
y más allá de la satisfacción o seguridad que ellos puedan ofrecer.
Porque tales milagros dejan una discusión en la mente
(pues a pesar de todos los milagros que Cristo mostró,
aún existía una discusión e insatisfacción en las mentes de muchos con respecto
a Él). Pero para el que siente la cosa misma en la verdadera Semilla,
donde son recibidas la demostración y la certeza de la seguridad del Espíritu,
este ha viajado más allá de toda discusión,
y ha sido introducido (en alguna medida) en la naturaleza de la cosa,
más allá de la satisfacción que los milagros pueden ofrecer.
Él está fuera del estado y mente que piden una señal
o que buscan confirmación por medio de una señal.

=== Un Breve Comentario con Respecto a las Reuniones en Silencio

Esto es un gran misterio que está escondido del ojo del hombre,
que ha huido de la vida interior hacia las observaciones externas.
Él no puede ver que esto es requerido por el Señor de Su pueblo,
no reconoce ninguna edificación en esto, ni beneficio alguno por este medio.
Pero para la mente que es atraída al interior, el asunto está claro,
y la verdadera edificación en la vida de Dios y la comunión
unos con otros son dulcemente sentidas en ello.
Porque en estas reuniones es recibido un precioso
refrigerio procedente de la presencia del Señor,
por aquellos que atentamente esperan en Él,
según la guía y requerimientos de Su Santo Espíritu.
Ahora, si al Señor le place, abriré esto un poco más para el de corazón recto.

Después de que la mente se vuelva al Señor en alguna medida,
se sientan Sus vivificaciones y Su Semilla empiece a levantarse y a brotar en el corazón,
entonces la carne debe ser silenciada delante de Él y el alma debe esperar en
Él (Sus siguientes apariciones) en esa medida de vida que ha sido revelada.
Ahora bien, es algo muy grande experimentar la carne silenciada,
sentir los razonamientos y los discursos de la mente carnal aquietados,
y la expectativa puesta en la sabiduría, luz y guía del Espíritu de Dios.
Porque el hombre tiene que experimentar su propia pobreza, su nadedad,
la verdadera humildad y el silencio de su espíritu ante
el Señor. Debe despojarse de todo su conocimiento,
sabiduría, entendimiento y habilidades; de todo lo que es, ha hecho o pueda hacer,
para ser vestido y llenado de la naturaleza, Espíritu y poder del Señor.

Entonces, en esta medida de vida que es de Cristo,
en la cual Cristo está y aparece al alma, está el poder de la vida y de la muerte.
Está el poder para matar la carne y el poder para vivificar para Dios.
Está el poder para hacer que el alma cese de sus propias operaciones,
y el poder para obrar en y para el alma lo que Dios requiera y sea aceptable a Su vista.
En esta medida de vida debe ser esperado y adorado continuamente Dios,
tanto en privado como en público, según Su Espíritu guíe y enseñe.

Porque el Señor requiere de Su pueblo, no sólo que lo alaben privadamente,
sino que también se reúnan a adorarlo en los tiempos
y de acuerdo a los movimientos de Su Espíritu.
Y aquellos que son enseñados por Él no se atreven a dejar de congregarse,
como muchos tienen por costumbre,
sino que vigilan contra tales tentaciones y trampas del enemigo.

Y esta es la manera en que deben adorar: Deben esperar en el Señor,
reunirse en el silencio de la carne,
y estar atentos a los movimientos de Su vida y a las apariciones de Su poder entre ellos.
Y en los levantamientos de dicho poder pueden orar, hablar, exhortar, reprender, cantar,
llorar, etc., según el Espíritu les enseñe y requiera, y les dé que hablen.
Pero si el Espíritu no requiere que se hable, ni da nada para que sea declarado,
entonces todos deben sentarse quietos en su lugar (en su lugar celestial,
es lo que quiero decir), sintiendo cada uno su propia medida, alimentándose de ella,
y recibiendo de ella en su espíritu lo que el Señor le dé.

En esto hay edificación, edificación pura, edificación preciosa.
El alma que espera en esta forma es, por este medio,
individualmente edificada por el Espíritu del Señor en cada reunión,
y también se siente la vida de todos en cada vasija
que está vuelta internamente hacia su propia medida.
Porque la calidez de la vida en cada vasija no sólo calienta al individuo,
sino que todas las vasijas son como un montón de carbones
frescos y vivos que se calientan unos a otros,
y una gran fuerza, frescura y vigor de vida fluye a todos.
Y si alguno es agobiado, tentado, abofeteado por Satanás, y está doblegado, sobrecargado,
decayendo, afligido, angustiado, etc.,
el estado de este es sentido en el Espíritu y clamores secretos ascienden al Señor por
él. Muchas veces este encuentra tranquilidad y alivio en unas pocas palabras habladas,
o incluso, cuando no hay palabras.

Ahora, en cuanto a reuniones completamente en silencio,
en las que hay una resolución a no hablar, estas son desconocidas para nosotros.
Al contrario, nosotros esperamos en el Señor, ya sea para sentirlo en palabras,
o en silencio de espíritu sin palabras, como a Él le plazca.
En lo que se refiere a nuestras reuniones,
lo que queremos y lo que el Espíritu nos ha enseñado a buscar,
es que la carne de cada uno sea mantenida en silencio,
y a que no haya edificación excepto en el Espíritu y poder del Señor.

Ahora, hay varios estados de personas.
Algunas sienten poco de la presencia del Señor,
y más bien sienten tentaciones y pensamientos,
con muchos vagabundeos y desvaríos de mente.
Estas todavía no están familiarizadas con el poder, o al menos, no conocen su dominio,
sino que aún sienten dominio del mal sobre el bien en ellas.
Este es un estado penoso y de mucho dolor,
y nuestras reuniones para tales personas (muchas veces)
pueden parecer más para lo peor que para lo mejor.
Sin embargo, incluso estas personas, mientras se alejan,
tanto como pueden de estas cosas,
y se adhieren (o al menos con sinceridad de corazón
desean adherirse) a lo que testifica contra la carne,
tienen aceptación del Señor en esto.
Y al continuar esperando en esta dificultad y angustia
(no dejando de asistir a las reuniones,
en temor y sujeción al Señor que requiere esto,
aunque con un beneficio aparentemente pequeño),
obtienen un beneficio escondido en el momento presente,
y cosecharán un beneficio más claro y manifiesto después,
conforme el Señor consuma y desgaste en ellas la
parte en donde las tinieblas tienen su fuerza.

Dios debe ser adorado en Espíritu, en Su propio poder y vida,
y esto está a Su propia disposición. Su iglesia es una reunión en el Espíritu.
Si algún hombre habla ahí, debe hablar como oráculo de Dios (1 Pedro 4:11),
como la vasija a partir de la cual Dios habla,
como la trompeta a partir de la cual Él da sonido.
Por lo tanto, debe esperarse en silencio hasta que el Espíritu del Señor mueva a hablar,
y dé también las palabras para hablar.
Porque un hombre no debe hablar sus propias palabras, o en su propia sabiduría o tiempo,
sino las palabras del Espíritu, en la sabiduría y tiempo del Espíritu,
que es cuando Él mueve y da para hablar.
Y puesto que el Espíritu alimenta internamente incluso
cuando no mueve a hablar con palabras,
entonces este sentido y alimento internos deben ser
esperados y recibidos cuando no hay palabras.
De hecho,
el ministerio del Espíritu y vida está más cerca e inmediato cuando es sin palabras,
que cuando es con palabras,
como ha sido a menudo sentido y fielmente testificado por muchos testigos.
El ojo no ha visto, ni el oído ha oído,
ni ha entrado en el corazón del hombre cómo y qué
cosas revela Dios a Sus hijos por el Espíritu,
cuando ellos esperan en Él en Su temor puro, y adoran y conversan con Él en Espíritu.
Porque entonces la fuente del gran abismo es abierta y los manantiales
eternos ciertamente entregan el agua viva y pura.
