== Capítulo 9. La Vida e Inmortalidad Sacadas a la Luz Por el Evangelio

=== Dos Preguntas con Respecto a la Enseñanza de Dios

[.discourse-part]
Pregunta: ¿Cuál es la razón por la que otros no pueden aprender,
ni sujetarse a las mismas verdades espirituales que Dios nos manifiesta a nosotros,
y a las que sujeta nuestros espíritus?

[.discourse-part]
Respuesta:
La razón es porque no aprenden de la misma manera que Dios nos enseña a nosotros.
Y así,
aunque puede ser que tengan más ventajas que nosotros en cuanto a habilidades naturales,
aprendizaje, etc., y que estudien duro para saber más,
no entran en la forma correcta en la que el Espíritu de Dios enseña,
y nunca llegan a aprender la verdad.

[.discourse-part]
Pregunta: ¿Cuál es la manera por la que Dios les enseña a ustedes?

[.discourse-part]
Respuesta: Esta es la manera por la que Dios nos enseña:
Nos da un entendimiento para conocer Al que es verdadero,
y abre un oído en nosotros para que oigamos Su voz.
Y así, al mantenernos dentro de los límites de ese entendimiento y de ese oído,
llegamos a oír y a conocer correctamente.

"`Mirad, pues, cómo oís,`" dijo Cristo.
¡Oh, el Señor nos ha hecho conscientes del peso de esa escritura!
Nosotros a menudo hemos experimentado que es fácil oír mal, leer mal, orar mal,
creer mal, esperar mal, pero lo que es difícil,
es hacer cualquiera de estas cosas correctamente.
Es por eso que somos enseñados a esperar la agitación de las aguas,
el movimiento del Santo Espíritu de Dios sobre nuestros espíritus,
y sólo entonces son sentidas y recibidas de Él la virtud
y habilidad sanadoras para realizar lo que Él requiere.

De modo que, cuando leemos las Escrituras,
nuestros ojos están hacia Él y vigilamos contra nuestros propios entendimientos,
contra lo que podríamos reunir o comprender por nosotros mismos.
Y así esperamos hasta sentir que abra nuestros espíritus,
y qué les manifiesta una vez abiertos.
Si Él no deja nada, no recogemos nada, pero si da luz,
entonces en Su luz vemos y recibimos luz.
Asimismo,
al orar esperamos sentir el nacimiento de la Vida respirar
en nosotros (la que es del Padre y a la que el Padre oye),
y en la medida que el Espíritu del Padre respira sobre el alma y esta respira al Padre,
en esa medida podemos orar.
Pero cuando la vida se detiene, nosotros nos detenemos,
y no nos atrevemos a ofrecerle a Dios ningún sacrificio por nuestra propia cuenta,
sino únicamente el que el Padre prepara y nos da.
Igualmente al comer y beber, y en cualquiera cosa que hagamos,
nuestros corazones se retiran al Señor y esperamos hasta
sentir que todo es santificado por Su presencia y bendición;
aquí todo es en verdad dulce para nosotros.
En cualquier cosa que el Señor nos permite hacer,
observamos cuidadosamente la dirección de Cristo,
"`no sepa tu izquierda lo que hace tu derecha.`"
Porque nosotros no somos nada por nosotros mismos,
ni podemos hacer algo por nosotros mismos,
de manera que cualquier cosa hecha en nosotros,
es hecha conforme experimentamos la gracia de Dios, la virtud y el poder de Su vida,
obrando todo en nosotros.

En esta disposición de espíritu no encontramos nada demasiado difícil para nosotros,
pues la fortaleza de Cristo siempre está a la mano, aun en medio de nuestra debilidad,
y las riquezas del reino siempre están disponibles,
aun en medio de nuestra pobreza y nadedad.
Su fortaleza opera y nuestra debilidad no obstaculiza
la gloria del que obra a través de ella.
Así que estamos seguros, por una constante consciencia y diaria experiencia,
que no es porque queramos o corramos según nuestra
propia sabiduría y fuerza que logremos algo,
sino porque Dios nos muestra misericordia en Cristo.
Por esta razón esperamos diariamente en los postes de la sabiduría celestial de Dios,
hasta sentir que la puerta de misericordia y tierno amor se abre para nosotros,
y que la misericordia y el amor fluyen sobre nosotros,
por medio de lo cual obtenemos lo que nuestros corazones desean y buscan.
¡Bendito sea el Señor para siempre!

Aquí, en los brotes de amor y manifestaciones de la misericordia de nuestro Dios,
ciertamente tenemos comunión con el Padre y con el Hijo, y unos con otros,
en el Espíritu Santo de vida.
Y además, testificamos de estas cosas a otros,
para que también puedan entrar en la misma comunión y ser de la
misma fe que fluye y permanece en el poder y la vida eternos.

¡Qué el Señor guíe hasta aquí a todos los espíritus tiernos, suspirantes y anhelantes,
para que se sacien en Su bondad y misericordia,
coman abundantemente de las grosuras de Su casa, beban de los ríos de Su placer,
y no deambulen de arriba para abajo en sus propios pensamientos,
entendimientos y conceptos estériles sobre las Escrituras!

=== La Triple Aparición de Cristo

[.offset]
A saber: Bajo la Ley, en el Cuerpo de Carne, en Su Espíritu y Poder

[.numbered-group]
====

[.numbered]
1+++.+++ _Su aparición bajo la ley._
Cristo apareció varias veces bajo la ley.
Algunas veces lo hizo como un ángel, en otras a semejanza de un hombre (como a Abraham,
Jacob, Moisés, Josué, etc.). También,
las apariciones de Dios a los profetas en visiones a menudo fueron apariciones de Cristo.
Particularmente aquella gloriosa aparición de Dios en la que estaba sentado en el trono,
con Sus faldas llenando el templo y los serafines clamando: "`¡Santo, santo, santo,
Jehová de los ejércitos;
toda la tierra está llena de su gloria!`" (Isaías
6:3). Esta fue una aparición de Cristo a Isaías,
tal como se manifiesta en Juan 12:41,
donde el evangelista (refiriéndose a ese lugar) usa la expresión:
"`Isaías dijo esto cuando vio su gloria, y habló acerca de él.`" Asimismo,
Él era el ángel de la presencia de Dios que iba delante de los judíos en todas sus jornadas;
la salida de Egipto, a través del mar, en el desierto y en el tiempo de los Jueces,
y quien obró todas las liberaciones para ellos, como se indica en Isaías 63:9,
"`En todas sus angustias El estuvo afligido, y el ángel de Su presencia los salvó,`" etc.
(NBLH) De la misma manera con los tres jóvenes en el horno ardiente,
cuando Él apareció en medio de ellos en semejanza del Hijo de Dios.
(Daniel 3:25)

En realidad,
toda la ley era una sombra de Aquel que debía llegar a ser la sustancia de esta,
y ejecutar internamente en el corazón lo que la ley representaba con las figuras externas.
Por tanto, Moisés y todos los profetas,
eran precursores del que es el gran profeta del Israel espiritual de Dios.
Todos los sacerdotes, especialmente los sumos sacerdotes, eran tipos y precursores de Él,
y estaban destinados a llegar a su fin en Aquel que
es Sumo Sacerdote sobre la casa de Dios para siempre.
Los jueces y salvadores eran tipos del que es el gran Salvador y Redentor,
pues ellos no salvaban por medio de sus propias fuerzas,
sino por el Espíritu y poder de Él que venía sobre ellos,
para que el yugo (que había sido hecho y traído sobre ellos por su rebelión contra
el Señor y desobediencia a Su ley) fuera quebrantado debido a la unción.

David, Salomón y los reyes buenos eran tipos de Él. David,
en Su conquista sobre Sus enemigos espirituales; Salomón,
en Su gobierno sobre Israel en paz, tras haber conquistado sus enemigos.

La circuncisión era tipo de Su circuncisión del corazón,
para que Sus hijos (Su simiente santa) pudieran amar al Señor su Dios con todo sus corazones,
y vivir.

La Pascua y la sangre del cordero, eran tipo de Su sangre rociada sobre la consciencia,
la cual protege del golpe y poder del destructor;
así pasa por alto Dios a todos los rociados,
cuando visita por el pecado y la transgresión.

El día de reposo externo era tipo del reposo puro
que Cristo les da a los que creen en Su nombre.
Porque los que verdaderamente creen en Él entran en el reposo,
y descansan de sus propios esfuerzos y obras,
y experimentan la obra de Dios en ellos que produce
"`tanto el querer como el hacer por Su buena voluntad.`"

La ley externa en la letra, escrita en tablas de piedra,
era una sombra de la ley de amor y vida, interna, viva, pura, poderosa y espiritual,
que Dios escribe en los corazones de Sus hijos,
la cual los constriñe a obedecer y les permite hacer todo
lo que Dios requiere de ellos con facilidad y deleite.
Porque en verdad, el yugo de Su ley es fácil y la carga de Sus mandamientos ligera.
Para los que están bajo Su Espíritu y en sujeción a Él, estos no son para nada gravosos.
Pues cuando la mente es recogida y sacada de debajo del espíritu y poder de las tinieblas,
y llevada a Su Espíritu y poder, ¡oh, cuán fácil es creer, amar, obedecer,
etc.! En realidad, ahí no hay nada más que amor, fe, obediencia, vida, justicia,
santidad, poder puro, paz y gozo.
Porque "`las cosas viejas pasaron;
he aquí todas son hechas nuevas,`" para los que están en la nueva creación en Él.

Así también Canaán, la Tierra Santa, representaba la tierra de vida,
o territorio de vida, en el que Dios reúne, alimenta y preserva a todos los vivos,
aquellos que Él recoge de los territorios de muerte y tinieblas.
La abundancia y plenitud de la tierra de Canaán y los dulces ríos en ella,
representaban la abundancia de riquezas y los ríos del deleite de Dios,
donde Sus redimidos beben conforme llegan a vivir, morar, caminar, cenar, en Él y con Él.

Jerusalén, la ciudad santa, era figura de la nueva Jerusalén, la Jerusalén espiritual,
la Jerusalén celestial, la que es madre de todos los nacidos del Espíritu.
La colina sobre la que Jerusalén fue edificada representaba la montaña santa de Dios,
sobre la que está edificada Su ciudad.
Los habitantes de la Jerusalén externa representaban a los habitantes de la nueva e
interna Jerusalén. El templo representaba el cuerpo de Cristo y los cuerpos de los santos,
los cuales son templos en los que el Santo mora en medio de ellos.
El altar en el templo externo representaba el altar en este templo interno,
del que todo judío verdadero, interno y espiritual tiene derecho a participar;
nadie más. El fuego en el templo externo,
los candeleros y las luces que nunca debían ser apagadas,
representaban el fuego santo en el templo espiritual,
el cual viene del cielo y con el que todos los sacrificios espirituales deben ser ofrecidos.
El candelero debe sostener la luz (y los sacerdotes mantener
la lámpara ardiendo) o Dios lo quitará de su lugar.
De igual manera,
las vestiduras santas de los sacerdotes representaban los mantos de justicia,
inocencia y pureza con los que el pueblo de Dios bajo el evangelio
(el cual es un sacerdocio santo para Él) debe vestirse.

El arca representaba eso que contiene la ley del nuevo pacto,
y la urna del maná mostraba el tipo de comida con la que Dios alimentó
y nutrió el alma en el desierto antes de introducirla en la Tierra Santa.
Porque Cristo, en verdad, apareció y estuvo con el pueblo en el desierto,
en una nube durante el día y en una columna de fuego durante la noche,
lo cual representaba la guía del Espíritu de Dios en el día del evangelio.
(Isaías 4:5) Asimismo, Él era la roca que los seguía,
el maná que habían comido y el agua que habían bebido.
Pues ellos comieron y bebieron las cosas celestiales en figura,
y cuando en algún momento sus espíritus eran abiertos,
gustaban la verdadera comida y tenían una experiencia de ella,
en y a través de la figura.
Sí,
no hay duda de que ellos en algunas ocasiones experimentaron y
comieron de la misma comida espiritual que nosotros comemos ahora,
"`y todos bebieron la misma bebida espiritual`" que nosotros bebemos ahora.
(1 Corintios 10:3-4). Porque ellos no sólo estuvieron bajo la nube y pasaron el mar,
sino que todos también fueron bautizados en la nube y el mar,
y tuvieron una experiencia del poder puro del Señor
y de Su brazo extendido desnudado para ellos.

Además, en el arca estaba depositada la vara de Aarón que floreció,
lo cual es evidencia del verdadero sacerdocio y del ministerio eterno.
Este sacerdocio no debe ser despreciado, sino reconocido y honrado como de Dios.
En esta arca también estaban las tablas de la ley,
la cual representaba la verdadera arca, en la que están las tablas de la ley de vida,
las que Dios escribe con el dedo de Su Espíritu y designa
que sean guardadas para siempre en el arca espiritual.

Encima del arca estaba el propiciatorio, con dos querubines de gloria,
uno a cada extremo, y con las alas extendidas por encima cubriendo el propiciatorio.
Dios habitaba o se sentaba entre estos,
se reunía y se comunicaba con Moisés y con los sacerdotes bajo la ley,
cuando ellos llegaban a adorarlo y a consultarlo.
Esto era figura del verdadero propiciatorio bajo el evangelio,
donde los verdaderos sacerdotes (la verdadera circuncisión,
el Israel espiritual de Dios) tienen entrada con confianza al trono de la gracia.
A través del Sumo Sacerdote de su profesión,
pueden alcanzar misericordia y hallar gracia para ser socorridos en tiempo de necesidad.

De la misma manera, todos los sacrificios bajo la ley (la ofrenda por el pecado,
la ofrenda de paz, la ofrenda de acción de gracias, la ofrenda elevada,
la ofrenda mecida, la ofrenda del holocausto, la ofrenda de cereal,
la ofrenda de libación, etc.) representaban a Cristo,
la única verdadera ofrenda que las abarca todas y que el pueblo espiritual
(los sacerdotes del evangelio) debe ofrecer a diario a Dios.
Las especies aromáticas,
el incienso y las fragancias representaban la manera por la que
los sacrificios del evangelio son dulcemente sazonados con gracia,
sal, el Espíritu, las frescas respiraciones de vida, inocencia, mansedumbre, ternura,
celo, fe, amor, etc.,
que producen la más placentera fragancia en la nariz del Señor. ¡Oh,
cuán precioso es leer las figuras de las cosas celestiales con verdadero
entendimiento! ¡Pero leer _a través de_ las figuras (con el ojo de vida,
con el ojo del Espíritu) la sustancia invisible, esto es en verdad, dulce,
precioso y celestial!

[.numbered]
2+++.+++ _Su aparición en el cuerpo de carne._
Cuando el tiempo de las sombras se acercó al final y la plenitud del tiempo llegó,
Aquel que había aparecido en diversos tipos y sombras vino del Padre,
se despojó a Sí mismo, y se vistió a semejanza de hombre al participar de carne y sangre.
Él fue hecho como nosotros en todas las cosas (excepto por el pecado,
porque Él era el Cordero sin mancha),
para que al humillarse a Sí mismo para estar bajo la ley y bajo la maldición,
pudiera redimir a los que están bajo la ley y bajo la maldición,
al cumplir la justicia de la misma e introducirlos a la justicia eterna.

Ahora, en este cuerpo Él consumó la obra que Su Padre le había dado hacer.
Él cumplió toda justicia (la justicia de la letra,
la justicia del Espíritu) para poder llevar a Su
pueblo de la justicia de la ley o de la letra,
a la justicia del Espíritu y poder, es decir, a la justicia de la nueva vida.
Toda Su vida fue un hacer la voluntad del Padre que lo había enviado.
Cuando el Espíritu del Señor estaba sobre Él, impulsándolo a predicar el evangelio,
Él predicaba el evangelio en el Espíritu y poder del Padre,
hacía el bien y sanaba a todos los que estaban oprimidos por el diablo,
según Su Padre lo dirigía y guiaba.
Porque Él no hizo nada por Sí mismo, en Su propia voluntad o para Sí mismo,
sino que lo hizo todo en la voluntad y tiempo del Padre.

Por tanto, Él siempre complació a Su Padre y buscó el honor del que lo había enviado.
Fue obediente hasta la muerte, y muerte de cruz,
al estar dispuesto a beber la copa que Su Padre le dio a beber.
Y así, tras finalizar Su obra,
regresó al lugar de donde había venido y se sentó
a la derecha de la Majestad en las alturas,
tras ser exaltado por encima de todos los principados, potestades y dominios,
tanto de este mundo como del mundo por venir.

[.numbered]
3+++.+++ _Su aparición en el Espíritu._
La tercera aparición de Cristo, fue Su aparición en el Espíritu, es decir,
Su aparición pura, interna y celestial en los corazones de Sus hijos,
a la que las dos apariciones externas le dieron paso.
Él les pidió a Sus discípulos que esperaran,
diciéndoles que Él no los iba a dejar huérfanos, sino que vendría a ellos de nuevo.
Ellos habían experimentado al novio en la carne y Él debía irse.
Esto no podía evitarse, era necesario para ellos que Él se fuera, pero (dice él):
"`Regresaré otra vez.`"
El mismo poder y presencia que estaban entonces con ellos en un cuerpo de carne,
los visitarían en Espíritu, y así permanecerían con ellos para siempre.
Pues Aquel que estaba con ellos entonces, estaría en ellos, y hasta ese momento,
tendrían tristeza y serían como una mujer en labor de parto.
Mientras tanto, el mundo se alegraría, "`pero os volveré a ver,
y se gozará vuestro corazón, y nadie os quitará vuestro gozo.`"
¿Acaso no fue así? ¿No envió Cristo al Espíritu, al Consolador?
¿No vino Él en el Espíritu y poder del Altísimo para estar con ellos siempre, es decir,
hasta el fin del mundo?
¿No les ordenó que no se fueran de Jerusalén,
sino que esperaran Su aparición en Su Espíritu,
y que no siguieran Su obra y mensaje hasta que Él regresara
en el poder y autoridad de Su Padre para ir junto con ellos?
¿No se regocijaron sus corazones cuando Él vino con gozo inefable y lleno de gloria?
¿No tuvieron entonces el gozo y la paz que sobrepasa todo entendimiento del hombre,
el gozo y la paz que nadie podía quitarles?
Sí, en el reino,
Espíritu y poder de nuestro Señor Jesucristo verdaderamente hay un ver ojo a ojo.

No hay duda de que esta administración del Espíritu
y poder del evangelio es extremadamente gloriosa,
y los que entran en ella, entran en la gloria,
dominio y autoridad celestiales del Señor Jesucristo (y así son hechos reyes por Él,
y usan coronas en Su presencia, aunque las echan a Sus pies),
y son cambiados de gloria a gloria.
Estos miran, como en un espejo, la gloria del Señor,
la cual nadie puede ver sino con el ojo que en alguna medida ha sido cambiado y glorificado.

Esta dispensación del evangelio, Espíritu y poder comenzó en los días de los apóstoles,
y en aquel entonces la iglesia era sumamente casta, pura y hermosa, sin mancha o arruga.
Pero después de esto hubo una caída, sobrevino una noche densa y oscura,
y se produjo una apostasía muy grande y universal del Espíritu y poder de los apóstoles.
Muchos se apartaron del poder del Señor,
se adentraron en una mente altiva y no guardaron su posición en la fe,
amor y obediencia de la verdad,
sino que sostuvieron una apariencia de piedad fuera del poder.

====

=== Con Respecto al Monte Sinaí y al Monte Sión

¿No era Sinaí la montaña que podía ser tocada, una montaña terrenal,
de la que vino la administración de la ley externa, o letra, que condujo a esclavitud,
condenación y muerte?
¿No dice el apóstol Pedro, con respecto a la ley tal como es administrada,
que era un yugo demasiado pesado para que ellos o sus padres llevaran?
(Hechos 15:10)

¿No es la Sión del evangelio una montaña espiritual, una montaña celestial,
una montaña que no puede ser tocada por los sentidos humanos,
una montaña de la que viene la ministración del Espíritu, la ministración de libertad,
la ministración de vida, la ministración de la gloria que sobrepasa?
¿No es esta la montaña santa,
sobre la que la ciudad santa (la nueva Jerusalén) está edificada,
donde el Rey de Justicia gobierna en justicia y paz sobre todos Sus súbditos,
donde Él les hace el banquete de manjares suculentos y cenan juntos,
comiendo y bebiendo el pan y el vino del reino, es decir,
el pan vivo y el fruto de la vid viva?

"`Porque no os habéis acercado al monte que se podía palpar, y que ardía en fuego,
a la oscuridad, a las tinieblas y a la tempestad, al sonido de la trompeta,
y a la voz que hablaba... sino que os habéis acercado al monte de Sion,
a la ciudad del Dios vivo, Jerusalén la celestial...`" (Hebreos 12)

Ahora bien,
el monte Sinaí fue la montaña de tierra que la voz y presencia
del Señor conmovieron en la ministración de la ley externa.
Pero hay una tierra interna que debe ser conmovida también, es decir,
la naturaleza que transgredió, la naturaleza sujeta al pecado y bajo maldición,
la tierra que produce cardos y espinos.
Esta es la tierra a la que el arado del Señor debe entrar para quebrantarla y volcarla,
a fin de formar una nueva tierra,
en condiciones de recibir a la Semilla celestial y producir fruto para Dios.
Sí, no sólo debe ser conmovida y removida la tierra,
sino los cielos también. "`Aún una vez, y conmoveré no solamente la tierra,
sino también el cielo,`" lo cual "`indica la remoción de
las cosas movibles...para que queden las inconmovibles.`"

Existe lo que cambia y existe lo que no cambia.
La tierra vieja y los cielos viejos cambian;
los nuevos cielos y la nueva tierra no cambian.
Hay una mente inconstante, un espíritu inconstante, una naturaleza inconstante,
una voluntad inconstante, una sabiduría inconstante,
una razón y entendimiento inconstantes (llevados de aquí
para allá) y un conocimiento de Dios inconstante,
que el hombre aprende, no del Espíritu del Señor, sino según una forma tradicional,
al atrapar con su propia mente y beber conocimiento de esa parte que es vieja y terrenal.
Ahí el hombre enciende su propio fuego, con el que se calienta,
recogiendo para sí paz y gozo, esperanza y confianza, etc.
Pero cuando el Señor aparezca y Su voz sea oída (cuando
Se levante a sacudir terriblemente la tierra,
sí, y los cielos también),
todo eso será sacudido y caerá como higos prematuros
ante el fuerte viento y la terrible tempestad.

Porque el día del Señor, el día de Su aparición pura,
el día del resplandor de Su levantamiento,
estará sobre todo lo que es soberbio y altivo y sobre todo lo que es enaltecido,
y se ha levantado sobre la Semilla pura.
Cada cedro del Líbano y roble de Basán que es erguido o elevado,
cada montaña y colina levantada, cada torre alta y muro fuerte, etc.,
todo sentirá el terror de Su majestad, y únicamente lo que es de la Semilla pura,
lo que está reunido en la Semilla, lo que ha sido cambiado a la naturaleza de la Semilla,
permanecerá. Nada más será capaz de morar con el fuego consumidor y con las llamas eternas.
Por tanto, bien se puede decir: '`¿Quién podrá soportar el día de su venida,
y quién permanecerá cuando Él aparezca?
Porque Él es como fuego purificador y como jabón de lavadores.
Él viene con el aventador en Su mano para aventar la paja.
Él se sentará como refinador y purificador de plata,
para purificar a los hijos de Leví y afinarlos como oro y plata,
para que puedan ofrecer al Señor una ofrenda en justicia...grata
al Señor`' (Malaquías 3:2-4),
la cual no puede ser hecha sino por los que son purificados por Él.

¡Oh, qué felices serán aquellos,
cuya religión y adoración resista la prueba y soporte
el fuego ese día! ¡Bendito sea el Señor para siempre,
quien se ha acercado para juicio, y es un testigo pronto contra todo engaño e injusticia,
pero justificador de aquellos cuyas consciencias
han sido rociadas con la sangre de Jesús!

Ahora bien, así como el Señor quita lo viejo, así trae lo nuevo.
Así como remueve la tierra vieja y los cielos viejos, donde habita la injusticia,
así forma y hace surgir los cielos nuevos y la tierra nueva, donde habita la justicia.
Aquí el reino es conocido y recibido, el cual no puede ser conmovido.
Aquí está el monte Sión, el cual nunca será sacudido, y la Jerusalén,
cuyas estacas o cuerdas nunca serán arrancadas o rotas.
Aquí está la ciudad que tiene fundamentos eternos, cuyo constructor y hacedor es Dios.
Benditos los que vienen y moran aquí,
los que no se han acercado a la montaña que puede ser tocada, conmovida y removida,
sino a la montaña santa de Dios, sobre la que todos los edificios de vida son levantados,
y sobre la que ellos permanecen firmes para siempre.
Porque el Señor de los Ejércitos, quien ha creado los nuevos cielos y la nueva tierra,
ha creado a Jerusalén alegría y a su pueblo gozo,
y ellos se alegrarán y regocijarán en Él por los siglos de los siglos.
Amén.

=== El Templo y los Sacrificios Bajo el Evangelio

El templo de Dios bajo el evangelio es la luz de Su Hijo, el Espíritu de Su Hijo,
las almas de los que son renovados y edificados como
una habitación para Él en el Espíritu de Su Hijo,
y los cuerpos donde moran las mentes y espíritus renovados.
Dios es luz y el habita en luz.
Dios es Espíritu y Su edificio es santo y espiritual,
porque Él no habita en nada que sea tinieblas, corrupto o inmundo.

Ahora, lo que es sacrificado u ofrecido a Dios debe ser limpio y puro.
Ningún pensamiento inmundo, ningún deseo inmundo, nada que sea terrenal,
carnal o egoísta debe ser ofrecido a Dios,
sino las respiraciones puras de Su propio Espíritu.
Porque todo lo que es de Él y viene de Él, es aceptado por Él;
pero lo que el hombre inventa, forma y ofrece por su propia cuenta o de sí mismo,
aunque sea muy glorioso, o altamente estimado a sus ojos,
todavía es abominación delante de los ojos del Señor.

En consecuencia,
todos los sacrificios de los gentiles (o de la naturaleza pagana) son rechazados,
y todos los sacrificios de los judíos externos (o de la mente y naturaleza religiosas,
sin la verdadera vida) son rechazados también. "`¿Con qué
me presentaré ante Jehová,`" dijo el profeta de antaño,
"`y adoraré al Dios Altísimo?
¿Me presentaré ante él con holocaustos,
con becerros de un año? ¿Se agradará Jehová de millares de carneros,
o de diez mil arroyos de aceite?
¿Daré mi primogénito por mi rebelión, el fruto de mis entrañas por el pecado de mi alma?`"
(Miqueas 6:6-7) ¿Cuál es la respuesta de Dios?
No, este no es el camino para llegar al perdón de pecado o a la aceptación de Dios,
sino ir a Eso que enseña lo que es bueno y declara lo que el Señor pide, lo cual es:
"`¡Oh, hombre...solamente hacer juicio, y amar misericordia,
y humillarte para andar con tu Dios!`" (Miqueas 6:8,
RV1602P). Presentarse en las enseñanzas del Espíritu de Dios y adorar ahí,
y allí experimentará el perdón de pecados y la aceptación del Señor.
(Isaías 1:16-18) Porque ofrecer los sacrificios de antaño (determinados
bajo la ley) no era lo que hacía la cosa;
ni bajo el evangelio, que los hombres reclamen el sacrificio de Cristo,
sino que se presenten ante el Espíritu que enseña santidad,
se sujeten a ese Espíritu y ofrezcan en dicho Espíritu (al Padre) lo que procede
de Él. Porque el edificio de Dios en el Espíritu es el único templo verdadero,
y los sacrificios u ofrendas en el Espíritu, son las únicas ofrendas del nuevo pacto.

Aquí todo gemido o suspiro hacia el Señor tras lo que es puro,
toda súplica en el Espíritu,
todo reconocimiento de la bondad del Señor en el verdadero y puro sentido,
es olor dulce para la nariz del Señor. En realidad, la hospitalidad, socorrer al pobre,
o hacer cualquier cosa buena a partir de la raíz buena y santa,
es sacrificio aceptable para el Señor. Lean las siguientes escrituras,
y si el Señor les abre los ojos,
pueden llegar a ver tanto lo que es el templo como lo que son los sacrificios.
En cuanto al templo, vean 1 Corintios 3:16; 2 Corintios 6:16; Isaías 5:7,15;
Efesios 2:21-22; Hebreos 3:6; Apocalipsis 21:22; Juan 4:23; Salmo 90:1. Luego,
para los sacrificios, Salmo 1:14-15; 51:16-17; 141:2; Malaquías 1:11; Hebreos 10:8-9;
Romanos 12:1; 1 Corintios 6:19-20; 1 Pedro 2:5; Hebreos 13:15; Filipenses 4:18.

=== Con Respecto a la Elección de Dios

Bien, con respecto a la elección de Dios, observen:
que es en Cristo y no fuera de Él. Pues la intención de Dios fue honrar a Su Hijo,
tal como Su Hijo lo honraba a Él. Y este fue el honor que Dios le dio:
Le dio el honor de ser Su salvación hasta los confines de la tierra,
para que todo aquel que cree en Él no se pierda, sino que tenga vida eterna.
Le dio el honor de ser el camino por el que toda la humanidad llega al Padre,
a través de la fe en Él. Porque así como en Adán todos murieron,
así también en Cristo todos pueden ser vivificados.
Así como en Adán todos los hombres fueron encerrados en la muerte y condenación,
así también el Don gratuito puede venir sobre todos,
y el camino de la vida y redención ser abierto para todos en Él.

Consideren la figura, la serpiente de bronce,
la cual no fue levantada sólo para que un cierto número fuera sanado,
y nadie más. Por el contrario,
fue levantada para que todos los que estaban heridos
y habían sido mordidos por las serpientes,
la miraran y fueran sanados.

Así también fue levantado Cristo,
para que todo pecador (mordido por el pecado y por la serpiente),
pueda mirar al médico de las almas y recibir virtud y sanidad de Él,
conforme a la preciosa escritura que dice: "`Mirad a mí, y sed salvos,
todos los términos de la tierra.`"
Y, "`Si alguno tiene sed, venga a mí; y el que quiera,
venga y beba del agua de la vida gratuitamente.`"
Sí, Dios está listo a encender,
mediante Su Espíritu Santo y poder vivificador (que están cerca de los hombres),
la verdadera sed y la buena disposición en ellos.

Pero para aclarar esto aún más: Hay una predestinación, elección, llamado,
justificación y glorificación. Hay una predestinación para la santidad,
una elección en eso que es santo, un llamado a salir de las tinieblas a la luz,
una justificación y glorificación en la luz,
a través de la renovación y santificación del Espíritu.
Todo esto lo ordena y maneja Dios según Su buena voluntad,
y de acuerdo con lo que se ha propuesto en Sí mismo.
Pero Él no es el que decreta, ni el autor del pecado o de la rebelión contra Él,
lo cual es la causa de la condenación de la criatura.

Ahora, todas las cosas están presentes delante de Dios antes de que sean.
Dios vio de antemano la caída de Adán antes de que
sucediera (aunque esto no lo hizo el autor de esta).
Él vio de antemano cómo debían obrar Su poder,
amor y misericordia hacia los hombres y por los hombres, en y a través de Cristo.
Supo hasta donde se extendería Su amor hacia los hombres,
y cuánto se resistirían los hombres y lucharían contra Su santo y buen Espíritu.
Él determinó cuánto tiempo debía luchar Su Espíritu con las naciones y personas,
porque en realidad, con algunas Él esperaría por mucho tiempo para ser misericordioso,
y con otras sería más rápido y más severo, conforme a las provocaciones de ellas.

De hecho, el amor, la misericordia, el poder y el buen Espíritu le pertenecen a Él,
y Él puede mostrar las operaciones de estos hacia los hombres según Su complacencia.
¿Y quién puede decirle a Él:
'`Qué haces?`' ¿Acaso no puede Él hacer lo que le agrada con lo Suyo?
Debido a que Él puede mostrar misericordia tanto tiempo como quiera,
y endurecer tan pronto como lo desee (según ve razón),
¿puede no ser dicho con toda veracidad: "`De manera que de quien quiere,
tiene misericordia, y al que quiere endurecer,
endurece`"? Pero Él no endurece sin antes haberles dado un día de misericordia,
de haberlos visitado con Su misericordia, siguiéndolos y soportándolos,
y buscándolos mediante las riquezas de Su bondad y longanimidad,
para conducirlos al arrepentimiento, a fin de que puedan escapar de Su ira.
De hecho, sugerir que Dios endurece a alguien por un mero deseo en Él,
porque quiere destruir a la mayor parte de los hombres, no tiene fundamento,
pues las Escrituras no declaran esto, sino que testifican abundantemente lo contrario.
Porque, ¿cuánto tiempo luchó Dios con el mundo antiguo (en los días de Noé), es decir,
para salvar a aquellos que después destruyó? Y,
¿cuánto tiempo lucho con el pueblo de los judíos (sí,
y con otras naciones también)? "`Vivo yo,
dice el Señor,`" (y Él habla desde Su corazón) "`que no quiero la muerte del impío,
sino que se torne el impío de su camino, y que viva.
Yo no soy el destructor, yo soy el Salvador, y mi deleite no es destruir, sino salvar.`"
"`¡Oh, Israel, tu destrucción es por ti mismo, pero en mí está tu ayuda!`"
Ciertamente, la sangre de ningún hombre estará a la puerta de Dios,
sino en la suya propia.

Por tanto, así como Dios ha preparado un Salvador, así no hay falta de amor,
misericordia o poder de Su parte, para atraer a los hombres al Salvador.
Pero esta es la condenación:
Que los hombres se endurecen contra las persuasiones de
Su Espíritu y contra la operación de Su luz y poder santos,
cuando aparecen y están dispuestos a obrar en y sobre sus corazones.
Las Escrituras no declaran que la condenación del
hombre se deba a que la luz no brilla en su corazón,
sino a que la luz brilla y los hombres aman más las tinieblas que la luz.
Porque, de hecho, una medida de luz aparece y alumbra a todos los hombres,
testificando contra las tinieblas y alejando de ellas, y al final,
será claramente manifiesto que el Espíritu de Dios en verdad luchó con todos,
y que los que Lo rechazaron no se volvieron de sus tinieblas
a la luz del Señor. Toda boca se detendrá delante de Él,
porque todos los hombres que perecen son justamente condenados,
habiendo rechazado y descuidado una salvación tan grande.
Ya que la luz del sol del día eterno de Dios y el sonido de Su Espíritu,
verdaderamente visitan al hombre en tinieblas, se extienden por toda la tierra,
y Su voz alcanza hasta los confines del mundo.

[.discourse-part]
Pregunta: ¿Cómo puede un hombre asegurar su llamado y elección?

[.discourse-part]
Respuesta: Asegurando a Cristo en él, Aquel en donde están el llamado y la elección;
porque el Señor escoge sólo en Él, y rechaza o reprueba sólo fuera de Él.

[.discourse-part]
Pregunta: ¿Cómo puedo asegurar a Cristo para mí?

[.discourse-part]
Respuesta: Recibiéndolo, rindiéndote a Él, separándote de todo por Él,
esperando en Él en el camino y la senda de vida,
hasta que sientas quebrantado en ti ese poder que te separaba de Él. Porque entonces,
¿qué peligro existe cuando el alma ha llegado a ser naturalmente del Señor,
y está arraigada en Su amor y circuncidada en el
corazón para amar al Señor por encima de todo,
es decir, con todo el corazón y con toda el alma?
En realidad, el amor del Señor no puede evitar fluir con gran fuerza hacia esa alma,
y ¿qué puede interponerse?
Pero mientras aún exista algo que no se haya rendido,
mientras todavía permanezca algo en donde el enemigo tenga parte y por donde pueda entrar,
el estado de esa alma no estará plenamente asegurado.
Ya que puede producirse un retroceso de la vida salvadora
hacia donde está la destrucción del alma,
y cualquiera que llegue ahí encontrará la perdición y destrucción,
en la medida que viaje en esa dirección.

En el camino de muerte hay muerte; en el camino de vida hay vida.
Dios no hace acepción de personas,
pero hace distinción de Su Semilla y de Su pacto eterno de vida,
el cual permanece firme en Su Semilla para siempre.
Toda alma que siente las persuasiones del Padre, y viene a Su Hijo en busca de vida,
y permanece en Él, encuentra la vida.
Pero aquella alma que no llega a esto,
sino que se aparta del Señor a través de un corazón incrédulo, encuentra la muerte.
Por tanto, el camino de Dios es eterno e inmutable; Él no puede negarse a Sí mismo.
El que cree en el Hijo tiene vida;
el que no cree está en la muerte y condenación que pertenecen al estado incrédulo.

Ahora,
¿deseas experimentar tu elección? Entonces espera conocer y distinguir en ti mismo,
entre Jacob y Esaú, Isaac e Ismael.
Pues estas fueron figuras y alegorías externas de algo interno.
Siente a Esaú, el profano; a Ismael, el burlador de la sabiduría,
camino y Semilla de Dios.
Debes sentirlos,
debes sentir a los que son expulsados por Dios y sentirlos
expulsados de ti también. Y luego debes sentir a Isaac,
la semilla de la promesa; debes sentir a Jacob, el nacimiento de vida puro,
levantado en ti,
viviendo en ti y tú en Él. Y entonces sentirás la elección y estarás
en la elección. En la medida que Su semilla sea segura en ti,
y tu unión con ella, y tu posición y permanencia en ella sean seguros,
así es segura tu elección.

La elección es un misterio profundo,
y nadie puede leer las Escrituras acerca de este (el cual, de hecho,
es difícil de entender y fácil de torcer),
excepto aquellos que pueden leer en la Semilla, vida,
poder y revelaciones del Espíritu del Señor. Estos leen las cosas como son,
pero los otros hombres leen las cosas sólo como las comprenden y conciben ser.
Pues el conocimiento que Dios le ha dado a Su pueblo,
está por encima de todo conocimiento que pueda ser escudriñado,
reunido o comprendido por todos los hombres sobre la tierra.

=== Una Breve Explicación del Misterio de los Seis Días de Trabajo y del Séptimo Día, el Día de Reposo

Para que lo contemplen aquellos cuyos ojos han sido abiertos por la Unción pura,
y no están tan sumergidos en sus conceptos y razonamientos
acerca del entendimiento de la letra,
como lo están la mayoría de los profesantes de esta era.

[quote.scripture, , Mateo 11:28-30]
____
Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.
Llevad mi yugo sobre vosotros, y aprended de mí, que soy manso y humilde de corazón;
y hallaréis descanso para vuestras almas; porque mi yugo es fácil,
y ligera mi carga.
____

Al que escucha el alegre sonido del poder vivo llamándolo
por medio de la voz de Su luz eterna,
a salir de las tinieblas, de la muerte, de la miseria, de los dominios,
territorios y profunda esclavitud de Satanás, para traerlo a Sí mismo,
y que viene a Él en la virtud y poder de esa vida que llama,
se le da a probar el descanso eterno y la promesa de entrar en él.

Pero la entrada a la plenitud no es inmediata, hay un largo viaje por hacer.
Hay que salir de Egipto, la tierra de tinieblas; de Sodoma, la tierra de inmundicia;
de Babilonia, donde todas las vasijas y cosas santas de Dios han sido profanadas;
hay que atravesar el desierto y hay que entrar en Canaán. Muchas batallas
deben ser libradas contra los enemigos que se interponen en el camino,
y también contra los enemigos que poseen la tierra santa.
Sí,
muchas dificultades deben padecerse al seguir al Capitán que guía
a Su Israel con una columna de nube durante el día,
y con una columna de fuego durante la noche.
Tienen que realizarse la circuncisión y el bautismo en la nube y en el mar,
y tiene que suceder la caída en el desierto de todos los
cadáveres que no van a entrar ni a ver la buena tierra,
antes de que la entrada sea ministrada a la Semilla,
y a los que pasan a través del agua y del fuego con Ella.
En términos simples, tiene que tomarse el yugo y aprender de Cristo bajo el yugo,
hasta que el espíritu orgulloso, rígido, terco, sabio, caprichoso y egoísta,
y el corazón duro de piedra sean desgastados y consumidos por la cruz,
y no quede nada sino lo que se hace uno con la Semilla,
y así es apto para casarse con Ella y para entrar con Ella al reino eterno.

Ahora, en este llevar el yugo, cargar la cruz,
seguir a Cristo en el desierto a través de las correcciones del Padre,
a través de las bofetadas y tentaciones del enemigo,
en medio de todas las debilidades y fragilidades de la carne,
en este avanzar cuando Él manda avanzar, en este permanecer quieto donde Él se detiene,
en este luchar cuando Él dispone la batalla,
soportar la derrota cuando Él permite que prevalezca el enemigo,
y esperar "`en esperanza contra esperanza`" que llegará
Su alivio y victoria en el debido tiempo,
en todo esto, está el esfuerzo, está el dolor, como el dolor de parto,
está la obra bajo el yugo de la vida,
con la medida de gracia y poder recibida de la vida.

De modo que, primero hay una visitación de la Aurora desde lo alto;
a partir de esa visitación entra la luz en el corazón,
y al estar de acuerdo con esa luz se recibe la gracia.
Ahora con esta gracia recibida hay una obra que hacer para Dios.
El talento de Dios debe ser incrementado durante los seis días
por los que quieran descansar con Él en el séptimo día,
y deseen cesar de sus propias obras en la consumación de la fe, la vida y el poder,
viniendo a ser el poder vivo el que lo realiza todo en ellos.
Aquel que no incremente el talento, que no siga adelante en la luz pura,
sino que se sienta al lado del camino,
o es engañado con una imagen de lo que una vez fue verdadero en él,
nunca llegará a la tierra de reposo (aunque puede que llegue a lo que
él llama "`reposo`"). Y cuando el Testigo eterno se despierte en él,
encontrará la falta del reposo y lamentará amargamente su grave error.

Ahora en esta ardua y dolorosa labor (con ardua quiero decir, sí,
muy ardua para la parte no renovada,
aunque fácil y natural para la parte renovada y nacida de Dios),
bajo las leyes y mandamientos espirituales internos de la vida,
al Señor le complace dar un día de refrigerio de vez en cuando,
haciendo que Su vida brote tan poderosamente que se puede sentir que es
ella la que es y hace todo en el corazón. Este es un día de reposo,
un día en que el alma reposa en los poderosos movimientos y operaciones de la vida,
y no encuentra ninguna tensión por problemas, dificultades o afán en ella misma,
sino que se queda quieta en el poder,
está tranquila en la vida y en la virtud eterna que vive, se mueve y es todo en ella.
Aquí no siente ningún dolor, ningún conflicto, ninguna angustia por ningún mandamiento,
todo es fácil para ella, todo es natural, todo es absolutamente placentero,
y la vida (para la cual todas sus propias leyes, estatutos, ordenanzas, juicios,
formas y caminos son fáciles) hace todo lo que se requiere,
incluso tan rápido como se requiera.
Aquí no solo es conocido y experimentado un reposo de días,
sino también un reposo de semanas, sí,
y algunas veces un reposo de años (además del jubileo eterno,
o el año de perfecta redención),
por aquellos que han esperado en el Señor en sencillez de corazón,
bajo el yugo de Su Espíritu, para la destrucción de la naturaleza áspera y adversa,
y para el surgimiento del corazón manso y humilde.

Sin embargo, aquí es sumamente fácil salir corriendo y hacerse a un lado;
es fácil huir de debajo del yugo para evitar la amargura
y los sufrimientos de la parte terrenal.
Sí, es muy fácil salirse del camino en el día de reposo, y por tanto,
perder la verdad en el gozo y regocijo propios de dicho día,
incluso para el que tenga un buen motivo para regocijarse.

¡Oh! ¿Quién puede evitar pensar que la amargura de la muerte ha pasado,
cuando todos los enemigos han desaparecido y sólo
quedan el Señor y el alma abrazándose uno al otro?
¿Quién puede evitar sentirse reacio a regresar de nuevo a su trabajo,
y al resto de su ardua labor?
Sin embargo,
es mucho mejor regresar al trabajo en la viña y sufrir de nuevo con la Semilla,
que guardar el reposo como un concepto, y perder la vida,
la presencia y virtud pura de la Semilla,
cuando Ella regresa y llama de nuevo al trabajo.
¡Oh,
cuántos han perecido aquí! ¡Cuántos se han divorciado del que los condujo al reposo
por no estar dispuestos a regresar con Él y cumplir lo que falta de Sus sufrimientos,
y así han guardado un reposo falso, muerto e imaginario,
después de que el verdadero había terminado!

Para estos no hay otro camino más que esperar sentir el soplo vivo,
la virtud vivificante, la Aurora de lo alto,
la que por causa del brillo de su levantamiento,
puede poner al descubierto este descanso falso, este descanso muerto,
este descanso imaginario, esa tranquilidad en la parte terrenal,
carnal e intelectual que ellos han defendido por medio de cosas
que han reunido con anterioridad a partir de las Escrituras,
o a partir de sus propias experiencias (quizás, en una ocasión, experiencias vivas),
pero que ahora sostienen en la parte muerta,
fuera de la experiencia y posesión de la vida.
Pero, la verdad de su estado, no la pueden ver,
hasta que la luz de la que se han extraviado se levante y les manifieste
su condición. Pero cuando la luz se incremente y les revele dicho estado,
encontrarán que el camino de regreso y la senda de redención,
son mucho más difíciles para ellos de lo que fueron al principio.
Sin embargo,
es mejor separarse de la tranquilidad de la carne
y sufrir las punzadas de un nuevo nacimiento,
que perder la herencia en la buena tierra.

Hay tres pasos o tres grados del estado bendito: Primero,
hay un engendramiento de deseos, sed y respiraciones anhelantes en pos de la vida.
Segundo, hay un esfuerzo en el servicio bajo el yugo,
por medio de la virtud que brota de la vida.
Tercero, hay un descanso o el sentarse a gusto en la vida.

Los deseos en pos de la vida son encendidos por la agitación de la vida en el alma.
Aquel en quién los deseos son encendidos y siente la virtud eterna,
no puede dejar de correr la carrera.
Y aquel a quien el Espíritu del Señor encuentra fiel corriendo la carrera,
es de agrado para Él darle una muestra del reposo de vez en cuando.
Por tanto, en la agitación del manantial,
el alma no puede dejar de moverse hacia su centro,
y conforme entra y se fija en dicho centro, participa del reposo.

Ahora bien, en conocer la guía del Espíritu hacia adelante y hacia atrás en los deseos,
cuando a Él le place; en la labor y servicio de la vida, cuando a Él le place;
en el dulce y perfecto reposo en la vida, cuando a Él le place,
está el progreso seguro y dulce del espíritu renovado.
El hombre que ha nacido del Espíritu debe esperar los movimientos,
respiraciones y destellos del Espíritu en él, y cuando el Sol se levante,
debe salir a su labor en la luz de este; cuando el Sol se retire en la noche,
debe descansar y velar; cuando llegue su séptimo día, el día de reposo,
debe recibirlo y disfrutarlo en el Espíritu. Luego,
debe estar dispuesto a comenzar su semana de nuevo,
hasta que toda su carrera y el recorrido completo de su peregrinación haya terminado.

Sin embargo, si fuera posible para el hombre, después de haber venido a Cristo,
habitar perfectamente con Él, dejar sus deseos, mantenerse dentro de la fe,
llevar naturalmente el yugo,
inclinarse continuamente en espíritu ante el Padre de los espíritus,
habría un continuo día de reposo guardado en el viaje, incluso antes del grande,
pleno y perfecto día de reposo al final.
La dificultad y la intranquilidad de la labor se debe a
la parte del hombre que es contraria a la vida,
pero cuando esta sea desgastada, ya no habrá más afán,
sino que el yugo se convertirá en el reposo,
y todos los movimientos y operaciones de la vida fluirán naturalmente en dicho reposo.
Y esta es "`la paciencia y fe de los santos,`" a saber, esperar bajo el yugo,
bajo la cruz diaria, que esa parte sea llevada y mantenida en sujeción,
hasta que todos los lazos de cautiverio sean quebrantados por la vida,
y el velo de la carne sea rasgado de arriba hacia abajo (la presencia
del cual es lo que frena la corriente libre de la vida).
Entonces el alma entrará en el lugar santísimo,
obteniendo así la completa posesión de la herencia eterna y de la redención eterna.
Aquí ya no experimentará tristeza, lágrimas, ataduras, enfermedad, muerte,
cautiverio (ni siquiera tendrá que luchar contra estas cosas, ni viajar fuera de ellas),
sino el gozo de la plenitud y llenura de la vida,
cosechando para siempre todos los frutos placenteros
de la vida eterna en la tierra de la abundancia.
