== Capítulo 10 La Ministración del Espíritu y Poder

Hay "`cámaras de imágenes pintadas`" en muchas personas, y fortalezas, razonamientos,
imaginaciones y pensamientos altivos,
exaltados por encima de la Semilla pura y medida de vida en sus corazones.
Pues todo verdadero cristiano, todo verdadero creyente,
ha recibido algo del Espíritu de Cristo,
alguna porción de gracia y verdad proveniente de la plenitud de Cristo,
la cual es como levadura y como sal,
para leudar el corazón y sazonar la mente y el espíritu.
Pero no todos conocen esto claramente,
ni todos los que lo conocen han llegado a sujetarse de manera que los guíe,
comande y gobierne en ellos.
Más bien, hay algo más que los mantiene bajo cautiverio.
El enemigo del alma ejerce el gobierno y dominio en los espíritus de muchos hombres,
y a pesar de que profesan la piedad,
en ellos la Semilla todavía es mantenida bajo sujeción,
de modo que sus almas permanecen alejadas de la redención
y liberación de las que podrían participar,
en y con la Semilla.
Así pues,
muchos que hablan del evangelio (y pronuncian grandes
palabras de Cristo y de la redención en Él),
no experimentan la '`inmortalidad que ha sido sacada
a la luz,`' ni lo muerto levantado por Él,
para vivir para Dios y alabanza de Su nombre.

Ahora, en estas "`cámaras de imágenes pintadas,`" en estas fortalezas,
hay muchas pinturas agradables,
muchas imágenes de cosas celestiales que los hombres forman en sus mentes,
a partir de sus propias imaginaciones y conceptos sobre las Escrituras.
Porque los hombres que leen las Escrituras fuera de la vida,
Espíritu y poder que las dieron (es decir, que las leen con lo que es natural),
no llegan al conocimiento vivo, verdadero, puro y celestial.
Estos únicamente obtienen un conocimiento natural, según el cual creen y adoran,
y por eso se inclinan delante de las comprensiones e imaginaciones de sus propias mentes.
Así, uno cree y adora de una forma, y otro cree y adora de otra forma.
Aquí los hombres en verdad adoran lo que no conocen, pero los que son verdaderos judíos,
conocen lo que adoran.
Porque la salvación es ciertamente de los verdaderos judíos,
de los que no adoran en esta montaña, ni en la otra montaña,
sino únicamente en Espíritu y en verdad, es decir,
en la vida y poder de nuestro Señor Jesucristo.

Así sucede con todos los hombres en sus diversas profesiones de religión
en las tinieblas (en la apostasía de la verdadera vida y poder),
en las cuales todos han errado y vagado, pero pocos han regresado.
¡Oh, pocos han encontrado la perla de gran precio que ha estado perdida por tanto tiempo!
En cambio, se han contentado con un relato y un conocimiento literal acerca de la perla,
sin conocer y poseer la perla misma.
Sí,
este era el estado de tinieblas en el que el Señor nos encontró cuando vino a visitarnos.
Pues el hombre fuerte tenía sus fortalezas en nosotros,
por medio de las cuales nos mantenía cautivos con ligaduras de muerte,
y libres de la vida y poder justos que ansiábamos.
Pero cuando el Hombre más fuerte vino, golpeó su fuerza, y asaltó y tomó sus fortalezas.
Él quebrantó todo su razonamiento, conocimiento,
sabiduría y sutileza en los que confiaba,
hizo despojo de sus bienes y liberó al cautivo de debajo de sus manos.

Porque en verdad, cuando el poderoso día del Señor vino sobre nosotros,
y Su luz pura y celestial alumbró en nuestros corazones,
Dios escudriñó a Jerusalén con linterna,
sacando a la luz las cosas más ocultas de la naturaleza de Esaú en el interior.
Entonces se encontró que todo el conocimiento y la sabiduría,
que todo el entendimiento y las experiencias,
que todo lo que se había atesorado en nosotros fuera de la vida pura,
fuera de la verdad (la que vive y permanece), estaba muerto.
Esto fue condenado a muerte en nosotros, y por tanto, arrojado,
así como los tesoros de Egipto y Babilonia,
y fue lanzado a los murciélagos y topos (que suben
y bajan sigilosamente en la naturaleza terrenal,
o se remontan en lo alto,
en los sueños oscuros e imaginaciones de la noche
de apostasía). Ya que cuando la verdadera luz alumbra,
pone de manifiesto qué es el día y qué es la noche, y también,
las cosas que son del día y las cosas que son de la noche.

Ahora bien,
cuando el Señor se nos apareció así e hizo que la luz de Su Hijo resplandeciera en nosotros,
muchos salimos rápidamente de Egipto al volver nuestras espaldas a las tinieblas.
Nos fuimos voluntariamente al desierto, para viajar junto con el Señor,
y ser ejercitados y preparados ahí para la buena tierra, la tierra de los redimidos,
la tierra de los vivos,
la tierra que fluye leche y miel (lo cual es comida pura y celestial).
Los que llegaron a dicha tierra encontraron la vid excelente,
la que produce las uvas celestiales de las que sale el vino del reino.
También encontraron el verdadero olivo, el que produce aceite dulce,
y casas que ellos no construyeron, en las que hay muchos lugares de reposo y gloria pura.

Pero hubo otros que no estuvieron dispuestos a salir de Egipto,
o de abandonar los ídolos y formas de adoración de Egipto y Babilonia,
a quienes el enemigo mantuvo cautivos por mucho tiempo en sus pensamientos,
razonamientos y en las disputas de sus mentes.
Estos sufrieron mucho,
y sintieron muchos de los golpes y pavorosos juicios del Señor
derramados sobre ese espíritu en ellos que los mantenía cautivos,
y sobre ellos mismos por escuchar y unirse a los
razonamientos y sugerencias sutiles de dicho espíritu.
Pues el enemigo usa toda su fuerza y sutileza al máximo,
para mantener a sus cautivos en sujeción a él y bajo su poder,
tanto tiempo como le sea posible.
Él mantiene cada agarre, fortalece cada razonamiento,
pensamiento e imaginación en la mente,
contra el llamado de Dios y contra la aparición de
Su Espíritu en el corazón. "`¡No se vayan todavía!`",
(dice el enemigo).
"`¡El camino delante de ustedes todavía no está claro,
la luz no está suficientemente clara! ¡Sus objeciones y consideraciones todavía no están
plenamente respondidas! ¡Deben poner a prueba todas las cosas! ¡Todavía queda esta consideración,
aquella, o aquella otra, que no han intentado todavía,
ni considerado plena y satisfactoriamente en sus propios corazones!`"
De esta manera,
muchas invitaciones puras del Padre (en las que había suficiente
luz para que el alma las siguiera) se perdieron,
y el alma perdió por este medio la mano que fue extendida
(en el amor tierno del Señor) para ayudarla y salvarla.

Pregunta: Sin embargo, algunos pueden preguntar:
¿Qué han aprendido ustedes del Señor más que nosotros, o más de lo que sabían antes,
cuando caminaban entre nosotros y practicaban las ordenanzas que nosotros practicamos?
¿Acaso no tenemos nosotros buenas instrucciones de las Escrituras?

Respuesta: Mencionaré tres cosas (además de muchas otras que podrían ser mencionadas),
que el Señor nos ha enseñado desde que Su Espíritu
y poder nos ha aparecido y sacado de las tinieblas.
Son las siguientes: Él nos ha enseñado a creer, Él nos ha enseñado a obedecer,
Él nos ha enseñado a orarle en el nombre de Su Hijo.

Objeción: ¿Ustedes no aprendieron estas cosas antes?

Respuesta: No, no como el Señor nos las ha enseñado ahora.
Es cierto que había algo de la verdadera fe procedente de la verdadera Semilla en nosotros,
algo de la verdadera obediencia y algunas respiraciones puras al Padre,
en los días de nuestra profesión anterior, pero no conocíamos la Raíz de donde venían,
como para volvernos a ella y permanecer en ella.
En consecuencia,
los deseos santos y el verdadero discernimiento en nosotros a menudo fueron apresados,
y quedamos en necesidad y esterilidad en tierra extranjera, sin poder disfrutar,
poseer o retener lo que nuestro Dios y Padre nos había dado gratuitamente en Cristo.
Pues todavía había una sabiduría, una comprensión, una naturaleza,
mente y conocimiento carnales (que en aquellos días nosotros pensábamos que eran espirituales,
como otros lo hacen ahora), que se levantaban sobre Ella.
Pero cuando el Señor nos volvió a la luz de Su Espíritu,
y mediante la luz y poder de Su Espíritu rompió las
ligaduras y cadenas de las tinieblas en nosotros,
pudimos creer en Aquel que aparecía. Y en la fuerza y virtud recibidas de Él,
pudimos obedecerlo,
presentando nuestros miembros como instrumentos de justicia para hacer Su voluntad.
Y en el Espíritu del Hijo (el que recibimos entonces en la fe, es decir,
el Espíritu celestial, el más excelente Espíritu) pudimos orar al Padre; primero,
suspirando y gimiendo ante Él, y después,
derramando nuestras peticiones y súplicas a Él con acción de gracias.

Pregunta: ¿Cómo les enseñó el Señor a creer?
O, ¿qué les enseñó a creer ahora más que antes?

Respuesta: Está escrito en los profetas:
"`Todos tus hijos serán enseñados del Señor.`" En el nuevo pacto está prometido:
"`Todos me conocerán, desde el menor de ellos hasta el mayor.`"

Ahora bien, conforme fuimos introducidos por el Señor en la luz de este pacto,
fuimos enseñados a conocerlo,
a creer en Él y a creer en Su Hijo (en la medida que Él se daba a conocer),
a fin de que experimentáramos al Padre revelando a Su Hijo, y al Hijo revelando al Padre.
Nuestros corazones fueron persuadidos a creer en ambos,
ya que ambos fueron revelados en nosotros y a nosotros,
y dicha revelación se produjo en el Espíritu de ambos, en la luz de ambos,
en la vida de ambos, en el poder de ambos, cuyo Espíritu, luz, vida y poder es uno.
Aquel que en verdad conoce al Hijo, conoce al Padre también,
y el que en verdad conoce al Padre, conoce al Hijo también.

Por tanto, para nosotros sólo hay un Dios y Padre, "`del cual son todas las cosas,
y nosotros en él,`" "`un Señor Jesucristo, por el cual son todas las cosas,
y nosotros por él,`" un solo Espíritu,
y un solo poder de vida que hemos recibido del Hijo y del Padre,
a través del cual creemos y echamos mano del poder y fuerza puros y eternos del Altísimo,
que redime y salva el alma.

Pregunta: ¿Cómo les enseñó el Señor a obedecer?

Respuesta: En realidad,
el Señor nos ha enseñado obediencia de una forma como nunca antes habíamos aprendido:
Puso Sus leyes en nuestras mentes, las escribió en nuestros corazones,
y nos dio Su buen Espíritu para que habite en nosotros,
para que nos vivifique y nos ayude a obedecer y a cumplir Sus leyes santas.
Ha escrito internamente en nuestros corazones,
y nos ha enseñado a observar y a obedecer aquellos dos mandamientos
(en los que se resume toda la ley y los profetas),
a saber: "`Amarás al Señor tu Dios con todo tu corazón, y a tu prójimo como a ti mismo.`"
De modo que ahora no tenemos otro Dios sino Al que nos sacó del
Egipto espiritual por medio de Su brazo extendido y poder puro,
revelados internamente en nosotros, como fueron revelados externamente para los judíos,
a quienes Dios redimió del Egipto externo.

Pregunta: ¿Cómo los enseñó Dios a orar?
De seguro ustedes nunca aprendieron el Padrenuestro, pues no practican eso entre ustedes.

Respuesta: Cuando Dios nos introdujo a una condición verdaderamente consciente,
llegamos a sentir nuestra pobreza y la necesidad de nuestras almas,
interna y espiritualmente.

Entonces, al esperar en el Señor en esta consciencia,
cuando nos reunimos y cuando estamos solos,
el Señor respira sobre nosotros y enciende en nosotros fervientes
deseos y anhelos en el alma de ir en pos de lo que es puro,
de ser liberados de lo que es impuro, y de ser injertados más y más en Cristo.
Deseamos que el juicio y la condenación pasen sobre todo lo que no es de Dios en nosotros,
y que nuestros corazones estén tan unidos al Señor que temamos plenamente Su nombre.
Pues sentimos y observamos que toda nuestra vida y fuerza
fluyen de la unión de nuestras almas con el Señor. Por tanto,
y por encima de todas las cosas,
pedimos esa unión y que seamos separados de ese espíritu
que nos lleva cautivos a las cosas de la tierra,
y a la mente y naturaleza terrenales.

Así,
velamos en oración y buscamos ayuda de Dios en nuestra invocación a Él.
Estamos profundamente conscientes de que tenemos necesidad de ambas cosas,
de velar y orar constantemente,
porque el enemigo está cerca y las trampas y peligros del alma son muchos.

En realidad, Cristo, nuestro Señor y Maestro,
quien enseñó a Sus discípulos a orar antiguamente,
también nos ha enseñado a orar la misma oración,
aunque no a decir las palabras externamente en la
voluntad de los hombres o en nuestra propia voluntad.
Sí, Él les ha enseñado a nuestros corazones a respirar en pos de las mismas cosas,
es decir,
a buscar que el nombre de nuestro Padre celestial sea honrado o santificado cada vez más,
entre todos los que invocan Su nombre en verdad, y especialmente en nuestros corazones.
Deseamos que Su reino venga más y más, que Él reine en los espíritus de los hombres más,
y que el reino de pecado y de Satanás sea derribado,
para que Su voluntad sea hecha en nuestra tierra tal como es hecha en los lugares celestiales,
donde todas las huestes de Dios lo obedecen.
Lo buscamos para que nos dé esa porción de pan celestial
por medio de la cual nuestras almas pueden vivir para Él,
y para que nos dé la comida necesaria y la provisión externa,
según lo que Él ve que es bueno, pues Él tiene cuidado de nosotros.

Ahora, mientras nos mantenemos en la luz y vueltos a la luz que descubre todas las cosas,
podemos ver de qué somos guardados.
Y si en algún momento nos enredamos y por eso pecamos contra el Señor,
entonces somos enseñados a suplicar perdón (y a esperar
donde el perdón debe ser recibido a través de nuestro abogado),
así como Dios nos ha enseñado a perdonar.
Sin embargo, esto no anima a ninguno de los pequeños a pecar,
sino a orar para no caer en tentación, y que en su lugar,
experimenten la liberación del mal con el que el enemigo vigila para atraparlos.

Nosotros testificamos que esta es la religión pura y sin mácula delante de Dios,
y somos conscientes de que el Señor nos lo ha enseñado.
Él ciertamente está con nosotros en nuestra fe (la que Él nos ha dado),
en nuestra obediencia, en nuestra oración a Él en el nombre de Su Hijo,
en nuestra vigilancia, en nuestra espera,
en el silencio de nuestros espíritus delante de Su poderosa y gloriosa majestad.

¡Ojalá todos ustedes conocieran a nuestro Dios y
a Su Cristo en el mismo pacto y poder de vida,
en los que a Él le ha placido manifestarse a nosotros! ¡Oh, despierten,
despierten de sus sueños,
salgan de la noche de pecado y oscuridad a la luz del día!
¡No se ofendan porque los llamo sueños de la noche,
porque no son más que sueños comparados con la luz del día! ¡Oh,
no se contenten con sueños con respecto a Dios, con sueños con respecto a la comunión,
remisión, justificación, paz, santificación,
con respecto a la ayuda del Espíritu de Dios en la oración, etc.!

¡Ah, amigos, queridos amigos,
dejen ir lo muerto en pro de lo vivo! ¡Quiten el conocimiento muerto, la fe muerta,
la esperanza muerta, las oraciones muertas, el entendimiento de las Escrituras muerto,
los esfuerzos muertos tras la santidad,
nada de lo cual obtendrá nunca la promesa! ¡Sientan esa Semilla levantarse en ustedes,
en la verdadera y apartada espera en el Señor,
la Semilla que ciertamente obtendrá la promesa en ustedes,
en la medida que sus mentes se unan a ella y lleguen
al verdadero sentido y sujeción bajo ella!

Con Respecto al Estado del Evangelio

El evangelio es la ministración del nuevo pacto,
o la ministración espiritual de la sustancia de todo lo que estaba en sombra bajo la ley.
Había muchas cosas bajo la ley, pero en el evangelio Dios lo ha reunido todo en Uno.
En Cristo sólo hay una semilla, un Espíritu, una vida, un poder que redime,
una circuncisión, un bautismo, una fe, etc.
La ley fue dada por medio de Moisés,
y su ministración continuaría a través de los profetas hasta que viniera la Semilla,
la cual debía ponerle fin a la ley y a la justicia de la misma (conforme a la letra),
e introducir para siempre la justicia en el Espíritu.

El evangelio es por medio de Cristo (a través del cual Dios habló en los postreros días),
el amado Hijo, profeta y sumo sacerdote de Dios, y quien debe ser oído por siempre.
Mientras Cristo estuvo en la tierra con Sus discípulos,
les enseñó en el cuerpo de carne que el Padre preparó para Él. Y ahora,
por medio de Su Espíritu (o santa unción),
continúa enseñando a Sus hijos y formándolos en la virtud, vida y poder del nuevo pacto,
al darles un nuevo corazón y un nuevo espíritu,
y hacer que la vieja naturaleza del Adán terrenal muera en ellos y pase de ellos.

La ley fue dada al judío externo, y es contraria a la naturaleza en el hombre,
quien parece dispuesto a obedecer,
pero no lo hará. La ley también fue dada para refrenar esa parte
(o naturaleza en el hombre) que está por encima de la Semilla,
a la que le fueron dadas todas las sombras y tipos externos.

Pero en el evangelio, el cual es el poder de Dios para la redención del alma,
esa parte es eliminada, la Semilla es levantada y viene a vivir en el alma,
y el alma vive en el poder que la vivifica en y a través de la Semilla.
Por tanto, en la ministración del evangelio, la vida,
virtud y naturaleza de la Semilla lo eclipsa todo y lo cambia todo,
de modo que hay un nuevo cielo y una nueva tierra, donde Dios reina y habita la justicia.
Las cosas viejas, en las que moraba la injusticia y reinaba el maligno, son eliminadas,
y como resultado, su reino en el hombre es destruido y asolado,
y el reino de Cristo instalado, establecido y exaltado.

Entonces la montaña de la casa del Señor es conocida en
la cima y por encima de todas las montañas y colinas.
Entonces el alma iluminada corre hacia ahí para aprender del Señor en Su santuario santo,
a fin de conocer Sus caminos y caminar en Sus sendas.
Entonces la voz del verdadero Pastor es oída y la ley que sale de Sión conocida
(la ley del Espíritu de vida en Cristo Jesús). Entonces el día del Señor,
el poderoso, terrible y sacudidor día del Señor es conocido,
el cual está sobre toda carne,
silenciándola en el pavor y temor de Aquel que es santo y puro.
Entonces la Semilla es levantada en vida y poder y sólo el Señor es exaltado en esa alma.

Luego, después de esta sacudida,
después de la obra de este terrible día del Señor en el corazón, cuando Dios,
mediante Su Espíritu de juicio y fuego,
ha purgado la inmundicia y la sangre del alma y del espíritu contaminados,
lo que quede será llamado santo y será dedicado al Señor,
en aquellos que están escritos y son contados por Dios entre los
vivos en Su Jerusalén. Y Dios cubrirá con la gloria de Su presencia,
todos Sus tabernáculos y lugares de habitación en Su montaña y en Su ciudad santa.
Él será una defensa alrededor de ellos (mediante Su columna
de nube y resplandeciente llama) en todas sus asambleas,
ante lo cual el brillo de Satanás, con sus estratagemas y dardos encendidos,
caerá como destellos de relámpago.
En verdad,
sus tormentas y vientos no podrán prevalecer contra los lugares de habitación
que Dios edifica sobre Su montaña santa de paz y salvación.

Entonces se conoce la vara del tronco de Isaí,
el vástago que crece de su raíz y el Espíritu del Señor que reposa
sobre Él. Porque "`la gracia y la verdad vinieron por medio de
Jesucristo,`" y donde se recibe esta gracia y esta verdad,
y se entra en Su pacto eterno, ahí es derramado y reposa el mismo Espíritu.
El verdadero juicio es establecido en el corazón,
y el alma es implantada en la justicia y paz de Su reino.

Por tanto, si a alguno le falta sabiduría, pídala a Él con fe,
porque es dada fielmente desde el Espíritu de sabiduría que es derramado sobre la Semilla.
Este es el Espíritu de entendimiento y conocimiento, de temor puro y celestial,
que hace que el temor del Señor cobre vida en el entendimiento
y (al ser entendido y obedecido) mantiene el corazón limpio,
enseñándole a evitar y a mantenerse fuera de todo lo que contamina.
Aquí los hijos e hijas que son guiados por el Espíritu de Dios,
y que viven y caminan en el Espíritu, no tocan las cosas impuras,
sino que siguen la ley del Espíritu de vida en Cristo Jesús plena y perfectamente.

¡Sí, en este día es hecho el banquete de manjares suculentos en la montaña santa de Dios!
Y en esta montaña el velo que cubre (extendido sobre el corazón) es eliminado.
(Isaías 25:7) Porque en la Semilla no hay un velo que cubra,
sino una revelación al ojo que ha sido abierto para que vea la vida y el poder develados,
es decir, para que vea el brazo del Redentor revelado.

"`¿Quién ha creído a nuestro anuncio,
y sobre quién se ha manifestado el brazo de Jehová?`" Esto fue dicho en el antiguo pacto,
en la dispensación de la ley, pero no es dicho así en el nuevo pacto,
en la dispensación del evangelio.
Porque el velo es quitado en Cristo,
y así los hijos contemplan a cara descubierta (como en un
espejo) la gloria del Señor. Aquí se revela la Semilla,
el alma entra en la Semilla,
se une con la Semilla y se experimenta a la Semilla romper la cabeza de la serpiente.
Y entonces el alma dice: "`¡He aquí,
este es mi Dios a quien yo necesitaba tanto y por el que esperé tanto! ¡Oh, Él ha venido,
Él ha venido a juzgar mi corazón con justicia y a derribar todo lo que
ha mantenido a la Semilla bajo sujeción en mí! ¡Lo siento a Él,
la salvación de mi alma,
y mi corazón se alegra en Él! ¡Ahora conozco la tierra de Judá`" (porque la tierra externa
no era más que una figura de la interna) "`y la ciudad fuerte que está en ella!`"
