== Capítulo 11. El Bautismo de Cristo

[quote.scripture, , Marcos 16:16]
____
El que creyere y fuere bautizado, será salvo;mas el que no creyere, será condenado.
____

Esta es una escritura muy importante y es necesario que todo cristiano la entienda correctamente,
para que así pueda creer y ser bautizado,
de manera tal que experimente la salvación mediante el evangelio de nuestro Señor Jesucristo.

Ahora,
¿qué tipo de creer es este que se requiere aquí como necesario
para la salvación? ¿Podría ser menor que el creer en el Señor Jesucristo
que surge del verdadero sentido de Su poder para salvar,
dado por el Padre?
¿Acaso no es un creer interno, un creer con el corazón? Y,
¿cuál bautismo o lavamiento es este que salva?
¿No es el lavamiento interno, el lavamiento del alma, el lavamiento del corazón,
el lavamiento de la consciencia de obras muertas para servir al Dios vivo?
El lavamiento externo, ¿salva el alma?
El lavamiento interno sí;
el bautismo en el nombre sí. El ejercicio corporal para poco es provechoso,
pero la piedad (la renovación y lavamiento internos
del corazón y la mente) beneficia grandemente.

Hay una fe y un bautismo.
(Efesios 4:5) ¿Acaso no es la única fe interna y espiritual?
¿No es el único bautismo igual?
Estoy seguro que el que cree y es bautizado interna y espiritualmente, será salvo.
Pero el que no cree permanece en el estado inmundo y sucio en el que no hay,
ni puede haber salvación, sino juicio y condenación, muerte y destrucción para siempre.
Consideren ahora:

[quote.scripture, , 1 Pedro 3:20-21]
____
...cuando una vez esperaba la paciencia de Dios en los días de Noé,
mientras se preparaba el arca, en la cual pocas personas, es decir, ocho,
fueron salvadas por agua.
El bautismo que corresponde a esto ahora nos salva
(no quitando las inmundicias de la carne,
sino como testimonio de una buena conciencia hacia Dios) por la resurrección de Jesucristo.^
footnote:[1 Pedro 3: ver. 20 (RV1960) y ver. 21 (RVG)]
____

El apóstol Pedro muestra cuál es el bautismo que salva,
ese que es "`antitipo,`" o que interna y espiritualmente cumple el testimonio
del arca de Noé. La palabra en griego es _"`antitypous,`"_ la cual significa antitipo,
o aquello que cumple el tipo;
es la sustancia que viene en lugar de la figura o de la sombra.
Y así es más apropiada y naturalmente traducida (como lo dice la traducción antigua):
"`El bautismo que ahora salva, es el que cumple esa figura.`"
Porque,
así como el arca de Noé salvó los cuerpos de aquellos que estaban dentro
de ella cuando Dios vino a juzgar y a destruir el mundo antiguo,
ahora el lavamiento interno salva a los que son lavados así,
de la ira y destrucción que vendrán sobre todos los que no han sido lavados.

Ahora, con el fin de que nadie malinterprete y aplique mal sus palabras,
como si estuviera hablando de un bautismo o lavamiento externo,
Pedro se explica a sí mismo con las palabras,
"`no quitando las inmundicias de la carne,`" no con el lavamiento externo del cuerpo,
nada de eso es lo que salva,
sino ese bautismo que produce el testimonio de una buena consciencia delante de Dios,
mediante la resurrección de Jesucristo.
Pues este es el efecto del bautismo interno: El pecado es lavado por el agua de vida,
por la sangre del Cordero, y lo que es nuevo, lo que es renovado,
emerge del agua que lava el pecado.
Entonces la consciencia pura y buena da testimonio a Dios,
y el alma conoce y participa tanto de la muerte como
de la resurrección de nuestro Señor Jesucristo.
Y así, al ser bautizada por el único bautismo (es decir,
el bautismo de Cristo) en un solo cuerpo,
el alma entra al estado y comunión de los vivos.
Otro apóstol también habla del lavamiento interno, es decir,
"`el lavamiento de la regeneración y de la renovación
del Espíritu Santo,`" mediante lo cual,
dice él, Dios "`nos salvó...por su misericordia.`"
(Tito 3:5)

En otra parte el apóstol Pablo habla de una "`circuncisión
no hecha por manos,`" y dice en qué consiste,
a saber, en quitar el cuerpo de los pecados de la carne.
Además, muestra cómo es efectuada esta, no por la circuncisión de Moisés,
sino por la circuncisión de Cristo.
(Colosenses 2:11) Aquellos que son circuncidados de esta manera,
ciertamente son la verdadera circuncisión, la circuncisión espiritual,
los que adoran a Dios en Espíritu y no tienen confianza en la carne,
sino que se glorían en Cristo Jesús quien los circuncidó. Luego,
en el siguiente versículo Pablo habla del bautismo,
de ser '`sepultados con Él en el bautismo,
y de ser resucitados con Él mediante la fe en el poder de Dios,
quien lo resucitó de los muertos.`' ¿Qué es este bautismo?
¿Es inferior a la circuncisión mencionada justo antes?
¿Acaso no es también '`no hecho por manos`'? ¿Qué es lo que sepulta
en la muerte de Cristo y qué levanta en la vida de Cristo,
mediante la fe en el poder de Dios?
¿No es este el único bautismo espiritual y celestial,
con el que el único cuerpo es bautizado por el único Espíritu?
¿De qué sirve la circuncisión externa?
¿Sirve de algo?
¿De qué sirve el lavamiento externo?
¿Sirve de algo más que la circuncisión externa?
Pero la circuncisión interna del judío interno,
y el lavamiento interno del alma que limpia del pecado, sirve de mucho.

Ahora,
¿qué bautismo ordena Cristo expresamente en Mateo 28:19?
Esta es una pregunta muy importante y digna de ser considerada.
Porque si ordena un bautismo externo,
los que creen que es interno y espiritual están enormemente equivocados.
Pero si con estas palabras se refería al bautismo interno y espiritual,
entonces los que piensan que es el externo están completamente equivocados.
Ahora consideren las palabras en el temor y peso del Espíritu de Dios.

Se dice, '`vayan y enseñen, bautizando,`' pero no se dice, bautizando con agua,
sino '`bautizando en el nombre,`' o más bien (como lo tiene el griego),
'`bautizando __dentro del__ nombre del Padre, y del Hijo y del Espíritu Santo.`'

Ahora bien, bautizar con agua es una cosa, y bautizar dentro del nombre es otra,
como todos los que experimentan el bautismo espiritual lo saben.
Porque la Palabra de fe vuelve a los hombres, de Satanás al poder de la vida,
y entonces a medida que reciben el poder y son hechos partícipes de dicho poder,
son bautizados dentro del poder y virtud de la vida.
Y así, mediante el poder de Su Espíritu,
son sepultados con este bautismo celestial en la muerte al pecado, y por el mismo poder,
son vivificados en la justicia.
Y como resultado, el nombre del Señor (el nombre del Padre,
Hijo y Espíritu) viene sobre ellos, ellos son levantados en Él para vida y justicia,
y así están muertos al pecado y vivos para Dios.

Cualquier circuncisión o lavamiento externo sólo puede ser figura de esto,
pero la circuncisión y el lavamiento internos son la cosa misma.
Porque Cristo no envió a sus ministros competentes del nuevo pacto a ministrar la letra,
o a ministrar las figuras de las cosas, sino a ministrar al Espíritu (de otra manera,
¿para qué eran ministros competentes del Espíritu?), es decir, a ministrar la sustancia.
Ellos no debían ministrar una circuncisión o un bautismo que podía ser sacudido y pasar,
como algo externo y natural,
sino ministrar la circuncisión y el bautismo que no pueden ser sacudidos.
Estos son la circuncisión y el bautismo del evangelio,
la circuncisión y el bautismo del Espíritu, la circuncisión y el bautismo del reino,
el cual no puede ser conmovido ni pasar como pasa lo natural,
sino que se mantiene y permanece para siempre.
Lean Hebreos 12:26-28,
y consideren la manera en que todo lo natural y las cosas externas que podían ser sacudidas,
debían ser sacudidas y desechas,
para que las cosas que eran de una naturaleza superior (es decir,
de la naturaleza del reino), pudieran permanecer y ser establecidas en su lugar.

En realidad,
así como la circuncisión interna no podía ser completa y exclusivamente
establecida mientras la figura de la misma permaneciera,
lo mismo puede ser dicho con respecto al bautismo interno.
Por esto es evidente que el bautismo de agua no es
el bautismo al que Cristo se refería en este lugar,
pues el bautismo del que se habla aquí iba a continuar hasta el fin del mundo.
Pero el bautismo de agua es claramente de una naturaleza externa
y natural que puede ser sacudida (así como también la circuncisión),
y debía ser sacudida a su debido tiempo, para que quedara lo que no podía ser conmovido.

[.discourse-part]
Objeción:
Contra esto es objetado que el bautismo del Espíritu no puede ser
el bautismo del que se hace referencia en este lugar,
porque el bautismo del que se habla es ordenado,
pero el bautismo del Espíritu nunca fue ordenado.

[.discourse-part]
Respuesta: Esto es evidentemente un gran error.
¿Nunca fue ordenado el lavamiento interno del corazón?
El evangelio es la ministración de las cosas internas,
y las cosas internas son estrictamente ordenadas
ahí. ¿Puede un hombre ser salvo sin el bautismo interno?
¿Y acaso no se le ordena recibir el bautismo interno?
¿Acaso no es pecado si no espera recibirlo,
ni rinde su corazón y alma para ser bautizado por el Espíritu Santo de Dios?

¡Oh,
si el ojo fuera abierto en las personas para que pudieran mirar
la ministración del evangelio y la naturaleza interna de las cosas,
entonces estas serían evidentes incluso para el bebé
espiritual más pequeño! Pues en realidad,
para el Señor el evangelio existía antes de la ley y no podía ser anulado por esta.
Por tanto,
esta ministración del bautismo del Espíritu (en naturaleza
y género) existía mucho antes del bautismo de Juan,
y no podía ser anulada por ninguna ministración externa de bautismo,
sino que permanece igual para siempre.
Este bautismo debe tener su lugar en el estado del evangelio,
en el que todas las figuras y sombras de las cosas desaparecen, y lo que es verdadero,
duradero y sustancial llena su lugar.

Ahora, el bautismo del Espíritu,
o lavamiento espiritual y circuncisión del corazón (todo lo cual es uno en sustancia),
les fue demandado y requerido a los judíos bajo la ley,
y el pecado de ellos fue no responder a la demanda de Dios ni al requerimiento de ello.
Consideren las siguientes escrituras, entre muchas más de la misma naturaleza:
"`Arad campo para vosotros, y no sembréis entre espinos`" (Jeremías 4:3). De nuevo:
"`Circuncidad, pues, el prepucio de vuestro corazón,
y no endurezcáis más vuestra cerviz`" (Deuteronomio
10:16). "`Haceos un corazón nuevo y un espíritu nuevo.
¿Por qué moriréis, casa de Israel?`"
(Ezequiel 18:31). (¿No es esto uno en sustancia con la escritura,
"`El que creyere y fuere bautizado, será salvo`"?) "`Lava tu corazón de maldad,
oh Jerusalén, para que seas salva.
¿Hasta cuándo permitirás en medio de ti los pensamientos de iniquidad?`"
(Jeremías 4:14) "`Rasgad vuestro corazón,
y no vuestros vestidos`" (Joel 2:13). "`Lavaos y limpiaos;
quitad la iniquidad de vuestras obras de delante de mis ojos... Venid luego, dice Jehová,
y estemos a cuenta: si vuestros pecados fueren como la grana,
como la nieve serán emblanquecidos; si fueren rojos como el carmesí,
vendrán a ser como blanca lana.
Si quisiereis y oyereis, comeréis el bien de la tierra;
si no quisiereis y fuereis rebeldes, seréis consumidos a espada;
porque la boca de Jehová lo ha dicho`" (Isaías 1:16-20).

¿No es esto el verdadero bautismo y la consecuente remisión de
pecados que viene después? ¿Acaso no es esta la bendición sobre
el estado bautizado y la maldición sobre el estado no bautizado,
el cual se extiende tanto al judío como al gentil (porque Dios no hace acepción de personas)?
¡Oh, si los hombres pudieran leer las Escrituras de Verdad,
con el verdadero Espíritu y con el verdadero entendimiento!
Pues estas cosas que fueron escritas al pueblo de los judíos,
fueron escritas para nuestra enseñanza.
De hecho,
cosas preciosas de las Escrituras pueden ser aprendidas
por aquellos cuyos ojos son abiertos por Dios,
y que en su lectura se mantienen cerca de lo que unge y abre los ojos.
De lo contrario,
los hombres no pueden evitar malentenderlas y torcerlas para su propio y gran peligro,
o para ruina y destrucción de sus almas.

[.discourse-part]
Objeción: El bautismo del Espíritu no puede ser pretendido en Mateo 28:19,
porque este bautismo debe ser administrado por hombres,
pero el bautismo del Espíritu nunca fue administrado por hombres, sino por Jesucristo.

[.discourse-part]
Respuesta: El apóstol dice que Dios los "`hizo ministros competentes de un nuevo pacto,
no de la letra, sino del espíritu; porque la letra mata,
mas el espíritu vivifica`" (2 Corintios 3:6). Ahora consideren,
ellos fueron hechos ministros competentes por Dios de lo que da vida,
y es manifiesto en Hechos 19:6 (y muchas otras escrituras) que
ellos ministraron el Espíritu mediante la imposición de manos.

Es cierto que los apóstoles no podían por sí mismos o por alguna virtud o fuerza propia,
engendrar hombres para Dios o bautizar hombres en Su nombre y poder,
pero la suficiencia de ellos era de Dios.

Piensen: Pablo fue enviado a los gentiles para que les abriera los ojos.
(Hechos 26:18) Ahora,
abrir los ojos de los ciegos es tan propio de Cristo
como lo puede ser bautizar con el Espíritu.
Cuando Cristo les dio a Sus apóstoles la comisión de enseñar y bautizar, les dijo:
"`Toda potestad me es dada en el cielo y en la tierra,`"
y les mandó "`que no se fueran de Jerusalén,
sino que esperasen la promesa del Padre, la cual, les dijo,
oísteis de mí. Porque Juan ciertamente bautizó con agua,
mas vosotros seréis bautizados con el Espíritu Santo
dentro de no muchos días`" (Hechos 1:4-5),
y luego recibirían el poder.
¿Poder para hacer qué? ¿Para bautizar con agua,
o para bautizar en el nombre con el mismo bautismo con el que ellos mismos fueron bautizados?
Ver Mateo 28 junto con Hechos 1.

Ahora bien,
si la comisión dada a los apóstoles en Mateo 28:19 era que bautizaran con agua,
entonces Pablo era inferior a los otros apóstoles.
Porque él,
aunque había visto al Señor y fue enviado por Él para abrirles los ojos a los gentiles,
no fue enviado a bautizar con agua, como él expresamente lo dice:
"`Pues no me envió Cristo a bautizar +++[+++es decir, externamente con agua],
sino a predicar el evangelio.`"
Sin embargo, si el bautismo pretendido por Cristo era interno y espiritual, es decir,
en el nombre, virtud, vida y poder del Espíritu,
entonces Pablo recibió la comisión apostólica tan
plenamente como cualquiera de los demás apóstoles,
y la gracia y el poder de Dios obraron tan poderosamente
en él para este fin como en cualquiera de ellos.

Pero los hombres están tan equivocados acerca de la enseñanza requerida en esta comisión,
como lo están acerca del bautismo.
Pues esta enseñanza no es una enseñanza literal de cosas,
o una disciplina hacia un conocimiento y camino externos,
sino una enseñanza en el Espíritu y poder.
Aquel a quien Dios capacita para enseñar en el Espíritu y poder,
también lo capacita para bautizar en el mismo Espíritu y poder.
Sí, de hecho,
cuando la vida y el poder ministran (y la palabra
hablada se mezcla con fe en los que oyen),
llevan la parte terrenal a sujeción,
y elevan la vida y el poder del Señor Jesucristo sobre el corazón y el espíritu.
Este es el verdadero bautismo,
y es la sustancia de la figura o sombra que estaba
antes de la figura del bautismo y de la circuncisión,
y permanece cuando estos se han ido.

[.discourse-part]
Objeción: El bautismo en la comisión era para todas las naciones,
pero el bautismo del Espíritu únicamente cayó sobre unos pocos al principio.

[.discourse-part]
Respuesta: La promesa de recibir el Espíritu se basa en creer,
y se extiende a todos los que creen.
"`El que cree en mí, como dice la Escritura, de su interior correrán ríos de agua viva.
Esto dijo del Espíritu que habían de recibir los que creyesen en él`" (Juan 7:38-39).

De la misma manera le habló Pedro a la gran asamblea a la que le predicó,
a la que fueron añadidos cerca de tres mil almas: "`Arrepentíos,
y bautícese cada uno de vosotros en el nombre de Jesucristo para perdón de los pecados;
y recibiréis el don del Espíritu Santo.
Porque para vosotros es la promesa, y para vuestros hijos,
y para todos los que están lejos;
para cuantos el Señor nuestro Dios llamare`" (Hechos 2:38-39).

Este es el único lavamiento con el que todo el rebaño debe ser lavado,
y así bautizado en el único cuerpo puro y vivo.
Esta es la sustancia de la figura, cuya sustancia pertenece al estado del evangelio,
a pesar de que Dios también hizo uso de algunas figuras en el comienzo del día del evangelio,
e incluso, inclinó sus corazones entonces para hacer uso de ellas.

[.discourse-part]
Objeción: El bautismo mencionado en la comisión en Mateo 28,
no puede ser el bautismo del Espíritu porque debe
ser administrado en el nombre del Espíritu.

[.discourse-part]
Respuesta:
La palabra en griego no es _'`en`'_ que significa _"`en,`"_
sino _'`eis`'_ que significa _"`dentro.`"_
De manera que el bautismo ordenado aquí es bautizar dentro del nombre,
dentro del nombre del Padre, dentro del nombre del Hijo, dentro del nombre del Espíritu,
al volverlos de las tinieblas a la luz, del poder de Satanás a Dios.
Entonces el poder y vida del Espíritu Santo de Dios viene sobre sus corazones y mentes,
quebranta el poder de Satanás, lava la consciencia de lo que está muerto,
y los zambulle o sumerge dentro de lo que está vivo.

Pero que también había un bautismo con agua externa, no lo niego,
y que este fue usado como un tipo y sombra para el estado débil y ceremonial en el que
estaban los judíos (cuando Cristo envió a Sus apóstoles a sacarlos del estado de la
ley y reunirlos en el estado del evangelio) también estoy de acuerdo.
Sin embargo,
este desde entonces ha sido corrompido y ha sido establecido por
encima de su lugar por los que han caído del poder y la vida.
Y cada uno debe considerar y esperar en el Señor hasta saber lo que Dios requiere y
lo que aceptará de él. Porque el reino de Dios no consiste en comida ni en bebida,
ni en algún lavamiento externo.
Tampoco viene según evidencia ocular,
sino en la Semilla celestial y en el Espíritu Santo y poder de vida.
¡Felices los que son hechos partícipes,
son bautizados y son conducidos por el Espíritu de Dios!
En realidad, Dios probará la religión,
obra y práctica de todos los hombres por medio del verdadero cordel
de medición. ¡Bendito aquel cuya religión soporte dicha prueba!

Es muy importante conocer el estado y ministración del evangelio,
el Espíritu y poder del evangelio, la iglesia y las ordenanzas del evangelio,
las palabras de los santos profetas con respecto al día del evangelio,
las palabras de Cristo con respeto al reino y poder de Dios,
las palabras de los apóstoles con respecto al misterio
de la fe y la Palabra que estaba desde el principio.

En efecto, estas son cosas pesadas y de gran importancia,
las cuales los hombres fácilmente pasan por alto y sobre las cuales tuercen las Escrituras,
a menos que sean alumbrados por el Señor en la renovación de sus mentes,
y sus ojos se mantengan hacia la santa unción, para que haciéndolo no corran adelante,
ni así imaginen y conciban según su propia habilidad y entendimiento.

Los fariseos tenían un gran conocimiento y entendimiento de la ley de Dios,
y de las profecías de cosas por venir, a partir de las palabras de Moisés y los profetas.
Pero al no tener la verdadera llave del conocimiento, '`erraron,
ignorando las Escrituras y el poder de Dios`' (a
pesar de toda su lectura y estudio diligentes).

¡Oh, piensen!
Los fariseos jamás pensaron que ellos habrían matado
a los profetas si hubieran vivido en sus días. No,
ellos condenaron grandemente a sus padres por hacerlo, y sin embargo,
crucificaron a Cristo.
Hoy pocos piensan que ellos habrían crucificado a
Cristo si hubieran vivido en los días de Su carne,
y sin embargo, lo desdeñan,
lo critican y lo persiguen en la aparición del mismo Espíritu, vida y poder,
tal como aparece ahora en Sus santos.

[.discourse-part]
Pregunta: ¿Qué es lo que debe ser lavado en el estado del evangelio?
¿El hombre exterior o el interior?
Y, ¿con qué se debe lavar el hombre interior?

[.discourse-part]
Respuesta: Consideren la siguiente escritura seriamente,
y ojalá el Señor les dé el verdadero entendimiento:
"`En aquel tiempo habrá manantial abierto para la
casa de David y para los moradores de Jerusalén,
para el pecado y la inmundicia`" (Zacarías 13:1,
RV1602P). ¿Acaso no habla esta escritura del estado del evangelio?
¿Cuál manantial se abre en el estado del evangelio?
¿Es un manantial externo de agua externa que lava el pecado y la inmundicia?
El Señor conoce de qué naturaleza es el pecado, y con qué agua debe ser lavado,
y por tanto,
abre ese manantial en el estado del evangelio con el que es apropiado lavarlo.

Ahora bien, que había un lavamiento de pecados figurativo mediante el bautismo de Juan,
no lo niego.
Porque el de Juan era un bautismo para arrepentimiento,
y con ello profesaban el arrepentimiento y que debían "`hacer frutos dignos de
arrepentimiento`" (Mateo 3:8). Pero el "`antitipo`" (1 Pedro 3:21) o cumplimiento,
no es un lavamiento de la inmundicia de la carne o del cuerpo, sino un bautismo interno,
el cual lava tan internamente que el testimonio de una buena consciencia
es palpablemente experimentado ante los ojos y presencia de Dios.
Y entonces el alma verdaderamente conoce con qué tipo de agua fue lavada.

¡Ojalá la gente conociera y experimentara el bautismo que es sustancia!
¡Entonces no idolatrarían ese bautismo (o lavamiento externo),
que en su naturaleza no puede ser más que una señal,
figura o representación de lo que es la sustancia!

Ahora piensen, ¿conocían los judíos la circuncisión interna?
Y,
¿conocen ustedes el bautismo interno más de lo que
los judíos conocían la circuncisión interna?
Lean esta escritura y que el Señor la aplique a sus almas:
"`Pues no es judío el que lo es exteriormente,
ni es la circuncisión la que se hace exteriormente en la carne;
sino que es judío el que lo es en lo interior, y la circuncisión es la del corazón,
en espíritu, no en letra; la alabanza del cual no viene de los hombres,
sino de Dios`" (Romanos 2:28-29). ¿Acaso no dice el Espíritu de Dios en nuestros días (sí,
en verdad el Espíritu de nuestro Dios lo dice así y muchos han oído Su voz hablando):
'`No es cristiano el que lo es externamente,
ni el bautismo del evangelio el que se hace externamente en la carne,
sino que es cristiano el que lo es internamente,
y el bautismo del evangelio es el del corazón, en el Espíritu, no en la letra,
cuya alabanza no es de los hombres,
sino de Dios.`' Los judíos alababan a los circuncidados
externamente y ustedes alaban a los bautizados externamente,
pero Dios alaba a los circuncidados y lavados internamente.

[.discourse-part]
Objeción: Pero el bautismo del Espíritu es una promesa, no un deber.

[.discourse-part]
Respuesta: Que el bautismo del Espíritu es una promesa, lo concedo,
pero también es un deber recibir la promesa y rendirse
para ser bautizado por Él. Porque Juan dijo:
"`Yo a la verdad os bautizo en agua para arrepentimiento; pero el que viene tras mí,
cuyo calzado yo no soy digno de llevar, es más poderoso que yo;
él os bautizará en Espíritu Santo y fuego`" (Mateo 3:11). El bautismo
del Espíritu es la purga interna del pecado y la inmundicia,
por medio del Espíritu y Su fuego,
o por el "`Espíritu de juicio y fuego`" (Isaías 4:4). Los que fueron bautizados por Juan,
después tuvieron que expectar y esperar este bautismo,
para que el Señor '`limpiara con Su aventador su era,
su paja fuera quemada y el trigo recogido en el granero.`' (Mateo 3:12)

Ahora bien, nosotros, en efecto,
concedemos que la circuncisión de Moisés era una ordenanza de Dios,
y que el bautismo de Juan era una ordenanza de Dios.
Pero afirmar que cualquiera de estas es una ordenanza del evangelio
(que la circuncisión de Moisés es la circuncisión de Cristo,
o que el bautismo de agua de Juan es el bautismo de Cristo),
lo negamos conscientemente y con fundamento.
En realidad, el Espíritu de Dios (en las Escrituras) declara una diferencia entre ellos,
en particular, entre el bautismo de Juan y el de Cristo.
(Mateo 3:11) Además, establecer la sombra de una cosa en lugar de la cosa misma,
no es la manera de glorificar a Cristo o la dispensación del evangelio.
Porque Cristo es el Hijo,
quien no vino predicando la circuncisión de Moisés
ni el bautismo de Juan (los cuales eran siervos),
sino el Espíritu y poder de Su Padre,
con los que Él circuncida y bautiza interna y espiritualmente.

=== El Testimonio del Espíritu de Dios

[quote.scripture, , Salmo 51:15-17]
____
Señor, abre mis labios, y publicará mi boca tu alabanza.
Porque no quieres sacrificio, que yo lo daría; no quieres holocausto.
Los sacrificios de Dios son el espíritu quebrantado;
al corazón contrito y humillado no despreciarás tú, oh Dios.
____

[.discourse-part]
__Interrogante 1:__
¿Qué regla tenía David de la ley de Moisés para decir que Dios no deseaba sacrificios,
ni se deleitaba en los holocaustos?
¿Acaso no deseaba y requería Dios que Su pueblo realizara estas cosas estando bajo la ley?
¿Acaso no las aceptaba y se deleitaba en ellas,
cuando ellos las cumplían correctamente en fe y obediencia a Él?
¿Acaso no se complació el Señor con el sacrificio de Abel?
¿No olió Dios una fragancia dulce del sacrificio de Noé? ¿Cómo pudo decir David,
en verdad y a partir del verdadero Espíritu,
que Dios no deseaba ni se deleitaba en esas cosas?

[.discourse-part]
__Interrogante 2:__
¿No debía probar David si el Espíritu que hablaba estas cosas en él era o no de Dios?
¿Debía él recibir de cualquier espíritu,
un testimonio tan directamente contrario en apariencia a
los anteriores testimonios de Dios en las Sagradas Escrituras,
sin la plena y segura evidencia y demostración de que era el Espíritu de Dios?

[.discourse-part]
__Interrogante 3:__ ¿Cómo debía probar David si ese Espíritu era o no de Dios?
¿Debía probar si hablaba de acuerdo al testimonio y ley de Moisés,
lo cual ciertamente era de Dios y fue dado por Dios como ley y
gobierno a los judíos? Si David lo hubiera probado de esta manera,
¿no lo habría juzgado como un espíritu diferente al Espíritu de Moisés,
hablando en contra de la ley y de los testimonios
que Dios le había dado a él? Pues efectivamente,
el sacrificio y el holocausto eran estrictamente demandados ahí,
y Dios a menudo testificó Su aceptación y deleite en ello.
Así que Dios aceptaba y se deleitaba en estas cosas en un sentido,
y no aceptaba ni se deleitaba del todo en ellas en otro sentido,
porque Su objetivo estaba en otra cosa y en otro sacrificio,
el cual David vio claramente.
Así, pues, el ojo, la mente, corazón y espíritu de David,
habiéndose vuelto hacia adentro, es decir, hacia donde estaban el ojo y corazón de Dios,
tuvo una vista clara y dio un testimonio fiel acerca de lo que
era y no era aceptable a los ojos del Señor. Y así dice:
"`Porque no quieres sacrificio; no quieres holocausto`" (Salmo 51:16),
aunque el lenguaje de la ley de Moisés habla de otra manera, donde la circuncisión,
sacrificios y tales cosas externas se declaran como de gran valor para el Señor.

[.discourse-part]
__Interrogante 4:__ Ahora bien,
¿acaso no puede decirle el mismo Espíritu (o los hijos de
Dios en el mismo Espíritu) al Señor en nuestro día,
con respecto a cosas de la misma naturaleza externa: '`Tú no deseas esas cosas externas,
de otro modo las realizaríamos.
Tú no te deleitas en las sombras externas de las cosas del reino.
No deseas que se lave el cuerpo con agua,
o que se coma el pan externo y se beba el vino externo,
que no valen más que la circuncisión y la Pascua.
Si Tu deleite estuviera en las cosas de esta naturaleza y las requirieras de nosotros,
¡oh, con cuánta disposición nos encontrarías en la práctica de ellas delante de Ti!
Pero Tu deleite está en el agua que lava el alma de su inmundicia
y en las almas que son lavadas con ella.
Tú deseas ver a tus hijos alimentándose del pan vivo, del pan que baja del cielo,
y bebiendo el vino que refresca y alegra el corazón tanto de Dios como del hombre.`'

El Señor también nos ha mostrado claramente que el agua, pan y vino externos,
no son la sustancia, lo espiritual, el agua celestial, el pan celestial,
el vino celestial.
Más bien, estas cosas son de la naturaleza de las cosas que deben ser conmovidas,
para que las cosas que no pueden ser conmovidas permanezcan
en el estado y reino del evangelio.

¡Por tanto, que los hombres tengan cuidado en la manera en que edifican,
o cómo juzgan con respecto a las apariciones de Dios,
mediante sus propias comprensiones de la letra de las Escrituras!
¡Sean todos cuidadosos en edificar sobre la roca que es Cristo,
sobre Su Espíritu, Su vida, Su poder internamente revelado,
que el nacimiento espiritual (según nos aferramos a él),
revela en y a nosotros! ¡Pues ningún hombre,
por medio de sus propios conceptos y comprensiones sobre la letra,
nunca conoció o puede conocer, el Espíritu del Señor ni Su voz!
Porque el hombre está muerto, está en oscuridad y es corrupto,
excepto en la medida que es vivificado,
iluminado y su corazón santificado por el Espíritu Santo de Dios.
¿Qué puede ver un hombre muerto?
¿Qué puede oír un hombre muerto?
¿Puede oír el sonido vivo antes de ser vivificado
por él? ¿No hablan las Escrituras de cosas espirituales?
¿Puede el hombre natural entenderlas?
¿Puede la mente impía del hombre entender las palabras del santo y puro Espíritu de Dios,
que fueron dadas a través de vasijas que fueron santificadas (algunas
desde el vientre) y cuando el Espíritu del Señor estaba sobre ellas?

¡Oh,
si los hombres vieran la necesidad de que el Señor les abra sus corazones
y de que la carne sea silenciada en ellos! ¡Si ellos pudieran llegar a
experimentar el nacimiento del Espíritu de Dios y el precioso entendimiento
de las cosas celestiales que les es dado ahí! Entonces,
ese entendimiento que no es precioso, ni vivo, ni de Dios, sino de ellos mismos,
no les sería de gran valor.
Porque, en efecto, a través de este gran error,
muchos (algunos de los cuales son celosos y conocedores según la estima de los
hombres) rechazan lo que es de Dios y establecen lo que es de ellos mismos,
es decir, su propia comprensión y conceptos,
todo lo cual será de amargura y dolor al final,
cuando sea abierto el ojo que actualmente está cerrado en ellos.

¡Bendito el que verdaderamente puede decir: "`El Señor ha abierto el ojo en mí, es decir,
el ojo verdadero, el ojo puro, el ojo vivo,
y ahora veo con ese ojo y no con el ojo con el que veía antes! ¡Ahora conozco la diferencia
entre ver las mismas cosas con mi propio ojo y con el ojo que Dios me ha dado!
De manera que ahora,
mi más ferviente deseo y oración al Señor es que mantenga
abierto en mí para siempre el ojo que Él ha abierto,
y que mantenga cerrado el ojo que Él, en Su tierna misericordia para conmigo,
le ha placido cerrar en mí.`"

Ciertamente esta es la base de la gran diferencia entre nosotros y los demás,
con respecto a las cosas de Dios.
Porque, aunque reconocemos las mismas cosas y hablamos de las mismas cosas, aun así,
nosotros no las reconocemos igual, ni hablamos de ellas igual.
¿Por qué? Porque las vemos con diferentes ojos,
y por eso tenemos un sentido diferente de ellas.
Otros dicen que las cosas son verdaderas y las reconocen así,
según las comprenden de la letra.
Nosotros las llamamos verdaderas en la medida que el Espíritu de Dios nos las demuestra,
y en la medida que experimentamos en nuestros corazones, proveniente de Dios, la virtud,
vida y poder de ellas.
