== Capítulo 12. Un Testimonio Adicional / Sobre la Obra de Dios en Nuestros Corazones

Nosotros somos un pueblo (muchos de nosotros) que ha estado grandemente afligido
por la falta de la vida y del poder que se revelaron en los días de los apóstoles.
Somos una raza de peregrinos que hemos estado viajando de la naturaleza, sabiduría,
espíritu y curso de este mundo (el cual es vano y pasajero),
hacia nuestro lugar de reposo.
Hemos vagado de montaña a colina, de una forma de religión a otra,
buscando a Aquel a quien nuestras almas aman tanto.
De hecho, los guardas a menudo se habían reído y burlado de nosotros,
deseando que volviéramos a ellos, pero eso no calmaba el clamor de nuestras almas,
las cuales habían estado enfermas por el ferviente deseo,
no en busca de las prácticas formales de religión,
sino en busca de la vida e inmortalidad,
para que fueran nuevamente sacadas a la luz (como habían sido experimentadas
en los días de los apóstoles) y que de esta manera,
nuestras almas fueran hechas partícipes de estas.

Después de muchos fatigosos pasos y profunda enfermedad de corazón,
cuando nos habíamos acercado a la desesperación por no encontrar
ni disfrutar lo que nuestras almas tanto anhelaban,
le plació al Señor finalmente, en Su tierna misericordia, aparecer entre nosotros.
Y mediante las instrucciones de Su Espíritu Santo,
nos enseñó a volver nuestras mentes al interior,
mostrándonos que lo que buscábamos fuera se encontraba dentro.
En efecto, Él nos dijo que allí (dentro) estaba el reino de Dios,
el cual no se halla en señales o evidencias externas,
sino cuando nos encontramos con la luz y poder de la vida, y nos sujetamos a ello.
Y cuando nos preocupó cómo íbamos a distinguirlo de las tinieblas y engaños internos,
la respuesta del Señor fue: "`Su naturaleza se dará a conocer a sí misma,
porque ella pondrá de manifiesto y reprenderá lo que merece ser condenado
y le proporcionará al alma fuerza contra las tinieblas y el engaño.`"

¡Oh, bendito sonido del Señor Dios de vida,
quien persuadió nuestros corazones a esperar en Él, y nos mostró cómo esperar,
qué esperar y dónde podíamos encontrar lo que nuestros corazones tanto deseaban y anhelaban!
Y así fue, cuando nuestras mentes se volvieron al interior,
la luz santa del Sol de Justicia brilló sobre nosotros,
y la vida y naturaleza puras del Hijo de Dios brotaron en nosotros.
Experimentamos el poder de Dios revelado en nuestros corazones,
que la vieja imagen de pecado e injusticia diariamente se desfiguraba,
y que nuestras almas eran creadas de nuevo (en Cristo Jesús) a la imagen santa y celestial.
Aquí sentimos la misericordia de Dios, que ha salvado a Su pueblo en todas las edades,
alcanzándonos a nosotros también, y descubrimos a Su Espíritu regenerándonos,
renovándonos y lavándonos con el agua y la sangre que limpian.
Por tanto, en la medida que éramos más regenerados y renovados, más lavados éramos,
más comunión experimentábamos con Cristo en Su muerte
y más levantados éramos por Él en Su vida,
y también,
más enseñados éramos a poner cada vez más la mira
en las cosas de arriba y menos en las de abajo.
Porque las cosas de abajo son de una naturaleza que atrapa y enreda,
en la cual las mentes de los hijos de los hombres son mantenidas
cautivas hasta que se encuentran con ese Espíritu y poder real,
excelente y noble que quebranta las cadenas y grilletes de las tinieblas,
y las redime de ellas.
Ahora podemos testificar (en el verdadero sentido,
evidencia y demostración del Espíritu de Dios) que no por nuestro propio obrar,
querer o correr (ni por ninguna obra de justicia que hayamos hecho o podamos hacer),
sino por la visita de la tierna misericordia de Dios y operación de Su
Santo Espíritu sobre nosotros (en y a través de la regeneración,
renovación y limpieza de lo que contamina y mancha nuestras almas),
fuimos salvados de la ira venidera y de los caminos de transgresión en los que andábamos,
antes de que nuestro Dios nos visitara.

Y ahora,
el deseo sincero de nuestras almas es que esta tierna misericordia
de Dios tenga también efecto sobre los demás,
y que sean llevados también por Él al lugar donde la sabiduría enseña a sus hijos,
donde la verdadera redención del alma es experimentada,
y el verdadero conocimiento del Padre y de Cristo
(el cual es vida eterna) es dado y recibido.
Es nuestro más ferviente deseo que las personas no se endurezcan hasta la destrucción,
ni sean engañadas en sus almas por una religión tonta y vana,
en la que no está la sustancia, sino únicamente una muestra y aparición de esta,
que no puede satisfacer en realidad lo que es ciertamente
engendrado y nacido del Espíritu de Dios.

=== Algunos Interrogantes que Deben Ser Seriamente Considerados

[.discourse-part]
_Interrogante 1:_
¿Quiénes conocen y confiesan verdadera y correctamente al Señor Jesucristo?
¿Son los que Lo conocen y Lo confiesan únicamente como es descrito
externamente en las Escrituras y se habla de Él en ellas,
pero no Lo conocen internamente revelado en sus corazones
como la Palabra y el poder de vida eterna?
¿No son más bien los que no sólo Lo conocen según la descripción literal de las Escrituras,
sino también internamente revelado por el Padre;
los que Lo experimentan formado en su interior,
teniendo sus corazones cambiados a Su imagen santa y celestial,
por virtud de Su aparición interna y operación de Su Espíritu y poder en ellos?

[.discourse-part]
_Interrogante 2:_
¿Quiénes conocen verdadera y correctamente la muerte y resurrección de Cristo?
¿Son los que únicamente conocen el relato de estas cosas en las Escrituras,
pero no son conformados a Su muerte, ni levantados por Él en el poder de Su vida?
¿No son más bien los que son sepultados con Él (por
el bautismo santo de Su Espíritu) en la muerte,
y quienes a través del Espíritu han hecho morir las obras del cuerpo?
Estos verdaderamente experimentan a la Semilla santa de vida resucitada y viva en ellos,
y se descubren a sí mismos resucitados y vivificados para
Dios en y a través del poder del Padre revelado en ellos.

[.discourse-part]
_Interrogante 3:_
¿Quiénes confiesan verdadera y correctamente que Cristo es el Señor y Rey,
Sacerdote y Profeta de Su pueblo?
¿Son los que Lo confiesan únicamente a partir de la lectura de estas cosas en las Escrituras,
o los que Lo experimentan ejecutando estas cosas dentro de ellos?
De hecho,
¿acaso no conocen verdaderamente a Cristo los que Lo experimentan
venciendo y reinando sobre el pecado y la muerte en ellos,
ministrando en Su templo, ofreciendo dones y sacrificios espirituales al Padre,
y profetizando ahí al abrir y revelar los misterios de Su reino?

[.discourse-part]
_Interrogante 4:_ ¿Conocen o pueden conocer verdaderamente la voz de Cristo,
los que nunca experimentan la Palabra de vida hablando en Sus corazones?
¿Dónde habla el falso profeta?
¿Acaso no habla en el interior?
¿Dónde habla el verdadero Pastor?
¿Acaso no lo hace también en el corazón? ¿Y acaso las ovejas no oyen,
conocen y distinguen Su voz allí también?

[.discourse-part]
_Interrogante 5:_ ¿Quiénes son injertados en Cristo?
¿Puede una persona ser injertada en Él,
a menos que Cristo le sea internamente revelado y dado a conocer,
de manera tal que palpablemente sienta la Raíz pura y santa de vida sosteniéndola,
y Su savia fluyendo en ella haciendo que produzca fruto para Dios a su debido tiempo?

[.discourse-part]
_Interrogante 6:_ ¿Quién ora en el nombre de Cristo?
¿Es el que dice las siguientes palabras (o parecidas) en su propia voluntad:
"`¡Escúchame, Señor, por amor a Cristo!`"
O: "`¡Te lo suplico en el nombre de Cristo, quien es digno!`",
etc.? ¿No es más bien el que ora en la naturaleza del niño,
con las respiraciones del Padre en él, en el Espíritu del Padre que le es dado,
y en el tiempo y voluntad del Padre?
El que no hace más que suspirar o gemir en y a partir del Espíritu,
¿acaso no asciende al Padre ese suspiro o gemido en el nombre de Cristo?
¡Ay, cuán externa es la religión de los hombres!
Pero no conocen los arroyos y las corrientes internas de la religión verdadera,
pura y celestial.

[.discourse-part]
_Interrogante 7:_ ¿Quién cree verdadera y correctamente en Cristo?
¿Cree alguno así, o puede hacerlo así,
sin haber experimentado primero la vida de la que brota la verdadera fe?
¡Ojalá se frustrara en los hombres toda forma de fe, excepto la que sale de la vida,
se une a la vida y permanece en la vida!

[.discourse-part]
_Interrogante 8:_ ¿A quién recoge Cristo de las áridas montañas? ¿Acaso no es a Sus pobres,
afligidas, esparcidas, heridas, desmayadas y casi famélicas ovejas?
¿Qué son las montañas de las que Él las recoge?
¿No son las varias formas, adoraciones y profesiones muertas de la religión sin vida?
¿De la boca de quién las rescata Él? ¿No es de la
boca de los pastores que han hecho presa de ellas,
de los que no las han alimentado con vida, sino con palabras, con sueños,
con comprensiones de sus propias mentes con respecto a las cosas de Dios?

[.discourse-part]
_Interrogante 9:_ ¿Quiénes son los parientes de Cristo según el Espíritu?
¿Quién es Su madre, hermana y hermano?
¿Acaso no son los que hacen la voluntad del Padre?
¿Y es esta obediencia una obra conforme a la ley o a la justicia de la ley?
No, es obra de la naturaleza y justicia del evangelio que fluyen de Aquel que es justo.

[.discourse-part]
_Interrogante 10:_ ¿Hay dos Cristos, uno manifestado fuera y otro revelado dentro?
¿O es el mismo Señor Jesucristo, quien en los días de Su carne apareció externamente,
y fue manifestado después en el interior como el misterio de vida y esperanza de gloria?
¿Acaso no es Él revelado también hoy,
y dado a conocer dentro de nosotros por el mismo Espíritu eterno?

Hay un gran número que afirman estar en el estado del evangelio,
diciendo que están en Cristo y bajo la gracia,
y que han sido gratuitamente justificados por gracia,
de modo que consideran sus pecados cubiertos por el Señor y no imputados a ellos, etc.
Muchos profesan estas cosas, sin embargo,
desconocen por completo lo que significan verdadera y rectamente ante los ojos de Dios.
Porque es algo muy serio estar en Cristo, es decir, conocer Al que es verdadero,
y estar en el que es verdadero.
Es algo muy grande salir de las tinieblas y entrar en Su luz,
salir de la muerte y entrar en Su vida,
salir del reino de Satanás y de la sujeción al pecado,
y entrar en el reino de Cristo y a la sujeción a Su Espíritu.
"`De modo que, si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron;
he aquí todas son hechas nuevas.`"
¿Es esto cierto?
¿El que está en Cristo experimenta esto?
¿Y el que no experimenta esto, está en Cristo?

¡Oh,
cuántos están engañados en lo que se refiere a su "`estar en`" Cristo
y de su esperanza en Él! ¡Cuán pocos de los que hablan de estar en Cristo,
conocen lo que significa la nueva creación en Él,
o qué es tener formado a Cristo en ellos! ¡Cuán pocos conocen Su Espíritu,
por haberlo recibido y por su unión con Él! "`Y si alguno no tiene el Espíritu de Cristo,
el tal no es de Él`" (Romanos 8:9, RVG).

¡Oh, cuán pocos conocen verdaderamente, lo que es estar bajo la gracia!
Porque la gracia es la que tiene dominio sobre el pecado,
y la que les da dominio a los que están bajo ella.
"`Porque el pecado no se enseñoreará de vosotros; pues no estáis bajo la ley,
sino bajo la gracia,`" dijo el apóstol.
Por tanto, no presenten sus miembros como siervos o instrumentos para el pecado.
Ustedes lo hacían así cuando eran libres de la justicia, pero ahora,
no dejen que el pecado reine en sus cuerpos mortales,
siendo que la gracia les da poder sobre él y los hace libres de él para justicia.

Por tanto,
la justificación por gracia es únicamente para los que son enseñados por la gracia.
La gracia de Dios les trae salvación, redención y justificación a estos, y no a otros,
porque los pecados son borrados,
cubiertos y no imputados sobre aquellos que reciben la gracia, oyen su voz y la obedecen.
"`Oigan, y sus almas vivirán.`" Al oír esta gracia (por medio de la cual Dios enseña),
las almas llegan a la luz en Su presencia y los vivos son justificados por Él,
y en el camino vivo y senda de vida,
los pecados son borrados y una vestidura es dada para cubrir la desnudez.
Esta vestidura debe ser ceñida en el alma y mantenida cerrada,
o la desnudez y la vergüenza aparecerán y se verán de nuevo.

Así que creer en el nombre de Cristo, correr a Su nombre, confiar en Su nombre,
orar al Padre en Su nombre, obedecer en Su nombre y poder,
son asuntos importantes y serios, y muy pocos de los que hacen profesión de ellos,
verdaderamente los conocen.
Pues Su nombre es vivo, y Su presencia,
virtud celestial y poder están en él. Los que conocen Su nombre,
conocen lo que está por encima de todo nombre,
y conocen lo que tiene la autoridad de Dios para someter todas
las cosas (tanto en el corazón como en la vida y la conducta),
a fin de que sólo Dios sea exaltado.

El estado del evangelio es un gran estado, un estado elevado.
No es un estado de sombras, sino el estado del reino eterno,
donde es poseída la sustancia de las cosas bajo la ley por aquellos que están allí,
según crecen en el poder y pacto del evangelio.

=== Algunos Temas en Particular

[.alt]
==== Con Respecto a la "`forma de las sanas palabras.`"--2 Timoteo 1:13

En las ruinas de la gran apostasía se han perdido y enterrado miserablemente,
no sólo la "`forma de las sanas palabras,`" sino
también el buen conocimiento de las cosas celestiales.
Ahora, aunque los hombres han tenido las Escrituras, aun así,
carecen del Espíritu de Dios, y al no saber cómo volver sus mentes a Él,
ni cómo discernir Su voz de la voz de sus propios espíritus y razonamientos (sí,
ni tampoco de la del enemigo,
quien acecha a la espera de meter sigilosamente falsas comprensiones
de las Escrituras en las mentes de los hombres),
no han llegado al entendimiento claro, ni de las cosas,
ni de las palabras de las Escrituras.
En su lugar, por el conocimiento y la comprensión que han reunido,
muchas veces han estado listos para pelear contra Cristo,
en lugar de pelear contra el anticristo.
De modo que sus confesiones de fe y sus exposiciones de las Escrituras han sido mezclas,
más acomodadas a sus propias creencias y comprensiones,
que a la verdadera naturaleza de las cosas.
Sí, por este conocimiento reunido,
han estado en gran peligro de oponerse a la administración pura de la verdad de Dios,
la cual proviene y está en la luz y poder de Su propio Espíritu.
Igualmente, las iglesias que estos hombres han reunido y edificado,
han sido edificadas mediante la imitación de algo que fue
hecho antes mediante el poder y la autoridad del Espíritu,
y no en el mismo poder, vida y autoridad.
Lo mismo podría decirse de sus ordenanzas y deberes,
en los que ellos han cometido muchos errores.

Es cierto, algunos de ustedes han rechazado algo de madera, paja y rastrojo,
y reconocemos la bondad de Dios para con ustedes, en que han llegado a este punto.
¡Pero aún hay más que rechazar!
Toda imitación,
conocimiento e interpretación de las Escrituras que esté fuera de la vida pura,
debe ser dejado de lado,
y el Espíritu del Señor debe ser esperado en la luz que es de Él.
La mente debe volverse hacía aquí y aprender verdaderamente a permanecer.

¡Oh, profesantes, ustedes conocerían mucho más de Él,
si lo conocieran a Su manera y lo adoraran en la ordenanza eterna,
la cual es la luz pura de Su Hijo!
Pues esta luz estaba antes de la letra,
y lleva al alma más cerca del Señor de lo que puede hacerlo la letra,
y da una comunión más plena con el Señor en el Espíritu,
de la que puede tenerse o disfrutarse a través de las palabras o conceptos de las cosas.
El propósito del testimonio de la letra es llevar el alma
al Espíritu y poder que es la administración del evangelio.

[.alt]
==== Con Respecto a las Doctrinas

Los hombres ponen un gran énfasis en aprobar las doctrinas,
según la comprensión que tienen de ellas,
pero aún queda mucho camino por delante para escapar de Babilonia,
y salir del espíritu y sabiduría del hombre.
En efecto, antes de que sus doctrinas sean aprobadas por el Señor,
ellos deben entrar más en el temor puro y esperar en Dios,
más en la consciencia y poder de la verdad,
y más en la luz y conocimiento que se experimentan ahí. "`¡Aférrense a
la Cabeza!,`" es el clamor que brota en mi corazón en amor y ternura verdaderos,
y en suave compasión hacia ustedes.
No cuestiono si tienen conceptos acerca de la Cabeza,
según el entendimiento que tienen de las cosas; no obstante, aferrarse a la Cabeza es,
definitivamente, algo mucho más profundo.

De nuevo,
un hombre puede percibir sus doctrinas referentes
a las cosas principales y sustanciales como correctas,
cuando en realidad no lo son.
Pues las doctrinas del evangelio son misterios.
La fe es un misterio, el amor de Dios en el Espíritu es un misterio,
la obediencia a la verdad es un misterio,
la correcta confesión de Cristo en y a través del Espíritu es un misterio,
la adoración a Dios en Espíritu es un misterio, la justificación, santificación,
paz y gozo del Espíritu, todos son misterios del reino,
los cuales son fáciles de perder y malentender,
pero llegar al verdadero conocimiento de ellos es difícil.
De hecho, si en algún momento es recibido algún conocimiento verdadero,
interno y espiritual de estas cosas, tal conocimiento es difícil de retener,
por no decir imposible de hacerlo correctamente, excepto en esa luz y poder que lo dio.

En realidad, este es el gran misterio de la religión, a saber:
Comenzar en el Espíritu y viajar en la luz, vida y conocimiento puros del Mismo,
y no dar lugar o mezclarse con algo de la carne.
Pero si un hombre no tiene el Espíritu de Cristo, o no es capaz de distinguir la voz,
movimientos y obras del Espíritu de Cristo del otro espíritu,
o de su propia sabiduría y entendimiento, entonces cuando lee una escritura,
fácilmente se extravía y se equivoca con respecto a las doctrinas ahí declaradas.
Puede dejar entrar algo propio, o de lo que el otro espíritu forma,
en lugar de lo que es la verdad pura de Dios, y luego,
lo que ha dejado entrar hará que juzgue mal con respecto a la verdad,
y a menudo lo hará un gran enemigo de ella.

Este fue el caso de los escribas, fariseos y grandes sacerdotes en el tiempo de Cristo.
Ellos estudiaban la ley y hacían interpretaciones de ella,
ya que habían sido designados por Dios para preservar el conocimiento del pueblo.
Por causa del entendimiento que tenían de la ley y los profetas,
Cristo no podía ser el Mesías,
pues Su aparición claramente no concordaba con la ley y los profetas,
según sus propias interpretaciones.

Así que mientras algunos dicen: "`Nuestra religión consiste, primero,
en comprensiones correctas de las Escrituras, etc.,`" nosotros, por otro lado,
no podemos dejar de testificar (según hayamos sido convencidos por el Señor),
que un hombre debe primero recibir al Espíritu,
antes de poder tener comprensiones correctas acerca de los misterios de Dios, Cristo, etc.
Porque el Espíritu escudriña lo profundo de las cosas de Dios,
y nadie conoce las cosas de Dios excepto por el Espíritu.
En consecuencia, es necesario que las personas se vuelvan primero al Espíritu de Dios.
Este es el primer paso en el camino hacia el conocimiento verdadero y salvador.

[.alt]
==== Con Respecto a la Obra de la Luz

Cristo,
a quien el Padre le dio todo el poder y la autoridad para
enviar mensajeros a predicar el evangelio de Su salvación,
envió a Sus apóstoles y siervos a testificarlo y a declararlo.
Ahora bien,
ellos fueron a predicar y a testificar lo que "`era desde el principio,`" es decir,
"`la vida eterna, que estaba con el Padre y que les fue manifestada.`"
Este es el mensaje que ellos oyeron de Él y fueron a declarar a otros: "`Dios es luz,
y no hay ningunas tinieblas en él.`" Esta Palabra de fe,
esta Palabra que era desde el principio, esta Palabra que reconcilia el alma con Dios,
ellos la predicaron como "`cerca, en el corazón y en la boca.`"
La intención de su predicación y testimonio era volver a los hombres a Ella,
de las tinieblas internas a la luz interna, del poder de Satanás en el interior,
al poder de Dios en el interior.
Ver Hechos 26:18.

Aquí, al ser vueltos a la luz, esta les pone al descubierto las tinieblas,
el estado perdido, el cautiverio, las ataduras, la miseria del alma,
y le permite al alma anhelar al Salvador.
Y no sólo esto, la luz también muestra al Salvador, a quien ella hace que el alma anhele,
y en la espera del Salvador en la luz que es de Él,
también da participación de Su salvación.

Y entonces, habiéndonos demostrado Dios esta luz, habiéndonos mostrado lo que es,
y habiéndonos dado participación de la preciosa virtud de ella,
¿cómo podemos llamarla algo menos que una medida de Cristo, una medida de Su Espíritu,
la Semilla del reino, la levadura celestial,
etc.? Pues sabemos y experimentamos con toda seguridad,
que ella es lo que Cristo describió en sus parábolas.
También sabemos que aquello en el hombre que se ofende
con nosotros por declarar estas cosas,
no es el verdadero nacimiento, sino el nacimiento de otra sabiduría,
el cual debe ser expulsado con su madre.
Ciertamente será un día feliz para ustedes,
si alguna vez llegan a experimentar la expulsión de dicho nacimiento.
Pero nunca lo experimentarán hasta que lleguen a conocer,
poseer y estar sujetos a Cristo en el interior,
al mandamiento puro de la Palabra de vida en el corazón, a la ley que sale de Sión,
y al testimonio y palabra del Señor provenientes de Jerusalén. Y cualquiera que no llegue
a experimentar la expulsión del nacimiento equivocado por medio del poder,
será expulsado junto con él.

En cuanto a la idea de que hay algunos destellos
de luz que permanecen en el hombre caído,
que lo instruyen con respecto a muchas cosas moralmente
buenas (tales como honrar a los padres,
tratar con justicia, hacer a los demás lo que queremos que nos hagan a nosotros, etc.),
y con esto se quiere decir que esta es una luz distinta
al Espíritu y naturaleza divina de Dios,
deseo que se pruebe tal idea a partir de las Escrituras.
Porque Adán tuvo que sufrir la muerte el mismo día que pecó,
y dicha muerte y maldición cayeron sobre su posteridad,
quienes están muertos en delitos y pecados,
pero la luz que pone al descubierto el mal y saca de él, es únicamente de Cristo.
Eso que manifiesta el pecado es Su luz.
Ahora,
yo leo en las Escrituras que la gracia que trae salvación
les ha aparecido a todos los hombres,
les enseña a los hombres a rechazar la impiedad y los deseos mundanos,
y les da fuerza para hacerlo.
Yo leo que es obra del Espíritu convencer de pecado,
que el Espíritu del Señor contendía contra el mundo
antiguo para sacarlos de sus malos caminos,
y que les dio a los judíos Su buen Espíritu para que los
instruyera (aunque ellos se rebelaron contra Él). Pero que
hay algunos destellos de luz separados del Espíritu de Cristo,
enseñándoles a los hombres caídos a hacer el bien,
y dándoles la fuerza correspondiente para que caminen en concordancia,
tal cosa no la leo en las Escrituras.

Dios prometió en el nuevo pacto que Él escribiría Sus leyes en el corazón,
y cualquier medida de Su ley escrita en el corazón del hombre,
es escrita únicamente por Él. Porque el hombre está muerto naturalmente a la ley de Dios,
y su ojo está cegado por el dios de este mundo.
Así entonces,
eso que abre el ojo del hombre para ver lo que dice la ley es la luz del Espíritu.
Porque la luz es la que pone de manifiesto todas las cosas (Efesios 5:13),
y lo que puede ser conocido de Dios en los gentiles,
les es manifestado por la luz de Dios en ellos.
(Romanos 1:19) Esta luz brilla en las tinieblas en
los hombres y sus tinieblas no pueden comprenderla,
pero la luz discierne y comprende las tinieblas y es capaz de sacar la mente de ellas.
Porque cuando la mente se sujeta a la luz (en la voluntad que la luz crea y engendra,
a través del poder eterno que viene con ella y está presente en ella),
puede ser liberada de las tinieblas.
Y dado que esta luz viene de Cristo (porque Él es la luz verdadera,
que alumbra a todo hombre que viene a este mundo; Juan 1:9, RVG),
revela y manifiesta a Cristo en Su naturaleza y Espíritu,
y conduce y guía a Él. Aquel que es conducido a Cristo en el Espíritu,
y nace de Él en el Espíritu,
no se pierde el beneficio ni la virtud de lo que Él hizo en el cuerpo de carne,
porque tal persona es reunida y hallada en lo que es de Él.

Entonces, es únicamente en esta luz y por esta luz,
que el alma recibe la naturaleza en la que la ley está cumplida,
y el acto de responder a la ley es sólo posible a través de la
renovación de la mente y del surgimiento de una nueva naturaleza,
cada medida de la cual es engendrada y mantenida por Cristo, el
poder de Dios.
Pero por medio de la vieja y corrupta naturaleza o mente,
ningún hombre puede hacer las cosas contenidas en la ley,
pues esta naturaleza es enemistad contra Dios y no se sujeta a Su santa ley,
ni tampoco puede.
Pero la ley es espiritual, santa, justa y buena,
convierte el alma y hace sabio al sencillo.
Esta obra se efectúa dondequiera que es escrita en
el corazón por el dedo del Espíritu de Dios.

Ahora bien, pensar que es posible estar, en algún sentido,
"`completo en Cristo`" cuando el corazón aún no está circuncidado ni sometido a Dios,
es un error peligroso.
Yo confieso: Que los pecados son perdonados sobre la base de la creencia verdadera;
que el alma entra en el pacto de vida y es aceptada por el Señor
cuando encuentra entrada en dicho pacto y camina en él;
que no hay condenación para los que están en Cristo, "`los que no caminan según la carne,
sino según el Espíritu.`"
Pero si se oye a la carne y se camina según sus deseos y pasiones,
¿acaso no hay condenación entonces?
¿Acaso no está la justificación en el pacto y de acuerdo con las leyes del pacto?
¡Ay, qué imaginan los hombres acerca de estas cosas!
Y así, en sus imaginaciones se justifican en aquello en lo que el Señor los condena,
y no experimentan el camino del pacto o la justificación de este.
Porque hay un nuevo pacto,
así como también uno antiguo (y el nuevo no es como el antiguo).
Hay un caminar con Dios en el nuevo pacto, donde cada paso en este, Su vida lo justifica,
y cada paso fuera de este, Su vida lo condena.
Pues el Mediador del nuevo pacto justifica según el nuevo pacto; nunca de otra manera.
De hecho, el camino de Dios es perfecto (el camino de vida, el camino de reconciliación,
el camino de redención),
y el alma es aceptada y justificada por el Señor únicamente en él.

[.alt]
==== Con Respecto al Camino de Vida Verdadero y Puro

Este ha sido el clamor de mi alma desde mi infancia, caminar en pos de la santidad,
en pos de la presencia del Señor, en pos de la unión con Él,
en pos de la naturaleza e imagen de Su Hijo,
en pos de la separación de lo que sea contrario a Él,
y ser levantado en el poder de Su vida.
¡Bendito sea el Señor que ha revelado lo que responde a mi clamor!
Pues en la medida que mi alma participa de eso,
es refrescada y satisfecha con la provisión de lo que ella tenía sed y clamaba.
Y ahora,
mi más ferviente deseo es que todo el que haya experimentado el verdadero clamor,
sea enseñado también por Dios, aprenda correctamente cómo esperar en Él,
cómo caminar humildemente y en temor delante de Él,
y que nada se interponga entre él y el clamor de su alma.
¡Sí,
que sea guiado por Él al disfrute y posesión de lo que el verdadero
nacimiento (que nace del Espíritu y es Espíritu) naturalmente anhela!

En realidad,
no hay otro camino a la vida y satisfacción que el de creer en
el poder y seguir el poder que resucitó a Cristo de los muertos,
ya que dicho poder hace la obra en todos los que son salvos.
Sentir este poder revelado en el interior, tener la mente vuelta a este poder,
seguir este poder en la obra y camino de regeneración,
es la forma de participar de su virtud y de experimentar la redención
que está en él y viene de él. El que es nacido del Espíritu,
tiene su ojo abierto y es diariamente ejercitado por Él, ese conoce al Espíritu,
conoce Sus agitaciones y movimientos,
y es enseñado por Dios a distinguirlos de las agitaciones
y movimientos del espíritu maligno.
De este modo el alma no apaga al Espíritu de Dios ni lo contrista cuando se mueve,
ni le da cabida al otro espíritu cuando este se mueve y seduce.

Porque el espíritu de engaño seduce y guía a los hombres, no tanto por reglas externas,
sino mediante la naturaleza interna maligna y la ley del pecado y muerte.
De igual manera,
el Espíritu de verdad conduce a la verdad mediante la novedad
y poder de Su propia vida revelada en el corazón,
mediante el instinto puro de la vida en el interior,
y por medio de la ley de Dios escrita en la naturaleza de la nueva criatura,
que está más cerca que las palabras externas.
Porque Dios borra en el corazón que le pertenece a Él lo que Satanás había escrito ahí,
y escribe con el dedo de Su Espíritu lo que Él quiere
que el nuevo nacimiento lea ahí. Efectivamente,
hay un reino de vida, de justicia, de verdadera paz y gozo (sí,
del poder y sabiduría santos del Altísimo),
para que Sus hijos (los nacidos de Su Espíritu y que brotan de la Semilla inmortal) lean.

¿Por qué se cierran los ojos de los hombres y se endurecen sus corazones contra la verdad?
¿Por qué claman por Cristo en palabras,
y protestan contra Su vida y poder donde esto es revelado?
¿Es esto honrar al Hijo?
Los que son culpables de esto, ¿pueden evitar perecer en el camino de su viaje interior?
¡Oh,
cuántos deben perecer por resistir el poder de la verdad
y el precioso testimonio del Santo Espíritu de Dios,
que busca rescatar de lo que cautiva y destruye!

Cristo vino a destruir el pecado, tras haber recibido poder de Su Padre para hacerlo.
Él sabe que este poder es de una naturaleza destructora,
y que también destruirá el alma si el pecado no es consumido
y destruido en ella mediante el poder de la vida.
¡Oh, cuán preciosa es para nosotros la visitación de la verdad, luz,
vida y poder que escudriña y descubre el pecado desde la misma raíz, y lo destruye! ¡Oh,
cuán gloriosa es esa hacha del Señor Jesucristo que
está puesta a la raíz del árbol corrupto,
y que diariamente lo está cortando y reduciendo para
que no pueda obstaculizar más el terreno!
Porque el corazón fue creado para que se convirtiera en buena tierra,
en tierra santificada, en tierra circuncidada por el Señor,
y para que produjera buen fruto,
buenas uvas y un buen incremento de la buena Semilla de vida para el buen Labrador,
quien es digno de cosechar la gracia y misericordia, amor y bondad, sabiduría y poder,
que Él siembra plena y diariamente en los espíritus de los Suyos.
¡Gloria a Su nombre por siempre, quien ha exaltado,
exalta y exaltará lo que los diversos tipos de profesantes
altivos pisotean y desprecian en su propia sabiduría!

[.alt]
==== Con Respecto al Perfeccionamiento de la Obra de Dios en el Corazón

¿No es la voluntad de Dios que Su pueblo y Sus hijos
sean enteramente santificados en cuerpo,
alma y espíritu?
(1 Tesalonicenses 5:23) ¿No es la voluntad de Cristo que Sus discípulos sean perfectos,
tal como el Padre de ellos en el cielo es perfecto?
¿Acaso no les ordenó que oraran: "`Venga tu reino; hágase tu voluntad, como en el cielo,
así también en la tierra`"? ¿Acaso no quería que ellos creyeran que esta
sería realmente hecha en la tierra como es hecha en el cielo?
¿Acaso no "`se purifica a sí mismo así como Él es puro`" el que tiene la esperanza verdadera,
pura y viva (que ancla dentro del velo)?

¿No es esta la manera de disfrutar las promesas de la santa presencia
de Dios (quien habita en un pueblo que está limpio y santificado):
"`limpiémonos de toda contaminación de carne y de espíritu,
perfeccionando la santidad en el temor de Dios`"?
(2 Corintios 7:1) ¿Habitará Dios en un templo profano?
¿Habitará Él donde habita el pecado?
En realidad,
Él puede hacerlo en el momento que sean tiernos y
estén verdaderamente ablandados delante de Él;
puede ser para ellos como un caminante que se detiene por una noche,
pero que no hará morada ahí, no caminará ahí, no cenará ahí,
ni les dará de cenar ahí con Él.

¿No ha recibido Cristo de parte de Su Padre todo el poder,
tanto en el cielo como en la tierra?
¿No es este el fin de recibir dicho poder: derribar los enemigos del alma,
y purificar y santificar Su iglesia para que no tenga mancha ni arruga,
ni cosa semejante?
¿No es Cristo el Capitán de nuestra salvación,
ungido para pelear las batallas del Señor? ¿Dónde ocurre la pelea?
¿Dónde se encuentra al hombre fuerte, para expulsarlo, despojarlo de sus bienes,
vaciar su casa de él y de todo lo que le pertenece?
¿Acaso no es Cristo el autor de la fe y el consumador de ella?
¿No lleva Él adelante la obra de fe con poder?
¿Qué es la obra de fe?
¿No es pelear y vencer el pecado?
¿No es ser demasiado fuerte para el enemigo y todas sus armas?
¿No hay preparada una armadura completa de luz,
vida y salvación? ¿Para qué está preparada?
¿No es para que los hijos de luz estén completamente armados con ella?
¿Hubo alguno que nunca estuviera completamente armado con ella?
Los que están armados con ella, ¿le temen al enemigo, a su poder, a sus trampas,
a sus engaños? ¿O son más bien ellos audaces en la fe,
al seguir Al que cabalga delante de ellos venciendo y para vencer?

¡Ojalá fueran abiertos los ojos de los hombres por el Señor!
Entonces verían la gloria de la verdad en la luz
pura que brilla desde la montaña santa de Dios.
Entonces las doctrinas oscuras de la noche pasarían (que tienden al deshonor de Cristo,
Su poder y Su amor, y a la defensa del reino del enemigo),
y no prevalecerían más en los corazones de quienes verdaderamente
temen al Señor. Entonces esperarían quietamente Su salvación,
para ser hechos libres de la ley del pecado y muerte,
mediante la ley del Espíritu de vida en Cristo Jesús, y no estar siempre sujetos a ella.
Porque todos aquellos a quienes el Hijo hace libres, son verdaderamente libres;
y al ser hechos libres por Él, pueden servirle a Dios en libertad de espíritu, sin temor,
en santidad y justicia delante de Él, todos los días de sus vidas.
Entonces conocerían verdaderamente el poder y la virtud del nuevo pacto,
y la defensa que hay en él, donde el ala del Todopoderoso cubre,
y Su salvación (revelada ahí) es experimentada como
un muro y bastión suficiente contra el enemigo.

[.alt]
==== Con Respecto al Verdadero Conocimiento de Cristo

Mientras las personas estaban a la expectativa y meditaban
en sus corazones con respecto a Juan el Bautista,
si era o no el Cristo,
Juan respondió al asunto y les dijo cómo podrían discernir y conocer al verdadero Cristo.
Dijo que no era el que bautizaba con agua,
sino el que "`bautiza en Espíritu Santo y fuego.`"
Que era Aquel cuyo "`aventador está en su mano,`" con el que "`limpiará su era;
y recogerá su trigo en el granero,
y quemará la paja en fuego que nunca se apagará.`" Entonces,
el que conoce Al que hace esta obra y Lo experimenta haciéndola en él,
¿acaso no conoce a Cristo?
¿No es precioso ser bautizado por Aquel a quien Dios ha designado para bautizar?
¡Oh, el aventador, el precioso aventador,
con el que Cristo (quien es poder y sabiduría de Dios) separa lo precioso de lo vil,
divide el trigo de la paja,
recoge el trigo en el tesoro precioso y deja salir el inextinguible fuego sobre la paja!

"`Nuestro Dios es fuego consumidor,`" dice el apóstol.
¿Y qué quema Él como fuego consumidor?
¿Acaso no quema la naturaleza que es paja, terrenal y escoria, en hombres y mujeres?
Si ustedes llevaran paja al fuego, ¿no la quemaría el fuego?
Y mientras esta arde y se consume, entonces lo que es puro,
lo que es nacido de Dios puede morar y deleitarse
en el fuego devorador y en las llamas eternas.
Porque Dios no es terrible para el hijo que es nacido de Él,
para el que es engendrado a la imagen y Espíritu de Su Hijo.
Pero para la naturaleza transgresora, para la semilla del malhechor,
para el que está naturalmente inclinado a hacer el mal y todos los días hace mal,
para ese, Él es terrible para siempre.

[.alt]
==== Con Respecto a la Luz que Alumbra a Todo Hombre

[quote.scripture, , Juan 1:4-5]
____
En Él estaba la vida, y la vida era la Luz de los hombres.
La Luz brilla en las tinieblas, y las tinieblas no la comprendieron.
____

¿Qué son las tinieblas que no comprenden la luz?
¿No es el hombre en el estado no regenerado?
"`En otro tiempo erais tinieblas,`" dice el apóstol,
hablando de lo que habían sido ellos en el estado no regenerado.

Ahora,
le place al Señor que Su luz pura brille en esas tinieblas para sacar al hombre de ellas.
Porque a menos que la luz brille sobre el hombre en su estado oscuro,
jamás podría ser sacado de este.
El que se vuelve a la luz y la sigue, no puede permanecer en tinieblas,
sino que entra en lo que recoge la mente y la preserva fuera de ellas.

Pero, ¿de qué naturaleza es esta luz que brilla en el hombre en su estado de tinieblas?
Es de la naturaleza viva, es la luz que fluye de la vida, la luz que tiene vida en ella,
la vida de nuestro Señor Jesucristo, la Palabra eterna, la cual es la luz de los hombres.
El que llega al verdadero entendimiento puede distinguirla de todas las demás luces.

Hay una vasta diferencia entre esta luz y la razón y entendimiento del hombre.
Pues el hombre natural, con su entendimiento, está muerto,
pero esta luz está viva y opera poderosamente en el hombre,
según encuentra entrada y la mente de él se une a ella.
El que está muerto, en realidad no la conoce,
pero el que está vivo para Dios siente la virtud de ella.
Esta luz está por encima de todo conocimiento acumulado, cualquiera que sea,
y por encima de toda descripción de las cosas, cualquiera que sea.
Pues la luz es la cosa misma, la sustancia misma, es decir,
la sustancia de la naturaleza de Aquel de quien ella fluye.
Un hombre puede obtener una idea de dicha luz en su mente
y retener el conocimiento muerto de dicha idea.
Sí, tal idea puede rápidamente convertirse en muerte en el hombre,
pero el que habita en la cosa misma, conoce y habita en lo que nunca muere.

[.alt]
==== Interrogantes con Respecto al Tiempo y la Obra de Reforma

[.discourse-part]
_Interrogante 1:_
¿Qué implicó el tiempo de reforma y sustancia (mencionado en Hebreos
9:10)? ¿Acaso no implicó la introducción del evangelio,
la llegada del día del Espíritu y poder de Cristo,
del día de Su renovación y reforma internas,
del día que toma Su aventador en Su mano para limpiar Su era,
del día que pone Su hacha al pie del árbol corrupto para poder
destruir las obras del maligno en los corazones de los hombres,
derribando y arrancando lo que Su Padre celestial no había plantado ahí?
Cuando Cristo viene como fuego purificador y como jabón de lavadores,
para purificar a los hijos de Leví tal como es purificado el oro y la plata,
para que puedan ofrecerle al Señor una ofrenda en justicia,
¿no es este el tiempo de reforma?

[.discourse-part]
_Interrogante 2:_ ¿Quién es el reformador?
¿No es el Señor Jesucristo?
¿No crea Él de nuevo?
¿No borra la vieja imagen y forma una nueva masa?
Porque si una persona está en Cristo, allí hay renovación, hay un nuevo edificio; sí,
allí las cosas viejas pasaron y no hay nada en ella sino lo que es nuevo.
Él es fiel (en toda Su casa) para juzgar, condenar, crucificar, someter,
destruir internamente cualquier cosa contraria a la naturaleza y Espíritu de Su Padre,
y para formar y edificar los espíritus de los Suyos en lo que es nuevo y puro.

[.discourse-part]
_Interrogante 3:_ ¿Cómo o por medio de qué reforma Cristo?
¿No es por medio de Su Espíritu y poder, por medio de Su luz, vida y virtud?
Porque nada puede cambiar ni reformar el corazón,
excepto lo que es más poderoso que el que lo corrompió.

[.discourse-part]
_Interrogante 4:_ ¿Dónde reforma Cristo y crea de nuevo?
¿No es en el nuevo pacto; en la fe y obediencia a este pacto?
¿Acaso no rompe y anula las leyes del antiguo pacto
e invalida el pacto del infierno y muerte,
mediante las leyes del nuevo pacto?
¿No hace un pacto eterno de vida y paz, es decir, un acuerdo santo,
puro y vivo entre Dios Su Padre y las almas que Le pertenecen?
Así, mediante Su luz vence las tinieblas, mediante Su vida vence la muerte,
y mediante Su naturaleza y Espíritu puros vence (encadena,
somete y destruye) lo que es impuro, al romper la atadura del pecado e iniquidad,
y al dejar que el oprimido quede libre de la sujeción a este.
De esta manera se manifiesta a Sí mismo como el Salvador,
quebrando el yugo del opresor por medio de Su santa unción. (Isaías 10:27)

[.discourse-part]
_Interrogante 5:_ ¿A quiénes reforma Cristo?
¿No es a los que toman Su yugo sobre ellos y aprenden de Él? ¿No es a
los que se vuelven a la luz de Su Espíritu internamente manifestado,
a los que se vuelven de las tinieblas y no caminan más en ellas,
sino que caminan en Su luz pura?
Los que reconocen Su aparición interna en sus corazones
y se vuelven (de la enemistad ahí) a Él,
recibiendo Su luz, Su ley, Su vida y Su Espíritu,
estos son diariamente ejercitados y reformados en sus corazones
por Él. Pero si alguno no recibe Su luz,
ni Su vida, ni a Su Espíritu en el interior, el tal no es de Él,
y puede reformarse a sí mismo tanto como pueda,
pero aun así no experimenta el día de la verdadera reforma.

[.discourse-part]
_Interrogante 6:_ ¿Cómo deben caminar los que Cristo ha comenzado a reformar?
¿No es en esa luz, en ese Espíritu, en ese pacto, en esa gracia,
en la que y por medio de la que los ha reformado en alguna medida?
¿No es en la novedad del Espíritu y en la ley del Espíritu de vida?
Aquí Cristo caminó delante del Padre y aquí nosotros
debemos hacerlo también. (1 Juan 2:6) De hecho,
no hay manera de agradar al Padre, ni a Cristo nuestro Señor y Maestro,
fuera de la virtud, vida y novedad de Su propio Espíritu.

[.discourse-part]
_Interrogante 7:_ ¿Acaso no da Cristo de Su gracia en el evangelio?
¿No obra Su gracia un glorioso cambio?
¿No aparece Cristo gloriosamente en los corazones de Su pueblo,
y en las asambleas de los que se reúnen en Su nombre
y esperan en Él en lo que es puro y vivo?

[.discourse-part]
_Interrogante 8:_
¿Acaso no fue puesta de manifiesto esta gloria en los días de los apóstoles?
¿No había sobre todos ellos entonces, abundante gracia?
(Me refiero,
sobre los que recibieron y guardaron el amor de la verdad.) ¿No
experimentaron la paz que sobrepasa el entendimiento del hombre?
¿Acaso no habían recibido ellos el entendimiento santo y espiritual del que es verdadero,
y no estaban ellos en el que es verdadero?
¿No conocían ellos la victoria y dominio sobre el pecado y la muerte?

[.discourse-part]
_Interrogante 9:_ ¿No fue eclipsada esta gloria y no vino sobre ella una gran oscuridad,
escondiéndola de los hijos de los hombres (por edades y generaciones),
para que no experimentaran al verdadero Espíritu, la verdadera luz, la verdadera vida,
el pacto eterno, el evangelio santo, la verdadera iglesia, el hijo varón,
etc.? ¿No han sido escondidas estas cosas, junto con muchos otros misterios celestiales,
de los ojos del hombre?
¿Y qué se ha levantado desde que estas cosas fueron escondidas?
¿Acaso no han tomado su lugar las sombras de la noche
y se han extendido sobre el estado cristiano,
en lugar de la luz del día? ¿No se ha levantado el
anticristo y aparecido una falsa iglesia?
¿No se ha despreciado, empujado hacia abajo,
restringido y perseguido lo que es tierno y engendrado por Dios,
mientras una falsa devoción y adoración se han establecido en lugar de la verdadera?

Ahora bien,
¿quién es sabio para entender la aparición del Señor y el principio de estas cosas,
lo cual es contrario a la sabiduría del hombre?
El que quiera discernirlas debe dejar de seguir su propio espíritu,
naturaleza y sabiduría en sí mismo,
y entrar en el sentido y guía de Aquel que da la verdadera vista.
La aparición del Señor es interna y espiritual,
y el que la discierne debe tener un ojo interno y espiritual.
En el pasado los burladores y mofadores decían, "`¿Dónde está la promesa de Su venida?
Porque todas las cosas siguen como eran desde el principio.`"
El mismo espíritu dice lo mismo hoy, sin embargo, para el ojo que el Señor ha abierto,
Él ya ha venido interna y espiritualmente, en Su propia, pura y eterna vida y poder.
Ciertamente, los efectos preciosos de Su venida se manifiestan en muchos corazones;
¡bendito sea Su nombre!
No obstante, Él aparecerá aún más en gloria y resplandor puro, y por tanto,
nosotros esperamos más de Su aparición,
tanto en nuestros corazones como en los corazones de los hijos de los hombres.
Nos hemos reunido con nuestro Amado, porque nuestro Dios a quien hemos esperado,
ha aparecido.
El Sol de Justicia se ha levantado con salvación bajo Sus alas,
y los que hemos sentido virtud y salvación de Él,
no podemos sino regocijarnos y testificar de Su salvación.

¡Oh, que todo el que ama al Señor Jesucristo con alguna medida de sinceridad,
conozca el camino del evangelio, el cual está en el Espíritu, luz,
vida y poder que son eternos, es decir,
en la gracia y verdad que están en Él! Porque Su reino,
que es espiritual y no de este mundo,
no puede ser sacudido por este mundo (ni Su Monte Sión ser removido).
Todo lo contrario,
Su reino es capaz de conmover todas las naciones y reinos que no honran a Su Hijo,
sino que se oponen a Él. (Salmo 2:12) ¡Bienaventurados los que
se vuelven a la luz de Su Espíritu y allí lo honran y obedecen!

[.alt]
==== Algunos Interrogantes Serios con Respecto al Espíritu de Cristo

[.discourse-part]
_Interrogante 1:_ ¿Conocen ustedes al Espíritu Santo del Padre?
Ustedes han leído algo con respecto a Él y tenido
comprensiones en sus mentes acerca de Él,
pero,
¿conocen verdaderamente lo que es Él por sus apariciones
y operaciones internas en sus propios corazones?

[.discourse-part]
_Interrogante 2:_ ¿Han recibido al Espíritu Santo de Dios en sus corazones?
¿Han dejado entrar al Espíritu de Cristo cuando Él
ha tocado la puerta de sus corazones y lo han recibido?
Porque el que es un hijo verdadero,
naturalmente respira y clama por el Espíritu del Padre,
y el Padre también les da naturalmente Su Espíritu
a los que verdadera y correctamente se lo piden.
(Lucas 11:13)

[.discourse-part]
_Interrogante 3:_ ¿Habita el Espíritu de Cristo en ustedes?
¿El Hombre más fuerte ha echado de ustedes al hombre fuerte,
ha tomado posesión en sus corazones y mora ahí? Entonces pueden decir, verdaderamente,
que son edificados por Él '`para morada de Dios en el Espíritu.`'

[.discourse-part]
_Interrogante 4:_
¿Los guía el Espíritu de Dios a toda la verdad que
necesitan conocer y en la que deben caminar?
¿Son verdaderos hijos,
que dependen del Espíritu del Padre y son guiados por Él? ¿Son
incapaces de ver su camino a menos que Él se los dé a conocer?
¿Son seguidores del Cordero sin mancha, en el mismo Espíritu en el que Él caminó?

[.discourse-part]
_Interrogante 5:_ ¿Viven ustedes en el Espíritu?
¿Sienten al Espíritu de Dios como una fuente de vida,
de la que diariamente brota vida en ustedes?
¿Experimentan esta escritura cumplida en ustedes:
"`El que cree en Mí de su interior correrán ríos
de agua viva`"? ¿Han recibido de Cristo el agua viva?
¿Se ha convertido esa agua viva en un pozo de vida en ustedes?

[.discourse-part]
_Interrogante 6:_ ¿Caminan ustedes en el Espíritu,
en la novedad de vida que brota de Él en sus corazones?
¿Conocen la diferencia entre caminar en el arcaísmo de la letra y la novedad del Espíritu?

[.discourse-part]
_Interrogante 7:_ ¿Han aprendido alguna vez del Padre a conocer a Cristo?
¿Han aprendido alguna vez de Cristo a conocer al Padre?
¿Ha revelado efectivamente el Padre al Hijo en ustedes
y el Hijo efectivamente al Padre en ustedes,
o todavía están sólo en las ideas secas y muertas,
o entendimientos estériles acerca de estas cosas?

[.discourse-part]
_Interrogante 8:_ ¿Saben ustedes cómo mata la letra y cómo vivifica y da vida el Espíritu?
¿Han sido vivificados por el Espíritu y nacido del agua y del Espíritu celestiales,
y así llegado a ser espirituales, tal como testifican las Escrituras:
"`El que es nacido del Espíritu, espíritu es`"?

[.discourse-part]
_Interrogante 9:_ ¿Están ustedes bajo la ministración del Espíritu?
¿Saben qué es la ministración del Espíritu,
o sólo conocen lo que dice la letra con respecto a la ministración del Espíritu,
mientras permanecen completamente ignorantes de la ministración misma?

[.discourse-part]
_Interrogante 10:_
¿Saben ustedes lo que significa la ley del Espíritu de vida
en Cristo Jesús? ¿Han recibido alguna vez esta ley,
la ley del nuevo pacto,
la santa ley de vida escrita en los corazones por el dedo del Espíritu de Dios?
Porque el mismo Espíritu que escribió la ley de la letra en tablas de piedra,
escribe la ley del Espíritu en las tablas de carne del corazón.

[.discourse-part]
_Interrogante 11:_ ¿Siguen ustedes contristando al Espíritu Santo, o apagándolo,
o despreciando Su profecía en sus corazones?
Pues Cristo es rey, sacerdote y profeta, y ministra en Su santuario,
en Su templo (el cual es el corazón santo y renovado), en y mediante Su Espíritu.

[.discourse-part]
_Interrogante 12:_ ¿Saben ustedes qué es la unción? ¿Están ungidos con ella?
¿Se encuentran en ella todas sus habilidades,
hasta el punto de que son diariamente conscientes
de que no pueden hacer nada por sí mismos,
sino que deben hallar a Dios obrando en ustedes tanto el
querer como el hacer lo que es correcto a Sus ojos,
por Su buena voluntad?

[.discourse-part]
_Interrogante 13:_ ¿Comenzó la religión de ustedes en el Espíritu,
en la ministración viva del nuevo pacto?
¿Comenzó el conocimiento de ustedes al experimentar
a Dios abriendo sus corazones por medio de Su Espíritu,
y dándoles entendimiento por medio del cual pueden conocerlo?
¿Comenzó la fe de ustedes en Su poder y permanece en el mismo poder hasta hoy?

[.discourse-part]
_Interrogante 14:_
¿Descansa la adoración de ustedes en el Espíritu
y en la vida interior de la verdad en sus corazones?
¿Son ustedes los adoradores que el Padre ha buscado y ha formado,
o son adoradores por cuenta propia o por la de otros hombres?
¿Se mantienen ustedes dentro de los límites de la adoración
viva y espiritual y no transgreden la ley de esta?

¡Oh,
quiénes querrían estar equivocados y engañados acerca
de cosas tan importantes como estas,
de tan grande necesidad y preocupación! ¡Quiénes querrían perder al Espíritu de Dios,
la ley y el pacto de vida en Cristo Jesús,
y sólo estar en un sueño con respecto a estas cosas, sin el conocimiento,
posesión y disfrute verdadero y evidente de ellas!

[.alt]
==== Con Respecto al Camino de Santidad o al Camino de Vida

Cristo es el camino, el único camino al Padre; no hay otro.
Ahora, todo el que quiera conocer verdaderamente a Cristo e ir a Cristo,
debe aprender del Padre.
Está escrito en los profetas:
"`Y todos tus hijos serán enseñados por Jehová;`" "`todo aquel que oyó al Padre,
y aprendió de Él, viene a Mí,`" dijo Cristo.
Aquí hay dos cosas necesarias para todo el que quiera venir a Cristo: Una, oír al Padre;
dos, aprender lo que Él enseña. Porque aunque un hombre oiga la voz del Padre,
si no aprende ni guarda la instrucción de vida recibida de Él,
puede ser apartado antes de llegar al Hijo.
Pero aquel cuyos oídos están abiertos para oír la voz y experimenta la
instrucción del Padre de ir a Aquel en quien Él ha colocado la vida,
a este el Espíritu del Padre secretamente persuade en lo íntimo de su mente y espíritu,
para alejarlo de lo que está realmente muerto y acercarlo
a lo que está verdaderamente vivo.

Ahora,
cuando un hombre es llevado al Hijo (en quien el Padre ha colocado la plenitud de vida),
lo experimentará como el camino al Padre y cada día le enseñará del Padre.
Aquí es experimentado el estado de la verdadera sujeción al Hijo,
a quien el alma debe oír (y de quien debe aprender) en todas las cosas.
Porque aquí el Hijo pone al descubierto la oscuridad interna en la mente del hombre,
y derriba en él lo que es contrario a Dios,
al tener la cruz diaria lista para eso que debe ser crucificado en él,
mediante la cual morirá diariamente a sí mismo.
Y en la medida que muera a sí mismo, Cristo se revelará más y más en él,
y sentirá la Semilla pura de vida brotando cada vez más en él,
viviendo en él y él en Ella.
Y, en y a través de esto,
llegará más y más a la unión y comunión con el Padre de los espíritus,
y con todo el cuerpo vivo de Su iglesia y pueblo.

Aprender del Padre a ir al Hijo, aprender del Hijo a conocer al Padre;
caminar en la novedad del Espíritu delante de Él,
y no caminar en el conocimiento arcaico, ni muerto, ni en el entendimiento carnal;
estos son grandes misterios.
Nadie puede aprender tales cosas mediante una concepción ni comprensión literal de ellas,
sólo es posible en la medida que la persona es vivificada,
y su mente y entendimiento abiertos y mantenidos así por el Señor. Por lo tanto,
esta es la gran inteligencia y verdadera sabiduría: Conocer al Pastor,
Su voz y Su manera de aparecer.
Y la forma y manera de Su aparición es visitando
y tocando el verdadero nacimiento en uno,
abriéndolo por Su poder y dándole la capacidad de ver, oír y entender.
Y de esta manera, también guarda el alma de la naturaleza,
sabiduría y espíritu contrario en todos los hombres.

[.alt]
==== Con Respecto a la Separación del Espíritu y Caminos del Mundo

Es necesario que aquellos que quieran ser del pueblo del Señor, se separen del espíritu,
caminos y adoraciones del mundo.
Los judíos externos debían ser un pueblo separado
de todos los demás pueblos (de sus dioses,
de sus adoraciones),
si querían disfrutar el favor de Dios y las bendiciones de la buena tierra.
Dios los había separado de todas las otras naciones,
y ellos no debían mezclarse con ellas, ni en su adoración, ni por matrimonio, etc.
Así también los judíos internos,
que son la reunión de los adoradores espirituales de Dios de toda nación, parentesco,
lengua y pueblo, deben ser un pueblo separado y santo para el Señor.

Porque cuando Dios desechó a los judíos, Él buscó adoradores en lugar de ellos, es decir,
buscó una nación espiritual y un pueblo santo de judíos internos,
en lugar de aquel pueblo externo,
de aquel lugar externo de adoración y de aquella tierra externa que Él había desechado.
Ahora, aquellos a quienes Dios busca que sean los adoradores nuevos,
internos y espirituales, en lugar de los literales y externos,
deben salir de todos los otros caminos y reuniones sobre muchas montañas,
y entrar a la montaña de la casa del Señor y al lugar
de Su adoración. Es un mandamiento explícito:
"`Salid de en medio de ellos, y apartaos, dice el Señor, y no toquéis lo inmundo;
y yo os recibiré`" (2 Corintios 6:17).

Los cristianos primitivos debían separarse tanto
de los paganos como de los judíos (es decir,
de sus templos, sacerdotes y ordenanzas que alguna vez fueron de Dios),
si iban a ser verdaderos adoradores bajo el evangelio, los adoradores que Dios busca.
Y ahora, después de la corrupción y oscuridad anticristiana,
los cristianos deben salir de Babilonia, esto es,
de todas las formas de religión y estructuras sin vida ni poder,
si quieren ser hallados adoradores en el día de la
restauración. Porque Babilonia es la ciudad de confusión,
la cual está edificada, permanece y practica sin el orden y unidad del Espíritu.
El mandamiento de salir de Babilonia (es decir,
separarse de toda forma y adoración anticristiana) es tan explícito
como la orden a los primeros cristianos de separarse de los paganos
y los judíos. Porque no hay verdadera adoración delante de Dios,
excepto en el verdadero camino de separación de todos los falsos adoradores,
que adoran en formas y apariencias de piedad sin vida ni poder.

¡Oh,
bendito el que es separado por el Señor de todo lo que no es de
Él! Pero cuando alguien que no conoce al Espíritu busca separarse,
este se diferencia de otros únicamente en la forma y apariencia externa de piedad,
pero sigue siendo uno en naturaleza y fundamento con aquellos de quienes se separa.
Por lo tanto,
los católicos y todos los profesantes cristianos que no experimentan al verdadero Espíritu,
poder, ni vida, siguen siendo uno en su naturaleza y fundamento,
sin importar cuán grandes parezcan sus diferencias externas.
Aquellos que se separan más y más (es decir, en la mayor medida, externamente hablando),
al no ser separados por el Señor de esa naturaleza
y espíritu en el que se aloja la enemistad,
todavía son habitantes de una misma ciudad (pues la ciudad de Babilonia es muy grande).
Permanecen hijas de una y misma madre, de la sabiduría que es de abajo,
cuya exaltación más elevada está muy por debajo de la naturaleza
y verdadera excelencia de la sabiduría pura y celestial.

¡Oh, bendita la religión, la adoración, la separación, el temor del Altísimo Dios, la fe,
el conocimiento, que comienzan en el Espíritu y poder (es decir,
en la evidencia y demostración del propio Espíritu de Dios),
y están y permanecen en Este!
Porque aquí los hijos de luz se distinguen y se mantienen
diferentes (mediante el Todopoderoso Dios,
quien ha hecho la diferencia) de todos los hijos de las tinieblas.
