== Capítulo 13. Las Enseñanzas de Dios y la Ley de Cristo

=== Prefacio

Cristo, quien vino del Padre y conocía el camino de la verdad y vida eterna,
y debía guiar a los hombres al Padre (al ser el único camino a Él),
predicó el reino y mandó a los hombres a buscar el reino.
Él les enseñó e instruyó con muchas parábolas con respecto a este,
y les indicó dónde y cómo encontrarlo.

Los apóstoles (que sucedieron a Cristo en el mismo Espíritu y poder
en el que Él ministró) también predicaron del mismo reino,
declarando y describiendo qué era y en qué consistía, a saber, no en palabras,
sino en poder, es decir, en el poder que sacude todo lo que debe ser sacudido,
pero que él mismo no puede ser sacudido.
(1 Corintios 4:20;
Hebreos 12:28) Predicaron que el reino de Dios tampoco
era comida ni bebida (o ninguna cosa externa),
sino justicia, paz y gozo en el Espíritu Santo.
(Romanos 14:17) En verdad, los apóstoles no predicaron en vano,
porque en muchos la vida fue internamente revelada, el poder fue internamente revelado,
el reino fue internamente revelado, y la justicia,
paz y gozo de este fueron experimentados.
Pues los que verdaderamente creyeron y obedecieron el evangelio,
recibieron el reino que no puede ser conmovido, y les fue ministrada una entrada,
en concordancia con su diligencia y vigilancia en la verdad.

Pero después, una gran oscuridad vino sobre el mundo,
por lo que este glorioso reino fue nuevamente velado,
y el reino de las tinieblas y engaño se extendió sobre la profesión del cristianismo.
En ese tiempo,
los hombres fueron cautivados por los conceptos y el conocimiento
externo en lugar de la vida y verdad misma,
en donde el reino y el poder permanecen.

Pero, ¡bendito sea el Señor!
La luz de vida brilla de nuevo en y sobre las tinieblas, el reino es recibido de nuevo,
y la entrada a este es conocida de nuevo.
Y ahora, a partir de lo que se ha visto y oído (y en alguna medida disfrutado y poseído),
un testimonio fiel ha sido dado.
¡Benditos los que oyen el sonido alegre,
porque es nada menos que el sonido de la vida misma, del poder mismo,
del evangelio mismo, del Espíritu mismo, manifestándose y hablando a través de vasijas,
según Su beneplácito!

Ahora bien, los que reciben esta luz, de la cual se testifica, reciben a Cristo,
pero los que la desprecian y rechazan, lo rechazan a Él,
tal como será hecho manifiesto en el día del Señor. Pues esta dispensación es, de hecho,
más preciosa, gloriosa y viva,
al ser la dispensación de la Semilla y del poder de vida mismo.
Mediante esta Semilla, Dios traslada de las tinieblas y sus regiones,
al reino de Su amado Hijo y a Su gloriosa imagen.
Este, lectores, es el objetivo de mi declaración de las cosas que siguen,
no sólo para que tengan conceptos acerca de estas, sino para que puedan, en verdad,
llegar a ser partícipes de la cosa misma.

=== Con Respecto a las Enseñanzas de Dios

Cristo dijo: "`Escrito está en los profetas: Y serán todos enseñados por Dios.
Así que, todo aquel que oyó al Padre, y aprendió de él,
viene a mí`" (Juan 6:45). Pues los profetas habían dicho:
"`Y todos tus hijos serán enseñados por Jehová,`" y "`todos me conocerán,
desde el menor hasta el mayor de ellos.`"

Ahora,
¿de quién son los hijos que "`serán todos enseñados por Dios`"? ¿Quiénes son
"`todos los que conocerán`" al Señor mediante las enseñanzas de Su Espíritu,
"`desde el menor hasta el mayor`"? ¿No son los hijos de la mujer libre,
los hijos de la Jerusalén que es de arriba,
la cual es madre de todos los que verdaderamente viven?
(Gálatas 4:26) Ahora bien, todos los hijos de ella son engendrados por el Padre de vida,
y Él se encarga de enseñarles el conocimiento verdadero, puro, celestial y vivo.
Estos en verdad conocen al Señor, al ser enseñados por la unción a conocerlo,
y en verdad conocen al Hijo, al serles revelado por el Padre.
Pues "`nadie conoce al Hijo, sino el Padre, ni al Padre conoce alguno, sino el Hijo,
y aquel a quien el Hijo lo quiera revelar.`"
(Mateo 11:27) "`Porque no te lo reveló carne ni sangre,
sino mi Padre que está en los cielos,`" le dijo Cristo a Pedro.
(Mateo 16:17) Y "`le agradó a Dios revelar a su Hijo en mí,`" dijo Pablo.
(Gálatas 1:15-16) ¿Cómo predicó Pablo a Cristo entre los gentiles?
¿No lo predicó como un misterio escondido desde los siglos y edades,
y que nadie más sino el Padre podía revelar y hacer manifiesto?
Y cuando Él es conocido y hecho manifiesto, ¿acaso no es conocido dentro,
revelado dentro y hecho manifiesto dentro?
(Colosenses 1:26-27; 1 Juan 1:2) Noten las palabras de Juan: "`La vida fue manifestada.`"
Ellos llegaron a conocer a Cristo de esta manera,
y si deseaban llevar a otros al conocimiento de Cristo,
debían llevarlos a la manifestación de la misma vida,
y mostrarles esa vida eterna que estaba con el Padre y que se les había manifestado.

Entonces, para que pudieran hacer esto, debían predicarles la luz (el mensaje:
"`Dios es luz, y no hay ningunas tinieblas en él,`" 1 Juan 1:5),
y dirigirlos a la luz (Hechos 26:18),
la única en la que los hombres pueden ver y recibir la vida que es eterna.
Los hombres pueden conocer o comprender muchas cosas
con respecto al Mesías a partir de la letra,
pero sólo pueden conocer al Mesías mismo en la luz que brilla en sus corazones.
Esta es la luz a la que Él envió a Sus apóstoles
dirigir a los hombres y volver sus mentes.
Pues ellos debían dirigirlos a la Palabra dentro, a la luz dentro, a la vida dentro,
al Espíritu dentro, para buscar la manifestación de Dios dentro.
Y así, Pablo dirigió a los gentiles a buscar y encontrar a Dios cerca, y no lejos.
(Hechos 17:27) ¡Oh, es precioso encontrar y sentir a Dios cerca, a Cristo cerca,
en Su luz ver la luz, en Su vida sentir y disfrutar vida!
Porque aquí (en el lugar de tinieblas, en el lugar de pecado y muerte,
en el lugar donde yacen los chacales,
Isaías 35:7) se siente el poder redentor y la liberación del alma que es experimentada,
por aquellos que verdaderamente creen.

Los escribas y fariseos tenían un conocimiento de que el Mesías iba a venir,
pero ¿cómo llegaron a ese conocimiento?
Lo habían leído en la letra de las Escrituras.
Los profesantes de esta época tienen el conocimiento de que Cristo ha venido,
pero ¿cómo llegaron a este conocimiento?
Lo han leído en los escritos de los evangelistas y apóstoles.
Pero ¿quién ha creído hoy la noticia de vida,
y a quien se le revela hoy el brazo del Señor (el cual está extendido)?
¿Quién ha oído y aprendido del Padre a conocer al Hijo, y por tanto, a ir a Él, es decir,
ir a Él a partir de la revelación interior de Su Espíritu y del
conocimiento vivo en el interior que se recibe por este medio?
Todos, dice Cristo,
los que son enseñados por Dios (debido a lo que han
oído y aprendido del Padre) llegan al Hijo.
Ahora bien, todos los que son atraídos de esta manera, y por tanto llegan,
son recibidos por Cristo y se les da vida eterna.
Estos conocen al que les da vida y al que preserva y mantiene la vida en ellos.
Pero otros sólo tienen un conocimiento intelectual de Él,
y realmente no conocen al que es verdadero, ni están en el que es verdadero, es decir,
"`en su Hijo Jesucristo.
Este es el verdadero Dios, y la vida eterna.`"
(1 Juan 5:20)

Y así,
estos que son enseñados por Dios aprenden de Él a arrepentirse de las obras muertas,
y en efecto, se arrepienten.
Otros, sin embargo, por la dureza del corazón,
no disciernen cuáles son obras muertas y cuáles no,
en materia de adoración. Otros no conocen la verdadera
diferencia entre lo muerto y lo vivo,
pero la muerte (desconocida para ellos) vive y reina en
sus propios conocimientos y comprensiones de las cosas.
La muerte reina incluso en la fe de ellos, incluso en sus prácticas religiosas, sí,
en todo lo que creen y realizan para Dios.
Porque así como Pablo en otro tiempo se creía vivo sin la ley,
incluso cuando caminaba irreprensiblemente, en concordancia con la letra de la ley,
así también muchos están muertos hoy,
en medio de todos sus conocimientos y prácticas de la letra,
hasta que lleguen a la administración del Espíritu.
"`Porque la letra mata, mas el Espíritu vivifica`" (2 Corintios 3:6; ver versículo 3).

Esta es por tanto, la obra del verdadero ministerio:
Engendrar en el Espíritu y en la vida.
¡Pero cuán poco conocen los hombres lo que son las obras muertas,
y lo que es experimentar verdaderamente el arrepentimiento
de ellas! ¡Los hombres que están fuera del Espíritu,
luz y poder de Dios, están tan lejos de arrepentirse de ellas,
que ni siquiera las distinguen ni disciernen correctamente!
En cambio, creen vivo lo que realmente está muerto, encienden un fuego para sí mismos,
y se rodean de teas pensando que el calor de estas es el verdadero calor.
Ahora, si los hombres no han llegado al verdadero arrepentimiento de las obras muertas,
mucho menos han llegado a la verdadera fe hacia Dios.
Por tanto, todavía están en sus pecados,
todavía están fuera de Cristo al no haber aprendido del
Padre a ir a Él. Todavía están en el espíritu de Egipto,
en la sabiduría de Egipto,
y en eso mantienen su religión. Y cuando Dios aparezca en Su Espíritu y poder,
no será para ellos lo que ellos esperan,
sino que un terrible golpe saldrá de Él sobre todos sus caminos y adoraciones,
que son tan abominables para Dios como para ellos agradables.

¡Pero ay, para que sirven las palabras a ese oído,
a ese espíritu que es como el áspid sordo, que no oye la voz del encantador,
por más hábil que sea este! ¿Pudieron los doctos escribas
y fariseos oír la voz de Cristo en los días de Su carne?
No, no pudieron; no en ese espíritu de disputa.
¿Pueden los instruidos profesantes, que están en el mismo espíritu,
oír la voz del Espíritu de Cristo hoy?
No, no pueden.
Y si no pueden oír la voz del segundo Adán, la voz del Espíritu vivificador,
la voz de Aquel que le da vida al alma, ¿cómo pueden vivir?
Y si primero no reciben vida de Cristo,
¿cómo pueden llevar a cabo alguna acción viva para Dios?
¿Cómo pueden adorar en el Espíritu y en la verdad viva si no se
han reunido primero en el Espíritu y en la verdad viva?
¡Ojalá pudieran los hombres considerar correctamente estas cosas,
y esperar en el Señor el verdadero entendimiento de estas!
Porque sin el verdadero conocimiento de Dios y Cristo
(sin ese conocimiento que es vida eterna),
los hombres necesariamente deben perecer.
No puede ser de otra manera, pues sólo el verdadero conocimiento salva, y por lo tanto,
los que no lo tienen deben perecer.

=== Con Respecto a la Ley de Cristo

[.offset]
__"`Y las costas esperarán su ley.`"__ --Isaías 42:4

¿Cuál es esa ley que las costas debían y deben esperar?
¿No es la gracia y la verdad que vienen por medio de Jesucristo, es decir,
la gracia en lo íntimo, la verdad en lo íntimo?
La ley externa fue dada por medio de Moisés a los judíos externos,
pero la gracia y la verdad vienen por medio de Jesucristo.
Esta es la ley del judío interior, la que las costas de los gentiles debían esperar.

El apóstol sostiene que Cristo es el amo del alma (Él es el Pastor, Señor,
Rey y Obispo del alma), a quien todos le deben rendir cuentas.
Ahora,
¿de qué le deben rendir cuentas los hombres a Él? ¿No es de la gracia y verdad
que vienen por medio de Él? Si algún hombre las ha recibido y obedecido,
creyendo el sonido, relato y voz de estas, y por tanto, las ha amado y seguido,
¿no será dicho de él: "`Bien,
buen siervo y fiel`"? Pero si alguno ha descuidado
y menospreciado la gracia (al no aumentar el talento,
sino sus propias habilidades,
mientras que el talento de Dios yace envuelto en un pañuelo y escondido en la tierra),
¿no será juzgada esa persona como un siervo perezoso,
en lo que a aumentar el talento se refiere,
sin importar lo que haya hecho para mejorar sus propios dones y habilidades naturales?

Ahora, consideren lo siguiente: Si Cristo es un amo interno y espiritual,
¿qué es Su ley sino las enseñanzas internas de Su Espíritu?
Moisés escribió: "`Profeta de en medio de ti, como yo, te levantará Jehová tu Dios;
a él oiréis,`" y el que no Lo oiga (por muy seguro
y confiado que parezca en su estado presente),
será cortado y destruido de entre el pueblo de Dios.
(Deuteronomio 18:15-19, Hechos 3:23) Las palabras, la voz, los movimientos, las guías,
las persuasiones, los mandamientos de Su Espíritu,
¿no son estas cosas la ley para todos los que son espirituales?
Aquí está la gloria del gran Señor y Rey,
y del gran Sumo Sacerdote sobre la casa de Dios,
en que Él da preceptos según Su voluntad y beneplácito santos.
En efecto, todas Sus ovejas conocen Su voz y lo siguen,
y todos Sus hijos y siervos lo observan y obedecen.

"`Si vivimos por el Espíritu, andemos también por el Espíritu,`" dijo el santo apóstol.
Estos son los límites de los hijos del nuevo pacto.
Esta es la ley de vida (la ley del Espíritu de vida en Cristo Jesús),
la ley del nuevo pacto escrita en el corazón,
la cual nadie puede leer sino mediante el ojo nuevo.
Los hijos de la carne pueden leer la letra, tener entendimiento con respecto a la letra,
y reunir reglas y explicaciones de la letra,
pero sólo los hijos del nuevo pacto pueden leer la ley de
vida en el corazón. Esta ley es el camino de vida,
el camino de todos los que son renovados por el Espíritu de Dios,
la que el judío interno debe leer diligentemente,
en la que debe deleitarse y meditar de día y de noche.
Esta ley es luz, luz verdadera, luz pura, luz espiritual, sí,
la luz que es eterna y nunca cambia.
El mandamiento que viene de esta luz es una lámpara y los que lo reciben,
saben que es nada menos que vida eterna; porque realmente,
los mandamientos del Espíritu de Cristo se sienten así. Ahora, este mandamiento,
esta ley, esta luz, al principio brilla en las tinieblas,
pero después brilla más y más fuera de las tinieblas (según se cree, se recibe,
se obedece y se camina en ella) hasta que el día es perfecto.
(Ver Proverbios 4:18-19)

[.discourse-part]
Pregunta: ¿Pero cómo puedo esperar, llegar a conocer y recibir esta ley?
Yo no pertenezco a los judíos naturales, sino a las costas de los gentiles.
¿Cómo puedo encontrar y recibir la ley de vida que viene de Cristo,
o la gracia y verdad que vienen por medio de Él?

[.discourse-part]
Respuesta: La manera de recibirla es,
ocupándose diligentemente de eso que ilumina y renueva la mente,
saca de la naturaleza y espíritu de este mundo, y de los caminos, adoración,
conocimiento y costumbres de este.
Aquí es encontrada la gracia, aquí es encontrada la verdad,
aquí es encontrado el Espíritu de vida,
aquí es sentido el cambio interior y es escrita la nueva ley en el corazón y en el espíritu.
Aquí la mente llega a probar y a conocer '`la buena,
agradable y perfecta voluntad de Dios.`' Porque Dios es el maestro en el nuevo pacto,
y Sus enseñanzas están aquí, es decir, en eso que renueva.
Él reúne en Su Espíritu,
les enseña a los que permanecen en Su Espíritu y les da vida eterna, virtud eterna,
alimento eterno, en y a partir de Su Espíritu.
Pero los que son grandes escudriñadores de la letra escrita,
entendedores de la letra y practicantes de la letra según sus propias
comprensiones (que no fueron reunidas ni leídas en el Espíritu),
pierden la vida eterna, el brazo y poder redentor,
y no son salvos del pecado por la sangre de Cristo.
Estos todavía están en transgresión, tinieblas y muerte, incluso hoy.
Ahora, el Señor, que conoce todas las cosas,
les pone de manifiesto sus estados y condiciones para que no perezcan para siempre,
y que en su lugar, aprendan del Padre a conocer al Hijo y del Hijo a conocer al Padre,
y lleguen a experimentar la verdadera vida manifestada en sus propios corazones,
para que puedan tener comunión con el Padre y con el Hijo.
Porque el que no se vuelve de las tinieblas a la luz (de
las tinieblas en el interior de su propio corazón,
a la luz que Dios hace brillar ahí), todavía no conoce a Cristo vívida y salvadoramente,
sino que permanece solamente en los conceptos y comprensiones que no pueden salvar.
Pues la vida y poder del Señor Jesucristo revelados
internamente contra el poder del pecado y muerte,
son lo único capaz de salvar el alma.

Ahora, consideren ustedes (todos los que no quieren ser engañados en este asunto):
¿Han conocido esta ley?
¿La han recibido en alguna medida, y esperan conocerla y recibirla diariamente,
más y más? Entonces son cristianos de verdad, y son de la casa de Jacob,
que caminan en la luz del Señor y en la luz de la ciudad santa, cuya luz es el Cordero.
Pero sin esta ley, sin esta luz,
sin el escrito interno del Espíritu de Dios en sus corazones,
no pueden ser judíos internos, ni hijos del nuevo pacto.

=== De la Gracia del Evangelio

Los profetas de antaño '`profetizaron de los sufrimientos de Cristo
y la gloria que los seguiría`" (1 Pedro 1:10-11). Ahora,
¿cuál era la gloria que los seguiría? ¿No era el establecimiento
del reino interior e invisible de Cristo en los corazones de ellos?
¿No era el abundante derramamiento que Dios haría de Su Espíritu, llenando sus vasijas,
para que el Espíritu de gracia y de gloria reposara sobre ellos,
como lo había hecho sobre Cristo?
¿No era que Dios moraría en los hombres, sería su Dios y los haría Su pueblo?
¿No era el cumplimiento de las preciosas promesas con respecto al estado del evangelio,
mediante el cual los hombres serían hechos partícipes
de la naturaleza divina (de la imagen celestial),
y serían cambiados de gloria a gloria por medio de la renovación del Espíritu y poder?
¿No era que tendrían comunión con Cristo, no sólo en Sus sufrimientos y muerte,
sino también en Su resurrección y reino,
donde el pan y el vino del reino serían comidos y bebidos,
y el banquete de manjares suculentos disfrutado?
¿No era el glorioso estado de que serían trasladados
del reino de las tinieblas al reino del amado Hijo,
y habitarían con Cristo en el reino?
¿No era que tendrían comunión (comunión pura y viva) con el Padre y con el Hijo,
para que la bendición y gozo del alma en el estado del evangelio pudieran ser plenos?

La ley era una administración de sombras,
porque bajo ella estaban las varias y muchas sombras de las buenas cosas por venir,
las cuales serían poseídas y disfrutadas en los días del evangelio.
En la ley había un pueblo externo (de judíos externos), un pacto externo,
una tierra de bendiciones, plenitud y reposo externa.
Había una Sión externa, una Jerusalén externa, un templo externo, un arca externa,
una mesa externa, una fuente externa, un candelabro externo, unas lámparas externas,
un aceite externo, una unción externa, una circuncisión y sacrificios externos,
nuevas lunas y días de reposo externos, reyes externos, sacerdotes externos,
victorias externas sobre enemigos externos, etc.

Pero ahora, en el evangelio, está la sustancia de estas cosas internamente revelada,
e internamente poseída y disfrutada.
Hay un judío interno (el nuevo hombre del corazón), un pacto de vida y paz interno,
(el que el verdadero creyente guarda en la fe, al no llevar ninguna carga,
encender ningún fuego, ni hacer ninguna obra de la carne en él). Hay una Sión interna,
una Jerusalén interna o ciudad santa,
un templo interno (en el que está el Lugar Santísimo), un arca interna,
en la que la ley de vida está atesorada, una mesa interna, una fuente interna,
un candelabro interno, una lámpara interna, un aceite interno,
una circuncisión y sacrificios internos, y estaciones solemnes.
En realidad, ahora hay un Rey de gloria interno,
un Profeta y Sacerdote interno que se experimenta, es decir, Cristo dentro,
que da victorias y dominio sobre los enemigos internos,
y les da a los Suyos ser partícipes de Su reino y sacerdocio.
(Apocalipsis 1:6) Sí, y por medio de Su Espíritu derramado sobre ellos,
hace que Sus hijos también vean y profeticen, como está escrito:
"`Derramaré de mi Espíritu sobre toda carne,
y vuestros hijos y vuestras hijas profetizarán.`"

Ahora, ¿no se cumplió esto después de los sufrimientos de Cristo en la carne?
¿Y no se cumple cada día más, en la medida que los sufrimientos de Cristo,
que aún faltan, se cumplen en Su cuerpo, la iglesia?
¿No siguió luego la gloria?
¿No fue revelado y concedido luego el espíritu y poder del evangelio?
¿No trajo esto el estado del evangelio?
¿No fueron cumplidas las preciosas promesas en él?
(2 Pedro 1:3-4) ¿No son ellas sí y amén en Cristo?
¿No es quitado el velo o cubierta en Cristo?
¿No es revelada la gloria en Él? ¿No es el Señor uno y Su
nombre uno en Él? ¿No hay gloria entonces en las alturas,
paz en la tierra y buena voluntad entre los hombres,
así como también buena voluntad en Dios para con los hombres?
¿Dónde están la enemistad y las guerras, las lujurias y las luchas?
¿No se ahogan estas cosas en el amor y en la paz,
en la vida y en el poder que son revelados en el estado
del evangelio y brotan en el Espíritu del evangelio?
Los que quieren hacer descender fuego del cielo sobre los desobedientes y opositores,
no saben de qué espíritu son.
No cabe duda, no son del Espíritu del evangelio, no son del Espíritu de Cristo,
pues Él no vino a destruir las vidas de los hombres,
sino a buscar y a salvar lo que se había perdido,
y a vencer por medio de inundaciones de Su amor y tiernas visitas de Su vida.
¿Cómo hacen guerra hoy Sus verdaderos hijos?
¿No es con inocencia, con mansedumbre, con paciencia, corazones amorosos, longanimidad,
verdad, justicia, como seguidores del Cordero,
como hijos de Aquel que abunda en el interior?
En realidad, es dada una espada, un instrumento de trilla,
dardos y flechas para disparar a los corazones de los enemigos del Rey.
(Salmo 45:3-5) Pero esto no es para destruir a la criatura,
sino para golpear y herir a ese espíritu que la esclaviza,
a fin de que la criatura pueda experimentar liberación y libertad de él. Sin embargo,
es cierto que los que se unen a ese espíritu, deben participar de sus juicios y plagas,
incluso para destrucción, si continúan así.

Ahora bien, esta gloria está envuelta en la gracia que es ministrada por el evangelio.
Donde se siembra la gracia, se siembra la gloria (hay una verdadera semilla de gloria);
donde abunda la gracia, abunda la gloria.
Se dijo con respecto a los primeros cristianos reunidos por los apóstoles,
"`y abundante gracia era sobre todos ellos`" (Hechos 4:33); en efecto,
este estado en el que ellos estaban reunidos y al que habían sido llevados,
era precioso y glorioso.
Hoy la gracia es revelada de nuevo, la gracia es derramada de nuevo,
la gracia ha aparecido enseñando y trayendo salvación de nuevo.
¿No les corresponde a todos conocerla y participar de ella?
(¿Y no estar contentos con palabras con respecto a la gracia,
sino experimentar la gracia misma, al recibirla de la mano de Aquel que la da,
y oír la voz, reprimendas e instrucciones de ella?) "`Oíd,
y sus almas vivirán.`" ¿A quién deben oír ellos?
¿No tienen que oír a Cristo, el gran profeta?
¿Cómo oirán a Cristo?
¿Existe alguna otra manera, además de oír Su gracia enseñándolos,
y escuchar la medida del don de gracia que es dado por Jesucristo?
"`La ley por medio de Moisés fue dada,`" (todo su pueblo, todos sus hijos,
toda su familia debía venir a estar bajo la ley, para ser gobernados por la ley).
"`La gracia y la verdad vinieron por medio de Jesucristo,`" (todos Sus hijos,
todo Su pueblo, toda Su familia tiene que venir a estar bajo la gracia,
para ser gobernados por la gracia), quien es fiel en toda Su casa,
dispensando de Su gracia y verdad a todos los Suyos,
tal como Moisés lo hizo con la ley (entregada a él) a todos los que estaban bajo él.

Así, entonces, todos los que deseen ser verdaderamente cristianos,
esperen conocer qué es esta gracia y verdad que Cristo les da,
participar de ella y estar bajo ella; bajo sus enseñanzas, bajo sus influencias,
bajo su protección,
bajo su gobierno (sujetándose a ella y siendo guiados por ella en todo).
En esta gracia llegarán a conocer, en verdadera experiencia y con todo el peso de esta,
lo que significa la escritura: "`Porque el pecado no se enseñoreará de vosotros;
porque no estáis debajo de la ley, sino debajo de la gracia`" (Romanos 6:14).

=== Respuesta a la Pregunta Sobre la Santidad Real

[.discourse-part]
Pregunta:
¿Acaso no deben ser personas realmente santas (realmente santificadas en Cristo Jesús),
aquellas que desean ser recibidas por el Señor y gozar comunión con Él,
como hijos e hijas en el evangelio de Su Hijo?

[.discourse-part]
Respuesta: Bajo la ley los judíos debían separarse de los paganos,
debían ser externamente circuncidados y lavados con el agua y la sangre
de purificación (que santificaba para purificación de la carne),
y no tocar ninguna cosa muerta o inmunda.
Cualquier cosa así los contaminaba,
y los que no estaban limpios tenían que ser mantenidos fuera del campamento
como no aptos para la comunión santa con Dios ni Su pueblo,
hasta que se limpiaran.

¿Qué indicaba esto?
¿No hablaba del estado interior puro y limpio que Dios requiere bajo el evangelio?
¿No hablaba de la circuncisión interior del corazón y del espíritu delante del Señor,
y de la limpieza del alma,
mente y cuerpo antes de presentarse a adorar en el templo interior y espiritual?
(Hebreos 10:22) ¿No hay una Jerusalén bajo el evangelio
en la que ninguna cosa incircuncisa o impura puede entrar,
o presentarse delante de Dios ahí? Noten lo que dice el apóstol en Hebreos 12,
"`No os habéis acercado al monte que se podía palpar,`" al Monte Sinaí externo, o Sión,
para presentarse a Dios ahí, sino que se han acercado al Sión espiritual,
a la ciudad del Dios vivo,
a la Jerusalén celestial y a la comunión con Dios y con Cristo ahí. (Hebreos 12:18-22)

Ahora, ¿cuál es el camino a este compañerismo santo y comunión celestial?
¿No lo ordena Dios mismo?
"`Por lo cual, salid de en medio de ellos, y apartaos, dice el Señor,
y no toquéis lo inmundo; y yo os recibiré, y seré para vosotros por Padre,
y vosotros me seréis hijos e hijas,
dice el Señor Todopoderoso`" (2 Corintios 6:17-18). Porque Dios
deseaba tener un pueblo representativamente santo en el tiempo
de la ley (pero no deficiente de la santidad interior),
y quiere tener un pueblo verdaderamente santo en el tiempo del evangelio.
"`Si alguno destruyere el templo de Dios,
Dios le destruirá a él,`" pero si lo mantiene limpio, puro y santo,
entonces el Santo Dios habitará y aparecerá ahí, según la promesa: "`Yo moraré en ellos,
y andaré en ellos.`"
Esto es eternamente verdadero,
y lo atestigua una experiencia clara y cierta entre los que conocen al Señor;
que si se toca algo impuro, hay una contaminación resultante,
y que se debe pasar por una limpieza,
antes de que haya una experiencia de la presencia del Dios
Santo y se pueda disfrutar comunión con Él de nuevo.

Por lo tanto, mantener fuera lo que es impuro,
debe ser el gran cuidado de toda mente renovada.
El enemigo procurará asaltar, tentar y echar en la mente lo que es impuro,
pero la mente pura y casta no debe alojarlo ni tocarlo,
sino retraerse y retirarse al lugar de seguridad, a la torre fuerte de defensa;
debe retirarse de todos los asaltos y molestias del enemigo.

¡Bendito sea el Señor,
quien ha revelado y otorgado a Sus hijos e hijas en estos últimos días,
esa luz de Su Santo Espíritu que escudriña las partes más íntimas!
Este Espíritu pone de manifiesto todo lo que es de una naturaleza contraria a Sí mismo,
vuelve y separa la mente de eso que es contrario, y lleva la mente, el corazón,
alma y espíritu bajo lo que es una cruz y un yugo para eso,
y que tiene poder de Dios para crucificarlo y someterlo.
De esta manera la vida y la inmortalidad son sacadas
a la luz y llegan a reinar en el corazón,
y la muerte e inmundicia son sorbidas en victoria.
Porque esta es la intención del evangelio y de la aparición de Cristo, o sea,
destruir el pecado y levantar la semilla santa, establecer la ley del nuevo pacto,
la ley de amor, la ley de vida, justicia y santidad,
en la que los renovados deben caminar delante del Señor todos sus días.

¡Oh,
que Dios no permita que el evangelio de nuestro Señor Jesucristo
(que es poder de Dios para salvación) no llegue a su fin,
o que la voluntad de Dios no sea cumplida!
Porque Su deseo es la santificación de Su pueblo en alma,
cuerpo y espíritu (1 Tesalonicenses 5:23),
que sean completamente leudados con la levadura de
Su reino y lleguen a ser una nueva masa en Él.

¡Qué el Señor haga que esto suceda en los corazones de los hijos de los hombres,
al derribar todas las religiones que no tienen la verdadera virtud en ellas!
¡Y qué extienda y establezca más y más esa religión que permanece en la evidencia,
demostración, virtud y poder de Su propio Espíritu,
para que los hombres puedan ser redimidos del engaño en asuntos de religión,
en donde la condición eterna de sus almas está en juego!
Amén.

=== Con Respecto a la Ley del Pecado en la Mente Carnal, y la Ley de Vida y Santidad en la Mente Renovada

¿Qué es la ley del pecado?
¿Quién la escribe en la mente?
¿Qué es cuando es escrita?
"`Entonces la concupiscencia, después que ha concebido, da a luz el pecado; y el pecado,
siendo consumado, da a luz la muerte`" (Santiago 1:15). De modo que,
el primer inicio del pecado es la concupiscencia maligna,
y toda la corrupción que hay en el mundo es a causa de la concupiscencia.
(2 Pedro 1:4) Ahora, ¿de dónde viene esta concupiscencia?
¿No es engendrada en la mente y espíritu por el tentador?
¿Y qué es la ley,
tanto de la concupiscencia como de los pecados cometidos a través de esta?
¿No es la naturaleza lujuriosa, la voluntad lujuriosa, la sabiduría lujuriosa,
los deseos y pasiones lujuriosos, que el dios de este mundo engendra en la parte mundana?

Por otro lado, hay una ley santa en la mente santa y renovada.
¿De dónde viene esta ley?
¿Acaso no viene de Dios?
¿No viene del Santo?
¿No es Él quien borra la ley de Satanás y luego escribe
Su propia ley en los corazones de los Suyos?
¿Qué es Su ley?
¿No es de una naturaleza contraria a la ley de Satanás? ¿No es
la ley de Dios lo que Él escribe en los corazones de Sus hijos,
que les enseña santidad, les demanda santidad,
ilumina la mente en santidad y manifiesta la voluntad buena, perfecta y agradable?

Bajo el antiguo pacto la ley estaba a distancia, escrita en tablas de piedra,
pero bajo el nuevo pacto la ley está cerca,
escrita en el corazón por el Espíritu y poder del Señor Jesucristo.
Porque Él es Rey, el Rey interno, el Rey espiritual de Su pueblo,
que viene para reformar y sanar por medio de Su pacto.
Debido a que Él encontró (bajo el antiguo pacto) que las leyes escritas externamente
nunca traerían ni mantendrían a los hombres bajo sujeción a Su Padre,
ahora escribe internamente por medio de Su Espíritu y poder,
y visita con el día interno y eterno; en otras palabras, con el día de Su poder.
De esta manera hace que Su pueblo esté dispuesto a recibir la ley de Su Espíritu de vida,
que hace "`libre de la ley del pecado y muerte`" (Romanos
8:2). Porque al ser esta ley interna y espiritual,
y más poderosa que la otra, vence la otra ley, es decir,
vence la "`ley del pecado y muerte`" (aunque sea interna y espiritual,
y también esté escrita internamente) y libera el alma de esta.
(Romanos 6:18).

Cada una de estas leyes obtienen su fuerza del que las escribe.
La ley del pecado y muerte obtiene su fuerza del dios de este mundo,
del príncipe de las tinieblas que gobierna en todos los
que son desobedientes al Espíritu y poder de Cristo.
La ley de santidad, la ley de vida, la ley de fe en el poder,
la ley de obediencia al Santo Espíritu de Dios, obtiene su fuerza del Santo,
del Príncipe de vida y paz.
Satanás está cerca de sus súbditos y mora en ellos,
para actuar en ellos y hacer que sus leyes de pecado y muerte sean forzosas en ellos.
Él enciende y vigoriza cada movimiento y tentación del pecado,
para prenderle fuego a los espíritus malignos de los hombres en pos del pecado,
la vanidad, el orgullo, lujuria, inmundicia, crueldad y toda forma de maldad.
Pero el Señor también está cerca del alma.
El Rey de santidad,
el Rey de justicia y paz está cerca para darle fuerza a cada deseo santo en el corazón,
y a cada movimiento de Su Espíritu hacia eso que es bueno y santo.
Por esta razón, el que confía en el Espíritu de Dios,
vigilando y siguiendo Sus movimientos y persuasiones, encuentra que la vida fluye,
que la virtud y la fuerza fluyen para poder llevar
a cabo todo lo que el Señor le mueva a hacer.
Así, si alguno llega a experimentar verdaderamente un movimiento,
o a entender las persuasiones y guías del Espíritu de Dios, entonces,
al que se rinde en la fe para seguir al Señor nunca le falta fuerza.

Entonces la clave del cristianismo es: Llegar a experimentar internamente al Señor,
experimentar internamente las apariciones del Pastor,
experimentar Su guía a los pastizales donde se alimenta la vida eterna,
y el regreso al redil de descanso,
el cual es nada menos que el seno de amor y vida eterna.
Ahora, el crecimiento del nuevo hombre, el crecimiento del estado cristiano,
está en el ejercicio bajo la ley de vida, bajo la ley del Espíritu.
Porque el Espíritu ejercita la mente mediante Su ley,
y la mente debe rendirse para ser tratada de esta manera,
esperando en el Señor en tales ejercicios día y noche, y nunca encontrándose fuera,
sino siempre bajo la ley de Cristo en todas las cosas.
En realidad,
¿cómo puede un hombre hacer algo correcto sin el sentido y conocimiento de la ley interna?
¿Cómo puede un hombre luchar correctamente contra sus enemigos
espirituales sin entender la ley de la lucha?
Porque hay una lucha lícita y una ilícita contra los enemigos del alma.
La lucha ilícita está en la voluntad, sabiduría y fuerza propias,
según las propias comprensiones y concepciones, las cuales no ganan terreno real;
por tanto, los que luchan de esta manera no pueden vencer.
La lucha lícita está en la fe, en la sabiduría y guía del Señor, en Su Espíritu y poder,
y esta lucha siempre tiene éxito.
Por tanto, hay una manera lícita y una ilícita de correr la carrera,
lo cual el apóstol claramente implica cuando dice:
"`Corred de tal manera que lo obtengáis`" (1 Corintios
9:24). Así también hay una ley de oración,
una ley de fe, una ley de amor, una ley de nueva obediencia,
una ley de libertad (porque la libertad bajo el evangelio no carece de límites,
sino que está sujeta al Espíritu), una ley real,
que el Rey de gloria escribe y mantiene viva en el corazón. Por medio
de esta ley Su voluntad es entendida y el camino de vida experimentado,
el cual sólo puede ser entendido por aquellos en quienes esta ley está escrita, es decir,
la ley del nuevo pacto, la ley del Espíritu de vida en Cristo Jesús.

Lean y consideren esto seriamente,
porque en verdad contiene el misterio mismo del cristianismo y la redención.
Pues la redención no sucede por medio de un conocimiento intelectual de Cristo,
sino al recibir y estar sujeto a la ley de Su Espíritu.
Espere conocer y entender si esta no es la ley de la que habla David cuando dice:
"`La ley de Jehová es perfecta, que convierte el alma; el testimonio de Jehová es fiel,
que hace sabio al sencillo.
Los mandamientos de Jehová son rectos, que alegran el corazón;
el precepto de Jehová es puro, que alumbra los ojos.
El temor de Jehová es limpio, que permanece para siempre;
los juicios de Jehová son verdad, todos justos`" (Salmo 19:7-9). Ciertamente,
la ley del Espíritu de vida en Cristo Jesús es todo esto,
al contener en ella el mandamiento que es vida eterna, el testimonio fiel,
todos los estatutos, juicios y temor santo que el alma necesita aprender.
De hecho, es perfecta y capaz de convertir e instruir perfectamente al alma convertida.
Aquí, bajo esta santa ley del Espíritu y poder de vida, se cumple la escritura:
"`Y ninguno enseñará a su prójimo, ni ninguno a su hermano, diciendo: Conoce al Señor,
+++[+++ninguno hará así en este pacto, bajo esta administración,
la cual es la administración del Espíritu y no la de la letra],
porque todos me conocerán, desde el menor hasta el mayor de ellos.
De hecho, ellos sabrán por las enseñanzas de mi propio Espíritu,
al escribir mi ley en sus corazones, por mi santa unción, que les enseñará a mis hijos,
a mis ungidos, todo lo que necesitan saber.`"
(Hebreos 8:11; Jeremías 31; 1 Juan 2:27)
