== Capítulo 14. La Semilla del Reino

[.discourse-part]
Pregunta: ¿Qué es la Semilla?

[.discourse-part]
Respuesta: La Semilla de Dios es la palabra de Dios;
la Semilla del reino es la palabra del reino.
Es una medida de la luz y vida, de la gracia y verdad que son de Jesucristo,
quien es la plenitud.
Es un talento celestial (o manifestación de Su Espíritu en el corazón),
que se le da al hombre para que lleve un incremento para Dios,
en la virtud y fuerza de Cristo.
Este don,
que ha colocado Dios en el hombre para que testifique en nombre
de sí mismo y guíe al hombre del mal al bien (en las respiraciones,
vivificaciones y resplandores puros de él), es la Semilla,
la cual es gratuitamente concedida al hombre para que brote y permanezca en él,
y lo saque de sí mismo y lo lleve a Ella.

[.discourse-part]
Pregunta: ¿Quién es el sembrador de esta Semilla?

[.discourse-part]
Respuesta: Dios, en y a través de Cristo.
Él es el buen jardinero.
Él, por medio de la palabra que creó todo en el principio, crea de nuevo en Cristo Jesús,
renueva Su hechura en el hombre,
y pone una medida de esta palabra o Espíritu de vida en el corazón del hombre,
a través del cual lo renueva.
Ahora, estos que son renovados por Él de esta manera, son "`hechura suya,
creados en Cristo Jesús para buenas obras.`"

[.discourse-part]
Pregunta: ¿Dónde se encuentra esta Semilla?

[.discourse-part]
Respuesta: Se encuentra donde Dios la siembra, esto es, en la tierra interna.
Esta es una Semilla interna y es sembrada en el terreno o tierra interna, es decir,
en los corazones de los hombres.
Ahí brilla la luz de la palabra, ahí se experimenta la vida de la palabra,
agitando y vivificando secretamente a los que estaban muertos en delitos y pecados.
Ahí la voz y el llamado de la palabra son oídos, llamando de la injusticia y del pecado,
a la justicia y santidad.

[.discourse-part]
Pregunta: ¿En qué tipo de terreno es sembrada esta Semilla celestial?

[.discourse-part]
Respuesta: En todo tipo: En terreno junto al camino, en terreno pedregoso,
en terreno espinoso y en buen terreno.
Los relámpagos de Dios en el interior iluminan todo el mundo interior,
de modo que Dios no ha dejado a ningún hombre sin
un Testigo en su consciencia contra el pecado.
Y aunque la consciencia del hombre es corrupta, y su luz se ha vuelto tinieblas,
aun así el Testigo de Dios en su consciencia no puede ser corrompido,
sino que cada vez que brilla en el corazón,
da verdadera luz ahí. Cada vez que testifica ahí, testifica la verdad para Dios,
testifica contra el hombre, y la corrupción y cauterización de su corazón y consciencia.

[.discourse-part]
Pregunta: ¿En qué tipo de terreno produce buen fruto?

[.discourse-part]
Respuesta: Sólo en el buen terreno.
Esta Semilla produce algo de fruto en otros terrenos, y el fruto que produce es bueno.
Las convicciones son buenas, los deseos engendrados ahí por Ella y que surgen de Ella,
son buenos.
El abandono de algunas cosas malas y el hacer algunas cosas buenas, es bueno.
Pero los espinos, el afán, la mundanalidad y el temor a la persecución,
se levantan de otra raíz y son de otra naturaleza,
y sofocan y ahogan la Semilla en el terreno espinoso.
Pero el buen terreno le cede todo su alimento a la buena
Semilla (y no le dará alimento a ninguna mala Semilla),
para que la buena Semilla no sólo brote, sino que lleve fruto.

[.discourse-part]
Pregunta: ¿Cómo puede ser hecho bueno el terreno que es malo?
¿No fue una vez malo el terreno que ahora es bueno?
¿Acaso no puede ser hecho bueno el terreno que ahora es malo?

[.discourse-part]
Respuesta: Dios ha encerrado a todos los hombres en incredulidad,
para poder tener misericordia de todos.
En realidad, el corazón que ahora es suave una vez fue duro.
El corazón que ahora cree una vez fue incrédulo.
El corazón que ahora ama a Dios una vez estuvo en enemistad.
El arado de Dios, puesto en el terreno espinoso, arrancando y desarraigando los espinos,
cambiará su naturaleza y hará que mejore.
"`Arad campo para vosotros,
y no sembréis entre espinos,`" dijo Dios a Su Israel
de antaño. ¿No cambia el hombre por medio de cuidado,
arte e industria la naturaleza externa de la tierra o del terreno?
De seguro entonces,
el Señor por medio de la palabra de Su poder puede
cambiar la naturaleza interna del terreno.

Ahora,
para una explicación más clara y simple de lo que aún queda en
mi corazón con respecto a esta preciosa Semilla del reino de Dios,
la consideraré bajo los siguientes tres subtítulos:
I+++.+++ Qué está envuelto o escondido en esta Semilla, II. La naturaleza de la Semilla, III.
Los efectos de la Semilla.

[.alt]
==== I. ¿Qué está envuelto o escondido en esta preciosa Semilla celestial?

En realidad, hay tanto envuelto en Ella, que el corazón del hombre no lo puede concebir,
y mucho menos, expresar la lengua.
Sin embargo,
he sentido algo y está en mi corazón responder a esto bajo los siguientes encabezados.

[.discourse-part]
__En primer lugar, la gloria del reino de los cielos,
la gloria del reino eterno está escondida y envuelta aquí, en la Semilla.__
De cualquier manera que aparezca, reine y brille Cristo, lo hace en esta Semilla.
¡Oh,
el brote y la manifestación de esta Semilla es ciertamente glorioso
y excelente! ¿Cómo puede un hombre hablar con respecto a Ella?
¡La cosa misma (al ser internamente sentida,
experimentada y disfrutada) está mucho más allá de todas
las palabras! ¿En qué consiste el reino de Dios?
No consiste en palabras, sino en poder.
El poder está escondido y envuelto en esta Semilla.
El poder puro de vida está en esta Semilla.
La espada que atraviesa a Leviatán, que hiere la cabeza de la serpiente,
que corta a Rahab y al dragón, está en esta Semilla.
¿Consiste el reino de Dios en justicia, paz y gozo en el Espíritu de Dios?
Todo eso está en esta Semilla, y se participa y se disfruta de todo ello,
en la medida que esta Semilla brota y gana autoridad y dominio en el corazón. Sí,
el cuerno del ungido de Dios, el cetro justo y apacible del Salvador,
son experimentados y exaltados en esta Semilla,
en la medida que brota y se propaga en el exterior, en la vida y virtud del Padre.

[.discourse-part]
__En segundo lugar,
la naturaleza divina de Dios Todopoderoso está escondida y envuelta en esta Semilla.__
Es la Semilla de Dios y la naturaleza misma de Dios.
Por tanto, aquel en quien Ella brota, que está recogido en Ella,
que ha nacido de Ella y ha sido hecho uno con Ella, participa de la naturaleza divina.
Pedro habla de las grandes y preciosas promesas,
por medio de las cuales los santos son hechos partícipes de la naturaleza divina.
(2 Pedro 1:4) Todas las promesas son para la Semilla de la promesa (Gálatas 3:19),
para Cristo el Hijo de Dios, para la Semilla de Dios,
para los herederos de la vida y salvación en Cristo.
Todas estas promesas están cumplidas en Cristo,
y son disfrutadas por aquellos que son injertados y hechos uno con Cristo, la Semilla.
Ahora, nada de esto puede ocurrir excepto por la gracia, por la verdad, por la luz, vida,
Espíritu y poder que Él siembra en el corazón, estas no son muchas cosas,
sino la única Semilla en donde están contenidas e incluidas todas ellas.

[.discourse-part]
__En tercer lugar, el nuevo pacto, o sea,
el acuerdo santo del alma con Dios en Cristo Jesús, está en esta Semilla.__
En Ella está el pacto que Dios hace con el nuevo Israel.
Por medio de este pacto hace que el corazón sea nuevo y escribe Su ley en él;
quita el corazón de piedra y sana todas sus rebeliones; los ama gratuitamente,
pone Su Espíritu dentro de ellos y hace que caminen en Sus caminos,
guarden Sus estatutos y juicios, y los pongan por obra.
Dios dio a Cristo por pacto,
y la Semilla de gracia y verdad viene por medio de Jesucristo.
Todo el que recibe esta gracia y verdad de Él (en la Semilla santa del reino),
recibe el pacto; y el que camina en Él, camina en el pacto.

Aquí y sólo aquí, es experimentada la nueva creación en Cristo Jesús. Aquí y sólo aquí,
es verdaderamente entendido y testificado el acercamiento a Dios por medio de Cristo.
Aquí y sólo aquí,
es escrita en el corazón la ley del Espíritu de vida en Cristo Jesús.
Manténgase aquí y nunca se saldrán del acuerdo santo con Dios,
porque en esta gracia y verdad, en esta Semilla de vida,
no hay nada que esté en desacuerdo con Él. Aquí viven en el Espíritu,
caminan en el Espíritu y no satisfacen los deseos de la carne (en realidad, no pueden).
No hay nada en esta Semilla que desagrade a Dios o aleje sus almas de Él. Más bien,
aquí el Señor guía los pies de Sus santos y les enseña a todos, al poner Su ley de vida,
nueva obediencia y Espíritu Santo en sus corazones,
para que ninguno de sus pasos se deslice.
Aquí el camino de santidad, por el que Dios los preserva de extraviarse,
(Isaías 35:8) es conocido y se camina en él. Sí,
aquí Cristo es conocido y experimentado como el camino, la verdad y la vida.
Las ovejas que son recogidas y vienen aquí,
han regresado al Obispo y Pastor de sus almas,
Al que las vigila y las preserva poderosamente para que no se descarríen más.

[.discourse-part]
__En cuarto lugar,
todas las gracias y virtudes del Santo Espíritu de Dios
están escondidas y envueltas en esta única Semilla.__
No hay nada que Dios requiera del alma, ni nada que el alma pueda desear de Dios,
sino lo que está escondido y envuelto en esta Semilla.
Todo lo que es necesario, o todo lo que puede ser deseado,
es el crecimiento y esparcimiento de esta Semilla en el alma, y que el alma se reúna,
viva, more, permanezca y actúe en Ella.
¡Oh, la gran diferencia que hay entre el esfuerzo egoísta del alma,
su querer y su hacer para unirse a Dios,
y la unión que hace Dios con el alma en esta Semilla, y Su vida,
Su querer y Su hacer que se experimentan en el brote de vida de esta Semilla!

[.small-break]
'''

Ahora,
para hacer esto un poquito más claro y evidente para los corazones de
aquellos que desean el verdadero entendimiento de estas gracias y virtudes,
les daré algunos detalles bajo este cuarto encabezado.

[.discourse-part]
_Primero:_ El conocimiento puro, vivo y celestial del Padre y de Su Hijo, Cristo Jesús,
está envuelto en esta Semilla.
Dios es luz, y esta Semilla que viene de Él, no es tinieblas, sino luz;
y en la luz que brota de esta Semilla, Dios y Cristo son revelados.
La naturaleza divina de Ellos brota de la Semilla,
y si uno experimenta la naturaleza de Ellos, entonces son verdaderamente conocidos.
De hecho, aquí experimentamos el justo Espíritu de Cristo, la justa naturaleza de Cristo,
la justa vida de Cristo, y lo sentimos ser uno con el Padre,
quien engendra al mismo Espíritu, naturaleza y vida en nosotros.
Y el que es nacido del Espíritu es espiritual; y el que es unido al Señor es un espíritu;
y el que es unido a la Semilla,
a la medida de gracia y verdad de Cristo (en la que y por la que el alma es unida),
es unido a Dios e injertado en Cristo.
Y en la medida que la Semilla es formada en él,
Cristo es formado en él. Y en la medida que él es
formado y creado nuevamente en la Semilla,
es hechura de Dios, formado y nuevamente creado en Cristo.

[.discourse-part]
_Segundo:_ La fe, la fe verdadera, la fe viva, efectiva,
salvadora y conquistadora que da victoria sobre el mundo,
y sobre el diablo y sus tentaciones, está contenida o envuelta en esta Semilla.
La fe es el precioso don de Dios que no se encuentra en la naturaleza del hombre,
sino que brota y crece de la preciosa Semilla del reino,
la cual Dios siembra en el corazón del hombre.
En realidad, la fe es un don que debe ser esperado y obtenido de Dios.
Por tanto, el apóstol Pedro, escribiéndoles a los santos de su tiempo,
dirige su epístola de la siguiente manera:
"`A los que han recibido una fe como la nuestra,
mediante la justicia de nuestro Dios y Salvador, Jesucristo`" (2 Pedro 1:1; LBLA).
La fe es algo precioso, algo justo, algo santo,
de la cual Dios es el dador y Cristo el autor y consumador.
Esta fe brota de la raíz santa,
de la Semilla santa de vida y justicia que Dios siembra en el corazón.
Esta fe (no hablo de la capacidad de creer del hombre,
o de la fe que es hallada en la naturaleza del hombre) es la fe de los elegidos de Dios.
(Tito 1:1) Es la fe que les da Dios a los que son nacidos de Él, (Juan 1:12-13),
a los que son nacidos de la Semilla incorruptible,
por la Palabra de Dios que vive y permanece para siempre.
(1 Pedro 1:23) Esta Palabra, al estar cerca, en la boca y el corazón, engendrando,
preservando e incrementando la fe ahí (según es experimentada diariamente),
es llamada "`la palabra de fe`" (Romanos 10:8).

[.discourse-part]
_Tercero:_ El temor puro, el temor santo, el temor celestial,
el cual es de una naturaleza limpia y celestial, y perdura para siempre,
también está en esta Semilla.
Este inocente temor es una promesa del nuevo pacto,
y es dado a los hijos del nuevo pacto,
el cual Dios pone en sus corazones desde la Semilla de vida que brota en ellos,
para que no se aparten del Señor. (Jeremías 32:40)

[.discourse-part]
_Cuarto:_ El amor puro y divino está en ella.
En la medida que esta Semilla brota, en esa misma medida brota el amor de Dios.
Así como Dios es amor, la Semilla que es de Él participa de Su amor.
No hay enemistad en ella, y ninguna enemistad u oposición brotarán de ella.
Esto hace que para los hijos de Dios sea muy natural amar,
pues han nacido de esa Semilla que vino del Dios de amor, cuya naturaleza es amor.
¡Oh, cuán diariamente es hallado, mediante una dulce y segura experiencia,
que esta Semilla (al brotar) enseña y hace posible amar!
Los que tienen esta Semilla brotando en ellos,
no necesitan ser externamente enseñados a amar con amor fraternal, pues en la Semilla,
por medio de ella y a través de ella, son enseñados por Dios a amarse unos a otros.
De manera que, el alma no necesita nada sino la circuncisión del corazón,
la purificación del corazón a través de la obediencia a la verdad,
la amputación de esa mente, naturaleza,
voluntad y sabiduría carnales que no pueden amar correctamente.
Entonces el amor puro brotará plenamente hacia el Señor y hacia los hermanos.
(Deuteronomio 30:6; 1 Pedro 1:22) Sí,
será natural amar a todos y el mandamiento de Cristo no será gravoso, a saber,
amar a los enemigos, incluso a los más grandes agraviadores,
maldecidores y perseguidores.
(Mateo 5:44)

[.discourse-part]
_Quinto:_ La esperanza pura, la esperanza del recto, la esperanza que no avergüenza,
la esperanza que penetra detrás del velo y es una ancla segura y firme ahí,
(al anclar la mente en el Señor, quien la mantiene en perfecta paz),
está contenida en la Semilla y brota de ella.
Pues nada sino lo que viene de Dios (de la Semilla santa
de verdad y justicia) puede anclar la mente en Dios.
De modo que, el que siente la Semilla, siente la esperanza,
y al mantenerse vuelto hacia la Semilla (hacia la raíz santa), la esperanza permanece.
Por tanto, al volverse la mente a la luz, al volverse del poder de Satanás a Dios,
al volverse a Cristo,
al volverse a la aparición y voz de la palabra de vida en el interior,
al volverse de la semilla de maldad y tinieblas a la Semilla santa y justa del reino,
está vuelta hacia lo que engendra la esperanza verdadera
y justa en el corazón. Esta no es una esperanza en la carne,
sino en la Semilla santa y celestial, y en la obra de justicia y del reino,
que es el hacha de batalla y arma de guerra de Dios,
por medio de lo cual Él derriba la carne.
Esta esperanza asegura la mente en cada tentación, en cada angustia, en cada prueba,
en todo viento, tormenta y olas de persecución con las que pueda ser asaltada.

[.discourse-part]
_Sexto:_ La verdadera paciencia y su obra perfecta (Santiago 1:4),
está contenida en esta Semilla y es dada con ella.
Así como Dios es paciente y tardo para la ira, así también es esta Semilla.
El hombre es de la naturaleza frágil, inquieta e impaciente,
pero el que recibe la palabra de fe, la Semilla de fe,
en Ella también recibe fe y paciencia.
A este no sólo le es dado creer, sino también sufrir por el bien de Cristo.
El que permanece en la Semilla,
y siente que la Semilla permanece y Su naturaleza prevalece en él,
no puede ser impaciente, sin importar lo que el Señor permita que le suceda.

[.discourse-part]
_Séptimo:_ Aquí la verdadera pobreza de espíritu es experimentada.
Es pobre verdaderamente, el que lo ha vendido todo y no se ha dejado nada,
excepto a esta Semilla y la aparición y ayuda de Dios en esta Semilla;
lo cual tampoco está en sus propias manos, sino en la voluntad y disposición de Dios.

[.discourse-part]
_Octavo:_ Aquí es experimentada la verdadera misericordia hacia otros.
Porque el que es llevado a la Semilla vive sólo por misericordia,
y el que vive por misericordia y es diariamente lo que es por misericordia,
no puede evitar ser misericordioso con otros.

[.discourse-part]
_Noveno:_ La verdadera hambre y sed de justicia brotan de esta Semilla.
La Semilla de Dios, el nacimiento de Dios,
es lo que discierne la excelencia de Su justicia,
y lo que tiene hambre y sed de Su justicia.

[.discourse-part]
_Décimo:_ Para no nombrar más, la cruz que hace morir y crucifica al mundo y al pecado,
sólo puede ser tomada en esta Semilla o por virtud de la Semilla.
En realidad, la Semilla es una cruz, sí, es enemistad contra la naturaleza,
espíritu y curso de la serpiente.
El que la toma (con Su voluntad, Su naturaleza, Su ley de vida),
toma la cruz contra la otra naturaleza, voluntad y ley de pecado y muerte.
Así que si se pierde la santa Semilla, sólo se puede tener una sombra o imagen de la cruz.
Pero en el verdadero sentido y sujeción a la Semilla,
la cruz de nuestro Señor Jesucristo es experimentada
obrando poderosamente contra el pecado,
crucificando y sometiendo efectivamente todo el curso de la naturaleza maligna y pecaminosa.

[.alt]
==== II. ¿Qué es la naturaleza de la Semilla de Dios, o la Semilla del reino?

[.discourse-part]
Respuesta:
Aunque la naturaleza de Esta ya ha sido ampliamente explicada bajo los encabezados previos,
hablaré un poco más específicamente de Ella con varios detalles,
de acuerdo con las Escrituras.

[.discourse-part]
__En primer lugar, es de una naturaleza inmortal e incorruptible.__
(1 Pedro 1:23) Es una Semilla que en sí misma no puede morir,
aunque parezca muerta en el hombre o para el hombre,
al no poder exponer nada de Su vida o virtud escondida en el hombre,
que la ha matado para sí mismo.
Porque el que ha rechazado y matado a la Semilla por medio de la cual Dios da vida,
todavía está muerto en delitos y pecados,
y no podrá vivir hasta que Dios respire y vivifique esta Semilla en él,
y lo resucite por medio de la Semilla.

[.discourse-part]
__En segundo lugar, es de una naturaleza que recoge.__
Ella tiene la naturaleza de una red.
(Mateo 13:47) Saca de lo que es contrario a Dios, para reunirlo en Dios.
Saca del mundo, del mar de maldad, del reino de las tinieblas,
de la propia naturaleza y espíritu del hombre,
para reunirlo en la naturaleza y Espíritu de Dios, y en Su luz y reino,
en donde el alma debe morar, caminar y estar sujeta a Dios.

[.discourse-part]
__En tercer lugar, es de una naturaleza que purga o limpia.__
Ella es de la naturaleza del fuego, de la naturaleza del agua,
internamente y espiritualmente.
Esta Semilla es Espíritu y vida en una medida,
y por Ella (o por el Espíritu de Dios que mora y es revelado en Ella) Él lava
y purga la inmundicia de la hija de Sión. Hay fuerza y virtud en esta Semilla,
contra toda fuerza de engaño y maldad en la otra semilla.
Conforme la Semilla del reino brota y es recibida
y disfrutada en el temor santo del Señor,
prevalece sobre la semilla contraria y arroja sus tinieblas,
y purga y quema su inmundicia, paja y corrupción.

[.discourse-part]
__En cuarto lugar, es de una naturaleza que sazona, leuda y santifica.__
Es como sal; es como levadura.
Ella sazona y leuda con vida.
Ella sazona y leuda con justicia.
Ella sazona y leuda con la imagen de Dios.
Tan pronto como brota en el corazón comienza a leudarlo, y si no se descuida,
ni se entristece, ni se lastima,
ni se apaga (porque esta Semilla es de una naturaleza muy sensible y tierna),
continuará leudando cada vez más con la naturaleza de verdad,
a semejanza del Dios de verdad.
Ver Marcos 9:50; Lucas 13:21; Colosenses 4:6

[.discourse-part]
__En quinto lugar, es de una naturaleza que enriquece.__
Es un tesoro escondido o perla de gran precio.
Hace al comerciante sabio muy rico,
a ese que lo vende todo por Ella y compra el campo con Ella.
El que compra la verdad y no la quiere vender ni apartarse de ella de ninguna manera,
sino que se rinde a ella y la hace su tesoro,
¡cuánto enriquece Esta su corazón con lo que es santo y
celestial! ¡Cuán rico lo hace tocante a Dios! (Mateo 13:44-46)

[.discourse-part]
__En sexto lugar, es de una naturaleza que se incrementa y crece.__
Un único talento puede ser incrementado.
La pequeña Semilla, como la semilla de un grano de mostaza,
crecerá en la buena tierra más allá de las hierbas, y se convertirá en un árbol,
árbol de justicia de la plantación del Señor, para que Él pueda ser glorificado.
(Mateo 13:31-32; 25:16; 13:23)

[.alt]
==== III. ¿Cuáles son los efectos de esta Semilla?

[.discourse-part]
Respuesta: Los efectos de la Semilla pura en el corazón son muchísimos, muy grandes,
muy dulces, preciosos y benditos,
los cuales llegan a experimentar todos aquellos que
experimentan el crecimiento y propagación de Ella.
Mencionaré sólo algunos.

[.discourse-part]
__Primero,
es una verdadera unión y comunión con el Dios y Padre de nuestro Señor Jesucristo,
el Padre de esta Semilla, y con todos los que están unidos a Ella.__
La unión y comunión con Dios están en esta Semilla, nunca fuera de Ella.
Porque en la simiente de la serpiente, el hombre está separado de Dios,
ajeno a Su vida y no puede acercarse a Él, ni tener comunión con Él. Por tanto,
en la Semilla santa, en la Semilla de vida, en la Semilla de justicia,
en la Semilla de fe, el alma es unida a Dios, tiene acceso a Él, fuente viva,
y tiene comunión con Él en lo que es vivo y santo de Él. Los hombres
pueden imaginar una unión y comunión con Dios fuera de Ella,
pero ninguno puede unirse a Dios o tener comunión con Él verdaderamente,
excepto en el don, en la gracia, en la luz, en el Espíritu que es de Dios.

[.discourse-part]
__Segundo, esta Semilla se siente brotar en el corazón, y cuando se une a Ella,
derriba y somete todo lo que es contrario a Dios.__
Este honor y poder los ha dado Dios a la Simiente
de la mujer (aún en la menor medida de Esta):
Que Ella herirá la cabeza de la serpiente y liberará
el alma del cautiverio y esclavitud del maligno.
Así, el alma, en la consciencia, autoridad y virtud vivas de la Semilla,
puede rehusar presentar sus miembros, sus facultades, su voluntad, su mente,
su entendimiento y sus afectos, al pecado y a la injusticia.
Sí, el diablo, el gran dragón rojo, el dios de este mundo,
el poderoso espíritu y poder de las tinieblas, al ser resistido en Esta,
es verdaderamente vencido.
Cuando alguno resiste al diablo en su propia fuerza (en la fuerza de sus propios deseos,
habilidades y decisiones),
es vencido por él. Pero el que resiste al diablo en la fe que brota de esta Semilla,
lo vencerá. Así, pues, el pecado es derribado y la tentación mantenida fuera,
por medio de la virtud y poder de la vida y autoridad
del Salvador que brotan en esta Semilla de Dios.

[.discourse-part]
__Tercero,
a medida que brota y a medida que sus operaciones son experimentadas y recibidas,
lleva a la imagen y naturaleza de Dios.__
Ella borra la imagen del diablo en la mente y renueva a semejanza de Dios y Cristo.
Sí,
aquí tenemos la mente misma de Cristo y somos hechos uno
con la mente de Él. Así como en la simiente de la serpiente,
son puestas la imagen y naturaleza de la serpiente, así en esta Semilla,
es puesta la imagen de Dios y de Cristo.
Sí, la serpiente, el espíritu de tinieblas, el espíritu maligno, el espíritu de engaño,
es quitado aquí y Cristo colocado.
Y cualquiera que desee experimentar el verdadero desvestirse del viejo hombre,
y el vestirse del nuevo hombre (el cual es creado en la justicia y santidad de la verdad),
debe experimentarlo en esta Semilla.

[.discourse-part]
__Cuarto, la Semilla lleva la mente, el corazón, el alma,
el espíritu a la nueva obediencia (a Su propia naturaleza obediente), o sea,
a hacer la voluntad de Dios con gran deleite y placer.__
"`El hacer tu voluntad, Dios mío, me ha agradado,`" dijo Cristo.
Esta Semilla es de Su naturaleza.
Es una medida, una porción, un talento celestial de Su gracia y verdad,
un don de luz y vida proveniente de Aquel que es la plenitud.
Es dada para dar la disposición (como tiene Él) de hacer la voluntad del Padre,
y realmente lo hace,
hasta el punto de que el alma que es completamente leudada y una con Ella,
puede también decir: "`¡Me deleito en hacer tu voluntad, oh, Dios.
Esta se ha convertido en mi comida y bebida, estoy nutrida y renovada,
y me deleito en la virtud que experimento brotar en mí al hacer Tu voluntad!`"
Ciertamente no es así al principio, mientras haya una naturaleza, una voluntad,
una sabiduría contraria a la naturaleza, voluntad y sabiduría de Dios.
Entonces la obediencia es difícil y la cruz sigue siendo un doloroso yugo sobre el cuello.
Pero al ser sometida esa naturaleza,
y al levantarse y prevalecer la naturaleza de la Semilla,
¿qué puede ser de mayor deleite para esta nueva naturaleza
que hacer la voluntad de su Padre celestial,
y descubrir el corazón del Padre complacido con el hijo?

[.discourse-part]
__Quinto, Ella lleva al entendimiento, sentido y deleite de todas las preciosas promesas,
y a todas las bendiciones espirituales en Cristo Jesús nuestro
Señor.__ Todas las promesas son para la Semilla,
y son sí y amén en Cristo, y la más pequeña medida de Su vida participa de esto.
La Semilla, la Semilla eterna es la heredera,
y nosotros los que estamos unidos a la Semilla,
que hemos nacido de la Semilla y crecemos en Ella, somos coherederos con Cristo.
Por tanto, cada promesa llega a ser entendida aquí, gustada aquí,
disfrutada aquí. ¡Cuán llenas están las Escrituras
de dulces y preciosas promesas! ¡Pero ay,
de qué sirve que los hombres se las apliquen a sí mismos,
cuando no tienen derecho a ellas, ni las entienden correctamente,
ni fueron destinadas por el Señor para el estado y condición caídos del hombre!
Pero llegar al entendimiento de las promesas, ser guiados por el Señor a esa condición,
y ser preservados por Él en esa condición a la que pertenecen las promesas--¡Oh,
cuán dulce, reconfortante y gozoso es esto!
De hecho, en esta Semilla todas las maldiciones del libro pasan,
y todas las bendiciones fluyen y se multiplican en el alma día tras día. De modo que,
con razón es llamada '`la Semilla bendita,`' pues en Ella
el alma es verdaderamente bendecida y colmada de bendiciones,
por Aquel que es capaz de multiplicarlas en el alma y de
guiarla en el uso y disfrute seguro y correcto de ellas.

Pero, ¿necesito mencionar algo más? Aquí está la luz, aquí está la vida,
aquí está la justicia, aquí está la paz, aquí está el gozo celestial,
aquí está el poder santo,
todo brotando y produciendo sus frutos y preciosas operaciones y efectos en el
corazón. Aquí está la seguridad del amor de Dios en Cristo para siempre,
y el conocimiento de que Dios nunca dejará ni abandonará
aquella alma que está unida a Él,
y que permanece en Él en esta Semilla.
Dicha alma será guardada por el poder de Dios,
a través de la fe que brota de esta Semilla, para perfecta redención y salvación. Amén.

=== Breve Aclaración con Respecto a la Imputación de la Justicia de Cristo

Dios visita a los hombres por medio de la luz y poder
de Su Santo Espíritu en su estado muerto y oscuro,
o sea, cuando son impíos. Ahora,
los que sienten la vida y en las vivificaciones de la vida se vuelven
a la luz y poder que los visita (por la fe que viene de la vida),
son trasplantados, en cierta medida, de la raíz impía a la raíz santa.
Aquí son hechos partícipes de la naturaleza y virtud del verdadero árbol de olivo,
es esparcida sobre ellos la misericordia del Señor en y a través de Su Hijo Jesucristo,
son perdonadas sus iniquidades y quitadas sus transgresiones por amor de Su nombre.
Estos son contados por Dios, no en la vieja raíz ni en la naturaleza impía,
sino en esa raíz que han asido por fe y a la que están unidos.
Aquí están ante los ojos del Señor,
y son aceptados y amados en Aquel en quien son hallados,
por Aquel que los trasplantó y los injertó ahí. Así que Cristo es realmente de ellos
y ellos de Él. Y lo que Él hizo por ellos en Su cuerpo de carne viene a ser de ellos,
de modo que tienen el beneficio y cosechan los dulces frutos de esto.
Y si después pecaran, tienen un abogado que defiende su causa con el Padre,
que respira vívidamente sobre ellos de nuevo, aviva fe en ellos,
y les da volverse de eso que corrió tras ellos,
los alcanzó y los contaminó. Debido a lo cual,
en este estado de verdadera fe y unión con el Hijo,
se experimenta una fuente abierta para el pecado y la impureza,
la cual diariamente lava las contaminaciones y manchas de la mente,
a las que es susceptible en el estado de viaje.

Ahora, estas cosas no pertenecen a todo lo que el hombre llama fe,
sino únicamente a la fe que fluye del poder de la
vida indestructible y que permanece en el poder.
La fe que proviene del poder es preciosa,
pues tiene una naturaleza y virtud preciosas en ella,
además de todos los efectos preciosos que fluyen de ella.
Porque ella es la sustancia de las cosas que se esperan; ella es de una naturaleza pura,
que tiene dominio y da dominio sobre el maligno.
Pero la creencia en Cristo, o la aplicación de Su justicia, que no es de esta fe,
ni está en la verdadera luz de vida,
(sino que es de acuerdo con las comprensiones de la criatura con respecto a cosas),
no es de la misma naturaleza, ni tiene la misma virtud, ni produce los mismos efectos.
Porque, a pesar de tener ese tipo de creencia y esperanza,
los hombres todavía están en sus pecados, no están lavados por la sangre de Cristo,
ni están perdonados o cubiertos por el Espíritu del Señor. ¡Ojalá
los hombres fueran cautelosos y le prestaran atención a este asunto,
para que no se perdieran el verdadero perdón del Señor!

Porque, en efecto,
hay un estado en el que la justicia de Cristo es imputada
a las personas alcanzadas por el poder del Señor,
aquellos que están saliendo del estado de impiedad y entrando en la verdadera justicia.
En el verdadero crecimiento,
el alma diariamente sale cada vez más de su propia injusticia, de las tinieblas,
de la imagen corrupta, y entra en la justicia de Cristo y en Su imagen pura.
Así es formado más y más diariamente Cristo en los
corazones de los que verdaderamente creen.
Ellos Lo reciben como la levadura celestial,
y al rendirse para ser leudados por Él son cambiados
a diario y cada vez más en la novedad del Espíritu,
hasta que llegan a ser una nueva masa, una masa completamente leudada.
Entonces las cosas viejas pasan y todas son hechas nuevas, es decir,
ya no son del viejo Adán, sino que todos son de Dios en Cristo.
Todos son de la nueva naturaleza y Espíritu, lo cual es justo a los ojos de Dios.

Ahora, esto es por lo que todos deben esforzarse y lo que todos deben buscar:
El reino de Dios y Su justicia, es decir,
encontrar la entrada ministrada a ellos en el reino eterno y la justicia de este,
para que realmente puedan despojarse del viejo hombre con sus pasiones y concupiscencias,
y vestirse del nuevo hombre; de la naturaleza, imagen,
Espíritu y justicia del nuevo hombre.
Todos deben buscar el verdadero vestido de boda para casarse con Cristo,
para ser una novia ataviada para el novio.
¡Oh,
es precioso para cualquiera experimentar su alma en este estado! ¿Quién no querría viajar,
luchar, esforzarse, vigilar,
orar y esperar para poder ser ataviado por el Espíritu del Señor para Su Hijo Jesucristo?

¡Oh, que ellos al tomar sobre sí la profesión del cristianismo puedan sentir el poder,
esperar en el poder, experimentar lo que es creer en el poder y vivir en el poder!
Porque sin este, el angustioso estado del cristianismo no es sino muerte,
sequedad y frío, al no tener la savia verdadera y viva,
ni calidez en él. Hay grandes engaños en el mundo
acerca de la imputación de la justicia y esas cosas.
Pero el que conoce la verdad tal como está en Jesús,
el que ha sido visitado por el poder, recogido en el poder y permanece en el poder,
ha descubierto lo que unge el ojo y el corazón,
y fortalece contra las más sutiles maquinaciones y engaños del espíritu que se transforma.
Pero quienquiera que profesa el cristianismo, y sin embargo, no está aquí,
no está a salvo, pues el enemigo tiene maneras de hechizarlo y engañarlo,
y el tal no puede resistirlo y evitarlo de manera eficaz.

=== Una Breve Pregunta Acerca de la Correcta Lectura de las Escrituras

[.discourse-part]
Pregunta:
¿Cuál es la lectura correcta de las Escrituras para que
sea de beneficio y provecho para el alma del lector?

[.discourse-part]
Respuesta: El que lee las Escrituras en una verdadera medida de vida recibida de Dios,
las lee correctamente, y cada vez que las lee así, es para su beneficio.
El que lee fuera de esa medida de vida, lee para su propio daño,
pues la naturaleza que entiende mal, aplica mal y se vuelve engreída,
sabia y confiada según la carne,
todavía está obrando en él. Este es propenso a establecer sus propias
interpretaciones en lugar del significado del Espíritu de Dios,
y además, a condenar todo lo que no afirme ni concuerde con su propio entendimiento.

El verdadero nacimiento es manso, tierno, gentil, temeroso delante del Señor,
espera en Él; a menudo le clama al Señor que no permita que sea engañado,
ni que algo equivocado se levante en él, ni que reciba algo como verdad,
excepto aquello que Dios sabe que es verdad.
Cuando al Señor le complace dar el verdadero conocimiento,
este es mantenido en la justicia del Señor, en Su vida, en Su voluntad, en Su sabiduría, etc.
Pero el nacimiento incorrecto no es así,
sino que es sutil en la búsqueda y formación de ideas, y las mantiene con sutileza,
y atrae la parte incorrecta en otros para que concuerden
y admitan lo que él propone y sostiene como verdad.

Hay una sabiduría en el hombre que está en contra de Dios.
Esta sabiduría se opone a la sabiduría de Dios de dos maneras:
Ya sea de manera directa y contradictoria, o de manera secreta, sutil y socavadora.
Ahora, ningún hombre puede ir a Dios,
o verdaderamente entender o recibir las cosas de Dios,
excepto en la medida que esta sabiduría llegue a ser confundida
y destruida en él por la luz y poder de Dios.
Todas sus fortalezas, todas sus imaginaciones sutiles,
todos sus razonamientos y consultas deben ser destruidas y llevadas a nada,
antes de que la verdad de Dios pueda tener pleno lugar y poder en el corazón.

Ahora bien, cuando esta falsa sabiduría es verdaderamente develada y el alma la niega,
vigilando contra ella y volviéndose a la verdadera sabiduría,
el hombre espera en Dios correctamente,
lee las Escrituras correctamente y llega al verdadero sentido,
entendimiento y experiencia de ellas.
Pero si en algún momento se queda sin esto, queda expuesto a la trampa del enemigo,
al entendimiento equivocado de la Escritura y a la confianza carnal que surge de esto.
De modo que, tras asumir un malentendido de una Escritura,
incluso se atreverá a hablar mal de las cosas celestiales y espirituales que son de Dios.
¡Oh,
cuánto destruye y enreda esta sabiduría! ¡Cuánto ha destruido y enredado a muchos hoy,
que piensan que están muy a favor de Dios en esas cosas y prácticas,
en las que están directamente en contra de Él!

Ahora noten bien: El Espíritu, la verdad, la vida, la sustancia, es de Dios para siempre,
y el espíritu inmundo no puede entrar a esto,
ni el vientre inmundo concebirlo ni darlo a luz.
Sin embargo, en cuanto a la letra, el caparazón, la figura externa,
el relato y la descripción externa de las cosas, etc., el otro espíritu,
sabiduría y naturaleza en el hombre puede leerlos y adivinar, transformar, recibir,
creer y edificar según la carne.
Aquí está el fundamento y surgimiento del anticristo y de Babilonia,
en aquellos que levantan un edificio, conocimiento, fe, esperanza, iglesia, adoración,
deberes, ordenanzas, justificación, santificación, etc.,
en imitación de Sión. Pero estas cosas no son la cosa en sí,
sino falsas representaciones de la cosa; ya sea porque fueron inventadas por el hombre,
o porque alguna vez fueran designadas y utilizadas por el Espíritu
del Señor. Pues hay poca diferencia entre inventar una cosa nueva,
y hacer uso de una cosa vieja que una vez fue de Dios, pero que ahora es entendida,
guardada y practicada fuera del sentido,
luz y guía de Su Espíritu (en otro espíritu y de acuerdo con otra sabiduría).

Esta no es la forma correcta de reforma, a saber,
el regreso a las cosas externas y de la letra,
las cuales eran practicadas por los judíos en sus días,
o por los anteriores cristianos en sus días. La forma correcta
es retornar al Espíritu en el que caminaban ellos,
y experimentar (en la verdadera vida y guía de esta) lo que Este
enseña y requiere que sea guardado y practicado hoy.
Porque hay cosas cuyo valor no está en sí mismas,
sino en el hecho de que Dios las requiere,
y el espíritu incorrecto puede entrar en tales cosas.
Y el Señor puede sacar a Su pueblo de esas cosas (así como
lo hizo del patio externo al edificio o templo interno,
por medio de Su luz y Espíritu en el interior,
cuando les dio el patio externo a los gentiles.
Apocalipsis 11:1-2). El que es encontrado en estas cosas después de que
Dios se las ha dado a los gentiles y sacado a Su pueblo de ellas,
ya no es reconocido o aceptado por Dios en ellas,
aunque tenga paciencia de él en el tiempo de su ignorancia.
Sin embargo,
si permanece en tales cosas después de la manifestación de la luz y su testimonio,
el Señor no tendrá paciencia de él,
sino que lo condenará y tratará con él como transgresor del pacto
en el que se experimenta la vida y la paz con Él.

Por lo tanto, en todas las cosas que conciernen a Dios,
ya sea en la lectura de las Escrituras,
oración o ejecución de cualquier cosa llamada deber y ordenanza, ¡oh,
muéstrense cristianos en verdad, al esperar conocer a su Guía y Líder,
y los verdaderos límites que están establecidos por Dios!
Pues así pueden servir a Dios en la verdadera fe, Espíritu y entendimiento, o sea,
en eso que Dios sabe que es verdadero,
y no en lo que ustedes falsamente interpretan como verdadero.
Porque noten: Si ustedes son cristianos, ¿acaso no están en Cristo y Cristo en ustedes?
¿Acaso no deben sentir Su vida y la guía de Su Espíritu,
para que puedan vivir en el Espíritu, caminar en el Espíritu, leer en el Espíritu,
orar siempre en el Espíritu, creer en el Espíritu,
adorar en el Espíritu y en el santo entendimiento de Su verdad, la cual es de Él?

Aquel que quiera ser correcto en religión, debe tener un correcto comienzo.
¿Cómo es esto?
Debe comenzar en el Espíritu, es decir, su conocimiento, su fe, su esperanza, su paz,
su gozo, su justicia, su santidad, su adoración, etc., deben comenzar en el Espíritu.
Debe salir de su propio espíritu, de su propia sabiduría,
de los consejos y pensamientos de su propio corazón,
y esperar en Aquel que comienza la obra de regeneración y vida en el corazón.

Después,
debe diligentemente vigilar contra ese espíritu y
sabiduría de donde el Señor lo ha sacado,
para que nunca entren de nuevo en él. Pues ese espíritu
y esa sabiduría se esforzarán por guiarlo fuera del camino,
con semejanzas y falsas imágenes de las cosas, con conocimiento falso,
con una fe que no es verdaderamente de Dios ni de la misma
naturaleza con la que el alma sintió al principio.
Se le presentarán con falsas esperanzas, falsos temores, falsos gozos,
una falsa justicia y santidad, que no son de Cristo ni según las Escrituras,
sino sólo lo que el hombre concibe de ellas.
Porque el hombre, que una vez gustó la verdad, y en alguna medida juzgó correctamente,
puede errar después en su gusto y juicio, y luego, tomar lo incorrecto por verdadero,
por no aferrarse a lo que le dio anteriormente el verdadero sabor.

Ahora bien, el que quiere encontrar la verdadera religión, la religión del evangelio,
debe encontrar el poder, recibir el poder, creer, habitar y actuar en el poder.
Porque Cristo fue hecho rey, sacerdote y profeta,
'`no según la ley de un mandamiento carnal,
sino según el poder de una vida indestructible,`' y Su pacto no es como el antiguo,
en palabra o letra, sino en el mismo poder y vida.
Por tanto, el conocimiento aquí, la fe aquí, la esperanza aquí, etc., no son de la letra,
sino de la vida.
El que recibe este conocimiento, recibe conocimiento vivo.
Esta fe da victoria sobre la incredulidad y sobre
ese espíritu cuya fuerza radica en la incredulidad.
Esta esperanza purifica el corazón, así como Él es puro.
El que recibe la justicia de este pacto, recibe una vestidura viva,
la cual tiene poder en ella sobre la muerte y la injusticia.
El comienzo de esta religión, de este poder y pacto santo e interno, es dulce,
pero el progreso puro y la continuación de este es mucho más placentero,
en la medida que el Señor da experimentar el crecimiento
y la frescura viva y dulce de este.
Aunque hay tentaciones, temores, problemas, pruebas, oposiciones y grandes peligros,
tanto en el interior como en el exterior,
el alma que se mantiene hacia la vida (a la que se volvió
primero) encuentra que el yugo es fácil y la carga ligera,
según son cambiadas la mente y la voluntad por el poder,
y ayudadas y asistidas por el Señor en su sujeción al poder.

Por tanto,
que el Señor Dios de las tiernas misericordias elimine las piedras
de tropiezo y guíe las almas errantes (que están enredadas en sus
propios pensamientos y razonamientos acerca de la letra),
a lo que es Espíritu y vida.
Porque el Espíritu y la vida estaban antes que la letra
y exceden la letra (con su dispensación) en gloria,
y deben permanecer después, y ser el reposo, gozo, vida,
paz y porción del alma por los siglos de los siglos.
Así que, honren la letra, creyendo sus testimonios con respecto a Cristo,
quien es el Pastor, el camino, la verdad, la vida misma,
a quien el alma es llevada y en quien el alma debe esperar la vida.
Y tras haber recibido vida de Él, moren, permanezcan y crezcan en Aquel que es la vida.
No retrocedan a nada que sea de la letra o sin vida,
no busquen gloria en el conocimiento o en las descripciones literales de las cosas,
sino avancen en la dispensación espiritual y celestial de vida y poder.
La ley era letra, el evangelio es vida y poder.
La ley era la sombra de los bienes venideros, pero el evangelio es la sustancia, la vida,
la virtud, el Espíritu de lo que la ley representaba.
A partir de aquí el cristiano debe brotar, la Jerusalén de arriba debe ser su madre,
y el Espíritu Santo el que lo engendra.
Aquí la verdad, dulzura y cumplimiento de las palabras es conocido,
sentido y experimentado, es decir,
en eso que las comprende y les da su debido peso y medida.
Porque nadie puede entender las palabras del Espíritu,
excepto aquel que está en el Espíritu,
y entonces conoce el lugar de las palabras que salieron del Espíritu,
y al Espíritu del que salieron las palabras.
¡Oh, esto es precioso!
Pero no será experimentado por el disputador sabio, sino únicamente por el viajero serio,
que primero es quebrantado y roto en pedazos en su propia sabiduría, y después es sanado,
conducido y guiado por el Espíritu de sabiduría, que es el Guía seguro e infalible.
