== Prefacio

=== Acerca de Isaac Penington

Isaac Penington (1616-1679) era el hijo mayor de un bien
conocido político Inglés y un Congregacionalista Puritano.
Fue criado en una familia rica e influyente,
y "`cultivado y pulido con una buena y amplia educación.`"^
footnote:[Tomado del testimonio de Thomas Ellwood con respecto a Isaac Penington.
Escrito con motivo de la muerte de Penington.]
Sin embargo, las aspiraciones de Penington, desde sus primeros días,
estaban enteramente fijadas en las cosas de arriba y no
en las muchas cosas del mundo que estaban a su alcance.
Él dice de sí mismo: "`Desde mi niñez mi corazón fue apuntado hacia el Señor,
de quien me ocupé y a quien busqué desde mis tiernos años. Yo sentía que
no podía estar satisfecho con (ni buscar) las cosas de este mundo perecedero,
las cuales naturalmente expiran,
sino que deseaba un verdadero sentido y unidad con lo que permanece para siempre.`"
De hecho,
el hambre y la desesperación de Penington por el verdadero conocimiento
y experiencia de Dios (como los lectores de este volumen reconocerán
sin duda) fue un sello distintivo en su vida.
Buscando, encontró; llamando,
la puerta se abrió delante de él. Buscó al Señor con todo su corazón, mente y fuerza,
y no cabe duda de que el Señor fue encontrado por él.

Isaac Penington vivió en una época de turbulencia política,
social y religiosa inigualable en Inglaterra.
En los treinta años durante los cuales Penington escribió sus cartas y documentos,
Inglaterra experimentó una guerra civil, el juicio y la ejecución del rey Carlos I,
el turbulento reinado de Oliver Cromwell seguida del sangriento regreso de Carlos II,
la terrible Peste de 1665 y el Gran Incendio de Londres en 1666,
después de lo cual los franceses se unieron a Holanda en guerra contra Inglaterra.
En medio de estos atribulados tiempos,
el Señor levantó a un pueblo que experimentó y predicó el
evangelio de Jesucristo de una manera posiblemente desconocida
para el mundo desde los tiempos de los primeros Apóstoles.
La Sociedad de Amigos original (que en desprecio eran llamados
Cuáqueros) era un pueblo cuyo cristianismo se encontraba y fluía
desde la luz y la vida de Jesucristo reinando en el hombre interior.
En su búsqueda de Dios,
Isaac Penington se volvió a esta luz y pronto se convirtió en un pastor entre este pueblo,
y un maestro de la verdad que el Señor estaba restaurando para Su cuerpo.

Las obras recopiladas de Isaac Penington fueron publicadas por primera vez en 1681,
apenas dos años después de su muerte.
Una segunda edición se imprimió en 1761, que consta de cuatro volúmenes.
Una tercera edición apareció en 1784 y una cuarta (que está disponible
en línea en varios formatos digitales) fue impresa en 1863.
En la década de 1990,
Quaker Heritage Press transcribió y reimprimió la edición de 1863
de sus obras completas en cuatro volúmenes de tapa dura,
la cuales se pueden comprar a través de su sitio web en www.qhpress.org.
Aunque el lenguaje es un poco más arcaico y la puntuación más complicada,
recomiendo fuertemente estos cuatro volúmenes para el estudiante serio de Penington.

=== Acerca de los Cuáqueros

Según la autobiografía de George Fox,
el nombre Cuáquero se originó con un magistrado llamado Gervase Bennet.
"`Bennet,`" dice Fox, "`fue la primera persona que nos llamó cuáqueros,
porque les ordené que temblaran ante la palabra del Señor.`" Así,
el nombre Cuáquero comenzó como una forma de ridiculizar la advertencia de George Fox,
pero pronto fue ampliamente aceptada y utilizada
tanto por los cuáqueros como por sus enemigos.

En mi opinión,
la obra del Señor en y a través de los cuáqueros
originales del siglo XVII fue un retorno a la vida,
luz,
poder y pureza originales que los primeros apóstoles
conocieron y proclamaron como el evangelio de Jesucristo.
Estos hombres y mujeres vieron al Señor, crecieron en Su vida y al igual que su Maestro,
fueron odiados, calumniados y perseguidos por ello.

Sin embargo, como sucede a menudo con movimientos genuinos del Espíritu de Dios,
sus enseñanzas y prácticas fueron rápidamente malinterpretadas,
corrompidas y mal representadas por las generaciones
sucesivas de aquellos que llevaban su nombre.
Las costumbres,
los principios y las formas externas pueden transmitirse de una generación a la siguiente,
pero la vida de Cristo debe nacer y experimentarse en cada alma individual.
Así es que los cuáqueros de hoy tienen poco o ningún parecido espiritual con sus antepasados.
La vida que una vez reinó en los corazones hambrientos
del siglo XVII ha sido en gran medida abandonada,
y la mayoría de los cuáqueros se ha convertido en una mezcolanza de doctrinas ateas,
causas terrenales y tradiciones religiosas.
Penington todavía es venerado por muchos como un padre fundador del movimiento,
pero la mayoría de los que lo respetan por su inteligencia, devoción o sufrimientos,
también se esconden de la luz que él conocía y amaba tanto.

Como con todas nuestras publicaciones,
se pueden obtener copias gratuitas de este libro a través de Market
Street Fellowship visitando www.marketstreetfellowship.com.
La editorial requiere que también haga copias disponibles
para la venta en línea a través de Amazon,
pero todos los ingresos de las ventas van a la distribución
gratuita de esta y otras publicaciones.

Jason R. Henderson
Septiembre, 2014
