== Capítulo I. Biografía de Isaac Penington

[.blurb]
=== Lo siguiente es un testimonio de Thomas Ellwood con respecto a Isaac Penington, que contiene dos relatos autobiográficos tomados de los propios escritos de Penington.

[.asterism]
'''

Yo +++[+++Thomas Ellwood]
no ignoro que muchos testimonios vivos y de peso ya han sido dados
por testigos verdaderos y fieles sobre la muerte de Isaac Penington,
y que bien podrían parecer suficientes para excusar el mío,
pero aún así no me siento libre,
me siento presionado en mi espíritu a escribir también
unas líneas en relación a mi querido amigo fallecido,
a quien le debo afecto y gratitud.
Lo amé, y lo amé en su totalidad, y estoy seguro que muy merecidamente,
porque él era digno de ser amado por todos los hombres, pero sobre todo por mí,
con quién él había sido abundantemente amable.
Pues el día que le agradó al Señor despertar mi alma
y llamarme de las contaminaciones del mundo,
tanto en lo que se refiere a la adoración como a la manera de vivir
(por lo que me convertí en objeto de burla de mi país,
de desdén y desprecio de mi familia y conocidos, y de cierta manera, también en paria),
¡cuán bienvenido fui entonces para él! ¡Cuán cariñosamente me recibió!
¡Cuán atentamente cuidó de mí! ¡Cuán tierna y paternalmente me vigiló,
para que yo no fuera arrastrado hacia atrás o de alguna manera engañado,
por la sencillez de la verdad tal como la había recibido!

¡Jamás podré olvidar su amor o dejar que su múltiple bondad se deslice de mi mente!
No, el recuerdo de él es placentero para mí y pienso en él con deleite.
Porque como amigo, verdaderamente lo amaba;
como padre (porque tal fue su cuidado hacia mí), lo reverenciaba; como anciano,
lo honraba, y eso (como bien lo merecía) con doble honor.
Mi espíritu estaba realmente unido al de él;
mi alma estaba vinculada y unida a él en el santo pacto de la vida,
el cual la muerte no ha sido capaz de disolver.
Por tanto, te suplico que tengas un poco de paciencia conmigo,
quienquiera que seas tú, y bajo cuyos ojos tienen ocasión de caer estas líneas,
si me tomo la libertad de expresar mis sentimientos por este amado amigo;
si te parecen un tanto particulares, sabe tú que mi relación con él fue así.

Él estaba naturalmente equipado con una inteligencia aguda y excelente,
una que fue cultivada y pulida con una buena y amplia
educación. Su disposición era cortés y afable,
libre de orgullo y pretensión. Su discurso ordinario era jovial y agradable,
ni taciturno ni liviano, sino inocentemente dulce,
templado con una gravedad tan seria que hacía que
sus conversaciones fueran placenteras y provechosas.

Desde su infancia (como lo oí decir ocasionalmente) tuvo una inclinación religiosa^
footnote:[En los escritos de Penington la palabra religión no tiene
las connotaciones negativas con las que a veces se asocia hoy.
Aquí es usada de manera general, para referirse al conocimiento y adoración de Dios.]
y buscó al Señor desde su tierna edad,
y aunque el camino de la verdad no le era manifiesto en ese entonces,
como le fue manifiesto más adelante,
en algunas ocasiones tuvo toques y muestras verdaderas de la vida
y revelaciones de las cosas celestiales (aunque no tan clara,
ni tan pura,
ni tan permanentemente como después). Al principio la manifestación
de la verdad no estuvo exenta de dudas y recelo acerca de ella,
como él mismo contó. Por un tiempo tampoco estuvo libre
de disputas y razonamientos contra la pequeñez de su apariencia.
Sin embargo, después de que le agradó al Padre, en la riqueza de Su gracia,
revelar a Su Hijo en él, otorgándole con ello ver y en definitiva conocer la buena,
agradable y perfecta voluntad de Dios,
¡con cuánta alegría la recibió! ¡Con cuánta disposición
se inclinó hacia ella! ¡Con cuánta presteza rindió su cuello
al yugo de Cristo! ¡Con cuánta constancia y deleite lo llevó!

¿Consideró él entonces los placeres de los tiempos,
o valoró las preferencias y honores del mundo?
No. (A pesar de que en aquel momento vivía en el favor y en la abundancia de ello).
Él le dio la espalda a todo eso y tuvo '`por mayores riquezas el vituperio de
Cristo que los tesoros de los egipcios,`' y echando su corona a los pies de Jesús,
voluntariamente se convirtió en un tonto para el mundo y para la sabiduría del mismo,
para poder ser verdaderamente hecho sabio para Dios.
Y en esto ciertamente obtuvo su deseo,
porque así como él honró al Señor y lo prefirió por encima de todo,
así lo honró el Señor altamente.
Generosamente le dio de la verdad y de la sabiduría celestial adornada con humildad,
de modo que fuera enseñado, y sin embargo, humilde;
lleno de conocimiento (conocimiento celestial), y sin embargo, no envanecido por este.
Y así como había recibido gratuitamente del Señor,
gratuita y prestamente comunicó lo mismo a los que estaban en la necesidad de consejo,
asesoría,
información o dirección en su viaje hacia la patria
celestial (tal como testifican las siguientes páginas).

Él estaba equipado y muy bien provisto para este
servicio por las experiencias de su propio viaje,
porque el Señor lo había conducido a través de mucha angustia y dificultad,
y a través de muchas tentaciones, pruebas y ejercicios,
por medio de lo cual lo había tratado y probado.
No sólo había pasado a través del Mar Rojo y del desierto,
sino que también había visto el fondo del Jordán, y el sostén y la entrega
del brazo del Señor a través de todo lo que había conocido y sentido.
De ahí que fuera capaz de dar una palabra de sabiduría a los confundidos caminantes,
una palabra de ánimo a los cansados y desfallecidos viajeros,
una palabra de alivio al alma afligida y de consuelo al espíritu herido.
¡Oh,
cuán dulcemente la oí fluir de él! ¡Cómo caía como el rocío
y cómo destilaba como suave lluvia! ¡Cuán tierno,
cuán compasivo,
cuán lleno de ternura y simpatía estaba él! Sin ninguna duda sus palabras
fueron muchas veces como '`manzanas de oro con figuras de plata.`'

El Señor estaba verdaderamente con él y Su poder celestial a menudo llenó Su templo.
El Espíritu del Señor reposaba sobre él y Sus frutos eran
abundantemente producidos a través de él en amor,
gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre y templanza.
Así de ricamente habitaba la palabra del Señor en
él. Su deleite estaba en el servicio a Dios,
a lo cual se entregó completamente y pasó la mayor parte de su tiempo.
Públicamente, en reuniones esperando en Dios; privadamente,
visitando y ministrando a los que estaban en dificultades
o de alguna forma afligidos en mente o cuerpo;
en la casa,
en frecuentes retiros interiores con el Señor. Oraba fervorosamente y muy a menudo,
porque el Espíritu de gracia y súplica había sido derramado abundantemente sobre él,
mediante el cual a menudo luchaba con el Señor y no en vano.

Leía profusamente las Sagradas Escrituras con gran deleite y provecho.
No lo hacía como un negocio superficial o formal,
ni buscaba elegir el significado mediante su ingenio o aprendizaje natural,
sino que con una gran serenidad de mente y reverencia de
espíritu, esperaba recibir el verdadero sentido de ellas,
proveniente de la revelación del Espíritu divino, mediante
el cual fueron inspirados los autores de las Escrituras.
Grande y fuerte era la aflicción de su espíritu por la salvación de otros.
Su amor fluía y su corazón anhelaba de manera muy
especial en busca de los profesantes de la religión,
por quienes continua y sinceramente trabajaba tanto por palabra como por escrito,
para que salieran de las sombras y finalmente heredaran la sustancia.
Y bendito sea el Señor,
porque por la poderosa operación del Espíritu de Dios muchos se convirtieron
a la verdad y muchos fueron confirmados en ella a través de su ministerio.
Pues el Señor estaba con él y hablaba por medio de él,
por lo que su enseñanza era con autoridad divina
y '`con demostración del Espíritu y de poder.`'

Para el mundo y sus afanes era un completo extraño,
pero en las cosas de Dios profundamente experimentado,
pues tenía '`puesta la mira en las cosas de arriba,`' '`su ciudadanía
estaba en el cielo`' y '`su vida escondida con Cristo en Dios.`' Él no
era más que un peregrino en la tierra que ya se ha ido a casa.
En su familia era un verdadero modelo de bondad y de piedad,
no sólo por su ejemplo solemne,
sino por sus valiosas instrucciones y exhortaciones a la piedad.
Era para su esposa, un esposo muy cariñoso; para sus hijos, un padre amoroso y tierno;
para sus siervos, un señor suave y gentil; para sus amigos, un amigo firme y fiel;
para los pobres, compasivo y generoso; para el resto, cortés y amable.
Era muy celoso de la verdad; incansable en la promoción de la verdad,
valiente e intrépido en su defensa, fiel en el testimonio de ella,
paciente y alegre en su sufrimiento por la misma.
Ciertamente era un hombre bueno y piadoso,
uno que verdaderamente temía a Dios y que vigilantemente renunciaba a toda maldad.

Cuán grandes y diversas fueron sus pruebas durante la época de sus anteriores creencias.
Cuán ferviente y apremiante fue su espíritu después, en pos del puro disfrute de Dios.
Cuán extraños y admirables fueron los tratos del Señor con él. Cuán lejos
llegó él para ver el fruto de la aflicción de su alma y estar satisfecho,
el cual él conocía mejor que cualquiera,
pues ocasionalmente diseminó por aquí y por allá un indicio
de ello en varios fragmentos de los siguientes libros.
Una vez pensé en recogerlos y presentarlos,
pero al encontrar entre sus papeles sueltos un resumen
escrito por su propia mano más de doce años antes,
cuando estaba en cautiverio por amor a Cristo y enfermo cerca de la muerte,
escogí transcribirlo aquí.

[.offset]
El primer relato que Isaac Penington da de sus aflicciones espirituales es como sigue:

[.embedded-content-document.testimony]
--

"`Este es un breve relato verdadero y fiel acerca de mí mismo,
en referencia a mis aflicciones espirituales y a los tratos del Señor conmigo.
Digo verdadero y fiel porque es la verdad, y porque no es dado en mi propia voluntad,
sino en la voluntad del Señor, y requerido de mí en este momento para Su servicio.
El relato es como sigue:

"`Yo he sido un hombre de tristeza y aflicción desde mi infancia,
uno que ha sentido necesidad del Señor y ha llorado
en busca de Él. Fui separado por Él del amor,
naturaleza y espíritu de este mundo y vuelto en espíritu
hacia Él casi desde que puedo recordar.

"`En la consciencia de mi estado de perdición, busqué al Señor, leí las Escrituras,
vigilé mi propio corazón, clamé al Señor por lo que sentía que me hacía falta,
bendije Su nombre por lo que misericordiosamente había hecho por mí y depositado en mí, etc.
Me entregué a la práctica fiel de lo que leía en las Escrituras
y que de acuerdo a mi entendimiento era el camino de Dios,
y me sentí contento por encontrar oprobio,
oposición y diferentes tipos de sufrimientos que
el Señor se agradaba en permitirme experimentar.
No puedo sino decir, que el Señor fue bueno conmigo, porque me visitó, me enseñó,
me ayudó y testificó Su aceptación por mí muchas veces,
para frescura y gozo de mi corazón delante de Él.

"`Pero mi alma no estaba satisfecha con lo que encontraba, ni podía estarlo,
al ser más vivificada y más presionada en mi espíritu
en pos de un conocimiento más completo,
seguro y satisfactorio.
Yo añoraba el sentido, la vista y el deleite de Dios,
tal como se testifica en las Escrituras que había
sido sentido y disfrutado en tiempos antiguos.
Claramente vi que se había producido una interrupción
en el fluir, y que quedábamos cortos del poder,
la vida y la gloria de la que los primeros cristianos participaron.
Nosotros no teníamos el Espíritu, no estábamos en la fe,
ni caminábamos ni vivíamos en Dios como ellos lo hicieron.
Ellos habían sido acercados al Monte Sión, a la Jerusalén celestial, etc.,
mientras que nosotros apenas teníamos un conocimiento
literal o una percepción de lo que eran esas cosas.
Entonces vi que el curso total de la religión entre
nosotros era, en su mayor parte, sólo palabras,
en comparación con lo que ellos habían sentido, disfrutado, poseído y vivido.

"`Esta consciencia me enfermó el corazón y me hizo clamar profundamente a Dios,
escudriñar cuidadosamente las Escrituras y esperar en Dios,
todo con el fin de poder recibir el sentido y el entendimiento puro de ellas, de la luz,
en la luz y por medio de la ayuda de Su Espíritu.
Lo que el Señor depositó en mí en ese estado, lo recuerdo
delante de Él con agradecimiento hasta este día,
porque era mi Dios, compasivo y vigilante,
aunque todavía no me había enseñado en cómo fijar mi mente
en Él. Luego fui conducido (de verdad fui conducido,
no corrí por mí mismo) a separarme de la adoración del mundo y a reunirme con una sociedad;^
footnote:[Quiere decir que él dejó las formas tradicionales de adoración
cristiana y comenzó a reunirse en una congregación independiente formada
por otros que compartían su hambre e insatisfacción]
para esto tanto las Escrituras como el Espíritu de Dios me dieron testimonio.
Hay un recuerdo y un testimonio en mi corazón hasta
este día de lo que experimentamos entonces,
y de la guía y la ayuda que sentimos, sin embargo,
faltaba algo y equivocamos nuestro camino.
Porque donde debimos haber presionado hacia adelante en espíritu y poder,
nos corrimos demasiado hacia afuera en la letra y la forma,^
footnote:[Penington a menudo usa la palabra forma para expresar alguna expresión,
estructura o sistema físico o externo usado en la religión.]
y aunque el Señor nos ayudó de muchas maneras,
en esto estaba contra nosotros y trajo oscuridad, confusión y dispersión sobre nosotros.
Yo estaba profundamente quebrantado y ensombrecido,
y a veces me quedaba quieto por largo tiempo en ese estado de tinieblas,
lamentándome y clamando secretamente al Señor de noche y de día. Otras
veces corría buscando lo que pudiera aparecer o brotar en otros,
pero nunca me topé con algo en lo que hubiera la menor respuesta para mi corazón,
salvo en un pueblo, quienes tenían un toque de la verdad,
pero nunca le dije mucho a ninguno de ellos,
ni los sentí en absoluto capaces de alcanzar mi condición.

"`Al fin, después de muchas aflicciones, andanzas y dolorosos ruegos,
me encontré con algunos de los escritos de este pueblo llamado Cuáqueros,^
footnote:[Tristemente,
los Cuáqueros de hoy tienen poca o ninguna semejanza espiritual a sus predecesores.]
a los que les eché una mirada ligera y desdeñosa,
como si quedaran muy cortos de aquella sabiduría, luz,
vida y poder que yo anhelaba y buscaba.
En algún momento después de eso,
tuve la oportunidad de reunirme con algunos de ellos, y unos pocos fueron
movidos por el Señor (ahora entiendo que fue así) a venir a verme.
Recuerdo claramente como ellos alcanzaron la vida de Dios en mí desde el puro principio,
la cual respondió a sus voces y provocó que brotara en mí un gran amor por ellos.
Aún así,
en mis razonamientos con ellos y en las disputas en mi mente con respecto a ellos,
yo estaba muy lejos de aceptar que ellos conocieran verdaderamente al Señor,
o que aparecieran/vinieran en esa vida y poder que mi condición necesitaba,
y mi alma esperaba.
De hecho, cuánto más conversaba con ellos, más me parecía en mi entendimiento y razón,
que yo los superaba y los aplastaba bajo mis pies como una generación pobre, débil,
tonta y despreciable.
Sentía que tenían una pizca de la verdad en ellos y algunos deseos sinceros hacia Dios,
pero que estaban muy lejos de un entendimiento claro y completo
del camino y voluntad de Dios;
ese era el efecto que me quedaba después de casi todas las conversaciones.
Ellos seguían alcanzando mi corazón y yo los sentía en un lugar secreto en mi alma,
lo cual hacía que mi amor hacia ellos continuara, e incluso,
que en algunas ocasiones se incrementara.
Sin embargo, yo sentía que cada día mi entendimiento los superaba más, y en consecuencia,
cada día los menospreciaba más.

"`Después de mucho tiempo me invitaron a escuchar
a uno de ellos hablar, como me habían invitado a menudo,
pues ellos, con tierno amor, seguían compadeciéndome,
y sentían mi carencia de lo que ellos poseían.
Hubo una respuesta en mi corazón,
y yo fui con temor y temblor y con deseos del Altísimo
(Quien está sobre todo y todo lo sabe),
de no recibir nada como verdad que no fuera de Él,
ni resistir nada que fuera de Él, sino de inclinarme delante
de la aparición del Señor mi Dios y ante ninguna otra.
Y en efecto, cuando llegué sentí la presencia y el poder del Altísimo entre ellos,
sentí que palabras de verdad provenientes
del Espíritu de verdad llegaron a mi corazón y a
mi consciencia, y pusieron al descubierto mi estado ante la presencia del Señor.
Sí, y no sólo sentí palabras y demostraciones desde afuera,
sino también que lo que estaba muerto cobraba vida
y que la Semilla se levantaba de manera tal,
que mi corazón (en la certeza de la luz y en la claridad de su verdadero sentido) dijo:
__'`¡Este es Él,
no hay otro! ¡Este es a quien he esperado y buscado desde mi infancia!
¡Aquel que ha estado cerca de mí siempre, y que a menudo ha engendrado
vida en mi corazón! ¡A quien no conocía claramente,
ni cómo recibirlo o morar con Él!`'__ Y entonces,
en esta consciencia (en el ardor y quebrantamiento de mi espíritu),
me rendí al Señor para ser Suyo,
tanto a la espera de una mayor revelación de Su Semilla en mí,
como para servirle en la vida y poder de Su Semilla.

"`Con lo que me topé después de esto en mis aflicciones, en mi espera
y en mis ejercicios espirituales, no debe ser pronunciado.
Sólo puedo decir en términos generales, que me topé con la fuerza misma del infierno.
El cruel opresor rugió sobre mí y me hizo sentir la amargura de su esclavitud,
mientras tenía algún poder sobre mí. Sí,
yo sentía al Señor lejos de mí y lejos de la voz de mi clamor como para ayudarme.
Me encontré además con profundas sutilezas y artimañas,
las cuales tenían como fin engañarme con esa sabiduría que
parece capaz de hacernos sabios en las cosas de Dios,
aunque en realidad es una tontería y una trampa para el alma,
pues intenta llevarla de regreso al cautiverio donde
prevalece la contienda del enemigo.
Externamente me encontré con la oposición de mi querido padre, mi familia, mis siervos,
la gente y los gobernantes del mundo, por ninguna otra causa sino por temerle a Dios,
adorarlo como Él requería de mí, e inclinarme ante Su Semilla, la cual es Su Hijo;
¡Quién debe ser adorado por hombres y ángeles para siempre!
El Señor mi Dios sabe, delante de quien mi corazón y mis caminos están,
que Él me preservó en amor por ellos.
En medio de todo lo que sufrí por causa de ellos,
Él me preservó. ¡Bendito sea Su puro y santo nombre!

"`Tal vez algunos quieran saber qué he encontrado finalmente.
Mi respuesta es: He encontrado a la SEMILLA.
Entiende esta palabra y estarás satisfecho y no preguntarás más. He encontrado a Dios.
He encontrado a mi Salvador.
Él no se ha presentado sin Su salvación,
sino que debajo de Sus alas he sentido caer la sanidad sobre mi alma.
He encontrado el verdadero conocimiento, el conocimiento de vida, el conocimiento vivo,
el conocimiento que es vida.
El conocimiento que tiene la verdadera virtud en él, y en el que
se ha gozado mi alma en la presencia del Señor. He encontrado al
Padre de la Semilla y en la Semilla lo he sentido ser mi Padre.
Allí he visto Su naturaleza, Su amor, Su compasión, Su ternura, lo cual ha fundido,
vencido y cambiado mi corazón delante de Él. He encontrado la fe de la Semilla,
la que ha hecho y hace lo que la fe del hombre jamás podrá hacer.
He encontrado el verdadero nacimiento,
el nacimiento que es heredero del reino y hereda el reino.
He encontrado el verdadero espíritu de oración y súplica
que triunfa en el Señor, y extrae de Él lo que la condición necesita;
en el que el alma Lo busca siempre en la voluntad,
tiempo y forma que son aceptables para Él. ¿Qué más diré? He encontrado la verdadera paz,
la verdadera justicia, la verdadera santidad, el verdadero reposo del alma,
la morada eterna en la que el redimido habita.
Sé que todo esto es verdadero en Aquel que es verdadero, y que no soy capaz de dudar,
disputar o razonar en mi mente acerca de esto
según premanezca ahí,
donde se ha recibido la plena seguridad y satisfacción.
También sé muy bien y con claridad de espíritu,
dónde están las dudas y las disputas y dónde están la certeza y la plenitud,
y que en la tierna misericordia del Señor he sido
preservado fuera de lo uno, y dentro de lo otro.

"`El Señor sabe que no digo estas cosas de manera jactanciosa,
que preferiría estar hablando de mi nadedad, mi vacío,
mi debilidad y mis múltiples enfermedades, las cuales siento más que nunca.
El Señor ha quebrantado la parte del hombre en mí; soy un gusano,
nadie delante de Él. No tengo fuerza para hacer algo bueno
o útil para Él. No puedo vigilarme o preservarme a mí mismo;
no.
Diariamente siento que no puedo mantener viva mi propia
alma, y que soy más débil delante de los hombres;
sí, más débil en mi propio espíritu, es decir, en mí mismo, como nunca lo he sido.
Sin embargo, no puedo sino pronunciar alabanza a mi Dios,
porque siento Su brazo extendido hacia mí, y que la
debilidad que siento en mí no es pérdida,
sino ganancia delante de Él.

"`Escribo estas cosas no teniendo un fin propio, absolutamente no,
sino porque esta mañana sentí que se me requería,
y en sumisión y sujeción a mi Dios me entregué a la tarea,
dejándole el éxito y servicio de esto a Él.`"

[.signed-section-signature]
Isaac Penington

[.signed-section-context-close]
La Cárcel de Aylesbury, 15 del mes tercero, 1667

--

[.offset]
Otro relato del viaje espiritual de Penington, el cual él titula,
__"`A Brief Account of My Soul`'s Travel Towards the Holy Land`"__
(Una Breve Reseña del Viaje de Mi Alma Hacia la Tierra Santa),
ha sido preservado y es como sigue:

[.embedded-content-document.testimony]
--

"`Desde mi infancia mi corazón estuvo dirigido hacia el Señor,
por quien me interesé y a quien busqué desde tierna edad.
Yo sentía que no podía estar satisfecho con las cosas de este mundo que perece,
las que naturalmente desaparecen (ni tampoco las buscaba),
sino que deseaba una verdadera experiencia y unidad con lo que permanece para siempre.
Es cierto que había algo dentro de mí en aquel entonces (la Semilla de
eternidad) que leudaba y balanceaba mi espíritu casi continuamente,
pero yo no lo conocía con claridad como para volverme
y rendirme a eso totalmente y con entendimiento.

"`En este estado de ánimo busqué fervientemente al Señor,
dedicándome a oír sermones y a leer los mejores libros que podía encontrar,
especialmente las Escrituras, las cuales eran muy dulces y agradables para mí. Sí,
yo deseaba y presionaba fervientemente en pos del conocimiento de las Escrituras,
pero tenía mucho temor de recibir la interpretación que los hombres hacen de ellas,
o de fijar cualquier interpretación sobre ellas por mí mismo.
Por tanto, esperé y oré mucho,
pidiendo que el Espíritu del Señor me diera el verdadero entendimiento de ellas,
y que Él me dotara principalmente de ese conocimiento que puede santificar y salvar.

"`Y en efecto, palpablemente recibí de Su amor, de Su misericordia y de Su gracia
(lo cual sentía moverse libremente hacia mí)
en los momentos en que yo más consciente estaba de mi propia indignidad
y tenía menos expectativas de la manifestación de ello.
Sin embargo,
yo estaba extremadamente enredado con respecto a la Elección y
a la Condenación (habiendo bebido de la doctrina de la predestinación,
como era entonces sostenida por los más estrictos de los llamados Puritanos),
temeroso de que a pesar de todos mis deseos y búsqueda del Señor,
en Su decreto Él me hubiera dejado de lado.
Sentía que sería terriblemente amargo para mí llevar
Su ira y ser separado de Su amor para siempre;
pensaba que si Él lo había decretado así, así sería,
y que (a pesar de mis justos inicios y esperanzas) yo debía caer y perecer al final.

"`Pasé muchos años en este gran problema y dolor,
lamento y lucha contra corrupciones y tentaciones secretas (ampliado
por no encontrarse el Espíritu de Dios en mí y conmigo,
como había leído y creído que lo habían tenido los anteriores
cristianos), y caí en una gran debilidad de cuerpo.
A menudo me tiraba en la cama retorciéndome las manos y llorando amargamente,
suplicándole fervientemente al Señor cada día que se apiadara de mí,
que me ayudara contra mis enemigos y me conformara a la imagen
de Su Hijo por medio de Su propio poder renovador.

"`Finalmente,
(cuando mi ser estaba prácticamente agotado y el pozo de la desesperación
estaba cerrando su boca sobre mí) surgió la misericordia y vino la liberación,
el Señor mi Dios se adueño de mí y selló Su amor hacia mí. La luz brotó en mi interior
e hizo que tanto las Escrituras como la creación externa fueran gloriosas a mis ojos,
es decir, que todo a la redonda fuera dulce, agradable y jubiloso.

"`Pero pronto sentí que ese estado era demasiado alto y glorioso
para mí y que yo no era capaz de permanecer en él,
porque abrumaba mis facultades naturales.
Por tanto, bendiciendo el nombre del Señor por Su gran bondad,
le pedí que tomara de mí lo que yo no era capaz de llevar, y que
me diera una medida de Su luz y de Su presencia que fuera apropiada
para mi presente estado y que me hiciera apto para Su servicio.
Eso fue prontamente removido de mí, aún así, un sabor permaneció conmigo,
en el que tuve dulzura, consuelo y refrigerio por una larga temporada.

"`Pero mi mente no sabía entonces cómo volverse y habitar con lo que me daba el sabor,
ni leer correctamente lo que Dios escribía a diario en mi corazón;
aquello que sobradamente se manifestaba ser de Él,
por medio de Su virtud viva y pura operación sobre
mí. Yo consideraba las Escrituras como mi regla,^
footnote:[La palabra regla es usada para referirse a aquello que gobierna,
rige o tiene verdadera autoridad en la vida de un creyente.]
y sopesaba las apariciones internas de Dios a mí por lo que estaba escrito externamente.
Yo no me atrevía a recibir algo directamente de Dios, tal como surgía de la fuente,
sino de manera indirecta.
En eso limité al Santo de Israel y herí ampliamente mi propia alma,
tal como sentí y llegué a entender más tarde.

"`Sin embargo, el Señor fue tierno conmigo y extremadamente condescendiente,
y abría las Escrituras para mí cada día, enseñándome,
instruyéndome y dándole calidez y consuelo a mi corazón por medio de ellas.
Él verdaderamente me ayudó a orar, a creer, a amarlo y amar Su aparición en cualquiera.
Sí,
a amar con verdadero amor a todos los hijos de los hombres
y a toda Su creación. Pero persistía el hecho en mí,
de que yo no conocía la aparición del Señor en mi espíritu y que
lo limitaba a las palabras de las Escrituras antiguamente escritas.
Un tejido de conocimiento creció a partir de las Escrituras, y se convirtió
en mi regla perfecta (como yo pensaba) en lo que se refiere a mi corazón,
mis palabras, mis caminos, mi adoración. Con mucha seriedad de espíritu y oración a Dios,
me encontré a mí mismo ayudando a construir una congregación independiente,
en la que el sabor de la vida y la presencia de Dios eran frescos para mí;
creo que todavía viven algunas personas de dicha congregación que pueden testificar.

"`Este era mi estado cuando fui golpeado,
quebrantado y angustiado por el Señor. Quedé confundido en mi adoración,
confundido en mi conocimiento y fui despojado de
todo en un día (esto es difícil de decir).
Me convertí en motivo de asombro para todos los que me veían.
Quedé expuesto y desnudo para todo el que preguntara,
y me esforcé en encontrar la causa por la que el Señor había tenido que tratar así conmigo.
Al principio algunos estaban seguros de que yo había pecado y provocado al Señor a hacerlo,
pero después de examinar las cosas a fondo y de abrirles y desnudarles mi corazón,
no recuerdo que alguno retuviera esa opinión con
respecto a mí. Mi alma recuerda el ajenjo y la hiel,
la extrema amargura de aquel estado,
y en el recuerdo de aquello permanece humillada en mí delante del Señor.
¡Oh,
cuánto deseé poder llegar delante de Él y como Job adrede suplicar!
¡Es que en verdad yo no tenía sentido de culpa alguno sobre mí,
sino que estaba enfermo de amor por Él y había quedado como el que
es violentamente arrancado del seno de su amado! ¡Oh,
qué gusto si me hubiera encontrado con la muerte!
Porque yo estaba cansado todo el día y temeroso de la noche,
y cansado durante la noche y temeroso del día siguiente.

"`Recuerdo mi doloroso y amargo lamento por el Señor. Cuán a menudo dije: '`Oh, Señor,
¿por qué me has abandonado?
¿Por qué me has roto en pedazos?
No tengo ningún deleite sino Tú,
ningún deseo sino Tú. Mi corazón se inclinó por completo a servirte, e incluso,
(según me ha parecido) me has equipado por medio de muchos profundos
ejercicios y experiencias para Tu servicio.
¿Por qué me haces tan miserable?`' A veces lanzaba mis ojos
sobre una escritura y mi corazón se derretía en mi interior.
En otros momentos deseaba orar a mi Dios como lo había hecho antes,
pero me daba cuenta de que yo no Lo conocía,
que no sabía cómo orar o cómo acercarme a Él. En
esta condición anduve para arriba y para abajo,
de montaña a collado, y de una persona a otra con un grito en mi espíritu:
'`¿Pueden ustedes darme noticias de mi amado?
¿Dónde mora Él? ¿Dónde aparece?`' Pero sus voces aún eran
extrañas para mí y me apartaba de ellas triste,
oprimido y humillado en espíritu.

"`Ahora bien, seguramente todas las personas serias,
sobrias y sensatas estarán listas para preguntar,
cómo llegué finalmente a conocer satisfactoriamente al Señor;
o si yo Lo conozco sin ninguna duda y si estoy verdaderamente satisfecho.
__Sí,
efectivamente estoy satisfecho en mi corazón. Mi
corazón está verdaderamente unido Al que anhelaba,
en un pacto eterno de vida pura y paz.__

"`¿Cómo llegué a eso?
El Señor abrió mi espíritu.
El Señor me dio la experiencia segura y perceptible de la Semilla pura,
la cual había estado conmigo desde el principio.
El Señor hizo que Su santo poder cayera sobre mí y me diera tal
demostración y experiencia interior de la Semilla de vida,
que grité en mi espíritu: __'`¡Este es Él! ¡Este es Él! ¡No hay otro,
nunca lo hubo! ¡Siempre estuvo cerca de mí aunque yo no lo conocía (no tan palpable
ni tan claramente como ha sido revelado ahora en mí y para mí por el Padre)! ¡Oh,
que ahora yo pueda estar unido a Él y que sólo Él viva en mí!`'__ Y así,
en la voluntad que Dios había obrado en mí (el día
de Su poder sobre mi alma) me rendí para ser instruido,
ejercitado y conducido por Él, y para que en la espera y experiencia de Su santa Semilla,
fuera sacado de mí todo lo que no podía vivir con la Semilla,
lo que obstaculizaba la morada y reinado de Ella
mientras permaneciera ahí y tuviera poder.
He pasado a través de dura angustia y combatido contra
muchos tipos de aflicciones y tentaciones,
en todo lo cual el Señor ha sido misericordioso conmigo,
ayudándome y preservando la chispa de vida en mí,
en medio de muchas cosas que me han sobrevenido y
cuya naturaleza trataba de apagarla y extinguirla.

"`Ahora, habiéndome encontrado con el verdadero camino y caminado con el Señor,
en el que todos los días la certeza, sí,
y la plena seguridad de la fe y del entendimiento son al fin obtenidas,
no puedo callar (el verdadero amor y la vida pura se agitan en mí y me mueven),
sino que debo testificar de ello a los demás:
Al retirarse interiormente y esperar experimentar algo del Señor,
algo de Su Santo Espíritu y poder,
descubriendo y apartándose de aquello que es contrario a
Él y entrando en Su naturaleza santa e imagen celestial;
entonces, conforme la mente es unida a esto, algo es recibido; algo de verdadera vida,
algo de verdadera luz, algo de verdadero discernimiento es recibido, en lo cual,
mientras la persona no se exceda (sino habite en dicha medida) estará a salvo.
Pero es fácil moverse de esto y difícil de permanecer
en ello y no adelantarse a Su guía. Sin embargo,
el que experimenta la vida, el que empieza en la vida, ¿no empieza de forma segura?
El que espera, teme y no se aleja de su Capitán que va adelante,
¿no continúa de forma segura?
Sí, muy segura, hasta que llegue a estar tan asentado y establecido en la virtud,
demostración y poder de la Verdad, que nada puede prevalecer para moverlo.

"`Bendito sea el Señor,
porque hay muchos en este día que pueden verdadera y fielmente
testificar que han sido llevados por el Señor a este estado.
Esto lo hemos aprendido del Señor, es decir,
no lo hemos aprendido mediante un gran esfuerzo o por una mente ambiciosa,
sino permaneciendo humildes y estando contentos con un poco.
Si solamente es una miga de pan (aún es pan),
si solamente es una gota de agua (aún es agua),
nos contentamos con eso y se lo agradecemos al Señor.
No lo hemos obtenido por medio de ingenio,
sabia búsqueda y profunda consideración en nuestra propia sabiduría y razón,
sino que en la quieta, mansa y humilde espera,
encontramos llevado a la muerte lo que no puede conocer los misterios del reino de Dios,
y encontramos vivificado y creciendo en la vida lo que debe vivir.

"`Por tanto, aquel que verdaderamente quiera conocer al Señor,
reciba la exhortación con respecto a su propia razón y entendimiento.
Yo la consideré seria e íntegramente.
Oré, leí las Escrituras y fervientemente,
deseé entender y descubrir si lo que esta gente llamada Cuáqueros testificaba
era el único camino y verdad de Dios (como parecían sugerir).
Por todo esto se multiplicaron sobre mí prejuicios y fuertes razonamientos contra ellos,
los cuales me parecían irrefutables,
pero cuando el Señor reveló Su Semilla en mí y tocó mi corazón con Ella,
pronto los percibí hijos del Altísimo, maduros en Su vida,
poder y santo dominio (tal como ve el ojo interior al ser abierto por el Señor),
haciendo surgir en mí una gran reverencia de corazón y alabanzas al Señor,
Quien había aparecido poderosamente entre los hombres en estos últimos días.

"`Por tanto, en la medida que Dios los acerque a Sí mismo en cualquier aspecto,
ríndanse en fidelidad a Él. Desprecien la vergüenza, tomen la cruz, que de hecho,
es un camino que se opone al hombre y del que su sabiduría se avergonzará grandemente.
Sin embargo, esa sabiduría debe ser negada, es de la que hay que volverse,
pero esperen y ríndanse ante los acercamientos secretos
y perceptibles del Espíritu de Dios.
Presten atención,
el que quiera entrar en el nuevo pacto deberá entrar en obediencia al mismo.
La luz de vida, la cual Dios ha escondido en el corazón, es el pacto.
En este pacto Dios no da conocimiento para satisfacer la vasta,
ambiciosa y amplia sabiduría del hombre, no;
da conocimiento vivo para alimentar lo que es vivificado por Él. Dicho
conocimiento es dado en la obediencia, y es muy dulce y precioso para el
estado del que sabe cómo alimentarse de él. Sí,
este conocimiento es verdaderamente de una naturaleza excelente, pura y preciosa,
y un poquito de él pesa más que el grande y vasto conocimiento intelectual,
que el espíritu y la naturaleza del hombre tanto aprecian y persiguen.

"`En verdad, amigos,
soy testigo en este día de una gran diferencia entre la dulzura
de entender el conocimiento de cosas tal como se expresan en las
Escrituras (del que me alimenté abundantemente antes),
y la dulzura de saborear la vida escondida,
el maná escondido en el corazón (el cual es mi comida ahora).
¡Bendito sea para siempre el Señor mi Dios y Salvador!
¡Ojalá que otros tengan un sabor verdadero,
cierto y real de la vida,
virtud y bondad del Señor tal como se revela en el corazón! En definitiva,
no suscitará sino la verdadera hambre, inflamará la verdadera sed;
hambre y sed que no podrán ser satisfechas nunca sino por el verdadero
pan y por el agua que proviene de la fuente viva.
A esto nos ha traído el Señor (en la ternura de Su amor y riqueza de Su gracia y misericordia),
y nosotros deseamos y procuramos ferviente y rectamente que otros sean
traídos también. Deseamos que otros puedan esperar correctamente (en el
verdadero silencio de la carne y en la pura quietud del espíritu),
deseamos que en el debido tiempo del Señor reciban lo que
responde al deseo de la mente y del alma despierta,
y las satisface con la verdadera y preciosa sustancia para siempre.`"

[.signed-section-signature]
Isaac Penington

[.signed-section-context-close]
Impreso en 1668

--

A Isaac Penington no sólo se le dio creer, sino también sufrir en el nombre de Cristo.
Sus encarcelamientos fueron muchos, y muchos de ellos prolongados,
a los que con gran temple y quietud de mente se sometió. Pero debido a que un
relato general de sus encarcelamientos tal vez no satisfaga el deseo del lector,
presentaré aquí más específicamente un breve informe de sus sufrimientos.

Su primer encarcelamiento fue en la cárcel de Aylesbury en los años 1661 y 1662,
siendo entregado allí por adorar a Dios en su propia casa.^
footnote:[Debido a la inseguridad política de ese tiempo,
había sido pasada una ley que prohibía toda reunión religiosa,
salvo aquellas que tomaban lugar en el tiempo y en
el lugar autorizados por la Iglesia de Inglaterra.
Por causa de la consciencia, Penington y muchos otros continuaron reuniéndose en casas.]
Por diecisiete semanas, una gran parte de ellas en invierno,
se le mantuvo en una fría y muy incómoda habitación sin chimenea.
A partir de ese duro uso de su delicado cuerpo contrajo una enfermedad grande y violenta,
por la que después de varias semanas no era capaz de darse vuelta en su cama.

Su segundo encarcelamiento fue en el año 1664,
siendo sacado de una reunión en la que con otros estaba esperando
pacíficamente en el Señor. Fue enviado a la cárcel de Aylesbury,
donde nuevamente permaneció prisionero de diecisiete a dieciocho semanas.

Su tercer encarcelamiento sucedió en el año 1665,
siendo tomado en la calle de Amersham, junto con muchos otros,
mientras llevaban y acompañaban el cuerpo de un amigo muerto a la tumba.^
footnote:[Este cortejo fúnebre era considerado una "`reunión
religiosa ilegal`" por los sacerdotes y magistrados,
quienes estaban empeñados en perseguir a los primeros Cuáqueros.]
De ahí fue enviado otra vez a la cárcel de Aylesbury.
Este encarcelamiento condujo a una orden de destierro, pero por un mes más o menos.

Su cuarto encarcelamiento sucedió el mismo año, 1665,
cerca de un mes después de ser liberado del anterior.
Hasta ese momento sus encarcelamientos habían sido ordenados por los magistrados civiles,
pero ahora, para que experimentara la seriedad de cada uno, cayó en manos militares.
Un rudo soldado sin más orden judicial que la espada que blandía,
llegó a su casa y le dijo que había ido a buscarlo
para llevarlo delante de Sir Philip Palmer,
uno de los líderes del ejército del condado.
Penington fue dócilmente y lo enviaron a la cárcel de Aylesbury con una
guardia de soldados y una especie de orden de la corte que decía:
"`El carcelero debe recibirlo y mantenerlo en lugar seguro durante
la voluntad del conde de Bridgewater,`" quien al parecer,
había concebido un grande e injusto descontento contra este inocente hombre.
Y aunque ese fue el año de la plaga^
footnote:[La Gran Plaga de 1665-1666 fue la última gran epidemia de peste
bubónica que ocurrió en Inglaterra y mató un estimado de 100,000 personas,
// lint-disable invalid-characters "%"
aproximadamente el 15% de la población de Londres.]
y se sospechaba que la enfermedad estaba en la cárcel,
el conde de Bridgewater no fue convencido por las fervientes súplicas
de personas de considerable alcurnia y poder en el condado,
de que trasladara a Isaac Penington a otra casa en el pueblo y
lo mantuviera prisionero ahí hasta que la cárcel fuera limpiada.
Tras la muerte de un prisionero en la cárcel,
la esposa del carcelero (su esposo estaba ausente) dio permiso
de que se moviera a Isaac Penington a otra casa,
donde estuvo encerrado cerca de seis semanas.
Después de esto, por la intervención del conde de Ancram,
un comunicado fue enviado del mencionado Philip Palmer,
mediante el cual Penington fue puesto en libertad después
de haber sufrido prisión tres cuartas partes del año,
con evidente peligro de su vida y por ninguna ofensa.

Cuando tenía cerca de tres semanas de estar en su casa,
una partida de soldados del llamado Philip Palmer (por orden del conde Bridgewater,
como se informó), llegó a su casa,
lo agarró en la cama y se lo llevó nuevamente a la cárcel de Aylesbury.
Allí, sin ninguna causa demostrada o delito comprobado,
lo mantuvieron preso un año y medio en cárceles tan frías,
húmedas e insalubres que estuvo cerca de que le costara la vida,
lo que le procuró tal enfermedad que yació débil por varios meses.
Al fin un conocido de su esposa mediante un _habeas corpus_,
lo llevó a la corte del King`'s-Bench,
en la que (con el asombro del tribunal de que un hombre estuviera largamente
prisionero por nada) finalmente fue liberado en el año 1668.
Este fue su quinto encarcelamiento.

Su sexto encarcelamiento sucedió en el año 1670 en la cárcel de Reading,
donde fue a visitar a sus amigos que sufrían ahí por el testimonio
de Jesús. Tras el aviso de esta visita a un tal Sir William Armorer,
juez de paz del condado,
Penington fue llevado abruptamente delante de él y entregado a la cárcel,
convirtiéndose así en compañero de sufrimiento de aquellos que había ido a visitar.
Ahí continuó prisionero un año y tres cuartos,
y fue llevado bajo sentencia de "`premunire,`"^
footnote:["`Premunire`" era un juicio legal diseñado para privar de derechos
a los que se negaban a jurar formalmente lealtad al rey de Inglaterra.
Los que estaban bajo la sentencia de "`premunire`" eran considerados traidores a su país,
perdían todo derecho a propiedades y posesiones,
quedaban fuera de la protección de los reyes, y por lo general,
eran encarcelados de por vida.]
pero al fin el Señor lo liberó.

Así, a través de muchas tribulaciones entró en el Reino, habiendo sido ejercitado,
tratado,
probado y aprobado por el Señor. Estuvo en la guerra largo tiempo,
y como un buen soldado soportó la lucha de aflicciones,
pero habiendo peleado la buena batalla y mantenido la fe,
ha terminado en el buen tiempo del Señor su travesía y ha
ido a poseer la corona de justicia guardada para él,
y para todos los que aman la brillante aparición del Señor.
Por muchos años fue un fiel obrero en la viña del Señor,
pero ya ha cesado de su labor y ahora sus obras le siguen.
Caminó con Dios y ya no existe.
Para el Señor vivió y en el Señor murió,
y por el Espíritu del Señor es pronunciado bendito: Por tanto,
bendito sea para siempre el nombre del Señor.
