[#el-camino, short="El Camino de la Vida y de la Muerte"]
== Capítulo II. El Camino de la Vida y de la Muerte Hecho Manifiesto y Puesto Delante de los Hombres

=== Prefacio

¡Sean sabios, ustedes sabios!
Abran el ojo y el oído que han sido cerrados,
cierren el ojo y el oído que han sido abiertos.
Ya no tropiecen, no sea que caigan y no se levanten más. Sé que no pueden ver,
pues el ojo equivocado está abierto y el Señor le ha escondido Su sabiduría a ese ojo.
Vuélvanse pobres en espíritu,
no sea que al final resulten ser el hombre rico a quien el Señor devolvió con las manos
vacías. Vendan todo rápido para que tengan lo necesario para comprar la Perla.
Ustedes no conocen la aparición del Señor porque en su sabiduría la han desdeñado.
Los niños, los tontos, los ciegos pueden ver el camino y entrar a la vida,
pero ustedes que son hombres, que son sabios, que tienen ambos ojos,
que pueden juzgar en la religión y determinar lo que es ortodoxo y erróneo, no pueden.

¡Escuchen para que sus alma puedan vivir!
Ustedes no saben cuán corto es su tiempo.
El día de su visitación pasa más rápido de lo que son conscientes.
El clamor se ha extendido: ¡He aquí,
el novio viene y su esposa ha sido preparada para su cama!
Quítense las vestiduras viejas y pónganse las nuevas.
Tengan el verdadero aceite en sus lámparas, o la puerta del
reino será cerrada sobre ustedes y no podrán entrar.
En términos sencillos, sepárense de toda su religión,
la que ustedes han obtenido en su propia sabiduría, la que ha crecido en la apostasía,^
footnote:[Penington y muchos de sus contemporáneos,
usan la palabra __'`apostasía`'__ para referirse a la condición de la iglesia cristiana,
que comenzó poco después de los primeros apóstoles, hasta la época de estos escritos.
En sus mentes, la forma predominantemente muerta,
externa y centrada en el hombre de la religión cristiana,
que había prevalecido a lo largo de los siglos,
era la gran apostasía que había sido predicha por Cristo y los apóstoles.]
la que sólo puede tener justa demostración en las tinieblas y no puede soportar
la escrutadora luz del día del Señor. Agárrense de la verdadera religión,
de la verdadera justicia, de la verdadera inocencia y pureza de Cristo.
Lo viejo debe ser eliminado, realmente eliminado, y lo nuevo debe ocupar su lugar.
La carne y el yo deben ser absolutamente destruidos.
Si van a entrar en Su reino,
nada que no sea Cristo debe ser hallado en ustedes, y ustedes
no deben ser hallados en otro lugar que no sea Cristo,
porque nada impuro puede entrar.

Quiten, por tanto, todo orgullo, pasión, enemistad y razonamientos carnales.
Busquen lo que es puro y entren en ello tomando la cruz contra todo lo que es contrario.
Vuélvanse de todas las imaginaciones y conceptos acerca de los
significados de las Escrituras en la mente incierta y extraviada,
y vayan a lo que es infalible.
Conozcan el silencio de la parte carnal,
para que la parte espiritual crezca en sabiduría, aprendan en el espíritu,
conozcan la Palabra de Dios y sean capaces de hablarla.

Mi corazón es para ustedes y esto ha sido escrito desde él,
no para enojarlos o avergonzarlos,
sino para provocarlos a celos contra ese espíritu oscuro y malo
que los lleva a la destrucción bajo la apariencia y forma de luz.
Mi deseo no es gloriarme por encima de ustedes,
pues mi alma yace en vergüenza y tristeza delante
del Señor y en el oprobio de mi propia apostasía,
y mi búsqueda de alivio del mundo (al haberme vuelto del Señor que me había herido,
para buscar consuelo en las vanidades terrenales) no será fácilmente recobrado.

El Señor fue bondadoso conmigo al quebrantarme en mi religión,
y visitarme con la dulce y preciosa luz de Su propio Espíritu,
pero yo no la conocía. Tengo que reconocer que yo sentía Su poder
sobre mí, y que pude haberlo entendido en verdad si le hubiera permitido que purificara
mi corazón y me engendrara a la imagen de Dios,
pero demandé que ese poder apareciera mediante una
demostración frente a mi razón y mi sabiduría terrenal,
y ante la falta de satisfacción, lo negué y me rebelé contra Él. Y así,
tras de toda mi miseria anterior,
perdí mi entrada y sembré semillas de nueva miseria y tristeza para mi propia alma,
las cuales he cosechado desde entonces.

Así que ahora no tengo motivos para jactarme sobre otros,
sino de tumbarme en humillación de espíritu.
Lo que escribo no lo hago en mi propio poder y autoridad,
sino para llevar a otros al poder y a la autoridad, a lo cual es bueno
para mí como para otros, estar sujetos.
¡Quiera el Señor desnudarnos de nuestro propio entendimiento
y de esa justicia nuestra (aunque la hemos llamado de Él),
para que así nos reunamos y recibamos de Su entendimiento,
seamos vestidos con Su justicia y experimentemos Su reposo y paz!

Feliz aquel que lo pierda todo para ganar esto,
pero el que conserve lo que tiene por mucho tiempo, al final lo perderá todo.
Por tanto,
ya no sean sabios a los ojos de la carne o de acuerdo a lo que el hombre llama sabiduría,
sino sean _verdaderamente_ sabios.

[.old-style.bold]
=== ALGUNAS POSICIONES / Con Respecto a la Apostasía del Espíritu y de la Vida Cristiana

[.alt]
==== Posición I

Ha habido una gran apostasía^
footnote:[Alejamiento, salida]
del Espíritu de Cristo y de la verdadera luz y vida del cristianismo;
dicha apostasía comenzó en los días de los apóstoles y maduró rápidamente después.

Ahora bien, que los apóstoles y los cristianos de sus días tenían el verdadero Espíritu,
la verdadera luz y la verdadera vida, no creo que sea negado.
"`Sabemos que somos de Dios y que el Hijo de Dios ha venido,
y nos ha dado entendimiento para conocer al que es verdadero; y estamos en el verdadero,
en su Hijo Jesucristo.
Este es el verdadero Dios, y la vida eterna.`"
(1 Juan 5:19-20) Ellos habían nacido verdaderamente
de Dios y sabían que el Hijo de Dios había venido,
que habían recibido de Él, verdadero entendimiento,
y que habían recibido la verdadera luz y el verdadero conocimiento en dicho entendimiento.
Tanto el entendimiento como el conocimiento estaban
arraigados y cimentados en el que es verdadero,
donde también estaban la posición y permanencia de ellos ("`estamos en el verdadero`"),
y donde experimentaban el verdadero Espíritu, el verdadero Dios y la verdadera vida,
es decir, la vida eterna.
Que tenían el verdadero Espíritu de Dios,
según Gálatas, "`Y por cuanto sois hijos,
Dios envió a vuestros corazones el Espíritu de su Hijo...`"
(Gálatas 4:6); que tenían la verdadero luz de Dios,
según 2 Corintios, "`Porque Dios, que mandó que de las tinieblas resplandeciese la luz,
es el que resplandeció en nuestros corazones...`"
(2 Corintios 4.6); que tenían la verdadera vida del Espíritu y en el Espíritu,
según Gálatas, "`Si vivimos por el Espíritu, andemos también por el Espíritu...`"
(Gálatas 5:25); es generalmente reconocido con respecto a ellos.

Bien, las Escrituras hacen mención de una apostasía de esto,
que incluso comenzó en los días de los apóstoles y se completó
no mucho después. El apóstol Pablo dice expresamente de esto,
"`no vendrá sin que antes venga la apostasía, y se manifieste el hombre de pecado,
el hijo de perdición`" (2 Tes.
2:3). Cristo había mostrado y declarado la senda de la vida,
había revelado la verdadera iglesia como "`columna y baluarte de la verdad,`" contra la
cual las puertas del infierno no prevalecerían. Había enviado al verdadero Espíritu,
el que podía "`llevar a toda verdad`" y preservar en la verdad.
Pero leemos en 2 Tesalonicenses, que antes debía surgir "`un hombre de pecado,
un hijo de perdición,`" quien en misterio,
obraría contra lo mostrado y declarado por Cristo,
y provocaría un alejamiento de todo eso.
El apóstol no sólo tocó esto por escrito aquí, también lo había dicho en persona,
como lo refiere más adelante. Se pueden dar muchas más escrituras como evidencia.

Cristo predijo los falsos profetas.
Mateo 7:15 dice, "`Guardaos de los falsos profetas,
que vienen a vosotros con vestidos de ovejas, pero por dentro son lobos rapaces.`"
El Señor envió profetas verdaderos bajo la ley y
les dio verdaderas visiones para que las declararan.
Cristo envió verdaderos apóstoles y ministros bajo el evangelio y les dio la verdad,
la cual debían predicar y propagar.
Pero luego también se levantaron falsos profetas,
falsos apóstoles y falsos ministros que nunca fueron enviados
por Cristo y que nunca recibieron la verdad de Su Espíritu.
Estos no llegaron a ser parte de la vida ni de la verdad de Cristo,
sino que se alejaron de ellas de tal modo que iniciaron una apostasía,
una separación. Cristo dijo: "`Guárdense de ellos porque vienen muy sutilmente.
Vienen vestidos de ovejas.
Se ponen vestidos de ovejas sobre sus espaldas,
y aunque es el mismo vestido que usa la oveja, no tienen la naturaleza de la oveja,
sino la naturaleza del lobo, la que anda hambrienta tras la vida de las ovejas.`"
Consideren lo siguiente: Donde hay vestidura exterior, pero no naturaleza interior;
donde hay apariencia de piedad, pero no poder;
donde hay palabras de las Escrituras y prácticas,
pero no el Espíritu de vida de donde proceden; ¡hay un falso profeta!, ¡hay un lobo!,
¡hay un apóstata!, ¡hay un engañador!

Cristo predijo de nuevo en Mateo 24:11 acerca de muchos falsos profetas,
"`Y muchos falsos profetas se levantarán, y engañarán a muchos.`"
En Mateo 24:24 dice, "`Porque se levantarán falsos Cristos, y falsos profetas,
y harán grandes señales y prodigios, de tal manera que engañarán, si fuere posible,
aun a los escogidos.`"
Y así como Cristo,
sus apóstoles después de Él y por el mismo Espíritu predijeron lo mismo.

El apóstol Pablo habló de espíritus engañadores y doctrinas de demonios,
que prevalecerían en los postreros tiempos para hacer que algunos apostataran de la fe.
(1 Tim. 4:1) Y si en aquellos días el poder de los engañadores
era tan grande como para apartar de la fe,
que en ese entonces era tan manifiesta y viva,
cuán fácil sería después mantener lejos de la verdad,
cuando la fe hacía tiempo se había perdido y sacado de la memoria, y por ello,
el engaño había entrado en su lugar y tomado su nombre.

El apóstol Pedro también predijo, "`habrá entre vosotros falsos maestros,
que introducirán encubiertamente herejías destructoras,
y aun negarán al Señor que los rescató`"; estos prevalecerían tanto que según Pedro,
"`muchos seguirán sus disoluciones,
por causa de los cuales el camino de la verdad será blasfemado`" (2 Ped.
2:1-2).

En la segunda epístola a Timoteo, Pablo habla de nuevo de los últimos días diciendo,
que los tiempos en ellos serían "`peligrosos`" (2 Tim.
3:1). Cristo había dicho, "`El amor de muchos se enfriará, y abundará la iniquidad`" (Mat.
24:12). Pablo muestra que los tiempos probarían ser
muy peligrosos por la abundancia de la iniquidad.
"`En los últimos días vendrán tiempos difíciles.
Porque los hombres serán amadores de sí mismos, avaros, jactanciosos, soberbios,
blasfemos, desobedientes a los padres, ingratos, irreverentes, sin amor, implacables,
calumniadores, desenfrenados, salvajes, aborrecedores de lo bueno, traidores, impetuosos,
envanecidos, amadores de los placeres en vez de amadores de Dios`" (2 Tim.
3:1-4 NBLH).
He aquí, el tipo de fruto que surgió de la falsa doctrina
de los falsos maestros en su apostasía de la verdad,
y sin embargo, todo esto vino "`teniendo apariencia de piedad,
pero habiendo negado su poder`" (ver. 5). Cristo envió el poder
de la piedad al mundo para someter la raíz de donde todo esto surge,
para matar interiormente la naturaleza maligna,
pero en la apostasía la naturaleza del mal no es asesinada,
porque se rechaza el poder que la mata, y se conserva la forma externa
de religión para cubrir la naturaleza maligna dentro.

Miren hacia cualquier lugar entre los líderes de la apostasía y vean:
¿Está muerto el amor al yo?
¿Está muerta la avaricia?
¿Están muertas la vanagloria y la soberbia?
¿Está muerto el amor a los deleites?
¿Están muertas las persecuciones y las opresiones?
¿Yacen en el polvo el honor y la gloria del hombre?
No, estas cosas no están muertas en los líderes de la apostasía,
sino cubiertas con una forma externa.
Todavía viven en ellos,
porque el poder con el que debieron ser asesinadas fue rechazado al comienzo,
y ahora dicho poder está perdido y es desconocido.
Donde está la Vida está el poder, y donde está el poder la naturaleza del mal es acabada,
pero donde la naturaleza del mal no es asesinada, sólo hay una apariencia de piedad,
una cubierta; un sepulcro blanqueado con podredumbre en el interior.

Los últimos días y los últimos tiempos no estaban lejos, comenzaron en seguida,
porque el apóstol exhorta a Timoteo a volverse de tales hombres.
"`...a éstos evita`" (2 Tim.
3:5), implicando que incluso entonces ya estaban esos de los que había que volverse.
Más adelante dice que ellos resisten la verdad,
como Jannes y Jambres se habían esforzado en resistir la vida y el poder que estaban
en Moisés. Así que para el momento en que el apóstol le escribió esta carta a Timoteo,
dichos hombres habían llegado.

Judas habla de "`hombres impíos que convierten en libertinaje la gracia de nuestro Dios,
y niegan a Dios el único soberano,
y a nuestro Señor Jesucristo,`" y que ya "`han entrado`" (Jud.
1:4). El apóstol Juan dice muy específicamente, "`Hijitos, ya es el último tiempo;
y según vosotros oísteis que el anticristo viene,
así ahora han surgido muchos anticristos; por esto conocemos que es el último tiempo.
Salieron de nosotros...`" (1 Juan 2:18-19). Cristo,
instruyendo a Sus discípulos con respecto a los últimos tiempos,
les dijo que se levantarían falsos cristos con gran poder de engaño. (Mat.
24:24) Ahora bien, Juan dice: "`han surgido muchos anticristos;
por esto conocemos que es el último tiempo.`"
Estos no permanecieron en la doctrina de los apóstoles que predicaban "`el evangelio
eterno,`" ni permanecieron en el Espíritu y principio en el que habían entrado,
sino que se "`salieron`" de ellos,
salieron del Espíritu (de la unción en la que tenían que mantenerse y por la
que eran mantenidos) hacia otro espíritu y predicaron otro evangelio.
El evangelio del anticristo no era el poder de Dios para destruir lo terrenal,
todo lo contrario, consistía en un conocimiento muerto y literal de las cosas,
del que lo terrenal podía alimentarse y mantenerse vivo.

Miren el estado de las iglesias de entonces,
según lo que las Escrituras registran de ellas,
y aparecerán claramente los síntomas de la apostasía.
La iglesia de Éfeso (en la que habían entrado algunos lobos rapaces, Hech.
20:29) había dejado su primer amor.
(Apoc.
2:4) Las iglesias de Galacia habían sido hechizadas y se habían apartado del evangelio.
(Gal.
3:1) La iglesia de Colosas estaba enredada y sujeta a los rudimentos del mundo,
ordenanzas (que perecen con el uso), mandamientos y doctrinas de hombres.
(Col.
2:20-22) La iglesia de Corinto también estaba siendo
turbada por los falsos profetas (2 Cor.
11:12-13), tanto así,
que el apóstol temía que la iglesia fuera corrompida por ellos (ver. 3).
En la iglesia de Pérgamo había unos que retenían la doctrina de Baal.
(Apoc.
2:14) La iglesia de Tiatira permitía que la mujer
llamada Jezabel y que se hacía llamar profetisa,
sedujera y diera a luz niños de apostasía. (Apoc.
2:20,23) La iglesia de Sardis tenía nombre de estar viva
pero estaba muerta y había manchado sus vestiduras (Apoc.
3:2,4). La iglesia de Laodicea se veía a sí misma rica, enriquecida, y
que no tenía necesidad de nada, pero era desventurada, miserable, pobre,
ciega (el ojo se había desviado) y desnuda; sin oro, sin vestido, sin colirio
(Apoc.
3:17-18). Finalmente,
todos los gentiles fueron advertidos por Pablo en
su carta a la iglesia de Roma a mirar su estatus,
para que no cayeran de la fe,
de la verdad y de la vida a la apostasía (como habían hecho los judíos),
ni experimentaran la severidad de Dios,
como también la habían experimentado los judíos. (Rom.
11: 20-22)

Es evidente, por tanto,
que en los días de los apóstoles la apostasía había
encontrado asidero y había comenzado a esparcirse.
El apóstol Juan mirando en el espíritu el estado futuro de las cosas,
la vio extendida y cubriéndolo todo;
"`todas las naciones han bebido del vino del furor de su fornicación`" (Apoc.
18:3). El camino de la verdad había sido blasfemado hacía mucho (2 Ped.
2:2), y la Roca Eterna que sólo se establece en la verdad había sido abandonada.
Todo se hizo como un mar,
se levantó la bestia (que no podía levantarse mientras el poder
de la verdad estuviera en pie) y sobre la bestia la mujer,
y en su mano la copa de engaño y desvío de la vida.
Ella les dio a beber a todas las naciones y las naciones bebieron y se embriagaron,
por lo tanto,
todas las naciones han sido envenenadas con las doctrinas
y prácticas de la apostasía. Ellas han tomado como verdad,
lo que la ramera les dijo que era verdad; han guardado como mandamientos de Dios,
lo que la ramera les dijo que eran mandamientos de Dios.
Por este medio nunca han llegado a estar casadas con Cristo, a estar unidas a Él,
a recibir la ley de vida de Su Espíritu y a experimentar
la libertad de la esclavitud de la corrupción. Por el contrario,
han estado en la cama de fornicación con la ramera y se han complacido,
saciado y satisfecho con esta fornicación. En consecuencia,
la corrupción cubrió toda la tierra.

Y aunque Dios se reservó para sí un remanente que lo adorara y
diera algún testimonio de Su verdad durante todo ese tiempo,
la "`bestia`" (que era manejada por la ramera) tenía poder sobre ellos;
poder para hacerles guerra, poder para vencerlos.
(Apoc.
13:7) La "`bestia`" tenía poder sobre toda "`tribu, pueblo,
lengua y nación`" en todas partes, para vencer a los "`santos,`"
para suprimir la verdad de la que ellos eran movidos a dar testimonio,
para establecer la adoración de la "`bestia`" y hacer
que toda la tierra cayera delante de eso.
(Apoc.
13:7-8)

Ahora bien, por lo que ha sido expresado,
¿no es manifiesto con sencillez y claridad para todo ojo,
que ha habido una gran apostasía del verdadero conocimiento de Cristo,
y que una corrupción y un poder universal de muerte se han
propagado en lugar del poder de vida y gracia de Dios?
"`La gracia de Dios que trae salvación`" ha desaparecido;
la "`abominación de la desolación`" ha tomado su lugar y lo ha
llenado todo de veneno mortal contra la verdad y contra la vida.
Así, esa enemistad contra Dios bajo la apariencia de amor y celo por Él,
ha reinado en términos generales en los corazones de los hombres
desde los tiempos de los apóstoles hasta este día presente.

[.alt]
==== Posición II

En esta gran apostasía el verdadero estado del cristianismo se ha perdido.
Si ellos apostataron del Espíritu, de la luz y de la vida,
entonces se salieron de dicho estado y lo perdieron.

Se podría describir con multitud de detalles la manera
en que el estado del cristianismo se perdió,
pero sería demasiado extenso y tedioso.
Por tanto, puede que baste exponer unos pocos ejemplos importantes.

=== 1. La verdadera regla del cristianismo se perdió.

La regla que dirige,
guía y ordena al cristiano en toda su marcha, fue apostatada y perdida.

[.discourse-part]
Pregunta: ¿Cuál es la regla^
footnote:[La palabra __regla__ se usa para referirse a eso que gobierna,
rige o tiene verdadera autoridad en la vida del creyente.]
por la que el cristiano tiene que dirigir y ordenar su curso?

[.discourse-part]
Respuesta: Ser cristiano es ser seguidor de Cristo, en consecuencia,
se debe caminar en la misma regla que caminó Cristo.
El cristiano proviene de Cristo y tiene la misma vida en él,
por lo tanto necesita la misma regla.
Cristo tenía la plenitud de vida y todos recibimos
de Su plenitud una medida de dicha vida.
"`Porque somos miembros de su cuerpo,
de su carne y de sus huesos`" (Ef. 5:30). En efecto,
nosotros salimos del mismo manantial de vida de donde salío Él,
"`Porque el que santifica y los que son santificados, de uno son todos;
por lo cual no se avergüenza de llamarlos hermanos`" (Heb.
2:11). ¿Cuál era Su regla?
¿No era la plenitud de vida que recibió? Y, ¿cuál es la regla de los que son santificados?
¿No es la medida de vida que recibieron?
¿No era la regla de Cristo la ley del Espíritu,
la ley que el Espíritu escribió en Su corazón? Y,
¿no es la regla de los cristianos la ley del Espíritu,
la ley que el Espíritu escribe en sus corazones?

¿Cómo fue hecho Cristo rey y sacerdote?
¿Fue por la ley de un mandamiento carnal o por el poder de una vida indestructible?
¿Y cómo son hechos ellos reyes y sacerdotes de Dios?
(Apoc.
1:6). ¿Es por la ley de un mandamiento carnal,
o por el poder de la misma vida indestructible?
"`He aquí que vengo para hacer tu voluntad, Dios mío`', dijo Cristo,
"`cuando entró al mundo`" (Heb.
10:7,5) Pero ¿por cuál regla?
¿Por cuál ley?
"`Tu ley está en medio de mi corazón`" (Sal.
40:8). Y el Espíritu que la escribió ahí,
es el mismo que escribe el nuevo pacto (con todas sus leyes) en el corazón de cada cristiano,
desde el más pequeño hasta el más grande.
(Heb.
8:9,10) Sí, el Espíritu que habitaba en el corazón de Cristo,
es el mismo que habita en el de los cristianos de acuerdo a la promesa del pacto.
(Ezeq.
36:27)

Esta era la regla por la que Pablo caminaba,
"`la ley del Espíritu de vida en Cristo Jesús`" (Rom.
8:1-2). Esto lo hizo "`libre de la ley de pecado y muerte.`"
¿Dónde está escrita la ley del pecado?
¿Dónde está escrita la ley de la muerte?
¿No está escrita en el corazón? ¿No debe ser escrita ahí también la ley
de justicia y vida, para que sea capaz de tratar con el pecado y la muerte?
El Espíritu forma de nuevo el corazón, forma a Cristo en el corazón,
engendra una nueva creación ahí que no puede pecar.
("`El que es nacido de Dios no peca.`") Esta es la regla de justicia,
la nueva creación o el Espíritu de vida en la nueva creación.
"`Porque en Cristo Jesús ni la circuncisión vale nada,
ni la incircuncisión,
sino una nueva creación. Y a todos los que anden conforme a esta regla,
paz y misericordia sea a ellos`" (Gal.
6:15-16). Noten, esta es la regla:
La nueva creación que es engendrada en todo el que es nacido de Dios.
"`Si alguno está en Cristo,
nueva criatura es,`" y esta nueva creación tiene que ser su regla.
En la medida que cada hombre camine de acuerdo a esta regla,
de acuerdo a la nueva creación,
de acuerdo a la ley de luz y vida que el Espíritu continuamente sopla en la nueva creación,
tiene paz.
Pero si transgrede esto y no camina según el Espíritu, sino según la carne,
camina fuera de la luz, fuera de la vida, fuera de la paz; camina en el mar,
en la muerte, en la dificultad y en la condenación. Esta es, pues,
la ley del hombre convertido: La nueva creación;
y la ley de la nueva creación es el Espíritu de vida que la engendró, que vive,
respira y emite Su ley continuamente en ella.
"`Pero vosotros tenéis la unción del Santo,
y conocéis todas las cosas`" (1 Juan 2:20). ¿Cómo
llegaron ellos a conocer todas las cosas?
¿No dice Juan que fue por "`la unción?`" La unción estaba en ellos,
una fuente o manantial de luz y vida manando en el interior
continuamente como ríos y corrientes de vida;
no necesitaban ningún otro maestro,
ni en la verdad ni en el camino de vida (ver. 27). El "`Consolador`"
renovaba sus corazones suficientemente y los llevaba a toda verdad.

Escudriñen las epístolas de los apóstoles, y los encontrarán testificando
que el Señor mandó Su Espíritu a los corazones de los cristianos.
Encontrarán exhortaciones de no entristecer o apagar al Espíritu,
sino de seguir según fueran guiados.
Ellos tenían que "`vivir en el Espíritu`" y "`caminar en el Espíritu.`"
(Gal.
5:25) El Espíritu tenía que caminar, vivir y producir Su propia vida y poder en ellos.
(2 Cor.
6:16) ¿Cuál puede ser la regla apropiada y completa de los hijos e hijas de Dios,
sino la luz del Espíritu de vida que recibieron de su Padre?
De esta manera elevó Dios la condición del creyente por
encima de la condición de los judíos bajo la ley.
Porque el judío externo tenía la ley escrita por el dedo de Dios en tablas de piedra,
pero nosotros tenemos la ley escrita por el dedo de Dios en las tablas de nuestros corazones.
La de ellos era una ley externa, a distancia,
y los labios del sacerdote estaban para preservar
el conocimiento de la misma e instruirlos en ella.
Pero ahora hay una ley interna, a mano,
la inmediata luz del Espíritu de vida brillando directamente en el corazón.
Los que conocen esta ley interior no necesitan hombre que les enseñe,
tienen el Espíritu de profecía en ellos y enseñanzas vivas provenientes de Él
continuamente.
Estos son hechos reyes y sacerdotes para Dios,
tal como el pacto de la ley sólo pudo representar.

El evangelio es la sustancia de todo lo que las sombras contenían en la ley.
El cristiano es aquel que entra en esa sustancia,
vive en esa sustancia y en quien esa sustancia vive.
Su regla es la sustancia misma,
en la que él vive y la que vive en él. Cristo es la sustancia,
Él vive en el cristiano y el cristiano en Él. Cristo vive en él
por Su Espíritu, y él vive en Cristo por el mismo Espíritu.
Ahí vive y tiene comunión con el Padre y con el Hijo, en la luz en la que Ellos viven,
y no mediante ninguna regla externa.
(1 Juan 1:6-7)

[.discourse-part]
Pregunta: Pero ¿cuál es la regla ahora en la apostasía?

[.discourse-part]
Respuesta:
Entre los católicos la regla son las Escrituras interpretadas
por la iglesia (como ellos se llaman a sí mismos),
con una mezcla de sus propios preceptos y tradiciones.
Entre los protestantes la regla son las Escrituras,
según las entienden por su propio estudio,
o según reciben entendimiento de ellas de los hombres que consideran ortodoxos.
De aquí se levantan continuamente diferencias, grupos y sectas;
unos siguiendo una interpretación, otros siguiendo otra.
Esta es una apostasía grave, la cual es raíz, manantial y fundamento de todo lo demás,
porque el que se pierde en el principio,
el que comienza su religión sin la verdadera regla,
¿cómo podrá seguir correctamente después?

[.discourse-part]
Objeción: ¿Pero no son las Escrituras la palabra de Dios?
¿No debe ser la palabra de Dios la regla de un cristiano?
Si todo el mundo fuera dejado en su propio espíritu,
¡cuánta confusión e incertidumbre produciría esto!

[.discourse-part]
Respuesta: Las Escrituras no son la Palabra viva,
no son la señalada por Dios para ser la regla de un cristiano,
pero contienen palabras habladas por el Espíritu de Dios
que testifican y apuntan a la Palabra que debe ser la regla.
"`Ustedes examinan las Escrituras porque piensan tener en ellas la vida eterna.
¡Y son ellas las que dan testimonio de Mí! Pero ustedes
no quieren venir a Mí para que tengan esa vida`" (Juan 5:39-40;
NBLH).
Las Escrituras deben ser escudriñadas por el testimonio que dan de Cristo,
y cuando dicho testimonio es recibido, Cristo es encontrado y la vida recibida.
Pero los fariseos antiguamente y los cristianos desde
entones (me refiero a los cristianos de nombre),
escudriñan las Escrituras pero no van a Cristo por la vida,
sino que se aferran a la letra de las Escrituras y se oponen a la vida con la letra.
Se mantienen a sí mismos alejados de la vida por
medio de su sabiduría y conocimiento de la letra.
De esta manera ponen las Escrituras en el lugar de
Cristo, y así ni honran a Cristo ni a las Escrituras.

No habría sido honor para Juan el Bautista haber sido tomado como la Luz;
el honor de Juan era apuntarla.
Tampoco es ningún honor para las Escrituras ser llamadas la Palabra de Dios,
su honor es develar y testificar de la Palabra.
Ahora oigan lo que las Escrituras llaman la Palabra: "`En el principio era la Palabra,
y la Palabra era con Dios, y la Palabra era Dios`" (Juan 1:1; JBS).
"`Y aquella Palabra fue hecha carne`" (Juan 1:14, JBS).
Este era el nombre de Cristo cuando vino en la carne a sembrar Su vida en el mundo.
Cuando viene al mundo de nuevo de una tierra lejana
a pelear contra la bestia y el falso profeta,
y a limpiar la tierra de la fornicación e ídolos de la ramera, tiene el mismo nombre,
"`su nombre es la Palabra de Dios`" (Apoc.
19:13). Pedro llama esto "`la palabra de Dios que vive y permanece para siempre`" (1 Ped.
1:23). Esta Palabra que vive y permanece para siempre
es la Palabra que ellos predicaron (ver. 25),
y los que creyeron no sólo aplaudieron las palabras
que los apóstoles hablaron de la Palabra,
sino que también recibieron aquello de lo que hablaban,
"`la Palabra injertada,`" la que es recibida con espíritu manso,
quieto y sumiso y que "`puede salvar el alma`" (Sant.
1:21). Es la "`Palabra de fe,`" es decir, la que está "`cerca,
en el corazón y en la boca`" (Rom.
10:8). Es la Palabra que está a la puerta del corazón
y pide que la dejen entrar ("`He aquí,
yo estoy a la puerta y llamo,`" Apoc.
3:20). Cuando se le permite entrar, habla en el corazón lo que tiene que ser oído y hecho.
Está cerca, está en el corazón y en la boca, ¿con qué fin?
"`Para que ustedes puedan oírla y hacerla.`"
La Palabra viva,
que es "`viva y eficaz y más cortante que espada de dos filos,`"
divide en la boca y divide en el corazón lo vil de lo precioso.
Sí, llega hasta la parte más íntima del corazón y corta entre las raíces.
(Heb.
4:12) Ustedes tienen que oír y hacer esa Palabra.
Tienen que separarse de todas las palabras viles, de la forma vil de vida,
del curso y de la adoración vil del mundo exterior,
del curso y de los pensamientos viles del pecado en el interior,
tan rápido como la Palabra se los descubra.
Ustedes tienen que ejercitarse en lo que es locura y necedad a los ojos del mundo,
con la severidad de la cruz sobre sus propias naturalezas terrenales.
De hecho, cuando la Palabra alcanza la naturaleza,
la vida y el espíritu mismo en el interior,
la vida carnal en el corazón no puede ser perdonada,
ni puede ser rechazado lo tonto y lo débil (en opinión
del ojo sabio del hombre) que se levanta en su lugar,
lo cual, cuando es recibido, es como una pequeña semilla,
como la más pequeña de las semillas.
Esa es la palabra de vida; esa es la regla verdadera y viva y el camino a la vida eterna;
esa es la obediencia; ese es el oír y el hacer de la Palabra.
"`El que tenga oídos, que oiga.`"

"`Examinaos a vosotros mismos si estáis en la fe; probaos a vosotros mismos.
¿O no os conocéis a vosotros mismos, que Jesucristo está en vosotros,
a menos que estéis reprobados?`"
(2 Cor.
13:5). ¿Están ustedes en la fe?
Entonces Cristo está en ustedes.
¿No está Cristo en ustedes?
Entonces están reprobados, fuera de la fe.
Cristo está en ustedes, ¿y no llevará Él las riendas y gobernar?
La Palabra viva está en el corazón, ¿y no será el gobierno del corazón? El apóstol Juan,
quien había visto, gustado, tocado y predicado la palabra de vida,
¿refirió a los cristianos a sus epístolas, o a cualquier otra parte de la escritura,
para que fueran su gobierno?
No, él los dirigió a la unción como maestro suficiente.
(1 Juan 2:27) "`El que cree en mí, como dice la Escritura,
de su interior correrán ríos de agua viva`" (Juan
7:38). El que tiene la fuente de vida en él,
el que tiene ríos de agua viva manando continuamente,
¿ha necesitado ir a otro lugar a buscar agua?
"`El reino de los cielos está en ustedes,`" dijo Cristo, y manda a "`buscar el reino.`"
Enciendan la candela, barran la casa, busquen diligentemente el reino; ahí está,
si consiguen encontrarlo.
Él que ha encontrado el reino en el interior, ¿debería mirar afuera,
a palabras habladas acerca del reino para hallar las leyes del reino?
¿No se encuentran las leyes del reino en el reino?
¿Está el reino en el corazón y las leyes del reino escritas en un libro afuera?
¿No es el evangelio la ministración del Espíritu?
Aquel que ha recibido al Espíritu, ¿regresará a la letra para ser guiado?
El Espíritu vivo que da las Escrituras está presente,
¿y no tendrá preeminencia por encima de Sus propias palabras escritas?

¿Cuál es el objetivo correcto de la letra?
¿No es testificar del Espíritu y llevarlo a uno al Espíritu?
La ley, los profetas, Juan el Bautista, condujeron a Cristo en la carne;
Él tenía que ser la luz creciente y ellos tenían que decrecer.
Las palabras de Cristo en la carne,
las palabras de los apóstoles después y todas las palabras desde entonces,
no son sino para conducir a Cristo en el Espíritu, a la sustancia eterna y viva.
Cuando las palabras de Cristo, de los apóstoles,
o cuales quieras otras palabras habladas en estos días desde el mismo Espíritu,
llevan al Espíritu, a la experiencia y al establecimiento del alma en el fundamento vivo,
a la edificación y perfeccionamiento del hombre de Dios en dicho fundamento,
han alcanzado entonces su fin y su gloria.
Pero alabar las palabras escritas sin entender su voz,
manteniéndose a distancia de eso a lo que nos invitan,
pone las palabras fuera de su lugar, fuera de su uso y servicio correcto,
y así ni alcanzan su fin ni su gloria.
Y aunque el hombre pusiera sobre esas palabras algo que pareciera de mayor gloria,
es decir, las hiciera su regla y su guía,
no sería más que deshonra tanto para ellas como para
el Espíritu que las dio para un propósito diferente.

Con respecto a la otra parte de la objeción,
la que habla de si los hombres deberían ser dejados en sus
propios espíritus y seguir la guía de sus propios espíritus,
y que eso produciría confusión e incertidumbre,
¡yo reconozco que así sería! Pero aquí no estamos
hablando de dejar al hombre en su propio espíritu,
sino de dirigir y guiar al hombre a la Palabra y al Espíritu de vida,
a conocer y a oír la voz de Cristo,
la cual reúne y traslada al hombre de su propio espíritu al Espíritu de Cristo.
Allí no hay confusión ni incertidumbre, sino orden, certidumbre y estabilidad.

La luz del Espíritu de Dios es una regla segura e
infalible, y el ojo que la ve es un ojo seguro.
El entendimiento humano de las Escrituras es incierto y falible.
El hombre, al no tener el verdadero oído,
recibe en su entendimiento incierto un conocimiento literal y dudoso de las cosas,
y engaña su alma.
De esta manera,
se pierde en su propia mente errante e incierta, en
medio de su sabiduría y conocimiento de las Escrituras,
y su alma es engañada por falta de una raíz verdadera y de un fundamento en él. Pero
aquel que es llevado al verdadero Pastor y conoce Su voz, no puede ser engañado,
puede leer las Escrituras a salvo y probar la verdadera
dulzura de las palabras que salen de la vida.

Pero el hombre que está fuera de la vida se alimenta
de cáscaras y no puede recibir nada mejor;
ha reunido un conocimiento muerto, seco,
literal y áspero de las Escrituras y eso es lo que saborea.
Cuando la vida de las palabras y las cosas de las
que se hablan le son declaradas no las puede recibir,
porque está fuera del lugar donde fueron escritas
y del único lugar donde pueden ser entendidas.
Así entonces, el tal, tras perder la vida, ¿qué más puede hacer?
No puede hacer otra cosa más que alabar la letra escrita,
aunque su alma esté hambrienta y se encuentre famélica
y muerta por la falta del pan de vida.

Los escribas y fariseos hicieron una gran algarabía
acerca de la ley y las ordenanzas de Moisés,
afirmando que Cristo y Sus discípulos eran quebrantadores y profanadores de ellas.
No obstante, ellos mismos no honraban verdaderamente la ley ni las ordenanzas de Moisés,
sino sus propias doctrinas, mandamientos y tradiciones.
Así es ahora con los que hacen una gran algarabía acerca
de las Escrituras y de las enseñanzas de los apóstoles.
Estos no honran las Escrituras ni las enseñanzas de los apóstoles,
sino sus propias definiciones, sus propios conceptos,
sus propios inventos e imaginaciones.
Corren a las Escrituras con ese entendimiento,
con el que está fuera de la Verdad y que no los dejará entrar en ellas.
Cuando no son capaces de alcanzar y comprender la verdad tal como es, entonces estudian,
inventan e imaginan el significado.
Moldean una semejanza, una similitud de la verdad lo más aproximada posible,
y lo hacen pasar como la verdad.
Luego honran y se inclinan ante ello como si fuera la voluntad de Dios,
aunque no sea más que una semejanza de su propia
invención y creación. Ellos no adoran a Dios,
ni honran las Escrituras, honran y adoran las obras de su propio cerebro.
El hombre ha hecho una imagen,
ha hecho un ídolo de cada escritura a la que le ha creado un significado,
de cada escritura que no ha leído en la luz verdadera y viva del Espíritu eterno de Dios.
El respeto y honor que le da a ese significado, no es respeto y honor a Dios,
sino a su propia imagen, a su propio ídolo.

¡Oh,
muchos son tus ídolos cristianos de Inglaterra! ¡Cuán llenos están de imágenes,
ídolos y conceptos espirituales! ¡Han corrido de una idea a otra
con la misma mente y espíritu con que comenzaron al principio!
El fundidor de imágenes nunca ha sido descubierto
y destruido en ustedes y por eso sigue operando.
Grande será el dolor y la angustia cuando el rápido ojo escrutador
del Señor lo busque y revele Su justa ira contra él.

Yo honro las Escrituras en mi corazón y mi alma,
y anhelo leerlas con ojo puro y en la luz pura del Espíritu vivo de Dios.
¡Pero,
qué el Señor me libre de leer una línea de ellas en mi propia voluntad,
o de interpretar alguna parte de ellas de acuerdo a mi propio entendimiento!
Anhelo leerlas sólo en la medida que sea guiado, conducido e iluminado por Él,
en la voluntad y entendimiento que vienen de Él. En Su luz, toda escritura,
cada escrito del Espíritu de Dios que proviene del aliento de Su vida,
es provechoso para edificar y perfeccionar al hombre de Dios.
Pero las instrucciones, las reprimendas, las observaciones, las reglas,
los motivos de esperanza y consuelo,
o cualquier otra cosa que el hombre haya encontrado
en las Escrituras (estando él mismo fuera de la vida),
no tiene verdadero provecho, ni edifica lo verdadero.

=== 2. La verdadera adoración se perdió.

La verdadera adoración de Dios en el evangelio es en el Espíritu.
"`Mas la hora viene, y ahora es,
cuando los verdaderos adoradores adorarán al Padre en espíritu y en verdad;
porque también el Padre tales adoradores busca que le adoren`"
(Juan 4:23). La verdadera adoración es en el espíritu y en la verdad,
y los verdaderos adoradores adoran ahí. El Padre
busca tales adoradores y acepta esa adoración;
cualquier otra adoración es adoración falsa, y cualquier otro adorador es adorador falso.
¿No rechazó Dios el sacrificio de Caín antes?
¿Puede Él aceptar ahora cualquier sacrificio o adoración que se
ofrezca en la naturaleza de Caín? El que adora sin el Espíritu,
adora en esa naturaleza, pero el que quiera adorar correctamente,
debe tener su naturaleza cambiada y adorar en esa fe, en esa vida, en esa naturaleza,
en ese Espíritu, mediante el que y donde el tal es cambiado.
Porque no estar en esto o no permanecer en esto,
hace que sea imposible agradar a Dios en algo.

El que es verdadero adorador debe guardar la ley de la fe,
la ley del Espíritu de vida en él;
la ley que él recibe continuamente del Espíritu de vida mediante la fe fresca.
Debe oír y atender la voz de la Palabra viva
en toda su adoración y debe adorar en la presencia,
poder y guía de esa Palabra.

Voy a dar sólo el ejemplo de la oración. "`Orando en todo
tiempo con toda oración y súplica en el Espíritu`" (Ef.
6:18). Note que toda oración y súplica debe ser en el Espíritu.
Si un hombre siempre que habla lo hace desde su propio espíritu,
aunque lo haga con mucho fervor y pasión,
aún no es oración. Es oración sólo en la medida que el Espíritu la motive,
en la medida que el Espíritu la dirija y la guíe. Si un
hombre comienza sin el Espíritu o continúa sin el Espíritu,
no está en la verdadera adoración, está en su propia voluntad,
es adoración de la voluntad.^
footnote:[Adoración de la voluntad es un término que se usa para
referirse a cualquier forma de adoración que brota de los recursos
del hombre y que está de acuerdo a la voluntad del hombre.]
Es adoración de acuerdo a su propio entendimiento y naturaleza,
ambas cosas deben ser crucificadas,
y no deben ser seguidas en ninguna forma bajo el evangelio.
"`Nosotros somos la circuncisión,
los que adoramos a Dios en Espíritu,`" (estos son los verdaderos adoradores,
"`la circuncisión,`" y esta es la verdadera adoración, "`en Espíritu`"),
"`no teniendo confianza en la carne.`"
Si un hombre se ocupa en algún tipo de adoración a Dios sin Su Espíritu,
¿no es esto confianza en la carne?
Si comienza sin el movimiento del Espíritu, ¿no es esto comenzar en la carne?
Si sigue sin la continuidad del Espíritu,
¿no es esto continuar en la fuerza y confianza de la carne?
La adoración del Espíritu es en la voluntad y tiempo
del Espíritu y es continuada por Su luz y poder.
Este poder mantiene abajo la parte intelectual y emotiva del hombre,
en la que todo el mundo adora, ofrece sacrificios inaceptables,
y ofrendas cojas y ciegas que el alma de Dios odia.

Ahora bien, la adoración no se halla en la voluntad ni en el tiempo del hombre,
sino en lo que permanece para siempre, esta es adoración continua.
Hay una continua oración a Dios.
Hay una continua bendición y alabanza de Su nombre, al comer,
al beber o al hacer cualquier otra cosa.
Hay una continua inclinación ante la majestad del Señor en cada pensamiento,
en cada palabra, en cada acción. Esta es la verdadera adoración,
este es el descanso o día de reposo en el que los verdaderos adoradores adoran.

Cuando la creación de Dios es finalizada,
cuando el niño es formado en la luz y la vida soplada en él,
entonces Dios lo pone en Su tierra santa donde se guarda Su día de reposo.
Este está en la fe, la cual es la sustancia de las cosas que se esperaban bajo la ley.
Él ha salido de todos los tipos y sombras de la ley,
de todas las observaciones paganas de días y tiempos en el espíritu de este mundo,
para entrar en el verdadero día de reposo, en el verdadero descanso,
donde no tiene que obrar más,
donde Dios obra todo en él en Su tiempo y de acuerdo a Su propio beneplácito.
"`Pero los que hemos creído entramos en el reposo`" (Heb.
4:3). Y "`el que ha entrado en su reposo, también ha reposado de sus obras,
como Dios de las suyas`" (ver. 10). El que tiene la menor muestra de fe
experimenta una medida de reposo al encontrar la vida obrando en él. Su alma
es diariamente dirigida más y más en la vida, mediante la obra de la vida,
y el pesado yugo de su propio esfuerzo en pos de la vida es quitado de sus hombros.
Ahora esto es la verdad, la vida,
el día de reposo y la adoración del alma que es guiada
en la verdad y preservada en la verdad.

[.discourse-part]
Pregunta: Pero ¿cómo es la adoración ahora en la apostasía?

[.discourse-part]
Respuesta: Entre los católicos es una adoración muy desagradable;
una adoración más carnal que lo que alguna vez fue
la adoración de la ley del antiguo pacto.
Porque aunque la ley en su naturaleza era externa y carnal,
aun así era enseñada y prescrita por la sabiduría
de Dios y provechosa en su lugar y para su fin.
Pero la adoración entre los católicos fue inventada por una sabiduría
corrupta y establecida en la voluntad corrupta del hombre,
y no tiene verdadero provecho, todo lo contrario, mantiene alejada la vida,
el poder y al Espíritu mediante prácticas de la carne
que alimentan y complacen la naturaleza carnal.
Miren sus días consagrados a los santos, sus horas canónicas de oración,
sus oraciones en una lengua desconocida +++[+++Latín], sus ayunos, festines, Aves Marías,
Padres Nuestros, credos, etc.
¿No está todo esto fuera de la vida,
fuera del Espíritu y según la invención y voluntad de la carne?

La adoración de los protestantes no es muy diferente,
porque su adoración es también desde un principio carnal,
en sus propios tiempos y voluntades,
según su propio entendimiento y aprehensión de las cosas.
No proviene del levantamiento y guía de la infalible vida del Espíritu en ellos,
porque cuando el Espíritu lo intenta, ellos lo sofocan.
También guardan días, tiempos y ordenanzas que perecen,
ni salen de la carne para entrar en el Espíritu donde
la verdadera adoración debe ser conocida.

=== 3. La fe, la verdadera fe se perdió.

La fe que vence al mundo, la fe que alimenta la vida del justo y mata al injusto,
la fe que es pura y da entrada al reposo de Dios,
la fe que es la sustancia de las cosas que se esperan
y la evidencia de las cosas que no se ven,
se ha perdido.

Porque los que llevan el nombre de cristianos y dicen creer en Cristo y tener fe en Él,
no pueden vencer al mundo con su fe,
más bien son vencidos por el mundo todos los días.
¿No son estos cristianos encontrados en los honores,
modas, costumbres o adoración del mundo?
¡En efecto, están tan lejos de vencer que son vencidos por todo eso!

La fe de estos cristianos (así llamados) no es un misterio^
footnote:[Penington usa la palabra __misterio__ para referirse a las
cosas que no pueden conocerse por medio de facultades naturales,
sino que deben ser reveladas por el Espíritu de Dios.]
(ellos no conocen el misterio de la fe, el cual es guardado en una consciencia pura),
la fe de ellos consiste en creer un relato histórico y en un mejoramiento
carnal de eso que puede ser guardado en una consciencia impura.

Ellos no han entrado en el reposo por medio de su fe;
no conocen el verdadero día de reposo en el Señor,
sino que continúan en un día de reposo que es sombra.
Su fe tampoco es la sustancia de lo que esperan,
porque la sustancia de lo que esperan aún es ajena a ellos.
No han llegado "`al monte de Sion, a la ciudad del Dios vivo, Jerusalén la celestial,
a la compañía de muchos millares de ángeles, a la congregación de los primogénitos,
a Dios el Juez, a Jesús el Mediador, a la sangre rociada`" y por lo tanto,
a la unidad y certeza en la vida.
Más bien permanecen en meras opiniones,
formas y prácticas adecuadas para el espíritu terrenal,
todo lo cual puede ser fácilmente sacudido, y debe ser sacudido hasta caer,
si es que alguna vez van a conocer el edificio de Dios y la verdadera fe.

=== 4. El amor, el verdadero amor se perdió.

El amor inocente, el que no guarda rencor, no desea el mal,
ni mucho menos le hace mal a alguien; el amor que es sufrido, amable, manso,
humilde y no busca lo suyo,
sino el bien de otros... ese amor se perdió. El amor no fingido fue desterrado,
y el amor fingido del que proceden la enemistad y la violencia ha tomado su lugar.
El verdadero amor ama al enemigo y no puede devolver enemistad por enemistad,
más bien busca el bien de aquellos que lo odian.
Pero el amor falsificado puede perseguir y odiar al que él llama amigo, sí,
incluso puede perseguir y odiar a un hermano por
causa de alguna diferencia de opinión o práctica.
El amor que estaba en Cristo le enseñó a dar Su vida por Sus ovejas,
y el que tiene el mismo amor puede dar su vida por su hermano.
Sin embargo, el amor que está entre los cristianos hoy más bien tiende a quitar la vida.

¿Cómo es el amor entre los católicos?
Miren sus inquisiciones, sus iras, sus quemas en la hoguera, etc.
¿Cómo es el amor en Nueva Inglaterra?
Es un amor que encarcelará o desterrará a su hermano si difiere, aunque
sea un poco, en el juicio o práctica de la adoración. En efecto,
ellos azotan, queman manos, cortan orejas,
al igual que los obispos de la vieja Inglaterra.
Si alguien les hubiera dicho, cuando huyeron de la persecución de los obispos,
que iban a hacer las mismas cosas, habrían estado listos a responder:
"`¿Qué? ¿Somos acaso perros que regresan a su vómito?`"
Pero ellos huyeron de la cruz,
la que habría crucificado ese espíritu de persecución
y lo llevaron vivo con ellos a Nueva Inglaterra.

¿Cómo es el amor aquí en la vieja Inglaterra?
¿No es un amor que azota, pone en el cepo, encarcela, apedrea y se burla?
Sí,
los mismos maestros (que deberían ser modelos de amor para los
demás) echan en la cárcel y toman los bienes de sus hermanos.
Vean el __"`Record of Sufferings for Tithes in England`"__
(Registro de Sufrimientos por Diezmos en Inglaterra),
que puede hacer que un corazón tierno sangre al leerlo,
y que se situará como una señal de infamia en la magistratura
y ministerio de Inglaterra para sucesivas generaciones.

¿Es este el amor de la semilla justa o es el amor de Caín,
el cual es una mera confesión en palabra y demostración, pero no en hecho, ni en verdad?
¿Cómo pueden tales hombres amar a Dios?
No, si el verdadero amor de Dios estuviera en ellos esta enemistad no podría existir,
ni los malos frutos brotar.
Estos no han visto al Padre ni al Hijo.

"`Por esto conocerán todos que sois mis discípulos, si se aman los unos a los otros`"
(Juan 13:35). Y por esto podrán conocer todos los hombres,
que los que ahora pasan por cristianos no son discípulos de Cristo,
porque _no_ se aman unos a otros.
No están en la unidad de la luz y por eso no pueden amarse unos a otros.
Su unidad consiste sólo en formas externas, en opiniones, confesiones, prácticas,
por lo tanto,
cualquier diferencia suscita rápidamente la enemistad y
provoca levantamientos en el corazón unos contra otros.
Pero el verdadero amor crece a partir de la verdadera unión y comunión en la luz.
Cuando esta no se conoce, no puede haber verdadero amor en el Espíritu,
sino uno fingido en la carne.

=== 5. La verdadera esperanza, el verdadero gozo y la verdadera paz se perdieron.

El verdadero fundamento de la esperanza es Cristo en el corazón,
y la verdadera esperanza es la que se levanta de ese fundamento,
de la experiencia de Cristo ahí: "`Cristo en ustedes, la esperanza de gloria`" (Col.
1:27). ¿Cuál es la verdadera esperanza del cristiano?
Cristo en él. El que "`tiene la vida eterna morando en él`" y la conoce,
no puede sino ser llevado a la gloria.
Pero, ¿cuál es la esperanza del cristiano común? El aferra
su esperanza a las palabras que ha leído,
a la creencia en un testimonio escrito.
Él lee que el que cree será salvo.
"`Yo creo,`" piensa, "`por lo tanto seré salvo.`"
Y así como ha levantado la fe equivocada y el amor equivocado,
levanta la esperanza equivocada.
Esta esperanza se perderá, porque es la esperanza del hipócrita.
Es una esperanza en la naturaleza hipócrita,
que cumple con las palabras de las Escrituras,
pero no está en unión con Dios ni con la vida de ellas.
Y al estar sin ancla es llevado por las olas del mar.

El verdadero gozo está en el Espíritu, en lo que se siente,
se disfruta y se espera ahí. Pero el gozo del cristiano común está
en las cosas que acumula y comprende en su entendimiento,
o en destellos de emoción que siente en la parte afectiva, provenientes del fuego
y de las chispas de su propia leña donde encuentra su calidez y confort.

La verdadera paz se encuentra en la reconciliación
con Dios al haberse derribado lo que causaba la ira.
El Cordero de Dios derribó la pared de separación en el corazón. La sangre
de Jesús (en la que está la vida) limpia el corazón de pecado,
lo purifica y une el corazón puro al Dios puro.
Ahí está la unión, ahí está la comunión, ahí está la paz.
No obstante,
la paz del cristiano común se fundamenta en un malentendido de las Escrituras,
mientras tanto,
la pared de separación permanece de pie y la maldad continúa albergada
en su corazón. Ellos razonan entre sí usando palabras de las Escrituras;
que Dios está en paz con ellos y que ellos están unidos a Él, pero al mismo tiempo,
lo que es verdaderamente de Dios en el interior de ellos, testifica contra ellos,
combate contra ellos y no hay paz.

=== 6. El verdadero arrepentimiento, la verdadera conversión y la verdadera regeneración se perdieron.

El verdadero arrepentimiento es,
el arrepentimiento de obras muertas y del principio
muerto de donde todas las obras muertas proceden.
Sin embargo, de esto no ha habido arrepentimiento,
más bien se ha apreciado en la apostasía. La edificación y el ejercicio de la religión
en la apostasía ha descansado en el entendimiento equivocado de lo que es arrepentimiento,
el cual debe ser destruido, y la voluntad carnal que debería haber sido crucificada,
ha sido complacida y alimentada con esta religión.

La verdadera conversión es, la conversión de la potestad de Satanás a Dios,
de las tinieblas a la luz,
pero en la apostasía los hombres no han conocido a Dios ni a Satanás,
no han conocido la luz ni las tinieblas.
En la apostasía los hombres han errado tomando uno por el otro,
adorando al diablo en lugar de a Dios (Apoc.
13:4) y siguiendo los conceptos oscuros de sus propias mentes
con respecto a las Escrituras y llamándolos luz.

La regeneración es el cambio de hombre que ocurre
mediante el nacimiento que es del Espíritu.
La criatura se desnuda de su propia naturaleza, de su propio entendimiento,
de su propia voluntad y se forma de nuevo en el vientre del Espíritu.
La vieja criatura pasa y surge una nueva,
la cual crece diariamente en la nueva vida hacia la plenitud de Cristo.
Pero ahora,
si los hombres pudieran abrir sus ojos verían que su nacimiento es carnal y que consiste,
en el mejor de los casos, en una conformación a la letra,
la que la vieja naturaleza puede imitar y alcanzar.
Verían que la Semilla inmortal no está brotando en ellos,
que ni ellos están muertos a lo mortal, ni vivos a lo inmortal.

=== 7. La verdadera sabiduría, justicia, santificación y redención se ha perdido.

La verdadera sabiduría está en el temor de Dios y en apartarse del mal.
Los que son enseñados por Dios aprenden esa sabiduría,
y de ese modo son hechos sabios para salvación. Pero la mayoría
de los que son llamados cristianos no han entrado en el temor de
Dios y lo miran como perteneciente a la ley y no al evangelio.

La verdadera justicia está en la fe, en oír y obedecer la palabra de fe.
¿De dónde venía la justicia de la ley sino por oír y obedecer la voz de la ley?
¿De dónde viene la justicia del evangelio sino por oír y obedecer a la Palabra de fe,
la cual es predicada (y es el Predicador) en el corazón? El apóstol
Pablo hace esta comparación. La justicia de la ley dice:
"`El hombre que haga estas cosas, vivirá por ellas`" (Rom.
10:5), pero ¿qué dice la Palabra de fe?: "`Cerca de ti está la palabra,
en tu boca y en tu corazón`" (Rom.
10:8); el que hace y oye esa Palabra vivirá en ella.
"`De cierto, de cierto os digo: Viene la hora, y ahora es,
cuando los muertos oirán la voz del Hijo de Dios;
y los que la oyeren vivirán`" (Juan 5:25) La desobediencia
a la ley escrita era injusticia y llevaba a la muerte.
De igual manera,
la desobediencia a la Palabra viva es injusticia y el hombre no puede ser justificado,
sino condenado.
Cuando el alma oye, cree y obedece es justificada,
sus pecados anteriores son olvidados y esto le es imputado como justicia.
Pero cuando el alma no oye, no cree ni obedece, esta incredulidad es juzgada en ella,
sus pecados son retenidos y no le son remitidos.

La verdadera santificación consiste en el crecimiento de la Semilla
y en Su propagación sobre el corazón y sobre todo el hombre,
tal como sucede con la levadura.
Cristo es formado por la fe en el corazón y según crece esta Semilla,
según se propaga esta Levadura, según crece este Hombre,
así hace santa a la persona en quien Él crece.
La semilla de la vida, el reino de los cielos,
es algo santo y según crece y se extiende purga la vieja levadura y hace nueva la masa.
Pero ahora, los cristianos que han crecido en la apostasía,
desconocen esta Semilla y no disciernen esta Levadura,
por lo que su santidad consiste en conformarse a reglas de las Escrituras
que reciben en el corazón y en el entendimiento viejo.
¡Cuánto ruido ha hecho la santidad del hombre en
el mundo a lo largo de la noche de la apostasía!

La redención consiste en ser comprados por el precio de la vida, para salir del pecado,
salir de la muerte, salir de la tierra, salir del poder del diablo.
Consiste, en expulsar del corazón al hombre fuerte con todo lo que introdujo,
y en la liberación de su poder.
Consiste en disolver la obra del pecado, la obra que el diablo ha forjado,
y colocar al alma, la cual es inmortal, en libertad; libre del pecado,
libre para la justicia.
Esta es la verdadera redención. Pero la redención en la apostasía es una redención fingida,
en la que la salvación del pecado, del diablo y su poder no se siente ni se experimenta,
el hombre fuerte aún está en el corazón,
mantiene al alma en la muerte y produce frutos de muerte diariamente.

Anteriormente,
(el primer día en que el poder de Dios irrumpió)
los cristianos tenían a Cristo en ellos,
a la Palabra viva.
Ellos le abrieron su corazón, lo recibieron,
lo sintieron ahí y lo encontraron hecho para ellos su sabiduría, su justicia,
su santificación, su redención. (1 Cor.
1:30) Ellos tenían la sustancia que esas palabras significan y de la que hablan,
y conocían el significado de las palabras por la experiencia de la sustancia.
Pero los cristianos ahora, en la apostasía,
tienen una multitud de percepciones tomadas de las palabras,
sin la experiencia de la sustancia de la que ellas hablan; en eso consiste su religión.

=== 8. La iglesia, la verdadera iglesia se perdió.

La verdadera iglesia era una congregación reunida en Dios fuera del mundo,
engendrada y reunida en Su vida por la Palabra viva; por lo tanto,
tenía un lugar y una habitación verdadera en Dios.
El apóstol Pablo escribiendo a los de Tesalónica los llama "`la iglesia en Dios.`"
La iglesia bajo el evangelio está formada de verdaderos israelitas,
reunidos en la medida del Espíritu de Dios en ellos,
fuera de sus propios espíritus y naturaleza.
Ellos son engendrados por Dios, nacidos de Su Espíritu,
sacados de Egipto por Él y llevados a través del desierto a Sión, el monte santo.
Ahí encuentran la Piedra angular elegida y preciosa que está puesta en
Sión. Son piedras vivas edificados sobre ella en Jerusalén la ciudad santa.
(1 Ped.
2:5-6; Heb.
12:22) Esta es la verdadera iglesia.

Todo el que cree en Cristo es una piedra viva; y como piedra viva,
está colocado sobre el fundamento vivo, por tanto,
es una parte del edificio en el templo del Dios vivo.
Sí, al ser limpiado su cuerpo y su espíritu,
él mismo es un templo en el que Dios habita, aparece y es adorado.
La reunión de algunas de estas piedras,
en cualquier momento y en la vida y nombre de Cristo, es un templo más grande,
y tal templo, que Cristo nunca falla en aparecer.

Pero, ¿qué ha sido la iglesia en la apostasía? Un edificio de piedra, dicen algunos,
y esto no sólo entre los católicos, sino también entre los protestantes en Inglaterra.
Muchos han llamado a un edificio de piedra, iglesia, templo, casa de Dios,
alegando que es un lugar santo,
y lo demuestran quitándose sus sombreros mientras están en el interior.
Otros dicen que no es el edificio de piedra, sino la gente que se encuentra ahí,
sin embargo,
estos siguen burlándose si oyen a un hombre hablar de ser movido por el Espíritu.

=== 9. El ministerio, el verdadero ministerio se perdió.

El verdadero ministerio era un ministerio hecho y establecido por el Espíritu,
por el don que el Espíritu les confirió,
por el Espíritu que los envió y los designó para Su obra.
Cristo les mandó a Sus apóstoles y discípulos que
esperaran en Jerusalén la promesa del Espíritu,
y cuando les dio el Espíritu los dio a la iglesia para la obra del ministerio.
(Ef. 4:11-12; Hech.
20:28) Ahora bien,
si nadie puede ser miembro de la verdadera iglesia sino al ser engendrado,
sacado de la muerte e introducido en la vida mediante el Espíritu,
ciertamente nadie es suficiente para ministrar al engendrado sino por el mismo Espíritu.
Por consiguiente, estos recibieron su ministerio del Señor Jesús (Hech.
20:24), y por el don del Espíritu que recibieron de Él,
fueron hechos "`ministros competentes del Nuevo Testamento, no de la letra,
sino del Espíritu`" (2 Cor.
3:6). Ellos eran aptos en Dios para ministrar desde
el Espíritu de Dios a los espíritus de Su pueblo.
No ministraban conocimiento literal de cosas al intelecto del hombre,
sino que conducían a los hombres al Espíritu de Dios,
y les ministraban cosas espirituales dadas por Dios al entendimiento espiritual.
Tampoco hacían uso de su propia sabiduría y habilidad
para satisfacer los deseos del oído natural,
sino que le hablaban a la consciencia con demostración
del Espíritu en la presencia de Dios,
según le placía al Espíritu darles expresión.

Pero, ¿cómo son hechos los ministros en la apostasía? Por órdenes de los hombres,
creados en sus propias voluntades, según sus propias invenciones.
¿Cómo son calificados?
Por la habilidad e idiomas humanos,^
footnote:[Es decir, los idiomas originales de la Biblia, el griego y el hebreo.]
lo cual ha sido de alta estima en la iglesia,
ya que el idioma del Espíritu de Dios y Su habilidad se perdieron.
Dios no escoge aquí quiénes serán Sus ministros,
cualquier hombre puede designar a su hijo para ser ministro,
si lo enseña a aprender y lo envía a la universidad.
Estos, entonces,
son aptos para ministrarle al hombre las cosas del
hombre de acuerdo a las habilidades humanas,
y esto, en la oscura noche de la apostasía,
se ha hecho pasar como el verdadero llamado al ministerio de Dios.
Por lo tanto, el ministerio es también una invención del hombre, hecho por el hombre,
que no procede del Espíritu ni es capaz de ministrar de espíritu a espíritu.

[.discourse-part]
Objeción: Pero, ¿no ha habido verdadera religión desde los días de los apóstoles?
¿Ni verdadera regla, verdadera adoración, verdadera fe, verdadero amor,
verdadera esperanza, gozo o paz?
¿Ni verdadero arrepentimiento, conversión, regeneración? ¿Ni verdadera sabiduría,
justicia, santificación ni redención? ¿Ni verdadera iglesia, ni verdadero ministerio?
¿Qué ha llegado a ser de todos nuestros antepasados?
¿Perecieron todos?
¿No se han convertido muchos a Dios por este ministerio?
¿No son ustedes mismos convertidos por él? De hecho,
¿no han sido muchos de ellos martirizados y testigos de la verdad?

[.discourse-part]
Respuesta: La adoración, la fe, el amor, la esperanza, el gozo, la paz,
el arrepentimiento, la conversión, la regeneración, etc.,
que han sido declaradas en las naciones como la verdad,
la iglesia y los ministros, todo esto se ha corrompido,
nunca ha recuperado su estado verdadero y original hasta el día presente.
Han habido cambios de una cosa u otra, pero no se ha conocido una verdadera restauración.

Sin embargo,
a lo largo de todas las edades y generaciones Dios ha reservado
una simiente para Él. Con dicha semilla hizo que surgiera un remanente
al que movía y llevaba a testificar contra estas corrupciones,
y tan pronto como la bestia los derribaba y mataba, Dios levantaba más.

Ahora bien, aunque esta simiente,
aunque este remanente no fue capaz de recuperar la
total posesión de la vida y del poder que se perdieron,
sí experimentó un verdadero sabor de ello y el testimonio
que dio a partir de esa experiencia fue verdadero.
Y en la medida que mantuvo ese testimonio en la fe y en la paciencia
que había aprendido y recibido de Dios (aunque en una medida menor),
fue aceptado por Él. Así que no todo se perdió en esta noche de oscuridad;
aquellos que temían a Dios, conocían y oían Su voz,
tenían el testimonio de Su presencia con ellos y
gustaban Su vida y poder en alguna medida.
Dios no era un amo duro con ellos, sino tierno,
gentil y contento de cosechar lo que ellos sembraban, sin embargo,
la aparición de Dios en ese tiempo oscuro era débil y pequeña, fácil de apresar.
Lo siguiente es muy claro, que mientras la sencillez corría pura, era preservada,
pero tan pronto el espíritu del hombre era tentado a establecer
formas externas (ya fueran viejas o recién inventadas),
la sabiduría de la carne se metía con ella, crecía más que ella, corrompía la vasija,
la desafiaba y se perdía la vida.
