== Capítulo III. Algunos Principios que Guían Hacia Afuera de la Apostasíay que Introducen en el Verdadero Espíritu y Vida Cristiana

=== 1. No hay salvación salvo por el verdadero conocimiento de Cristo.

El conocimiento de Cristo no es literal, tradicional o carnal,
ni puede ser recibido por el entendimiento natural;
el conocimiento de Cristo es espiritual y el entendimiento debe ser dado por Dios.
Él "`nos ha dado entendimiento para conocer al que es verdadero`"
(1 Juan 5:20). Un hombre puede leer las Escrituras y oír sermones,
y de ese modo reunir conocimiento en el viejo entendimiento, pero ni ese entendimiento,
ni ese conocimiento reunido es espiritual, sino carnal, por lo tanto, no puede salvar.
El que llega a recibir entendimiento de Cristo y a tener
el conocimiento de Cristo derramado en su corazón,
conoce la diferencia entre este y el entendimiento en el que el hombre acumula cosas.
El conocimiento de Cristo según la letra (y el tipo
de fe que corresponde a tal conocimiento) no salva.
Un hombre debe conocer a Cristo en el Espíritu, la vida y el poder en el que Él vive,
si realmente espera ser salvado por Él. (2 Cor.
5:16-17)

=== 2. Cristo salva mediante el nuevo pacto; no por medio de algo adquirido por la mente en el arcaísmo de la letra, sino mediante la vida nueva que es engendrada.

Hay dos pactos de los que se hacen mención en las Escrituras,
uno es llamado antiguo y el otro nuevo.
El antiguo pertenecía a los judíos y ya terminó, junto con sus ceremonias, nación y reino.
Cristo es el Mediador del nuevo pacto, el cual es mejor que el anterior.
(Heb.
8:6) Él salva al mediar entre Dios y la criatura,
al reunirlos en y de acuerdo a este pacto,
pero el hombre que queda en estado de separación y alejamiento de Dios perece.
Por lo tanto, el que no es dirigido por Cristo a dicho pacto,
no está en estado de salvación.

=== 3. El nuevo pacto es escrito en el corazón.

La única forma de entrar en el nuevo pacto,
del cual Cristo es el Sumo Sacerdote y Mediador,
es teniendo las leyes de Dios escritas en el corazón. "`Este
es el pacto...pondré mis leyes en la mente de ellos y sobre
su corazón las escribiré...y ninguno enseñará a su prójimo,
ni ninguno a su hermano, diciendo: Conoce al Señor, porque todos me conocerán,
desde el menor hasta el mayor de ellos`" (Heb.
8:10-11). Aquí el autor está hablando del pacto del que Cristo es Mediador (ver. 6),
el que él llama nuevo pacto (ver. 8), del que dice que no es como el antiguo (ver. 9),
y demuestra con dos detalles importantes en qué son diferentes:
1) El antiguo fue escrito externamente con letras, para ser leído con ojos externos.
El nuevo es escrito internamente en el corazón y en la mente,
y por eso sólo puede ser leído con el ojo espiritual.
2) Bajo el antiguo ellos necesitaban las enseñanzas de los hombres.
Los labios del sacerdote estaban para preservar el conocimiento,
y el pueblo tenía que buscar la ley en los labios del sacerdote.
Pero en el nuevo la ley está tan cerca de ellos y tan claramente escrita en ellos,
que no necesitan que alguien les enseñe.

De la ley viene el conocimiento de Dios y la ley ahora está en el corazón.
De la ley en el corazón mana el verdadero conocimiento de Dios,
tanto en el menor como en el mayor que están dentro de ese pacto.
Ellos no necesitan decirse unos a otros '`conoce
al Señor;`' esta es la condición del nuevo pacto,
al que los cristianos entraron los primeros días de la iglesia (1 Juan 2:27). Sin embargo,
esto es algo desconocido en esta noche oscura de apostasía y sigue siéndolo para muchos.
"`Todos me conocerán, desde el menor hasta el mayor.`"
Noten:
Incluso el más pequeño en este pacto tiene la ley tan escrita en
su corazón que no necesita buscar conocimiento en ningún otro lugar.

=== 4. Solo el Espíritu de Dios puede escribir el pacto en el corazón, o solo Cristo escribe el pacto por medio de su Espíritu.

El hombre con toda su sabiduría no puede lograr esto;
fue expulsado de Dios y no puede encontrar el camino de regreso
a Él sin la enseñanza y liderazgo del propio Espíritu de Dios.
No tiene que ver con ser educado en alguna forma de religión desde la infancia,
ni con correr a las denominaciones cristianas y sectas que valen algo,
tiene que ver con prestar oído a la verdadera voz del verdadero Espíritu.
Está escrito en los profetas con respecto a los hijos de este pacto,
que todos serían enseñados por Dios:
"`Y todos tus hijos serán enseñados por el Señor.`" Sólo el Señor mediante su Espíritu
puede enseñarles a venir a Cristo y a recibir de Cristo el nuevo pacto en sus corazones.
El hombre es incapaz de conocer a Cristo o de recibir Su pacto
hasta que el Espíritu lo haya preparado y enseñado (Juan 14:17),
luego, cuando el Espíritu ha preparado el corazón,
escribe con Su propio dedo la ley pura de la naturaleza y vida de Cristo en él.
Al recibir esto el hombre sale de su propio espíritu oscuro y de su propia naturaleza,
y entra al verdadero conocimiento de Dios y a una unión
con Él. "`Y pondré dentro de ustedes mi Espíritu.`"
(Eze.
36:27) Esto es parte del pacto; es más,
es la parte a través de la cual se realiza todo el resto.

=== 5. Por lo tanto, el primer paso correcto en la religión es conocer al Espíritu de Dios.

No hay verdadero progreso en la verdadera religión hasta que el hombre entre en el pacto,
y no hay entrada al pacto sino por el Espíritu.
Por lo tanto,
lo primero que es absolutamente necesario conocer en la religión es al Espíritu de Dios,
es decir,
es absolutamente necesario conocer Sus escritos o al menos Sus movimientos en el corazón.

Todo lo que es aceptable para Dios en la religión fluye del Espíritu.
Todo conocimiento tiene que proceder de Él,
porque sólo Él ha revelado y puede revelar la verdad
y fue nombrado por Cristo para guiar a toda verdad.
Toda adoración tiene que ser ofrecida en Él,
porque los que adoran al Padre tienen que adorarlo en Espíritu y en verdad,
porque el Padre busca que tales adoradores lo adoren y rechaza a los demás
adoradores y su adoración. La oración tiene que ser siempre en el Espíritu.
(Efes.
6:18; Jud.
20) Lo mismo sucede con el canto.
Es más, toda la vida y conducta del cristiano tienen que ser en el Espíritu.
(Gal.
5:25) Hacer morir toda la corrupción tiene que ser hecho por el Espíritu.
"`Mas si por el Espíritu hacéis morir las obras de la carne, viviréis`" (Rom.
8:13). De hecho, un cristiano no es nada, ni puede hacer nada,
sin el poder y la presencia del Espíritu de Dios en él. Así, entonces,
si en la religión nada puede ser hecho (y ser aceptado por Dios) sin el Espíritu,
entonces el Espíritu es lo primero de lo que tiene
que ocuparse el que es verdaderamente religioso.

=== 6. La primera manera en que conocemos al Espíritu de Dios es como convencedor de pecado.

Esta es la verdadera entrada.
Esta es la llave que abre la puerta a la vida eterna; el que pueda aceptar esto, acéptelo.
No se entra al remontarse a las alturas con altas imaginaciones y formas de adoración,
no, sino al descender, a saber, a la convicción de pecado.
Esta es la primera y más apropiada obra del Espíritu de Dios para con el hombre caído,
la obra por medio de la que Él se abre camino hacia la escritura de Su ley en el corazón.

Cuando Cristo prometió al Consolador, al Espíritu de verdad, dijo con respecto a Él,
"`...convencerá al mundo de pecado`" (Juan 16:8). Ahora bien,
aquellos que han sido creados de nuevo en Cristo y se han
vuelto sus discípulos reciben consuelo del Espíritu,
pero, ¿qué es el Espíritu para el mundo incrédulo?
O,
¿cómo podrían ellos sentir alguna operación de Él? Él es para ellos un convencedor
de pecado y lo sienten frenándolos y convenciéndolos de sus pecados.
En consecuencia,
el gran objetivo para el hombre mientras permanece en la
oscuridad (que cuando sea trasladado a la luz será fácil),
es distinguir el movimiento y la agitación del Espíritu de Dios.
Y esta es la mejor manera por la que un hombre en
este estado conoce el movimiento del Espíritu:
Cuando discierne que eso que devela y expone al mal, debe ser bueno.
Que eso que descubre lo que es espiritualmente maligno, debe ser por obligación,
espiritualmente bueno.
O, que eso que revela lo que es indudablemente puro e inclina el corazón a ello,
debe ser de Dios.
Conocer esto, y ser unido a ello, resulta en la unión de la criatura con Dios.
Este es el verdadero comienzo de la vida eterna.

=== 7. La manera en que el Espíritu de Dios convence de pecado, es haciendo brillar Su luz en la consciencia^
footnote:[Es importante notar que tanto la mente como la
consciencia del incrédulo están naturalmente corrompidas.
Pablo escribe en Tito 1:15, "`Todas las cosas son puras para los puros,
mas para los corrompidos e incrédulos nada les es puro;
pues hasta su mente y su conciencia están corrompidas.`"
Por lo tanto,
no es la consciencia misma la que es o la que posee
luz divina (como muchos falsamente asumen),
no; Cristo hace brillar Su Luz en la consciencia,
y eso es lo que lleva al hombre al conocimiento de la verdad, y cuando obedece,
a la transformación del alma.]
o en el hombre interior.^
footnote:[Es importante notar que tanto la mente como la
consciencia del incrédulo están naturalmente corrompidas.
Pablo escribe en Tito 1:15, "`Todas las cosas son puras para los puros,
mas para los corrompidos e incrédulos nada les es puro;
pues hasta su mente y su conciencia están corrompidas.`"
Por lo tanto,
no es la consciencia misma la que es o la que posee
luz divina (como muchos falsamente asumen),
no; Cristo hace brillar Su Luz en la consciencia,
y eso es lo que lleva al hombre al conocimiento de la verdad, y cuando obedece,
a la transformación del alma.]

El hombre caído es oscuridad.
La luz brilla en la oscuridad y le muestra al hombre el mal que
de otro modo quedaría escondido en él. El hombre cayó de Dios,
perdió la imagen de Dios y se convirtió en total oscuridad.
Pero el Espíritu de Dios es luz y brilla en la oscuridad,
y lucha para someterlo de nuevo a la luz de la que cayó. "`Porque Dios,
que mandó que de las tinieblas resplandeciese la luz,
es el que resplandeció en nuestros corazones,
para iluminación del conocimiento de la gloria de Dios,`" etc.
(2 Cor.
4:6) ¿Dónde se encontraron los apóstoles y los cristianos de sus
días con la luz del conocimiento de la gloria de Dios en Cristo?
Dios resplandeció en sus corazones.
El que hizo por Su Espíritu que la luz brillara de
la profundidad de las tinieblas (Gén. 1:2),
hizo por el mismo Espíritu que la luz del conocimiento
de la vida resplandeciera en sus oscuros corazones,
y es también allí donde el mismo Espíritu forja la obra de convicción.
El que perfecciona la buena obra en el corazón es el mismo que la comienza.
Este comienzo consiste en reprender y convencer de pecado,
para que el hombre vuelva su corazón del pecado a Dios,
y a la obediencia a la justicia que Dios hace manifiesta.

Ahora bien, el que no se encuentra con el Espíritu al inicio de Su obra, se escabulle,
no continúa con Él, y en su lugar asfixia Sus reprensiones,
nunca se encontrará con Él al final.
Entonces será muy tarde para el tal culpar su religión,
en la que sólo había una forma muerta y no el poder vivo de Dios.
El que llega a la vida eterna debe ser trasladado de su entendimiento muerto,
de todos sus caminos muertos y de sus adoraciones, a la Semilla viva,
y permanecer ahí. Entonces realmente conocerá la vida, la verdadera comida de esa vida,
la verdadera adoración,
el servicio a partir de dicha vida y la recompensa que pertenece a todo esto.

=== 8. Esta luz que convence de pecado brilla en cada consciencia.

"`Oh hombre, él te ha declarado lo que es bueno`" (Miq.
6:8). "`La vida`" que estaba en Cristo era "`la luz de los hombres`"
(Juan 1:4). Cristo es "`la luz del mundo`" (Juan 8:12). Dios,
porque amó al mundo, manifestó Su amor al mundo enviando Su luz a él,
para "`alumbrar a todo hombre que viene al mundo`" (Juan
1:9) y para que con la luz pudieran ver a Su Hijo.
"`Y a todos los que le recibieron, les dio el poder de ser hechos hijos de Dios.`"
Como Dios desea que "`todos los hombres sean salvos y lleguen al
conocimiento de la verdad,`" les ha dado a todos esa luz,
la luz que puede conducir al conocimiento de la verdad que salva.
"`La gracia de Dios que brinda salvación, ha aparecido a todos los hombres`" (Tito 2:11).

Debido a que el enemigo se apoderó del corazón de todos los hombres llenándolos de tinieblas,
Cristo persigue y trata de despojar al enemigo por
medio de la luz que envía en pos de ellos.
Esta es la condenación del hombre,
no que carezca de una luz que testifique contra el enemigo y lo saque de él,
sino que ama al enemigo y escoge ser uno con él, odiando la luz y apartándose de ella.
(Juan 3:19-20) El hombre le presta oídos a los razonamientos de su mente contra la luz,
la asfixia y la ahoga.
No se vuelve a la luz para que los razonamientos de su mente
no sean sometidos por ella y sujetos a ella.

=== 9. El verdadero camino a la vida eterna consiste en creer en la luz del Espíritu que brilla en la consciencia.

El hombre está en tinieblas, dichas tinieblas lo mantienen en la muerte.
No hay manera de que salga de la muerte si no sale de las tinieblas,
y no hay manera de que salga de las tinieblas si no sigue
la luz que las expone y lo llama a salir de ellas.
El que sigue la luz no puede permanecer en tinieblas, con seguridad saldrá.

Hay una semilla maligna en el hombre que llama al mal,
y hay una Semilla del bien que llama a salir del mal para entrar al bien.
El que sigue al bien no puede seguir al mal, sino salir de este.
"`Yo soy la luz del mundo (dice Cristo), el que me sigue no andará en tinieblas,
sino que tendrá la luz de la vida`" (Juan 8:12).
La ruina del hombre es que ama las tinieblas,
ama el mundo, el camino del mundo, la adoración del mundo.
El hombre ama su propio entendimiento y su propia voluntad,
de modo que odia esa luz que se atraviesa y contradice esto;
odia la luz que le enseñaría mediante la negación a sí mismo,
a crucificar la naturaleza de donde su entendimiento y voluntad brotan.

Por tanto, llega a pasar (debido a que el amor por el pecado es fuerte, y Satanás,
el hombre fuerte,
guarda la casa) que los movimientos del Espíritu de Dios son fácilmente pisoteados,
sea por los razonamientos del entendimiento o por la perversidad de la voluntad.
Pero si un hombre se atreve a encomendarse a los movimientos del Espíritu de Dios,
rápidamente encontrará de qué naturaleza son por
la fuerte oposición del hombre fuerte contra ellos.
Este es, de hecho,
un camino recto y angosto en el que la carne no puede entrar ni caminar.
Y sin embargo, es el único camino, pues no hay vida en Dios, ni paz para con Dios,
mientras el enemigo viva en el corazón. Pero cuando
se recibe la luz y el hombre se vuelve a ella,
el poder empieza a obrar, y mata al enemigo en el corazón; y habiéndolo hecho,
cesa la guerra y sólo hay paz.
Luego, la verdadera paz que sobrepasa el entendimiento llena y refresca el corazón.

=== 10. Creer en la luz del Espíritu que brilla en la consciencia une el alma a Dios y le abre el manantial de vida.

Creer en las tinieblas (que es incredulidad para con Dios)
separa el alma de Dios y le cierra el manantial de vida.
Creer en la luz, la cual es enviada para sacar de las tinieblas,
une y abre el manantial de nuevo.
Dios es luz, Él habita en la luz y en ella se goza plenitud de vida.
Él da una medida de Su propia luz para sacar de las tinieblas,
y el que cree y la sigue es conducido por ella a Dios,
de quien salió. Al salir de las tinieblas y entrar en Dios
el alma empieza a sentir de nuevo el manantial de vida,
el fresco manantial de vida que está en Él. El que cree ha llegado al pozo de la salvación,
del que saca agua viva y toma continuamente para no tener sed.
Es más, "`de su interior correrán ríos de agua viva.`"
Este es el fruto de la verdadera fe.
Este es el verdadero camino, el camino angosto (puedo, en presencia del Dios vivo,
poner mi sello sobre la verdad de esto),
el que le ha placido a Dios revelar y hacer manifiesto otra vez,
tras la larga y oscura noche de la apostasía. No llegamos al camino verdadero
al oír o recibir nuevos conceptos o percepciones de las cosas,
sino al experimentar "`eso`" que le puso fin a todos
los conceptos y percepciones de la criatura.
Nosotros crecemos en Él por el incremento de "`eso`" en nosotros, es decir,
por el incremento de la Semilla a quien se le hizo la promesa,
la Semilla que era antes de que Abraham fuese, es sentida, es conocida,
Su día es visto y disfrutado, y por la luz del mismo,
las tinieblas son descubiertas y el reino de las tinieblas asaltado.

=== Algunas Objeciones y Respuestas

Objeción 1: Este es un nuevo camino, una nueva luz.
Nosotros ya conocíamos la religión antes de que esto surgiera y vamos a seguir con ella.

Respuesta:
Es efectivamente nuevo para los que han permanecido mucho
tiempo en la apostasía y han establecido otra luz,
pero no es nuevo en sí mismo, es el mismo que estaba en el principio; sí,
es el mismo que estaba incluso antes del principio.
Cristo es el mismo ayer, hoy y por todos los siglos, y la luz que viene de Él es como Él,
la misma ayer, hoy y por todos los siglos.
Era la misma luz bajo la ley, la misma antes de la ley y la misma desde la ley.

"`Lo que era desde el principio,`" dice el apóstol Juan,
"`eso os anunciamos`" (1 Juan 1:1). Y "`este es el mensaje que hemos oído de él,
y os anunciamos: Dios es luz,
y no hay ningunas tinieblas en él`" (1 Juan 1:5). El objetivo de
la predicación de este mensaje es sacar de las tinieblas a la luz,
llevar a los hombres a la experiencia de la luz de Dios en ellos, y así,
a la unión con ella.
Dios (quien es luz) está cerca del hombre (quien es tinieblas) a pesar
de que sus sentidos están engrosados y difícilmente pueden verlo o sentirlo.
La luz de Dios brilla en las tinieblas del hombre,
pero las tinieblas del hombre no la comprenden.
Por consiguiente, esta luz no es nueva en sí misma,
únicamente es nueva para el viejo espíritu,
el cual ha permanecido mucho tiempo escondido en la región
de tinieblas y muerte y no ha conocido la luz de la vida.

Objeción 2:
Esta es una luz natural o la luz de la naturaleza y consciencia del viejo Adán.

Respuesta: En cierto sentido es una luz natural,
es de la naturaleza de Aquel de quien proviene; la naturaleza de Dios y de Su Cristo.
No es de la naturaleza del Adán corrupto,
a quien esta luz siempre ha reprobado y contra quien sigue en pie como
testigo condenando toda corrupción. El hombre es tinieblas (Efes.
5:8) y cuando Cristo viene a redimirlo lo encuentra en tinieblas.
Cristo no halla luz en el hombre que exponga el pecado,
por eso todos los descubrimientos de pecado que son hechos en el corazón,
son hechos mediante la luz de Cristo, no mediante alguna luz de la naturaleza del hombre.
El Señor es quien escudriña el corazón y lo escudriña con Su propio candil,
no con alguna luz que quede en la naturaleza del hombre.
El hombre cayó en las tinieblas y no sabía dónde estaba,
pero el Señor viene tras él con Su lámpara y le manifiesta su estado.
Esta es la luz de la que el hombre cayó y contra la que peca,
la única capaz de hacerle manifiesta su desobediencia.

"`Porque sabemos,`" dice el apóstol, "`que la ley es espiritual; mas yo soy carnal`" (Rom.
7:14). La ley es la aparición más tenue de la luz, y sin embargo,
es espiritual y de la naturaleza de Cristo,
no de la naturaleza de Adán. Quienquiera que conozca
la naturaleza de eso que pone de manifiesto el pecado,
sabe que es espiritual.
Es el hombre caído el que llama a la luz tinieblas.
El hombre ha establecido una luz por su cuenta,
ha levantado una luz por medio de su estudio e invención,
en la fuerza de la sabiduría caída. Y ahora, habiendo establecido esta como su luz,
es obligado a llamar a la verdadera luz tinieblas,
tal como hicieron los fariseos con Cristo.

Objeción 3: Esta luz hace las Escrituras vacías e inútiles.

Respuesta: No es así. La luz vino del Espíritu que dio las Escrituras,
y es de la misma naturaleza de la luz que brillaba en los que dieron las Escrituras.
Dice lo mismo que dicen las Escrituras, guía a lo mismo,
revela y testifica de las palabras que las Escrituras hablan.
Por tanto,
la luz lleva las Escrituras (que por mucho tiempo han sido abusadas) a su verdadero uso.
En efecto, le pone fin al uso corrupto de las Escrituras,
a las invenciones del hombre y a la formación de cosas a partir de ellas,
y las lleva a su verdadero uso y servicio.
Las quita de las manos del hombre,
quien ha matado la vida por la manera en que las ha usado,
y las pone en las manos del Espíritu, quien hace que las palabras sean nuevamente puras,
prontas y vivas,
y purga los conceptos e interpretaciones corruptas
y muertas que el hombre ha puesto sobre ellas.

El hombre debe conocer al Espíritu, ir al Espíritu,
ser unido y estar en unión con el Espíritu,
antes de poder tener el verdadero entendimiento de las Escrituras.
Las Escrituras son, efectivamente, las palabras de Dios o varias expresiones de Su mente.
El hombre que las escudriña antes de tener al Espíritu no puede conocer la verdad,
sólo puede adivinar e imaginar.
De allí que hayan surgido tantas sectas y denominaciones en el mundo,
según la variedad de las imaginaciones del hombre.
Cierto tipo de hombres declaran: "`Este es el camino, esta es la verdad,
esta es la iglesia, esta es la adoración.`" Otros dicen: "`Así no es,
eso es superstición y error.
Es de esta otra manera.`"
Y así un tercer y un cuarto tipo.
Es lo mismo con las Escrituras.
Unos dicen que este es el significado, otros dicen que no, que es este otro.
Ellos permiten que sus propios razonamientos e imaginaciones se suelten,
y no hay fundamento de la certeza.
Pero si esperaran al Espíritu para comenzar y continuaran
sin ir más lejos de lo que Él les revela,
todas las dudas y divisiones serían sofocadas.

Yo no rechazo la lectura de las Escrituras (incluso en este estado de ceguera e incertidumbre),
en tanto el hombre las lea con temor y temblor;
no poniéndoles su propio entendimiento o el entendimiento de muchos hombres,
sino esperando al Espíritu,
quien es el único que puede darle al hombre entendimiento
para recibir el verdadero conocimiento.
Me atrevo osadamente a afirmar,
que la lectura que hace el hombre de las Escrituras en su propia sabiduría y
auto-confianza (o en la confianza de las interpretaciones que otros han dado),
no le hace ningún bien, sino mucho daño,
porque lo lleva a edificar lo que Dios destruirá de nuevo.

El que comienza con el Espíritu de Dios, entregándose a la luz que viene de Él,
llega a la verdadera unión con Dios y a la experiencia de la vida.
Este encuentra el verdadero crecimiento y el verdadero conocimiento del Espíritu de Dios,
por medio de lo cual llega a conocer y a entender
las Escrituras que salieron del mismo Espíritu.
También llega a ser capaz de medir el engaño de su propio espíritu,
el que anteriormente lo sacaba del camino,
y a ver y a medir los espíritus de los engañadores.
Pero el que está en el engaño, en las imaginaciones y fuera del verdadero conocimiento,
no puede discernir el engaño de su propio espíritu ni el de los espíritus engañadores.

Objeción 4: Esta luz enseña cosas contrarias a las Escrituras.

Respuesta: La luz que viene del mismo Espíritu del que vinieron las Escrituras,
no puede enseñar cosas contrarias a las Escrituras.
Pero el hombre,
quien ha tomado las herramientas de su entendimiento y formado
imágenes y semejanzas a partir de las Escrituras (digo,
inventado significados y sentidos, y juzgado que son conforme a las Escrituras),
inevitablemente juzgará lo que es contrario a sus
significados como contrario a las Escrituras.
La verdad, sin embargo, es una en sí misma,
y concuerda con todo lo que es cierto en este siglo o en siglos anteriores,
y únicamente difiere de aquello que no es cierto.

Objeción 5:
Esto establece el libre albedrío. Cuando a las personas se les exhorta a abrazar la luz,
y a dejar entrar la luz, claman diciendo: "`¿Depende del hombre creer?
¿Depende del hombre recibir la luz?
¿Tiene el hombre libre albedrío?`"

Respuesta: En cuanto al discurso del libre albedrío,
ustedes no saben de qué están hablando.
La voluntad, junto con la libertad de la misma,
se sitúa en la imagen y poder de Aquel que la hizo o en una imagen y poder contrarios.
Mientras está en la imagen y poder del que la hizo, es libre para el bien, no para el mal.
Mientras está en la imagen y poder del que la corrompió, es libre para el mal,
no para el bien.
La voluntad no es de sí misma, es sierva de aquel en quien se encuentra,
ahí es obligada y definida su libertad.
No hay estado intermedio entre los dos poderes,
un lugar donde la voluntad funcione por sí misma y sea libre de ambos por igual.
La voluntad del hombre es sierva y está bajo el mandato de uno de esos poderes.
Si está bajo el dominio del pecado, bajo el poder de las tinieblas,
es libre de la justicia.
Si está bajo el dominio y poder de la justicia, es libre del pecado.
Pero el libre albedrío tal como los hombres se refieren a él comúnmente,
es mera imaginación y no tiene fundamento en el verdadero estado de las cosas.

=== Tres Cosas a Manera de Consejo

Y ahora, ustedes, cuyos corazones han sido tocados y convencidos de la verdad,
y tienen un deseo encendido en pos del Dios vivo, y hambre y sed tras Su justicia,
tomen nota de estas tres cosas que tengo en mi corazón a manera de consejo:

=== 1. Conozcan y tomen su cruz, la cruz de Cristo, la cruz de Cristo cada día.

La cruz de Cristo contradice lo natural y es poder de Dios para liberar de lo natural.
¿Cómo debe ser crucificado y muerto el entendimiento terrenal, la voluntad terrenal,
los afectos terrenales,
junto con la naturaleza elemental (la cual ha tenido su reinado en la tierra)?
Mediante la cruz de Cristo.
Aquel que busca una religión para complacerse a sí mismo en algo no debe venir a la cruz.
Y aquel que después de haber llegado a la cruz busca algo agradable para lo terrenal,
negará y se volverá de la cruz; irá hacia atrás, no hacia adelante.
No es de extrañar que exista tal enemistad en todos los hombres contra la verdad,
pues ella atenta contra sus vidas; sí, atenta contra la raíz misma de sus vidas.

Si esta fuera una nueva manera o forma de religión,
entonces el entendimiento y los afectos del hombre podrían
adaptarse gradualmente y encontrar placer en ella.
Pero la cruz es una muerte directa para la naturaleza y
para el espíritu que han vivido en alguna forma de religión,
y para toda la trayectoria de dicha naturaleza y dicho espíritu.
Sin embargo,
a través de esa muerte brota la verdadera vida en los que reciben su ataque fulminante.
Por tanto, estar dispuestos y aprender a morir cada día,
lleva todo lo que es contrario a Cristo a la cruz.
Negarse a sí mismo en todo, tomar la cruz en todo, seguir a Cristo en todo,
es el camino prescrito por Cristo para llegar a ser Sus discípulos.
"`Si alguno quiere venir en pos de mí, niéguese a sí mismo, tome su cruz cada día,
y sígame.`"
No busquen una vida fácil en la carne, no, en lo más mínimo,
más bien tomen la cruz cada día en todo, hasta que lo terrenal sea muerto,
hasta que la sabiduría y la fuerza de la carne sean totalmente sometidas,
entonces la sabiduría y el poder de Dios llegarán a ser naturales.

=== 2. Mantengan el sentido, el sentimiento y la experiencia, y tengan cuidado con el entendimiento, la imaginación y el pensamiento de la mente.
La mente no es útil para Dios,
ni lleva fruto para Dios hasta que sea hecha nuevamente y sea nuevamente moldeada.

La única Semilla de vida yace en el invisible hombre interior
del corazón entre una multitud de semillas de muerte,
todas las cuales tienen su crecimiento y su fuerza en la parte natural corrupta.
Por tanto,
esa Semilla de vida no puede dispararse en la criatura sin que
las otras semillas se disparen con ella y procuren ahogarla.
Ahora bien, las otras semillas brotan de dos maneras:
Ya sea en forma de oposición contra la verdadera Semilla, o en forma de semejanza.
No puede entrar un buen pensamiento,
deseo o haz de luz en el entendimiento o la voluntad,
sin que haya y broten una multitud de malos pensamientos,
deseos o razonamientos carnales contra dicha luz y traten de vencerla.
Pero si después de tal asalto el enemigo es largamente vencido
(por el poder de Dios que pelea contra él y lo derrota),
también puede ponerse su vestidura de luz.
Entonces puede introducir pensamientos,
deseos y movimientos que se parecen a los de Dios,
y que fácilmente pasan por buenos si el alma no mantiene una estrecha vigilancia.

La única seguridad está en mantenerse fuera de lo natural,
de lo que el enemigo posee y de donde radica su fuerza,
y mantenerse en el sentido y sentimiento de la Semilla invisible,
y sólo involucrarse con Él en lo natural, en ese sentido y sentimiento.
Cuando Él venga, vendrá con fuerza,
vendrá sobre la fuerza que tiene el enemigo en lo natural y gradualmente
lo conquistará. De ninguna manera descansen o permanezcan en lo natural,
más bien retírense con el Señor al lugar de descanso.
Puede que estas palabras sean duras ahora,
pero en adelante (conforme las experimenten) las conocerán.

=== 3. Esperen pacientemente al Señor. No se apresuren en pos de la vida y la salvación en la voluntad de la carne, y dejen que el Señor escoja Su propio tiempo para el derramamiento de Su misericordia y bendición.

El alma debe conocer y sentir cuán malo y amargo es el haber abandonado al Señor,
fuente viva de viva misericordia,
y haber buscado la vida en vanidades y entre ídolos muertos.
Todos los ídolos deben ser derribados y el corazón
lavado de esa naturaleza que corre tras ellos,
y convertirse en una virgen pura para llevar y dar a luz a la Semilla viva.
Ahora, al serle fiel a esa Semilla y al esperar en ella,
en el tiempo del Señor el alma recibirá la misericordia,
bendición y herencia que le pertenecen a la Semilla.
El agricultor no cosecha inmediatamente,
sino que espera largamente a que la semilla crezca hasta la madurez.
Mientras tanto,
el alma se queda quieta y lleva la indignación del Señor contra eso que ha transgredido,
hasta que Él la juzga, la libera de ello y la conduce a la inocencia y justicia.
No piensen en la larga carrera, ni en la dura batalla,
ni se cansen de las aflicciones y castigos en el camino, sigan al Capitán, al Guía,
al Líder, cuya luz, fuerza, coraje y sabiduría lo vencerán todo,
y llevarán al alma que permanece en ella a Su propio trono.

Ahora, mientras esperan tomen la cruz y manténganse en la experiencia de la Semilla,
así la parte corrupta, natural y mortal,
en donde el trono y el poder de Satanás han estado, se marchitará,
decaerá y se debilitará día a día. Igualmente, la tierna planta de Dios,
la Semilla inmortal, se disparará y se fortalecerá cada día,
y ustedes llegarán a una nueva voluntad en Dios y a un nuevo entendimiento en Dios.
Aquello que es de Dios se manifestará y ustedes conocerán,
desearán y se deleitarán en las cosas de Dios.
El alma que es inmortal, oirá, recibirá y comerá la Palabra inmortal,
la cual es el pan de vida y la única capaz de preservar y nutrir la vida eterna.
Entonces sabrán lo que es temblar ante esa Palabra,
y tener todos los poderes de la naturaleza derretidos y fracasados delante de ella.
Luego conocerán la fe que da la victoria,
el conocimiento que les permite entrar en la vida,
el temor que conserva el corazón limpio,
la esperanza que ancla el alma inmortal en el Dios inmortal,
la paciencia que gana la corona.
Llegarán a ser testigos de las diversas condiciones de los
santos en la escritura conforme crecen en ellas.
Ustedes no necesitarán que los hombres les den los significados
de las Escrituras que provienen de sus cerebros,
habilidades y entendimientos adquiridos,
ustedes conocerán el significado proveniente de la cosa misma en sus propios corazones.
Oirán las palabras de la viva voz del Espíritu que habló primero las Escrituras,
el único capaz de interpretar Su propia mente y revelar las palabras que Él mismo dijo.
Entonces ustedes conocerán y amarán la verdadera vida,
y no necesitarán más exhortaciones para salir de todas las formas muertas,
corruptas y corruptoras que siempre han sido y serán enemigas de la vida.
Así la paz de Dios, el reposo de Dios, el verdadero día de reposo de Dios,
la eterna luz y vida de Dios,
llegarán a ser de ustedes y disfrutados por ustedes más allá de toda duda o controversia.
