== Capítulo IV. El Hacha Está Puesta a la Raíz / del Antiguo Árbol Corrupto

=== Prefacio

Hubo un día glorioso y una brillante aparición de la Verdad en los días de los apóstoles.
Ellos tuvieron al verdadero Consolador,
quien los guió a toda Verdad y los mantuvo vivos en la Verdad,
y a la Verdad viva en ellos.
Mediante este Espíritu, ellos como piedras vivas,
fueron edificados como una casa espiritual, (fundada sobre Sión, el monte santo,
en Jerusalén, la ciudad santa), la cual es la iglesia del Dios vivo,
columna y baluarte de la Verdad.
En esta casa espiritual, la iglesia, tuvieron su ciudadanía en el cielo, con Dios,
el juez de todos; con Cristo, el Mediador;
con los espíritus de los justos y de los santos ángeles
que siempre contemplan el rostro de Dios.
Ellos vivieron en el Espíritu, caminaron en el Espíritu, oraron en el Espíritu,
cantaron en el Espíritu, adoraron en el Espíritu y en la Verdad que los hizo libres.
Tuvieron a Dios morando en ellos y a Cristo caminando en medio de ellos,
y por la presencia y poder de Su vida en ellos,
quedaron verdaderamente muertos al pecado y vivos para Dios.
No lucharon contra el pecado con el espíritu legalista del hombre,
sino por medio del poder de la gracia,
la cual los hizo más que vencedores a través de Aquel que
los amó. Esto fue parte de la gloria de ese estado inicial,
el día del brillo del evangelio.

¡Pero he aquí, una noche espesa de tinieblas se extendió sobre la belleza de esto!
Algunos falsos hermanos salieron de la verdadera iglesia hacia el mundo,
y con vestidura de ovejas y haciendo una gran aparición
externa arrastraron al mundo en pos de ellos;
sí, incluso a algunos de entre las verdaderas iglesias.
(¡Cuán obligado se vio el apóstol Pablo a defender ante los corintios
su propio apostolado y doctrina para poder preservar esa iglesia de los
falsos apóstoles!) Y cuando reunieron suficientes seguidores en el mundo,
ganaron terreno contra las verdaderas ovejas y corderos de Cristo,
pelearon contra ellas y las vencieron.
Y cuando vencieron a las que tenían el testimonio vivo de Jesús
y el verdadero poder y presencia del Espíritu entre ellas,
establecieron su propia forma muerta y proclamaron
sobre todas las naciones de la tierra diciendo:
"`¡La revelación ha cesado!
Ya no hay que buscar tal Espíritu infalible,
ni las enseñanzas directas como sucedió con los cristianos en los días de los apóstoles,
quienes tenían la unción para enseñarles todas las cosas.`"
Y así dirigieron a los hombres a las tradiciones, a la iglesia (como la llamaban ellos,
y cuyo nombre ha sido controlado por la ramera desde los días de los apóstoles),
a escudriñar las Escrituras,
a la lectura de exposiciones sobre ellas y a obras religiosas constituidas
por la parte intelectual del hombre para instruir la parte intelectual.

En consecuencia, el curso total de la religión y del conocimiento de Dios,
llegó a estar fuera del Espíritu y de la vida de la que
primeramente había salido (y en la que primeramente se hallaba).
Ahora el cristianismo consistía en doctrinas de hombres,
en una forma de adoración y de conocimiento que había construido la sabiduría del hombre,
y en una imitación de aquello que estaba antes en la vida.

Como resultado de esto, y porque los hombres salieron de la vida,
del Espíritu y de sus enseñanzas directas,
y entraron en una forma externa de conocimiento y
adoración a Dios en la naturaleza equivocada,
se ha levantado el anticristo y el dragón se ha sentado en el templo,
apareciendo ahí como si fuera Dios, dando leyes y ordenanzas públicas de adoración,
demandando deberes privados y ejercicios de devoción. El anticristo
es obedecido y reverenciado en la observancia de estas cosas,
pero Dios, el Dios vivo y verdadero no es conocido, ni conocido Su secreto,
ni oída la voz que llama al hombre a salir de esas cosas,
debido al gran ruido que hace el dragón en el templo de Dios (que por ahora es suyo,
por haberlo ganado, aunque anteriormente era de Dios).

Con todo, le agradó al Señor a lo largo de esta noche de tinieblas,
levantar algunos testigos contra el dragón y contra todas sus inventadas formas de adoración,
pero estos testigos fueron cazados, perseguidos y derribados,
y sus testimonios proclamados como error, herejía, cisma y blasfemia.
De esta manera, los Católicos Romanos se oponen a los Protestantes llamándolos herejes,
cismáticos y que testificaban contra ellos.
Los Protestantes se oponen a los No-conformistas, Separatistas y Brownistas,
quienes son testigos en su contra.
Y cada secta se opone mayormente contra aquellos que son llevados más lejos de las tinieblas.
La forma^
footnote:[Penington a menudo usa la palabra __forma__ para hablar de alguna expresión,
ceremonia, estructura o sistema físico o externo usado en la religión.]
siempre mata la vida,
la vida que se mueve por debajo y que una vez apareció con alguna frescura.
Y cuando la vida muere (de la que la '`forma`' deriva su belleza y brillo externo),
pronto se marchita y muere la forma también, pues una vez inmolada la Semilla viva,
no queda nada salvo el espíritu muerto que se alimenta de la forma muerta.

¡Salgan rápido de ese espíritu! ¡Salgan rápido de Babilonia!
Porque este es el gran error de esta época:
Que el hombre con el conocimiento adquirido de las palabras de
las Escrituras sin la verdadera fe y sin la verdadera vida,
trata de evaluar la vida y el conocimiento que provienen de la verdadera fe,
y como no se alinean con las comprensiones que ha adoptado en su mente, las condena.
Por tanto,
al estar el hombre en la sabiduría y observancia terrenal (a la cual la
verdad nunca le fue revelada y siempre le ha sido ofensiva) tropieza,
tal como sucedió con los fariseos de antaño.

Escuchen por tanto mi exhortación, ustedes que aman sus almas:
¡Vengan a la fe y a la iglesia que es recibida, reunida y defendida por Cristo,
el Cuerno de Salvación! ¡Dejen sus razonamientos y disputas en esa sabiduría
que ha matado la vida y vengan a la sabiduría que brota de la vida! ¡Ustedes
encontrarán más certeza y satisfacción en un toque de la verdadera vida,
que en todos los razonamientos y disputas de los
hombres sabios hasta los confines de la tierra!

El terreno en el que crece la religión del hombre
(incluso el más celoso de los hombres) es malo.
Es el mismo terreno en el que se levantaba y crecía la religión de los fariseos.
Este terreno ha producido un tipo de fruto, a saber,
conformación a la letra de las Escrituras,
el cual está en el entendimiento y en la voluntad del hombre,
pero lo mantiene lejos de la vida y del crecimiento en ella.
Pero la verdadera religión se encuentra en la acogida de la Semilla de la vida, la cual,
mediante Su crecimiento forma una vasija para sí misma,
y toda la parte anterior (en la que se encontraba el pecado por
un lado y la justicia propia por el otro) desaparece.

=== La Fe del Hombre versus la Fe que es de Dios

Hay una fe que es del yo del hombre, y hay una fe que es don de Dios.
O, hay un poder para creer que es hallado en la naturaleza caída del hombre,
y un poder para creer que es dado de arriba.
Así como hay dos nacimientos, el primero y el segundo,
así cada uno tiene su fe y cada uno cree con su tipo de fe.
Ambas afirman que echan mano de lo mismo para la vida,
y la contienda acerca de la herencia no será acabada hasta que Dios lo determine.
Caín sacrificó con su fe y creyó que sería aceptado, si no lo hubiera creído así,
no se habría enojado cuando se encontró con lo contrario.
El espíritu cainista del hombre, el que lo expulsó de la vida de Dios,
el que no tiene la eterna vida de Dios morando en él,
está ocupado con la misma fe hasta el día de hoy y tiene
la misma expectativa de ella como la tenía Caín.

Esta fe del hombre es la raíz de la falsa religión, de la falsa esperanza,
de la falsa paz, del falso gozo, del falso reposo, del falso consuelo,
de la falsa seguridad, así como la otra es la raíz de lo verdadero.
En la fe que es del hombre y en el desarrollo de la misma,
se encuentra todo el conocimiento, el celo,
la devoción y la adoración del mundo en general y
el de la parte mundana en cada hombre en particular.
Pero el verdadero conocimiento, el verdadero celo,
la verdadera devoción y la verdadera adoración se encuentran en
la fe que le da Dios a los que han nacido de la Semilla inmortal,
los que viven en Dios y en los que Dios vive para siempre.

Ahora, le concierne a todo hombre considerar profundamente,
de cuál de estos dos tipos de fe procede su conocimiento, religión y adoración,
y en cuál de ellas se encuentra.
Porque si todo ello procede y se encuentra en la fe que es del hombre,
no puede agradar a Dios ni conducir a la salvación del alma.
Aunque tenga un sabor agradable a su paladar y le
administre mucha esperanza y satisfacción en el presente,
fracasará en el tiempo de necesidad.
Porque como habló Cristo con respecto a la justicia de los escribas y fariseos,
así puedo hacerlo yo con relación a esta fe.
A menos que la fe de ustedes exceda la fe que se encuentra
en la naturaleza del hombre (y todas las obras de la misma),
ella nunca los llevará al reino de Dios,
ni les concederá entrada en la herencia de la vida.
Porque el que herede la promesa, deberá ser el heredero correcto;
deberá tener la fe de Abraham, la fe de Isaac,
la fe que brota de la raíz de vida en la Semilla.
Esta fe conducirá a la semilla a ese manantial de vida (a partir del cual
crece como una rama) lo cual es la herencia prometida a la Semilla.
Aquí está Cristo, Alfa y Omega,
en cada alma particular en la que la vida se ha iniciado y perfeccionado,
siguiendo su curso a través del tiempo,
y de regreso a lo que estaba antes del principio.

Por tanto, observe y considere bien qué puede hacer esta fe que es del yo del hombre,
cuán lejos puede llegar en el cambio del hombre y producir
una conformación a la letra externa de las Escrituras.
Luego considere dónde queda afuera, qué _no puede_ hacer, qué cambio no puede realizar,
a qué no lo puede conformar.
Para que así la verdadera diferencia pueda ser establecida en su mente y no se
ponga un fundamento para tan grande error en un asunto de tan grande importancia.

[.numbered]
1+++.+++ Un hombre puede creer la historia de las Escrituras, sí,
y todas las doctrinas de ellas hasta donde pueda abarcarlas con su entendimiento,
con la fe que es del hombre.
Al leer el relato de la caída del hombre, de la recuperación por medio de Cristo,
del camino de la vida, etc.,
la fe del hombre puede creer el relato de estas cosas
tanto como puede creer el relato de otras cosas.

[.numbered]
2+++.+++ Habiendo creído el relato de la historia de estas cosas,
esta fe de manera natural pone todos los poderes
del hombre a trabajar (enciende el entendimiento,
la voluntad y las emociones) para evitar la miseria y alcanzar la felicidad.
¡Qué no haría el hombre para evitar la miseria perpetua
del alma y del cuerpo y obtener la corona de bendición eterna!
Tales ideas revuelven las emociones y ponen el entendimiento a trabajar al máximo,
para reunir todas las reglas de las Escrituras y practicar
todos los deberes y ordenanzas en ellas mencionados.
¿Qué proponen las Escrituras que se crea que el hombre no estaría dispuesto a creer?
¿Qué proponen que se haga que el hombre no estaría dispuesto a hacer?
¿Debe orar?
Él orará. ¿Debe oír? Oirá. ¿Debe leer?
Leerá. ¿Debe meditar?
Meditará. ¿Debe negarse a sí mismo, negar su propia justicia y deberes,
y sólo esperar la salvación en los méritos de Cristo?
Parecerá que hace esto también y dirá cuando haya hecho todo lo que puede,
que él no es más que un siervo inútil.
¿Dicen las Escrituras que él no puede hacer nada sin el Espíritu?
Él reconocerá esto también y esperará tener el Espíritu.
Dios ha prometido el Espíritu a todos los que se lo pidan y él lo ha pedido largamente,
y sigue haciéndolo, y por eso espera tenerlo.
Y así,
mediante una fe natural crece y se extiende como
un gran árbol y está muy confiado y complacido,
sin percibir el engaño en su raíz y a lo que todo este crecimiento lo va a llevar.

[.numbered]
3+++.+++ Habiendo hecho esto con la mayor seriedad y energía,
habrá necesariamente un gran cambio en el hombre.
Su entendimiento estará cada vez más iluminado,
su voluntad cada vez más conformada a eso que se
entrega y se inclina con todas sus fuerzas,
y sus afectos estarán cada vez más destetados;
él encontrará un tipo de vida y crecimiento en esto (de acuerdo a ese tipo).
Dejen que el corazón del hombre esté en algún tipo de estudio o de conocimiento,
aplicándose estrictamente a ello,
reuniendo entendimiento en su mente y calidez en sus afectos, y sucederá lo mismo.

[.numbered]
4+++.+++ Ahora bien,
¡cuán fácil es para un hombre equivocarse aquí y decir que eso es la verdad!
Primero confunde eso con la verdadera fe,
y luego se equivoca al aplicarle todo lo que le pertenece a la verdadera fe.
En consecuencia,
entra en el espíritu de error al principio y se equivoca
en el curso de su religión de principio a fin.
Ve un cambio realizado (mediante esta fe natural) en él y lo considera
la verdadera conversión y regeneración. Esto lo lleva a pedir,
a buscar y a orar, y él lo considera la verdadera oración,
la verdadera búsqueda y la verdadera petición. Esto limpia (según este género) su entendimiento,
voluntad y emociones,
y él lo toma como la verdadera santificación. ¡Ahora
este hombre se siente a salvo! ¡Él es un creyente,
es un adorador de Dios, es un cristiano, es un observador de los mandamientos de Cristo.
Cuando venga el azote abrumador no lo tocará, y los juicios,
plagas y amenazas en las Escrituras no tienen que ver con él, sino con los incrédulos!

No obstante,
el crecimiento de esta fe y la propagación de la misma en todo su conocimiento,
celo y devoción no ha cambiado la naturaleza de aquello en todo este tiempo.
Permanece siendo la misma que era al principio, es decir,
_sigue siendo el poder de la naturaleza del primer nacimiento._
Todos estos frutos no son más que los frutos de la primera naturaleza,
la cual continúa viva por debajo de todo.
Nada de lo que se encuentra en esta falsa fe puede matar la semilla de la que crece,
más bien la alimenta y la engorda para el sacrificio.

Hasta aquí puede llegar la fe del hombre,
pero entonces hay algo que queda excluido desde el mismo principio.
Hay algo que esta fe no puede recibir, no puede creer, o un lugar donde no puede entrar.
¿Qué es?
La vida, el poder, la realidad interior.
A pesar de que parece tener concordancia con las Escrituras de acuerdo a la letra,
no tiene concordancia con una sola escritura de acuerdo a la vida,
pues su naturaleza está excluida de la naturaleza de las cosas ahí descritas.

Por ejemplo: Puede tener un conocimiento literal de Cristo,
de acuerdo a la manera en que las Escrituras hablan de Él; su nacimiento, su predicación,
sus milagros, su muerte, resurrección, ascensión, intercesión. Sí,
pero no conoce la realidad de la que hablan.
La naturaleza de Cristo está oculta para ese ojo.
Por tanto,
puede que tenga un conocimiento literal de la sangre de Cristo y de la justificación,
pero no puede experimentar la verdadera vida de la sangre;
sólo puede hablar de ella de acuerdo a lo que lee en las Escrituras.
Puede que tenga un conocimiento literal de la santificación,
pero no puede recibir en sí misma lo que verdaderamente santifica.
Así es para la redención, la paz, el gozo, la esperanza, el amor, etc.
Puede que esta fe llegue hasta la parte externa de estas cosas,
pero se queda afuera de la parte interna, de la vida, del espíritu de ellas.
No puede tocarlas o acercarse,
ni tampoco puede ser testigo del cambio que se siente y se conoce ahí.

Esta es la gran discordia en el mundo entre estos dos nacimientos:
Uno contiende por su conocimiento en la letra,
el otro contiende por su conocimiento en la vida.
Uno establece su fe a partir de la parte natural, llamándola espiritual; el otro,
el que ha sentido el juicio de Dios sobre la fe del hombre
(y de ese modo ha llegado a conocer la diferencia),
establece la fe del verdadero heredero,
cuya fe tiene una fuente diferente y un crecimiento diferente al del otro.
La fe que proviene de Dios será recibida en la tierra y en el reino de la vida.
La otra será puesta en evidencia como la fe que proviene del nacimiento
de la esclava y será echada con su madre para que busque pan en otro lugar,
pues la simiente de la esclava no comparte la herencia de Isaac,
la semilla de la promesa.

[.discourse-part]
Pregunta: ¿Qué es entonces esta fe que es don de Dios?
¿En qué es distinta de la fe que es del hombre?

[.discourse-part]
Respuesta:
Es ese poder de creer que brota de la Semilla de vida eterna y leuda el corazón,
no con conceptos de conocimiento, sino con el poder de la vida.
En contraste,
la fe que es del hombre sale de la naturaleza del hombre
mediante consideraciones que afectan la parte natural,
y es mantenida viva mediante ejercicios naturales como leer, oír, orar, estudiar,
meditar, etc.
Pero la fe que proviene de Dios brota de una Semilla de vida dada,
crece en la vida de dicha Semilla y sólo se alimenta de la carne y de la sangre de Cristo.
Esta fe, de primera entrada, golpea la parte muerta en donde creció la otra fe,
y mediante Su crecimiento,
perfecciona esa muerte y levanta una vida que es de otra naturaleza,
una que nunca entró en el corazón del hombre para concebir.
Por la muerte de esa parte en nosotros llegamos a
conocer y a disfrutar la verdadera vida,
y por la vida que hemos recibido,
llegamos a ver que lo que los otros hombres llaman vida (la que nosotros
mismos anteriormente éramos propensos a llamar vida) no es sino muerte.
De este verdadero conocimiento le damos al mundo
un verdadero testimonio de lo que hemos visto y sentido;
pero ningún hombre recibe nuestro testimonio.

Nos duele en el corazón ver que los hombres establecen
lo que perece como el camino a la vida.
Con tierno amor les advertimos de la fosa a la que por lo general corren rápidamente,
aunque nos paguen con odio por nuestra buena voluntad y se conviertan
en acérrimos enemigos nuestros porque les decimos la verdad.

Ahora bien, no sean ariscos ni se enojen,
lean humildemente la siguiente parábola y se abrirá para vida.
La parábola dice simplemente así:
El que vendió la primogenitura luego la busca con lágrimas y gran dolor,
pero nunca la recuperará. Pero está el que yace muerto, el que tiene la promesa,
el que no se mueve hasta que se levanta por el poder de la vida del Padre,
luego lucha con el Padre, prevalece y obtiene la bendición de Él. Por tanto,
conozcan la parte en ustedes que se levanta primero, la que está muy ocupada en querer,
correr y hacer mucho ruido acerca de deberes y ordenanzas,
la que mantiene abajo la vida que ha asesinado.
Conozcan también la Semilla de vida, la heredera,
la que yace por debajo de todo eso y que tiene que
permanecer muerta mientras la primera parte vive.
Sin embargo,
si alguna vez escuchan la voz del Hijo de Dios esa Semilla vivirá
y la otra morirá. ¡Feliz será para siempre el que conozca esto!
Pero de miseria será la porción del que no pueda ser testigo de
una transformación profunda por el omnipotente poder del Dios vivo,
y solo haya pintado la vieja naturaleza y el sepulcro.
Miseria será la herencia de aquellos que nunca conocieron
la vieja vasija rota y una nueva formada,
la única que es capaz de recibir y retener el vino nuevo del reino.
Porque la otra vasija, al igual que los fariseos,
sólo puede recibir palabras acerca del reino escritas en el arcaísmo de la letra.

[.centered]
=== Algunas Afirmaciones con Respecto a la Fe, su Naturaleza, su Crecimiento y su Recibimiento de Cristo.

[.alt]
==== Afirmación I

Que la verdadera fe (la fe del evangelio, la fe del elegido,
la fe que salva al pecador del pecado y lo hace más que vencedor sobre el pecado
y el poder de las tinieblas) es la creencia en la naturaleza de Dios,
la cual da entrada, asegura, y hace que se permanezca en dicha naturaleza.

La incredulidad entra en la muerte y permanece en la muerte,
pero la fe injerta en la vid, participa de la naturaleza de la vid,
succiona el jugo de la vida de la vid.
Nada se puede hacer sino por la fe en la naturaleza,
y nada puede creer en la naturaleza sino eso que es uno con ella.
Así entonces, la fe no es creer la historia de las Escrituras,
creer y aplicar las promesas,
o creer que Cristo murió por los pecadores en general o por mí en particular;
todo eso puede ser hecho mediante la naturaleza incrédula (como se vio en los judíos).

[.alt]
==== Afirmación II

Que la verdadera fe brota del verdadero conocimiento de la naturaleza de Dios en Cristo.
No puede creer en la naturaleza de Dios aquel a quien
la naturaleza de Dios no le haya sido revelada primero.
Si un hombre escudriñara las Escrituras todos los días,
oyera todo lo que pueda ser dicho por los hombres con respecto a Dios, a Cristo, la fe,
la justificación, etc.,
fuera capaz de disputar acerca de eso y creyera que
puede probar sus argumentos contra todo el mundo,
y aún así no ha recibido el verdadero conocimiento de esas cosas,
toda su aparente fe en ellas no puede ser verdadera.

[.alt]
==== Afirmación III

Que sólo se puede tener verdadero conocimiento por
la directa revelación de Cristo en el alma.
Ningún hombre conoce al Padre sino el Hijo, y aquel a quien el Hijo se lo revele.
Los muertos oirán la voz del Hijo de Dios y los que
oyen vivirán. Un alma muerta no se levanta a vida,
sino por la directa voz de Cristo.
La predicación externa, la lectura de las Escrituras, etc.,
pueden dirigir y alentar a los hombres a prestar atención y a esperar la voz,
pero sólo la voz directa de Cristo en el alma puede vivificarla para Dios.
Hasta que la luz de la vida de Cristo brille directamente en el corazón,
el verdadero conocimiento no será dado.
(2 Cor.
4:6)

Por lo tanto, los que nunca han oído la voz directa de Cristo en el alma,
todavía están muertos en sus pecados y no han recibido aún el conocimiento vivo y verdadero;
en su lugar,
han recibido un conocimiento muerto y literal que
le da un brillo falso a las cosas en la parte muerta.
Es cierto, el uso apropiado de todos los medios es llevar al alma a la voz,
vida y poder directo, pero hasta que eso sea hecho, hasta que el alma llegue a eso,
a oír eso, a sentir eso, a ser arraigada en eso,
nada de lo hecho permanecerá. Pero el que conoce a Dios entra directamente en Su presencia,
y el que vive en Dios cada día, vive directamente en la vida.
La verdadera fe conduce a esto,
le da al alma tal toque y sabor de esto en un primer momento,
que hace que la vida sin ello sea imposible de satisfacer.

De esta manera Cristo excluyó a los judíos con todo su celo y conocimiento.
"`Pero ustedes no han oído jamás Su voz ni han visto Su apariencia.
Y Su palabra no la tienen morando en ustedes`" (Juan 5:37-38). Hay un oír la voz verdadero,
un ver la apariencia verdadero y un tener la palabra de Dios morando
en el corazón verdadero que mantiene al alma viva,
que la mantiene viviendo en la vida.
La voz da vida,
ver la apariencia diariamente conforma a la imagen
(la cual es contemplada por el ojo de vida),
y la palabra morando en el corazón nutre y alimenta al alma viva con el pan puro de vida.
Pero los judíos no conocían esto, sino que exaltaban sus días de reposo,
la ley de Moisés, las ordenanzas de Moisés, el templo de Dios,
la adoración a Dios establecida, y sin embargo,
estaban excluidos de la cosa misma a la que todas estas cosas apuntaban.
De la misma manera,
muchos fervorosos en estos días que no han llegado
a esto (como tampoco lo hicieron los judíos),
sino que siguen pegados a la letra del evangelio (como los
judíos estaban pegados a la letra de la ley),
tropiezan en la presente dispensación de vida y no pueden hacer otra cosa.

[.alt]
==== Afirmación IV

Que la revelación directa de Cristo de la naturaleza
de Su Padre es para los niños. No es para el sabio,
no es para el fervoroso, no es para el estudioso, no es para el devoto,
no es para el rico en conocimiento externo de las Escrituras, sino para el débil, tonto,
pobre y humilde de corazón. El hombre no recibe estas revelaciones por medio del estudio,
de la lectura, '`porque quiere o porque corre`',
sino al ser formado en la voluntad de la vida,
al ser engendrado por la voluntad del Padre, al nacer en esa voluntad,
al permanecer quieto en esa voluntad y crecer en dicha voluntad.
Aquí el niño recibe la sabiduría que es de arriba y diariamente
aprende la cruz que crucifica la otra sabiduría y la otra voluntad,
a las cuales les encanta alimentarse en la parte
sombría y robusta del conocimiento sin la vida.

Por lo tanto, si ustedes alguna vez desean recibir de Cristo ese conocimiento,
deben llegar a discernir el ojo en ustedes que debe ser cegado,
el ojo al que Cristo jamás le revelará al Padre.

El verdadero conocimiento es derramado únicamente en la nueva vasija.
El alma viva es la única vasija que recibe el conocimiento
vivo del Dios vivo desde Cristo la vida.
La vieja naturaleza,
el viejo entendimiento es para muerte y destrucción. A la sabiduría de la carne,
aunque pintada para parecer sabiduría espiritual,
no se le debe mostrar ninguna compasión; todo lo contrario,
dicha sabiduría con todo su celo, crecimiento y progreso en la religión debe perecer.
Todo el conocimiento que los hombres han reunido de las Escrituras en esa parte muerta,
de nada les aprovechará, sólo para estorbarlos.
Cada edificación que la lepra del pecado ha cubierto debe ser derribada.

[.alt]
==== Afirmación V

Que esta fe (la que brota del verdadero conocimiento) es don de Dios,
y no es el poder de creer que se encuentra en la naturaleza del hombre.
Es de otra naturaleza, es de la naturaleza del Dador.
Cuando el hombre es llamado a creer,
no es llamado a producir esa fe con la que cree otras cosas,
sino a recibir y a ejercitar el don de fe, el cual es de arriba.
Eso que debe ser creído es espiritual y debe ser espiritual lo que cree en ello.
El hombre con todos los poderes de su naturaleza está excluido.
Déjelo creer, leer, orar, oír y ejercitarse en eso que llama deberes y ordenanzas,
y todo se afirmará en la parte equivocada del hombre,
sólo alimentará la parte equivocada,
y dicha parte con toda su comida y nutrición quedará corta de la vida.

Por lo tanto,
la verdadera entrada a la vida es la experiencia del poder que
mata la capacidad y propensión natural del hombre a creer,
para que así el don de la verdadera fe pueda ser recibido.
Pues no hay resurrección y vida de lo segundo,
sin la muerte de lo primero con todas sus facultades y poderes naturales.

[.alt]
==== Afirmación VI

Que sólo por esta fe que es don de arriba (no la fe que crece en
el jardín de la vieja naturaleza y se alimenta del arcaísmo de
la letra y no de la novedad del Espíritu) es recibido Cristo.
Porque Cristo sólo puede ser recibido por la fe que viene de Él,
y esa fe que viene de Él no puede hacer otra cosa más que recibirlo.

La fe del hombre rechaza a Cristo, aunque reciba un conocimiento literal de Él,
de lo que oye de los hombres o lee en las Escrituras
con respecto a Él. No puede ser de otra manera,
pues la fe del hombre al no ser de la naturaleza de Él, no puede sino rechazarlo.
Pero la fe que es dada por Dios, que es de arriba,
al ser de la misma vida y naturaleza de Cristo,
no puede rechazar el origen de su propia vida, y lo recibe inmediatamente.
No hay distancia de tiempo; tan pronto es recibida la fe,
es recibido Cristo y el alma es unida a Él en la fe.
Así como la incredulidad lo rechaza inmediatamente,
la fe lo deja entrar inmediatamente y centra el alma en Él,
el alma inmortal siente la virtud inmortal y se regocija
en la fuente verdadera de su propia naturaleza inmortal.

Pero la fe del hombre nunca llega a esto, nunca recibe a Cristo,
sólo recibe una descripción de las cosas concernientes a Él,
y a esta fe que se afirma en la letra^
footnote:[Siempre que Penington habla de __la letra,__ hace referencia
a las palabras literales de las Escrituras que testifican (y que
sólo pueden testificar) de la verdadera sustancia espiritual.
Ver Romanos 2:29; 7:6; 2 Corintios 3:6.]
se le opone la fe que se afirma en la vida.
Aquí está el espíritu del anticristo; aquí está el misterio de iniquidad,
cambiando de una forma a otra.
Porque el anticristo no niega directamente a Cristo, ni niega la letra,
más bien aplaude a Cristo y elogia la letra,
pero de manera tal que estos alimenten la fe de su propia
naturaleza y mantengan la esperanza allí. En consecuencia,
el espíritu del hombre se une con lo que alimenta su propia naturaleza,
con lo que las interpretaciones de su propio entendimiento reúnen de las Escrituras,
y así puede venerar a Cristo y decir que espera ser salvo por Él,
aun cuando el espíritu de enemistad contra la naturaleza de Cristo se
aloje en su corazón. Ese es el anticristo donde quiera que se encuentre,
y esa es su fe; grande es su conocimiento y muchos sus disfraces.
Sin embargo, el Señor lo está buscando, Él lo desvestirá y hará aparecer su desnudez.

[.alt]
==== Afirmación VII

Que Cristo es recibido como un grano de mostaza y que todos los ojos,
salvo el ojo de la verdadera fe, lo desprecian.
Él es la piedra que la sabiduría de los edificadores ha rechazado en todas las edades.
Ellos buscan un Mesías glorioso, pero no lo conocen en Su humillación,
no lo conocen en la semilla pequeña,
a partir de la cual Él tiene que crecer en Su gloria.
Y así, al perderlo por completo,
construyen las cosas que tienen que ver con Él a partir
de sus elevadas imaginaciones en la altivez de la mente.

Cuando Dios envió a Cristo en la carne,
no había majestad ni belleza en Él. Como resultado,
los judíos cuya esperanza y expectativa estaba en eso,
no vieron belleza ni atractivo en Él. Así es hoy.
Cuando Dios viene a ofrecerse a los que afirman tener sus esperanzas en Él,
no ven belleza en Él y lo rechazan todos los días. "`¿Qué?,`" dicen,
"`¿esta cosita pequeña como una semilla de mostaza es el
glorioso Cristo del que las Escrituras han hablado tanto?
Porque nosotros conocemos Su origen (su padre, madre y parientes están con nosotros),
lo encontramos en nuestra propia naturaleza.`"
Entonces, al igual que los judíos de la antigüedad,
hacen un gran ruido acerca de Cristo pero Lo rechazan
porque carecen del verdadero ojo de la fe.
Porque si tuvieran ese ojo,
verían la virtud en la semillita y la recibirían en sus corazones en Su humillación,
donde diariamente llama a la puerta para entrar.
No estarían contentos hasta que esta semilla de mostaza
creciera y se hiciera un árbol grande y glorioso.
Pero a falta de dicho ojo Lo mantienen fuera y dejan entrar al asesino pintado,^
footnote:[Penington y sus contemporáneos con frecuencia usan la palabra __pintar__ o __pintado,__
para referirse a la cubierta falsa o al embellecimiento
exterior de algo que es corrupto y carnal debajo.]
el que habita en ellos y se cubre con conocimiento, celo, fe, esperanza, etc.,
en la vieja naturaleza, en la vasija vieja, en el antiguo entendimiento.
Ellos hablan bien de Dios y de Cristo, mientras el espíritu maligno tiene sus corazones,
mora allí y produce su propio fruto viejo y maligno
bajo la apariencia de devoción y santidad.

¡Oigan ahora, ustedes, los que son sabios en la letra pero extraños para la vida!
Hay una aparición de Cristo en el corazón con dos caras.
Una aparición de Él como siervo para obedecer la ley,
para cumplir la voluntad del Padre en el cuerpo que el Padre le preparó,
y otra aparición de Él en gloria, para reinar en la vida y poder del Padre.
El que no conoce la primera en su corazón jamás conocerá
la segunda ahí. El que no las conoce internamente,
jamás conocerá una venida externa y visible para su consuelo.
Porque si Cristo debe venir externamente para reinar (como muchos esperan),
que conste que Él no reinará en un corazón al que
no haya entrado primero y lo haya sometido a Él;
lo cual sólo puede ser hecho mediante Su aparición ahí,
primero como Siervo y luego como Rey.

Pero, ¿en qué estado están los llamados cristianos ahora,
los que no conocen Al único en ellos que es capaz de servirle a Dios?
¡Se están esforzando y luchando en la naturaleza en la que el pecado
tiene poder (la cual no puede vencer por no estar unida a la vida),
son ajenos a dicha vida y al poder en que son vencedores!
Por lo tanto, consideren todos en la profundidad de sus corazones,
porque lo siguiente es infaliblemente cierto:
Los que nunca han recibido la Semilla de vida en sus corazones,
nunca han recibido a Cristo.

[.alt]
==== Afirmación VIII

Que esta Semilla al ser recibida en el interior crece en su propia forma.
Ahí crece hasta ser el cuerpo que ha de servirle
al Señor. Así como una semilla echada en buena tierra,
o como la semilla del hombre o de la bestia sembrada en un vientre apropiado,
recibe forma y crece como una planta o como una criatura viva,
así es con la Semilla de Cristo en Su tierra.

Ahora bien, esta nueva criatura (o el Espíritu de vida en esta criatura,
el cual está en unión con ella), es la regla del cristiano.^
footnote:[La palabra __regla__ es usada para referirse a lo que gobierna,
rige o tiene autoridad en la vida del creyente.]
(Gal.
6:15-16; 1 Juan 2:27; Heb.
8:10, 12) Anteriormente fueron dadas reglas externas para el estado externo, es decir,
le fueron dadas reglas externas a los hombres bajo
la ley que no habían sido llevados a la vida,
pero que eran ejercitados bajo sombras y representaciones de la vida.
Pero el Hijo, quien mora en el interior, es la sustancia de todo,
es la vida y es uno con el Padre; no está atado a ninguna regla externa,
sino que vive y camina en la directa luz del Espíritu de Su propia vida.
El que tiene al Hijo tiene esta regla, el que no tiene esta regla no tiene al Hijo.
El que no tiene al Hijo no tiene la verdadera fe (la que lo recibe a Él inmediatamente),
por tanto, no es cristiano, sino que ha robado el nombre de cristiano de la letra,
pues no ha recibido nunca la naturaleza del Espíritu,
la única a la que le pertenece el nombre.

[.alt]
==== Afirmación IX

El que tiene a Cristo o la Semilla de vida eterna formada en él,
(Semilla en la que el Espíritu mora siempre, el mismo Espíritu que dio las Escrituras),
es el único capaz de entender las Escrituras que el Espíritu dio,
porque el Espíritu lo lleva al entendimiento de ellas.
Pero el que no ha recibido esa Semilla, que es como un grano de mostaza,
y por tanto no ha recibido a Cristo ni a Su Espíritu (sin importar lo que pueda fingir),
jamás podrá llegar al verdadero conocimiento de las Escrituras por medio de sus estudios,
humanidades, idiomas, lectura de comentaristas, conferencias e incluso experiencias,
pues tal hombre carece de la verdadera llave, la única que puede abrir.
Puede que tenga una gran colección de llaves equivocadas,
ninguna de las cuales puede abrir.
Él no tiene la llave del verdadero conocimiento, por tanto, queda fuera de él,
y sólo puede entrar al tipo de entendimiento que la llave equivocada puede abrir.

[.alt]
==== Afirmación X

El que ha recibido el nuevo pacto en su corazón,
con las leyes de la vida escritas ahí por el Espíritu de vida,
entiende que ese escrito vivo es su regla.
Las Escrituras testifican del lugar donde el pacto y la ley de vida están escritos,
y si deseamos leerlos debemos ir ahí. Debemos ir al lugar que las Escrituras nos señalan.
Debemos ir a Cristo el libro de vida y leer ahí con el ojo que Cristo da.

Las Escrituras están dispuestas a rendir su gloria a Cristo, Quien estaba antes de ellas,
está sobre ellas y estará después de ellas.
Pero hay un espíritu falso,
uno que se ha colocado a sí mismo en el conocimiento literal de las Escrituras
y formado imágenes y semejanzas de la verdad de ellas (y todo el mundo
va en pos de las imaginaciones de su propio corazón). Ahora bien,
todas esas imágenes y semejanzas caen cuando aparece Cristo la vida.
Ese espíritu falso afirma las Escrituras en forma de engaño,
justo como los judíos afirmaban a Moisés. Es un espíritu seductor que
levanta edificios y formas de conocimiento de la letra de las Escrituras,
y no llega a sentir, ni a unirse, ni a vivir en Cristo la vida.
A menos que ustedes lleguen a esa vida, la lectura que hagan de las Escrituras es vana,
y todas las reglas que han reunido para practicar y todo
consuelo sacado de las promesas terminará en vanidad.
No hay posibilidad de conocer o de recibir las Escrituras,
sino al sentir el toque real de la vida interior de ellas.
"`La sabiduría es justificada por sus hijos,`" pero lo que no ha
nacido de ella no puede justificar su vientre o nacimiento.

Los judíos, que eran un pueblo externo, habían recibido una regla externa,
una ley de mandamientos, estatutos,
juicios y ordenanzas propias al estado en que estaban.
Sin embargo, todo eso debía ser quitado y finalizado en aquello que representaban.
Entonces, puesto que Cristo la sustancia ha venido (Él,
que es el fin de todas estas sombras),
y puesto que el verdadero Judío ha sido resucitado inmediatamente en la vida,
tenemos ahora necesidad de que la vida sea directamente nuestra regla.
Para los que están bajo el evangelio, para los que han llegado a la sustancia,
para los que han sido engendrados y han nacido en la vida,
no puede haber otra regla proporcional a su estado además de Cristo la sustancia,
Cristo la vida.
Aquí sólo Él es la luz, el camino, la verdad, la regla.
Aquí el Espíritu es la regla, la nueva criatura es la regla, el nuevo pacto es la regla,
todo lo cual está en unidad; el que tiene uno de ellos los tiene todos,
y el que no tiene uno de ellos no tiene ninguno.

Por lo tanto,
instrucciones escritas sacadas de las Escrituras no pueden
ser la regla para el que es verdadero cristiano.
Sólo la medida de gracia, la medida de luz, la medida del Espíritu,
la medida del don recibido en el alma viva proveniente
de la fuente de vida es la regla de vida.
Sin embargo,
los cristianos en la degeneración han perdido esto y han tomado
palabras como regla (las cuales no fueron dadas con ese propósito).
Y así con deducciones de la mente terrenal alimentan la parte terrenal.
¿Qué puede ser alimentado por el conocimiento de los hombres
sobre las Escrituras sino el entendimiento terrenal?
¿No es la voluntad terrenal estimulada y los afectos terrenales enardecidos?
Cuando tales frutos son ofrecidos a Dios y rechazados (como con Caín),
el hombre terrenal se enoja al ver que Dios ha resucitado a Abel, al hermano menor,
quien ofrece el Cordero de Dios y le sirve al Dios vivo en su propio Espíritu
vivo y con la fe que viene de Él. La religión de Abel no se encuentra
en la parte en la que se encuentra la religión de los hombres,
se halla en la muerte de dicha parte y en la resurrección de otra parte,
en la parte de la que mana la vida.

=== Una Advertencia Necesaria

Oigan y consideren esto que está registrado en Apocalipsis 22:18-19:

[quote.scripture]
____
"`Si alguno añadiere a estas cosas,
Dios traerá sobre él las plagas que están escritas en este libro.
Y si alguno quitare de las palabras del libro de esta profecía,
Dios quitará su parte del libro de la vida,
y de la santa ciudad y de las cosas que están escritas en este libro.`"
____

Grandes son las plagas escritas en este libro,
incluido el derramamiento de la ira pura y eterna,
tormento de día y de noche en la presencia del Cordero, etc.
Grande es también la vida y la bienaventuranza que son prometidas
a los que pelean y vencen el misterio de la iniquidad.
Ahora,
enfrentar todas las plagas mencionadas aquí y perder todas las bienaventuranzas prometidas,
¿no sería un estado terriblemente triste?
El Señor dice que esto es lo que le acontecerá al que añada a las cosas
escritas ahí o quite de las palabras de esa profecía. Por lo tanto,
en el temor de aquel que ha dicho esto (y que con seguridad hará cumplir su promesa),
que todos escudriñen y consideren _quién es el añadidor y quien es el quitador._

Consideren ahora,
¿no es cierto que el que le da otro significado a cualquier escritura
además del significado verdadero y correcto de la misma,
es tanto añadidor como quitador?
El tal quita el sentido verdadero y le añade sentido que no es verdadero.
El Espíritu del Señor es el verdadero intérprete de las Escrituras, nunca añade ni quita,
pero el hombre sin ese Espíritu sólo puede adivinar, imaginar,
estudiar e inventar un significado y por eso siempre está añadiendo o quitando.
"`Este es el significado,`" dice uno.
"`Este es el significado,`" dice otro.
"`No, este es el significado,`" dice un tercero o un cuarto.
Otro, tal vez más ingenioso y educado declara que todos son correctos,
y otro más ingenioso aún,
dice que ninguno es correcto e inventa un significado diferente de todos los
demás. ¿No es esto clara muestra de que el que habla de esta manera carece del
Espíritu del Señor para abrir las Escrituras y manifestar el verdadero significado?
¿Acaso no está obrando en el misterio de las tinieblas?
Y sin embargo,
esta persona que está obrando con su propio espíritu oscuro en las tinieblas,
confesará con palabras que no hay entendimiento o verdadera
revelación de las Escrituras salvo por el Espíritu de Dios.
Si sólo el Espíritu es el verdadero intérprete de las Escrituras,
¿cómo se atreven ustedes a colocar su imaginación, fantasía,
razón o entendimiento sobre esta obra,
y adivinar sobre lo que el Espíritu no les ha mostrado?
¿No son hallados de esta manera añadiendo y quitando?

El que es añadidor, el que es quitador,
proclama contra el Espíritu del Señor. Él no puede evitar esto por el camino en que está,
pues habiendo juzgado primero su propia oscuridad como luz, en el siguiente lugar,
juzgará necesariamente la verdadera luz como oscuridad.
El que ha establecido el significado que inventó de cualquier escritura como verdadero,
necesariamente se opondrá al verdadero y lo llamará falso.
En consecuencia, por haber comenzado equivocado en su conocimiento de las Escrituras,
está comprometido a hacer uso de ellas contra el Señor y contra su propia alma.
Y sin embargo, piensa para sí, que hace uso correcto de ellas,
que le sirve al Señor y que no se opone a Su verdad,
que más bien se opone al error y a la herejía. Él
mismo es quien todo el tiempo ha estado en el error,
en la herejía y contra la verdad,
siendo un extraño para el Espíritu en cuya presencia y vida la verdad crece.

[.discourse-part]
Pregunta: Pero,
¿cómo podemos evitar añadirle a las cosas o quitar de las palabras de la profecía,
o de otras escrituras, para no toparnos con el peso de esta maldición,
o perder la bendición?

[.discourse-part]
Respuesta: 1. Esperen la llave del conocimiento, la cual es don gratuito de Dios.
No vayan con una llave falsa a las Escrituras de Verdad,
porque ella no las abrirá. El hombre se apresura a conocer el significado
de las Escrituras y a entrar en las cosas de Dios,
y así se salta la puerta con su propio entendimiento.
Como no tiene paciencia para esperar conocer la puerta,
ni para recibir la llave que abre y cierra la misma,
recoge muerte de las palabras que salieron de la vida.
Yo me atrevo a afirmar con toda seguridad,
que todos los que han andado por este camino sólo tienen un conocimiento muerto;
la muerte en ellos se alimenta de dicho conocimiento y la vida nunca se levanta.

Consideren el peso de este consejo:
No hay revelación de las Escrituras sino por la verdadera llave,
ni hay forma de llegar a la llave sino hasta que le plazca al Señor darla.
¡Qué debe hacerse entonces sino esperar,^
footnote:[Penington habla a menudo de esperar en el Señor. Este esperar,
tal como lo describe en varios otros documentos y cartas, no habla de un esperar pasivo,
refiriéndose principalmente al paso del tiempo.
Más bien es un esperar activo, un vuelco del corazón intencional y constante,
una búsqueda del Señor,
una permanencia en la medida de la luz de Cristo
que está obrando actualmente en el corazón.]
(en el silencio de la parte que está adelante y corriendo
al frente) hasta que la llave sea dada!

[.numbered]
2+++.+++ No corran en su propio entendimiento, ni en su propia voluntad,
buscando el significado de las Escrituras,
porque de esta manera ustedes alimentan con las Escrituras
lo que todas las palabras de vida intentan destruir.
Por el contrario, de la misma manera que esperan la llave al principio,
esperen continuamente la aparición y el movimiento del Usuario de la llave,
y Él cerrará sus entendimientos y sus voluntades constantemente,
y los dejará entrar a la vida tanto de las profecías como de las doctrinas.

[.numbered]
3+++.+++ No injerten ningún fruto del árbol de la vida en el árbol del conocimiento,
porque no crecerá ahí. Puede que crezca una apariencia o semejanza del verdadero fruto,
pero el fruto mismo no lo hará. En otras palabras,
no amontonen un tesoro de conocimiento en la parte intelectual que perece.
Más bien conozcan el verdadero almacén de las cosas de la vida,
que está en la vida misma, y en ese entendimiento que es formado, permanezcan y vivan.
No reserven maná para alimentarse de él en el viejo almacén,
(no sea que la parte carnal corra allí cuando el apetito carnal se despierte tras comida),
antes bien reciban todos los días el pan de la mano de la vida.

[.numbered]
4+++.+++ Hay un conocimiento de las cosas por el Espíritu
que revela las palabras que hablan de ellas,
o por profecías interiores y directas que provienen de la Palabra de vida en el corazón.
Este es un conocimiento excelente y no es encontrado en la parte terrenal del hombre.
Como es un conocimiento muy precioso y mucho más pleno y cierto que el otro,
y tiene la naturaleza y el poder directo de la vida en sí mismo,
es perfectamente capaz de preservar.
Por tanto,
no se contenten con las profecías reveladas o con los significados verdaderos
de las cosas (aunque este tipo de conocimiento es muy excelente y muy raro),
sino esperen experimentar la cosa misma de la que hablan
las palabras y ser unidos a ella por el Espíritu vivo,
entonces, tendrán el conocimiento que proviene de la naturaleza de la cosa misma.
Este es más profundo e interior que todo el conocimiento
que pueda tenerse de las palabras referentes a la cosa.

[.numbered]
5+++.+++ Cuando sientan esas cosas,
busquen la preservación de las mismas en la fuente de vida de ellas.
Dejen que la raíz los sostenga y sostenga todo el conocimiento que tienen,
junto con todo lo que les es concedido de Dios libremente.
Cuando se sientan leudados por la vida y se conviertan en una rama que crece de la vida,
aprenderán a permanecer en la vida y a mantener todo lo que les
es dado ahí. No tengan nada que puedan llamar propio nunca más;
perezcan para sí mimos y sean hallados en Él. Conozcan la tierra de los vivos,
en la que todas las cosas de la vida viven y no pueden vivir en ningún otro lugar.

Ahora bien, en todo esto hay estabilidad y seguridad.
Yo empiezo a aprender algo de Dios desde la primera
revelación que hace la verdadera llave;
empiezo a aprenderlo con certeza y a sentir seguridad y fundamento en ello.
Ahí empiezo a crecer.
Crezco en el verdadero aprendizaje y en el verdadero cimiento.
No tomo conocimiento de las Escrituras que provenga de mí mismo,
de mi propio entendimiento, de mi propio estudio,
de mi propia invención o de estudios de otros comentaristas,
sino de la mano divina de Dios.
¿Cómo puede torcer las Escrituras aquel que se mantiene con un solo objetivo
y no tiene deseo de ningún significado de ellas sino sólo del verdadero?
¿Cómo no va a entender el que espera recibir el verdadero significado,
no para alimentar la parte lujuriosa y de conocimiento en él,
sino para alimentar la vida con el verdadero significado?
Y cuando la vida no necesita del verdadero significado de las Escrituras,
la persona está contenta de tenerlas calladas y de estar sin ellas.
Digo, ¿cómo podría este hombre torcer las Escrituras?

Pero el hombre que ya ha recibido o inventado un significado,
va a las Escrituras y las dobla para conformarlas a ese significado,
y donde se oponen inventa una manera para hacerlas cumplir.
Las tuerce hacia adelante y hacia atrás para que hablen conforme a lo
que ya ha recibido y creído. De esta manera todo tipo de personas,
católicos romanos y protestantes,
doblan las Escrituras para hacer que hablen en conformidad a sus opiniones y prácticas,
sin haber experimentado el verdadero aprendizaje.
Estos están engañados y son inestables,
sujetos a ser sacudidos por cualquier viento de la
razón que sea más fuerte que el de ellos.
Tal uso torcido de las Escrituras es para su propia destrucción.

[.discourse-part]
Pregunta:
¿No es la oración un medio por el que uno puede evitar
lo falso y tomar posesión de lo verdadero?

[.discourse-part]
Respuesta: Cierto; hay una oración que es un medio, y hay una oración que no es un medio.
Hay una oración que es una ordenanza, y hay una oración que es un invento.
Hay una oración que es el aliento del verdadero Hijo,
y hay una oración que es el aliento de la parte carnal.
Hay una oración del primer nacimiento, y hay una oración del segundo nacimiento;
ambas claman y lloran al Señor por lo mismo.
Una de estas oraciones es el medio verdadero, la otra no.
Una de ellas es ordenanza de Cristo, la otra es ordenanza del anticristo.
Ahora, la pregunta es: ¿Cuál de estas es la oración de ustedes?
¿Salen sus oraciones de su propio aliento o del aliento de Dios?
¿Salen ellas de la renovación del Espíritu de vida, o de la parte natural pintada?
En consecuencia, es la oración de ustedes el medio verdadero o el medio falso.
Si es el verdadero, poseerán el Espíritu, la vida, el reino; si es el medio falso,
nunca obtendrán eso.

Los católicos oran, los protestantes oran; unos con formas, otros sin formas;
unos meditan de antemano, otros no meditan.
¿Es todo esto el verdadero medio, o es alguno de ellos el verdadero medio?
El nacimiento del Hijo verdadero es la única oración verdadera;
Él sólo ora en el movimiento y en la dirección del Espíritu
que lo engendró. Esta es una oración de acuerdo a la voluntad,
en la vida, y desde el poder de Dios.
Pero las oraciones de los hombres,
que son de acuerdo al horario que ellos establecieron para sí mismos,
o de acuerdo a los deseos en sus propias mentes,
las cuales le ofrecen a Dios en la naturaleza y corazón que peca contra Él,
son el medio falso.

¿Pueden ustedes orar?
¿Cómo aprendieron a orar?
¿Fueron enseñados de lo alto,
o ganaron la destreza y la habilidad por medio del
ejercicio y mejora de sus propias partes naturales?
¿Comenzaron con suspiros y gemidos,
permaneciendo allí hasta que el mismo Espíritu que
los enseñó a gemir les enseñara también a hablar?
¿Han sido alguna vez capaces de distinguir los suspiros
y gemidos de engendramiento del Espíritu,
de los suspiros y gemidos de sus partes naturales y emotivas?
¿Han sido empujadas a un lado esas partes naturales, con todos sus suspiros, gemidos,
deseos y esfuerzos?
¿Ha sido levantada la Semilla inmortal por el Espíritu de vida eterna,
la cual enseña a llorar y afligirse, y finalmente a hablar,
para pedirle al Padre la preservación y alimentación de Su vida?
Si ese ha sido el caso, ustedes conocen la oración que es el verdadero medio,
de lo contrario, aunque oren mucho tiempo, con grandes emociones y fuertes deseos,
esa oración no es otra cosa más que el medio falso,
con la calidez falsa que sale del fuego falso.
Este no es más que el medio que el espíritu de la ramera
(el que no está en unión con la vida ni con el poder,
sino que mantiene a la semilla en esclavitud) ha puesto en lugar del verdadero.
Este no puede llevar a la verdad,
pero sí mantener vivo al enemigo de Dios bajo una cubierta agradable.
Tampoco es la adoración al Dios vivo, ya que es de otro espíritu y para otro espíritu.
