== Capítulo V. En Busca de las Ovejas Esparcidas

=== Prefacio

[quote.scripture, , Jer. 2:13]
____
"`Porque dos males ha hecho mi pueblo: me dejaron a mí, fuente de agua viva,
y cavaron para sí cisternas, cisternas rotas que no retienen agua.`"
____

Esta fue la queja del Señor con respecto a Israel de principio a fin.
El Señor se deleitó engendrando, alimentando y criando a este pueblo para Sí mismo,
pero ellos continuamente se estaban rebelando y levantando
contra Él. Hizo grandes cosas por ellos,
pero seguían olvidándolo.
Los redimió por medio de Su brazo extendido, los alimentó y los defendió,
pero ellos no lo conocían. (Isa.
1:3) En su lugar,
se adornaron con los ornamentos que Él les había
dado y luego levantaron su talón contra Él. (Eze.
16:7; Deut.
32:15) En términos simples,
introdujeron en sus propias vasijas el conocimiento que
pudieron de Él y luego lo dispusieron para sí mismos.
Vivieron a partir de sí mismos,
sin la fresca corriente de vida que brota de la fuente
de la que venía el conocimiento de ellos.

Los sacerdotes no buscaron al Señor porque pensaban que podían
manejar la ley y enseñar el conocimiento de ella sin Él,
y los profetas pensaban que podían profetizar por otro espíritu.
(Jer.
2:8) De este modo, el Señor Dios de vida no vivía en ellos,
más bien ellos vivían en las cosas que alguna vez salieron de la vida.
Al separarse de la fuente,
quedaron muertos y sólo podían alimentar la parte muerta en ellos,
esa que estaba separada de Dios.
Por tanto, aunque profesaban grandes cosas, multiplicaban oraciones, sacrificios,
ayunos y se acercaban a Dios con sus labios,
sus corazones estaban lejos de Él. Ellos habían abandonado la fuente;
no bebían del agua de la fuente, no bebían de la Roca que los seguía,
sino del agua de sus propias cisternas.
Establecieron ese conocimiento de la ley como su luz,
el cual habían excavado con las herramientas de su propio entendimiento
sin el Espíritu que la escribió. Este fue el error del antiguo Israel:
Bebieron muy celosamente de las aguas de la ley, pero no las bebieron de la fuente,
sino de las cisternas que habían cavado.

Y así como sucedió con el antiguo Israel ha sucedido con Israel desde entonces.
El Israel cristiano siempre está reincidiendo,
siempre está olvidando al Señor. Siguen tomando lo que pueden de
Él para vivir de sí mismos y rechazan vivir por medio de Él. Obtienen
cuanto conocimiento pueden de las Escrituras sin Él,
obtienen lo que pueden de sus ejercicios y experiencias,
pero abandonan la fuente de sus vidas.
Como resultado, este Israel también se marchita,
se muere y es objeto de burla para los paganos,
porque aunque habla maravillas de su Dios, en muchas formas está como los paganos.
Incircuncisos como los paganos,
ignorantes de la virtud y del poder de la vida como los paganos,
en lucha constante contra el pecado con lo que no puede vencer al pecado,
en consecuencia,
son esclavos de sus pasiones y de su corrupción también. Al igual que
los paganos no conocen la verdad que lo hace a uno verdaderamente libre.

¡Ay! ¡Ay!
Babilonia ha prevalecido, su rey ha reinado.
Sión ha sido sujeta a cautiverio y lo que se ha levantado
con Su nombre ha sido la inmunda descendencia de Babilonia.
Esta ha dado fruto amargo, fruto repugnante.
El fruto de Babilonia está delicadamente pintado a la vista de los ojos naturales,
pero es repugnante en su naturaleza.
Este ha sido el estado de apostasía desde los días de los apóstoles,
en el que ha reinado lo que no es de Dios y lo que es de Dios ha sufrido y ha sido censurado.

La profunda consciencia de esto ha afectado mi alma desde mi juventud,
cada vez que el testigo eterno se despertaba en mí
y Su luz eterna me manifestaba las tinieblas.
En aquel entonces yo no sabía que esa era la luz y seguía intentando medir Sus apariciones
en mí mediante las palabras que la propia luz le había hablado a otros anteriormente.^
footnote:[Es decir, las palabras de las Escrituras escritas por los profetas y apóstoles.
Él trató de medir e interpretar la aparición de la luz de Dios
en su corazón por medio de su propio entendimiento de esas palabras.]
De esta manera colocaba mi propio entendimiento y mi propia comprensión como la medida,
aunque en ese momento no percibía ni pensaba lo estaba haciendo, y así,
por causa de la ignorancia,
mataba continuamente la vida y me conformaba con la apariencia
de vida que mi intelecto juzgaba más conveniente para las Escrituras.

Entonces un día, o más bien, una noche de oscuridad y angustia se apoderó de mí,
algo que derretiría el corazón más duro si oyera el relato.
Sin embargo, el Señor estaba conmigo en esa oscuridad,
me estaba protegiendo y me estaba formando para Él. Y el sabor que tuve de Él entonces,
fue mucho más allá de lo que yo había conocido anteriormente en la forma más pura de
mi religión. Él poderosamente calló mi intelecto y preservó mi vida del traidor.
No obstante,
aquello sobre lo que el tentador había hecho su obra no fue completamente
destruido en mí y el Señor le permitió poner una trampa.
Mis pies muy pronto se enredaron inconscientemente,
mi sencillez fue traicionada y la parte carnal creció sabia
por los ejercicios con los que el Señor me había tratado.
Esto me envenenó y me dolió;
golpeó la raíz de mi vida y la muerte creció insensible sobre mí.

El diablo, el envidioso vendedor de semillas, me engañó,
abrió mi parte intelectual (mediante la sutileza de la tentación y del engaño),
la que el Señor había destruido, y dejó entrar lo que el Señor había echado.
Como resultado de esto,
el camino de la vida se detuvo y el camino de la
muerte se abrió. Este fue mi estado por algún tiempo,
hasta que al fin el Señor sacó Su espada sobre mí y me hirió en lo más íntimo de mi alma,
y por causa de Su golpe mis ojos se abrieron.
Entonces vi la ceguera del ojo con el que yo pensaba que podía ver muy lejos,
y vi la estrechez del corazón y del espíritu que me habían parecido tan grandes
y vastos en comprensión. Mi alma se inclinó ante el Señor para matar eso,
para matarlo de hambre y dejarlo en ridículo.
De hecho, mi deseo era tan grande en busca de que esto muriera,
como grande era mi deseo en busca del disfrute de la vida en el Señor.

Esto ha abierto un manantial fresco de dolor en mí,
de lloro por el Único que ha sido asesinado por mí. ¡Cuán cruelmente,
cuán frecuentemente he asesinado lo que vino a darme vida! ¡Cuán
frecuentemente he buscado tener vivo mi propio entendimiento,
mi propia comprensión, mi propia voluntad y mis afectos en la religión, y al Justo,
Puro e Inmortal muerto! (Aunque en ese momento no llamara a nada de eso propio,
como otros hombres no lo hacen ahora,
y en su lugar lo tomara como algo de Dios y como lo que estaba destinado a vivir).
Porque yo también fui engañado y pensaba que el primer hijo tenía que heredar la promesa.
No lo conocía como el bastardo, todo lo contrario,
yo pensaba que él era el heredero correcto.
Mi alma está excesivamente cargada por los que en
estos días están bajo el poder del mismo engaño,
por los que han asesinado al Señor de vida como yo lo hice,
en quienes la naturaleza contraria vive bajo una cubierta.
Estos posiblemente no puedan ver (hasta que sea abierto el ojo
verdadero) que la naturaleza que ahora vive en ellos no es la heredera.

La vida que se revolvía al comienzo del problema de esta nación era muy valiosa.
Ella los unió a Dios y a unos con los otros.
Encendió un sentido universal de la cautividad,
de la esclavitud y de la gran opresión de Israel,
y un lloro conjunto subió a Dios por liberación.
Dios oyó el lloro y se levantó para liberarlos,
empezó a quebrar el yugo externo en la nación y el
interno en los espíritus de las personas.

Pero el tentador también se erigió para enredar al Israel de Dios.
Con ese fin sacó a la luz imágenes y semejanzas pintadas
de lo que Israel deseaba y estaba buscando.
Ideó varias formas de adoración con las cuales seducir a unos,
inventó varios tipos de conceptos con los cuales seducir a otros y produjo
varias apariciones frescas de amor y libertad para tentar al pueblo de
Dios a apartarse de en pos del Espíritu que se levantó para liberarlo.
Así surge el enemigo y prevalece.
Él divide en Jacob y dispersa en Israel.
Arrastra a una parte a esta forma, a otra parte hacia aquella otra;
a unos a este concepto, a otros a aquel otro; a unos a esta imagen,
a otros a aquel ídolo espiritual.
Todo lejos de la vida, lejos del poder, lejos del Salvador y detiene la verdadera obra;
la detiene en la nación y la detiene en los espíritus de las personas.

Y ¿dónde está ahora el pueblo que el Señor estaba redimiendo?
¿Dónde está el pueblo de oración, el pueblo anhelante, el pueblo de luto,
el pueblo que habría viajado de costa a costa para tener la voluntad de Dios revelada?
¿No han corrido hacia la tierra?
¿No se los ha tragado el espíritu de la tierra?
El judío interno, la naturaleza renovada está hundida, perdida, apresada.
El espíritu pagano se ha levantado y se ha colocado a sí mismo
en una forma de adoración o en algunos pensamientos altivos,
de los que ese espíritu que no conoce el árbol de la vida ama comer.
Unos están completamente muertos, sin ningún sentido en ellos;
sus vidas han sido completamente consumidas por la muerte.
Otros, tal vez, sigan urgidos en busca del Reino, pero en la naturaleza equivocada,
en la naturaleza que nunca lo obtendrá. Puede que estos encuentren algún disfrute,
pero no el auténtico disfrute de lo verdadero, sino el de la semejanza,
el que el enemigo ha pintado para engañarlos.

Ahora bien, en el verdadero amor,
mi vida les ofrece a todos ustedes esto como la correcta
y única manera de recuperación y redención:
Vengan a lo que puede juzgarlos.
"`Sión con juicio será rescatada y los convertidos de ella con justicia.`"
Si Sión ha de ser redimida, si la Semilla ha de levantarse de nuevo,
entonces ese espíritu que se ha levantado por encima de Ella y
la ha mantenido abajo deberá ser juzgado y puesto bajo juicio.
¿Cómo iba a ser recuperado el viejo Israel de su idolatría y prostitución,
sino al reconocer y llegar a esa luz en los profetas que
los expuso y juzgó? Ustedes también han adorado ídolos.
Ustedes también se han prostituido y se han enardecido con ídolos bajo todo árbol frondoso.
Cada cosa nueva, cada apariencia fresca,
cada ídolo atractivo los ha tentado a apartarse del Dios vivo.
Cuando una forma de adoración les ha parecido seca y estéril, la dejaron.
Cuando algunos conceptos les han parecido vacíos y oscuros, se cansaron de ellos.
Y luego,
el siguiente nuevo ídolo bajo el siguiente árbol frondoso los ha arrastrado al
lecho de fornicación donde han perdido la comunión con el verdadero Dios de vida.
Ustedes han traicionado a la Semilla de vida,
la que Él comenzó a vivificar y a levantar de la muerte.

Vengan ahora a eso que juzga al ídolo, al fabricante de ídolos,
al espíritu de prostitución, a lo que los tienta a apartarse del verdadero esposo.
Permitan que eso sea cortado por el juicio,
entonces la verdadera Semilla de vida brotará y florecerá de nuevo.
No hay otra manera,
no se engañen. Si la vida se va a levantar de nuevo
en ustedes y a tener dominio sobre la muerte,
algo que los juzgue tiene que ser despertado en ustedes,
y ese algo tiene que producir Su juicio hasta la victoria.
Ese espíritu que gobierna ahora en ustedes y mantiene a la vida abajo sabe esto muy bien,
y por eso hace lo posible para que ustedes no reconozcan el juicio.
De hecho, trata de evitar que la luz en otros lo juzgue.
"`No juzguen,`" dice, "`porque todo juicio está encomendado al Hijo.`"
Es cierto, ¿pero no debería juzgar la luz del Hijo?
La luz de la candela, la que el Señor ha iluminado en un corazón,
¿no descubrirá y revelará la oscuridad en otro corazón?
La luz pone de manifiesto y Su manifestación es Su juicio.
Siempre y cuando sea la luz,
adondequiera que brille no puede dejar de descubrir
y juzgar la oscuridad con la que se topa.

Y ahora, oh pobres almas perdidas que sienten su necesidad de juicio,
primero esperen el levantamiento del Juez de Israel en sus
corazones y luego la unión de sus corazones a Él;
ambas cosas tienen que ser hechas por Su luz eterna,
la luz que pone de manifiesto y da Su vida.
En el brillo más tenue de esta luz hay juicio y está el Rey mismo.
Inclínense ante Él, besen Sus pies, conozcan la naturaleza de Él y sujétense a ella.
Adórenlo en Su humillación, recíbanlo en Sus golpes, en Su castigo.
Observen y vuélvanse de lo que en ustedes mismos lo hiere a Él,
y un día lo verán en Su majestad, en el poder de Su amor, en Su eterna curación y abrazo.
Estas son palabras de tierno amor y serán palabras de verdadera vida también,
en dondequiera que la tierra del Padre se abra para beberlas.

[.old-style]
=== Algunas Propuestas / Con Respecto al Único Camino de Salvación

[.numbered]
1+++.+++ Que la única manera de ser salvos del pecado y de la ira eterna es por medio de Cristo,
aquel que murió en Jerusalén. No hay nombre, virtud,
vida o poder bajo el cielo por el cual el hombre perdido pueda ser salvo; sólo por Él.

[.numbered]
2+++.+++ Que la única manera de ser salvos por Él es,
recibiéndolo en el corazón por medio de la fe viva y teniéndolo formado
ahí. Cristo no salva mientras esté de pie tocando a la puerta,
sino cuando se le permite entrar.
Y estando adentro trae con Él esa vida,
poder y misericordia que derriban la pared intermedia, une a Dios y salva.
Los judíos no pudieron ser salvos anteriormente,
por la mera creencia en un Mesías venidero ni por guardar todas las leyes
y ordenanzas de Moisés. Tampoco puede ser salvo alguien hoy,
por la mera creencia en un Cristo ya venido,
ni por guardar todo lo que los apóstoles mandaron o practicaron.
Un hombre es salvo al recibirlo a Él en el corazón, ahí Él obra la salvación.

[.numbered]
3+++.+++ Que la única manera de recibir a Cristo en el corazón y que Él sea formado ahí es,
recibiendo la luz de Su Espíritu, en cuya luz Él es y mora.
El que no deja entrar la luz de Su Espíritu no deja entrar a Cristo.
El que deja entrar la luz de Su Espíritu deja entrar a Cristo.
El Padre y el Hijo son luz, y son conocidos y recibidos únicamente en la luz,
nunca fuera de ella.

[.numbered]
4+++.+++ Que la única manera de recibir la luz del Espíritu en el corazón
(y de ese modo ser unidos al Padre y al Hijo) es,
prestando oído y recibiendo la convicción de pecado que el Espíritu da ahí. La primera
acción del Espíritu hacia el hombre que yace en pecado es convencerlo de pecado.
El que no reciba la convincente luz del Espíritu detendrá la obra desde el mismo
principio y Cristo jamás se formará en él. Ese hombre puede hablar de Cristo,
hacer sus deberes (orar, leer y meditar con frecuencia),
recoger consuelo de las promesas bíblicas, ocuparse de las ordenanzas,
ser excesivamente celoso y apasionado en todo esto, y al final perecer.
Sí, el diablo lo dejará solo (si es que no lo ayuda) en todo esto,
sabiendo que lo tiene más seguro de ese modo.

[.discourse-part]
Objeción: Pero yo puedo ser engañado estando atento a una luz en el interior,
porque mientras creo que le estoy prestando oído a la luz del Espíritu,
puede que le esté prestando oído a la luz de la consciencia natural.

[.discourse-part]
_Respuesta 1:_
Si es solo la luz de la consciencia natural y aún así lo
sigue arrastrando del pecado que lo separa de Dios,
y lo prepara para entender, creer y recibir de Cristo, no es un engaño tan malo.
Pero si resulta que ha sido la luz del Espíritu y usted toda su vida la ha estado
tomando como la luz de la consciencia natural (y por eso ha despreciado,
o al menos, desatendido la luz del Espíritu),
entonces encontrará que este es un engaño mucho peor.

[.discourse-part]
_Respuesta 2:_ Yo le puedo mostrar mediante una escritura expresa,
que es obra del Espíritu convencer de pecado (Juan 16:8), y también, que la ley,
la cual es espiritual, manifiesta lo que es corrupto y carnal (Rom.
7:14). ¿Puede usted demostrarme mediante las Escrituras
que la consciencia natural puede convencer de pecado?

[.discourse-part]
_Respuesta 3:_ Si un hombre le presta atención a la Luz en su corazón,
la verá descubriendo sus maldades espirituales más íntimas y secretas.
Esto no lo puede hacer la luz natural,
porque lo que es natural no puede descubrir lo que es espiritual.

[.discourse-part]
_Respuesta 4:_
El apóstol dice que es la gracia la que se ha manifestado a todos los hombres,
y que no sólo enseña piedad, sino también sobriedad y justicia.
(Tito 2:11-12) La luz de la naturaleza caída es tinieblas y no puede enseñar nada de Dios.
Lo que cualquier hombre aprende hoy del verdadero
conocimiento de Dios lo aprende por gracia,
la gracia que brilla en las tinieblas de la naturaleza
del hombre para leudarla con el verdadero conocimiento.
Aún así, el hombre, al ser tinieblas, no tiene manera de comprenderlo,
ni tampoco puede darle su verdadero nombre.
Por tanto, preste atención,
no sea que (por ignorancia) blasfeme de la santa luz del Espíritu puro,
llamando natural (al mirar con el ojo carnal),
lo que con el ojo espiritual se ve que es espiritual.

El hombre está muerto en delitos y pecados por naturaleza; muy muerto,
y su consciencia está totalmente oscura.
Entonces,
lo que le da al hombre consciencia de su muerte y oscuridad
tiene que ser algo diferente a su propia naturaleza,
es decir,
tiene que ser la luz del Espíritu de Cristo brillando en su oscuro corazón y en su consciencia.
Esta es la semilla de la mujer que no sólo destruye,
sino que también descubre las obras de la serpiente.
Ahora, esta semilla, esta luz es una en todos,
aunque han habido varias dispensaciones de ella.
Una dispensación para los gentiles, en quienes brotaba de forma oculta.
(Rom.
2:14) Otra para los judíos,
en quienes era rigurosamente provocada mediante la ley escrita dada,
quienes por los tipos y sombras y ejercicios justos de acuerdo a la ley,
debían despertarse a la semilla viva.
(Miq.
6:8) Otra para los cristianos,
en quienes germina en la luz y en la vida mediante una dispensación especial de gracia.
No obstante,
en todas estas dispensaciones la gran mayoría de los hombres han
quedado cortos de la gloria de Dios y han perdido la Sustancia.
Ahora el Señor Dios está sacando a la luz la Sustancia misma,
pero lo hace bajo un velo que la oculta del ojo de la sabiduría humana.
A algunos esto les parece natural, a otros legal,
a otros les parece proveniente del poder de Satanás. Por tanto,
siendo que los hombres carecen de la verdadera plomada mediante la cual medirla,
tienen que adivinarla en la sabiduría de sus propias comprensiones.

¡No cierren sus ojos ahora, ustedes sabios,
abran sus corazones y dejen entrar al que llama,
al que puede salvarlos y lo hará! Porque no es un concepto de un Cristo externo
(junto con prácticas de auto negación y auto disciplina) lo que puede salvar,
sino oír a Cristo llamando a la puerta y dejándolo entrar
al corazón. Sólo esto abrirá correctamente las Escrituras.
Sí, esta es la llave que verdaderamente abrirá palabras, cosas y espíritus,
pero el que abre sin esta llave es un ladrón y salteador,
y tendrá que devolver todo lo que se ha robado el día del juicio de Dios.
¡Ay de aquel que cuando sea despojado de lo que se ha robado sea hallado desnudo!

Las Escrituras fueron dadas al pueblo de Dios; parte para los judíos,
parte para los cristianos.
El que es nacido de la vida tiene derecho a ellas,
y puede leerlas y entenderlas en el Espíritu que mora en la vida,
pero el que no ha nacido del Espíritu no es más que
un intruso y roba la luz de otros hombres,
roba el estado y las experiencias de otros hombres para su entendimiento carnal.
Las Escrituras no tenían esto como propósito,
sino ser leídas y vistas en la luz que las escribió. Todas
estas percepciones carnales del hombre (con toda su fe,
esperanza, amor, conocimiento, ejercicios, oraciones, lágrimas,
ayunos y demás imitaciones) se convertirán en pérdida para él,
cuando Dios recupere Sus Escrituras del espíritu oscuro del hombre
(quien las ha rasgado y profanado en exceso con sus propias ideas,
adivinanzas e imaginaciones) y las restaure de nuevo en Su pueblo.

Los profetas y los apóstoles que escribieron las Escrituras,
primero tuvieron la vida en ellos, y el que entiende sus palabras,
primero debe tener también la vida en él. El que entiende las palabras de vida primero
tiene que tener vida en él. La vida es la medida y el discernimiento de las palabras;
las palabras no miden ni disciernen la vida.
Cuando las Escrituras son interpretadas por la vida y por el Espíritu que las escribió,
no hay más disputas ni más contiendas con respecto a ellas.

Este es el verdadero problema:
El espíritu muerto del hombre lee las Escrituras y a partir de esa sabiduría,
la cual está en la muerte,
(sin conocer la mente del Espíritu) le da sus propios significados.
Luego, tras creer y practicar las cosas de las que hablan,
abraza la esperanza de que todo va a estar bien al final.
Con todo, no siente ni experimenta la purificación,
limpieza y circuncisión que corta el cuerpo de pecado y muerte,
ni tampoco conoce la entrada al reino eterno, donde el Rey de justicia es visto,
conocido y adorado en espíritu.

[.old-style]
=== Un Catecismo Corto / Por el Bien de un Corazón Sencillo

[.discourse-part]
Pregunta: ¿Cuál es por naturaleza el estado y la condición de todos los hombres,
puesto que son engendrados de la semilla del malhechor
y salen de los lomos del primer Adán?

[.discourse-part]
Respuesta: Es un estado de pecado y de tinieblas, es un estado de muerte y miseria,
es un estado de enemistad contra Dios, es un estado de maldición de Dios,
es un estado de exposición a Su ira y a Sus más justos juicios;
ahora y después de la muerte.

[.discourse-part]
Pregunta: ¿Qué llevó a Adán a ese estado, y qué mantiene a los hijos de Adán en él?

[.discourse-part]
Respuesta: Comer del árbol del conocimiento,
del que el hombre continua comiendo hasta este día
aunque esté excluido del Árbol de la Vida.

[.discourse-part]
Pregunta: ¿Cómo se alimentó Adán del árbol del conocimiento en un primer momento,
y cómo continúan haciéndolo los hombres hoy?

[.discourse-part]
Respuesta: A partir de un lujurioso apetito y deseo tras la sabiduría prohibida,
sembrados en su corazón por el envidioso enemigo de sus almas.
Este continúa enrollado en el árbol del conocimiento tentando a los hombres y
a las mujeres a comer de él y persuadiéndolos de que el fruto es bueno para comer.
Y sí, el fruto es muy deseable para sus ojos y promete hacerlos eternamente sabios,
pero no lo logra.

[.discourse-part]
Pregunta: ¿Qué es el fruto prohibido?

[.discourse-part]
Respuesta: Es conocimiento sin Vida.
Es conocimiento en la parte terrenal, conocimiento adquirido de abajo, no dado de arriba.
Este conocimiento le promete a los hombres hacerlos como Dios y a darles
la capacidad de discernir y distinguir entre lo bueno y lo malo,
lo cual es propiedad particular de Dios.
Comer de este árbol fue la ruina de Adán, la ruina de los gentiles,
la ruina de los judíos y la ruina de los cristianos.
Todos se han alimentado del árbol del conocimiento y se
han separado de la Vida en sus varias dispensaciones.

[.discourse-part]
Pregunta: ¿Cómo es que este fruto se constituye en ruina para el hombre?

[.discourse-part]
Respuesta: Porque la sabiduría y el conocimiento que reúne proveniente de ese fruto,
y del que además se alimenta, lo pervierten.
Esto lo hace sabio en la parte equivocada y lo exalta contra la Vida.
Desgana el apetito verdadero e incrementa el apetito equivocado,
dejándole apenas un deseo por Dios.
De este modo,
lo que a la postre fue ordenado para vida se convirtió en muerte para el hombre.

Fue así como los gentiles se negaron a retener a Dios en su conocimiento
y provocaron que Él los echara y los entregara a la vanidad de sus imaginaciones.
Los judíos a quienes Dios había escogido,
fueron igualmente entregados a la lujuria de sus corazones y rechazados como pueblo.
Los gentiles a quienes Dios había injertado en el verdadero olivo en lugar de los judíos,
también y de la misma manera cayeron de su dispensación. Por lo tanto,
cada uno de ellos cayó al apilar sabiduría de la letra y
al perder la Vida en cada una de estas dispensaciones.

[.discourse-part]
Pregunta: ¿De qué comida se debería alimentar el hombre?

[.discourse-part]
Respuesta: Del Árbol de la Vida; de la Palabra que vive y permanece para siempre,
la cual está en medio del jardín de Dios.
Esta misma Palabra fue hecha carne por causa de la debilidad del hombre,
de cuya carne se alimenta el alma viva y de cuya sangre bebe el espíritu vivo;
así es alimentado para vida eterna.

[.discourse-part]
Pregunta: Pero, ¿tiene Adán esta comida para alimentarse?
¿Tenía que ser esta la comida de los gentiles,
judíos y cristianos en sus varias dispensaciones?

[.discourse-part]
Respuesta: Dios sopló en el hombre aliento de vida y el hombre fue un alma viviente.
Nada menos que la vida misma podía satisfacer su alma en un principio,
y nada menos puede hacerlo hoy.
Cada palabra fresca que sale de la boca de Dios es alimento y vida para el hombre.
Dios le habla al hombre con frecuencia mostrándole lo que es bueno,
pero él es incapaz de saborear o alimentarse de eso porque
por el error y la alienación de su mente desea otra cosa.
La Palabra no está lejos de ningún hombre,
pero los oídos de los hombres generalmente se detienen contra
ella por la sutileza de la serpiente que los engañó al principio.

[.discourse-part]
Pregunta:
Pero ¿no buscaron los judíos la vida eterna al leer y estudiar las Escrituras
bajo su dispensación? ¿No buscan los cristianos hoy la vida,
y no buscan comer de ella?

[.discourse-part]
Respuesta: Sí, ellos la buscaron y la buscan a su manera,
pero la rechazan a la manera de Dios.
Del mismo modo Adán, después de haber comido del árbol del conocimiento,
también habría comido del Árbol de la Vida,
pero fue echado entonces como son echados los cristianos hoy.
Si ellos alguna vez se van a alimentar del Árbol de la Vida,
van a tener que perder su conocimiento,
van a tener que ser cegados y van a tener que ser
conducidos a di cho Árbol por un camino que no conocen.

[.discourse-part]
Pregunta: Esto es demasiado misterioso para mí;
deme el conocimiento simple y literal de las Escrituras.

[.discourse-part]
Respuesta: ¿No es la sustancia espiritual un misterio^
footnote:[Penington a menudo usa la palabra __misterio__ para referirse a
las cosas que no pueden ser conocidas por medio de las facultades naturales,
y que tienen que ser reveladas por el Espíritu de Dios.]
siempre?
¿No está la vida en la sustancia?
La letra de cualquier dispensación mata; el Espíritu es el único que da vida.
Un hombre puede leer la letra de las Escrituras diligentemente,
acumular un gran conocimiento a partir de ella y alimentarse allí con avidez,
pero el único que se alimenta de esta manera es el espíritu muerto.
Entre tanto, el alma subyace flaca, estéril, hambrienta e insatisfecha,
y lo sentirá cuando despierte.

[.discourse-part]
Pregunta: Pero,
¿no puede acaso el espíritu muerto también imaginar
misterios en todo y alimentarse de sus imaginaciones?

[.discourse-part]
Respuesta: Sí puede, y el error aquí es mayor que el anterior.
Pero, hay seguridad al esperar en humildad y temor a tener el ojo correcto abierto
y el verdadero misterio revelado en el corazón humilde y honesto.
Al recibir la demostración del Espíritu fuera de la sabiduría de la carne, no hay error,
sino el verdadero conocimiento que mana de la vida y trae vida.

[.discourse-part]
Pregunta: ¿Cómo llego a este misterio?

[.discourse-part]
Respuesta:
Sólo hay una llave que puede abrirlo y sólo hay una
mano que puede darle vuelta a la llave.
Y sólo hay una vasija, un corazón, un espíritu que puede recibir el conocimiento.

[.discourse-part]
Pregunta: ¿Cómo llego a ese corazón?

[.discourse-part]
Respuesta: De la misma manera que usted fue tocado por el enemigo, lo dejó entrar,
y no lo rechazó con el poder de esa vida que era más fuerte que él. Igual ahora,
cuando usted sea tocado y atraído por su Amigo,
y de algún modo encuentre el comienzo de Su virtud entrando en usted,
ríndase en y por esa vida y virtud,
y espere más. Y conforme usted sienta que lo llama y crece en usted,
siga el sendero y ella lo sacará de la tierra de muerte y oscuridad por un camino maravilloso,
lo sacará de la tierra en la que el alma ha estado cautiva
y lo introducirá en la tierra de vida y perfecta libertad.

[.discourse-part]
Pregunta: Pero, ¿puedo hacer algo yo en pro de mi propia salvación?

[.discourse-part]
Respuesta: Por usted mismo no,
pero en el poder de Aquel que obra en usted tanto el querer como el hacer,
puede hacer un poquito al principio.
A medida que ese poder crezca en usted, será capaz de querer y hacer más,
al punto de que nada llegue a ser demasiado difícil para usted.
Cuando usted lo haya conquistado todo, sufrido todo y realizado todo,
verá y será capaz de decir con entendimiento que no ha hecho nada, que la eterna virtud,
vida y poder lo han forjado todo en usted.

[.discourse-part]
Pregunta: Percibo por lo que se ha dicho que hay un Salvador, uno que tiene virtud,
vida y poder en Él para salvar, ¿cómo puedo encontrarme con Él?

[.discourse-part]
Respuesta: Sí,
Aquel que hizo al hombre lo compadece y no está dispuesto
a que el hombre perezca en el hoyo en el que cayó,
sino que ha señalado a Uno para sacarlo y salvarlo.

[.discourse-part]
Pregunta: ¿Quién es este Salvador?

[.discourse-part]
Respuesta: Él es el Árbol de la Vida del que he hablado todo este tiempo,
cuyas hojas tienen virtud en ellas para sanar a las naciones.
Él es la planta de justicia, la planta en la mano derecha de Dios.
¿Ha experimentado alguna vez en usted dicha planta,
plantada ahí por la mano derecha de Dios?
Él es la resurrección y la vida, quien levanta al alma muerta y hace que viva.
Él es el maná espiritual del que las almas vivas se alimentan.
Sí, su carne es verdadera comida y su sangre verdadera bebida,
y aquel que es levantado en la vida se alimenta y encuentra virtud viva en ellas,
las cuales satisfacen y alimentan su alma inmortal.

[.discourse-part]
Pregunta: Pero, ¿tiene nombre este Salvador?
¿Cuál es Su nombre?

[.discourse-part]
Respuesta:
Sería mejor para usted aprender Su nombre al experimentar
Su virtud y Su poder en su corazón. No obstante,
si puede con esto, este es su nombre: Luz, Luz del Mundo.
Él es la luz que alumbra a los gentiles,
para poder convertirlos y hacerlos parte del Israel de Dios
y para que Dios llegue a ser la gloria de ellos.
De acuerdo a Su oficio, Él ha alumbrado a todo hombre que viene al mundo.
Los hombres, sin embargo, no han conocido la luz que viene de Él,
ni han conocido a Aquel de quien viene la luz.
Y así, a pesar de que la luz está muy cerca de ellos,
permanecen ajenos a ella y no salvos por ella.

[.discourse-part]
Pregunta: ¿Por qué lo llama usted la luz?
¿No hay otros nombres igual de apropiados por los que Él pueda ser conocido también?

[.discourse-part]
Respuesta: Sí,
pero sólo recibiéndolo como la luz es que llegamos a conocer Sus otros nombres.
Él es la vida, la justicia, el poder, la sabiduría, la paz, etc.,
pero Él es todo esto en la luz y en la luz lo aprendemos y lo recibimos todo.
Ninguna de estas cosas puede ser conocida en el espíritu excepto en y por la luz.

[.discourse-part]
Pregunta: ¿Cómo son conocidos los otros nombres de Cristo en y por la luz?

[.discourse-part]
Respuesta:
Al dejar entrar la luz (la cual convence y batalla
contra el pecado) la vida se revuelve y es sentida.
La vida lleva a la experiencia de la Palabra que estaba en el principio,
y en la Palabra son experimentadas la justicia, la paz, la sabiduría, el poder,
y el amor.
Él es hecho todas esas cosas para los que son conducidos y se mantienen en la luz.
Cuando los poderes de las tinieblas aparecen con
temor poderoso y no hay fuerza para resistirlos,
la luz levanta un estandarte contra ellos,
calma toda tempestad y cura todas las heridas y enfermedades del alma,
ungiéndolas con el aceite eterno.
Así, pues,
en ese momento sí puedo decir con todo el sentido y llamarlo con claro entendimiento,
mi Salvador, el Capitán de mi salvación, mi Cristo o Ungido, mi Esposo, mi Rey,
mi Señor y mi Dios.

[.discourse-part]
Pregunta: ¿En dónde brilla esta luz?

[.discourse-part]
Respuesta: Al principio en las tinieblas, pero cuando la luz las ha derrotado,
expulsado y esparcido, brilla fuera de ellas.

[.discourse-part]
Pregunta: ¿Qué son esas tinieblas en donde brilla la luz?

[.discourse-part]
Respuesta: Las tinieblas son el hombre, el corazón del hombre, la consciencia del hombre,
el espíritu del hombre.
Este es el mundo del que Cristo, el Sol de justicia,
es la luz en aquellas partes en la que Él hace que los rayos de Su luz brillen.
No obstante,
las tinieblas no pueden comprender el más mínimo brillo de esta luz en ninguna parte.

[.discourse-part]
Pregunta: ¿Cómo pueden ser convertidas entonces las tinieblas por la luz?

[.discourse-part]
Respuesta: Las tinieblas no son convertidas;
todo hombre en ese estado es reprobado y la ira permanece sobre él. Es por eso
que las tinieblas deben ser rechazadas junto con el hombre en las tinieblas,
pero el alma que es tocada por la luz y hecha sensible a ella,
la sigue en la vida y en el poder que es engendrado, sacada del horrible pozo, y salvada.

[.discourse-part]
Pregunta: ¿Cómo puedo encontrar la luz en medio de las tinieblas de mi corazón,
dado que son tan grandes y la Semilla tan pequeña?

[.discourse-part]
Respuesta: Mediante su revelación y batalla contra las tinieblas.
Hay algo que revela tanto la abierta como la secreta iniquidad del corazón corrupto,
y encuentra la luz bajo todas sus cubiertas de celo, santidad,
apariencia de humildad y justicia propia.
Eso que guerrea contra las tinieblas para sacar a las personas
de todo fundamento falso y llevarlas al fundamento vivo y verdadero,
es la luz.
Así es como usted puede encontrarla,
la encuentra de un momento a otro obrando en su corazón.

[.discourse-part]
Pregunta: Habiendo encontrado la luz,
¿cómo puedo llegar a sentir la virtud y el poder salvador de ella?

[.discourse-part]
Respuesta: Creyendo en ella,
pues la virtud y el poder brotan en el corazón que cree en ella.

[.discourse-part]
Pregunta: Pero, ¿cómo puedo creer en ella?
¿Acaso no estoy muerto?

[.discourse-part]
Respuesta: Hay una creación, un poder vivificador en la luz,
el cual engendra un poco de vida, y esta puede responder a la voz del poder vivo.

[.discourse-part]
Pregunta: Si yo pudiera encontrar tal cosa engendrada en mí,
entonces sería capaz de creer, pero en definitiva, mi corazón muerto no puede.

[.discourse-part]
Respuesta:
¿Nunca ha experimentado usted un suspiro de anhelo verdadero y honesto hacia Dios?
¿Nunca ha encontrado que el pecado es una carga real (no imaginaria)?
Esto provenía de la vida.
Había algo engendrado por Dios en usted que sentía esto.
Y ciertamente no era la carne ni la sangre en usted, sino algo de arriba.
Si usted hubiera conocido el origen de esa vida,
se habría alimentado y crecido en la virtud y poder de la fuente de donde esa vida provenía.

[.discourse-part]
Pregunta: Si esto fuera cierto, entonces todos los hombres tienen poder para creer.

[.discourse-part]
Respuesta: En la luz que alumbra en todos, y visita a todos, está el poder para creer.
Este poder lucha con la criatura y busca obrar él mismo en la criatura,
y en donde se ha producido el más pequeño suspiro tras la vida,
también se ha gustado el poder.
Pero el gran engañador de las almas levanta la mente del hombre
con imaginaciones para que busque una mayor apariencia de poder,
y como resultado,
el hombre con frecuencia menosprecia y pasa por alto el día de las pequeñeces,
y no tiene cuidado de recibir los comienzos del poder de Dios.
Pero, al esperar en lo escaso y pequeño en el corazón entra el poder,
crece la Semilla y el reino es sentido y revelado
cada día más. Esta es la verdadera puerta;
cuidado con tratar de subir de otra manera.

[.discourse-part]
Pregunta: ¿Qué es creer en la luz?

[.discourse-part]
Respuesta: Es recibir el testimonio de la luz con respecto al bien y al mal, y ya sea,
volverse hacia el bien o alejarse del mal,
en la voluntad y poder que la luz engendra en el corazón.

[.discourse-part]
Pregunta: ¿Cómo me salvará esto?

[.discourse-part]
Respuesta: Por este medio:
Eso que lo destruye a usted y lo separa del Dios vivo será arrancado diariamente,
y el corazón será cambiado cada día a la imagen del que es la luz.
Usted será llevado a la unidad y a la comunión con
la luz poseyéndola y siendo poseído por ella.
¡Esta es su salvación!

[.discourse-part]
Pregunta: Nosotros pensábamos que la salvación nos sería concedida en el futuro,
después de la muerte del cuerpo, pero si eso es cierto,
entonces la salvación se experimenta aquí.

[.discourse-part]
Respuesta: Sí, en todos los que son salvos.
No hay una obra de salvación en el futuro, es forjada aquí con temor y temblor.
El creyente que está verdaderamente unido a la vida
es diariamente cambiado de gloria en gloria,
como por el Espíritu del Señor.

[.discourse-part]
Pregunta: Demuestre más específicamente cómo la fe o creer en la luz obra la salvación.

[.discourse-part]
Respuesta: 1. En primer lugar causa temor y temblor para sujetar al pecador.
El Señor Dios Todopoderoso, mediante el aumento de Su luz en el corazón,
hace que los poderes de las tinieblas se sacudan,
que la tierra tiemble y que las colinas y las montañas se derritan;
luego la planta del Señor brota del suelo seco y estéril,
y por el rocío y las lluvias que caen de arriba, prospera,
crece y se extiende hasta llenar la tierra de Dios.

2+++.+++ En este temor y temblor la obra del verdadero
arrepentimiento y conversión se inicia y continua.
Hay un vuelco del alma de las tinieblas a la luz,
del poder de las tinieblas al poder de la luz,
del espíritu de engaño al espíritu de verdad,
y de toda falsa aparición e imaginación acerca de la santidad a
lo que la luz eterna manifiesta ser realmente así. Este es un tiempo
de profunda lamentación porque la separación obra en el interior,
la fuerza del enemigo no ha sido quebrantada ni sometida en el corazón completamente,
y el corazón a veces continúa anhelando sus antiguos amores.

3+++.+++ En la convicción de la luz, y en el temor colocado en el corazón, brota una esperanza,
una esperanza viva, de la raíz viva,
la cual se ha manifestado a sí misma y ha comenzado a obrar.
Porque en el alma que se está volviendo realmente a la luz,
el brazo eterno y el poder vivo son sentidos.
Esto se convierte en el ancla que sostiene al alma en todos los problemas,
tormentas y tempestades con las que se encuentra después; que son muchas, sí,
en verdad muchas.

4+++.+++ La fe obra justicia y enseña verdadera sabiduría a través de la esperanza.
Entonces el beneficio de toda la dificultad,
angustia y miseria anterior empieza a hacerse sentir y la obra continua dulcemente.
Toda injusticia está en las tinieblas, en la incredulidad y en la falsa esperanza.
La fe disipa en la luz la injusticia y obra la justicia de Dios en Cristo.
Ella lo hace a uno verdaderamente sabio, sabio en el poder vivo,
en una sabiduría que el hombre no puede aprender en ningún otro lugar.

5+++.+++ En la justicia y en la verdadera sabiduría que es recibida en la luz, brotan el amor,
la unidad y la comunión con Dios el Padre de luces
y con todos los que son hijos de la luz.
Al ser engendrados por Cristo,
pronto es sentida la unidad con el Padre y con los que han nacido
del mismo vientre y son partícipes de la misma naturaleza.
Ahí, en ese amor,
hay una voluntad y un poder que sienten deponer la
vida de uno por la menor verdad de Cristo,
o por los hermanos.

6+++.+++ Creer en la luz obra paciencia, mansedumbre, delicadeza, ternura y longanimidad.
Esto sobrellevará cualquier cosa para Dios y cualquier
cosa por el bien del alma de los hombres.
Esperará silenciosa y quietamente que la obra de Dios continúe en su propia alma,
y esperará la manifestación del amor y de la misericordia de Dios por
los demás. Soportará la afrenta de los pecadores buscando el bien de ellos,
aún cuando estén tramando, ideando e incubando maldades.

7+++.+++ Esto trae paz, gozo y gloria.
La fe en la luz derriba la pared de tinieblas, la pared de separación,
la que separa de la paz, la que causa angustia y problemas en el alma,
y así introduce al alma en la paz.
Cristo es el Médico hábil, Él sana de la enfermedad al quitar la causa.
Los médicos que no son hábiles curan engañosamente, proclaman paz, paz,
cuando no hay paz, cuando lo que rompe la paz sigue en pie.
Pero Cristo no lo hace así,
Él mata la enemistad en el corazón mediante la sangre de Su cruz; así hace la paz.
Esta es paz verdadera y cierta.

Ahora bien, el alma es introducida en la paz cuando los terrones de tierra son removidos,
el enemigo hollado, el pecado eliminado y la vida y el poder están presentes.
¡Aquí está el gozo, el gozo inefable!
Este es un gozo que el mundo no puede ver ni tocar,
ni el poder de las tinieblas acercarse a interrumpir.
Aquí ya no existe más el clamor: "`¡Oh,
miserable hombre!,`" o "`¡Quién me librará!`" Sólo regocijo
en el que ha dado la victoria y ha hecho al alma victoriosa;
de hecho, más que victoriosa.
Esperen a sentir esto, ustedes,
los que están ahora gimiendo y siendo oprimidos por
los inmisericordes poderes de las tinieblas.

Este gozo está lleno de gloria,
de la gloria que se incrementa cada día al ver y al sentir
diariamente la virtud y el poder vivo en Cristo la luz.
Aquí el alma es continuamente transformada y cambiada
al salir de lo corruptible a lo incorruptible,
de la incircuncisión, vergüenza y afrenta para entrar a la circuncisión, vida y gloria.

[.discourse-part]
Pregunta: ¿Hace todo esto la luz?

[.discourse-part]
Respuesta: Sí, en aquellos que se vuelven a ella,
se rinden ante ella y permanecen en ella.
A estos ella los limpia de las tinieblas y diariamente los transforma a la imagen,
pureza y perfección de la luz.
Esto sólo lo puede hacer la luz.

[.discourse-part]
Pregunta: ¿Qué hace a los hombres en general tan hostiles a la luz?

[.discourse-part]
Respuesta: Su unión con las tinieblas.
La luz es enemiga de toda oscuridad, pues la descubre y la perturba.

[.discourse-part]
Pregunta: Pero los hombres sabios, los que conocen,
los que son considerados con mayor luz,
también son enemigos de esta luz y hablan despectivamente de ella.

[.discourse-part]
Respuesta:
¿No ha sido siempre así? ¿Creyó en Él alguno de los gobernantes
o sabios escribas y maestros de la ley antes?
¿Es de extrañarse si los tales no creen en Él hoy?

[.discourse-part]
Pregunta:
¿Cuál es la razón por la que los sabios no pueden
ni han podido hasta ahora creer en la luz?

[.discourse-part]
Respuesta: Hay dos grandes razones.

1+++.+++ Porque no pueden comprenderla.
Ellos pueden entender el tipo de conocimiento que
es adquirido a partir de libros de la naturaleza,
a partir de los libros de la ley y los profetas,
o a partir de los libros de los evangelistas y apóstoles,
pero no pueden comprender la luz de la que todo esto testifica.
Hay un tipo de conocimiento que ellos pueden reunir, sí, pero no pueden recibir la luz,
pues ella no es comprendida por el hombre.
Más bien, atrae a sí misma a los hombre y ahí nos muestra todo.

2+++.+++ Porque la verdadera luz es un completo enemigo para ellos.
Ella no le hará un guiño a la más pequeña de sus maldades,
ni les hablará de paz mientras permanezcan en tinieblas.
Puede que su propio conocimiento adquirido les hable de paz,
pero la luz no lo hará. En este sentido los judíos podían hablar de paz
entre ellos mismos con las ordenanzas y sacrificios del templo,
aunque caminaban en la terquedad e incircuncisión de sus corazones,
resistiéndose siempre a los frenos y movimientos del Espíritu Santo ahí. Así,
los cristianos pueden hablar hoy de paz entre ellos mismos
por una creencia en la muerte de Cristo en Jerusalén,
aunque no Lo conozcan en ellos,
ni reciban Su poder en los frenos y reprimendas por el pecado.

[.discourse-part]
Pregunta: Pero hay muchos profesantes, profesantes estrictos,
que sin ninguna duda han gustado alguna vez de la virtud viva.
¿Qué los hace ahora tales enemigos de la luz?

[.discourse-part]
Respuesta: 1. Que hayan caído de lo que alguna vez tuvieron,
porque si estuvieran en esa Semilla viva que una vez les
dio un verdadero sabor de la vida a través de las Escrituras,
no podrían dejar de conocer y reconocer la luz.
Pues la luz fue lo que les dio el sabor,
y lo habrían preservado de haber sabido cómo volverse y permanecer en ella.

2+++.+++ La luz es un testigo contra todo el conocimiento de ellos,
sus prácticas religiosas y las imitaciones que han reunido de las Escrituras.
La luz testifica contra lo que ellos creen y practican fuera de la luz en su injusticia,
es decir, en esa parte del hombre que no puede conocer o ser el adorador.
¿Puede culparlos usted por volverse contra ella,
cuando la luz es tan grande enemigo de ellos?
¿Cómo podrían, habiendo matado y asesinado al Justo en ellos mismos,
reconocer y darle Su debido honor en otros?

[.discourse-part]
Pregunta: Pero estos estrictos profesantes,
que proclaman grandes cosas en honor a Cristo, ¿Lo han asesinado en ellos mismos?

[.discourse-part]
Respuesta: Sí, efectivamente; tan ciertamente como los escribas,
fariseos y el pueblo judío lo llevaron a la muerte en Jerusalén. Porque
lo que le hacen ellos a la menor aparición de Su luz en sus corazones,
se lo hacen a Él. Es más, nuestro Señor Jesucristo, este mismo día,
está tan verdaderamente crucificado en el Egipto y en la Sodoma espiritual en ellos,
como lo estaba fuera de las puertas de Jerusalén. Su justa sangre clama tan fuerte
contra los profesantes de esta era como lo hizo contra los judíos siempre,
pero los hombres hoy se han endurecido contra Él por el conocimiento
vanidoso que han reunido de las Escrituras mediante sus imaginaciones.
Sus ojos no pueden ver más hoy, que lo que pudieron ver los ojos de los judíos entonces.

[.discourse-part]
Pregunta: Es seguro que si ellos conocieran la luz como el único camino vivo,
no serían enemigos de ella.

[.discourse-part]
Respuesta: Sí, yo creo con respecto a ellos (como se dijo con respecto a los judíos),
que si ellos la conocieran, no habrían crucificado al Señor de gloria.
Porque yo doy testimonio de que muchos de ellos tienen un gran celo,
aunque no de acuerdo al conocimiento.
Sin embargo, ¡cuán triste es su estado en el presente,
porque el dios de este mundo ha cegado en ellos el único ojo que puede ver la verdad!

[.discourse-part]
Pregunta: Pero,
¿acaso no es posible para los hombres obtener la vida eterna por la lectura de las Escrituras,
sin conocer o reconocer este principio de la luz?

[.discourse-part]
Respuesta:
El verdadero objetivo de la lectura de las Escrituras
es que el hombre se vuelva a la luz.
Las Escrituras tienen mensajes con respecto a Dios, con respecto a Cristo,
con respecto al Espíritu,
la meta de los cuales es que los hombres se vuelvan al único poder
y a la única vida que pueden obrar para ellos y en ellos.
"`La Palabra está cerca de ti,
en tu corazón y en tu boca,`" les dice Moisés a los judíos,
y les dice Pablo a los cristianos.
¿Con qué fin les dicen ellos que está ahí? Para que ahí esperen oír su voz y obedecerla.

Ahora ponga atención,
si un hombre pudiera practicar y realizar todas las cosas
mencionadas en las Escrituras sin haberse vuelto a la luz,
aún no está en el camino de salvación. Pues el camino de salvación no es un camino particular,
o un curso de ordenanzas y deberes prescritos en las Escrituras, sino un camino nuevo,
un camino vivo,
un camino que el más sabio profesante mediante su propia sabiduría nunca podría conocer.
("`Yo los llevaré por un camino que ustedes no han conocido.`") Así, pues,
mientras los hombres no conozcan ni se vuelvan a
la luz y al poder del que las Escrituras testifican,
todas sus lecturas, oraciones y práctica de ordenanzas y deberes son en vano.
Al final esto probará ser una cubierta falsa, no la cubierta del Espíritu.
