== Capítulo VII. Las Sagradas Escrituras / Si Ellas Deben Ser la Verdadera Regla de Fe y de Vida

El más grande tipo de conocimiento se da al conocer
las cosas a través de nuestra unión con ellas,
es decir, al experimentar una medida de la vida de ellas hecha manifiesta en el interior.
Confesamos que esta es nuestra manera de entender
las cosas y también la de entender las Escrituras;
las Escrituras que hablan de cosas espirituales.
En realidad, hemos encontrado que este es por mucho el tipo de conocimiento más seguro,
a saber, entender las Escrituras por la experiencia de lo que ellas hablan,
no mediante la adivinación de las cosas,
ni por la consideración o exploración de las palabras con la mente carnal.

Ahora bien,
con respecto a la idea de que las Sagradas Escrituras
puedan ser la regla perfecta de fe y vida,
consideremos que el nuevo pacto es el pacto del evangelio.
Dicho pacto es un pacto vivo, un pacto espiritual, un pacto interior, por consiguiente,
la ley o la regla no puede estar escrita en el exterior.
Lea el tono del nuevo pacto en Hebreos 8:10, "`Pondré mis leyes en la mente de ellos,
y sobre su corazón las escribiré.`" Note que hay una diferencia
manifiesta entre el nuevo pacto y el antiguo,
es decir, que las leyes de uno estaban escritas en el exterior, en tablas de piedra,
y que las leyes del otro iban a ser escritas en el corazón. Es decir,
el corazón es el libro en el que se prometió que las leyes del nuevo pacto serían escritas,
por tanto, ahí deben ser leídas.
Así, el que vaya a leer y a obedecer las leyes del pacto de vida,
deberá buscarlas en el libro en el que Dios ha prometido escribirlas.
Porque aunque un hombre pueda leer algunas descripciones externas de la cosa,
sólo en el corazón podrá leer la cosa misma.

"`Cristo es el camino, la verdad y la vida.`"
¿Cuál es la regla del cristiano?
¿No es el _camino_ de Dios su regla?
¿No es la _verdad_ de Dios su regla?
¿No debe ser enseñada y oída la verdad en Jesús y
sólo en Jesús? (Ef. 4:21) ¿No es Él el rey,
el sacerdote, el profeta, el sacrificio, el camino de Dios, la vida misma,
la senda viva de salida de la muerte; sí,
el '`todo en todos`' para los creyentes cuyos ojos están abiertos para contemplarlo?
Las Escrituras testifican de Cristo, pero no son Cristo.
También testifican de la verdad (y ciertamente son un testimonio verdadero),
pero la verdad misma está en Jesús,
que mediante Su Espíritu vivo la escribe en el corazón que Él ha vivificado.

Por lo tanto, la vida del cristiano es en el Espíritu: "`Si vivimos por el Espíritu,
andemos también por el Espíritu`" (Gal.
5:25). Toda la vida y el recorrido de un cristiano está en el volumen de ese libro,
según el Señor va abriendo las páginas de este en él. La regla del cristiano,
su regla de conocimiento, de profecía, de obediencia, es "`el don de Dios,
la medida de fe`" que Dios le ha dado.
(Heb.
12; Rom.
1:5; 12:6) Si se mantiene en ella,
si camina de acuerdo a la proporción de ella no se equivoca,
pero si camina fuera de la fe, entonces todo lo que conoce,
todo lo que cree y todo lo que hace es un error.

La nueva criatura (la que Dios ha creado nuevamente en el corazón,
la que es enseñada por Dios y en la que la vida respira y nada más que
la vida respira) es la regla por la que tiene que caminar el hombre.
El apóstol lo dice expresamente así:
"`Porque en Cristo Jesús ni la circuncisión vale nada, ni la incircuncisión,
sino una nueva creación. Y a todos los que anden conforme a esta regla,
paz y misericordia sea a ellos, y al Israel de Dios`" (Gal.
6:15-16).

Lo que es nacido de Dios es un hijo, y ese hijo,
así como es engendrado por el soplo del Espíritu,
es también preservado y guiado por el mismo soplo.
Todos los que son guiados de esta manera son hijos, nadie más;
pues leer las Escrituras y reunir reglas a partir
de ellas no es lo que hace que uno sea hijo,
sino recibir al Espíritu y ser guiado por Él. "`Porque
todos los que son guiados por el Espíritu de Dios,
éstos son hijos de Dios`" (Rom.
8:14-15). Puesto que en el evangelio toda la adoración es en el Espíritu,
es necesario recibir dicho Espíritu en primer lugar, y luego, en ese mismo Espíritu,
el alma deberá aprender a conocer y a esperar Sus
soplos y movimientos y a seguir al Señor en ellos.
El Espíritu no cesará de soplar sobre lo que Él ha engendrado,
así que dicho soplo es la guía del hombre, la regla del hombre, el camino del hombre.

Todo esto está claramente manifiesto en las Escrituras mismas,
porque ellas expresamente llaman a Cristo el camino, la verdad, la regla, la fe,
la gracia, etc.,
y demuestran además que el corazón es la tabla sobre
la que Dios ha escogido escribir Su ley.
Porque, ¿dónde se llaman las Escrituras a sí mimas la regla perfecta de fe y obediencia?
"`...ellas son las que dan testimonio de Mí;
y no queréis venir a Mí para que tengáis vida`" (Juan
5:39-40). La vida no puede recibirse de las Escrituras,
sólo de Cristo, fuente y origen de ella.
De la misma manera, las Escrituras no pueden dar la verdadera regla,
sólo pueden apuntar hacia la fuente de vida de donde se recibe la regla de vida.
Las Escrituras no pueden injertar el alma en Cristo, ni darle al injertado una regla viva.
No obstante,
el que ha oído el testimonio de las Escrituras con respecto a Cristo y ha llegado a Él,
puede permanecer y esperar en Él para que la ley del Espíritu
de vida sea escrita en su corazón. _Esta_ será su regla,
la que lo sacará de la ley del pecado y muerte y lo introducirá en la tierra de la vida.

Consideren ahora mansa y humildemente si las Escrituras
son la regla de los hijos del nuevo pacto.
Porque si las Escrituras no fueron planeadas por Dios para
que fueran la regla y ustedes las toman como tal,
pueden fácilmente equivocar el camino a la vida eterna, y además,
errar su entendimiento y uso de las Escrituras,
al usarlas como algo para lo que nunca fueron planeadas
y así perder el verdadero uso y propósito de ellas.

=== Tres Argumentos

Las Escrituras no tenían como objetivo,
ni fueron dadas por Dios para que fueran la regla de los hijos del nuevo pacto.
Consideren los siguientes tres argumentos:

[.small-break]
'''

1+++.+++ Las Escrituras son una regla o ley externa,
pero expresamente dicen que la ley del nuevo pacto sería una ley interna.
Está escrito en los profetas que todos los hijos del nuevo pacto
(o Nueva Jerusalén) serían enseñados por el Señor. (Isa.
54:13) Que el Señor los enseñaría internamente mediante
Su Espíritu y escribiría Su ley en sus corazones.
(Jer.
31:33-34) En este sentido,
el Señor introdujo a Su pueblo en pacto con Él y les enseñó en los días de los apóstoles:
"`Pero la unción que vosotros recibisteis de él permanece en vosotros,
y no tenéis necesidad de que nadie os enseñe;
así como la unción misma os enseña todas las cosas, y es verdadera, y no es mentira,
según ella os ha enseñado, permaneced en él`" (1 Juan 2:27). El pacto es interno,
el maestro es interno, el escrito es interno, la ley es interna,
ahí es donde debe ser leída, aprendida y conocida,
donde el Espíritu la enseña y la escribe.

[.small-break]
'''

2+++.+++ Las Escrituras (o los escritos de Moisés y los
profetas) no son la ley de los hijos del nuevo pacto.
La ley de Moisés era la regla de un estado externo, era la regla del Israel externo,
no la regla del Israel interno.

Ahora bien,
en Deuteronomio 29 Moisés hace un pacto con Israel por mandato expreso de Dios,
además del pacto (ver. 1) que anteriormente había hecho con ellos en el Sinaí. Moisés
dice que el mandamiento de este pacto no debe ser buscado donde fue escrito el otro,
sino en otro lugar, en un lugar cerca de ellos, es decir, en la boca y en sus corazones.
Ahí ellos debían leer, oír y recibir el mandamiento de este pacto.
"`Porque este mandamiento que yo te ordeno hoy no es demasiado difícil para ti,
ni está lejos`" (Deut.
30:11); "`no está en el cielo`" (Deut.
30:12); "`ni está al otro lado del mar`" (Deut.
30:13); "`porque muy cerca de ti está la palabra, en tu boca y en tu corazón,
para que la cumplas`" (Deut.
30:14); este era el camino de vida.
"`Vean (dice Moisés) yo he puesto delante de ustedes este día la vida y el bien,
la muerte y el mal`" (Deut.
30:15). De esto depende su felicidad eterna, obedezcan esta palabra y vivirán,
desobedézcanla y morirán. Si ellos hubieran guardado esta palabra,
habrían caminado en obediencia a la ley escrita,
pero al dejarla de lado no pudieron guardarla,
cayeron bajo la maldición de ella y perdieron las bendiciones.
Israel creía agradar a Dios con los sacrificios, el aceite,
el incienso y la observancia de las lunas nuevas y días de reposo,
pero el Señor continuaba rechazándolos por la falta de obediencia a esta palabra.

Los profetas también los guiaron a esta palabra rogándoles que "`circuncidaran sus corazones.`"
Incluso después de mucho conflicto entre el Señor y ellos,
cuando el pueblo parecía muy deseoso de complacer al Señor con lo que Él había requerido,
ya fueran "`holocaustos, becerros,
carneros o aceite,`" los profetas ponían a un lado todo eso,
les señalaban la obediencia a esta palabra como la manera
de agradar a Dios y como lo único que Él requería de ellos.
"`Oh hombre, él te ha declarado lo que es bueno, y qué pide Jehová de ti:
solamente hacer justicia, y amar misericordia, y humillarte ante tu Dios`" (Miq.
6:8). ¡Oh, hombre, todo esto está escrito en tu corazón. Léelo ahí, obedece esa palabra,
esto es lo que Dios requiere!

Asimismo,
la ley de David era la palabra escrita en su corazón. Él vio a
través de los sacrificios y holocaustos el escrito interno,
esto lo hizo más sabio que todos sus maestros,
los que estaban ocupados en la ley externa.
La ley externa sólo era una sombra de los bienes venideros y no perfeccionó nada,
pero David conocía una ley perfecta: "`La ley del Señor es perfecta,
que convierte el alma`" (Sal.
19:7).

[.small-break]
'''

3+++.+++ Las Escrituras del Nuevo Testamento nunca se llamaron a sí mismas '`regla`', no;
llamaron '`regla`' a otra cosa.
Ellas identificaron los escritos del Espíritu de Dios en
los corazones de Su pueblo como la ley del nuevo pacto.
(Heb.
8:10) Denominaron a Cristo como "`el Camino, la Verdad, la Vida.`"
(Juan 14:6) (El camino es la regla, la verdad es la regla, la vida es la regla).
Señalaron a la nueva creación como la regla,
como caminar de acuerdo a aquello en lo que se recibe y disfruta la paz y la misericordia.
(Gal.
6:16) Se refieren al Consolador como el guía a toda verdad (Juan 16:13); sí,
el ámbito de toda la verdad en el que el creyente
tiene que tener la totalidad de su vida y recorrido.
(Gal.
5:25) Vivan en el Espíritu, caminen en el Espíritu, sigan al Espíritu,
manténganse dentro de ese ámbito y no se equivocarán.

Un hombre puede errar en el entendimiento e interpretación de las Escrituras,
pero aquel que ha recibido al Espíritu, conoce al Espíritu,
sigue al Espíritu y se mantiene en el Espíritu; y en la medida que lo haga,
en esa misma medida no puede errar.
Por eso dice Juan, escribiendo con respecto a los engañadores y advirtiendo contra ellos:
"`Ustedes han recibido la unción,
la cual les enseña todas las cosas`" (1 Juan 2:27). Manténganse
en las enseñanzas de la unción en todo y estarán a salvo.
¿Podemos ser engañados?
No, la unción nos guarda de todo engaño en el corazón,
y de todo engaño de los engañadores; "`...y es verdadera, y no es mentira`" (ver. 27),
conduce a toda verdad y saca de toda mentira,
esta les enseñará a permanecer en Él. ¿En quién? En la Palabra que era desde el principio,
la injertada en el corazón de cada creyente,
y en la que el corazón de cada creyente ha sido injertado.
La Palabra está verdaderamente en la vid,
y la savia de la vid corre en el creyente y lo hace fructífero para Dios.
Él permanece en la Palabra que ha oído desde el principio y la
Palabra que era desde el principio permanece en él (ver. 24).

El apóstol Pablo dice expresamente que la justicia de la fe viene por el oír esta Palabra.
Así como Moisés dijo que Ella era el mandamiento de Dios para ellos,
Pablo coloca a esta misma Palabra como la regla de los hijos del nuevo pacto hoy.
Demuestra que él, de hecho, no enseñó nada sino a Moisés y los profetas (Rom.
10:6) al apuntar a la misma Palabra y mandamiento de vida eterna como
lo había hecho Moisés. "`Esta es la Palabra de fe que predicamos.`"
La Palabra que Moisés enseñó y que dijo que estaba cerca de ellos,
en el corazón y en la boca (pues ningún hombre necesita subir al cielo,
bajar a las profundidades o buscarla en algún sitio) es precisamente la que apuntamos.
Esta es la Palabra de fe, este es el mandamiento de vida.
¡Con cuánto celo clamaría Pablo (si estuviera vivo ahora en el
cuerpo) contra los que pasan por alto o niegan esta Palabra,
y establecen en su lugar sus escritos, junto con los escritos del resto de los apóstoles,
como la regla verdadera!

De hecho, yo podría demostrar más aún, cómo el espíritu de profecía,
el testimonio de Jesús,
o la aparición viva de Dios en el corazón ha sido una regla para los testigos
contra el engaño del anticristo durante la larga noche de la apostasía. (Apoc.
11:3; 19:10)

Ahora consideren si las Escrituras son o no verdaderamente su regla.
¿Esperan ustedes con sencillez de corazón que el Señor abra las Escrituras por
Su Espíritu y mantenga fuera su razonamiento carnal (el cual no puede entenderlas,
sino torcerlas y hacerlas hablar en conformidad a sus deseos)?
O, ¿buscan ustedes en ellas con la parte natural,
la que siempre ha estado cerrada al conocimiento correcto de ellas?
"`El hombre natural no entiende las cosas del Espíritu de Dios.`"
El Espíritu de Dios es el único que entiende el significado de
Sus propias palabras y sólo Él da el entendimiento de ellas;
dicho entendimiento no es dado al escudriñador sabio
ni al disputador (ni al profesante prudente,
Mat.
11:25), sino a los niños que Él engendra.
A estos Él les da el reino y les abre las palabras
de las Escrituras con respecto al reino.
"`La sabiduría de la carne es enemistad contra Dios,`"
y si dicha sabiduría carnal escudriña las Escrituras,
sólo reunirá conocimiento adecuado para esa enemistad.
En este sentido los judíos eran grandes enemigos de Cristo.
Ellos se opusieron a la verdadera Palabra con el conocimiento carnal
que habían reunido de las Escrituras que Dios les había dado.
Este mismo espíritu se ha enrollado alrededor de las Escrituras escritas por los apóstoles.
Porque así como este espíritu luchó contra Cristo y Sus apóstoles usando las Escrituras
del Antiguo Testamento (las cuales había escrito antes el Espíritu de Cristo),
así pelea ahora contra las ovejas de Cristo usando las Escrituras del Nuevo Testamento.

Ciertamente,
el gran bastión del anticristo hoy es la Escritura interpretada por la sabiduría carnal.
Porque el anticristo no viene con una negación directa de Cristo
o de las Escrituras (es demasiado astuto para ponerse en eso),
sino que las inclina hacia un lado mediante la sabiduría
carnal para que le sirvan a la voluntad carnal.
De esta manera,
socava al Espíritu y exalta la carne con un entendimiento y una interpretación
carnal de las Escrituras que fueron escritas por el Espíritu contra la carne.
Es por causa de este error que muchos alaban inocentemente las cosas practicadas al
principio del surgimiento de la verdad (la que surgió en los días de los apóstoles),
sin ver de qué naturaleza eran, sobre qué consideración fueron hechas,
cuáles de ellas fueron desechadas por el mismo Espíritu
qué había conducido al uso de ellas antes,
aunque las Escrituras testifican expresamente de esto.

Muchos tipos de profesantes proclaman las Escrituras como su regla,
pero ¿cuáles de ellos son enseñados por el Espíritu
a mantener la parte carnal fuera de las Escrituras?
¿Cuáles de ellos mantienen fuera su propia voluntad y entendimiento,
y reciben el entendimiento de las Escrituras únicamente
del Espíritu que las escribió? En su lugar,
¿no reúnen los hombres conocimiento en la carne y crecen fuertes, sabios,
capaces de disputar y confiados en sus propias formas,
y se convierten en feroces enemigos de todos aquellos que
no coinciden con sus interpretaciones de las Escrituras?
Por consiguiente, la mente de Dios o el verdadero significado de las Escrituras,
no es la regla de ellos, sino una imagen que se han formado a partir de ellas.
Tienen un significado que sus ingenios han imaginado
fuertemente y lo defienden con argumentos,
pero la verdadera mente e intención del Espíritu está oculta para ellos.
Así, pues, por estos medios, muchos engañan tanto sus propias almas,
como ayudan a engañar las de otros al perder la claridad y simpleza del Espíritu,
y reúnen conceptos en la sabiduría y sutileza de la parte carnal,
donde la sabiduría de la serpiente se aloja y se enrolla alrededor del árbol del conocimiento.
Ahora, pues, ¿qué están haciendo realmente estos hombres?
¿A quién le están sirviendo realmente?
¿Hacia dónde se llevan y llevan a otras pobres almas que pretenden salvar?
