[short="Capítulo VIII -- La Autoridad y Gobierno que Cristo Excluyó"]
== Capítulo VIII. La Autoridad y Gobierno que Cristo Excluyó de Su Iglesia

[quote.scripture, , Mateo 20:25-28]
____
"`Entonces Jesús, llamándolos, dijo:
Sabéis que los gobernantes de las naciones se enseñorean de ellas,
y los que son grandes ejercen sobre ellas potestad.
Mas entre vosotros no será así,
sino que el que quiera hacerse grande entre vosotros será vuestro servidor,
y el que quiera ser el primero entre vosotros será vuestro siervo;
como el Hijo del Hombre no vino para ser servido, sino para servir,
y para dar su vida en rescate por muchos.`"
____

Con esto Cristo corta el tipo de poder y autoridad
que crece en la naturaleza corrupta del hombre,
el que a veces surgía incluso en los discípulos.
Aquí Cristo lo excluye por completo de la iglesia y dice expresamente,
que no habría tal cosa entre ellos; no habría ese tipo de grandeza,
ni ese tipo de autoridad.
Entre los gentiles hay grandes y hay príncipes,
y esos grandes y esos príncipes se enseñorean sobre los
inferiores ejerciendo autoridad y dominio sobre ellos,
"`...mas entre vosotros no será así.`"

El estado gentil era una sombra, así como el estado judío era una sombra.
Uno de muerte, el otro de vida; uno de tinieblas, el otro de luz.
Uno era la imagen de Satanás, el príncipe de maldad, el otro era la imagen de Cristo,
el príncipe de justicia y paz.
Ambos eran velos bajo los cuales se escondían los dos reinos.

Bien, en el estado gentil había naciones, príncipes, leyes, gobernantes, dominios,
autoridades, etc., pero todos estaban caídos, en tinieblas,
en transgresión de la vida de Dios.
El estado completo era corrupto y en el reino de Cristo no debía hacerse ninguna imitación,
ni ninguna semejanza de él, ni de tales cosas.
En el reino de Cristo no hay tal tipo de ley, ni tal tipo de gobierno,
ni tal tipo de autoridad, ni tal tipo de enojo hacia las personas que transgreden,
ni tal tipo de tratos con ninguna.
Nada afligirá, ni hará mal en el santo monte de Dios, porque hay un cetro justo,
un cetro dulce,
un cetro espiritual que alcanza al espíritu del hombre en el poder de la vida,
pero que no toca al hombre exterior.

Dos cosas excluye Cristo aquí;
de estas dos se levanta todo tipo de daño en la iglesia
(toda la tiranía y opresión de las consciencias de los hombres,
de sus personas, estados y libertades; todo por causa de la consciencia).
Primero, la grandeza personal; segundo,
el ejercicio de dominio y autoridad por aquellos que desean ser grandes de esta manera.
Este tipo de grandeza tal como es en el mundo, es la destrucción de la vida de Cristo.
Ese tipo de dominio y autoridad tal como es entre las naciones,
es la directa anulación del reino de Cristo.
Esto establece otro poder que no es el de Cristo, otra grandeza que no es la de Cristo,
otra clase de autoridad que no es la de Cristo,
así se consume la virtud y la vida de Su reino haciéndolo
tal como uno de los reinos de este mundo.

"`Mas entre vosotros no será así.`" Este espíritu debe mantenerse fuera de entre ustedes.
Este espíritu ambicioso, este espíritu altivo,
este espíritu que ama ser grande y le encanta tener dominio,
busca exaltarse a sí mismo debido al don que ha recibido y al deseo
de llevar a otros a sujeción. Este espíritu debe ser sometido entre
los que son discípulos de Cristo o lo arruinará todo.

El Señor da gracia y conocimiento,
pero no lo da con la intención de que los hombres lo tomen para engrandecerse
a sí mismos o para gobernar sobre otros debido a ello.
El que por causa de la dádiva recibida piensa de sí mismo como
apto para gobernar sobre las consciencias de los hombres y hacerlos
inclinarse ante lo que él conoce o piensa que es la verdad,
perderá su propia vida.
Porque no es hablar cosas verdaderas lo que hace bien,
sino hablarlas a partir de lo que es puro y transmitirlas a lo que es puro,
pues la vida corre a lo largo de una vasija de vida
en uno hacia la vasija de vida en otro.
Pues las palabras, sin importar cuán ciertas puedan ser,
no pueden transmitir vida a otro,
sólo en la medida que una vasija viva se abra en uno y sea abierta en otro.

[.discourse-part]
Pregunta: Pero,
¿cómo se puede mantener este espíritu fuera o abajo
para que no dañe al discípulo en quien se levanta?

[.discourse-part]
Respuesta: Cuando este espíritu empiece a levantarse en alguien,
tan pronto como ese alguien lo perciba,
tiene que luchar contra él en la luz que lo descubrió.
Tiene que ponerse a sí mismo en la posición más baja,
tiene que prestar atención a la cruz,
bajarse y someterse en servicio y ministerio a los que son poco o pequeños a sus ojos.
En lugar de gobernar sobre ellos, déjenlo tumbarse debajo de ellos,
déjenlo ver y conocer la Semilla de vida en otros y servirla,
aún en la medida más pequeña, porque ese es su lugar.
El que quiera reinar tiene que servir,
el que quiera ser grande tiene que ser pequeño y la pequeña Semilla tiene que
convertirse en una nación. La Semilla que está abajo tiene que levantarse,
y usted no se tiene que levantar con ella más allá de lo que puede servirla,
tanto en usted como en otros.

¡Por lo tanto, si usted alguna vez tiene ambiciones,
si alguna vez tiene la idea de gobernar,
si alguna vez piensa que usted es capaz de enseñar por lo que ha recibido, húndase,
bájese, tome la cruz contra ese espíritu orgulloso y haga que se doblegue y sirva!
Permita que la vida en cada uno se levante sobre ese espíritu y lo pisotee,
y después algo se levantará en usted que es capaz de enseñar, sí,
y de gobernar en el Señor. En tanto ese algo tenga el dominio,
usted puede ser útil para el Señor, para Su verdad y Su pueblo.
Pero si alguna vez se vuelve a levantar lo otro,
usted deberá volver a bajarse de inmediato.

De este modo,
si un hombre es fiel a Cristo este espíritu malo y ambicioso
puede ser tratado en su primera aparición y mantenerlo abajo.
Pero si dicho espíritu es admirado y se le abre paso,
una vez levantado será difícil de derribar.
Por eso, los discípulos o la iglesia de Cristo tienen que vigilar tal espíritu, abatirlo,
testificar contra él, darle la espalda, arrasarlo, ponerlo en su lugar, debajo de todo,
al servicio de todos, y así no permitirle levantarse.
El que quiera ser grande, el que quiera reinar tiene que servir.

Cristo exhorta a Sus discípulos desde Su propio ejemplo:
"`...como el Hijo del Hombre no vino para ser servido,
sino para servir`" (ver. 28). Si alguien tenía derecho a ser grande, sin duda era Cristo.
Si alguien tenía derecho a ejercer autoridad, ese era en definitiva Cristo.
Si alguien era superior por causa de un don recibido
o debido a la presencia del Espíritu en Él,
ciertamente era Cristo.
No obstante,
Cristo no tomaría sobre Sí este tipo de grandeza ni ejercería este tipo de autoridad; no,
Él fue un siervo.
Él hizo uso del don del Espíritu y del poder de la
vida recibida del Padre para ministrar y servir.
Nunca se enseñoreó sobre la consciencia de ninguno de Sus discípulos,
tuvo paciencia con ellos compadeciéndose de sus debilidades.
("`¿Así que no habéis podido velar conmigo una hora?...
el espíritu a la verdad está dispuesto,
pero la carne es débil`"). Nunca les ofreció lo que
Él sabía que era verdad y demandó que lo creyeran.
Antes bien,
estaba contento con ellos en su estado y a la espera de que sus capacidades fueran ensanchadas,
estando satisfecho con la honestidad e integridad
de sus corazones en su presente estado de debilidad.

Tampoco se esforzó Cristo por reinar sobre el mundo,
ni invocó fuego del cielo cuando no lo recibieron.
No expresó indignación cuando desearon que saliera de su ciudad,
ni pidió doce legiones de ángeles cuando llegaron a traicionarlo en busca de Su vida.
Todo lo contrario,
la vida que había recibido de Su Padre la rindió como rescate por Sus discípulos, y sí,
por Sus enemigos también. Note:
Cristo no hizo uso de lo que le fue dado para levantarse por encima
de otros o para que Su palabra se estableciera como ley,
más bien esperó hasta que fuera revelada en Sus discípulos y en el pueblo;
en aquellos que eran capaces de recibir Su testimonio.
Él hizo uso de Su poder de vida y de la plenitud del Espíritu para servir más abundantemente
y para esperar con paciencia el cumplimiento de la voluntad del Padre.
Y aunque Israel no estaba dispuesto a ser recogido por Él, fue manso,
paciente y reposado en la voluntad de Aquel que lo
envió. En lugar de buscar reinar sobre todos,
sirvió a todos y dio esa vida (cuyo deber era reinar)
"`en rescate por muchos`" (ver. 28).

"`Su reino no era de este mundo;`" no buscó ninguna
grandeza o autoridad de acuerdo a este mundo,
ni sobre los judíos, ni sobre los gentiles, ni sobre Sus propios discípulos,
sino que les sirvió a todos, buscó el bien de todos.
La vida en Él (la que era para reinar sobre todo) aquí sirvió a todos, sufrió por todos;
ese fue Su camino a Su corona.
Y ahora, habiendo terminado Su viaje, cumplido Su servicio,
perfeccionado Sus sufrimientos, se ha sentado a la diestra de la Majestad en las alturas,
donde reina sobre todo y fue hecho rey por Dios en justicia.
Este es el patrón por el que Sus discípulos tienen que caminar.
Cuánta más vida reciban, más tienen que ministrar, más tienen que servir.
No deben alzarse por sus dones.
No deben enseñorearse sobre otros,
ni exponer su conocimiento o doctrinas y hacer que otros se inclinen ante eso.
No, más bien deben esperar en su servicio hasta que el Señor abra camino
en los corazones de los hombres y siembre Su verdad ahí,
y en Él tienen que esperar el riego y el crecimiento de ella.

=== La Autoridad y Sujeción del Espíritu

[.discourse-part]
Pregunta: Pero,
¿no debe haber grandeza ni autoridad entre los discípulos
de Jesús o en la iglesia de Cristo?
¿Tiene cada quien que hacer lo que desea,
sujetarse a sus propias fantasías e imaginaciones,
a las invenciones de su corrupto corazón? ¡Qué edificio más confuso sería este!
Con seguridad, esto no hará que Sión permanezca por mucho tiempo,
pronto se convertirá en una Babilonia, es decir, en un cúmulo de desorden y confusión.

[.discourse-part]
Respuesta: No debe haber grandeza o autoridad de _este tipo;_ aún así,
hay tanto una grandeza como una autoridad adecuadas para el estado de
los verdaderos discípulos y para el tipo de reino al que pertenecen.
Hay leyes, hay gobiernos, hay gobernadores, hay reglas y hay sujeción,
pero todo en el Espíritu, y no de acuerdo a la carne.
Tal como el reino de Cristo no es de este mundo,
así el gobierno de Su iglesia y de Su pueblo no es de acuerdo a este mundo.
Así como lo que se reúne en Su Espíritu es espiritual,
y lo que es gobernado son los espíritus de Su pueblo,
así dichos espíritus tienen que ser gobernados por Su Espíritu; espiritualmente,
no carnalmente.

De este modo, Cristo mismo, aunque sirvió a Sus discípulos,
también fue Señor y Maestro de ellos,
y en el Espíritu y la vida del Padre gobernó sobre ellos.
Los apóstoles y otros ministros de Cristo también tuvieron, en el Espíritu,
cuidado de las iglesias y autoridad en el Señor,
y mediante Su Espíritu gobernaron los espíritus de Su pueblo.
Estos no gobernaron según la manera carnal, por medio de sus propias voluntades.
Tampoco les prescribieron a otros qué debían creer o practicar,
sino que en la luz y poder del Espíritu se adentraron
en la consciencia de todos ante los ojos de Dios.
Ministraron a todos en el Espíritu según su capacidad y crecimiento,
y esperaron pacientemente que Dios proveyera la comida
y nutrición y que edificara sus espíritus en la fe.

"`El espíritu de los profetas está sujeto a los profetas.`"
Aquí está el gobierno, esta es la ley de la regla y sujeción en la vida.
Toda persona que experimenta una medida del Espíritu en sí misma,
es enseñada a reconocer y a sujetarse a una mayor medida del mismo Espíritu en otro.
El que no tiene una medida del Espíritu de Dios, no es de Dios, ni es de Cristo,
pero el que ha recibido una medida del Espíritu,
en el mismo Espíritu puede sentir la medida de otros y reconocerla en su sitio y servicio,
conocer sus movimientos y no la apagará, sino que le dará paso con gozo y deleite.
Cuando el Espíritu se mueve en alguien para hablar,
el mismo Espíritu se mueve en otro para sujetarlo y abrirle paso.
Así, pues,
como todos se mantienen dentro de los límites de
su propia medida en el Espíritu no hay desorden,
sino verdadera sujeción por parte de cada espíritu.
Pero donde esta falte,
no puede ser suplida o establecida en la iglesia por ninguna regla u orden externo,
pues ese sería carnal, dejaría entrar la carne y destruiría el verdadero orden,
regla y sujeción del Espíritu.

Los verdaderos apóstoles y ministros de Cristo vienen
de Cristo con un mensaje de vida y salvación,
con un testimonio acerca de la buena voluntad de Dios y Su amor por la humanidad.
Estos señalan el camino de la muerte a la vida, de la esclavitud a la libertad,
de la ira y destrucción a la paz y salvación. Lo que ellos han visto, lo que han sentido,
probado y manejado, lo que han encontrado que los redime y libera,
es lo que le declaran a otros conforme son movidos, enviados, guiados y asistidos.

Ahora bien,
lo que ellos predican es para la consciencia de los hombres ante los ojos de Dios.
Ellos presentan la verdad que conocen, dan su testimonio en el movimiento,
conducción y poder del Espíritu,
y dejan que el mismo Espíritu lo demuestre en la
consciencia de los hombres como a Él le plazca.
Los ministros son nada, no pueden hacer nada, ni pueden convertir a alguien a Dios.
Sin embargo, el poder que habla por ellos,
es el mismo poder que obra en la consciencia de otros hombres en su tiempo.
Este es el comienzo del gobierno de Cristo en el corazón:
Cuando la verdad de Cristo lleva la convicción con ella a la consciencia,
y la consciencia es arrastrada a rendirse a Él,
Cristo pone Su yugo sobre ella y toma sobre Sí la guía de la misma.
Él la aprecia, la limpia, la consuela, la ordena según Su voluntad.
Sólo Él la preserva pura, casta, suave, mansa y dócil a las impresiones de Su Espíritu.
Cuando la consciencia se mantiene sin mezcla y tierna para Cristo,
Su gobierno se incrementa en ella,
pero cuando se endurece o se somete a la voluntad de los hombres,
toma dominio sobre ella otro espíritu.

Por tanto, la mayor obra del ministro de Cristo,
es mantener la consciencia abierta a Cristo y salvaguardar a los hombres de recibir
de él verdades de Cristo más allá de lo que el Espíritu les ha revelado.
Debe evitar que los hombres imiten cualquiera de sus prácticas
más allá de donde el Espíritu los ha conducido,
guiado y persuadido.
Pues los hombres son extremadamente propensos a recibir las cosas como
verdades de aquellos de quienes tienen alta opinión e imitar sus prácticas,
y con ello dañar su propio crecimiento y poner en peligro sus almas.
Porque si yo recibo una verdad antes que el Señor mediante Su Espíritu me la haga manifiesta,
pierdo mi guía y sólo sigo el consejo de la carne,
la cual codicia en gran manera recibir verdades y
correr a las prácticas religiosas sin el Espíritu.

Por tanto, en la religión lo importante es mantener la consciencia pura para el Señor,
conocer la guía, seguir la guía, recibir de Él la luz mediante la cual debo caminar.
No debo tomar cosas como verdades porque otros las ven como verdades,
sino esperar hasta que el Espíritu me las manifieste
a mí. Tampoco debería correr hacia adoraciones,
deberes, acciones o prácticas porque otros son llevados ahí,
sino esperar hasta que el Espíritu me lleve ahí. Los apóstoles
fueron extremadamente tiernos en este punto,
porque aunque conocían cierta e infaliblemente qué creer,
no se enseñorearon sobre la fe de los hombres,
sino que esperaron hasta que el Señor de la fe abriera
el camino hacia las consciencias de los hombres.
No se atribuyeron la responsabilidad de darle vuelta a la llave
para dejar entrar verdad y convicción en los espíritus de los hombres,
sino que los dirigieron al Único que tiene la verdadera llave.

"`Cada uno esté plenamente convencido en su propia mente,`" dijo el apóstol
en Romanos 14. Tengan cuidado de recibir las cosas demasiado pronto,
tengan cuidado de correr a las prácticas demasiado pronto,
tengan cuidado de hacer lo que ven hacer a otros.
Antes bien, esperen su guía particular y una completa persuasión proveniente de Dios.
Aunque yo sepa que algo es verdad,
ustedes no deben recibirlo hasta que Dios se los manifieste a ustedes.
Reciban la verdad sólo de Su mano,
manténganse hasta que Él se las dé. Ciertamente el asunto
más importante en la religión es evitar que la parte equivocada,
la parte que se adelanta, el primer nacimiento, corra a deberes y eche mano de promesas;
y también, experimentar al verdadero Heredero nacido de la Semilla inmortal,
Aquel a quien le pertenecen todas las cosas.
Habiendo conocido la Semilla verdadera,
no dejen que después se levante por encima de Él el otro nacimiento,
sino sométanlo y llévenlo a sujeción.

El apóstol repite que tengan cuidado de hacer algo "`con duda.`"
Que no avancen ni se apresuren, sino que esperen la guía,
que esperen la manifestación del Espíritu.
Que estén seguros de recibir todo lo que reciben en la fe,
y que todo lo que practican lo practiquen en la fe, pues "`todo lo que no proviene de fe,
es pecado.`"
Recibir o actuar aparte de la fe es desviarse de la Semilla de vida,
es perder la guía y con ello perder terreno,
deshonrar a Cristo y quedar bajo condenación.

Así advierte el apóstol a los creyentes a tener cuidado de arrastrarse
unos a otros demasiado rápido o a juzgarse entre sí con respecto a cosas,
cuando algunos de ellos tienen luz y otros no.
El que come no tiene que juzgar al que no come;
el que no come no tiene que juzgar al que come.
En asuntos de adoración, el que observaba un día y guardaba el día de reposo,
no tenía que juzgar al que no observaba un día y no guardaba el día de reposo.
Pues en los días de los apóstoles los judíos que se habían convertido verdaderamente,
se tardaron un tiempo en salir de la observancia de los días de reposo.
Es más,
apenas podían sobrellevar a los creyentes gentiles que nunca
habían sido enseñados a guardar los días de reposo,
sino a estimar cada día igual y a santificarlos para el Señor (Rom.
14:5). Y los que estimaban cada día igual y los dedicaban al Señor,
apenas podían soportar a los que observaban un día.

Ahora bien, es cierto que estando presente Cristo no debemos establecer un nuevo tipo,
sino entrar por fe al verdadero reposo,
el cual es la sustancia de lo que los otros días significaban.
Sin embargo,
los cristianos son propensos a luchar en pro de una unidad
y uniformidad equivocadas en observancias y prácticas externas,
y a juzgarse entre sí injustamente en estas cosas.
Ahora observen: No es la práctica diferente lo que rompe la paz y la unidad,
sino el juicio de unos a otros debido a las prácticas diferentes.
El que no guarda un día en particular puede estar unido en el mismo Espíritu,
en la misma vida, en el mismo amor con el que guarda un día,
y el que guarda un día puede estar unido en alma y corazón en el mismo Espíritu y vida
con el que no guarda un día. Pero el que juzga a otro debido a cualquiera de estas cosas,
se desvía del Espíritu, del amor, de la vida y rompe así el vínculo de la unidad.
El que arrastra a otro a cualquier práctica antes de que la vida lo lleve ahí,
hiere el alma de dicha persona.
(Rom.
14:15) Esta era la regla del apóstol:
Cada uno realice individualmente ante el Señor lo que hace,
y no para interferir con la luz de la consciencia de otro (menospreciando a su
hermano o juzgándolo porque su luz y práctica difieren de las de él. Rom.
14:10). Cada uno tenía que mantenerse cerca de su propia medida de luz, es decir,
a la proporción de fe y conocimiento que Dios en Su misericordia le había otorgado.
En la vida interior está la verdadera unidad del Espíritu, no en la uniformidad exterior.
Tal conformidad exterior no era necesaria en los días de los apóstoles,
no es necesaria hoy, y el ojo que la busca pasa por alto lo único que es necesario.

Si los hombres se mantienen cerca de Dios,
Él los guiará y les dará luz con suficiente rapidez,
porque Él se ocupa de tales cosas y sabe qué luz
y qué prácticas son las más apropiadas para ellos.
Sin embargo, cuando los hombres caminan más rápido que el suministro de luz del Señor,
esto les imposibilita avanzar y levanta algo equivocado en ellos.
De esta forma, el verdadero nacimiento sufre,
se empequeñece y es impulsado hacia atrás. ¡Oh,
cuán dulce y agradable es para el verdadero ojo espiritual
ver en la escuela de Cristo varios tipos de creyentes,
varias formas de cristianos! ¡Cuán grande es, de hecho,
cuando cada uno aprende su propia lección realizando su propio servicio, conociéndose,
aceptándose y amándose unos a otros en sus diferentes lugares y desempeños para su Maestro,
a Quien le tienen que dar cuenta,
y no se riñen unos a otros acerca de sus prácticas diferentes! (Rom.
14:4)

Este es el verdadero terreno del amor y de la unidad.
No que un hombre camine y haga lo mismo que yo,
sino que yo experimento al mismo Espíritu y la misma vida que está en él,
y que él camina en ello de acuerdo a su propia medida,
orden y en adecuada sujeción a ello.
Es más, esto es mucho más agradable para mí que si él caminara como yo,
porque yo no puedo desear que lo haga hasta que sea particularmente
llevado allí por el mismo Espíritu que me llevó a mí. El
que conoce lo que es recibir las verdades del Espíritu,
ser llevado a las prácticas por el Espíritu,
y cuán propensa es la parte carnal a adelantarse,
no se apresurará a presionar su conocimiento o prácticas sobre otros.
Más bien,
y por temor a que las reciban y practiquen demasiado rápido
o en la parte del hombre que no puede servirle al Señor,
esperará pacientemente hasta que el Señor los prepare para recibirlas.
En honor a la verdad puedo decir con respecto a mí mismo,
que nunca he hallado mi espíritu presionando para arrastrar a otros,
ni a lo que creo que es cierto,
ni a ninguna práctica o forma de adoración que observo o en la que camino,
sino que he deseado que el poder y guía de la vida vaya delante de todos los hombres,
y tengan temor de recibir cosas de mi mano y no de las del Señor.

=== El Verdadero Gobierno de la Iglesia

Por tanto,
ya que ante los ojos de Dios el verdadero gobierno de la iglesia es en el Espíritu,
sobre la consciencia del hombre y no sobre su cuerpo,
tiene que tenerse mucho cuidado de que nada más gobierne salvo el Espíritu,
y que ese gobierno se extienda únicamente a lo que debe ser gobernado.

_Primero:_
Se debe tener cuidado de que nada gobierne en la
iglesia de Cristo salvo el Espíritu de Cristo.
Nada más enseña, exhorta, amonesta y reprende; nada más corta y echa afuera.
Cada ministro en la iglesia tiene que vigilar que su propio
espíritu no se entrometa en la obra de Dios,
que no tome sobre sí ser el maestro, el que exhorta, el que reprende, etc.
Cada miembro tiene que esperar en la medida del Espíritu que ha recibido,
para experimentar los movimientos del Espíritu en Aquel que enseña y gobierna.
De esta manera cada uno se sujeta al Señor y no al hombre;
cada uno recibe del Señor y obedece al Señor. No
debemos conocer a ningún ministro según la carne,
sino recibir y someternos a lo que proviene del Espíritu en el Espíritu.
No debemos conocer a Pablo, a Apolos o a Cefas, sino al Espíritu ministrando en ellos.
Pablo puede errar, Apolos puede errar,
Pedro puede errar (de hecho erró cuando obligaba
a los gentiles a vivir como los judíos (Gal.
2:14), Bernabé también erró (ver. 13), pero el Espíritu no puede errar.
El que se mantiene en la medida del Espíritu no deja entrar el error,
pues la más pequeña medida del Espíritu es cierta y brinda un juicio verdadero.
Sin embargo, el que recibe una gran medida del Espíritu y no se mantiene bajo,
y no permanece en ella, y por el contrario, se levanta sobre sus hermanos,
fácilmente puede errar y arrastrar a otros en su error.

_Segundo:_ Se debe tener cuidado de mantener la consciencia sensible,
para que nada sea recibido en la consciencia sino lo que está de acuerdo a la luz.
La consciencia es el asiento de la fe,
y si dicho asiento no se mantiene cerca de la luz con la que Dios brilla ahí,
la fe está pronta a naufragar.
El cristianismo se inicia en el Espíritu,
y es el Espíritu mismo el que mantiene fuera la parte carnal,
junto con toda la sabiduría y razonamiento propios de la carne acerca de las cosas espirituales.
Así como el inicio es en la unción, así debe ser el progreso.
Así como el Espíritu comienza en la consciencia convenciendo y persuadiendo ahí,
estableciendo Su luz y conduciendo al alma por medio de dicha luz,
así esa luz debe ser continuamente buscada y vista.
Sólo cuando la luz crece y se manifiesta en la consciencia
hace que el alma se quede quieta o avance.

El gran error en las edades de la apostasía ha sido,
establecer un orden y uniformidad externos,
y hacer que las consciencias de los hombres se inclinen ante ello,
ya sea por los argumentos de la sabiduría o por la fuerza.
Sin embargo,
lo que caracteriza al verdadero gobierno de la iglesia es
que deja la consciencia a su plena libertad en el Señor,
a fin de preservarla sin mezcla y completa para Él,
para que se ejercite y busque la unidad en la luz y en el Espíritu.
El que tiene fe y se ve más allá que otro,
puede tenerla para sí y no molestar a su hermano con ella,
sino descender y caminar con él de acuerdo a su medida.
¡Oh, cuán dulce y precioso es ver a los hermanos habitar juntos en unidad,
ver la verdadera imagen de Dios levantada en las personas,
conociéndose y amándose unos a otros en dicha imagen! ¡Cuán
precioso es soportarse unos a otros a través del amor,
ayudándose entre sí en sus tentaciones y aflicciones de espíritu,
con las cuales todos deben esperar encontrarse!

Si usted es un cristiano de hecho y en verdad,
preserve su consciencia pura y tierna hacia Dios.
No la contamine con prácticas religiosas, deberes, ordenanzas, etc.,
hacia lo cual el Espíritu no lo está guiando,
pues todas esas cosas son ídolos y lo contaminarán en extremo.
Así mismo,
sea sensible a la consciencia de su hermano y no sea un instrumento que lo arrastre
hacia algo donde el Señor no lo haya llevado a él. Más bien regocíjese si lo encuentra
en la sencillez de corazón y siendo tratado por el Señor en cualquier cosa,
pues si él permanece ahí fielmente,
Su guía aparecerá en su tiempo y despejará su camino delante de él.

¡Cuántos se han vuelto del Señor y se han prostituido! ¡Cuántos han perdido
primero la guía de Su Espíritu y luego han ahogado sus vidas en obras
religiosas! ¡Cuántos han bebido de la copa de fornicación contra la vida,
en manos de la sabiduría carnal! ¡Cuántos han llenado sus espíritus de
ídolos e imágenes del Nuevo Testamento! ¡Cuántos incluso han endurecido
sus corazones y consciencias siguiendo las doctrinas de los hombres,
sus significados imaginarios de las Escrituras y las imaginaciones
y sueños de sus propios corazones! ¿No es tiempo de que los hombres
se vuelvan al Señor y esperen la visitación y luz de Su Espíritu?
Si alguien en algún momento experimenta y disfruta la guía del Espíritu de Dios,
debe mantener su consciencia sensible a ella,
lista a oír y a seguir Su voz que habla en Espíritu a lo
que ha nacido de Él. "`Mis ovejas oyen mi voz,`" dice Cristo,
ellas la conocen, pero no conocen la voz de un espíritu extraño como para seguirla,
sino que se apartan de ella, tanto en sí mismas como en otras.
Esperen pues el nacimiento del Espíritu, en el que el Espíritu es dado como guía,
Quien infaliblemente guía fuera del engaño.

[.discourse-part]
Objeción: Pero, ¿no es preciosa la unidad?
¿No exhorta el apóstol a los cristianos a ser de una sola mente?
¿No sería algo muy dulce si todos fuéramos de un solo corazón y de una sola manera?

[.discourse-part]
Respuesta: Sí,
la unidad es muy preciosa y tiene que ser deseada y esperada conforme
el Espíritu del Señor (que es uno) nos conduce y hace uno.
Sin embargo,
la parte carnal (la parte del razonamiento sabio en el hombre) mediante
maneras y medios carnales se esfuerza para lograr la unidad carnal;
esta no es preciosa, ni espiritual, ni cristiana.
Si bien es cierto el apóstol exhorta a los cristianos a ser de una mente,
aún así no los empuja a esforzarse unos a otros a ser de una misma mente,
sino a caminar juntos dulcemente en la medida que han alcanzado,
y si en algo piensan de otra manera, en Su tiempo Dios les revelará más (Fil.
3:15-16). Al que tiene, más le será dado.
La intención y obra del ministerio (en las distintas ministraciones
de este) es llevar a la unidad (Ef. 4:13),
según las personas sean capaces de seguir.
No se trata de forzar a todos los hombres en una sola práctica o forma.
Este es el camino para destruir la fe y la verdadera unidad.
Esto, en el mejor de los casos, puede introducir una apariencia carnal de unidad,
en una forma externa de adoración y piedad que carcome el poder.

Ciertamente el camino es uno: Cristo, la verdad de Dios.
El que está en la fe y en la obediencia a la luz que brilla
en el corazón de cada creyente desde Su Espíritu,
tiene una prueba del único corazón y del único camino.
Este sabe que ninguna variedad de prácticas (que son de
Dios) pueden abrir una brecha en la verdadera unidad.
Este es el único camino:
Que cada uno se sujete a la luz del Espíritu de Cristo que ha recibido de Cristo.
Si se mantiene la unidad de esta manera,
eventualmente se llegará a una unidad externa también,
según crece la luz en cada uno y cada uno crece en la luz.
No obstante,
esto debe ser pacientemente esperado de la mano de Dios (Quien
tiene la manera correcta de efectuarlo y el Único que puede hacerlo),
y no intentarlo dura y cruelmente mediante la tosca mano del hombre.
