[short="Capítulo IX -- El Nuevo Pacto del Evangelio"]
== Capítulo IX. La Diferencia entre el Nuevo Pacto del Evangelio y el Antiguo Pacto de la Ley

=== Prefacio

No hay forma de llegar a ser heredero del reino de
Dios si no se es engendrado y nacido de Su Espíritu,
el cual sopla sobre el espíritu del hombre,
respira vida en él y lo forma en la imagen eterna.
(Juan 3:8; Gal.
4:19)

No hay forma de preservar esta obra de Dios en el
hombre sino volviéndose al Espíritu que engendra,
permaneciendo y manteniéndose firme en lo que es
engendrado y cuidándose de la sabiduría carnal.
La sabiduría del hombre permanece cerca para corromper y destruir la obra de Dios,
para tentar y desviar de la verdad hacia una imagen o semejanza de ella.
Si esta sabiduría prevalece, súbitamente se produce un alejamiento de la vida de Dios,
y una marcha en pos de las invenciones de la sabiduría carnal (la cual
aparece en semejanza de la verdadera sabiduría para engañar mejor).

Ahora bien,
cuando el Espíritu respira vida sobre el hombre por
primera vez y es engendrado para Dios,
no hay más que un poco de vida, un poco de sencillez, un poco de luz, un poco de poder,
un poco de la sabiduría del verdadero bebé. Pero también hay un gran cuerpo de muerte,
engaño, tinieblas y poder, y la sabiduría de la carne sigue en pie.
Todo esto se empeña en volcar y destruir la verdadera
obra de Dios levantando una imagen falsa de ella,
lo cual es hecho fácilmente.
Es difícil permanecer y preservarse uno mismo en la verdad,
sólo se mantiene por ese poder que engendró la vida al principio.

El poder de Dios preserva el alma al mantenerla fuera de la parte
sensual y racional del hombre (donde el corrupto tiene su acomodo),
y dentro de la pobre, baja,
pequeña e infantil sensibilidad de la vida que el Padre ha engendrado.
Aquí está la entrada a la verdad, aquí está el crecimiento,
aquí está la preservación y la seguridad.
Esto lo hace muy difícil para los que son sabios y fuertes en razonamiento y comprensión;
se les hace difícil entrar o permanecer y crecer en la desnudez,
sencillez y aparente locura del verdadero evangelio.
¡Oh,
cuánto debe ser derribado antes de que el hombre pueda ser
verdaderamente alcanzado y convencido por las cosas necias
y débiles que usa Dios para lograr Su gran obra! (1 Cor.
1:27,
28) ¡Qué lucha tiene Dios con ellos para golpear su sabiduría y derribar su entendimiento,
que cuánto más grande es, más se interpone en el camino de Su luz! (1 Cor.
1:19) ¡Cuán fácilmente son atraídos los que han sido convencidos,
a regresar a su propia sabiduría mediante uno u otro mecanismo sutil!
¡Cuán rápidamente son alejados de la claridad y sencillez de la verdad,
en el intento de sostenerla en la sabiduría de la parte intelectual del hombre! (2 Cor.
11:3)

En el Espíritu que engendra y en la verdad que es engendrada por Él hay verdadera unidad.
Que en unos y otros se experimente esto, es lo que nos une unos a otros.
Cuando alguien se ciñe a esto en su propia persona, se ciñe a lo que une,
y la parte que puede unirse se mantiene viva en él. Sin embargo,
salirse de esto es salirse de la verdadera unidad
rumbo al error y al terreno de la división. Luego,
ese que se ha desviado y se ha salido de la verdadera unidad
se esfuerza por establecer una imagen falsa de la unidad,
y le echa la culpa al que permanece en la verdad porque no puede unirse.
Pues ese que permanece en el Espíritu y en lo que el Espíritu ha engendrado y formado,
no puede unirse según la carne,
y ese que ha fornicado y que ha huido del Espíritu
hacia una imagen formada por la sabiduría carnal,
no puede unirse según el Espíritu.
¡Consideren esto profesantes de esta era:
Ustedes nos culpan de habernos apartado de ustedes,
de habernos retirado de la unidad con ustedes,
pero nosotros los culpamos de salirse de la Semilla viviente,
la única en la que nuestra unidad con ustedes puede permanecer!

¡Oh,
si pudieran oír la voz del Señor que grita a voz en cuello a los profesantes
de esta era que abandonen al hombre! ¡Abandonen al hombre en ustedes,
los que alguna vez han tenido una prueba de la gracia pura
y del poder de Dios! ¡Abandonen su propio entendimiento,
sus propios afectos, su propio celo,
su propio conocimiento y su propia sabiduría reunida de las Escrituras con todas
las chispas de su propio fuego! ¡Dejen que Dios sea todo en ustedes,
dejen que Su habitación eterna sea levantada y perfeccionada en ustedes
y que ustedes sean consumidos y conocidos en ella para siempre! ¡Oh,
qué obra es para Dios expulsar la razón y la sabiduría del hombre de su templo,
expulsarlo de Sus Escrituras y de todas Sus cosas santas! ¡El que tenga
oídos oiga en aras de la paz eterna de su alma! ¡Ay! ¡Ay! ¡Cuántos tropiezan
y blasfeman de lo único que puede salvar el alma!

Los judíos eran poseedores del Mesías (de acuerdo a las Escrituras, según pensaban),
pero lo rechazaron en la forma que vino para salvarlos.
Ahora bien,
si los cristianos han reunido un tipo de conocimiento
de las Escrituras como lo hicieron los judíos,
¿cómo van a evitar el mismo error, a saber,
confesar a Cristo de acuerdo a las Escrituras (según piensan),
y rechazarlo tal como viene a salvarlos?
¿Cómo pueden evitar rebelarse contra Su ministerio vivo
y contra el poder y la demostración pura de Su Espíritu?
¿No les parecerá Su poder débil y reducido sólo porque no aparece
como ellos esperaban de acuerdo a su entendimiento de las Escrituras?
Por tanto,
al leer las Escrituras en otro espíritu y otra sabiduría
diferente del Espíritu que las escribió,
necesariamente concluirán y reunirán algo diferente de lo que está escrito en Ellas,
y usarán la letra como un medio para desviarse de la vida.

=== El Día de Reposo del Señor

En el verdadero amor por sus almas y en el temor del Señor,
tengo un par de cosas que establecer delante de ustedes,
para que la sencillez en ustedes no sea engañada
y para que no se desvíen del camino de la vida.
Pues si buscan en las Escrituras con el ojo equivocado, leerán mal,
entenderán mal y practicarán mal,
y se alejarán más y más de Dios aún cuando piensen
que están acercándose a Él. Sean persuadidos,
pues,
a considerar seriamente (en la sencillez infantil de Su
engendramiento donde la verdadera vida brota) lo siguiente:

[.numbered-group]
====

[.numbered]
1+++.+++ Que la totalidad de la ley de Moisés (los diez mandamientos,
así como la institución de los sacrificios y de la adoración)
fue añadida por causa de la transgresión. (Gal.
3:19)

[.numbered]
2+++.+++ Que la totalidad de la ley
(los diez mandamientos y los sacrificios) eran representaciones,
figuras o sombras de algo en relación con Cristo la Semilla.
Era inferior a la promesa, pues la ley nada perfeccionó,
sino que apuntó y abrió el camino para la introducción de una mejor esperanza.
(Gal.
3:21; Heb.
7:19) La ley de los mandamientos no perfeccionó más
de lo que las otras sombras o sacrificios hicieron,
sin embargo, con ellos se abrió un camino para una mejor esperanza,
hacia la cual ellos tenían que conducir al discípulo como lo hace un maestro de escuela.

[.numbered]
3+++.+++ Que la totalidad de la dispensación de la ley fue dada a los judíos, no a los gentiles.
(Rom.
9:4)

[.numbered]
4+++.+++ Que la dispensación de la ley de Moisés en la letra duraría
hasta que Cristo la Semilla viniera y la cumpliera.
(Gal.
3:19;
24 y 25) La casa de Moisés con todas las leyes debía preparar
para Cristo la Semilla y darle paso a Él cuando viniera.
Porque cuando llegara la dispensación que fue descrita por medio de tipos y figuras,
la dispensación de figuras llegaría a su fin.
(Heb.
3:5 y 6) Cristo vino para hacer la voluntad,
a guardar y cumplir la totalidad de la ley y ponerle fin a esa dispensación. (Sal.
40; Rom.
10:4) Así quitó Él la primera administración de la ley, la cual era en la letra,
a fin de poder establecer la segunda, la cual es en el Espíritu.
(Heb.
10:9; 2 Cor.
3:7-11)

====

Esta es entonces la verdad, conforme está en Jesús, con respecto a esto: Que Cristo,
al venir en la carne y cumplir toda la justicia (en los diez mandamientos y en los sacrificios),
le puso fin a la dispensación anterior en su totalidad,
para que de ahora en adelante tanto judíos como gentiles acudan a Él a oír Su voz:
"`Este es mi Hijo amado,
a Él oíd.`" Moisés predijo que cuando viniera el
profeta debía ser oído en todas las cosas.
(Deut.
18:15) Todo el ministerio de Moisés no era más que una figura y un símbolo
de lo que el Hijo debía cumplir en el Espíritu después. (Heb.
3:5) Moisés fue fiel al darle la sombra completa a su casa, la nación de los judíos,
pero Cristo lo sería al entregarle toda la ley y la sustancia de la vida a Su casa.
(Heb.
3:6) De modo que ahora en el evangelio, habiendo venido Cristo,
el nuevo pacto y la nueva ley en el Espíritu están en vigor,
y no el antiguo pacto ni la ley en la letra.
Esta nueva ley es más interna, más plena, más cercana,
más espiritual y más duradera que el ministerio de la ley de Moisés para los antiguos.
(Gal.
3:25) Este ministerio de la ley del Espíritu es el que no debe
pasar de los discípulos de Cristo hasta que todo sea cumplido,
sino que debe permanecer una espada contra toda lujuria y deseo de la carne en los discípulos,
hasta que todo ello, con la raíz misma, sean cortados.
(Mat. 3:12; Heb. 4:12; Mat. 5:17 y 18)

[.discourse-part]
Pregunta: ¿De qué eran figura o sombra los diez mandamientos?

[.discourse-part]
Respuesta:
Las tablas de piedra eran representaciones o figuras de las tablas de carne del corazón,
en las que es escrita la nueva ley del pacto de vida.
La escritura de la ley de mandamientos en las tablas de piedra era figura de la escritura
de la nueva ley hecha en el corazón por el dedo del Espíritu de Dios.
La escritura externa en tablas externas era figura
de la escritura interna en tablas internas.

Cuando la nueva ley es recibida de esta manera, escrita de esta manera,
es fácilmente cumplida.
En cambio,
la ley en la letra era muy difícil de cumplir debido a la debilidad de la carne,
y en general demostró ser un acta de ordenanzas contra los judíos.
Porque el que era culpable de una ordenanza era culpable de todas,
así que cada transgresión tenía la fuerza y la fortaleza de toda la ley
contra él. Y ahora cualquiera que corra de vuelta a la ley en la letra
para tomar algún mandamiento tal como fue dado a conocer en ella,
se hace deudor de toda la ley y será hallado quebrantador de la ley en el Espíritu,
es decir, que tiene más dioses que el Señor, un hacedor de imágenes,
uno que toma el nombre en vano, un profanador del día de reposo, etc.
Porque el que no ha recibido la ley del Espíritu de vida en Cristo Jesús,
no conoce al Señor de vida como el único Dios verdadero,
sino que hace imágenes en su mente,
toma Su nombre en vano y no experimenta el poder vivo de la ley.
El tal tampoco puede guardar verdaderamente el día de reposo (no puede dejar el pecado,
abstenerse de sus propias obras, de su propio querer y hacer,
ni entrar al reposo del evangelio).
Porque sólo hay un día de reposo santo para el Señor,
y todos los días de reposo de la ley sólo eran señales de
este al tener una santidad simbólica o representativa.
El verdadero día de redención que el Señor ha hecho (Sal.
118:24) (en el cual Sus redimidos se gozan y reposan en Él) tiene la verdadera santidad.
Este vino por medio de Cristo,
el otro vino por medio de Moisés. (Juan 1:17) La casa o los hijos de Moisés
tenían que guardar el día natural (que era el día para los siervos,
el que era practicado bajo las sombras),
pero los creyentes tienen que guardar este día en el Espíritu
para entrar al reposo por medio de la fe.
(Heb.
4) Ellos tienen que adorar al Padre en él, en Espíritu, en verdad,
en la montaña de Su santidad (Juan 4:23), de la que la otra montaña, templo,
adoración y día sólo eran una sombra.

Ahora bien,
la suma o sustancia de esta ley del Espíritu puede ser expresada
externamente en varias palabras cortas que la abarcan,
palabras como: amor, temor del Señor, "`no codiciarás`" (así le fue administrada a Pablo,
Rom.
7), "`acuérdate del día de reposo,`" "`cree en la luz, sigue la luz.`"
El acatamiento de cualquiera de estas en el Espíritu es el cumplimiento de la ley,
porque toda violación a la ley está fuera del amor, fuera del temor,
es codicia del espíritu carnal,
una transgresión del día de reposo (o del reposo espiritual de Dios),
está fuera de la luz y fuera de la fe.
Pero si ustedes leyeran esta en el Espíritu y llegaran a la verdadera justicia
de la fe (la cual es recibida en la obediencia de la fe a la ley del Espíritu),
entonces llegarían a la Palabra de fe, a la que Pablo nos dirige.
(Rom.
10:6) Por el oír esta palabra es la justificación,
y no por una creencia simple de que la sangre de Cristo fue derramada.
Porque es el _poder_ de la sangre lo que salva, cuyo poder está en la palabra viva,
y es experimentado y recibido al oír, creer y obedecer dicha palabra,
llevando así al alma a la unidad y conformidad con Él,
tanto en Su muerte como en Su resurrección y vida.
Este es el único camino a la vida.
No se engañen, no hay y nunca ha habido otro camino.
¡Oh, esperen al Señor en Su temor que el camino sea abierto para ustedes!

=== Un Pacto Espiritual

El apóstol Pablo dice que Dios los hizo "`...ministros competentes de un nuevo pacto,
no de la letra, sino del espíritu`" (2 Cor.
3:6). Después de la dispensación de la ley, la que era sombra de cosas buenas por venir,
y después de la dispensación de los profetas,
quienes predijeron mejores días y mejores condiciones por venir,
le plació a Dios enviar a Juan el Bautista como precursor en el espíritu
y poder de Elías para que preparara el camino del Rey y Su reino.
Luego el Rey mismo fue enviado en la plenitud de Su Espíritu,
para que reuniera discípulos para Sí y les proporcionara
una medida competente del mismo Espíritu.
Estos tenían que levantar una simiente espiritual para Él,
en quienes el Rey establecería Su reino y morada.
Ahí Él caminaría y reinaría haciendo brillar Su luz desde allí y alrededor de la tierra;
desde Su santa ciudad fundada sobre Su santa montaña de Sión.

Ahora bien,
los discípulos o ministros que Él escogió para levantar esta simiente santa para Él,
fueron hechos competentes para ministrar Su nuevo pacto.
Ciertamente les proporcionó tal poder de Su Espíritu
que fueron capaces de ministrar a través de Él,
no en la letra, como fue ministrado el antiguo pacto (que dejó al pueblo muerto,
o que debido a la naturaleza transgresora,
hizo abundar la transgresión e incrementó la muerte sobre ellos),
sino en el Espíritu vivificador.
Este Espíritu es el que levanta de la muerte e introduce en la luz de los vivos
para caminar con el Dios vivo hacia la tierra del eterno reposo y paz.
Por lo tanto, lo que ellos ministraron era Espíritu y a lo que ministraron era espiritual.
Por el poder del Espíritu, y en la predicación de la Palabra viva de fe,
alcanzaron a través del velo eso que yacía en la muerte,
estimularon la semilla viva y le ministraron vida a través del Espíritu.
(Gal.
3:5) A aquellos que habían nacido de esa Semilla viva les enseñaron a vivir en el Espíritu,
a caminar en el Espíritu,
a ser perfeccionados por el Espíritu y a no correr de vuelta a la ministración
de la letra (como era común para los judíos de sus días).
Ellos fueron enseñados a no correr de regreso a la manera de la dispensación anterior,
sino a permanecer en la Semilla viva, a crecer en la Semilla,
en la vida eterna y en la inmortalidad del evangelio.

¡Observen bien (ustedes cristianos que desean vida eterna)
la diferente ministración que hay entre la ley y el evangelio!
La ley era el ministerio de la letra,
en ella debían buscar ayuda del Espíritu para ser guardados
en la fe de la ley y ser hechos obedientes a ella.
(Neh.
9:20) El evangelio es el ministerio del Espíritu,
en el que los cristianos tienen que comenzar y continuar.
Ellos no deben reunir reglas externas de la letra,
de lo que está escrito o de lo que está dicho,
sino mantenerse en la Semilla viva y experimentar refrigerio en esta,
leyendo u oyendo lo que está escrito o es dicho por el Espíritu.
De esta manera, cuando las Escrituras son leídas,
o cuando se escucha a uno que habla de parte de Dios,
eso se mezcla con fe y se vuelve provechoso y nutritivo,
refresca la planta joven y tierna, la Semilla viva y hace que crezca en ellos.
Sin embargo, lo que sea que se entienda, se reciba o se retenga fuera del Espíritu,
alimenta la parte terrenal y sólo engrosa el velo sobre la Semilla viva.

"`El reino de los cielos se ha acercado,`" dijo Juan el Bautista.
(Mat.
3:2) "`...ha llegado a vosotros el reino de Dios,`" dijo Cristo (Mat.
12:28), hablando de ese poder de vida que fue hecha manifiesta a los fariseos en Él. (Luc.
17:21) Los fariseos le preguntaron cuándo vendría el reino de Dios.
Él les dijo que no vendría con apariencia exterior o evidencia ocular.
Que no vendría de la manera que ellos buscaban que viniera, es decir,
mediante la manifestación de un glorioso rey externo para
reinar externamente sobre la ciudadanía del Israel externo.
El reino está en ustedes.
¿Cómo estaba en ellos?
Cristo les explica en otro lugar, que estaba dentro de ellos como un grano de mostaza,
que era la más pequeña de todas las semillas en sus corazones.
Que había muchas y muy grandes semillas de oscuridad ahí,
pero que también había una Semilla pequeña de luz.
Está ahí junto con las otras (aunque más pequeña que todas
ellas) y a veces arroja algunos destellos de luz,
aunque las tinieblas no puedan comprenderla.
Esta Semilla también fue comparada con levadura,
la cual al ser recibida por fe en la masa,
leudaría la masa completa y le daría el sabor y el dominio del reino.
El ministerio de los apóstoles era volver a los hombres
del reino de Satanás a este reino;
de su gran extensión de dominio en el corazón, a esta Semilla estrecha;
de su gran territorio de oscuridad, a esta pequeña Semilla de luz;
de su gran poder de muerte,
a esta pequeña y débil cosa de Dios en la que el poder eterno y divinidad es hecho manifiesto.
Todo esto llega a ser revelado e incrementado por el Espíritu.
Aquí la luz es sembrada para el justo y el gozo para el recto de corazón, donde crecerán,
y desde donde será recogida la cosecha después de su crecimiento hacia la perfección.

¡Cuánto tiempo han carecido los cristianos (así llamados) del Espíritu!
¡Cuánto se han fatigado corriendo de un lado para otro a través
de la letra para encontrar la mente de Dios,
y aún así siguen insatisfechos con respecto a ella, e incluso,
ahogándose en imaginaciones y argumentos carnales acerca de ella!
Buscan satisfacer esa parte que no puede ser satisfecha.
Buscan saber con esa parte que no puede saber.
Le ofrecen a Dios servicio, fe y obediencia de lo que Él no aceptará,
y se guardan lo que Él busca.
Buscan al Espíritu en la letra según la forma de la ley,
pero no se esperan para experimentarlo en la Semilla, en la Semilla que da vida,
morando en la Semilla, donde Cristo y Sus apóstoles nos mandaron a esperarlo.
Buscan en palabras escritas el conocimiento, la fe, la vida y el Espíritu, lo cual,
según predicó el apóstol,
debía ser buscado en la Palabra en el corazón. Por estos medios
levantan distintos edificios y obtienen varios tipos de conocimiento,
cada uno de acuerdo a su propio entendimiento y comprensión de la letra,
y cada hombre está muy confiado de que tiene razón según sus propias comprensiones.
De esta manera se desvían de la ciudad del Dios vivo y del conocimiento vivo,
y levantan imágenes (algunas externamente, algunas en sus mentes, algunas más toscas,
otras más refinadas) carentes de la verdadera vida y poder de Dios.

¡Oh, si ustedes pudieran leer en la luz eterna de vida! ¡Cristianos,
cristianos! ¡Si pudieran ver cómo el entendimiento y el conocimiento que
tienen de la letra se interponen en sus caminos tanto como lo hizo el
conocimiento de los judíos en los de ellos! ¡Este conocimiento debe ser
derribado tan completamente como fue derribado el de ellos,
antes de que el fundamento del reino pueda ser colocado
y el edificio de la vida eterna alzado en sus corazones!
No se ofendan por causa de mi celo por el Señor mi Dios y por sus almas,
me ha costado muy caro lo que les testifico en la sencillez
e integridad de mi corazón. Ahora sé que esto es muy cierto,
que ese espíritu del hombre que se ha anidado en la letra sin la luz eterna,
y que ha hallado un tipo de sabiduría y conocimiento en ella,
será sacudido y expulsado por el mismo Espíritu que dio la letra.
Cuando esto sea hecho y el Espíritu de Dios finalmente revele la letra:
¡Cuán dulce y provechoso será leer en la luz del Espíritu! ¡Cuán
claro y refrescante leer en la fe que es en Cristo Jesús,
la cual es engendrada en el corazón por la palabra de fe!
De esa luz, de esa fuente (según el Señor se complace en revelar,
ensanchar y llenar la vasija) salieron todas las palabras de los santos hombres de Dios,
y solo en dicha luz tienen los hombres su dulzura, frescura, virtud y plenitud.
Nosotros tenemos que leer estas palabras externamente escritas,
manteniendo esa luz y entendiéndolas en esa fuente!
Debemos mantener fuera al hombre natural junto con su entendimiento natural,
el cual no conoce las cosas del Espíritu ni puede conocerlas o recibirlas.
(1 Cor.
2:14) Esto es un misterio para aquellos que no se han vuelto internamente a esta palabra,
ni han conocido u oído Su voz.
Sin embargo, el Señor está recuperando el misterio de la vida y conforme este aparezca,
el misterio de la muerte debajo de toda su pintura (debajo de toda su fe pintada,
amor pintado, conocimiento pintado, obediencia pintada, deberes pintados,
ordenanzas y adoración) será hecho manifiesto.
¡Dichoso aquel cuyo edificio interior permanezca,
cuyo oro soporte el fuego y las llamas eternas del celo de Dios,
y cuyo colirio haya sido comprado al verdadero Espíritu! ¡Cuán
duro será para el hombre a quien el Señor (cuando Él venga a buscarlo)
no encuentre ser un verdadero judío en el interior,
ni haya sido verdaderamente circuncidado por el Espíritu eterno y luz del Señor!

Esta es la gran miseria de los cristianos: Que el velo está sobre sus corazones,
el mismo velo que les tapaba a los judíos la letra de Moisés.
Estos están buscando a tientas la mente de Dios en la letra,
pero la vida está escondida para ellos,
así como lo estuvo para los judíos. Y puesto que también
dicen que pueden ver y que tienen la vida y al Espíritu,
el velo se mantiene y aún permanecen en el cautiverio y esclavitud del enemigo.

=== Algunas Preguntas y Respuestas

[.discourse-part]
Pregunta: ¿No son los diez mandamientos, expresados en Éxodo 20,
morales y por lo tanto perpetuos?

[.discourse-part]
Respuesta:
El pacto que Dios hizo con los judíos en el Monte Horeb
cuando salieron de la tierra de Egipto no iba a ser perpetuo,
pero iba a abrirle paso al pacto, sacerdocio, legislador y ley que sí lo iban a ser.
La ley dada a Moisés no perfeccionó, era una continua acta de decretos contra los judíos.

Bien, este pacto anterior no iba a permanecer, pero le daría paso a otro pacto (Heb.
8). Que Dios hablara de un nuevo pacto implica que Él mismo dio por viejo al
primero (8:13). El primero tuvo una larga continuidad entre el pueblo judío,
pero ahora, en vista de la venida de Cristo, quien es Mediador de un mejor pacto (8:6),
es decir, de un nuevo pacto (8:8),
eso que había estado por mucho tiempo decayendo y
envejeciendo quedó listo para desaparecer (8:13).

En verdad era necesario que desapareciera pues no era sin defecto.
¿De qué manera no era sin defecto?
¿Había algún pecado en la santa ley y ministración de Dios por medio de Moisés?
¿Puede ser hallada alguna culpa en algo que procedía del Señor? En efecto,
el ministerio de Moisés fue santo y sin culpa, pero era débil debido a la carne.
(Rom.
8:3) Por tanto, Dios deseaba hacerlo a un lado,
pues era débil y apropiado para la debilidad del pueblo carnal,
y en su lugar traer el ministerio de la ley en el Espíritu, el cual sería vivo,
poderoso y eficaz en los espíritus de Su pueblo.

Ahora,
el propósito de Dios de tener un pacto era que Él y Su pueblo se mantuvieran unidos.
Sin embargo, el primer pacto fue débil en relación al pueblo; ellos no continuaron en él,
por tanto, según ese pacto, Dios se desentendió de ellos.
(8:9) Al hallar que ese pacto no era capaz de efectuar
Su propósito de amor hacia Su pueblo,
Dios no queda satisfecho y saca a la luz otro pacto, o segundo pacto,
al que el primero le da paso.
(8:7) Este otro pacto o nuevo pacto no es como el viejo.
¿En qué sentido no es como el viejo?
No fue escrito en el exterior como el primero.
"`No como el pacto que hice con sus padres el día que los tomé de la mano para
sacarlos de la tierra de Egipto`" (8:9). "`Pondré mis leyes en la mente de ellos,
y sobre su corazón las escribiré`" (8:10). Ahí todos aprenderán el conocimiento de Dios;
todos,
desde el menor hasta el mayor (8:11). "`Y todos tus
hijos serán enseñados por Jehová`" (Isa.
54:13) y aprenderán la ley de Su boca.
Este no es como la ley dada en el Monte Sinaí (cuya
ministración era para los hijos del antiguo pacto),
sino como la ley que sale de Sión y de la "`Jerusalén que es de
arriba,`" la cual es madre de todos los hijos del nuevo pacto.

Por tanto, observen diligentemente las siguientes cosas en el temor del Señor:

[.numbered-group]
====

[.numbered]
_Primero:_ Los diez mandamientos dados mediante Moisés en el Monte Horeb,
fue el pacto que hizo Dios con los judíos cuando los tomó
de la mano para sacarlos de la tierra de Egipto.

[.numbered]
_Segundo:_ Dios no quedó satisfecho,
pues este pacto no era capaz (debido a la debilidad
de la carne en ellos) de guardarlos para Él.

[.numbered]
_Tercero:_ Dios provee un nuevo pacto en la venida de Cristo, un mejor pacto,
del cual Cristo es el mediador.
Este pacto no es externo, como el anterior, sino interno, puesto en la mente,
escrito en el corazón. Así como el pueblo es interior, el santuario es interior,
el arca es interior, las tablas del pacto son interiores,
así es el pacto y la escritura del mismo.
Dado que este pacto sólo está escrito en el Espíritu y en lo que es espiritual,
no puede ser leído en la letra.

[.numbered]
_Cuarto:_ Adonde quiera que este nuevo pacto llegue, el otro se envejece,
sea que llegue a una persona o a un pueblo.
Adonde quiera que la ley del Espíritu de vida se manifieste,
la ley de la letra es sorbida en ella y desaparece,
excepto cuando es entendida y generada en la ley del Espíritu.
El que está en el Espíritu y ha recibido la ley de vida del Espíritu,
no conoce a Cristo según la carne y mucho menos a Moisés. No obstante,
todo el ministerio de Moisés (no sólo los diez mandamientos,
sino todos los sacrificios y otros tipos también) es reconocido y recibido aquí,
es decir, es reconocido y recibido en Cristo, la sustancia.
Pero los diez mandamientos, puesto que eran una sombra, pasan ante el Sol de justicia,
así como los otros tipos y sombras de la ley.

====

[.discourse-part]
Objeción: Pero, ¿había algo en los diez mandamientos que era sombra?
¿No demandan todos ellos cosas que permanecen para siempre?

[.discourse-part]
Respuesta:
El ministerio de Moisés (tal como estaba en la letra externa) no fue sino
una sombra de la plenitud y perfección del ministerio del Espíritu que
iba a venir y a ser establecido por el Hijo en Su casa.
(Heb.
3:5,6) El pueblo de Moisés no fue sino una sombra del pueblo espiritual.
Los sacerdotes y los sacrificios de Moisés no fueron sino
una sombra de sacerdotes y sacrificios espirituales.
La ley de Moisés en la letra ministrada desde el Monte Sinaí no fue sino una sombra
de la ley de Cristo en el Espíritu ministrada desde el Monte Sión. (2 Cor.
3:10,11) La ley misma que fue dada por Moisés no fue sino
una sombra de la gracia y verdad que vendrían por Jesucristo.
(Juan 1:17) Ahora miren particularmente en los diez mandamientos
y vean si no aparece algo de una sombra en ellos.

El primer mandamiento para ese pueblo es,
que no debían tener otros dioses (como los paganos),
sino únicamente a Aquel cuyo poderoso brazo los había sacado de Egipto.
Esta es una sombra de la sujeción interior del Israel espiritual al Señor de los espíritus,
por cuyo poderoso brazo los redimió del Egipto espiritual.

El segundo mandamiento dice,
que no debían hacer imágenes o semejanzas de cosas en los cielos o en la tierra,
o inclinarse ante ellas.
¿No es esta una sombra de lo que Dios demanda al Israel espiritual en el hombre interior?
Las imágenes talladas e ídolos externos hablan de todas las semejanzas, inventos,
imitaciones,
imaginaciones y semblanzas de lo que el hombre ha visto en el Espíritu arriba,
u observado abajo en la naturaleza terrenal.
Estas no deben ser hechas por ellos, ni inclinarse antes las hechas por otros.

Que no debían tomar el nombre del Señor en vano,
¿no es esto una sombra de las pretensiones que hace el hombre al poder vivo de Dios,
cuando Dios mismo no se manifiesta en ellos?
¿No pretende el hombre hoy reunirse en el nombre vivo y adorar en el Espíritu,
cuando de hecho han fornicado y huido de ese nombre y ahora son extraños
para él? ¿Debo mencionar algo más? Es fácil observar la manera en que
los otros mandamientos eran sombras externas de inocencia y pureza interna,
las cuales recibe el creyente internamente en su corazón por la
poderosa operación de la ley del Espíritu de vida en él.

[.discourse-part]
Objeción: ¿Se nos permite ahora romper esas leyes?
Si no pueden ser quebrantadas, entonces son perpetuas.

[.discourse-part]
Respuesta:
La razón por la que no pueden ser quebrantadas no
es porque la dispensación de ellas siga en vigor,
sino porque la dispensación de la ley del Espíritu abarca y cumple toda
la justicia de la ley de Moisés. Cristo disuelve ese pacto no para que
alguien tenga la libertad de hacer las cosas que se muestran injustas,
sino para que la justicia descrita en la ley se cumpla
en los que reciben la ley del Espíritu de vida.
(Rom.
8:4) Observen esto atentamente:
La ley del pecado está más cerca de nosotros de lo
que cualquier ley de la letra pueda llegar a estarlo.
El pacto de muerte e infierno está escrito por el dedo de Satanás adentro.
Por lo tanto, lo que borra este pacto debe estar muy cerca, es decir,
debe ser un pacto interior,
la escritura interior que proviene de la Palabra eterna
en el corazón mediante la ley de Su eterno Espíritu de vida.

Esta es entonces mi respuesta:
La ley de Moisés permanece en sustancia cuando es acogida
por medio de Cristo y administrada por Él en Espíritu.
No permanece tal como le fue dada en la letra a los judíos,
pues esa forma era una sombra, no perfeccionaba nada.
El pacto de la letra abrió el camino para una mejor esperanza,
para el pacto establecido sobre mejores promesas,
para la ley interior del Espíritu de vida en Cristo Jesús.
Esto efectivamente afecta los espíritus del pueblo de Dios,
lo que la ley de Moisés no pudo hacer de ninguna manera.

[.discourse-part]
Pregunta: ¿Cuál es la sustancia de la ley que permanece?

[.discourse-part]
Respuesta: La sustancia de la ley es el amor:
Amar a Dios por encima de todo (por encima de todo afuera,
y por encima de todo adentro) y amar al prójimo como a uno mismo.
Recibir este amor de Dios y ponerlo de manifiesto
en Su Espíritu es la sustancia de la ley;
a esto apuntaba la ley en sombra.
La ley es cumplida en esta única palabra: Amor.
No obstante, dicho amor debe ser recibido de Dios, Quien cumple la ley.
Un hombre puede esforzarse en amar abundantemente, puede esforzarse en obedecer en amor,
y aún así quedar corto del pacto,
porque el Señor debe circuncidar primero el corazón
antes de que el amor que cumple la ley pueda brotar.
(Deut.
30:6)

[.discourse-part]
Pregunta: ¿No es el propósito del cuarto mandamiento,
"`Acuérdate del día de reposo para santificarlo,`" persuadirnos
a dejar de lado nuestro empleo un día de siete,
para que podamos en dicho día estar completamente entregados a esperar en el Señor?

[.discourse-part]
Respuesta:
El alcance y propósito del cuarto mandamiento era ordenarle a los
judíos que guardaran estrictamente el día de reposo como una señal,
que se abstuvieran de toda obra y que lo santificaran como
un día de reposo para el Señor de acuerdo a la ley.
(Eze.
20:12) Sin embargo, habiendo llegado la sustancia (Cristo, quien es el cuerpo, Col.
2:17) y siendo experimentados el día y el reposo del Espíritu,
la señal ha llegado a su fin, y la sustancia ha tomado su lugar.
Así que ahora el reposo está en Cristo a través de la fe, por medio de Su Espíritu,
donde también está la adoración. En el evangelio esto abarca el tiempo de adoración,
el lugar de adoración y la adoración misma (todo lo cual es espiritual).
En Cristo la sustancia todo es conocido, disfrutado y celebrado,
lo cual sólo fue testificado en las sombras bajo la ley.
La santificación ha llegado, el reposo ha llegado, el Señor del día de reposo ha llegado,
¿no pasará la señal de la santificación, la señal del reposo?
(Éxo. 31:13)

[.discourse-part]
Pregunta: Nuestro Señor dice en Mateo 5: "`...hasta que pasen el cielo y la tierra,
ni una jota ni una tilde pasará de la ley.`"
Si Él aquí no se refiere a la ley de los diez mandamientos,
¿a cuál ley está haciendo referencia?

[.discourse-part]
Respuesta:
Con la palabra "`ley`" está haciendo referencia a la totalidad del ministerio de Moisés,
(ver. 18) y con la palabra "`profetas`" a la totalidad
del ministerio de los profetas (ver. 17). Así,
pues, Cristo no sólo incluye los diez mandamientos,
sino también la totalidad del ministerio de Moisés. Dijo que ni
una jota ni una tilde iban a pasar hasta que todo fuera cumplido,
es decir,
que iban a permanecer firmes en la letra para los
judíos hasta que se cumpliera el tiempo.

"`La ley y los profetas eran hasta Juan,`" y desde
ese momento el reino de Dios comenzó a ser predicado.
(Luc.
16:16) Entonces, tanto la ley, los profetas y Juan mismo debían decrecer,
y Cristo y Su reino crecer.
En el capítulo 5 de Mateo, Cristo predicó el reino y declaró a quiénes pertenecía. Ahora,
ese tipo de predicación podría haber parecido una
desviación de la ley de Moisés y de los profetas,
cuya doctrina y dispensación parecía que podían ser destruidas por Cristo.
No obstante,
Él elimina la posibilidad de tal malentendido diciéndoles que no
piensen que Él había venido a destruir la ley o los profetas;
pues Él no había venido a destruir, sino a cumplir.
En consecuencia, vemos que Cristo hace estas dos cosas:

_Primero_ establece el ministerio de la ley y los profetas para su tiempo,
hasta que fuera cumplido por Él, la sustancia;
por Aquel que debía cumplir toda la justicia de la ley.
Ella debía permanecer la totalidad de su día y no fallar
en una sola tilde (como Él mismo explicó en Luc.
16:17), hasta que el cielo y la tierra de los judíos pasaran.
(Heb.
12:27,28)

_Luego_ toma la sustancia de la ley en Su propio ministerio, y la coloca más interna,
cerca y principalmente sobre los espíritus de Sus discípulos,
más que lo que había hecho Moisés en la letra sobre sus discípulos.
En Mateo Él no lo explica completamente,
pero les da a sus discípulos una probadita de cuán directamente
les ministraría la sustancia mediante Su Espíritu,
en la medida que estuvieran bajo Su yugo (Mat.
11:29). Dicho yugo es el Espíritu de la ley,
así como el yugo de Moisés era la ley de la letra.

Noten además, que Cristo no divulga Su ley en letra, como fue entregada por Moisés,
pero requiere algo de Sus discípulos que incluye la letra.
Por ejemplo, cuando Él administra la ley contra la venganza,
de donde se origina el asesinato, no dice:
"`No matarás,`" como les había dicho Moisés en el pasado.
En su lugar dice: "`No se enojarán sin causa,
no le hablarás a tu hermano con lenguaje provocador`" (Mat.
5:22). Tampoco dice:
"`No cometerás adulterio,`" sino "`No mirarás con lujuria
ni dejarás que entren pensamientos lujuriosos`" (Mat.
5:28).

Si Cristo hubiera hablado del día de reposo, ¿lo habría administrado en la letra?
O, ¿habría ordenado guardar el verdadero día de reposo, en el que ninguna obra es hecha,
ningún fuego encendido y ninguna carga llevada,
sino que cada criatura descansa en la Semilla?
"`El Hijo del hombre es el Señor del día de reposo.`"
Es cierto que Él se sometió a la ley, pero Él seguía siendo el Señor. Hace todo Suyo,
reyes y sacerdotes para Dios, a los que habiendo sido bautizados en Su muerte,
ahora conocen Su resurrección y reinado.

[.discourse-part]
Pregunta:
Si la venida de Cristo en la carne y Su cumplimiento de toda la justicia de la ley llevó
a su fin la ley en la letra y se le promulgó otra ley a la casa de Cristo,
¿qué es, entonces, esta nueva ley?
Y, ¿es contraria a la ley escrita?

[.discourse-part]
Respuesta: Es la ley del Espíritu, o la luz del Espíritu en el corazón,
la cual descubre el pecado (no sólo en los actos externos, sino en su fuente,
levantamiento,
primeros movimientos y naturaleza interior) promulgando Sus mandamientos vivos
contra él. Esta es ahora la ley en la que el creyente tiene que comenzar (Gal.
3:3),
y según la cual tiene que continuar hacia la perfección. Pues como
el creyente es engendrado por el Espíritu y nacido del Espíritu,
tiene que recibir la ministración de Su ley desde el Espíritu y en el Espíritu.
Él recibe un don de fe, una medida de fe de la eterna fuente de vida, y esa es su ley.
Su ley es la ley de la fe.
La luz de la vida que recibe en la fe,
le revela la mente y la voluntad de Cristo en el Espíritu,
mostrándole tanto el pecado como las cosas de Dios más plenamente de lo que pudo
hacerlo la ley de Moisés. Este es un tipo de ministración más pleno y más profundo,
y por eso revela las cosas que ministra más plenamente de
lo que pudo hacerlo la ministración de una naturaleza inferior.
No es contrario a la ley de Moisés, sino que reúne en sí mismo toda la sustancia,
justicia y equidad de ella (como dije antes), aquello que la ley como sombra,
representaba y le era demandado a aquel pueblo externo, o de la sombra; los judíos.

[.discourse-part]
Pregunta:
¿Por qué entonces el apóstol Santiago habla de transgredir la "`ley real,`" y amonesta:
"`Así hablen ustedes y así procedan,
como los que han de ser juzgados por la ley de la libertad`"?

[.discourse-part]
Respuesta: ¿Qué es la ley real?
¿Qué es la ley de la libertad?
¿Era la ley administrada por Moisés la ley real?
O, ¿es la ley real la que es administrada por el Hijo, quien es Rey de los santos,
y quien escribe Su ley en sus corazones como Rey de ellos?
De nuevo,
¿era la ley que ministró Moisés a los judíos una ley de libertad o de esclavitud?
¿No condujo a la esclavitud el ministerio del Monte Sinaí? (Gal.
4:24), pero en el ministerio de la ley mediante el Espíritu hay vida y libertad, (Gal.
4:26 y 2 Cor.
3:17). Esta ley: "`Amarás a tu prójimo como a ti mismo`" es real,
es una ley de pura libertad en la que no hay esclavitud
cuando es ministrada por el Espíritu.
Sin embargo,
dejen que cualquier hombre lea esta ley en la letra
y se esfuerce en obedecerla hasta donde pueda,
y la hallará débil debido a la carne, y acusándolo y esclavizándolo también.

Los cristianos ruegan en sus oraciones como personas esclavas,
porque no conocen la ley real de la libertad.
No sienten el amor que engendra el Espíritu,
sino que se esfuerzan en tener la letra escrita en sus corazones,
buscando responder a los mandamientos de la letra
con cualquier amor u obediencia que puedan reunir.
A esto le llaman obediencia en el Espíritu (por no
ver el verdadero pacto ni el ministerio de Cristo).
El testimonio de Jesús es el Espíritu de profecía. (Apoc.
19:10) Sus mandamientos vienen frescos de ese Espíritu de profecía y tenemos
que estar atentos a ellos hasta que el día despunte y el lucero se levante.
Entonces conoceremos un ministerio más pleno que el de profecía, es decir,
el brillo y la aparición de Aquello que fue profetizado.

[.discourse-part]
Pregunta: El cuarto mandamiento, el que habla de guardar el día de reposo,
¿no debe ser guardado por todos los creyentes?

[.discourse-part]
Respuesta:
Todos los mandamientos del pacto de Cristo deben ser guardados por los creyentes,
según Él se los dispensa bajo Su administración en el nuevo pacto.
Sin embargo, las leyes del antiguo pacto no son las leyes del nuevo pacto,
excepto en que están reunidas y comprendidas en la
justicia que es enseñada y requerida por el Espíritu,
la cual es más completa, estricta y exacta que la que requería la ley de Moisés.

No por eso voy a enseñarle a nadie a quebrantar el menor de los mandamientos de Cristo,
sino la manera de cumplirlos, la cual es:
Conocerlos y obedecerlos bajo el ministerio del pacto de Cristo, donde Él los escribe,
en el corazón y en la mente, mediante Su Espíritu.
De esta manera es posible guardar todos los mandamientos de Cristo.
Sí, esta es la única manera de tener la justicia de la ley cumplida en nosotros.
Porque el que mantiene fijo sobre el Espíritu el ojo que el Espíritu ha abierto,
no será capaz de quebrantar ninguna ley de justicia,
sino que la justicia de la ley de Moisés será cumplida en él.

Cristo es el verdadero reposo del evangelio (como también la tierra santa),
y entramos a este reposo al creer.
Este es el verdadero día de reposo y la manera de guardarlo.
El reposo del evangelio es guardado manteniendo la fe.
Romper con cada lujuria que Él pone de manifiesto,
acatar todo lo que el Rey pide por Su Espíritu y esperar una mayor
manifestación o resplandor de luz de Su Espíritu en el corazón,
esta es la verdadera obediencia de la fe.
Esta es la vida santa y espiritual y la sujeción del alma viva a su Rey vivo.
Este es el comienzo, crecimiento y perfección de un verdadero cristiano.
En cuanto a tiempos, lugares, personas, etc.,
estos son de otra naturaleza y pertenecen a otra parte, es decir,
a esa parte en el hombre que tiene que ser eliminada cuando entra en la fe y en el reposo.

Con fe no invalido la ley,
sino que la establezco en su ministerio en el Espíritu para los discípulos de Cristo.
Los que se mantienen en el Espíritu no pueden transgredir la justicia de la ley,
aunque pueden aprender por el Espíritu a no estimar un día por encima de otro,
sino a estimar cada día igual (ningún día ha tenido alguna
vez algo de santidad real en él por encima de otro,
sólo en sentido figurativo o representativo, el cual es consumido por Cristo,
la sustancia).
Porque cuando el día de Cristo amanece,
aquellas cosas que eran sombras de ese día desaparecen.

[.discourse-part]
Objeción:
¿No es peligroso mantener un día de reposo espiritual y negar el
sábado semanal en el que nuestro Señor Jesucristo reposó,
al cual también el Señor bendijo y santificó para Adán y su posteridad?

[.discourse-part]
Respuesta: El evangelio es un estado de sustancia,
un estado de cumplimiento de los tipos y sombras de la ley que
lleva a los creyentes a la posesión de aquello que estaba señalado.
Canaán era un tipo de Cristo, Quien es la tierra de los vivos,
y en Quien cada creyente tiene una habitación de acuerdo a la proporción de su fe.
Ahora el verdadero día de reposo es el día que cada
creyente debe celebrarle a Cristo en esa tierra santa,
lo cual hace al creer y obedecer a Su Espíritu en la fe que lo mantiene fuera del pecado,
la incredulidad y sus obras.
No conozco ninguna escritura que enseñe la idea de que el día de reposo de la ley,
y el resto de la misma que apuntaba a la fe,
deba guardarse aún en el tiempo del evangelio.
Pero yo conozco algo que me enseña lo contrario.
El día ha amanecido, ¡bendito sea el Señor Dios Todopoderoso!
El eterno día ha amanecido y las sombras de la ley han desaparecido.

[.discourse-part]
Objeción: ¿No habla Hebreos 4 de tres reposos?
¿El séptimo día,
el reposo de Israel en Canaán y el reposo que queda del que habla David en el Salmo 95?

[.discourse-part]
Respuesta: Concedo eso.
Había dos reposos bajo la ley que eran señales de uno bajo el evangelio.
Los dos bajo la ley eran externos y naturales;
el reposo bajo el evangelio es interno y espiritual,
consistente con el estado del evangelio.
David no sólo estaba familiarizado con el estado de la ley,
sino también con el Espíritu y con la ley eterna en el Espíritu.
Él conocía la nueva creación, la creación de un nuevo espíritu,
y también la de un nuevo reposo.
Él conocía la circuncisión del corazón,
los sacrificios espirituales de un corazón quebrantado y de alabanza.
Él pudo tomar la copa de la salvación y cantar la canción de alabanza al Señor,
algo que nadie puede hacer en tierra extraña ni en
ningún otro día que no sea el día de reposo.
Él invita a Israel a este reposo,
y a que no endurezcan sus corazones contra dicho reposo, sino a que entren en él,
durante el día de su visitación al oír la Palabra,
la cual estaba cerca de ellos y les da entrada a través de la fe.
"`Si oyereis hoy su voz, no endurezcáis vuestros corazones.`"

Hay un reposo al que ustedes son llamados ahora a entrar,
así como fueron llamados sus padres a entrar a la tierra de Canaán. Por lo tanto,
no endurezcan sus corazones como lo hicieron ellos, sino oigan la voz,
oigan la palabra que los llama a este reposo, crean y entren.
Este reposo permanece, dice el apóstol,
los otros sólo fueron tipos de éste bajo el estado de la ley, los cuales iban a pasar.

Ahora bien, la entrada a la plenitud del reposo no es inmediata,
hay un largo camino que recorrer de Egipto, la tierra de oscuridad, de Sodoma,
la tierra de inmundicia, de Babilonia,
donde todos los vasos y las cosas santas de Dios han sido profanadas,
a través del desierto hasta Canaán. Muchas batallas deben ser peleadas contra
los enemigos por el camino y contra los enemigos que poseen la tierra santa.
Muchos sufrimientos deben ser padecidos siguiendo al Capitán,
quien también guía a Su Israel por medio de una columna
de nube en el día y una columna de fuego en la noche.
Deben haber una circuncisión y un bautismo en la nube y en el mar,
la caída en el desierto de todos los cadáveres que no deben entrar ni ver la buena tierra,
antes de que la entrada sea ministrada a la Semilla,
y a eso que cruza el agua y el fuego con la Semilla.
En términos sencillos, debe tomarse el yugo y aprender a Cristo bajo el yugo,
hasta que el espíritu orgulloso, terco, sabio, voluntarioso y egoísta,
y el corazón duro como piedra sean consumidos y desgastados por la cruz.
Nada debe ser dejado excepto lo que se hace uno con la Semilla;
y así es apto para casarse con la Semilla y para entrar con ella al reino eterno.

Ahora, este llevar el yugo, este tomar la cruz,
este seguir a Cristo en el desierto a través de las correcciones del Padre,
a través de las bofetadas y tentaciones del enemigo,
en medio de todas las debilidades y flaquezas de la carne, andar cuando Él dirige andar,
quedarse quieto cuando Él se detiene, pelear cuando Él se prepara para la guerra,
llevar el oprobio cuando Él permite que el enemigo prevalezca,
esperar "`en esperanza contra esperanza`" Su alivio y victoria a su debido tiempo,
_este_ es el trabajo, el esfuerzo laborioso como de parto, la obra bajo el yugo de la vida,
con la medida de gracia y poder recibida de la vida.
Entonces, primero hay una visita desde lo alto de la aurora,
y de esa visitación es introducida luz en el corazón,
y al estar de acuerdo con dicha luz, se recibe gracia.
Al hacer uso de esa gracia recibida hay una obra por hacer para Dios,
porque Su talento debe incrementarse durante los seis días
en aquellos que reposarán con Él en el séptimo,
y en todo aquel que desea cesar de sus labores en el cumplimiento de la fe,
la vida y el poder (Su poder viviendo,
convirtiendo y realizando todas las cosas en ellos).
El que no incremente el talento o no siga adelante en la luz pura,
sino que se sienta en el camino o se engaña con una
imagen de lo que una vez fue cierto en él,
no podrá entrar a la tierra del descanso; y cuando el Testigo eterno se despierte en él,
el tal hallará la ausencia de la tierra del descanso
y amargamente llorará su grave error.

[.discourse-part]
Pregunta: ¿Qué contiene el nuevo pacto o pacto del evangelio?

[.discourse-part]
Respuesta: Dios pone Su temor en el corazón, escribe Su ley en la mente,
derrama agua pura y clara para lavar la contaminación del interior,
circuncida la inmundicia del corazón,
sana la naturaleza apóstata mediante la creación de un espíritu recto adentro y guarda
al espíritu recto creado por medio de la presencia del Espíritu que lo creó. (Ver Jer.
31:31-32; Eze.
36:25; Oseas 14:4). Este es el pacto de Dios,
este el nuevo pacto que debe ser hecho con la casa
de Israel y de Judá cuando Dios los redima,
y nunca serán redimidos excepto por este pacto.
Israel tenía que permanecer desolado hasta que el
Espíritu fuera derramado de lo alto sobre ellos (Isa.
32:15), hasta que sus corazones fueran circuncidados para amar al Señor su Dios,
hasta que Su temor fuera colocado ahí y de este modo caminaran en Sus caminos.
Cuando ellos recibieran al Espíritu, fueran introducidos en el temor,
tuvieran la ley escrita en sus corazones y fueran sometidos a ella,
así gustarían este pacto,
serían llevados a la redención por él y llegarían a ser una gloria
internamente y externamente sobre la tierra.

Consideren ahora: ¿No era este pueblo judío,
mientras estuvo relacionado con Dios en su pacto (dado por Moisés en el Monte Horeb),
junto con el pacto mismo y todas las cosas pertenecientes a él,
sombra de cosas espirituales internas que iban a aparecer
más tarde y ser hechas manifiestas en su tiempo?
¿No eran los judíos sombra de un pueblo más interior y espiritual que
iba a ser reunido con Dios mediante un pacto interno y espiritual?
¿No era su pacto externo una sombra o representación visible de dicho pacto,
y las leyes de este una sombra o representación de leyes internas
que iban a ser escritas en el corazón de ese pueblo espiritual?
¿No era su tabernáculo o templo una sombra del verdadero tabernáculo o templo,
viendo que Dios no habita en templos hechos por manos, sino en un espíritu pobre,
humilde y contrito, y en el corazón que tiembla ante Su palabra?
(Isa.
57:15;
66:1-2) ¿No era su circuncisión una sombra de la circuncisión que
tiene que pasar en los corazones de los escogidos de Dios?
¿No eran sus sacrificios tipos o representaciones de los
sacrificios de alabanza y de un corazón quebrantado?
(Sal.
51:17; 50:14) ¿No era su Canaán o tierra santa un tipo del reposo verdadero,
santo y espiritual al que la fe da entrada?
¿No era su ciudad Jerusalén un tipo de Jehová-sama?^
footnote:[Que significa "`El Señor está allí,`" Ezequiel 48:35]
¿No eran sus sacerdotes y levitas un tipo del sacerdocio espiritual que iba a
ofrecer la ofrenda pura y los sacrificios espirituales entre los gentiles?
(Mal.
1:11) ¿No predicen claramente sus Escrituras el rechazo de los judíos y sus ofrendas,
sacerdotes y levitas,
y que Dios levantaría una simiente entre los gentiles en
la que Él tendría un pueblo y una adoración más aceptable;
es decir, un pueblo puro y espiritual, y una ofrenda pura y espiritual?

Consideren en segundo lugar: Si ellos eran efectivamente tipos,
representaciones o sombras de algo espiritual por venir, entonces,
¿no tenían que darle paso a lo espiritual cuando llegara y ser sorbidos en ello?
¿No es la gloria espiritual la verdadera gloria?
¿No es el Judío interno el verdadero Judío? ¿La circuncisión
del corazón la circuncisión escogida?
¿La ofrenda de alabanza y de un corazón quebrantado el sacrificio aceptable?
¿La tierra de vida y justicia la verdadera tierra de reposo para los que viven por fe?
¿No es la ciudad,
la casa o el templo espiritual que Dios construye
la Jerusalén o el templo del nuevo pacto?
¿No es esta la casa escogida por Dios?
¿No había una expectativa de gloria espiritual en la venida del Mesías,
de que todos los tipos y sombras de Moisés (que lo apuntaban a Él) se
cumplieran en Él cuando finalmente llegara a establecer Su gloria sustancial,
verdadera, interior e invisible entre Su pueblo interior y espiritual?
Cuando el día del Mesías amanece, ¿no desaparecen las sombras de Moisés? ¡Oh,
que sus ojos sean abiertos para contemplar la gloria de la vida interior,
las cosas buenas del nuevo pacto,
el gran tesoro y las riquezas que son reveladas y poseídas en el Espíritu por los espíritus
que son redimidos para Dios! ¡Entonces sus ojos no estarían tanto sobre lo que es externo,
porque aunque poseyeran hasta el último de sus deseos de las cosas externas,
no serían comparables con las cosas internas!

Consideren por último, que cuando Moisés dio la ley, el velo estaba sobre su cara,
y los padres no pudieron soportar la luz en la que la ley fue dada,
ni la luz en la que las profecías de los profetas fueron dadas.
Por lo tanto, ellos se extraviaron de la ley,
fueron ofendidos por los profetas mientras estaban vivos,
y malentendieron sus palabras después de sus muertes.
Ahora,
¿no están ustedes escudriñando en Moisés y en los profetas en el mismo espíritu de error,
al igual que lo hicieron sus padres,
y no están siendo excluidos también de la luz de
ellos tanto como fueron excluidos sus padres?
Si esto es cierto, si el velo permanece sobre sus corazones,
si son ignorantes de la verdadera luz,
del verdadero poder eterno en el que las Escrituras fueron dadas,
¿cómo no van a malentenderlas, cómo no van a malentender a Moisés,
a los profetas y las cosas habladas con respecto al Mesías? Sin esta luz
ustedes no pueden ver el final de las cosas ministradas por Moisés,
la ministración que iba a pasar,
ni tampoco pueden ver el principio de la ministración del Mesías que estaba por sucederla.
¡Oh, vuélvanse hacia dentro, a la palabra cerca en el corazón,
para que el verdadero Judío pueda ser engendrado y formado en ustedes,
y que Su luz pueda levantarse y extenderse en ustedes!
En dicha luz ustedes verán la luz de Moisés y la de los profetas,
y no recogerán falsos significados de sus palabras,
sino que las entenderán correctamente en el mismo santo Espíritu.
En dicha luz ustedes disfrutarán las bienaventuranzas
de las que ellos hablaron y señalaron,
las cuales yacen en el levantamiento interior de una Semilla interior,
y no en una conformación externa del hombre exterior,
mientras el corazón y la mente permanecen sin cambio y sin renovación.
