[short="Capítulo X -- La Oración, el Ministerio, la Sabiduría Y el Reino"]
== Capítulo X. La Oración, el Ministerio, la Sabiduría Y el Reino que son Espirituales

=== La Oración en el Espíritu

La verdadera oración es esa respiración anhelante del niño hacia el Padre que lo engendró,
que surge de una verdadera consciencia de sus necesidades,
para la satisfacción de esas necesidades.

"`El viento sopla de donde quiere, y oyes su sonido; mas ni sabes de dónde viene,
ni a dónde va; así es todo aquel que es nacido del Espíritu.`"
(Juan 3:8) Dios, por medio del soplo de Su Espíritu,
engendra un hombre a Su propia imagen y semejanza,
fuera del espíritu y semejanza de este mundo.
El que es engendrado de esta manera necesita alimento, necesita el calor divino,
los pechos de consolación, la ropa del Espíritu,
el vestido de salvación. Necesita el pan de vida
para alimentarse y el agua de vida para beber.
Necesita fuerza contra los ataques del enemigo y sabiduría contra sus trampas y tentaciones.
Necesita el brazo del Libertador para preservar y llevar la obra de redención diariamente.
Necesita fe para negar la sabiduría carnal y para
confiar y sentir la virtud del brazo del Libertador.
Necesita esperanza, paciencia, mansedumbre,
una clara guía y un corazón recto para seguir al Señor. Ciertamente son muchas
las necesidades diarias de este niño que es engendrado por el soplo de Dios,
en estado de debilidad, hasta que es acercado a la unidad del cuerpo,
donde la plena comunión con la vida es experimentada,
el corazón satisfecho y las deficiencias ahogadas.

Esa respiración anhelante del niño hacia el Padre,
que proviene de la verdadera consciencia de estas
necesidades y hacia el suministro del Padre,
es oración. Aún cuando no sea más que un gemido o
un suspiro que no se pueda pronunciar o expresar,
es oración, verdadera oración,
la que tiene aceptación del Señor y recibe una respuesta de gracia de Él. El que engendra
al niño es el que lo enseña a orar por medio del mismo Espíritu que lo engendró. Fijar
la mirada diariamente en el Espíritu mantiene al niño sensible a la voluntad del Padre,
y en Su luz ve la manera en la que debe caminar.
También ve al enemigo que viene, las trampas que secretamente pone,
y siente su propia debilidad para resistir o escapar.
Ante esta consciencia su corazón clama al Padre de los espíritus para que lo preserve,
para que intervenga en el momento necesario y en el tiempo de angustia.
Por lo tanto, al fijar la mirada en el Espíritu,
la vida de un cristiano llega a ser un continuo fluir de oración; ora continuamente.
Esta es la oración viva del niño vivo, la cual no consiste en cierta forma de palabras,
ni leídas de un libro o concebidas en la mente,
sino en la experiencia del soplo de su naturaleza,
manando de la Semilla de vida en el interior hacia el manantial vivo,
el cual es el Padre de Ella.
Y el Padre, al hacer que Sus virtudes broten en Ella, alimenta al alma para vida eterna.

Sin embargo, son muchos los que no han nacido del Espíritu,
pero (por concebir algunas de las verdades de Dios en la sabiduría
de abajo) han logrado algún cambio de opinión y conducta.
Estos pretenden ser del nacimiento de arriba,
cuando de hecho han nacido "`de sangre,`" "`de la
voluntad de la carne`" o "`de la voluntad del hombre.`"
(Juan 1:13) Y aunque imiten las cosas que Dios engendra y le da al verdadero niño,
están fuera de la naturaleza y del espíritu donde el verdadero niño es engendrado,
y de donde el verdadero don del Padre es recibido por él. Estos seguirán creyendo
aunque no hayan recibido de la mano del Padre una porción de la fe viva.
Seguirán aparentando arrepentimiento y pesar por el pecado,
aunque sus corazones no se hayan vuelto de él. Seguirán
esperando en la misericordia de Dios,
aunque estén fuera del fundamento y de la sombra del propiciatorio.
Seguirán orando,
aunque no hayan recibido al Espíritu ni hayan sido enseñados por Él a orar.
Así, pues, por estar fuera de lo que tiene que guiarlos,
enseñarles la verdad y el camino de adoración tal como es en Jesús,
salen corriendo hacia invenciones e imaginaciones,
y establecen un camino de su propia elección. Y habiéndole
dado mucho pensamiento a su propio camino,
habiéndolo formado por medio de razonamientos y cercado con argumentos,
crecen sabios ante sus propios ojos y en verdad creen que ese es
el camino de Dios y que pueden mantenerlo contra todos los opositores.

Así pues, un hombre apoya una forma en particular de oración y adoración,
otro hombre está en contra de esa forma, y en su lugar apoya o insiste en otra.
Cada uno se cree capaz de mantener su propia perspectiva y derrocar la otra.
¡Pero oh, si el oído fuera abierto para oír la verdad!
Si sólo hubiera un deseo verdadero, honesto y recto en pos de Dios,
que brotara de la sencillez del corazón,
entonces el hombre no sería fácilmente traicionado por la sutileza de la sabiduría carnal,
la que acecha en la sabiduría y razonamiento del hombre con el
fin de traicionar al pobre y débil bebé. El hombre natural,
el hombre racional, el hombre intelectual, el hombre sabio según la sabiduría natural,
no puede entender las cosas de Dios.
En la sabiduría y entendimiento del hombre no hay forma de aprender a orar correctamente,
a creer correctamente, a esperar correctamente, a llorar correctamente,
a regocijarse correctamente, etc.
Tal sabiduría tiene que ser reducida a nada (1 Cor.
1:19), y el hombre tiene que llegar a ser como un niño a todo conocimiento,
para poder conocer el camino de Dios.
El que llega a ser como un niño es enseñado a orar, a creer, a esperar,
a tener esperanza y a todo lo que es necesario para la vida eterna.

Conforme el Padre enseña a orar,
así da deseos o palabras (si le place) de acuerdo a la necesidad presente.
A veces da la habilidad de suspirar o gemir (y si no da más, Él acepta eso).
A veces da fuertes respiraciones y muchas palabras
para derramar el alma delante del Señor. Sin embargo,
si un hombre oyera y recordara esas palabras,
las guardara para otro momento y se las ofreciera a Dios en su propia voluntad,
esto no sería más que "`adoración de la voluntad`" y abominación. Esto
lo conozco por experiencia y he sentido la ira de Dios por ello.
La oración es lo que brota fresco del Espíritu y
el verdadero deseo es el que engendra el Espíritu,
pero los afectos y las chispas del propio fuego del hombre
no agradan al Señor ni conducen al alma al reposo,
todo lo contrario, terminará en el lecho de dolor.
(Isa.
50:11)

Con respecto al uso del Libro de Oración en Común,
o las oraciones concebidas en la mente sin las respiraciones directas del Espíritu,
hablaré de mi propia experiencia fielmente:
He experimentado que dichas oraciones sacan de mí la parte equivocada
y mantienen vivo en mí lo que la verdadera oración mata.
Aquel que pronuncia una palabra más allá de la consciencia que Dios engendra en su espíritu,
toma el nombre de Dios en vano y Lo provoca a celos contra su propia alma.
"`Dios está en el cielo y tú sobre la tierra; por tanto,
sean pocas tus palabras`" (Eclesiastés 5:2). Las pocas palabras que el Espíritu habla,
o las pocas, suaves y apacibles respiraciones que el Espíritu engendra,
son agradables para Dios y provechosas para el alma.
Pero las muchas palabras que la sabiduría del hombre concibe hieren
la preciosa vida y engrosan el velo de muerte sobre el alma,
manteniendo vivo eso que la separa de Dios y que
tiene que morir para que el alma pueda vivir.

La verdadera oración viene mediante eso que Dios engendra en la
virtud de Su Espíritu ("`oren siempre en el Espíritu,`" Ef. 6:18;
Jud.
20) y en el momento que Él escoge.
Pues el Espíritu sopla cuando quiere y donde quiere,
y el hombre no puede limitar cuándo soplará o cuándo no soplará,
sino que debe esperar el momento del soplo del Espíritu y así "`velar en oración.`"

Ahora bien, si la oración es en palabras (porque hay oración sin palabras),
entonces debe ser en las palabras que al Espíritu le place dar,
desde la consciencia que Él enciende y no en las palabras
que la sabiduría del hombre enseña o escogería usar.
En efecto, en la verdadera religión y en todo ejercicio de ella,
la sabiduría del hombre es mantenida fuera y clavada en la cruz,
por lo que la vida inmortal es levantada e incrementada en el verdadero discípulo.
Este cree, tiene esperanza, espera, ora, llora, se regocija, obedece, etc.,
permaneciendo en la cruz para la parte mortal.
Él hace estas cosas no como enseña la sabiduría del hombre,
pues su sacrificio al Señor todavía es abominación,
incluso para la parte sabia y egipcia en él (Éxo. 8:26),
sino que lo haga todo como enseña la vida, como enseña la sabiduría de arriba,
la sabiduría que rompe, calla,
confunde y destruye la sabiduría del hombre mientras Dios le enseña a Su bebé.

=== El Ministerio en el Espíritu

No es predicar cosas verdaderas lo que hace que un ministerio sea verdadero,
sino recibirlo del Señor. El evangelio es del Señor y tiene que ser predicado,
pero tiene que ser predicado en Su poder,
y los ministros que lo predican tienen que estar dotados de Su
poder y ser enviados por Él. Los apóstoles habían recibido instrucciones
con respecto al reino de los propios labios de Cristo,
tanto durante Su vida como después de Su resurrección (Hech.
1:3), y habían recibido de Él la comisión de enseñar a todas las naciones.
(Mat.
28:18) Aún así,
esto por sí solo no era suficiente para hacerlos ministros competentes del Nuevo Pacto,
pues antes de que fueran a predicar al extranjero,
recibieron la instrucción de esperar el poder.
(Hech.
1:4,8) Luego, habiendo recibido el poder, tenían que ministrar en él,
para que los hombres se convirtieran en el poder y por el poder,
de manera que su fe no se fundamentara en la sabiduría
de sus palabras (la cual pudo haber abundado en Pablo,
así como en otros), sino en el poder de Dios.
(1 Cor.
2:5) Sabiendo esto, Pablo ministraba con temor y temblor,
para que no ministrara la parte equivocada en él,
para que la parte del entendimiento terrenal no hablara
las verdades de Dios fuera de la vida,
fuera del poder, y que por eso,
los hombres se convirtieran a la sabiduría de las
palabras que él decía y no al poder de Dios.
(1 Cor.
2:
2-3) Pablo fue enviado por el Señor para que los hombres se volvieran
"`de las tinieblas a la luz y del poder de Satanás a Dios`" (Hech.
26:18); del espíritu de enemistad y muerte, al Espíritu de amor y vida.
Así que tuvo mucho cuidado en su ministerio para que los hombres
no corrieran con sus palabras y se perdieran la sustancia.
Esta era también la manera por la que descubría a los verdaderos o falsos ministros:
"`Pero iré a verlos pronto...y conoceré, no las palabras de los arrogantes,
sino el poder.
Porque el reino de Dios no consiste en palabras, sino en poder`" (1 Cor.
4:19-20). Muchos hombres podrían coger las palabras de los apóstoles,
correr con ellas y predicarlas, pero no podrían ministrar en el poder.

Ahora bien, el reino, cuyo evangelio predican los ministros,
no consiste en palabras sino en poder.
Dios "`nos hizo ministros competentes de un nuevo pacto, no de la letra,
sino del Espíritu.`"
(2 Cor.
3:6) El ministerio del Nuevo Pacto es el ministerio
del Espíritu y no puede existir sin el Espíritu.
Dicho ministerio alcanza la consciencia de los hombres
"`con demostración del Espíritu y poder`" (1 Cor.
2:4; 2 Cor.
4:1-2), y cuando el corazón lo siente y se vuelve a ello, el hombre es convertido a Dios.

El ministerio del evangelio no consiste en un simple
abrir la letra como hizo el ministerio de la ley,
o en levantar doctrinas y costumbres a partir de la letra,
que la sabiduría del hombre pueda fácilmente realizar.
Más bien consiste en llevar a los hombres a la experiencia del Espíritu, es decir,
a la experiencia del eterno poder de Dios que redime,
volviendo a los hombres de las tinieblas a la luz y colocando sus rostros hacia el poder.
El evangelio es la sustancia de lo que estaba en sombra en la ley,
y el que lo ministra tiene que ministrar sustancia.
Este tiene que tener el tesoro celestial (que es
la sustancia) en su vasija terrenal (2 Cor.
4:7) y dar de este tesoro a la vasija que Dios prepara.

A fin de hacer esto, el ministro tiene que ministrar en el Espíritu y en el poder.
Sus palabras no pueden ser las que la sabiduría del hombre
enseñaría o como las que la comprensión del hombre reuniría,
sino las que la sabiduría de Dios prepara para él y pone en su boca.
El que quiere ser un verdadero ministro tiene que recibir del Señor
tanto su don y ministerio como el ejercicio de ambos,
y tener cuidado en su ministración para mantenerse
en el poder o nunca ganará a otros para el poder.
Manteniéndose en el poder,
tiene que ministrar crucificado a su propio entendimiento y sabiduría,
exponiendo las verdades que el Señor escoge que hable y en las palabras que Dios escoge;
es decir, en las palabras que son ministradas a él por el poder.
Ministrando de esta manera salvará su propia alma y las almas que lo oyen;
salvará a todos los que en temor y mansedumbre reciben la
palabra implantada que es capaz de salvar el alma.

¡Por desgracia,
muchos han recibido palabras de verdad y una sensación
de conocimiento mediante lo cual esperan ser salvos,
pero cuán pocos están familiarizados con el conocimiento
que se encuentra en el poder de Dios,
el único que convierte y mantiene vivo para con Dios! ¡Oh,
por cuántas almas tendrán que responder aquellos
que tomaron sobre sí ser pastores de Dios,
que han alimentado al rebaño con palabras y discursos hechos por ellos,
que han gobernado sobre ellos con fuerza y crueldad, pero han carecido del amor,
la ternura,
la luz y el poder del verdadero Pastor! ¿Qué van a hacer
estos cuando Dios demande Sus ovejas de sus manos?
¡Ojalá haya en ustedes un corazón que reflexione, pastores de Inglaterra!

Mediante Su ministerio Cristo llama a Sus discípulos a salir del mundo hacia el Padre,
a salir del honor, de las riquezas y de todo lo que es del mundo.
"`¿Cómo pueden creer, cuando reciben gloria los unos de los otros,
y no buscan la gloria que viene del Dios único?`"
(Juan 5:44) Al hombre rico le dice "`vende todo y sígueme.`"
El apóstol Juan dice: "`No amen al mundo ni las cosas que están en el mundo.
Si alguien ama al mundo,
el amor del Padre no está en él. Porque todo lo que hay en el mundo,
la pasión de la carne, la pasión de los ojos, y la arrogancia de la vida,
no proviene del Padre, sino del mundo.`"
(1 Juan 2:15-16) Aquel que quiere ser discípulo de
Cristo tiene que viajar de lo terrenal a lo celestial,
dejar atrás todo lo que es de este mundo y no poseer nada como
propio a excepción de Aquel que lo ha llamado a salir de su tierra,
de su parentela y de la casa de su padre, para ir a otra tierra,
a otra parentela y a otra morada.
Así, pues, aquí los discípulos son peregrinos y extranjeros, forasteros y pasajeros,
desconocidos para el mundo y de una extraña vestimenta, comportamiento y apariencia.
Estos no disfrutan nada como lo disfruta el mundo, ni usan nada como lo usa el mundo.
No honran a los hombres ni reciben honor de los hombres como el mundo da o recibe honor,
sino que honran a los hombres en el Señor y reciben honor del Señor.
Y en lo que parece que retienen de las cosas terrenales,
se mantienen como mayordomos bajo el Señor,
no usándolo o disponiendo de eso como bien les parece,
sino esperando que el Maestro revele Su voluntad,
Quien lo ordena todo en Su consejo y sabiduría para Su propia gloria.
La ley requería que una décima parte fuera ofrecida al Señor,
el evangelio lo requiere todo: El alma, el cuerpo, el espíritu, el buen nombre, etc.,
es decir, que la totalidad de la posesión sea vendida y puesta a los pies del Maestro.
El que retiene algo no puede ser un discípulo, no puede ser un soldado de Cristo,
porque necesariamente se enredará en los negocios de esta vida.

El Señor circuncida el corazón de los creyentes bajo el nuevo pacto,
para que amen al Señor Su Dios con todo su corazón y puedan vivir.
Él hace que la planta brote de la tierra seca y estéril,
la que Él riega con Su bendición,
y pone Su hacha a la raíz del árbol viejo trozándolo hasta que lo ha cortado.
Él implanta la Palabra Eterna en el corazón y por medio de Ella
diariamente purifica y continúa la obra de fe con poder.
El ministerio que Él dio era para "`perfeccionar a los santos`" (Ef. 4:12-13),
el cual exhortaba y animaba a los creyentes (a partir de las promesas de Dios
de Su presencia y poderosa acción de Su Espíritu en los corazones de sus hijos
e hijas) para que se limpiaran "`...de toda inmundicia de la carne y del espíritu,
perfeccionando la santidad en el temor de Dios`" (2 Cor.
7:1).

=== Sabiduría Espiritual

Conocer a Cristo como la luz eterna (como era Él ayer, es hoy y será para siempre),
confiar en esta luz, en sus convicciones, llamadas y revelaciones de amor,
experimentar su virtud viva y en dicha virtud rendir
todo lo que es de la naturaleza y del espíritu terrenal,
venderlo todo en pos de la herencia eterna es, en verdad, el camino a la vida.
Hacer cosas no es de valor en sí mismo,
pues el hombre puede imitar y esforzarse para hacer mucho,
y puede recorrer un gran camino para abandonarlo todo y despojarse
de sus afectos por las cosas (al punto de "`dar todos sus bienes
a los pobres y su cuerpo para ser quemado,`") y aún así,
no ser de provecho para él. Pero hacer cosas en la virtud,
en la vida y en el poder que provienen de Cristo,
es lo que tiene aceptación para Dios y es de ventaja para el alma.
Cada movimiento y operación de la verdadera vida brota de
la raíz de vida y tiene la virtud de la raíz en ella.
Lo que diferencia los movimientos y operaciones de la verdadera vida de todas las imitaciones
de los hombres y de todas las semejanzas que el espíritu terrenal pueda poner por delante,
es la manifestación de la naturaleza y virtud de la raíz de vida.
Por lo tanto,
el que quiere ser un verdadero cristiano tiene que fijar sus ojos en Cristo,
la fuente de su vida,
tiene que mantenerse en el sentimiento y experiencia de Su virtud viva,
y en esto ofrecer todos sus sacrificios de fe, amor y obediencia a Dios.
El que quiere ser un verdadero ministro tiene que esperar el poder sobre él,
para ser un instrumento (en la mano de poder) para dirigir
a los hombres a esto y preservarlos y edificarlos en ello.

¡Desgraciadamente, esta es la piedra que los constructores peritos han rechazado siempre!
Los constructores antes de la venida de Cristo tenían
un conocimiento con respecto al Mesías por venir,
pero al desconocer la cosa misma,
rechazaron tanto Su venida como la vasija en la que apareció. Los constructores
durante toda la apostasía han tenido un conocimiento del Cristo ya venido,
y han predicado creyendo en Él crucificado y como el camino a la vida,
pero de la piedra viva, de la cosa viva misma, la cual es tanto el fundamento,
la piedra angular, como la piedra superior del edificio,
de ella han sido ignorantes y han estado listos para
perseguirla en cada una de sus apariciones.
Cristo no puede aparecer más en Espíritu ahora de lo que anteriormente
pudo hacerlo en aquel cuerpo de carne que le fue preparado,
sin que los peritos constructores se muestren a sí
mismos listos para proclamarlo como blasfemo,
profanador de las ordenanzas de Dios,
engañador de la gente o alguien que tiene un demonio.
"`Pero la sabiduría`" en todas las edades "`es justificada por
sus hijos`" y por nadie más. El que es nacido de la sabiduría puede
discernir el vientre y reconocer el fruto y las ramas,
incluso bajo el oscuro velo en el que se esconden del sabio carnal de toda época.
"`El reino de Dios no viene con señales visibles.`"
Los fariseos y escribas más sabios no pudieron conocerlo mediante las
observaciones que pudieron reunir de los escritos de Moisés y los profetas.
Nadie puede conocerlo ahora mediante alguna observación
que haya reunido de los escritos de los apóstoles,
sino al nacer del Espíritu del que nacieron los apóstoles,
y ser formado en el vientre en el que ellos lo fueron.
Sólo por este medio uno llega a conocer lo que ellos conocieron.
El que recibe el mismo ojo ve lo mismo de acuerdo a su medida.
Al llegar a la vida en la que los apóstoles recibieron la verdad,
las palabras que hablaron con respecto a la verdad son fáciles de discernir.
Así como fueron escritas en el Espíritu, deben ser leídas en el Espíritu,
y son extremadamente provechosas cuando son leídas de esta manera.
Pero el hombre que adivina, imagina y razona en su sabiduría carnal las cosas de Dios,
y a partir de esto reúne sentidos y significados acerca
de las palabras y expresiones de las Escrituras,
construye una Torre de Babel,
la cual será derribada por la vida eterna y el poder
(cada vez que aparezca) junto con el que la construyó.

¡Oh,
si los hombres fueran sabios para esperar la develación de la verdadera
roca y del verdadero edificio sobre dicha roca! ¡Oh,
si esa ciudad y edificio que sólo Dios puede erigir pudieran ser levantados en ellos!
Entonces no quedarían desolados y miserables en el
día tormentoso que sacudirá todos los edificios,
fundamentos y rocas, salvo a nuestra Roca.
Pues en ese día todos los profesantes, predicadores, eruditos,
y cualquier otro que pueda ser nombrado,
que hayan tropezado con la verdad viviente de Dios, confesarán con lágrimas, tristeza,
angustia y vergüenza que sus rocas no son como la Nuestra.
Pues aunque todo tipo de profesantes generalmente
reconocen en sus palabras a Cristo como la roca,
aún así la mayoría pierden la realidad misma.
Pues el enemigo sutilmente ha hecho uso de un concepto
o de una comprensión acerca de esto en la mente carnal,
para engañar y apartar de esta realidad.
De esta manera les impide sentir la virtud eterna,
el poder vivo de la vida en el corazón, lo cual es el brazo de salvación de Dios,
mediante el cual Cristo saca de la tumba de pecado y corrupción
el alma y el espíritu perdido del hombre para llevarlos al Padre.
¡Oh,
cuán engañados están los pobres corazones de quienes piensan
que se presentarán sin mancha o arruga delante de Dios,
teniendo una mera creencia con respecto a lo que Cristo logró mientras estuvo aquí en
la tierra! ¡Cuán engañados están los que se jactan del sacrificio de Cristo por ellos,
cuando aún cargan el cuerpo de pecado con ellos hasta
el último momento que están en sus cuerpos aquí,
y no han sentido el brazo del poder de Dios derribar sus enemigos espirituales,
sus deseos y sus corrupciones y redimirlos de todo ello!
A Cristo se le dio el nombre de Jesús porque iba a salvar a Su pueblo de sus pecados,
y nadie puede conocer verdaderamente ni vívidamente el nombre '`Jesús,`'
más allá de su propia experiencia de la virtud salvadora del mismo.
Pero el que efectivamente experimenta la virtud, en verdad conoce el Nombre,
puede inclinarse ante el Nombre y sentir sus deseos
y enemigos inclinados bajo el poder de dicho Nombre,
y que algo más se levanta en su interior que puede adorar al Padre en Espíritu y verdad.
¡Oh,
si los hijos de los hombres supieran! ¡Si los maestros y profesantes de
esta era entendieran lo que por tanto tiempo han injuriado y pisoteado!
Ciertamente se lamentarían amargamente, besarían al Hijo y escaparían de la ira!

Ahora bien,
si el Señor se complace en herir la sabiduría y comprensión de cualquiera
(que son los obstáculos más importantes que se interponen en el camino
de las manifestaciones y revelaciones puras de la vida),
y le da un verdadero sentido de lo aquí escrito, que reconozca al Señor en temor.
Que espere en el Señor ser mantenido en este sentimiento,
sin magnificar o injuriar a ninguno de Sus mensajeros,
sino que con mansedumbre y humildad abrace las instrucciones del
Todopoderoso de cualquier mano que Él haya usado para dárselas.
En cuanto a mí, yo no soy más que una cáscara.
Si ese grupo me conociera^
footnote:[El texto de este capítulo se ha tomado de la respuesta de Penington a un artículo
en el que él sentía que estaba siendo excesivamente alabado o preferido por sus autores.]
(el que me ha colocado muy alto,
prefiriéndome por encima de otros a quienes el Señor ha preferido por encima mío),
pronto reconocería que soy pobre, débil y despreciable.
Sin embargo, no voy a negar de ninguna manera,
que ciertamente el licor puro de la vida eterna brota y proclama
según Su voluntad a través de mí. Aunque también puedo decir,
con verdadero entendimiento,
que proclama más a menudo y más abundantemente a través de otros.
¡Qué la vida tenga su honor donde quiera que aparezca! ¡Quiera
el Señor hacer caer de los corazones de las personas lo que obstaculiza
el reconocimiento y recibimiento de su virtud!

=== El Reino Espiritual

El reino de Cristo, el reino de Dios,
el reino del cielo (pues todos ellos son uno y el mismo),
es la Semilla de vida eterna que Dios ha escondido
en los corazones de los hijos de los hombres,
por medio de la cual los reúne para Sí, los lleva bajo el yugo de Su gobierno,
rige sobre ellos y reina en ellos.

Este reino es comparado con un grano de mostaza por su pequeñez;
con una perla por su riqueza, valor y precio;
con la levadura por su naturaleza de esparcirse.
Cristo hizo uso de muchas otras parábolas para describirlo,
como la de una moneda de plata, que la mujer que la perdió, encendió una candela,
barrió la casa y buscó diligentemente, para al fin encontrarla donde la había perdido.

En lo que se refiere al Señor, el hombre que ha caído de Dios se ha perdido.
En lo que se refiere a su propia felicidad en el Señor,
el hombre ha sido expulsado de la bendita presencia y divina imagen,
vida y Espíritu de Dios, y ha entrado en el espíritu,
imagen y vida terrenal que él escogió. Sin embargo, en esta tierra,
en este campo del mundo, Dios ha escondido algo, ha escondido la perla eterna,
la que cuando el hombre es despertado para buscarla
y la encuentra mediante la eterna luz de vida,
es capaz de redimirlo.
La perla puede esparcirse y leudarlo (quedando sujeto a las leyes, guías,
enseñanzas y poder de ella) a la semejanza e imagen de la vida y espíritu puros.

¡Oh,
si los hombres conocieran el don de Dios! ¡Si los hombres conocieran la compra
de la sangre de Cristo! ¡Si conocieran esa cosa buena y espiritual por medio
de la cual Cristo (quien murió por ellos) puede redimirlos! ¡Si pudieran ser
unidos a Cristo en ese don y así ser renovados y restaurados a Dios por Él! Porque
así como el Padre no recibe a nadie sino a través del Hijo,
así el Hijo no recibe a nadie sino en ese don de gracia que Él otorga de parte del Padre.
Él no reconoce ninguna fe, amor, esperanza, arrepentimiento ni obediencia,
sino lo que brota del don de gracia y permanece en él.

Ahora bien,
cuando el hombre nace de este y es leudado por él (conforme se va convirtiendo
en un tonto en su propia sabiduría terrenal y excelencia del espíritu caído,
para llegar a ser un bebé, un niño, etc.), entra en el reino al ser injertado en la raíz,
así crece en este y este en él. Aquí está la nueva naturaleza, la nueva vida,
el nuevo corazón, el nuevo espíritu,
en donde la unidad y comunión con Dios es nuevamente conocida.
Aquí también está la desunión con el mundo, con la sabiduría, los intereses, las modas,
las costumbres, los temores, las esperanzas, los deleites,
las alegrías de este mundo y todo lo que es de él. Pues así como Cristo no es del mundo,
llama a los hombres a salir del mundo,
y los que lo siguen y se convierten en Sus discípulos
tienen que salir del mundo tras Él. Es decir,
tienen que salir en espíritu y conducta de lo que es de la tierra,
de lo que no sea del Padre.
'`Ellos no son del mundo,
como Yo no soy del mundo,`' dice Cristo con respecto a Sus discípulos en Juan 17,
'`y por eso el mundo los aborrece.`'

Las leyes de este reino son promulgadas en el reino,
a partir del pacto de vida que es hecho ahí en Cristo.
Estas leyes son escritas en el corazón, en la mente, en la medida que esta es renovada.
Ahí es puesto el temor, ahí es abierta la sabiduría eterna,
ahí es conocida Sión y la Jerusalén que es de arriba.
Las leyes de vida eterna son expedidas frescas desde ahí y reveladas
por la vida en el corazón que se vuelve hacia la vida.
Ahí el pecado es reprendido y la justicia eterna manifestada en la luz que no
puede engañar. En la medida que el corazón es sometido bajo el yugo,
así es desarraigado el pecado e introducida la justicia.
Bajo la cruz (o el yugo de vida) la sangre del pacto eterno
corre a través de la vasija para mantenerla pura,
dulce, limpia y fresca en la vida.

Este es, entonces, el gobierno de Cristo:
Ser sometidos a Su Espíritu que aparece y revela Su voluntad en
el don de gracia que proviene de Él. Experimentar Su aliento vivo,
mediante el cual el corazón es engendrado para Dios fuera de la región de oscuridad.
Conocer los movimientos, agitaciones, guías y pasos del Cordero,
quien es "`el Capitán de nuestra salvación.`" Seguirlo donde sea que vaya,
haciendo todo lo que Él ordena y absteniéndose de
todo lo que Él prohíbe "`sin murmurar ni discutir.`"

Cualquiera que sea del Israel interior, del Israel espiritual,
el que Cristo redime del Egipto espiritual y conduce a través
del desierto espiritual hacia la tierra de reposo,
tiene que conocer a su Líder, recibir Su Espíritu y seguirlo fielmente.
"`Si alguno no tiene el Espíritu de Cristo, no es de Él;`" no es del Israel espiritual.
Si alguno no sigue al Espíritu de Cristo a través de todas las
jornadas en el desierto (y en su lugar se sienta en el camino,
o se tumba ante cualquier tipo de enemigo,
o no llega al final de su viaje habiendo terminado la batalla y pelea de la fe),
queda corto del reposo.
¡Oh, si los hombres se despertaran para considerar las cosas tal como verdaderamente son!
Porque la verdadera religión no es una forma de doctrina
externa o adoración de algún tipo,
como los hombres en general (cuyas pobres almas son engañadas mediante las sutilezas
de los poderes de las tinieblas) son muy propensos y están dispuestos a concebir.
La verdadera religión consiste en Espíritu, poder, virtud, vida,
no en la antigüedad de ninguna forma que pasa,
sino en la novedad del Espíritu que permanece para siempre.
Consiste en ser nacido del Espíritu, en permanecer en el Espíritu, en vivir,
caminar y adorar en el Espíritu.
Sí, en llegar a ser y crecer en el Espíritu y en la vida eterna,
porque "`lo que es nacido del Espíritu, espíritu es.`"
¡Ojalá los hijos de los hombres escucharan para que pudieran degustar la dulzura y riqueza
de la bondad que el Padre en Su gratuito amor ha revelado en los espíritus de muchos!
¡Ojalá los hombres permitieran el desgaste de sus espíritus y sabiduría terrenal,
para que pudieran llegar a ser como Dios,
a ser formados y vivir en Su imagen! ¿Hasta cuándo prejuiciará el destructor
a los hombres de todas las edades contra los que buscan su bien?
¡Ciertamente el espíritu de este mundo luchará hasta lo último contra el Espíritu de Dios!
Pues en verdad el espíritu de este mundo no está
sujeto al Espíritu de Dios ni tampoco puede,
por lo tanto,
no soporta que el gobierno del reino de Cristo (que
no es de este mundo) sea establecido ante su vista.

Sin embargo,
el gobierno de Cristo y Su reino no es contrario
a ningún gobierno justo de ninguna nación o pueblo.
El gobierno de Cristo es un gobierno justo del corazón u hombre interior,
que no se opone a un gobierno justo del hombre exterior.
De hecho,
aquellos que están sujetos a Cristo y son individualmente
obedientes a Su ley de justicia en sus espíritus,
son más fieles a los hombres y más sujetos a cualquier ley justa del gobierno,
que lo que otros pueden ser,
pues su fidelidad y sujeción es debido al amor y por causa de la consciencia.
Sin embargo, lo que ofende al mundo es precisamente lo siguiente:
Que los hombres muchas veces hacen leyes en su propia
voluntad y en conformidad a su propia sabiduría,
leyes forjadas para fines egoístas e intereses corruptos.
Lo que es de Dios no puede inclinarse ante algo corrupto en el hombre.
Puede tumbarse, sufrir y soportar el látigo sobre su espalda,
pero no puede hacer nada que vaya en contra de su vida.
No puede ser desleal a su Rey para gratificar al espíritu de este mundo,
pero cualquier práctica o testimonio que su Rey exija
contra el mal y la corrupción de este mundo,
debe obedecerse individual y fielmente.

¡Si los hombres temieran delante del Señor y se aseguraran
de gobernar en lo que es de Dios,
entonces los gobernantes en la tierra no dañarían a ninguno de los Suyos,
ni correrían el riesgo de que su gobierno fuera sacudido.
Sin embargo, lo que no es de Dios, tanto dentro como fuera,
tiene que caer en el día del poder de Dios.
¡Feliz es aquel que está dispuesto a desprenderse de lo
que Dios está determinado a desgarrar del hombre,
a fin de permanecer en lo que no puede ser sacudido!
Porque ha habido un gran temblor en esta nación,
tanto en las cosas de afuera como en las de adentro, y queda aún más por ser sacudido,
tanto fuera como dentro, para que la gloria de Dios tenga espacio para aparecer.
¡Oh Inglaterra, honra al Hijo para que no se enoje!
Deja que todas esas leyes y costumbres que no son de Él caigan delante de Él,
y lo que es de Él déjalo inclinarse ante Él (tanto dentro como fuera),
para que Su ira no irrumpa como fuego, el que nadie puede aplacar.
