== Capítulo XI. Algunas Directrices para el Alma Anhelante

[quote.scripture, , Mateo. 11:28-30]
____
"`Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.
Llevad mi yugo sobre vosotros, y aprended de mí, que soy manso y humilde de corazón;
y hallaréis descanso para vuestras almas; porque mi yugo es fácil, y ligera mi carga.`"
____

Algunas dulces meditaciones brotaron en mi corazón
con respecto a esta porción de las Escrituras,
con respiraciones del espíritu y tierno afecto hacia aquellos "`que están trabajados
y cargados;`" meditaciones que me siento impelido a comunicar.

[.numbered]
1+++.+++ El verdadero descanso del alma está en el evangelio (el cual es "`poder
de Dios para salvación`"). Aquí está la verdad con respecto al reino,
donde está la vida, el gozo, la paz y el descanso eterno para el alma en Dios.
La ley tenía la sombra de los bienes venideros, pero,
bajo ella no se tenía posesión de los bienes mismos;
lo que había era un gran esfuerzo tras ellos, lamento y carga por la falta de los mismos.
Pero en el evangelio está la sustancia y el gozo,
donde la vida y la inmortalidad son traídos a la luz,
y la entrada al reino eterno es experimentada, poseída y disfrutada.
"`El reino de los cielos se ha acercado,`" dice el precursor,
"`ha llegado,`" dice el Mesías; y en él hay justicia,
paz y gozo en el Espíritu puro de vida.

[.numbered]
2+++.+++ Es la voluntad del Rey de los santos que Su pueblo
disfrute el reposo y la paz de Su evangelio.
Él no desea que ellos estén siempre trabajados y cargados como bajo la ley,
sino que sus almas experimenten y disfruten la tranquilidad, la libertad, la dulzura,
el poder puro y el reposo eterno de Su vida.
El Espíritu del Señor estaba sobre Él para que predicara buenas nuevas a los abatidos,
libertad a los cautivos y vida a los muertos; para que abriera la cárcel de los presos,
vendara a los quebrantados de corazón y derramara aceite en los heridos.
El Señor desea que las almas de Su pueblo disfruten lo que Él les vino a traer.

[.numbered]
3+++.+++ Cristo le ha marcado claramente el camino de Su reposo a cada alma cansada y anhelante,
y la que camina en él no se puede perder.
Él ha hecho claro el camino en el evangelio, tan claro, que el viajero, aún el insensato,
al mantenerse en la luz del evangelio, no puede equivocarse o perder su bendito reposo.
¿Cuál es el camino?
"`Venid a mí;
llevad mi yugo sobre vosotros y aprended de mí.`"
El que anda en este camino no puede perderlo.
El reposo está al final de él. No, más bien, el reposo está en él:
"`El que cree entra en el reposo.`"
La verdadera fe, la fe que está en el poder de Dios y se le da al nacido de arriba,
es la sustancia del reposo esperado,
y hay un gusto real y cierto disfrute verdadero de él otorgado al que realmente cree.

[.numbered]
4+++.+++ El reposo fue en otro tiempo sentido y disfrutado
cuando el evangelio era experimentado en el poder.
En los primeros días del evangelio (antes de que la noche superara esa gloriosa dispensación),
los creyentes encontraban "`paz y gozo al creer;`" en realidad,
ellos podían regocijarse en el Señor siempre.
Sentían el poder y la vida que estaba sobre todos los poderes
de las tinieblas y que les traía bien de toda aflicción,
tentación y angustia.
Estaban en la vida y en el poder que los había vivificado y que estaba presente en ellos,
por tanto,
podían '`tener por sumo gozo cuando se hallaban en diversas
pruebas,`' conociendo el beneficio que de este modo devengarían,
y teniendo sus almas en la paciencia pura hasta que Dios la obrara para ellos.
Tenían una entrada ministrada para ellos en el reino eterno.
Recibieron el reino que no podía ser sacudido y en
el que tenían comunión con el Padre y con el Hijo.
En la luz eterna, la sangre que los limpiaba y mantenía puros corría en sus vasijas.
Se sentaron con Cristo en lugares celestiales,
cada uno en la mansión particular que Dios había edificado en ellos mediante Su Espíritu.
El temor del Dios vivo estaba puesto en sus corazones.
El Espíritu del Señor estaba dentro de ellos,
ahí fue escrita Su ley y era leída en el Espíritu,
y los tesoros de Su reino fueron abiertos por la llave de David en la mano del Espíritu.
De este modo sus almas tenían verdadera satisfacción
y reposo en medida y viajaban hacia la plenitud.

[.numbered]
5+++.+++ No hay descanso para ser disfrutado en el evangelio,
para el alma que no está bajo el yugo.
El verdadero descanso es hallado en eso que enyuga todo
lo que está a gusto y en libertad fuera de la vida.
Sólo cuando lo enyugado es consumido y destruido, la libertad es conocida,
y entonces ya no se siente como un yugo, sino como perfecta libertad.
Lo que es la libertad es también el yugo, y bajo el yugo es disfrutada la dulzura,
la holgura y la posesión segura de la vida.
Por lo tanto, noten esto diligentemente: El yugo no es una cosa y la libertad otra; no,
el yugo y la libertad son una y la misma cosa.
El poder de Dios, la vida eterna, la luz pura,
la naturaleza divina son un yugo para la naturaleza transgresora, pero es holgura,
placer, descanso, paz y gozo para lo que es nacido de Dios.

Ahora bien, tengo que decirle al alma que ha sentido deseos por el Señor anteriormente,
y en la que todavía hay verdaderos deseos en pos de Su presencia
viva y de la experiencia de Su virtud eterna en el corazón:
¿Dónde está usted?
¿Está en el descanso de su alma?
¿Experimenta la virtud y el poder del evangelio?
¿Está su esfuerzo por la vida en un buen grado cerca del fin?
¿Experimenta la vida y el poder fluyendo sobre usted desde la fuente gratuita?
¿Ha sido realmente quitada la carga de su espalda?
¿Encuentra al cautivo redimido y liberado del poder del pecado y rota la cautividad?
¿El que lo lleva cautivo lejos de la vida y del poder eterno es
ahora llevado cautivo por la vida y por el eterno poder redentor?
¿Ha encontrado esto o se lo ha perdido?
Deje que su corazón responda.
¡Oh, no imagine ni pase hablando del reposo y la salvación de su alma!

El estado del evangelio es un estado de sustancia, el estado en que se disfruta la vida,
el estado en que se experimenta la presencia y el
poder del Señor en Su Espíritu puro y santo.
Es un estado de unión, un estado de salud,
un estado en el que se conoce al Señor y se camina con Él en la luz de Su propio Espíritu.
Comienza con un dulce y poderoso toque de vida,
y hay un crecimiento en la vida (en el poder, en la virtud divina, en el reposo,
paz y satisfacción del alma en Dios) que tiene que ser administrado y esperado diariamente.
¿Está usted aquí, en el poder vivo, en la vida divina,
unido a la fuente de vida y sacando con gozo agua de vida del pozo de vida?
O, ¿está seco, muerto, estéril, sin savia, o en el mejor de los casos,
insatisfecho y de luto en pos de lo que carece?
¡Ustedes que están secos, muertos y estériles, por así decirlo,
sin el Dios vivo (que no conoce el resplandor de Su sol,
ni la caída del rocío de lo alto sobre sus tiernas plantas),
esperen la virtud dadora de vida, las visitas de la aurora de lo alto!
Espérenlo a Él para ser vivificados de nuevo para Dios y puedan
encontrar Su vida visitándolos y a Su Espíritu soplando sobre ustedes.
Vuélvanse y esperen que la semilla de Jacob sea levantada
en ustedes para salir de su estado de esterilidad,
es decir, para que salgan de esa tierra de tinieblas y de debajo de la sombra de muerte,
hacia la tierra donde la vida vive y florece.
Conozcan la tierra que diariamente distribuye alimento
y abundante refrigerio a toda su descendencia,
quienes son enseñados a esperarlo y a alimentarse de él en el lugar santo,
fuera de la vista del ojo de la sabiduría carnal.

Y ustedes, que todavía anhelan al Dios vivo,
sobre quienes los soplos de vida aún permanecen,
que se mantienen insatisfechos interiormente por la falta de la presencia del
Señor y cuyos corazones siguen con lloro y lamento profundo en pos de Él,
¡piensen cuál podría ser el problema! ¡Consideren
por qué se han lamentado por tanto tiempo,
por qué han buscado por tanto tiempo, por qué hasta el día de hoy,
están a cierta distancia de la cosa por la que se
han lamentado y han buscado por tanto tiempo!

"`Porque estrecha es la puerta, y angosto el camino que lleva a la vida,
y pocos son los que la hallan.`"
El camino de la incredulidad es amplio, ciertamente,
pero el camino de la creencia también lo es.
Es fácil para un hombre creer con respecto a Cristo o en
Cristo (o como su corazón lo llame) de manera tal,
que pierda la naturaleza de la verdadera fe,
y todos los efectos dulces y benditos que la acompañan. Asimismo,
es fácil perder el yugo o tomar un yugo equivocado, en la propia voluntad,
en la propia sabiduría, en la propia interpretación de las Escrituras.
Es fácil desviarse del verdadero yugo,
pero caminar bajo el yugo de la vida y permanecer bajo él es difícil.
De nuevo, es fácil aprender equivocadamente.
Un hombre puede leer y oír de manera tal,
que puede estar aprendiendo siempre y nunca llegar al conocimiento de la verdad,
es decir,
nunca llegar a la verdad tal como es recibida y permanece
en Jesús. Si un hombre pierde el camino así,
¿cómo puede alcanzar la meta?
Si alguno no comienza en la verdadera fe, en la fe viva, ¿cómo puede alcanzar el reposo,
hacia el que solamente la fe verdadera lleva?
Si un hombre pierde el yugo o no permanece constantemente bajo él,
¿cómo puede encontrar la verdadera tranquilidad y el verdadero
descanso que está en el yugo y que sólo él puede administrar?
Si un hombre no aprende la verdad correctamente del verdadero
maestro ¿cómo puede cosechar los efectos del verdadero conocimiento?
¡Ah, pobres corazones!
No es suficiente tener anhelo de Dios, ni ser muy diligentes y trabajadores,
sea en ordenanzas externas o en ejercicios internos del espíritu.
El camino del evangelio debe ser abierto por Dios,
el alma debe ser guiada por Dios en dicho camino y diariamente
preservada por Él. El alma debe caminar en la senda correcta,
de lo contrario, puede lamentarse y llorar todos sus días,
y nunca experimentar el gozo de Dios ni la satisfacción
en Dios que espera y tras la que llora.
Una cosa es llorar en pos del estado del evangelio,
y otra ser introducido en él por el poder.
Con mi corazón reconozco a los que lloran y sienten la carencia de Dios,
dondequiera que estén, pero sé con certeza,
que ellos no podrán llegar a gozar de Él salvo en ese camino vivo,
del que las Escrituras testifican que está en Aquel que es la vida.

[.discourse-part]
Pregunta: ¿Cómo puede mi pobre alma que ha llorado y gemido tanto tiempo,
y que ha estado '`enferma de amor tras mi Amado`' llegar a caminar en Su senda,
para que yo pueda experimentar y descansar en el poder de vida y salvación
del que el evangelio habla ampliamente al verdadero creyente?

[.discourse-part]
Respuesta: Usted que desea disfrutar a su Amado,
experimentar el reposo de Su evangelio y caminar en la senda que lo conduce a Él,
espere aprender del Espíritu lo siguiente:

[.numbered]
1+++.+++ Conozca qué es lo que puede caminar en la senda de vida,
y que ciertamente es lo único capaz de caminar en ella.
Es lo que gime y llora, y es engendrado de Dios en usted.
La senda de vida es para la semilla de vida.
El verdadero conocimiento del camino y la caminata en él,
están reservados para los hijos de Dios, para los viajeros de Dios.
Por lo tanto, manténgase en la regeneración, manténgase en el nacimiento,
no sea más de lo que Dios le ha hecho.
Basta ya de su propia voluntad, basta ya de su propia marcha,
basta ya de su propio deseo de saber o de ser algo.
Sumérjase en la Semilla que Dios sembró en el corazón; deje que crezca en usted,
que sea en usted, que respire en usted, que actúe en usted,
y encontrará mediante una experiencia dulce, que el Señor conoce,
ama y reconoce esa Semilla, y que la guiará a la herencia de vida,
la cual es Su porción. Cuando usted tome la cruz para sí y permita
que la Semilla se esparza y se convierta en un yugo sobre usted,
será renovado, disfrutará la vida y la herencia eterna en la Semilla.

[.numbered]
2+++.+++ Conozca la luz del Espíritu en la que usted debe caminar.
Ahí el niño es engendrado (no, en las tinieblas de Satanás,
ni en la sabiduría del hombre buscando conocimiento o entendimiento), y ahí camina.
En esa luz el niño encuentra cada paso y movimiento hacia la tierra de la vida.
Por lo tanto, no retenga conocimiento fuera del Espíritu.
Si algún conocimiento con respecto a las cosas de
Dios es sostenido fuera de la frescura del Espíritu,
pronto prueba ser muerto e improductivo.
El Israel espiritual no puede viajar sin luz espiritual,
dicha luz es eterna e incomprensible,
y no puede ser sostenida por el espíritu del hombre.
Esta luz brilla fresca cada día en el espíritu renovado,
y diariamente lo recoge más y más en el interior de sí misma, lo comprende en sí misma,
y lo preserva en su propia pureza, claridad y resplandor.

Ahora bien, esta ha sido la caída de muchos: Coger algo de luz del Espíritu,
luego trasplantar la imagen de las cosas divinas en la naturaleza terrenal,
y sostenerla ahí en la parte terrenal.
De este modo el hombre busca crecer sabio y hacer uso de
las cosas espirituales tal como él estima que es bueno,
y no ve la necesidad de depender del Espíritu para tener
luz y vida frescas cada día para cada movimiento espiritual.
En consecuencia,
el viajero pronto llega a perder la senda verdadera y en su lugar viaja en el camino
de su propia sabiduría. A tal hombre le parece que está haciendo un gran progreso,
aunque no está haciendo ningún verdadero progreso, todo lo contrario,
se ha alejado mucho en la dirección equivocada y
debe recorrer ese terreno otra vez de regreso,
antes de poder llegar a la verdad de su estado anterior,
o continuar en el verdadero camino.

[.numbered]
3+++.+++ Conozca y aférrese al poder, lo único que comenzó una verdadera obra en el corazón,
lo único que puede preservarla y lo único que puede continuarla.
Cristo fue hecho sacerdote, no según la ley de un mandamiento carnal,
sino según el poder de una vida indestructible.
Cada sacerdote bajo Él (lo cual es cada verdadero
creyente) es hecho sacerdote por el mismo poder.
Los poderes de las tinieblas están continuamente a la mano,
contra los cuales nada puede permanecer si no está
en el poder que está por encima de ellos.

Ahora bien,
la primera llegada del alma a Cristo debe ser en el poder de la invitación del Padre,
y luego,
nuestra capacidad de creer tiene que permanecer e ir adelante
en el mismo poder para ser de la naturaleza correcta.
Por lo tanto, tanto llevar el yugo como el viaje del alma y el progreso en él,
deben ser mediante el poder de la nueva vida;
así debe ser todo el aprendizaje del discípulo.
Así como el maestro enseña en el poder del Espíritu
cosas que sólo pueden ser vistas con el nuevo ojo,
oídas con el nuevo oído y recibidas en el nuevo corazón,
así debe aprender y recibir el estudiante Sus lecciones de vida, en el mismo poder.
Si algún discípulo de Cristo se sale de debajo de la sombra del poder,
y cree sin el poder, camina sin el poder, actúa sin el poder,
está fuera de donde está Su vida y de donde encuentra
preservación. ¡Cuán expuesto queda él a los hoyos,
moretones, trampas y tentaciones del enemigo!

[.numbered]
4+++.+++ Esté en guardia contra la sabiduría egoísta en cada etapa de su crecimiento,
que no se interponga entre usted y su vida.
Vigile que no sea engañado con una semejanza, una sombra,
haciéndola parecer más agradable al ojo que la sustancia.
En cada paso de su camino le irá poniendo trampas.
Pues es fácil que el engaño entre en cualquier momento y que la sabiduría
carnal se levante en usted bajo la apariencia de sabiduría espiritual,
si el Señor no lo preserva tierna y poderosamente.
Si la sabiduría equivocada prevalece,
ella lo desviará de la senda de la verdadera sabiduría. Lo engañará con una fe falsa,
en lugar de la fe verdadera; con falsa oración,
en lugar de las respiraciones del verdadero niño;
con diligencia y celo en el camino falso, en lugar del verdadero celo y diligencia.
Es más, lo apresurará en la senda del error, cerrando en usted el ojo que puede ver,
y endureciendo su corazón contra su amigo más verdadero.
Al ser engañado así,
usted llegará a ser tan celoso en su era y generación contra
la verdad como lo fueron los judíos en la de ellos.

[.numbered]
5+++.+++ Que nada juzgue en usted (con respecto a su propio corazón, con respecto a otros,
o con respecto a algún camino o verdad de Dios) salvo lo que es
nacido de Dios en su corazón. Deje que la luz en la que usted es
engendrado para Dios y que brilla sobre Su engendrado,
sea el único juez en usted, entonces no se equivocará en el juicio.
No se precipite, no se adelante en el juicio, manténgase detrás de la vida,
siga esperando la aparición y revelación de la vida.
Unos pocos pasos ganados en la vida y poder de Dios son más seguros y
dulces que un progreso apresurado en el espíritu precipitado y adelantado.

En realidad esta es la verdadera religión:
La experiencia del Espíritu de Dios que comienza algo en el corazón,
la espera del corazón en Él por más de Su Espíritu,
y caminar con Él en Su Espíritu conforme le place avivar, conducir, extraer y fortalecer.
De hecho, no hay deber u ordenanza del evangelio fuera del Espíritu.
Sin embargo, es fácil elogiar y practicar la semejanza de esas cosas sin el Espíritu;
entonces lo que era de Dios en el corazón pronto se marchita,
una edificación contraria es levantada y el estado del corazón cambiado.
¡Espere en el Señor que Él le dé el entendimiento de estas cosas!

[.discourse-part]
Pregunta: ¿Cómo puedo conocer y aferrarme al engendrado de Dios,
y a la luz y poder del Señor,
y evitar que se levante la sabiduría y comprensión
carnal con respecto a las cosas de Dios?

[.discourse-part]
Respuesta: Cuando Dios engendra vida en el corazón hay un sabor de ella en la vasija,
una calidez secreta y viva,
una virtud que el corazón experimenta en alguna medida y por la que la vida es conocida.
Inclínese bajo el temor del Altísimo para que esta
levadura crezca y se incremente en usted.
Esta es la levadura del reino.
Esto es lo que debe cambiar su corazón y su naturaleza,
y hacer que su vasija (la cual quizás haya sido por mucho tiempo
muy corrupta) esté en condiciones de recibir el tesoro del reino.

Ahora bien, mientras el sabor esté sobre usted,
mientras la virtud de la vida sea fresca en usted,
encontrará algo de fuerza en dirección a Dios,
con un poquito del gusto y discernimiento de las cosas de Su reino.
Conozca su debilidad y no vaya más allá de la medida,
sino que inclínese delante de la plenitud de lo que ha recibido,
adore a Dios en ello y sea paciente, independientemente de cómo trate Él con usted,
y espere más de Él. Y cuando la noche caiga sobre usted, y se encuentre desconcertado,
le falte el sabor y la presencia de la vida, y no sepa cómo volver otra vez,
sea paciente y esté quieto,
y encontrará respiraciones anhelantes tras una nueva visitación, y de un espíritu manso,
humilde y quebrantado delante del Señor. Verá que usted
no puede hacer nada para recuperar Su presencia de nuevo;
no, sin Su ayuda usted ni siquiera puede esperarlo o respirar tras Él. Sin embargo,
Él está cerca del pobre, cerca del quebrantado, cerca del afligido, cerca del indefenso.
¡No piense en despertar a su Amado con sus gritos y rugidos carnales antes de Su tiempo!
Sin embargo,
en la noche de aflicción palpe tras eso que puede calmar y mantener su corazón hasta
el siguiente surgimiento del día. El sol se levantará y dispersará las nubes,
Él está cerca,
el que le dará esperanza de que aún verá a Dios y de nuevo
encontrará la vivificación y guía de Su Espíritu.
En el día de Su poder usted encontrará fortaleza para caminar con Él; sí,
en el día de su debilidad Su gracia será suficiente para usted.
Él lo nutrirá en Su vida mediante Su Espíritu puro,
haciendo que usted crezca bajo Su sombra.
Él lo enseñará a vivir, a hablar, a moverse y actuar desde la Semilla,
y dentro del ámbito de Su luz y vida eterna.
Sólo no sea imprudente de coger el entendimiento de las cosas en la parte terrenal,
donde la polilla corrompe y el ladrón puede penetrar y robar,
más bien llegue a conocer el tesoro divino,
donde todas las cosas de la vida son atesoradas por
e l Espíritu y otorgadas al niño vivo con vida fresca,
de acuerdo a su necesidad de ellas.

De esta manera su corazón será mantenido cerca de Dios y sus sentidos
espirituales continuamente ejercitados con respecto a Sus cosas.
Será fácil para usted conocer la voz del pastor y distinguir
el sonido del Espíritu en su propio corazón. Y Aquel que
prueba los espíritus y los movimientos en su propio corazón,
también le dará el discernimiento de la verdad y el error en otras partes, es decir,
entre el Espíritu de Dios y el espíritu de Satanás en otros.
Usted será capaz de probar no sólo palabras, sino espíritus,
llegando a familiarizarse con la unción que prueba todas
las cosas y que le permitirá juzgar no mediante las palabras,
sino mediante el poder.
Porque para usted, al estar en el poder, en la unción y en el sabor,
le llegará a ser natural experimentar, probar,
conocer y unirse con lo que es uno con su vida,
con lo que viene del mismo espíritu en otros y volverse también de lo que es contrario.
Por lo tanto, su vida, su crecimiento, su senda será dulce, segura, clara, cierta,
demostrativa en el Espíritu y más allá de todo razonamiento de carne y sangre,
ya sea en usted como en otros.
Aún los comienzos de la vida eterna son de una naturaleza
más elevada que lo que el hombre pueda alcanzar.
La sabiduría y el conocimiento del hombre con respecto a las cosas de Dios,
no son sino necedad delante de ella, pero cuando usted entra en dicha vida,
permanece y crece en ella, está más allá del juicio del hombre,
y es capaz de juzgar al hombre y discernir la totalidad de su camino.

=== Acerca de la Adoración al Dios Vivo

He tenido profunda experiencia en cuanto a la adoración a Dios desde niño,
habiendo luchado desesperadamente en espíritu con mi Dios,
por el conocimiento correcto de la misma, y en sencillez de corazón,
me he rendido ante Él conforme ha enseñado y conducido mi pobre,
necesitada y dependiente alma.
Ahora bien,
la adoración a Dios es algo de peso y han habido
muchos errores (y todavía los hay) acerca de ella.
Estos errores son de consecuencias muy peligrosas,
tanto en relación con el estado eterno de los hombres en la otra vida,
como en relación con su correcto fundamento, paz y bienestar en este mundo.
Por lo tanto,
está en mi corazón responder algunas preguntas con respecto a la adoración a Dios,
para el servicio de los que tienen tanto el deseo
como la necesidad de instrucción de ella.

[.discourse-part]
_Pregunta 1:_ ¿Quién es el adorador aceptable ante la vista de Dios?
O, ¿a quién le ha concedido Dios Su adoración a la vista del mundo,
ya que rechazó a los judíos y su adoración?

No es todo hombre que se meta en la cosas del Señor a quien Él aceptará,
sino "`los verdaderos adoradores adorarán al Padre en espíritu y en verdad;
porque también el Padre tales adoradores busca que le adoren`" (Juan 4:23). Hay
una capacidad que debe ser hallada en el hombre para hacer de él un adorador,
es decir,
una capacidad que le permita realizar la adoración que Dios requiere de él. Ahora,
esto es lo que ha de ser indagado: ¿Cuál es esta capacidad?
¿Quiénes son las personas que son halladas en dicha capacidad?

[.discourse-part]
Respuesta: El adorador en los tiempos del evangelio, el adorador bajo el nuevo pacto,
es "`el que es nacido de Dios,`" el que es sacado del espíritu de las
tinieblas de este mundo y formado de nuevo en la luz del Espíritu de Dios.
El adorador que "`el Padre busca que le adore`" es el judío interior,
el que tiene el prepucio de su corazón cortado por el poder de Dios.
Esta es la clase de adoradores que Dios escogió cuando rechazó al judío externo.
Dios no escogió ninguna nación o muchas naciones en lugar de la que rechazó, más bien,
envió a Sus apóstoles y ministros a todas las naciones
a reunir una semilla espiritual en lugar de la natural.
Esta semilla espiritual es la única capaz de establecer
y sostener Su adoración espiritual en el mundo,
y de provocarlos a esperar y a presionar hacia la
capacidad de entrar en la misma adoración espiritual.

[.discourse-part]
_Pregunta 2:_ ¿Cuál es el lugar de adoración?

[.discourse-part]
Respuesta:
El único lugar de adoración en el nuevo pacto es
aquel donde los adoradores espirituales se reúnen.
Este lugar es espiritual.
Así como la adoración es espiritual, es el lugar donde tiene que ser ofrecida.
Esta es de carácter espiritual; no es externa, como lo era bajo la ley.
Tiene que ser ofrecida en el Espíritu; ese es el lugar.
¿Dónde ofrece mi alma su adoración privada a Dios?
¿Tiene relación con algún lugar externo o es en el edificio
que Dios ha levantado en mi corazón mediante Su Espíritu?
Este edificio se levanta y es comprendido en Su Espíritu,
y yo puedo ofrecerle adoración pública únicamente en un edificio de la misma naturaleza,
en una casa construida con más de las mismas piedras.

Esta es, entonces, la forma de adoración en la verdadera Luz:
Varias piedras vivas reunidas, cada una retirándose en espíritu dentro del Nombre vivo,
dentro del poder que las engendró, reunidas en un mismo lugar, en un mismo poder,
en una misma fuente de Vida.
Aquí se inclinan ante el Padre de vida, ofreciéndole sacrificios vivos,
recibiendo el pan y el agua de vida de Él y alimentándose
en los ricos pastos de Su infinita plenitud.
La ciudad santa, el templo vivo,
el construido por Dios de la Piedra que los otros edificadores desecharon,
es el lugar de adoración al Dios vivo,
donde los verdaderos judíos se reúnen para ofrecer sus espíritus,
almas y cuerpos en sacrificio vivo al Padre de vida.
Aquí se encuentran con tal presencia y poder glorioso del Padre,
como ninguno que no sea verdadero judío haya jamás conocido.

[.discourse-part]
_Pregunta 3:_ ¿Qué es la adoración, o que son los sacrificios,
los que los verdaderos adoradores le ofrecen a Dios en este lugar santo?

[.discourse-part]
Respuesta: Los dones que provienen de Su Espíritu; estos son los únicos que se ofrecen.
Las respiraciones anhelantes que el Padre pone en el corazón del niño,
son devueltas a Él en el mismo Espíritu de vida,
en la consciencia viva y el poder vivificador.
Nada de la sabiduría del hombre, nada de la invención del hombre,
nada de acuerdo a la voluntad del hombre,
nada que agrade a la carne o parezca glorioso a sus
ojos es ofrecido aquí. Pero las exhortaciones,
las instrucciones o reprensiones que brotan en la luz y sabiduría de Dios,
son dadas en la guía y mediante la conducción de Su Espíritu,
y alcanzan los corazones de aquellos a quienes Él le place dirigirlas.
Este es el fundamento de la rendición,
quebrantamiento y convicción del alma que es tan
frecuente encontrar en este tipo de asambleas.
Porque el Dios vivo está ahí y el temor de Su poder se extiende sobre
los corazones de los que están reunidos y congregados en Su nombre.
La vida brota en las vasijas terrenales y el deleite es
precioso para todos los que tienen sus sentidos espirituales.

[.discourse-part]
_Pregunta 4:_ ¿Cuál es el tiempo de ofrecer estos dones?

[.discourse-part]
Respuesta: El tiempo de la verdadera adoración está en la voluntad de Dios.
Estos son Sus dones, y el tiempo de ellos está en la voluntad del Dador.
Orar es un don.
Un hombre no puede orar cuando lo desee,
pero debe velar y esperar el momento en que el Padre
encienda en él anhelos vivos hacia Sí mismo.
La palabra de Dios (ya sea de exhortación o de instrucción) es un don que se debe esperar,
y luego debe ser dado en la vida y fuerza de ese Espíritu que hizo que surgiera.
En verdad es difícil hablar la palabra del Señor u oír la palabra del Señor. Un hombre
fácilmente puede hablar lo que inventa y otro fácilmente puede oír y juzgar esas palabras,
pero hablar la palabra de vida requiere la lengua del que
ha aprendido el lenguaje del Espíritu de Dios.
Oír la palabra de vida requiere un oído vivificado.
Conocer los tiempos y sazones del Espíritu requiere tanto haber
sido engendrado por el Espíritu como estar familiarizado con Él.

[.discourse-part]
_Pregunta 5:_
¿Era esta la adoración de los antiguos cristianos en los días de los apóstoles?

[.discourse-part]
Respuesta: Busquen en las Escrituras.
¿No llegaron ellos a la Nueva Jerusalén? ¿Dónde ofrecieron sus sacrificios?
¿Los ofrecieron en la vieja Jerusalén,
en Samaria o en la montaña donde adoraron los padres?
¿No los ofrecieron más bien en el Monte Sión, al que habían llegado,
donde el macho del rebaño (es decir,
el cordero sin mancha) es conocido y la sangre rociada experimentada?
(Heb.
12:22-24; 1 Ped.
2:5) ¡Lean!
Lean en la vida de Dios la naturaleza de las cosas mismas,
no se alimenten de sus propias imaginaciones o de las imaginaciones
de ningún otro hombre con respecto a ellas.
Dulce es nuestro Dios y Su presencia viva es abundantemente nutritiva para el alma.
Precioso es Su poder experimentado en el corazón,
y adorarlo en Su Espíritu es nada menos que una verdadera experiencia de la vida eterna.
¡No dejen que el enemigo del alma distraiga sus almas
por más tiempo de las preciosas cosas de Su reino,
con comida áspera y seca que sólo gratifica la parte terrenal,
pero que no nutre la vida inmortal!

[.discourse-part]
_Pregunta 6:_
¿Cómo llegó a transformarse y a cambiar tanto la adoración
de Dios de un poder vivo a formas muertas y formales,
como en las que son hallados generalmente los adoradores en el mundo?

[.discourse-part]
Respuesta: El enemigo lo ha hecho, con el permiso de Dios.
Al Señor le plació permitirle prevalecer contra la verdad hasta ahora, es decir,
entrar en la forma externa de ella, engendrar ahí hombres en dicha forma,
y luego negar y volverse contra el poder.
Esta es la manera del anticristo en reinos y naciones:
Establece una manera formal de adoración,
y mediante ella pelea contra el verdadero poder.

=== Algunas Preguntas y Respuestas Relacionadas a la Conversión y a la Ternura de Consciencia

[.discourse-part]
Pregunta: ¿De qué manera ocurre la conversión?

[.discourse-part]
Respuesta:
Volviendo a los hombres de las tinieblas a la luz y del poder de Satanás a Dios.

[.discourse-part]
Pregunta: ¿Cuándo se convierte un hombre?

[.discourse-part]
Respuesta: Cuando es reunido con la luz y el poder,
fuera de las tinieblas del pecado y de los dominios de Satanás.

[.discourse-part]
Pregunta: ¿Cómo se convierte un hombre?

[.discourse-part]
Respuesta: Por la operación de la luz y el poder de Dios sobre su consciencia.^
footnote:[Es importante señalar que tanto la mente como
la consciencia del incrédulo están naturalmente corrompidas.
Pablo escribe: "`Todas las cosas son puras para los puros,
mas para los corrompidos e incrédulos nada les es puro;
pues hasta su mente y su conciencia están corrompidas`" (Tito 1:15). Por lo tanto,
no es la consciencia misma la que es o posee luz divina (como muchos falsamente asumen).
Más bien,
es Cristo la Luz en la consciencia el que lleva al hombre el conocimiento de la verdad,
y cuando obedece, a la transformación del alma.]

[.discourse-part]
Pregunta: ¿En qué condición está la consciencia antes de que Dios obre sobre ella?

[.discourse-part]
Respuesta: Dura y corrupta.
Endurecida por los razonamientos egoístas y oscuras imaginaciones
contra las convicciones de la luz y operaciones del poder de Dios.
Está corrompida por el pecado y la iniquidad que moran en ella.

[.discourse-part]
Pregunta: ¿Qué hace Dios por medio de Su obra en ella?

[.discourse-part]
Respuesta: Suave y tiernamente,
ponerla en condiciones de recibir las impresiones de Su Espíritu.
Mediante la influencia y poder de Su Espíritu en la consciencia,
abre el oído para que escuche Su voz y prepare el corazón para que siga Su guía.

[.discourse-part]
Pregunta: ¿Cómo continúa Dios Su obra en el alma convertida?

[.discourse-part]
Respuesta: Manteniéndola humillada y tierna,
fuera de la sabiduría propia y de los endurecidos razonamientos del entendimiento humano.
Por estos medios la mantiene dócil a la luz y al poder de Su Espíritu.

[.discourse-part]
Pregunta: ¿Sólo una consciencia tierna es apta para ser trabajada por Dios?

[.discourse-part]
Respuesta: Sí; en realidad, únicamente esa.
El corazón duro no considera la voz de Dios y es inflexible y obstinado contra ella.
Siempre tiene a mano algo de la sabiduría o voluntad de
la carne con la cual resistir la voz y guía de Dios.

[.discourse-part]
Pregunta: ¿Quién preserva la consciencia tierna?

[.discourse-part]
Respuesta: El Señor de la consciencia.
El que la hizo conoce el temperamento de ella y sólo Su luz y poder
son capaces de conservarla en la ternura en la que la formó.

[.discourse-part]
Pregunta: ¿Qué endurece la consciencia?

[.discourse-part]
Respuesta: La sabiduría de la carne.
El hombre, tras ganar una sabiduría fuera de la luz de Dios mediante las imaginaciones,
razonamientos y fortalezas de la misma, se endurece contra Dios.

[.discourse-part]
Pregunta:
¿Qué debe vigilar un hombre si desea que la obra de conversión continúe en su corazón?

[.discourse-part]
Respuesta:
Debe ser cuidadoso en volverse y evitar los razonamientos de la sabiduría humana,
y tener su ojo y oído abiertos a la luz y voz del Espíritu de Dios,
a fin de que su consciencia pueda ser mantenida recta y limpia delante del Señor.

[.discourse-part]
Pregunta: ¿Qué mancha la consciencia?

[.discourse-part]
Respuesta: Cualquier desobediencia al Espíritu de Dios.
Escuchar o seguir la voz de un espíritu extraño.
Esto permite que entre la oscuridad que contamina,
tal como la luz purifica.

[.discourse-part]
Pregunta:
¿Tiene entonces un hombre que tener la expectativa de tal
cosa como la guía del Espíritu de Dios en su consciencia?

[.discourse-part]
Respuesta: Un hombre no puede heredar el reino de Dios a menos que haya nacido de nuevo,
es decir, a menos que haya "`nacido del Espíritu.`"
Así dice la Escritura y así dice la experiencia de
aquellos que experimentan el nuevo nacimiento.
Cuando el hombre nace del Espíritu, debe permanecer en el Espíritu,
y de Él aprender la ley de la nueva vida y recibir poder diariamente.
Si no lo hace,
el espíritu de las tinieblas pronto ganará terreno en el
hombre y gradualmente lo recuperará de nuevo en su dominio.

[.discourse-part]
Pregunta: Si en definitiva esto es cierto,
entonces el camino de la verdadera religión es difícil
y hay pocos que son hallados en la verdad de él.

[.discourse-part]
Respuesta: El camino de la verdadera religión es difícil en verdad,
y completamente contrario tanto a la sabiduría como a la voluntad humana.
De hecho, el hombre no puede entrar en él, ni caminar en él,
a menos que su sabiduría y su voluntad sean cortadas.
El que quiera ser discípulo de Cristo y seguir la guía de Su Espíritu,
deberá negarse a sí mismo por completo, llegar a ser de otro,
y para su propio Amo estar en pie, o caer.
El tal no puede agradar a los hombres, no en su adoración a Dios,
sino que debe volverse de lo que es glorioso a los ojos de los hombres y sacrificar
al Señor lo que para ellos es una abominación. (Éxo. 8:26) Así que,
el que sea aprobado ante la vista de Dios deberá esperar ser condenado por los hombres.

[.discourse-part]
Pregunta:
¿Por qué ha puesto Dios a Su pueblo en todas las edades y generaciones en tal dificultad,
como es caminar de manera contraria al mundo y ser objeto de su odio,
desdén y persecución?

[.discourse-part]
Respuesta: ¿Cómo podría ser de otra manera,
siendo que Su pueblo es engendrado de un Espíritu que es contrario al
mundo y que testifica contra él al mostrar que su obras son malas?
¿Cómo no va a volverse el espíritu del mundo contra estos y odiarlos y perseguirlos?

[.discourse-part]
Pregunta: ¿Por cuánto tiempo será de esta manera?

[.discourse-part]
Respuesta:
Hasta que la verdad sea levantada por el poder de Dios con
dominio sobre el espíritu y poder de las tinieblas.
El Espíritu de vida sufre ahora bajo el peso de las corrupciones del hombre,
y en amor a ellos se esfuerza por salvarlos.
Hay algo en cada pecador que por temporadas gime bajo el peso de sus pecados,
y en alguna proporción lucha contra el peso de los mismos.
Este algo no siempre yacerá debajo,
sino que en el día del Señor se levantará sobre el transgresor.
En ese día Israel será glorioso con Su Dios, recibirá elogios de Él,
y será aliviado de todo lo que lo ha oprimido.

[.discourse-part]
Pregunta: ¿Habrá un día así?

[.discourse-part]
Respuesta: Las Escrituras testifican de ese día;
el día en el que el Señor "`solo será exaltado,`" en el que "`quitará la afrenta
de su pueblo de toda la tierra`" y derribará "`todo lo alto y levantado`" por
encima del temor y Espíritu del Señor. En esta nuestra era,
el Señor ha escogido muchos mensajeros para que corran arriba y
abajo proclamando este día. Y tan seguro como el Señor vive,
lo que Él ha dicho se cumplirá y ni una tilde de ello caerá a tierra.

Dios no hizo al hombre para que les sirviera a sus propias concupiscencias,
ni a Su creación para que les sirviera a las lujurias del hombre.
Antes bien, hizo al hombre para que temiera delante de su Creador y le sirviera,
e hizo las criaturas para que fueran ordenadas por el hombre
en el temor y sabiduría de Dios y para la gloria de Dios.
El Espíritu de Dios gime ahora bajo la iniquidad del hombre
y los espíritus de Su pueblo también lloran y anhelan.
De hecho, las criaturas mismas gimen bajo la esclavitud de la corrupción,
y el Dios de compasión oye sus clamores.
Un día, un poderoso día de redención y liberación está determinado,
en el que el espíritu del mundo será hundido con todo su peso de maldad,
y el Espíritu de vida y justicia será levantado en Su gloria.
