== Capítulo XII. Algunas Preguntas y Respuestas Para Que los Ojos Sean Abiertos

Pregunta: ¿Cómo llegó a caer el hombre de su condición original?

Respuesta: No voluntariamente ni por inclinación propia,
sino engañado para que considerara el deseo de ensanchar su bienaventuranza
más allá de los límites de la voluntad de su Creador.

Pregunta: ¿Cómo pudo entrar tal tentación en el hombre cuando era puro y santo,
inclinado hacia el bien y en contra del mal, según la imagen de su Creador?

Respuesta:
El hombre no fue creado para que disfrutara perfección en sí mismo separado de su Creador,
o para que viviera por sí mismo, sino para que viviera en dependencia.
Y aunque en sí mismo no tenía inclinación a buscar vida en él fuera de la fuente,
sí había en él la capacidad de hacerlo.
Fue ante esta capacidad que el tentador puso su cebo,
para hacer avanzar al hombre hacia una mayor sabiduría,
gloria y excelencia que en la que lo había colocado su Creador.
Entonces el hombre, al considerar la oferta en independencia de su Creador,
cayó de lo único que era capaz de sostenerlo en el
estado puro en el que había sido hecho.
De esta manera fue cogido en la trampa de la miseria y llevado a esa pérdida
en la que todos los hijos de Adán siguen esclavizados hasta el día de hoy.

Pregunta: ¿Cuál es el estado del hombre desde la caída?

Respuesta: Es un estado de tinieblas, un estado de muerte,
un estado de profunda esclavitud, en el que su alma,
su cuerpo y su espíritu se han convertido en tinieblas en cuanto
a la luz de Dios y en muerte en cuanto a la vida de justicia;
el hombre es cautivo de ese espíritu que ha entrado en él por haberlo
oído. Dicho espíritu mora y gobierna ahora en él en las tinieblas,
como Dios lo hacía antes en la luz.

Pregunta: ¿Cómo es el hombre tinieblas?
¿Cómo es el hombre muerte?
¿Está su alma o su cuerpo muerto en cuanto a su ser?
¿Cómo es esto?

Respuesta: El hombre no está muerto en lo que se refiere a su ser, ni en alma,
ni en cuerpo, pero sí en cuanto al estado recto, puro y santo de cada uno.
Las vasijas siguen siendo las mismas en el ser,
pero están vacías de su licor apropiado y llenas de otro vino.
El entendimiento es el mismo, la razón es la misma, la voluntad es la misma,
la memoria es la misma y los miembros del cuerpo
son los mismos en cuanto a su ser o materia,
pero todos están completamente leudados y ahora habita
otro rey en ellos que reina sobre ellos.

Pregunta: Entonces,
¿es necesaria la destrucción de la razón del hombre o de reducirla a nada,
o sólo es necesario un cambio de levadura?

Respuesta: El hombre se ha convertido en otra cosa por haber caído de la vida.
Está tan envenenado por el pecado y la corrupción que debe
ser totalmente quebrantado y reducido a nada,
aún en las capacidades naturales,
para que pueda ser hecho de nuevo y edificado en la novedad del Espíritu.
En consecuencia, debe convertirse en un tonto,
llegar a ser como un niño pequeño y ser formado y nacido del Espíritu.
Conforme brote en la vida debe ir olvidando su propia tierra,
porque ahora vive en el Espíritu y camina en el Espíritu.
Mientras vigile en el Espíritu y contra su propia
razón en la inocencia pura como la de un niño pequeño,
eventualmente encontrará su razón formada de nuevo y brotando en él. Pero si el ojo
de la razón se abre demasiado rápido y no se mantiene fijo en la luz de la vida,
el traidor entrará por esa puerta de nuevo y llevará al alma a la muerte,
incluso después de haber saboreado la dulce y preciosa virtud y poder redentor.

Pregunta:
¿Puede el hombre en la caída ver su estado caído y así buscar recuperarse de ella?

Respuesta:
Es imposible para el hombre hacerlo sin algo de luz brillando sobre él desde el Redentor.
¿Cómo pueden las tinieblas descubrir las tinieblas?
Es la luz la que pone de manifiesto las tinieblas.
Cuando la vasija es tinieblas y el príncipe de las tinieblas la llena y habita en ella,
qué puede ver ese ojo sino aquello que está en concordancia con las tinieblas,
juzgando el mal como bien y el bien como mal,
lo amargo como dulce y lo dulce como amargo.

Pregunta: Pero, ¿no tiene todo hombre al menos algo de luz, en uno u otro momento,
por la que puedan ver el bien o el mal en alguna medida?

Respuesta:
Este ver no proviene de la luz de la naturaleza del
hombre tal y como esta es ahora en la caída (la cual,
al estar totalmente en manos del enemigo y haberse convertido ella misma en tinieblas,
no puede hacer consciente al hombre de las tinieblas),
sino de una visitación fresca de la vida,
la vida que le da a todos los hombres un día de visitación
por medio del resplandor de su luz.
El Espíritu vivo también lucha con el hombre, atrayéndolo de uno hacia el otro,
según el beneplácito del Señor.

Pregunta: Pero,
¿no tiene el hombre una especie de luz natural en la condición
caída que descubra para él el bien y el mal?

Respuesta: No, no una verdadera luz, ni un verdadero descubrimiento,
lo único que tiene es algo que el enemigo pone en el hombre para mantenerlo
en los enredos del engaño y libre de la sospecha de este.
Porque el enemigo, entrando en el hombre sutilmente,
ciega y engaña sus ojos (para retenerlo cautivo en el engaño) a tal punto,
que este no puede discernir la imagen falsa que el enemigo ha estampado
en él. Porque aunque el enemigo lleva al hombre a un estado de tinieblas,
muerte y cautiverio real, estas cosas no le aparecen a este como lo que son,
pues han sido desteñidas o pintadas para aparentar lo que no son,
y así mantenerlo engañado, hechizado y enredado en ellas.
El enemigo no le presentó a Adán las tinieblas,
la muerte y la cautividad con una apariencia espantosa,
más bien las retrató como sabiduría, como luz, como mejor vida, como mayor libertad.
De esta manera, aún ahora, él entra en el hombre y según esta misma manera mora en él,
hasta que la verdadera luz lo persiga revelando y descubriendo
su engaño. La luz entonces saca al hombre de ese falso paraíso
de placer en la sabiduría humana y de libertad fuera de la vida,
y lo introduce en una consciencia de su carencia y anhelos
tras el verdadero jardín del Dios vivo.

Pregunta: ¿Se equivoca el hombre entonces en su juicio del bien y del mal desde la caída?

Respuesta: Sí, se equivoca por completo.
Por este error el hombre se coloca a sí mismo y establece
su residencia en el reino de las tinieblas,
en el que hay fortalezas y sabios razonamientos contra el
verdadero Dios y a favor de las falsas apariencias del bien.
Así que,
tanto en personas individuales como en sociedades el mal es seguido y afirmado como bien,
y el verdadero bien es suprimido como mal mediante la obra del
misterio de las tinieblas en los corazones de los hombres.

Pregunta: ¿Cuál es entonces el verdadero estado y condición del hombre en la caída?

Respuesta: Un estado de luz falsa, vida falsa, libertad falsa.
A él le parece avanzar en sabiduría por encima de la baja,
vacía y desnuda condición de inocencia (la cual es nada y no tiene nada,
salvo lo que tiene por una continua dependencia de la bondad del Creador).
También le parece avanzar en vida y en libertad; puede hablar sus propias palabras,
pensar sus propios pensamientos, hacer su propia voluntad, buscar su propio bien,
complacerse y satisfacerse.
La vida de justicia le parece un yugo, una especie de servidumbre,
y cree que es libre de la restricción de ella porque tiene
vida en sí mismo y es extremadamente sabio en su opinión.

Pregunta: ¿Cuál es la obra de redención?

Respuesta: Purgar la vieja levadura de la vasija,
purificar la vasija de todas las falsas apariciones de la luz,
derribar todas las fortalezas del enemigo en la mente, todos los razonamientos,
pensamientos, imaginaciones y consultas.
Luego,
crear y formar nuevamente la vasija a imagen de la sabiduría
y pureza en la que fue formada primero.

Pregunta: ¿Quién hace este trabajo, o quién redime al hombre de la caída?

Respuesta: La Palabra Eterna o el Hijo del Padre, es decir,
la sabiduría y el poder que salieron de la fuente para crear todas las cosas.
La misma Palabra sale del seno del Padre para purificar a la criatura y así llevarla
de vuelta (habiendo sido purificada y limpiada) a Su seno de nuevo.

Pregunta: ¿Con qué redime esta Palabra o Redentor?

Respuesta: Con Su propia vida, con Su propia sangre,
con Su propia virtud y pureza eternas.
Él desciende a las profundidades de la tierra, se hace carne ahí,
siembra Su propia Semilla en Su tierra preparada, engendra de Su carne y de Su hueso,
a Su propia semejanza, y alimenta con Su propia carne y sangre para vida eterna.

Pregunta: ¿Qué es esta vida?
O, ¿cómo se manifiesta inicialmente en las tinieblas?

Respuesta: Ella es la luz de los hombres.
Ella le dio luz a Adán al principio,
otra vez a él después de la caída y a todos los hombres
desde la caída. Es Su naturaleza alumbrar.
Ella alumbraba bajo la ley, alumbró bajo el evangelio antes de la apostasía,
y de nuevo desde la apostasía.

Pregunta: ¿Cómo alumbra la luz?

Respuesta: Mediante su brillo.
La Palabra eterna se mueve, la vida se abre, la luz brilla.
Esto, en menor grado, es un principio de redención, y en su plenitud,
es redención perfeccionada.

Pregunta: ¿Cómo obra redención la luz en su brillo?

Respuesta: De dos formas.
Primero, al volver el corazón de las tinieblas hacia sí misma.
Segundo, al ejercitar el corazón que ha vuelto.

Pregunta: ¿Cómo vuelve el corazón de las tinieblas?

Respuesta: La luz, mediante su brillo e iluminación encuentra lo suyo,
lo abre y lo toca con una virtud secreta,
la cual persuade y traslada el corazón del principio
y poder de la muerte y tinieblas a su propia Fuente.

Pregunta: ¿Pueden ser apagadas estas persuasiones y la obra de Dios detenida?

Respuesta: La planta del Señor es muy tierna, su Espíritu puro celoso,
el enemigo muy fuerte y sutil, a tal punto,
que la planta misma puede ser fácilmente aplastada,
el Espíritu afligido y apagado y el cautiverio redoblado.

Pregunta: ¿Cómo ejercita Dios el corazón que se vuelve?

Respuesta: En fe y obediencia,
a través de muy grandes variaciones y cambios de condiciones.
Él lo ejercita para que crea en Su voz,
obedezca Su voz y lo siga en lo que sea que requiera y hacia donde Él lo lleve.

Pregunta:
¿Cuáles son los varios estados o condiciones en los que
Dios ejercita el espíritu del hombre en fe y obediencia?

Respuesta: Los estados y condiciones particulares son innumerables,
pero pueden ser resumidos bajo estos tres principios generales: Primero,
echar abajo el edificio anterior.
Segundo, devastar o preparar para edificar nuevamente.
Tercero, reedificar.

Dios no olvida,
antes bien ejercita a Su pueblo en Egipto cuando aún están
bajo servidumbre y antes de que lleguen a recibir Su ley.
Primero los visita en la tierra de tinieblas,
les abre el ojo que puede ver el cautiverio,
causa gemidos y suspiros en sus oprimidos espíritus,
les declara la promesa y los prepara para la salida de esa tierra.
Luego se toma un tiempo para despojarlos,
nutrirlos y educarlos bajo Su disciplina e íntimos ejercicios.
Aquí están desolados y listos para pecar y perecer en cada momento,
pero también están maravillosamente abastecidos y son abundantemente ayudados y perdonados.
Entonces, después de haber sido preparados para su entrada en la tierra de vida,
viene el estado en el que las piedras son reconstruidas
en un nuevo edificio a fin de que la vida more en él.

Pregunta: Explique más claramente estos estados y los ejercicios en estos.
Primero muestre cuál es el estado del alma en el Egipto espiritual,
cuando el Señor la visita ahí con Su luz.

Respuesta: Es un estado de profunda esclavitud y gemido bajo el poder de las tinieblas,
donde las amargas opresiones se incrementan a medida
que aumentan la sensibilidad y el cansancio del alma.
Entonces,
el alma discierne su cautiverio lejos de la vida y descubre
una edificación de muerte y corrupción levantada en ella,
en donde el príncipe de las tinieblas habita y gobierna.
¡Oh,
cuánto gime y anhela salir de esa tierra y espera la promesa de redención fuera de ella!
Pero todavía es dejada en manos del enemigo,
y diariamente siente la amarga servidumbre de la poderosa ley del pecado
y muerte que brota en el corazón y fluye a través de los miembros.

Pregunta: ¿Cómo son ejercitadas la fe y la obediencia aquí?

Respuesta: Al creer la promesa, al esperar la promesa,
al sentir algunos remotos jalones de la vida y unirse a ellos en la medida de lo posible,
en este estado oscuro y esclavizante.
Aquí ocurre un reconocimiento del verdadero Príncipe y una
inclinación hacia Él aún en este estado de cautiverio,
hasta que a Él le plazca romper las ataduras.

Pregunta: ¿Cuál es el estado del alma en el desierto espiritual?

Respuesta: Es un estado de espera; se espera la guía del Líder,
recibir la dirección y las leyes que provienen del Líder y en el
que se sigue al Líder por donde a Él le plazca conducir.
Es el estado en el que Él dirige a través de los enredos, tentaciones,
estrecheces y necesidades con las que Él considera conveniente ejercitar al espíritu,
para que esa parte que no ha de heredar se desgaste
y para preparar al verdadero heredero para la herencia.

Pregunta: ¿Cómo son ejercitadas aquí la fe y la obediencia?

Respuesta:
Al esperar en la luz la guía de la ley de la vida y al sujetarse
al Líder contentos con todas Sus administraciones ahí;
con el momento que Él escoja para quedarse quieto,
con el momento que Él escoja para viajar,
con la proporción de luz y guía que Él juzgue adecuados,
con la comida y ropa que Él prepare y preserve,
y con los enemigos que Él vea adecuados evitar o enfrentar.
De este modo, la propia sabiduría del hombre, la propia voluntad del hombre,
la propia fuerza del hombre, los deseos propios del hombre,
los deleites propios del hombre, con todas las murmuraciones,
cansancio y descontento que se levanten de la parte terrenal,
sean desgastados gradualmente y una vasija pura sea
preparada para que el nacimiento puro brote y aparezca.

Pregunta: ¿Qué es el Canaán espiritual, o estado celestial, o estado del evangelio?

Respuesta: Es el estado de regeneración o de renovación en la vida e imagen pura,
donde el edificio hecho sin manos es erigido,
donde hay un crecimiento dulce y pacífico en la vida
y un disfrute fresco y satisfactorio de la vida.

Pregunta: ¿Cómo son ejercitadas la fe y la obediencia aquí?

Respuesta: Al permanecer en la vid,
al extraer de la vid la savia y la virtud y retornarlo a ella,
y al vivir según la voluntad de la vid en la libre administración de la misma.
En consecuencia,
las obras son excluidas junto con el yo (de donde
provienen) y la vid se convierte en el todo en todos.

Pregunta: ¿Son los estados de Egipto,
el desierto y Canaán tan distintos espiritualmente como lo eran naturalmente?

Respuesta: Sí, existen diferencias entre los estados espirituales.
Es posible que un hombre esté espiritualmente en Egipto,
pero de ningún modo en el desierto o Canaán. También existe un estado en el desierto,
en el que se está fuera de Egipto,
pero no se ha llegado aún a Canaán. Y también hay un estado en Canaán,
en el que se está más allá de Egipto y del desierto.
Con todo, estos estados a menudo se entretejen en el espíritu,
junto con los ejercicios en ellos, a tal punto,
que en algunos aspectos (en su propio entendimiento)
un alma puede estar parcialmente en Egipto,
parcialmente en el desierto y parcialmente en el reposo, la vida y la paz.
Sin embargo, estas cosas no deben ser examinadas con curiosidad,
para que no se levanten una sabiduría y un conocimiento erróneo,
sino que al permanecer baja y pequeña en la pequeña Semilla,
el reino y la herencia eterna crezcan día a día en el alma, y el alma crezca, a su vez,
día a día dentro de ella y se ensanche en ella.

Pregunta: ¿Hay algún regreso a Egipto o al desierto,
después de que el alma ha avanzado hasta muy alto,
después de que la entrada a la herencia eterna ha sido administrada
y el alma ha encontrado un lugar de reposo en la vida?

Respuesta: El enemigo permanece cerca para engañar y tiene poder para tentar.
Si uno escucha sus tentaciones,
en esa misma medida se va a producir una salida de la vida pura y un regreso al cautiverio
o a la confusión. La preservación está en la fe y en la obediencia a la luz de la vida,
fuera de ella hay muerte y destrucción eternas.

=== La Enseñanza, Disciplina y Ejercicio del Alma

Pregunta: ¿Cómo redime al hombre el Hijo de Dios o la Palabra Eterna,
en Quien está la luz de la vida, y lo saca del estado caído,
del reino de las tinieblas y muerte,
y lo lleva al reino de eterna justicia y paz en la vida?

Respuesta: De tres maneras: Primero, hiriéndolo en el estado natural y corrupto,
rompiendo así su paz y placer en el reino de las
tinieblas y haciendo que se canse de este.
Segundo, debilitándolo bajo las enseñanzas y azotes de la ley.
Tercero, sanándolo y vendándolo con el aceite de salvación,
en el poder de la vida indestructible, el cual es el evangelio.

Pregunta: ¿Cómo lo hiere Dios en el estado natural y corrupto?

Respuesta: Persiguiéndolo con Su luz,
la cual le permite ver su condición y le descubre el mal y el peligro de ella.
Así desteta su corazón de dicho estado y lo hace buscar y anhelar un redentor.
¡Oh, cuán gravoso es el cautiverio para el alma despierta,
cuando ha tenido un vistazo de lo que era el hombre antes de su
caída (cuando el hombre tenía un lugar y un ser en la vida,
con un espíritu adecuado para la vida)! ¡Cuán horrible es ver el
estado presente de alejamiento y separación de la vida,
y saber hacia dónde va el hombre en su camino de injusticia, alejamiento y separación!

Ahora,
mientras el corazón del hombre se está volviendo de la tierra de muerte y cautiverio,
y anhela el poder redentor y la virtud de la vida,
el enemigo (el poder de las tinieblas) pone cargas sobre él,
atrayéndolo bajo las cadenas y lazos de iniquidad, más y más y con la mayor de su fuerza,
para que abunde la concupiscencia,
se incremente el mal y se multipliquen las tentaciones y trampas.
En verdad, en la tierra de cautiverio la fuerza de estas es grande,
el alma es débil y frágil, y el poder redentor y la virtud parecen muy lejanos.
Ahora,
el estado de conversión sucede cuando el Señor (en medio del poder de
la muerte y de las tinieblas) vuelve el corazón de estas cosas hacia Él,
y aún bajo cautiverio,
hace que espere la aparición del brazo de Su fuerza para
romper del cuello de los oprimidos el yugo del opresor.
Así saca el alma de la tierra de muerte y tinieblas,
y se la lleva en el viaje hacia la tierra de la promesa, donde la paz, la vida,
la libertad en el Señor, el reposo, el gozo,
el pleno contentamiento y la felicidad son cosechados
por el alma que sigue al Cordero hasta allí.

Pregunta: ¿Cómo debilita Dios a la a criatura bajo las enseñanzas y azotes de la ley?

Respuesta: Ejercitándola con respecto al bien y al mal,
y corrigiéndola por su incredulidad y desobediencia, cuando la encuentra buena,
justa y necesaria para él.

Pregunta: ¿Cómo ejercita Dios al hombre con respecto al bien y al mal, y cómo lo corrige?

Respuesta:
Después de que Él ha sacado al hombre de debajo del
poder de las tinieblas en alguna medida,
y en alguna medida lo ha liberado mediante la virtud de Su vida que brota en el corazón,
entonces ejercita el corazón y la conducta hacia el bien y los aleja del mal.
Luego da leyes a favor o en contra de cosas,
según lo considere más apropiado para el estado de cada alma en particular.
Ahora, después de la dádiva de la ley (la vida siendo levantada en alguna medida),
está lo que ama sus enseñanzas y senda pura, y está también lo que se retira de ellas.
Puesto que esa parte que retrocede es todavía fuerte,
vienen muchos golpes y azotes del Señor sobre Su propio amado hijo.
¡Estos en verdad son amargos!
Como también es amargo,
ser forzado hacia el pecado que ahora el corazón aborrece y del que se ha vuelto (en
parte por la fuerza del enemigo y en parte por causa de su propia debilidad y negligencia),
y ser mantenido lejos del bien que se anhela y al que el corazón está unido.
Y así, el alma clama día tras día,
y encuentra esta administración de la ley casi tan
pesada como el yugo en la tierra de servidumbre,
debido a su debilidad por causa de la carne,
y por la fuerza y ventajas que la corrupción del
corazón y el príncipe de las tinieblas tienen.

Pregunta: ¿Cuál es el beneficio de estos ejercicios sobre el alma?

Respuesta: Ellos ablandan, ellos quebrantan,
ellos hacen que el corazón sea tierno y apto para
ser moldeado por la virtud y poder eternos,
en una vasija para el poder.

Pregunta:
¿Hacia cuáles condiciones espirituales dirigen estos ejercicios el corazón o la mente?

Respuesta: Hacia unas muy preciosas.
Por ejemplo: En primer lugar, hacen que el espíritu sea pobre.
Las incursiones diarias del pecado y de la corrupción que
se apresuran contra la ley de la vida santa y justa,
que dominan los fuertes deseos en pos de la pureza y fuerzan hacia la impureza,
que impiden que el alma haga lo que ama, y que haga lo que odia,
hacen que el espíritu sea más y más pobre y se aflija más día a día. Tras
algunas visitas de la vida pura y alguna virtud fresca recibida,
¡oh, cuán fuerte parece el alma!
Pero cuando repentinamente es privada de sus misericordias,
pierde su frescura y cae en el hoyo más profundo que antes,
¡cuán pobre y débil se siente entonces!
Luego tiembla en las siguientes revelaciones de la vida y en el surgimiento de su virtud,
sin saber cuánta debilidad, cautiverio,
enredos y miseria provenientes de las trampas de muerte siguen!

En segundo lugar, llevan a una condición de luto.
Llenan los ojos de lágrimas y el corazón de pena.
Sí, abren una entrada a la casa de luto.
Al haber experimentado muchas heridas, moretones y trampas,
al haber entristecido al Espíritu y provocado al Libertador, y de este modo,
al haberle dado más ventajas al enemigo, etc.,
el corazón es abrumado de dolor y le causa una continua
pena y lamentación a esa parte que es recta hacia Dios.

En tercer lugar, llevan a una condición de mansedumbre,
misericordia y ternura de corazón hacia los demás. El que es tentado,
el que a menudo cae y es a menudo herido y desdichado,
se compadece de los que se equivocan.
Se duele por los desdichados.
Su corazón se rompe con los pecados y aflicciones de los otros,
y no puede ser duro con ellos al sentir él mismo continua necesidad de abundante misericordia.
El hombre rico, el hombre sólido en religión es áspero y duro,
pero el que ha sido completamente derretido en el horno y edificado otra vez es blando,
y conserva el sentido de mansedumbre, amor y misericordia para siempre.
Ahora, el estado quebrantado en la religión, o el estado de espera de la vida,
es mucho más precioso que ese que parece rico y pleno por lo que recibía antes,
y por lo que sostiene fuera de la directa experiencia y virtud fresca de la vida.

En cuarto lugar, llevan a una condición de hambre y sed de santidad y justicia.
¡Oh,
cuánto desea el alma que es consciente de su inmundicia
ser lavada! ¡Cuánto anhela los pastos de vida,
la comida de vida,
el agua viva! ¡Cuánto ansía presentarse ante Dios
y disfrutarlo en la tierra de los vivos! ¡Oh,
cuánto anhela el corazón que diariamente es afligido por su incredulidad y desobediencia,
la fe que permanece en el poder y la obediencia que fluye de este! "`¡Oh,
enséñame Tus estatutos; muéstrame la senda pura de obediencia en el camino de vida,
guía mis pies en el camino eterno! ¡Escribe Tu temor en mi corazón para
que yo no me separe de Ti! ¡Crea un corazón limpio en mí y pon Tu Espíritu
dentro de mí para que sea mi fuerza! ¡Continúa con Tu amorosa bondad hacia
los que Te conocen y con Tu justicia hacia los de recto corazón!`" ¡Oh,
cuán indescifrables respiraciones salen diariamente del
espíritu quebrantado hacia la fuente de su vida!

En quinto lugar, llevan a un estado puro, a una limpieza del interior.
"`Limpia primero lo de dentro del vaso y del plato,`" les dijo Cristo a los fariseos.
Esto Él lo hace también en Sus verdaderos discípulos.
"`Con la mente sirvo a la ley de Dios,`" dijo Pablo cuando clamaba:
"`¡¡Miserable de mí!! ¿quién me librará?`" No se puede concebir cuánta pureza de corazón
puede formar Dios en Su Israel mediante el fuego que Él enciende en Su Sión y por el
horno que Él establece en Su Jerusalén. Pues mientras en el horno todavía aparezca escoria
(o se vea lo que es capaz de abatir y afligir el precioso corazón),
el ablandamiento y la purificación continuarán dulcemente y el
alma que permanezca en el calor será efectivamente limpiada.
De hecho, esta limpieza es evidentemente manifiesta después,
cuando la justicia brota con su fruto apacible,
pero mientras las llamas todavía están poniendo al
descubierto la injusticia y apoderándose de ella,
no se puede discernir.

En sexto lugar, llevan a una condición de paciencia,
apta para soportar las críticas y persecuciones del mundo, el cual,
en medio de toda esta debilidad, miseria y angustia, pone cargas sobre la pobre alma,
persigue al que Dios ha golpeado, y con lo que habla lastima al que Dios ha herido.
Dios lo disciplina por falta de obediencia,
por demasiada propensión a complacer al mundo,
por no salir suficientemente rápido de sus costumbres, vanidades,
caminos mundanos y adoraciones.
Pero tan pronto como el corazón y la conducta se rinden en obediencia al Señor,
el mundo se disgusta y entonces los hiere y persigue debido a la obediencia.
Ahora, cuánto más quebrantado sea el espíritu por la mano del Señor,
más enseñando sea a temerle;
y cuánta menos fuerza tenga en sí mismo para luchar
contra el espíritu perseguidor del mundo,
más apto será para permanecer en el consejo de Dios.
Sí, ahora es más apto para esperar Su fuerza y protección,
lo cual es capaz de sostener su cabeza por encima de toda furia y acrecentamiento
de las aguas del espíritu mundano que está en los hombres de este mundo.

Se podría decir mucho más, pero esto puede ser suficiente.
Lo que haga falta aquí será sentido interiormente,
conforme el alma espera en Dios y en la guía de Su Espíritu, a través de las enseñanzas,
azotes y angustias de la ley.

Pregunta:
¿Con qué tipo de cosas ejercita el Señor los espíritus de Su Israel para
llevar sus corazones hacia estas y otras preciosas condiciones similares?

Respuesta: Con varias clases y tipos de cosas, tanto externas como internas, tales como:
En primer lugar, con oposiciones,
críticas e interrupciones provenientes de la parte terrenal,
tanto en los hombres de este mundo, como en sí mismos.
Hay mucho dentro y mucho fuera que buscará resistir,
despreciar e interrumpir la obra de Dios en el corazón. Sí,
hay mucho que se opondrá y se resistirá a lo que Él ha engendrado ahí,
a Su guía y a la obediencia a Él.

En segundo lugar, los ejercita con tentaciones del enemigo de muchos tipos,
naturalezas y grados según el estado de ánimo y condición del alma.
Hay tentaciones para que duden y se desesperen,
o para que tengan confianza en la carne por el conocimiento recibido
fuera del temor puro y de la fresca experiencia de la vida.
Hay tentaciones para que se detengan o para hacerlos retroceder,
o para que se apresuren y se adelanten, y así,
o bien dejan de obedecer y actuar para Dios,
o actúan en esa voluntad y sabiduría que están contra Dios.
Ahora bien, estas, junto con otras tentaciones similares, son muy numerosas,
frecuentes y a veces muy violentas e impulsivas.

En tercer lugar, los ejercita al replegar Su vida y dulce presencia del alma.
Esto es muy frecuente por parte del Señor hacia Su pueblo, a tal punto que es llamado:
"`El Dios que esconde Su rostro de la casa de Jacob.`"
(Isa.
8:17; 45:15)

En cuarto lugar, con bofetadas y predominio del enemigo.
Cuando el Espíritu es contristado y la vida herida y replegada al interior,
el enemigo con frecuencia gana terreno, hiere y le hace moretones al alma.
Este no sólo tienta,
sino que encuentra entrada y coge en la trampa al ave que una vez escapó y fue liberada.

En quinto lugar, con dudas,
temores y razonamientos confusos con respecto a la voz de Dios y la voz del enemigo.
En la hora de oscuridad (cuando al Señor le parece bien permitir
el poder de las tinieblas y retirar los rayos de Su luz),
¿cómo puede ser distinguido claramente lo que sólo se conoce y se ve en la luz?
¿Cómo pueden ser distinguidos los movimientos,
persuasiones y obras puras y bajas de la vida,
de las imágenes y transformaciones falsas del enemigo?
¡Oh,
la miseria y la angustia de la pobre alma en esta condición! ¡Cómo
se aflige el pobre y recto corazón entre la fe y la incredulidad,
entre la obediencia y la desobediencia,
sin saber cuándo es arrastrado hacia adelante o hacia atrás, o por quién!

Pregunta: ¿Cuándo comienzan estos ejercicios y por cuánto tiempo continúan?

Respuesta: El Señor empieza a ejercitar el alma incluso en Egipto.
Porque después de la promesa de liberación del Faraón espiritual,
la esclavitud se acrecienta,
el yugo se hace más pesado y Faraón se vuelve más violento y furioso.
En realidad, el cautiverio se incrementa mucho y no hay redención a la vista,
excepto para ese ojo que es débil y fácilmente dominado en Israel.
Pero los ejercicios son mucho más completos y agudos en el desierto,
donde Israel es conducido, probado, afligido y consumido día a día,
como si nunca fuera a llegar a la tierra santa,
ni nadie de Israel quedara vivo para entrar.
Sí, y en Canaán también, en la rica posesión,
en los abundantes desbordamientos de la vida,
todavía queda algo que probar y someter en Israel,
en caso de que se exalte con la gloria y plenitud
de su propio estado y empiece a olvidar a su Dios.

Pregunta: ¿Por qué ejercita Dios a Su Israel de este modo?
¿Por qué los conduce de esta forma tan complicada,
por qué no los lleva de una manera más fácil y rápida
a la posesión eterna y plenitud de la misma?

Respuesta: Porque el estado y condición de ellos lo requiere.
Porque de otra manera no podrían ser purificados y preparados para la vida.
Sus vasijas no serían tan amplias como para recibir
la vida ni podrían disfrutarla con seguridad,
si no fuera por este camino de sabiduría. En él Dios ejercita y
trata cada grieta de sus espíritus hasta que los haya preparado
y haya detenido la entrada de la muerte en todas partes.

Pregunta: ¿Cómo los purifica y los ensancha estos ejercicios?

Respuesta: En primer lugar, prueban la fuerza y la virtud de la vida en ellos,
y les descubre su mayor necesidad de ella.
En tiempos de prosperidad del alma parece haber suficiente,
pero el día de angustia pone de manifiesto el estado y condición tal cual es.
Entonces la fe, el amor, la paciencia, la mansedumbre,
la constancia y castidad ante el Novio (amándolo y uniéndose a Él sobre todo y en todo),
muchas veces resulta ser menos de lo que se juzgaba.

En segundo lugar, los llevan a esperar en Dios Su apoyo y a recibir más de Él. Entonces,
la vida respira vigorosamente y el alma anhela,
se aferra y ve su necesidad tanto de la presencia
de la vida como del incremento de su virtud.
Luego, el que era rico se hace pobre, y el que estaba lleno queda vacío y se vuelve nada.
Sí, el que tenía suficiente para vivir y hasta más, ahora está estrujado por el hambre,
la carencia y la pobreza.

En tercer lugar, los preparan para una entrada más clara en la plenitud,
y para un disfrute más seguro de esta.
Cuánto más vaciada es el alma de la fuerza y de las riquezas que recibió de Dios,
más preparada está para entrar y vivir en el Ser Puro mismo.
Porque nada velado puede vivir ahí. En la vida Dios era,
es y debe ser todo en todos por siempre.
Por tanto, lo que entre ahí y viva y permanezca ahí, debe ser pobre,
debe estar vacío y desnudo, debe ser nada y permanecer siendo nada por siempre.
Pero si recoge algo de la plenitud y llega a ser algo en sí mismo, será excluido.

Pregunta:
¿Cómo cura y venda Dios lo que ha herido y quebrado
en pedazos con Sus varios y frecuentes ejercicios?

Respuesta:
Al abrir el poder de la vida indestructible en la
vasija que Él ha purificado y preparado cuidadosamente,
y llenándola del poder.
El gratuito poder de la vida es el evangelio,
el evangelio que fue profetizado a los mansos,
a los quebrantados de corazón y a los limpios.
Por tanto, cuando la obra de purificación sea acabada,
la herida sea suficientemente amplia y permanezca abierta suficiente tiempo,
y cuando la muerte del primer esposo sea plenamente cumplida (Rom.
7:4),
entonces el aceite perfecto será completamente derramado
y se obtendrá salud y salvación eternas.
Este es el fin que Dios busca con las visitaciones y guías de Su semilla.
¡Bienaventurados los que pasan por el valle de miseria y beben los sedimentos
de la "`copa de ira`" sin desmayarse ni sentarse en el camino,
sino que siguen al Pastor fiel y Líder de Israel, hasta llegar aquí!

Pregunta: ¿Cuál es el gran peligro en el camino de la vida?

Respuesta:
El gran peligro es ascender un paso más alto de lo
que pueden soportar el estado y la condición presentes.
Por este medio la mente ambiciosa se levanta y se exalta,
y sostiene algo recibido de la vida fuera del temor puro que preserva el corazón limpio,
y fuera de la experiencia viva que mantiene el corazón fresco y vivo para Dios.
Entonces, la sencillez es traicionada, el espíritu malo vive y el ojo incorrecto se abre,
de modo que ya no queda más que la prostitución de la vida.
De hecho, el corazón se exalta y presume en el camino de sus prostituciones,
como si este fuera la cama pura y la más excelente forma de disfrutar la vida.

Pregunta: ¿Cuál es la manera de preservarse de esto?

Respuesta: Vigilando la vida,
manteniéndose bajo el temor y cerca de la experiencia viva de esto.
Aquí el ambicioso es excluido o espiado tan pronto como empieza a entrar,
entonces la cruz viva es recibida, lo crucifica y lo hace retroceder.
En efecto, no hay camino seguro en los viajes del alma hacia el disfrute de la vida,
excepto sometiendo a la cruz ese espíritu y naturaleza
que desean meterse en las cosas de Dios,
complacerse a sí mismos y ser algo ahí, pero siempre olvidan la Fuente pura y eterna,
debido a sus adulterios con eso que mana de ellos.

El hombre fue hecho por Dios para que fuera la vasija de Su placer,
para que como reflejo de Él, recibiera el contentamiento, disfrute y felicidad de Dios.
Así, pues, el trabajo propio del hombre era vigilar la fuente de donde venía,
a fin de estar dispuesto, ordenado y vivir conforme al placer de Dios.
Esto era natural para el hombre antes de la caída,
hasta que un espíritu corrupto (mediante el engaño) entró en él y lo corrompió.
Mientras permanezca algo de este espíritu corrupto o naturaleza caída,
el hombre tenderá a tener aspiraciones en el egoísmo
y a buscar placer en lo que viene de la fuente (sí,
incluso en la fuente misma) en y de acuerdo a la voluntad y sabiduría del egoísmo.
Aquí, incluso los viajeros experimentados pierden su camino,
al caer de su porción en la tierra de la vida y de sus deleites de la vida,
en el espíritu terrenal y carnal, sosteniendo su propia sabiduría y riquezas ahí,
en la parte terrenal, sin saber que han movido su morada ahí.

El que lea estas cosas no se esfuerce en comprenderlas,
más bien conténtese con lo que vívidamente siente
y con lo que es adecuado para su presente estado.
Conforme la vida crezca en él y él en la vida y se
tope con las cosas y ejercicios aquí mencionados,
entonces las palabras y las experiencias relacionadas
con ellos se abrirán a sí mismas para él.

=== Consejo para el Viajero Espiritual

Ahora, aquel que viaja con seguridad en el espíritu hacia la tierra de vida,
espere tener las siguientes cosas escritas en su corazón por el dedo de Dios,
y conocer el verdadero sentido y peso de ellas preservadas frescas en su interior.

En primer lugar, la gracia gratuita de Dios es la que comienza la obra de redención,
la que hace que la luz brille,
la que obra el arrepentimiento o vuelve del estado de muerte,
y la que también obra la creencia y el vuelco hacia el Dios vivo.

En segundo lugar,
la misma gracia es la única que puede preservar y hacer que la planta de gracia crezca.
Si se produce un retiro de la luz, una retención de la influencia gratuita,
de lo que ella depende, no puede conservar su frescura.
Esto lo puede hacer el Señor tan a menudo como le plazca,
para disciplina de la parte rebelde o para probar Su vida y virtud puras en Sus plantas.

En tercer lugar, la gracia de Dios que visita el alma en la muerte, en las tinieblas,
en el estado caído, engendra de nuevo vida en ella y la hace, en alguna medida,
"`luz en el Señor.`" Sí,
esta gracia abre un ojo en el alma para que vea las cosas de Dios y un
oído para que oiga y distinga entre el sonido de la vida y de la muerte,
y obra en el corazón un vuelco y rechazo a toda vanidad
y hace que se vuelva y permanezca en la sustancia viva.

En cuarto lugar, el Espíritu de Dios lleva a cabo la obra de redención al atraer,
conducir y actuar sobre el alma vivificada,
y al ejercitar eso que Él ha engendrado en la vida, bajo la ley de la vida.
Así la vida diariamente acerca más y más el alma
a la fuente eterna y la aleja del pecado que se debilita,
de la vanidad y de la criatura.
Y el alma, por la avivada virtud, diariamente sigue en pos de la vida en la guía,
espíritu y poder de la misma.
Hay un alma viva engendrada por la virtud de la gracia,
dicha alma viva vive en la gracia y viaja en la virtud
de ella de la incredulidad a la fe,
de la enemistad al amor, del camino torcido al camino enderezado,
de la iniquidad a la justicia.
Sí, el alma viva viaja de todos los territorios de tinieblas,
y de las débiles medidas y grados de gracia y vida, hacia la plenitud misma,
hasta estar perfectamente centrada en la vida y llena de ella.

En quinto lugar,
donde la virtud recibida de la gracia se detiene por falta de respuesta en el corazón,
ahí se detiene también la obra de redención. Si el alma no sigue en el llamado,
el llamado se pierde.
Si el oído no se abre para oír la voz de la Palabra,
o si no está acompañada de fe en los corazones que la oyen, resulta ineficaz.
Si la fuerza emana del Señor,
pero el alma no recibe la fuerza que emerge y burbujea en ella,
o no responde rindiéndose a ella y continuando con el viaje,
entonces permanece donde estaba antes (si es que no retrocede más
allá del estado y condición al que la vida la había adelantado).
Porque si la virtud de la vida y de la gracia es rechazada,
le es dada una ventaja a la muerte para entrar de nuevo
y ganar terreno mediante su propia virtud y poder.

En sexto lugar, noten atentamente,
cómo continúa el Señor la dispensación de Su amor y gracia gratuita,
como si mucho fuera por la fuerza y diligencia de la criatura.
¡Cómo se hiere la criatura a sí misma por arrepentimiento!
¡Cómo se esfuerza en creer! ¡Cómo lucha contra los enemigos,
cómo lucha por las influencias de la gracia,
por conservar la esperanza y mantener fuera la desconfianza!
¡Cuán estricta vigilancia y espera se conocen,
como si la criatura hubiera obrado su salvación completa!
Pero aunque parece que la criatura hace mucho por sí misma (al recibir
vida de la gracia y actuar abundantemente para Dios en la gracia),
es la gracia y la virtud que provienen del Creador (quien
es también el Redentor) las que en realidad lo hacen todo.
Pues aunque la criatura verdaderamente se arrepiente
y se vuelve de las tinieblas con todo su corazón,
aún así este arrepentimiento proviene de la virtud que fluye
de la gracia y no de la criatura que recibe la gracia.
Así es también con la fe, el amor, la obediencia, la mansedumbre, la paciencia,
la vigilancia, la espera, la esperanza, etc.
Sí, la aceptación misma de la gracia no es de la criatura, sino de la gracia.
Pues la criatura está muerta hasta que es visitada por la gracia,
y sólo por la visitación de la gracia es vivificada y capaz de recibir.

He aquí el misterio de la redención. Dios está en
toda la redención. Dios hace toda la redención,
es decir, la totalidad de la obra,
tan plenamente como lo hace en la creación (porque
esta es una nueva creación). Sin embargo,
la criatura que es vivificada y renovada está en unión con Él en Sus operaciones.
(Fil.
2:12-13) Aquel que tiene los ojos abiertos puede leer el misterio y con
verdadero entendimiento decir (si ha sido conducido hasta aquí):
"`Soy capaz de hacer todas las cosas a través de Cristo que me fortalece, pero no yo,
sino la gracia de Dios en mí.`"

Ahora bien,
para llevar a la criatura a esto el Señor la ejercita diariamente
en obediencia a Él en la vida y virtud que brotan de Él,
haciendo que la criatura sienta su debilidad y olvide sus ambiciones
de vivir para sí misma fuera de una dependencia real en la fuente.
En efecto, la virtud que proviene de Dios sólo puede responderle a Dios,
y la criatura es aceptada únicamente en la medida que se
encuentre con y en la Fuente y Padre de la vida.

Pregunta: Pero si la obra de redención es forjada por el poder creativo de Dios,
¿por qué se topa con tantos obstáculos e interrupciones, y a veces, hasta es vuelta?
¿Puede algo detener el poder creativo de Dios?

Respuesta: Hay tres cosas involucradas en la redención. Primera,
hay una emisión de gracia gratuita, amor, virtud y poder divino hacia la criatura.
Segunda, de esta manera hay una revelación del estado de la criatura,
convenciéndola y sacándola de su estado de separación
de la vida hacia la unidad con la vida.
Tercera, la criatura debe caminar en pos de la vida,
en la obra de convencimiento de la virtud vivificadora, a través de las trampas,
tentaciones, desviaciones y oposiciones del enemigo.

Bien, no hay obstáculo alguno ante la emisión de la gracia hacia la criatura,
ni tampoco ante la obra de convencimiento e inclinación de la criatura
a seguir al Señor que necesariamente resultan luego.
Pero el seguimiento y progreso de la criatura (o su permanencia en la virtud
y poder vivificadores) pueden ser interrumpidos y desviados de muchas maneras,
y así puede ser sacada de debajo de la influencia del pacto gratuito.
Porque aunque el pacto es gratuito,
la criatura únicamente participa de él en la medida que
es atraída hacia él y preservada en él. Por lo tanto,
que teman los que sienten el poder y la virtud redentora, y sepan,
que a pesar de la promesa cierta y gratuita de la Semilla,
la criatura sigue siendo como arcilla en las manos del alfarero
y puede ser hecha una vasija de honra o deshonra,
según le plazca al alfarero favorecer o tomar ocasión contra ella.

=== El Triple Estado del Hombre

Primero, hay un estado gentil o estado de la naturaleza.

Segundo, hay un estado judío o de la administración de la ley,
en el que Dios toma al hombre bajo Su propia instrucción,
dándole a conocer Su voluntad y exigiéndole obediencia.
Y no sólo esto,
sino que también lo dirige hacia el maestro interior y al principio del temor puro,
que es el lugar de la enseñanza e instrucciones de la sabiduría.

Tercero, hay un estado del evangelio o estado de la fe,
donde la Semilla es levantada y vive.
Sí, la Semilla que hace la voluntad y recibe la promesa es conocida,
disfrutada y sentida brotando en el interior.

En todos estos estados, la ley, la luz, la vida, la sabiduría,
el poder son uno y el mismo, pero las administraciones son diferentes.

En el estado gentil o estado de la naturaleza,
la luz que recibe el hombre (para descubrir el mal y obrar
hacia el bien) es del Espíritu y por la virtud de la promesa.
Porque si no hubiera sido por la promesa,
él habría estado eternamente encerrado en las tinieblas.
En verdad, es por motivo de la promesa y por la gracia gratuita,
que el hombre recibe alguna visitación en su estado natural,
o tiene algún deseo de seguir, o guía hacia el bien y en dirección opuesta al mal.
Nada de esto brota ni puede brotar de la naturaleza corrupta,
sino sólo de la fuente gratuita de nueva vida.

En el estado de la ley la luz se hace más clara.
Aquí el maestro es discernido y reconocido, y sus persuasiones, advertencias,
instrucciones y reprensiones se sienten más claramente,
y el alma (que es vigilante) es continuamente ejercitada en estas.

En el estado del evangelio, el principio de vida es levantado,
la Semilla prometida ha llegado,
el poder que hace la voluntad es recibido y la luz de vida entra y posee la vasija.

Ahora bien, este es todo el deber del hombre:
Esperar la ministración de la vida en su estado actual,
ya sea en el estado de la naturaleza, bajo la ley o bajo la gracia.
Debe saber de dónde brota su redención y debe esperar el brazo redentor para el comienzo,
para el progreso y para el perfeccionamiento de la misma.
Si él ha llegado a experimentar vívidamente dicha virtud, es suficiente.
O, si se mantiene deseando y anhelando en pos de ella, está bien.
De hecho, si sólo hay un deseo en él tras la sed verdadera, hay esperanza, sí;
y si sólo hay en él la menor consciencia de su estado muerto, estéril y sin sentido,
entonces hay algo de la vida que el Señor ama en él,
y el Señor hallará la ocasión de expresar Su compasión hacia esta.
Sí,
el Señor todavía tiene compasión hacia el que se siente
completamente en tinieblas y encerrado en el hoyo,
y después de muchos días puede que se complazca en visitarlo.
¡Oh, la altura, profundidad,
longitud y anchura de las riquezas de la misericordia y amor de Dios! ¿Quién
conoce Sus anhelos hacia las almas y Sus maneras de visitar y redimir?
¡Oh, alma mía,
espera en el Señor para siempre y no dejes de respirar anhelantemente hacia Él,
hasta que tú y toda Su creación se llenen y satisfagan
de Él y encuentres el soplo de vida en Él para siempre!

=== Para Aquellos que Reclaman Falta de Poder de Dios

Pregunta: ¿Qué es Dios?

Respuesta: Él es la fuente de seres y naturalezas,
la sustancia interna de todo lo que aparece externamente, el que crea, sostiene,
consume y lleva a nada, según le place.

Pregunta: ¿Cuáles son sus mandamientos?

Respuesta: Son muchos, pero todos pueden ser referidos a estos dos principales:
Amar a Dios por encima de todo y amar al prójimo como a sí mismo,
haciéndole a él en todos los sentidos,
como a uno le gustaría que él hiciera con uno en caso similar.

Pregunta: ¿Cómo puede realizar el hombre esto?

Respuesta: Sólo recibiendo la Semilla de vida de Dios y manteniéndose cerca de ella.

Pregunta: ¿Cómo puede un hombre recibir la Semilla de vida de Dios?

Respuesta: Dios está cerca de todos los hombres con el aliento de Su vida,
soplando sobre ellos de tiempo en tiempo de acuerdo a Su beneplácito.
Cada vez que el espíritu del hombre se abre a la vida y la bebe,
esta se convierte en Semilla de vida en él esparciéndose
hasta cubrirlo y leudándolo para vida eterna.

Pregunta:
¿Qué le impide al hombre recibir esta Semilla de vida y mantenerse cerca de ella?

Respuesta: La semilla carnal, la cual es contraria al conocimiento,
temor y obediencia al Señor y a todo lo que brota del poder de Su vida.

Pregunta: ¿Cómo llegó esta semilla carnal al hombre?

Respuesta: Fue sembrada por el enemigo en el alma del hombre.
Este le dio entrada en su espíritu al oír sus sugerencias y tentaciones.

Pregunta: ¿Qué ayuda tiene el hombre contra esta semilla carnal?

Respuesta: Ninguna en sí mimo,
pero al ser tocado gratuitamente por la Semilla de vida y gustarla,
debe esperar en la misericordia y gracia de Dios la manifestación de Su luz y poder,
para que le descubra la naturaleza maligna y el curso de su propio corazón,
y corte sus deseos, razonamientos e imaginaciones corruptas.

Pregunta: ¿Cómo puede un hombre llegar a creer en esta Semilla de vida?

Respuesta: Al experimentar Su naturaleza;
esperando experimentar algo engendrado por esa Semilla de vida.
Ahí brota Su luz, brota Su vida, brota Su amor,
aparece Su poder oculto y Su sabiduría y bondad preservadoras
son hechas manifiestas al alma que se aferra a esto.

Pregunta: ¿Cómo puede un hombre llegar a obedecer esta Semilla?

Respuesta: En la fe, al verla y aferrarse a ella,
es emitida fuerza de la Semilla a la criatura y la
hace capaz de realizar todo lo que le pide.

Pregunta:
¿Por qué las personas que llegan a un verdadero comienzo
de la vida y a un fervoroso anhelo en pos de Dios,
se sienten tan débiles y se quejan tanto por la falta de poder?

Respuesta: Porque el enemigo interpone sus razonamientos entre ellas y su fe.
Las tinieblas, el principio de incredulidad,
se encuentra cerca y está levantando lodo (tanto
como sea posible) entre la Semilla de vida y el alma.
Así, en la medida que se interpone entre estas,
perturba tanto los movimientos del alma hacia su fuente de vida,
como el claro burbujeo de la fuente en el alma y su flujo a través de ella.

Pregunta: ¿Qué requiere Dios del hombre?

Respuesta: Él requiere arrepentimiento, fe y obediencia del hombre.
Que se vuelva a Su llamado de las tinieblas a la luz;
que confíe en la luz y se una a ella y que no crea más en el espíritu de oscuridad.
Finalmente, que obedezca la luz,
la siga y camine en los pasos de los vivos hacia la tierra de luz.

Pregunta: ¿Cómo puede hacer esto el hombre?

Respuesta: Por sí mismo no puede, pero al ser tocado,
al ser vivificado por el poder eterno,
al ser vuelto por la virtud secreta y al ser agitada la vida en su corazón,
puede volverse hacia Aquel que lo volvió. Al ser atraído por la vida y por el poder,
puede ir en pos de la vida y en pos del poder.
Tras encontrar la dulzura de la vid viva, y su alma vivificada por la savia de la vid,
su corazón puede unirse y permanecer en la vid y producir
el fruto de la fe viva y de la obediencia al viñador.

Consideren lo siguiente:
¿Es posible que un hombre llegue al eterno reposo si no viaja en la senda verdadera?
¿Hay alguna otra senda además del arrepentimiento,
la fe en el Espíritu vivo y la obediencia a Él? ¿Hay algún
otro camino para el niño engendrado por el poder eterno,
aparte de ser enseñado por el Padre a permanecer y a caminar en la vida y en el poder?

Dios extiende su mano todo el día para traer a casa al hombre perdido.
Él le ha dado un talento, un talento vivo,
el cual es capaz de llevarlo a la vida y de producir los frutos de vida en él. No obstante,
el hombre pasa por alto este talento, no une su corazón a él,
ni tampoco produce los frutos de vida para el Dador, sino que grita que carece de poder.
Grita: "`¿Qué soy yo?
¿Qué puedo hacer?
¿Puedo limpiar mi propio corazón? ¿Puedo matar mis propias corrupciones?
¿Puedo vivificarme a mí mismo?`"...etc.

Ahora consideren lo siguiente también:
Han habido varias dispensaciones de Dios para la humanidad,
en todas las cuales el hombre (en sí mismo) ha quedado corto de la vida, del poder,
de la gloria, y por tanto, cae bajo condenación. Dios culpa al hombre por no escuchar,
por no creer, por no caminar con Él. El hombre culpa a Dios y dice que carece de poder.
Ahora consideren a aquellos que no son obedientes a la luz (de
la cual no pueden sino confesar que brilla en sus corazones y a
menudo los amonesta) y pregúntenles por qué no la obedecen.
¿No es esto lo que alegan?
¿Qué carecen de poder?
Que los hombres consideren, ¿se mantendrá de pie esta defensa delante del trono de Dios?
Esta es la condenación, que los hombre no creen en la luz de la vida,
no obedecen el evangelio de nuestro Señor Jesucristo,
no confían ni siguen la luz que los guiaría a la vida.
Más bien,
confían y siguen las tinieblas que los guiarían hacia la muerte y condenación eterna.
La defensa del hombre es que carece de poder para eso.
¿Es cierto esto?

Confieso que el poder no fluye hacia el hombre en la forma que este lo espera.
El poder de vida obra de manera secreta en el hombre sacándolo de la muerte,
y comienza en él como debilidad.
Al principio,
toda la fuerza y el poder del enemigo están contra la obra de Dios en el corazón,
y no hay más que algo pequeño (como una semilla de mostaza), algo débil,
una tontería ahí, para vencer todo eso, y sin embargo,
en esa cosa pequeñita está el poder.
Este es el gran engaño del hombre:
Que busca un gran poder manifiesto en o sobre él para comenzar,
y no ve que el poder está en los pequeños y débiles movimientos de la vida en el corazón.
El poder está en algo que se levanta contra la poderosa fuerza de corrupción en él,
hacia lo cual debe volverse, unirse y esperar.
La fuerza del Señor se manifestará a su tiempo,
él será acercado más y más al Señor y sus enemigos
serán vencidos y caerán en una forma que él no conoce.
Pero el que espera una aparición poderosa de poder al principio,
busca comenzar de esa manera y ser preservado y llevado así,
no puede caminar en la senda eterna.
Porque el poder de Dios brota como debilidad,
y conduce y vence enemigos obrando de manera misteriosa,
y no en una forma tan manifiesta y directa de conquista
como la sabiduría del hombre espera.

La Semilla del reino es sembrada y crece de un modo que el hombre no entiende,
y el poder aparece y obra en ella en una forma de la que él no es consciente.
El hombre busca el reino,
el poder y la vida según su propia observación y de acuerdo
a los pensamientos y expectativas de su corazón,
pero estos nunca aparecen como el hombre los espera,
sino según sus propios movimientos eternos.
La Semilla del reino brota en los corazones de muchos,
pero ellos la pasan por alto y se vuelven diariamente de ella;
no conocen la verdadera manera en que aparece porque la esperan de otra forma.
Por tanto,
el enemigo los mantiene en la esclavitud de la muerte y son cautivos en tierra extraña,
y rechazan al Príncipe de vida en Su ofrecimiento diario de vida,
porque no Lo buscan en la forma que Él aparece, sino según otra forma y manera.
Hasta que ese ojo que observa sea sacado de ellos,
no podrán ver claramente la manera en que el Salvador se les aparece,
ni sentir la eficacia de Su salvación de aquello que nadie sino Él puede liberar.

=== El Conocimiento Correcto de las Cosas de Dios

Todavía quedan algunas cosas que pesan en mi corazón y que quiero poner delante de ustedes,
las cuales pueden servirles en su condición actual.
Son cuatro proposiciones relacionadas con el correcto
conocimiento de las cosas de Dios y son las siguientes:

Primera, el conocimiento de las cosas de Dios proviene del Espíritu.
Así como las Escrituras mismas salieron del Espíritu,
el verdadero conocimiento de ellas es dado solo al
hombre que las recibe por el mismo Espíritu.
Ningún hombre viviente puede conocer el significado de las palabras que habló el Espíritu,
excepto si el Espíritu que las habló le da el significado de ellas.

Segunda, el conocimiento de Dios (el conocimiento vivo,
el conocimiento útil) está guardado en el Espíritu y en el nacimiento que es del Espíritu.
La parte natural del hombre no es la verdadera tesorería,
ni le fue dada a la razón del hombre ser el amo de
ninguna de las cosas del Espíritu de Dios.
Más bien, lo nacido de la Semilla del reino es lo que sostiene el conocimiento del reino,
la gracia del reino y las experiencias vivas.
La razón del hombre está excluida para siempre de las cosas de Dios,
salvo donde se humilla, está limitada y es sometida a ellas.

Tercera,
el conocimiento recibido del Espíritu todavía tiene que ser probado por el Espíritu.
Únicamente el Espíritu puede mantenerlo vivo y únicamente el Espíritu puede decir
si la vida y la virtud están todavía en él o si la muerte lo ha atrapado.
Sólo el Espíritu puede discernir si es el maná apropiado para alimentar
el alma o si el maná que una vez fue dado ahora está corrompido.
¡Oh, mis queridos amigos, esperen para que entiendan mi experiencia concerniente a esto!
Y es la siguiente:
Yo ciertamente había recibido algo de Dios y al principio
el verdadero nacimiento se alimentó de eso,
pero luego, el nacimiento terrenal buscó atraparlo,
asirlo y atesorarlo para alimentarse en otro momento.
Igualmente en mi lectura de las Escrituras,
a menudo caí en la gran trampa de leer en mi propia
voluntad y de reunir cosas en mi propio entendimiento,
y así crecer sabio con respecto a las cosas de Dios según la carne.
Porque aunque en ese momento yo no carecía de conocimiento vivo y experiencias de Dios,
no sabía aún cómo volverme de la muerte ni cómo mantenerme hacia la vida.
Por lo tanto, lo malo, lo enjuto, lo terrenal,
lo desfavorecido sobrepasó lo bueno y agradable para Dios
y se lo llevó a la amargura de la miseria y de la muerte.
¡Ojalá ustedes supieran qué es ser engendrados por la voluntad del Padre,
mantenerse en la voluntad del Padre y recibir de Sus manos el pan de cada día! Lo que
el hombre concibe con respecto a las Escrituras no es la leche pura de la Palabra,
porque sólo la que dan los pechos tiene la vida, virtud y verdadero alimento en ella.
Esta debe ser devuelta a la divina tesorería; no debe ser guardada en la parte terrenal,
ni en la voluntad ni en el entendimiento terrenal,
sino recibirla de la vida de nuevo cuando vuelva a ser necesaria.
Sí,
a menudo me he dado cuenta de que he recibido consuelo
fresco del Señor cuando he estado en gran angustia,
pero cuando he recurrido al consuelo que había guardado para después, no me ha consolado;
todo lo contrario, me ha herido más profundamente.
De esta manera el Señor me ha estado enseñando a vivir en Él,
no en algo que haya recibido de Él, sino en la vida misma, la misericordia,
el beneplácito que vienen directamente del pan vivo de cada día.

Cuarta, es fácil recibir conocimiento en la parte terrenal, en la sabiduría terrenal,
separado del Espíritu y de la virtud viva.
Cuando uno lee las Escrituras es fácil concebir y percibir
un significado uno mismo o tomar el de otro hombre,
pero es difícil abstenerse de todo lo que la mente concibe y razona,
y esperar la voluntad pura y revelación del Espíritu.
También es fácil retener conocimiento y hacer uso
de él en la voluntad y sabiduría de la mente natural,
pues ambas son naturales, pero es difícil negar la razón,
los pensamientos e imaginaciones y vigilar al Espíritu.

¡Oh, profesantes, esperen la aparición viva de Dios!
Esperen la frescura de Su Espíritu en sus espíritus,
para que en lo que viene del Espíritu ustedes puedan conocer al Espíritu y puedan,
además,
conocer cómo volverse a Él y permanecer con Él. Estén
atentos contra esa sabiduría en ustedes,
la que en todas las edades y generaciones ha sido
eternamente excluida de las cosas del reino,
aunque pueda reunir y sostener un vasto conocimiento
de las cosas del reino en la tesorería terrenal.
El Israel carnal tiene la sabiduría de la letra, pero el Israel espiritual la sabiduría,
virtud y vida del Espíritu en todas las edades y generaciones.
Y aunque el que nace según la carne desprecia al que nace según el Espíritu,
este es el heredero de Dios; y la esclava, la sabiduría terrenal,
con todos sus hijos (incluidos los mayores gigantes en conocimiento,
profesantes de religión y observaciones de las Escrituras),
deben ser echados y no heredar la vida eterna.
Esto está escrito para que la Semilla que hereda la vida
eterna sea levantada en ustedes mediante el poder,
y para que no encuentren sus almas engañadas cuando la luz de ese día se revele plenamente,
la cual ya ha amanecido.

Yo estaba en una condición pobre y humillada cuando el Señor me visitó en el pasado.
Yo estaba tan perdido, tan desecho y era tan miserable como cualquier otro.
Cualquier conocimiento, cualquier vida,
cualquier preciosa virtud que yo recibiera entonces provino de la gracia de Dios,
pero todavía era Suyo y encontré que Él podía pedirlo cuando quisiera.
Ciertamente,
el que ha recibido de la fuente debe confiar y devolver
a la fuente de nuevo cuando Él así lo requiera,
y luego permanecer vacío,
desnudo y desolado hasta que sea gratuitamente visitado de nuevo.
Esta es una lección difícil, ¿quién puede aprenderla?
¿Quién puede confiar su vida a la fuente y estar abierto a lo que sigue?
Sin embargo,
esto fue lo que el Señor demandó de mí. Y dado que mi corazón
no estaba dispuesto a separarse de mi vida,
sino que me esforcé en retenerla y crecer en esta
primera experiencia de gracia hacia la perfección,
Él la quebrantó de una manera tan indecible y trajo tal miseria y desolación sobre mí,
como no podría haberlo sospechado.
Ahora Él me está enseñando a vivir más plenamente en Su gracia, o más bien, en la fuente,
donde no soy nada y donde jamás podré ser algo,
sino donde Él es todo y siempre será todo, de la manera y en el tiempo que Él quiera.
Y ahora nada puede satisfacerme en Él,
salvo aquello que es de Él y vive en Él. Allí todo lo que he conocido
o gustado anteriormente de Él brota de nuevo en Su tiempo,
y yo bebo del vino viejo y también del nuevo,
pero no tengo nada en mi propia disposición. Cuando yo me aferro a algo o busco ser algo,
pierdo la fuente y soy corregido por mi reincidencia y espíritu de adulterio.
Pero entonces soy visitado nuevamente por Su fresco amor,
por una emanación de vida y poder fresco,
por frescas visitaciones de rica misericordia y gracia
que la fuente eterna naturalmente abre en lo suyo.

La perla es extremadamente rica, el tesoro de vida es inefable.
El que quiera poseerla deberá venderlo todo por ella, es decir,
todos sus deseos y corrupciones.
De hecho, deberá vender todas las riquezas de su naturaleza (lo mejor de su voluntad,
lo mejor de su sabiduría más refinada).
Y no sólo esto, deberá vender todas las riquezas de su espíritu,
todo a lo que se ha aferrado o pueda aferrarse fuera de la vida.
Luego, cuando sea pobre en espíritu y no tenga nada en sí mismo sino vacío,
nada donde recibir o retener la vida excepto lo que es formado,
crece y es preservado en ella, de acuerdo a su mera voluntad y buen placer,
entonces estará en condiciones de ser unido y llevado a la fuente eterna.
Perfectamente feliz es aquel que es perfectamente poseído por la fuente, sin embargo,
aquel que también anhela desesperadamente en pos de la fuente y
camina hacia ella no se queda sin una medida de bienaventuranza.
Esta no puede ser alcanzada por la parte natural
que retiene la letra o alguna revelación o conocimiento,
sino al comenzar en la virtud eterna, permanecer en ella,
transitar de muerte a muerte y de vida a vida,
hasta que todo lo que debe morir muera y perezca en el camino,
y sea levantado y perfeccionado todo lo que debe recibir
y vivir en el reino y corona de vida para siempre.
Esta corona la pone el Señor delante de todos los que corre en pos de ella,
pero nada sino la semilla espiritual (que es engendrada
por el Espíritu y permanece en Él) puede obtenerla.
Piensen entonces en este breve resumen:

La criatura perdida, la criatura desechada,
es misericordiosamente buscada y visitada por la fuente de su vida y ser.

Siendo visitada por la misericordia y gracia y abrumada,
recibe algo de la gracia y virtud viva proveniente de la fuente.

Habiendo recibido algo, la criatura tiende a retenerlo en su vasija (es decir,
en su propia voluntad,
y busca ensanchar su propia sabiduría y así convertirse
en algo de nuevo en sí misma) y olvida la fuente.

En la medida que la criatura retiene algo en la parte natural,
fuera de la experiencia directa de la virtud viva,
en esa misma medida se corrompe y adultera de la fuente viva.

Eso con lo que alguien ha adulterado debe ser quitado de él,
él debe morir a eso y eso debe morir a él antes de poder ser recuperado al estado vivo,
antes de estar en condiciones de disfrutar lo que anteriormente
había recibido o de recibir más y crecer en la virtud viva y fresca.
