== Capítulo XIII. La Suma y Sustancia de la Verdadera Religión

[.discourse-part]
_Pregunta 1:_
¿Qué es la verdadera religión? ¿Es un don de Dios otorgado
a los que Él engendra por el poder de Su vida,
o es una práctica de adoración en la naturaleza de este mundo que
el hombre puede alcanzar mediante medios y esfuerzos naturales?

[.discourse-part]
_Pregunta 2:_
¿Cuál es la suma y sustancia de la verdadera religión?
¿No es el amor que procede de la Semilla de vida?
¿No es el viaje de la criatura de la enemistad contra Dios al amor de Dios?
¿No brota la luz de vida en el amor y reúne en el amor?
¿No enseña Cristo (revelado en el corazón y leudándolo
con el sabor de la vida) a amar a los enemigos,
soportarlos en amor, buscarlos en amor, perdonarlos en amor, orar por ellos en amor,
desear el bien para ellos y luchar con Dios por misericordia hacia ellos,
incluso cuando odian y persiguen?

[.discourse-part]
_Pregunta 3:_ ¿Son encontrados en este amor los católicos,
protestantes o cualquier otra clase de personas religiosas?
¿Lo manifiestan mediante su discipulado a Cristo y por el poder de Cristo en ellos,
o establecen sus varias formas externas y las mantienen
en ira y enemistad unos contra otros?
De hecho, ¿no se destruirían entre sí, si pudieran?
¡Ciertamente,
este espíritu está en muchos de ellos! ¿No da esto
una evidencia contundente contra la religión de ellos,
que no es más que una forma externa y no el verdadero poder en ella?
¿No muestra esto que ellos en el corazón no son discípulos de Cristo?
Porque si fueran Sus discípulos aprenderían a amar por medio de Él.

[.discourse-part]
_Pregunta 4:_ Si no se mantiene en el poder de la vida, ni sujeta a él,
¿no es cierto que cualquier forma de religión termina peleando contra el poder,
al conservar una demostración externa sin la sustancia y que por este medio la aplasta?
¿Cuál forma de religión en el mundo de hoy permite que el
amor crezca y que la vida guíe y gobierne en amor,
y que el Señor de vida ejerza Su autoridad en los corazones y consciencias de los hombres?
Esto es por falta de poder interno y por formas externas forzosamente establecidas;
pues la religión del evangelio comenzó en Espíritu y en poder,
y no puede ser restaurada ni preservada sino por el mismo Espíritu y el mismo poder.
La separación de los protestantes de los católicos fue buena,
solo en la medida que se mantenga en el poder de la vida;
y la separación de los otros de los protestantes también fue buena,
sólo en la medida que haya sido comenzada y sea mantenida en el mismo poder.
Aunque un grupo empiece correctamente por medio de
un liderazgo verdadero y claro del Espíritu de Dios,
tan pronto como empiece a inventar y a torcerse hacia una forma de su propia escogencia,
es inmediatamente corrompido al apoyarse en los razonamientos
y entendimientos de los hombres.

[.discourse-part]
_Pregunta 5:_
Si el poder de la verdadera religión (y verdadero
amor) fuera levantado y restaurado de nuevo,
¿haría más feliz al mundo y colocaría cada cosa en el lugar apropiado,
tanto interna como externamente?
¿No sería el sentido algo excelente en el hombre si fuera guiado por la razón? ¿No sería
la razón algo aún más excelente si fuera guiada por la Semilla de vida en el interior?
Pero el sentido sin la guía de la razón, ¡cuán necio es!
De igual manera, la razón sin la guía de la vida, cae debajo del sentido.
¡Cuán cruel, cuán ciego, cuán egoísta,
cuán injusto es el hombre que sigue los dictados de su propia razón corrupta,
sin conocer y sujetarse a aquello que debería iluminarla
y darle a él el correcto uso de ella!

[.discourse-part]
_Pregunta 6:_ Cuando Dios restaure la verdadera religión y la levante en poder,
¿no deben necesariamente marchitarse y decaer las
formas y costumbres de adoración sin dicho poder?
Cuando el poder apareció por primera vez en la dispensación del evangelio,
¿no volaron y se desvanecieron todas las sombras de las
ceremonias de Moisés ante él? Y cuando aparezca de nuevo,
¿no se desvanecerán ante el resplandor de la luz del día todas las sombras e
inventos del hombre que han surgido desde entonces (durante el tiempo de la noche)?
Donde el poder se levanta en un corazón,
¿qué pasa con el hombre y con todo lo que brota de él? ¿Dónde queda su
sabiduría? ¿Dónde queda su antigua adoración? ¿Qué pasa con todas sus
formas de religión? ¿No son disueltas todas y reducidas a nada?
¿Acaso no se convierte en un niño pequeño para ser
formado de nuevo en el poder de la vida,
y nacido del Espíritu de vida para poder entrar en el reino de Dios?
¿No pasan todas las cosas viejas y brotan nuevas de la Semilla
de vida que Dios siembra y preserva en el corazón mediante Su poder?

Ahora, ¿quién es sabio para entender estas cosas?
¿Quién tiene la llave para abrir los misterios de la vida?
¿Quién conoce los tiempos y las ocasiones (los tiempos y las ocasiones de las formas,
los tiempos y las ocasiones de la vida y el poder)?
¿Quién ve lo que Dios está a punto de hacer en el mundo y prepara
su corazón para Sus administraciones sobre la tierra?
¿Quién es amigo de Dios y de la humanidad,
y está dispuesto a salir en espíritu de este estado oscuro, corrupto y terrenal de cosas,
hacia la naturaleza y ser celestial?
Esto no lo puede hacer él por su propia fuerza y razón,
sino por el poder y la guía de Dios revelados en él; el principio de vida interior.
Aquel que siga esto debe sentirlo en su corazón,
darle la espalda a la naturaleza y sabiduría terrenal,
y pelear contra sus propios razonamientos corruptos en y con la luz de la vida,
en la medida que esta se levante y sea cada vez más revelada
en su corazón a través de la gracia y misericordia de Dios.
De esta manera Dios le ofrece ayuda al hombre miserable
y perdido para redimirlo de su miseria y estado de ruina.

El hombre tiene un tiempo asignado por Dios aquí y cuando dicho tiempo se acabe,
se determina con respecto a él. Él es un sembrador de semillas en este mundo,
lo que siembre aquí lo cosechará en la otra vida.
Él siembra para la carne o para el Espíritu,
para su propia voluntad o para la voluntad de Dios.
Sigue los caminos de su propio corazón o los del Espíritu de Dios.
Experimenta el poder de la verdadera religión, y por lo tanto,
es renovado y preparado para Dios,
o se contenta con una forma de piedad sin poder y sigue siendo lo que era.

El que sea renovado, el que sea cambiado en corazón y vida,
el que siembre para la voluntad y naturaleza de Dios heredará vida con Dios.
El que viva en una forma de religión sin poder y siga las vanidades de su propia mente,
será cortado de Dios y yacerá en tristeza y angustia de alma.
El tal lamentará amargamente el tiempo que malgastó
y la pérdida de la vida y felicidad de su alma,
por disfrutar por unos pocos días la naturaleza y
espíritu terrenal en su estado corrupto y degenerado.

¡Oh, hombre, quienquiera que seas,
que estás sumergido en los deseos y placeres de este mundo,
los cuales solamente responden a la parte sensual y corrupta,
recuerda que también tienes un alma preciosa que necesita
redención por el poder de Dios para hacerte feliz!
Un día esta alma será despertada en ti, y cuando lo sea sentirá su falta de Dios.
Hoy es el día que Dios te está extendiendo Su brazo.
¡No lo dejes escapar!
Porque si lo haces,
terrible será el día de tu despertar y tu miseria será inevitable e intolerable.
Y si ahora los dolores de tu cuerpo son espantosos para ti,
¿cómo será que tu alma sea desgarrada por la ira del Todopoderoso?

Reflexiona en tu corazón y retírate interiormente,
y busca sentir algo de Dios que recoja tu alma y la guíe
fuera de tu propia naturaleza y espíritu mundano,
hacia la naturaleza y vida de Su Espíritu.
Porque el espíritu del hombre regresa a Dios que lo dio,
así como el cuerpo regresa a la tierra.
Entonces el Señor le asigna el lugar apropiado en
concordancia con la naturaleza que es hallada dentro.
Si es hallada la naturaleza del trigo,
si lo hallado es de la naturaleza renovada y ha tomado
la cruz y seguido a Cristo en la regeneración,
Él la recoge en Su granero.
Pero si la naturaleza hallada es cáscara, si lo hallado es del espíritu terrenal,
la mente permanece no renovada ni reconciliada con la naturaleza de Dios,
entonces Él la echa al fuego que nunca se apaga (es decir,
al fuego que la quemará y abrasará sin extinguirse),
al gusano que no muere y carcome perpetuamente,
y trae a la mente toda la vanidad anterior y pérdida de
tiempo para incrementar el calor y las llamas del fuego.
¡Oh, ¿qué alma,
si no estuviera hechizada y adormecida en un sueño
de muerte por el espíritu de este mundo que atonta,
correría tan grande peligro para disfrutar unos pocos
placeres momentáneos en la parte sensual?
¿Y quién, a sabiendas,
perdería el deleite interior de paz y reconciliación con Dios aquí
y los placeres de Su reino de verdadera gloria en el más allá?!

=== Las Influencias de la Razón y la Fe

Está el hombre natural y el hombre espiritual,
y están las influencias de cada uno en y sobre asuntos de religión.
Está la influencia de la razón y la influencia de la fe.
La influencia de la razón es esa creencia que el hombre recibe en su mente
o corazón a partir del ejercicio de la facultad del razonamiento;
esta influencia en asuntos de religión no es más que la opinión o el juicio del hombre.
Ahora, no importa cuán cierta o infalible le parezca esta influencia,
todavía puede ser sacudida por una demostración o
evidencia de un género o naturaleza superior.

La influencia de la fe es esa creencia que recibe la nueva criatura en la mente renovada,
a partir de la evidencia y demostración del Espíritu.
Esta influencia revela y manifiesta las cosas del Espíritu
a la mente que es engendrada y renovada por Él.

Ahora, la más baja influencia de la fe es superior y de una naturaleza más noble,
que la más alta influencia de la razón. La verdadera fe es de un principio superior
y de una naturaleza y fundamento más profundo que los de la razón del hombre.
Pero debido a que tal fe no aparece dentro de la esfera del hombre, sino fuera de ella,
y además es contraria a la línea y alcance de su sabiduría,
es considerada por él necedad y locura.
Por eso es que la sabiduría de Dios (y de los mismos hijos)
es juzgada y condenada por el hombre el día de hoy.

¿Cómo no va a ser así? ¿Cómo no va a juzgar la sabiduría del hombre como locura algo,
cuya belleza y excelencia están escondidas a su ojo?
Esto se debe a que la sabiduría del hombre opera fuera de
su lugar y no está sujeta a la sabiduría de Dios,
más bien se exalta por encima de ella.
Por tanto,
se le permite a la sabiduría del hombre que por un tiempo se levante en
su engreimiento y persiga la sabiduría pura de Dios y a los hijos de ella,
pero al final caerá y será quebrantada,
y su día merecidamente llegará a su fin y será encerrada
en las sombras y aposentos de eterna oscuridad.

Pero, ¡qué oído de hombre puede oír esto!
Ciertamente ninguno que sea fuerte en la forma de la sabiduría,
razón y entendimiento del hombre, sino aquel que está magullado,
roto y en alguna medida despedazado por las incursiones de la vida y naturaleza divina.
Feliz el que conoce y atiende la influencia del Espíritu de Dios,
que es nacido de Dios y enseñado a esperar en Él, y que lo adora en Espíritu.
Feliz aquel que recibe su religión de la luz de la fe en la naturaleza y mente renovada,
y no de la razón del hombre en el entendimiento natural,
el cual es fácilmente corrompido y no puede ser conservado puro.

=== Un Vistazo a Algunos Misterios del Reino de Dios

[.alt.centered]
==== CON RESPECTO A CRISTO

[.discourse-part]
Pregunta: ¿Qué es Cristo?

[.discourse-part]
Respuesta:
Él es en Sí mismo el linaje inmediato de la vida eterna y la fuente o manantial
de vida para la creación. "`Porque como el Padre tiene vida en sí mismo,
así también ha dado al Hijo el tener vida en sí mismo;`" y en Su
Hijo y a través de Su Hijo Él comunica Su vida a Sus criaturas.

[.discourse-part]
Pregunta: ¿Cómo comunica Cristo vida?

[.discourse-part]
Respuesta: Como la Palabra viva, como la Semilla prometida.
Él siembra la Semilla del reino (en la que está la vida) en el corazón,
y conforme le abre paso para que se extienda, crezca y leude la vasija,
así vivifica y reúne en Su vida.
De nuevo, Él es la palabra iluminadora, la palabra que da vida, la palabra de sabiduría,
la palabra de poder, la palabra de amor y reconciliación,
cuya voz obra poderosamente para destruir el pecado y salvar el alma de dicho pecado.

[.discourse-part]
Pregunta: ¿Dónde debe ser esperada esta Palabra o Semilla?

[.discourse-part]
Respuesta: Su aparición ocurre en los corazones de los hijos de los hombres,
ahí debe ser esperada.
Dios siembra esta Semilla en el corazón,
allí está cerca de aquellos a quienes Él visita con Su amorosa bondad y misericordia.

[.discourse-part]
Pregunta: ¿Cómo se recibe esta palabra?

[.discourse-part]
Respuesta: Mediante la fe en la virtud que fluye de ella.
La naturaleza de la palabra es volverse contra el pecado y atraer hacia el Padre.
Su luz brilla para descubrir el pecado y su vida se agita para vivificar
contra él. En la medida que el corazón crea y sea influenciado contra
lo que la luz evidencia que es malo,
y sea conquistado por lo que la luz muestra que es bueno, la palabra es recibida,
y un fundamento de unión es colocado entre ella y el alma.
Pero en la medida que el corazón rechace o se vuelva
de cualquier cosa que provenga de la palabra,
Cristo es rechazado y dejado atrás.

[.discourse-part]
Pregunta: ¿Cómo obra esta palabra en o sobre el corazón?

[.discourse-part]
Respuesta: Según encuentre acceso y entre en el corazón, o según sea rechazada o negada.
En la medida que tenga acceso obra vida ahí y la criatura es hecha conforme a la vida.
Injerta Su naturaleza, Su justicia, Su santidad, Su dulzura, Su paz, Su amor, Su gozo,
Su mansedumbre, Su paciencia, etc.,
conforme abre campo en el corazón al expulsar la naturaleza contraria.
Pero donde es rechazada obra muerte y condenación
e incrementa la cautividad y miseria del alma.
¡Así que sería mejor nunca oír ningún sonido de Cristo en el corazón,
que oírlo y no prestarle atención ni sujetarse a él!

[.discourse-part]
Pregunta: ¿Qué entorpece la unión con Cristo?

[.discourse-part]
Respuesta: El hombre fuerte armado, a quien Cristo viene a despojar,
hace lo posible para cegar el ojo que puede ver la hermosa
naturaleza de Cristo y endurecer el corazón contra Sus apariciones.

[.discourse-part]
Pregunta: ¿Cómo puede ser ayudada el alma contra el hombre fuerte?

[.discourse-part]
Respuesta: Recibir la verdad en amor,
y rendir el corazón a la virtud que fluye de Cristo en Sus visitas y apariciones,
permite que entre al alma esa fuerza que lo conquista.
El hombre fuerte no es capaz de permanecer ante el poder de Cristo.
Dicho poder actúa en el interior en la medida que el alma lo deja entrar.
La incredulidad de corazón y los pensamientos e imaginaciones
terrenales son los que le dan fuerza al enemigo;
pero ante la fe verdadera, aún en la más pequeña medida,
el hombre fuerte se debilita y su fuerza cae.

[.alt.centered]
==== CON RESPECTO A LA MANERA DE CONOCER A CRISTO

Cristo es el ministro del verdadero santuario que Dios ha levantado, no el hombre.
Hay una ciudad "`cuyo arquitecto y constructor es Dios.`"
Cristo es la primera piedra, la piedra angular,
la piedra superior de esta ciudad o edificio.
Por tanto, el que desee conocer a Cristo y ser edificado sobre Él,
deberá encontrar algo santo revelado en su corazón y su alma edificada sobre eso,
por el Único que puede levantar ese edificio.
Sólo Uno puede alzar el tabernáculo que por tanto tiempo ha estado caído,
edificar las antiguas ruinas y restaurar las sendas para que los
rescatados y redimidos del Señor caminen y viajen por ellas.

Ahora, aquel que puede encontrar algo de Dios edificado en su corazón (sí,
incluso si puede encontrar los principios del verdadero santuario),
puede encontrar también a Cristo ministrando ahí. El verdadero
Sumo Sacerdote ofrece en el corazón sacrificios,
intercede ante el Padre y le da a comer al alma de las cosas santas.
Bien, esta es la manera de conocer a Cristo, a saber,
en Su vida engendrada en el corazón,
en Su presencia ahí y en Sus ministraciones entre el alma y el Padre.
El que lo conoce así, viendo en sencillez de corazón con el ojo verdadero,
no puede ser engañado con respecto a Él,
sino que conoce la voz de Su Espíritu y sin reparos la abraza.
Pero no conoce al extraño o al engañador, ni lo oirá,
sino que por instinto de vida se volverá de ellos.
Por tanto,
el conocimiento y la preservación de la oveja no es por los sabios razonamientos
de la mente con respecto a la voz del pastor o a la voz del extraño,
sino por el instinto de la nueva naturaleza escondida,
la cual le enseña al corazón sencillo a evitar las trampas
en las que la sabiduría terrenal es fácilmente enredada.
Los mansos, los humildes, los quebrantados de corazón, los débiles, los pobres,
los bebés, los niños pequeños,
estos son a los que el Padre les enseña. Estos tienen esa
preservación e instrucción que pierden las mentes sabias,
conocedoras y juiciosas (según la consideración del hombre).
De ahí que lo insensato de Dios sea más sabio que el hombre,
y lo débil de Dios más fuerte que el hombre.
Dios ha escogido en cada hombre lo que no es, para llevar a nada todo lo que está en él,
de modo que la carne no se glorifique en Su presencia,
ni ningún hombre se jacte delante del Señor de la salvación de su alma.

[.alt.centered]
==== CON RESPECTO AL ARREPENTIMIENTO

[.discourse-part]
Pregunta: ¿Qué es arrepentimiento?

[.discourse-part]
Respuesta: Es el vuelco del corazón que obra Cristo,
de la naturaleza muerta y de las obras muertas,
a la Semilla viva y a las obras vivas de la misma.

[.discourse-part]
Pregunta: ¿Puede o no un hombre volverse del pecado a Dios cuando quiera?

[.discourse-part]
Respuesta: No, el hombre es un prisionero,
su entendimiento está cautivo y su voluntad también. Todos
los afectos del hombre y su naturaleza están en cautiverio,
y nada puede volverlo a Dios salvo aquello que es
más fuerte que el poder que lo mantiene cautivo.

[.discourse-part]
Pregunta: ¿Cómo se realiza el arrepentimiento?

[.discourse-part]
Respuesta: Es don de Cristo,
a quien Dios ha designado como príncipe y Salvador
para dar arrepentimiento y remisión de pecados.
Él da arrepentimiento en la virtud que ilumina y atrae, mediante la cual,
la naturaleza de pecado queda al descubierto y la inclinación
del alma es secretamente vuelta contra ella.

[.discourse-part]
Pregunta: ¿De qué y hacia qué es vuelto el corazón?

[.discourse-part]
Respuesta: Es vuelto de una naturaleza a otra, de una semilla o otra,
de un espíritu a otro, de un camino a otro, de un fin a otro.

[.discourse-part]
Pregunta: ¿Es dado el arrepentimiento en plenitud de una vez?

[.discourse-part]
Respuesta: No, pero se incrementa,
y se le da más día a día al corazón que espera en el Señor. El pecado,
la naturaleza de pecado, el camino de la mente y del cuerpo en él,
son expuestos cada día más,
y la aversión y el aborrecimiento hacia este aumentan conforme la nueva naturaleza
reúne fuerza en la mente y se incrementa en la luz y poder de la vida.

[.discourse-part]
Pregunta: ¿Qué pasa si se comete pecado después que uno se ha vuelto de él?

[.discourse-part]
Respuesta: El arrepentimiento no se ha perfeccionado todavía ahí;
el enemigo no ha sido totalmente echado, ni su fuerza suficientemente quebrantada.
La ley no está cumplida ahí, ni el pacto de gracia plenamente experimentado,
sino que el alma todavía se encuentra cautiva bajo el poder del enemigo en alguna medida.
Ahora bien, si el corazón está inclinado contra el pecado cometido,
Dios lo carga sobre el enemigo y no sobre el alma.
"`Y si hago lo que no quiero, ya no lo hago yo, sino el pecado que mora en mí.`" (Rom.
7:20)

[.alt.centered]
==== CON RESPECTO A LA FE

[.discourse-part]
Pregunta: ¿Qué es fe?

[.discourse-part]
Respuesta: Es creer en las apariciones del Señor al alma,
aferrarse a la virtud de ellas y beber de las mismas.
Hay diversas apariciones del Señor, como Espíritu vivificante,
que da vida y fuerza al alma.
También, como descubridor, amonestador y condenador de pecado, y justificador de justicia.
Así como fortalecedor y consolador de aquello que carece de Su fuerza y consuelo,
y como fuente de perfecto amor, de dulzura, de todo bien, etc.
Ahora bien, aunque al Señor le complace aparecer, es fe aquello que ve, conoce,
se apropia, se une a sus apariciones y bebe de la virtud de las mismas.

[.discourse-part]
Pregunta: ¿Mediante qué medios es forjada la fe?

[.discourse-part]
Respuesta: Mediante la palabra viva en el corazón;
mediante la palabra de la que el alma tiene existencia y está cerca de ella.
Esta era la palabra de fe o la palabra que obraba fe bajo la ley.
(Deut.
30) Esta era la palabra de fe que los apóstoles predicaron
y la que obraba fe bajo el evangelio.
(Rom.
10) Esta es la palabra que hoy sentimos obrando fe en nosotros.
De hecho,
esta es la Semilla de vida de la que cada cosa espiritual brota y crece en el corazón.

[.discourse-part]
Pregunta: ¿Cómo es recibida la fe?

[.discourse-part]
Respuesta: En el poder vivificante, La Semilla de vida dispara Su luz, Su vida,
Su naturaleza, Su virtud en el corazón,
y al tocarlo es vivificado para Dios en alguna medida.
En esta virtud y desde esta virtud vivificante fluye la fe en el alma.
Porque en la muerte de pecado, en el estado de pecado, no hay nada sino incredulidad.
La fe, por tanto, debe necesariamente fluir de los movimientos vivificadores de la vida.

[.discourse-part]
Pregunta: ¿Qué hace la fe en el corazón?

[.discourse-part]
Respuesta: La fe une a Dios y separa del pecado.
Ella empieza y continua la obra de redención en el alma.
Recibe lo que es de Dios y repele lo contrario.
Mantiene la mente casta, pura,
viva y fresca delante del Señor. Saca la virtud y sorbe la dulzura de cada aparición
de Dios en el corazón. Mantiene en el amor de Dios y expulsa el amor al pecado,
el amor a la criatura, el amor al yo o a cualquier cosa que esté fuera de Dios.
De hecho, la fe sorbe el aliento de vida y purga el aliento y poder de muerte.

[.discourse-part]
Pregunta: ¿Sobre qué se coloca la fe?

[.discourse-part]
Respuesta: La verdadera fe se coloca en aquello por medio de lo cual es recibida,
es decir, en el poder vivificador.
La fe debe ser continuamente mantenida viva por la Semilla de vida o no puede vivir.
Ella brota en el poder, habita en el poder,
actúa en el poder y nunca es hallada fuera de él. El hombre no puede creer cuando quiera,
es un continuo don que depende de la continua vivificación
y nutrición de la vida de donde surgió.

[.discourse-part]
Pregunta:
¿Por qué el enemigo asalta con incredulidad y pelea
tan fuertemente contra la fe del alma?

[.discourse-part]
Respuesta: Porque todo depende de ella.
Detiene la fe y lo ha detenido todo; vence esta y lo ha vencido todo.
Si la fe está firme y permanece fuerte, el enemigo no gana nada, todo lo contrario,
pierde en cada tentación y aparente victoria.

[.alt.centered]
==== CON RESPECTO AL AMOR

[.discourse-part]
Pregunta: ¿Qué es amor?

[.discourse-part]
Respuesta: ¿Qué diré de ello, o cómo expresaré en palabras su naturaleza?
Es la dulzura de la vida; es la dulce,
tierna y suave naturaleza de Dios fluyendo a través de Su Semilla de vida hacia la criatura;
y de todas las cosas, el amor hace a la criatura más como Él mismo,
tanto en naturaleza como en operación. El amor cumple la ley, cumple el evangelio,
lo envuelve todo en uno y todo lo lleva a cabo en unidad.
Excluye toda maldad del corazón y perfecciona todo bien
en el corazón. Un toque de amor hace esto en cierta medida,
el perfecto amor lo hace en plenitud.

Pero, ¿cómo puedo proseguir hablando de él? ¡Oh,
que las almas de todos los que temen y esperan en
el Señor puedan experimentar su naturaleza plenamente,
entonces conocerán sus dulces y triunfantes operaciones,
tanto hacia los demás como hacia los enemigos! ¡Qué mi alma espere
y clame en pos del perfecto fluir de amor eterno en mi corazón,
y me consuma totalmente en él y me gobierne enteramente él! ¡Qué
la vida de Dios en su perfecta dulzura corra plenamente a través
de esta vasija y que de ninguna manera sea teñida por la vasija.
Todo lo contrario,
que la vida de Dios tiña y cambie la vasija según Su propia naturaleza,
entonces no será hallada ninguna falta en mi alma delante del Señor,
sino que la vida impecable de Dios será totalmente disfrutada por
mí y se convertirá en un sacrificio placentero para mi Dios!

¡Oh,
cuán dulce es el amor! ¡Cuán agradable es su naturaleza!
¡Cuán hermosamente se comporta en toda situación,
en toda ocasión,
en cada persona y en todo! ¡Cuán tierna y fácilmente ayuda y sirve
lo más bajo! ¡Cuán paciente y mansamente sobrelleva todas las cosas,
sean de Dios o del hombre,
por más inesperadas que vengan o por muy difíciles que parezcan! ¡Cuánto cree,
cuánto espera, cuánto perdona, cuánto cubre,
incluso lo que parece inexcusable y no apto de ser cubierto! ¡Cuán amable
es incluso en sus interpretaciones y acusaciones con respecto a los errores!
¡El amor nunca exaspera el espíritu de aquel a quién reprende,
nunca endurece, nunca provoca,
sino que lleva con él suavidad y poder de convicción! ¡Esta es
la naturaleza de Dios! ¡Y en las vasijas que han sido hechas aptas
para recibir el amor y manifestar la gloria de este,
el poder del enemigo no es capaz de permanecer!

[.alt.centered]
==== CON RESPECTO A LA OBEDIENCIA

[.discourse-part]
Pregunta: ¿Qué es obediencia?

[.discourse-part]
Respuesta: Es la sujeción del alma a la ley del Espíritu,
cuya sujeción fluye y es fortalecida por el amor.
Esperar conocer la mente de Dios y llevar a cabo Su voluntad en todo,
a través de la virtud de la Semilla de vida revelada en el interior,
es la obediencia de fe.
Esta es la obediencia de la Semilla transmitida a la criatura por la Semilla.
El hijo obediente es el que naturalmente hace la voluntad, sí,
y también es el siervo escogido.

Noten cómo todo en el reino y todo lo espiritual
se refiere a Cristo y se centra en Él. Su naturaleza,
Su virtud, Su presencia, Su poder lo constituyen todo.
De hecho, Él es para el creyente todo en todos,
manifestado y revelado en el corazón de diversas maneras sólo por el Espíritu.
Él es el tomo completo,
cada página y cada línea hablan de Él y lo describen en
una u otra de Sus dulces y hermosas características.
Por tanto, si yo aún hablara de algo más, como de mansedumbre, ternura, humildad,
misericordia, benignidad, paciencia, longanimidad, contentamiento, etc.,
(todo lo cual yo preferiría que fuera leído en Su
libro vivo de la Palabra eterna que en mis escritos),
sólo estaría hablando más de Su naturaleza misma, originada,
manifestada y exhibida en y a través de las criaturas
mediante el giro de la rueda de Su vida en sus corazones.
Pero mi espíritu se aleja apresuradamente de las palabras y siento
que debo acortar y pasar por encima de estas revelaciones en mí,
para que ni mi alma ni la de otros se fijen en las palabras con respecto a la cosa,
sino que más bien se sumerjan en espíritu hasta la experiencia de la vida misma.
¡Oh, que podamos aprender lo que es disfrutar la sustancia ahí,
ser comprendidos por ella y dejar de esforzarnos
solo por saber o comprender con respecto a ella!
Porque aquel que gusta de este conocimiento vivo,
el cual está depositado en ese tesoro que el ladrón
y corruptor no tienen manera de tocar,
no puede sino estar dispuesto a vender todo el conocimiento
que pueda estar contenido en la vasija de la criatura.
No obstante, no puedo dejar de añadir algo más con respecto a la paz, el gozo,
la libertad, la oración, como también con respecto a la regeneración, justificación,
santificación, reconciliación y redención,
porque mi corazón cree que esto puede resultar útil para algunos
en la guía y misericordia del buen Espíritu del Señor.

[.alt.centered]
==== CON RESPECTO A LA PAZ O AL REPOSO

La verdadera paz es la quietud,
tranquilidad y satisfacción del corazón en Dios que fluyen desde
y con el Espíritu de vida en el alma que está sujeta a Cristo.
Hay, de hecho, otro tipo de paz, a saber,
una falsa paz o reposo en el pecado y la injusticia.
Sin embargo, no es verdaderamente natural para el alma mientras dura,
y es repentinamente perturbada cuando la verdadera luz brilla
en el corazón y cuando el testigo de Dios lo despierta;
entonces: "`no hay paz para los malos.`"
¡Oh,
el apuro y la perplejidad para el pecador cuando la luz del Espíritu de
Dios le pone de manifiesto Su corazón y Sus caminos! ¡Qué amarga guerra,
ruido y tumulto levanta el enemigo en su interior! ¡Cómo trata de molestar
a cada paso del camino y cuánto se esfuerza por oscurecer cada tirón,
movimiento y guía que saca al alma de sus dominios!
Pero conforme la redención es experimentada, así los lazos del enemigo son rotos,
la vida es manifestada y el alma se siente entrando en la
naturaleza de la vida y en la obediencia a ella.
En consecuencia, la paz brota y el reposo en Dios es gustado y disfrutado.

[.alt.centered]
==== CON RESPECTO AL GOZO

El gozo es la alegría del corazón en Dios, que mana, principalmente,
de la refrescante vida de Dios y Su presencia,
el cual lleva a través y sobre toda prueba y tribulación; incluidas las más grandes.
Cuando la pobre,
jadeante y fatigada alma (la que ha anhelado en pos de Dios y ha sentido largamente
la amargura y miseria de su separación) empieza a sentir su unión con Él,
Su amor, bondad, justicia, poder, sabiduría y salvación,
¡cuán llena es de gozo y deleite en las arras de su porción!
Ahora puede decir en la fuerza de la vida:
"`Mi alma se regocija en Dios mi Salvador, porque ha mirado mi bajeza.
Su corazón ha sido movido hacia mí, la aurora de lo alto me ha visitado.
Y yo, que he estado desolada y abandonada largo tiempo,
he hallado ahora favor en los ojos de mi Amado y mi corazón
siente (en medida) que soy Suya y Él mío. Él me ha tocado,
ha ganado mi corazón y ¿qué nos puede separar?
Él mismo ha hecho el nudo y ¿quién puede romperlo?
¿Cómo no se va a regocijar mi corazón en Su nombre sobre todos mis temores,
falsos razonamientos, dudas y recelos,
que por mucho tiempo me mantuvieron cautiva y evitaron que mis ojos leyeran Su amor,
el cual fue escrito tanto en Su corazón como en Sus tratos hacia mí?`"

[.alt.centered]
==== CON RESPECTO A LA LIBERTAD

La libertad es el ensanchamiento del corazón en el Espíritu del Señor,
en donde tiene libertad en todo lo que es bueno, y es expulsado de todo lo que es malo.
El Espíritu del Señor es libre y libera.
El espíritu terrenal está en esclavitud con sus hijos;
pero los que son engendrados por el Señor y están envueltos en Su Espíritu,
encuentran en Él el poder y la libertad de la nueva vida, y por tanto,
son completamente sacados del alcance de aquello que tiene poder de capturar y esclavizar.
Así, pues,
la verdadera libertad no consiste en libertad en toda forma de alcance y amplitud, no,
la verdadera libertad consiste en el alcance y amplitud propias de Su naturaleza.
En consecuencia,
el Infinito e Ilimitado está limitado (si fuera apropiado expresarlo así)
dentro de los límites y fronteras de Su propia naturaleza y Espíritu,
lo cual Él no puede transgredir, ni de ninguna manera consentir,
que se haga lo que es contrario a ella.

==== CON RESPECTO A LA ORACIÓN

La oración es esa respiración de anhelo del niño vivo por el Padre de vida,
en ese Espíritu que hace que el niño viva,
que le otorga un sentido correcto de sus deseos,
y clamores apropiados proporcionales a su estado y momento.
Noten pues: La oración está totalmente fuera de la voluntad de la criatura,
totalmente fuera del tiempo de la criatura, totalmente fuera del poder de la criatura.
Está en el Espíritu del Padre,
quien es la fuente de vida y le da respiraciones de vida a su hijo según Su beneplácito.

[.alt.centered]
==== CON RESPECTO A LA REGENERACIÓN

[.discourse-part]
Pregunta: ¿Qué es regeneración?

[.discourse-part]
Respuesta: Es el nuevo nacimiento de la criatura o,
nacer de nuevo de la Semilla inmortal de la Palabra de vida eterna.

[.discourse-part]
Pregunta: ¿Cómo se obtiene este nacimiento?

[.discourse-part]
Respuesta: Por el brote de la Semilla de vida eterna en el corazón,
la transformación del corazón a Su imagen y ser llevado en ella.

[.discourse-part]
Pregunta: ¿Cómo es transformado el corazón a imagen de la Semilla y llevado en ella?

[.discourse-part]
Respuesta: Al ser leudado con el poder y la virtud de Su naturaleza,
mediante la nueva savia que recibe de ella, la cual,
se extiende poco a poco hasta que al final llega a ser todo en él.

[.discourse-part]
Pregunta: ¿Cómo se recibe esta virtud de la Semilla?

[.discourse-part]
Respuesta: Rindiéndose a ella en la fe que fluye de ella.
Esto permite que entren la nueva savia y la naturaleza de vida que purgan lo viejo.

[.discourse-part]
Pregunta: ¿Cómo aparece la Semilla y se manifiesta a sí misma,
y cómo se entrega uno a ella en la fe?

[.discourse-part]
Respuesta: La Semilla aparece en Su propia luz y virtud vivificante,
lo cual descubre las tinieblas y la muerte del pecado y
saca al corazón (que ha sido hecho dispuesto) de ello.
Ahora, conforme esta separación es sentida,
es claramente conocida y lo requerido por ella es hecho manifiesto.
Aquí es engendrada la fe en el corazón. Luego,
el alma tiene que rendirse en la obediencia de la fe sin consultar
los razonamientos ni la sabiduría de la mente carnal,
donde el enemigo está listo a apagar esta luz de fe y llevar a la incredulidad.

[.alt.centered]
==== CON RESPECTO A LA JUSTIFICACIÓN

[.discourse-part]
Pregunta: ¿Qué es justificación?

[.discourse-part]
Respuesta: Es la aceptación o absolución de una persona en su obediencia al Señor. O,
el perdón, el dejar pasar, y así absolverlo de su desobediencia.

[.discourse-part]
Pregunta: ¿Quién es el que justifica?

[.discourse-part]
Respuesta: El Señor, el que da a la humanidad la ley según Su beneplácito.
El que también es juez de la obediencia o desobediencia del hombre a la ley,
y el correcto justificador o condenador del hombre en ella.

[.discourse-part]
Pregunta: Pero,
¿no está el hombre en un estado caído? ¿Puede él obedecer
a Dios en algo para ser justificado por Él?

[.discourse-part]
Respuesta: En efecto,
el hombre está caído y no tiene fuerza o voluntad en sí mismo para servir u obedecer
al Señor. Pero hay una visitación de vida y amor emitiéndose hacia la humanidad en general,
en la que la vivificante vida mana de Dios y un poder secreto y escondido da la habilidad
a todo corazón dispuesto a seguir Su invitación. Esta visitación es administrada así
por el Señor para que ningún hombre perezca por falta de poder,
sino sólo por la terquedad y por la elección de su propia voluntad.
Así, pues, la destrucción del hombre es, en verdad, por sí mismo y no por Dios,
Cuyo deleite es salvar y no destruir a Su criatura.

[.discourse-part]
Pregunta: ¿Cómo se forja esta justificación?

[.discourse-part]
Respuesta: Por fe en la virtud que fluye de Cristo.
Dios introduce la naturaleza de Su Hijo en el corazón
y engendra allí algo de Su propia semejanza,
mediante lo cual llama y da la habilidad de creer.
Esta fe es imputada por Dios para justicia en todo corazón donde quiera que se encuentre;
y dondequiera que esta fe en la virtud viva sea hallada,
ahí borra Dios las iniquidades por amor de Su nombre.
Sí, y la remisión del pecado es sentida en aquello que es vivificado.

[.discourse-part]
Pregunta: ¿Puede un hombre ser justificado sin haber oído nunca de Cristo externamente?

[.discourse-part]
Respuesta: Si un hombre experimenta la Semilla de vida, es vencido por Su naturaleza,
se rinde ante Su ley según es hecha manifiesta en su corazón,
aborrece la naturaleza y ley del pecado y muerte, y en consecuencia,
se aferra al Señor en su alma y lo sigue,
entonces el Espíritu y vida del Señor no pueden sino justificarlo.
La gracia y misericordia del Señor no pueden negarse a darle perdón
de sus pecados pasados (y dejar pasar sus futuras debilidades),
aunque él no sepa claramente cómo implorar por ellas.
La redención y el perdón de pecado ocurre por la ilimitada gracia de Dios,
la cual no está restringida al conocimiento externo de la criatura,
sino que emerge según la capacidad que Dios da para recibirla.
La vida, misericordia, gracia, perdón, etc., salen de Dios hacia vasijas de todo tipo,
pues el objetivo de Dios en todas Sus dispensaciones
es la experiencia interna de la vida,
no la habilidad o el conocimiento externo.

[.discourse-part]
Pregunta: ¿Cómo es la justificación por gracia?

[.discourse-part]
Respuesta: Ningún hombre en su estado caído merece algo de Dios.
Por Su gracia lo visita mediante cualquier derramamiento de Su amor y misericordia.
Por Su gracia le da alguna capacidad de volverse hacia Él. De hecho,
es tal la debilidad del hombre,
que ninguno puede ser justificado por obras de obediencia
que realice bajo cualquier dispensación,
sino sólo por la remisión y capacidad que recibe de la gracia.

[.discourse-part]
Pregunta: ¿Cuál es la justicia que justifica ante los ojos de Dios?

[.discourse-part]
Respuesta: Sólo la justicia de Cristo.
Esta justicia transmitida a la criatura en y a través de la Semilla,
producida en la criatura por medio de la Semilla,
y la criatura unida a Cristo en la Semilla, es la justificación de vida.

[.alt.centered]
==== CON RESPECTO A LA SANTIFICACIÓN

[.discourse-part]
Pregunta: ¿Qué es santificación?

[.discourse-part]
Respuesta: La limpieza de la vasija por medio del Espíritu del Señor,
de la contaminación tanto de la carne como del espíritu.

[.discourse-part]
Pregunta: ¿Por medio de qué limpia el Espíritu del Señor a la vasija de su contaminación?

[.discourse-part]
Respuesta: Mediante la Verdad viva que tiene poder en ella para lavar el engaño,
la enemistad, la impureza y cualquier maldad que haya ensuciado anteriormente la vasija,
o que pueda contaminarla de nuevo en cualquier momento.

[.discourse-part]
Pregunta: ¿Cómo recibe el alma esta limpieza o purificación del Espíritu del Señor?

[.discourse-part]
Respuesta:
Al obedecer Su verdad hecha manifiesta en el corazón. Porque mediante
esa obediencia el poder de la palabra entra en el alma y derrama
abundantemente Su virtud viva en ella.

[.discourse-part]
Pregunta: Entonces,
¿en qué debe ocuparse principalmente el alma que desea ser purificada de su inmundicia?

[.discourse-part]
Respuesta: En la obediencia de la fe, o en la obediencia que brota de la fe.
Porque así como todos los beneficios y bendiciones
de la ley dependían de la obediencia a la ley,
así dependen los beneficios y bendiciones del evangelio de la obediencia al evangelio.
Sí, y esta es la gloria y excelencia del evangelio:
Que el principio de la fe hace ahora lo que el principio de la ley nunca pudo.

[.alt.centered]
==== CON RESPECTO A LA RECONCILIACIÓN

[.discourse-part]
Pregunta: ¿Qué es reconciliación?

[.discourse-part]
Respuesta: Es unir las mentes y corazones de Dios y del hombre en Uno.

[.discourse-part]
Pregunta: ¿Cómo se logra?

[.discourse-part]
Respuesta: Eliminando la enemistad de la naturaleza del hombre,
la cual es contraria a Dios, y plantándolo en la naturaleza y vida que Dios ama,
y haciéndolo crecer en ella.
De esta manera, lo que Dios odia y es causa de separación, es removido del hombre,
y el hombre es introducido y criado en lo que es el amor y deleite del corazón de Dios.

[.discourse-part]
Pregunta: ¿Por medio de qué se logra esta reconciliación?

[.discourse-part]
Respuesta: Por medio de la Palabra de poder de Dios.
Esta Palabra brota del amor de Dios hacia el hombre,
que al ser rescatado de sí mismo e introducido en Ella,
la semilla del mal es destruida y la buena Semilla del reino amada.

[.alt.centered]
==== CON RESPECTO A LA REDENCIÓN

[.discourse-part]
Pregunta: Qué es redención?

[.discourse-part]
Respuesta:
Es la compra de la vasija para sacarla del cautiverio y de la miseria de la muerte,
e introducirla en la libertad y bendición de la vida divina, la cual es sembrada,
revelada, incrementada y perfeccionada en el corazón.

[.discourse-part]
Pregunta: ¿Quién es el redentor?

[.discourse-part]
Respuesta: El Hijo de Dios, el Hijo engendrado de Dios, la imagen divina,
el que cree y cumple naturalmente la voluntad del Padre en cada vasija que Él ha preparado.

[.discourse-part]
Pregunta: ¿Por medio de qué redime Él?

[.discourse-part]
Respuesta: Por medio de Su sangre, Su vida, Su poder,
Su naturaleza sembrada en la vasija y transformándola a Su imagen.
Sí, esto, en efecto, es redención:
Cuando la criatura es transformada y llevada bajo el gobierno de la imagen, poder,
naturaleza, virtud y vida divina del que Redime.
Y la vieja imagen, la contraria,
es perfectamente borrada por Su presencia y la criatura habitada por lo nuevo.
Esta es perfecta redención, la menor medida de lo que es redención en cierto grado.

Después de esto brota la gloria de la Vida en la vasija, es decir,
la gloria que tenía con el Padre antes de que el mundo fuese.
La gloria está escondida en la naturaleza de la Vida.
Está sembrada en la Semilla, muere con la Semilla y es levantada con la Semilla.
Cuando Sión es edificada en cualquier corazón es
natural que el Señor aparezca en Su gloria ahí;
el ojo puro Lo ve, el corazón puro se deleita y es uno con Él. Por tanto,
así como hay una verdadera entrada, comunión y deleite en la muerte de Cristo,
también hay resurrección y gloria de la vida redimida.
Esta es la porción y herencia que Dios ha preparado para Sión,
después de su larga desolación y dolorosa viudez.
Esta porción Él se la dará a la vista de todo el mundo,
por lo que se convertirá en la belleza, gozo y alabanza de toda la tierra.

=== Una Última Palabra de Advertencia

Estoy seguro de que para el Señor sería sencillo dar una
descripción literal de todas las cosas de Su reino,
tan exacta, completa y clara como para responder y satisfacer toda mente inquisitiva.
Sin embargo, eso no efectuaría la obra en la que Dios está ahora.
No levantaría Su semilla,
la cual yacería muerta y sepultada bajo todas estas descripciones,
a menos que fuera directamente vivificada y levantada por el poder y la vida del Padre.
¿Acaso no edificaría el espíritu terrenal fácilmente
un tejido terrenal con palabras tan claras,
el cual no estaría en concordancia con la medida del verdadero templo?

¿Puedo hablar libremente?
Yo no les ocultaría nada que es de Dios,
ni tampoco sería un instrumento para apagar el menor bien en ninguno.
No obstante, he visto, sentido y conocido algunas de sus trampas,
y preferiría gastar la fuerza de mi espíritu clamando a
Dios por ustedes para que Él quebrante y desenrede sus almas,
que intentar demostrárselas y manifestárselas a ustedes.
Y ahora estoy pensando en una de estas trampas en la que ustedes han caído,
la cual no es la más pequeña, a saber:
Obtener conocimiento de cosas en la mente y comprensión
que se esfuerzan por crecer ricas y sabias ahí,
para entender y disputar acerca de ellas.
Si el Señor no tocara mi alma continuamente para
que rinda el conocimiento externo de todo,
y para que siga adelante en pos de la vida interior,
yo podría crecer pronto sabio según la carne,
pero perdería el aceite fresco que me suaviza y me nutre.
Mi espíritu se inclina y se oprime dentro de mí fervientemente ante el Dios de misericordias,
para que ustedes no se queden detrás de la manada
cuyo camino es vivo y sigue las pisadas del Cordero,
Quien conduce por Su Espíritu vivo de vida a vida hacia Su reino.
