== Capítulo XIV. Las Dos Semillas

Esta es la sustancias de nuestra religión: Primero,
experimentar y discernir las dos semillas, es decir,
la semilla de enemistad y la semilla de amor,
la semilla de la carne y la semilla del Espíritu,
la semilla de Agar y la semilla de Sara,
la semilla del vientre egipcio y la semilla santa de Israel.
Segundo,
experimentar los juicios de Dios administrados a una de
estas semillas hasta que sea llevada a cautiverio y muerte;
y experimentar a la otra Semilla levantándose en el amor
y misericordia del Señor para vivir en nosotros,
y para que nuestras almas sean reunidas en ella y vivan para Dios en ella.

Ahora,
cuando la luz del Espíritu Santo de Dios irrumpe
sobre el hombre y Su virtud vivificadora es sentida,
la vida entra en aquello que estaba muerto,
y un deseo de salir del estado egipcio rumbo a la buena tierra es engendrado
en el corazón. Puesto que el alma fue creada por Dios,
añora regresar a Él, salir del estado pecaminoso, errante,
miserable y perdido para poder vivir y caminar con Él en la pureza,
virtud y poder de Su propia vida y Espíritu.

Pero entonces, el nacimiento carnal pelea por su vida, y Faraón el rey de Egipto,
toma parte junto con sus egipcios contra Israel.
En esta pelea no hay ayuda para la pobre alma,
excepto cuando Dios derrama Sus juicios sobre esa naturaleza dura
y sobre el espíritu del hombre que es del nacimiento de la carne,
y que recibe influencia y fuerza de su padre que lo endurece contra la verdadera Semilla.
Ahora bien, ¿en qué condición está la pobre alma?
La luz del Espíritu de Dios le da consciencia de su estado y los
movimientos vivificadores de la vida le hacen palpable su esclavitud.
También se levantan algunos deseos y anhelos en busca de la liberación,
pero estos sólo provocan al enemigo,
porque el alma todavía está en su territorio y bajo su poder,
y él se ocupa más duramente de ella incrementándole sus cargas y la opresión diaria.
¡Oh, los clamores del alma en este estado! ¡Cuán dolido,
angustiado y molesto está su espíritu en su interior, tanto,
que casi podría escoger permanecer en Egipto, en lugar de sufrir las pesadas cargas,
opresiones, temores y peligros con los que diariamente se topa en este estado!

Sin embargo,
hay una secreta esperanza brotando en el corazón que proviene de la verdadera Semilla,
y que a menudo lo anima a confiar en Él y a esperar en Aquel
que ha visitado con Su ministración pura de juicio.
Pues en la medida que el alma es hecha verdaderamente consciente por el Señor,
es sentido varias veces que el juicio no es para la semilla, no es para Israel,
sino para Faraón y sus egipcios, y que con cada golpe de la ira de Dios sobre ellos,
la semilla es más aliviada y su liberación obrada.

Así que, cuando el juicio es por fin acabado en la tierra de Egipto,
cuando la fuerza de Faraón y sus egipcios es quebrantada y sus primogénitos liquidados,
Israel sale; sale de la tierra de oscuridad,
sale de la casa de servidumbre y viaja hacia su lugar de reposo.
Entonces el Cordero pascual es conocido y comido.
De hecho, es debido a la sangre del cordero rociada en los dinteles de las puertas,
que Israel es pasado por alto y salvado en el día de la visitación a Egipto.

Pero ahora, cuando la semilla es sacada de Egipto no es el final de todo,
sino el comienzo de sus viajes.
Faraón y sus egipcios con sus caballos y carros pueden perseguirla otra vez, e incluso,
darle alcance.
Puede que parezca que el alma no tiene escape o que no hay forma de ayudarla,
sino quedándose quieta, esperando en el Señor y aguardando ver Su salvación. Entonces,
el mar que detenía el avance de Israel será dividido,
y Faraón junto con sus egipcios (los enemigos del alma en esta aparición de terrible
y opresivo poder) serán destruidos y jamás volverán a ser vistos.

Aún así, en el desierto, en el paso a través de los enredos hacia la tierra santa,
hay muchas estrecheces, pruebas y enconados enemigos por enfrentar.
Algunos enemigos lucharán abiertamente por la fuerza,
otros buscarán engañar a Israel con sus encantamientos.
Pues todavía hay una parte de Israel que no ha sido derribada,
que todavía no ha sido sometida, en la que los enemigos lucharán para penetrar la mente.
En la medida que Israel olvide a Su Dios y camine fuera de Su consejo,
y esté atento a eso que su oído no debería oír, uniéndose así a la semilla contraria,
en esa misma medida las plagas, juicios,
indignación y aflicción serán sentidas por él y muchos pueden caer.
Aquí puede haber un gran clamor en el corazón:
"`¿Quién puede permanecer delante de este Señor Dios santo?
¿Moriremos todos completamente?`"
Sí, hay algo que debe morir completamente.
Pues aunque un hombre llegara tan lejos como para experimentar
el dominio y la victoria sobre los enemigos de su alma,
y la semilla maligna llevada a muerte en él, aún así, si esa parte no se mantiene muerta,
el enemigo volverá a sembrar para la carne.
Sembrará otra vez algunas de sus semillas corruptas
en el corazón (si el alma se duerme y es negligente),
y la corrupción echará raíces de nuevo,
el nacimiento contrario crecerá y las zorras irrumpirán
en el viñedo y estropearán las uvas tiernas.

Así, pues, esta es nuestra religión: Conocer las dos semillas,
experimentando una siendo derribada y la otra siendo levantada por el poder de Dios.
Esto se debe presenciar todos los días,
al experimentar diariamente el mismo poder que mantiene
una semilla en la muerte y la otra en la vida,
por medio de la santa ministración del pacto vivo y puro de Dios.
En esta forma debemos conocer a Dios en este pacto, en este pacto que vive,
da vida y conserva en la vida.
Y así debemos caminar con Dios, adorarlo y servirlo en Su Hijo: en la luz de Su Hijo,
en la vida de Su Hijo y en la virtud y habilidad que fluyen de Su Hijo a nuestros espíritus.
Esta es, entonces, nuestra religión,
la que el Señor nuestro Dios en Su tierna misericordia nos ha otorgado.
De hecho, encontramos que esta es la religión pura, viva e inmaculada delante de Dios,
y experimentamos diariamente Su aceptación de ella en y a través de Su Hijo,
Cuyo nombre es conocido y confesado, adorado y honrado aquí,
en concordancia con el corazón mismo del Padre.

Esto puede ser adicionalmente ilustrado, y tal vez ser más notorio para algunos,
mediante una o dos escrituras.

"`Porque el deseo de la carne es contra el Espíritu,
y el del Espíritu es contra la carne; y éstos se oponen entre sí...`" (Gal.
5:17)

Aquí tenemos dos semillas (la semilla de la serpiente y la semilla de la mujer)
cuyos esfuerzos y peleas se dan en el hombre una vez que Dios despierta el alma.
Una tiene una naturaleza, deseo o codicia contraria a la otra.
Cuando una de estas prevalece en un corazón, la otra baja.
Cuando una gana vida y poder, la otra es llevada a muerte y cautividad.
Por lo tanto,
lo siguiente es lo que todos tienen que esperar después de llegar
al conocimiento vivo y experiencia de estas dos semillas:
Experimentar la carne derribada,
la codicia de esta negada y los juicios del Señor administrados sobre ella,
y experimentar a la otra semilla levantarse para vivir,
prosperar y prevalecer en el alma;
de esta manera el alma experimenta salvación y redención bajo su sombra:
"`Sion será rescatada con juicio, y los convertidos de ella con justicia`" (Isa.
1:27).

¿Qué es Sión? ¿No es el santo monte de Dios donde
Su Hijo se establece como Rey para reinar,
donde la ciudad santa es edificada y Dios adorado en espíritu?
¿En qué condición está Sión cuando Dios la visita para redimirla?
¿No yace devastada, desolada y en el polvo?
(Sal.
102: 12-13) Pues bien, ¿cómo la redimirá Dios?
"`Sion será rescatada con juicio, y los convertidos de ella con justicia.`"
La redime al traer juicio sobre lo que la mantiene sometida, sobre sus enemigos,
la semilla contraria, y redime a sus convertidos,
al traer justicia (la vida justa y el Espíritu de Su propio
Hijo) en aquellos cuyas mentes se han vuelto a ella,
y cuyos rostros están dirigidos hacia Sión. Sí,
esto es verdaderamente sentido y experimentado:
En la justicia viva de Cristo revelada en el corazón y teniendo poder ahí,
Él libera de toda la injusticia que había ahí antes, y luego,
cuando el injusto es expulsado,
el Justo revelado y el alma unida a Él (recibiendo toda virtud y poder de Él),
esta se vuelve sierva de la justicia y no comete pecado, sino que hace justicia;
"`...el que hace justicia es justo,
como él es justo`" (1 Juan 3:7). Si la vida justa
es revelada y levantada en dominio en Él,
¿cómo podría ser de otra manera?
¿Cómo podrían el mismo Espíritu justo y la vida (ahora revelados
en los miembros tal como estaban en la Cabeza) sino vivir y actuar
en los miembros de la misma forma que lo hicieron en la Cabeza?
(¡Oh,
se volvieran los hombres a lo que les puede dar el conocimiento
cierto y la experiencia viva de esto!) Esto es en extremo precioso
para los que están viajando verdaderamente hacia ello,
y más aún, para los que lo disfrutan.

Estas tres cosas son la suma de todo:
1) Conocer y experimentar lo que tiene que ser derribado y mantenido en muerte.
2) Conocer lo que tiene que ser levantado de la tumba
y vive para Dios y reina en Su dominio.
3) Conocer lo que debe ser mantenido en sujeción
y obediencia a Aquel que tiene que reinar.
Ahora, bien, ¡experimentar esto cumplido en el corazón (la carne derribada,
la Semilla de vida levantada y el alma sujeta al poder puro celestial) es, en efecto,
un estado bendito!
Pues aquí la obra está hecha, el trono de Dios exaltado,
Su Rey reina en justicia y paz y todos Sus enemigos están bajo Sus pies.

Pues en el estado externo el Israel externo tenía
que guardarse para Dios en el pacto externo;
y este tiene que ser el estado interno del Israel interno,
guardarse para Dios en el pacto interno, el cual es un pacto puro de vida y paz.
Este es el pacto de todas las bendiciones y misericordias
internas y espirituales en Cristo,
en el que las almas de quienes son obedientes a Dios
y caminan humildemente con Él son bendecidas.
Ahora, ¿cuál es el Israel que debe heredar estas promesas?
El Israel de Dios,
porque todas las promesas son "`sí y amén en Cristo`" para él. Entonces,
¿por qué el Israel de Dios no debería tener la esperanza de disfrutar estas cosas?
¿No deberían ellos conocer al Espíritu Santo de Dios y esperar
en Él para experimentar lo que se les ha concedido?
¿No deberían ser liberados de las manos de sus enemigos para servirle a Dios sin temor,
en santidad y justicia delante de Él (Cuyos ojos son penetrantes
y no pueden contemplar iniquidad) todos los días de sus vidas?
Verdaderamente,
los hijos del nuevo pacto no podrán llegar a vivir completamente para Dios,
hasta que experimenten la circuncisión interna del corazón,
para amar al Señor con todo el corazón y con toda el alma.
(Deut.
30:6) ¡Oh,
si tan sólo el pueblo tuviera una experiencia del poder de Dios
y creyera en él! ¿Qué podría interponerse en el camino de este?
¿No fue el pecado del Israel antiguo que miraron a sus enemigos y vieron la fuerza de
ellos en la tierra que Dios le había prometido como herencia a la semilla de Abraham?
Ellos no pudieron creer que tales enemigos podían ser vencidos.
¡Oh, tengan cuidado de no caer en la misma incredulidad hoy!

=== Con Respecto a Venir al Padre por Medio de Cristo

"`Yo soy el camino, la verdad, y la vida;
nadie viene al Padre si no es por mí.`" (Juan 14:6)

El hombre en el estado corrupto y degenerado,
ha caído de Dios y ha perdido Su imagen (la imagen
santa y celestial del Padre de los espíritus).
Ha sido expulsado de la presencia de Dios y habita en la tierra de oscuridad
y confusión bajo el gobierno del príncipe del poder del aire,
quien rige y tiene poder sobre todos los hijos de desobediencia.
Ahora bien, este debería ser el objetivo del hombre: Regresar al Padre;
salir del estado pródigo y perdido hacia la casa del Padre,
donde hay cantidad suficiente y plenitud de pan y agua de
vida para satisfacer a toda alma hambrienta y sedienta.

El camino por el que el hombre debe venir,
la verdad en la que debe ser renovado y la vida en la que debe ser vivificado es Cristo,
el Hijo del Dios vivo.
El hombre tendrá que conocer a Cristo como el Hijo del Dios vivo,
experimentarlo en el interior recibido y revelado, y como resultado,
caminar en Él como el camino, la verdad y la vida,
si en algún momento quiere venir al Padre.
No debe descansar sobre una mera descripción de estas cosas, sino experimentar, conocer,
recibir y caminar en la cosa misma que el Espíritu
del Señor ha descrito tan a menudo en palabras.
No debe recibir, simplemente,
todo lo que fue declarado sobre Él anteriormente o todo lo proclamado ahora.
En efecto,
el alma que vaya a vivir por medio de Él tendrá que recibirlo
como la raíz santa y experimentar ser injertado en ella,
en la Palabra viva del eterno poder de Dios.
Tendrá que conocer esta Palabra injertada en su corazón,
para que llegue a haber una unidad real en naturaleza y espíritu con Él. Solo entonces,
un alma está verdaderamente viviendo en la Vid y en el Olivo,
participando de Su virtud y Su savia, y caminando en Su Espíritu, vida y poder.

Un hombre no puede caminar aquí en el arcaísmo de la letra,
sino en la novedad del Espíritu.
Pablo, a pesar de todo su conocimiento de las Escrituras,
caminaba en el arcaísmo de la letra antes de que Cristo fuera revelado
en él. Aquellos que en los días de los apóstoles tenían una apariencia
de piedad pero se habían vuelto del poder y lo habían negado,
también caminaban en el arcaísmo de la letra.
Incluso la iglesia de Sardis (en su mayor parte) y la iglesia de
Laodicea (que había recibido el orden correcto y las ordenanzas,
la verdadera descripción de las cosas y pensaba que estaba llena,
enriquecida y que no le hacía falta nada),
caminaban de acuerdo al arcaísmo de la letra y no
en la novedad y poder del Espíritu de vida.
¡Pero ay, cuántos hay en este día que proclaman conocer a Cristo,
pero nunca han llegado tan lejos como para caminar en el arcaísmo de la
letra a partir de un entendimiento verdadero! ¿Podrán tales hombres tener
la posibilidad de entender la verdad o conocer sus apariciones internas,
espirituales y preciosas, sea en sus propios corazones o en los corazones de otros?
¡Con seguridad no! ¿Por qué? Esta es la razón:
Porque ellos miden las apariciones de la verdad en sí mismos y en otros,
mediante sus propias comprensiones y concepciones de la Escritura, que en definitiva,
no son la medida apropiada para ellas.
Todos esos hombres no son sino ciegos guiando ciegos, y de continuar en este camino,
sin la menor duda, caerán en el hoyo de perdición.

Nadie puede conocer a Cristo correctamente sino por
la revelación interna que proviene del Padre.
El misterio debe ser develado internamente o no hay verdadero conocimiento.
El misterio de engaño es puesto al descubierto en el interior y el misterio
de vida también. Cualquiera que experimente a Cristo revelado en el interior,
Lo hallará revelado para este fin:
Destruir las obras del diablo ahí. Él es un poderoso Salvador del alma
del pecado y un poderoso Destructor de las obras del diablo en el interior.

Ahora, con respecto a la lectura de las Escrituras, mantengan esto en mente:
Se dice de los judíos que cuando ellos leían el Antiguo
Testamento el velo estaba puesto sobre sus corazones,
el cual es quitado en Cristo.
(2 Cor.
3:14-15) ¡Oh, consideren ahora seriamente! ¿Ha sido quitado el velo de ustedes?
¿Leen ustedes las Escrituras con el ojo descubierto?
¿Leen en la unción, en el Espíritu de Cristo,
en la sabiduría pura y celestial del divino nacimiento?
Fue prometido desde la antigüedad que Dios quitaría
la cubierta con que están cubiertos todos los pueblos,
y el velo que envuelve a todas las naciones.
(Isa.
25:7) ¿Experimentan ustedes esta promesa cumplida?
¿Conocen ustedes la diferencia entre leer las Escrituras
con el velo puesto y con el velo quitado?
¿Están las Escrituras abiertas y desbloqueadas para ustedes por la llave de David,
para que las puedan leer y entender en la luz y demostración del Santo Espíritu de Dios?
O,
¿están sus propios entendimientos y voluntades en operación cuando escudriñan las Escrituras?
Si el nacimiento equivocado,
la sabiduría equivocada o el entendimiento equivocado están en operación,
sólo se puede recoger aquello que los alimentará y fortalecerá.
Si ustedes no están en Cristo ni leen en Cristo,
el velo no ha sido quitado de ustedes,
pues el velo sólo es eliminado en Él. Si ustedes leen y caminan en el
arcaísmo de sus comprensiones de la letra y no en la novedad del Espíritu,
entonces tampoco conocen las Escrituras ni el poder de Dios,
sin importar lo que puedan alegar frente a los hombres o soñar con respecto a sí mismos.
Pues sus propios conocimientos, comprensiones, fe, esperanza,
paz y gozo (al estar fuera del alcance de la verdad pura y viva) no son más que sueños.

Las Escrituras son palabras, cuyo principal fin,
significado y servicio es llevar a los hombres a
la Palabra de la que las Escrituras salieron.
Cuando los hombres llegan ahí y permanecen en esta Palabra,
están en la vida de las Escrituras y experimentan el cumplimiento de las Escrituras.
Allí encuentran los justos juicios de Dios ejecutados sobre ese espíritu,
mente y naturaleza en ellos que es contraria a Su imagen.
Allí conocen el cumplimiento de las promesas y las seguras
misericordias que pertenecen a Cristo la Semilla,
y a los que están reunidos y permanecen en Cristo la Semilla.
Allí está el pacto, el nuevo pacto.

Ahora, bien, todo lo que ha sido dicho en las Escrituras con respecto al pacto,
no es más que una descripción en palabras de dicho pacto, pero Cristo en el interior,
la expectativa de gloria, el Espíritu en el interior, el temor en el interior,
el poder de vida en el interior quebrantando y reinando
sobre el poder del pecado y la muerte,
es el pacto.
La fuerza y la virtud del pacto son experimentadas en el alma,
en la medida que es sentido el poder de la vida revelado en ella.
Entonces el alma es sometida al poder de Cristo, quien reina en justicia, amor,
misericordia y paz en los corazones de aquellos que
Él redime de la naturaleza y espíritu terrenales,
hacia la mente y Espíritu de Su Padre.
Allí los salmos, himnos y cantos espirituales, los cantos puros (el canto de Moisés,
el canto del Cordero) son entonados al Padre de los espíritus, al Redentor de Israel.
Estos son cantos que nunca fueron cantados,
ni pueden ser cantados en ninguna parte de Babilonia.

=== Con Respecto a Cristo Manifestado Afuera y Adentro

Se objeta contra nosotros que negamos a Cristo (y que no buscamos
ser salvos por Él) tal como fue manifestado externamente,
y que sólo buscamos ser salvos por un Cristo en nuestro interior.
Está sobre mi corazón responderles a aquellos quienes, con respecto a esta objeción,
desean verdaderamente satisfacción.

Nosotros, ciertamente, sí expectamos ser salvos (sí, y no sólo expectamos,
sino que ya experimentamos salvación en nuestras diversas medidas) por
la revelación y operación de la vida de Cristo en nuestro interior.
No obstante, esto no deja de tener relación con lo que Él hizo externamente,
pues todo lo que Él hizo en el cuerpo de carne era del Padre,
tenía su lugar y servicio en la voluntad del Padre y era de acuerdo al consejo del Padre.
Sin embargo, desde los días de los apóstoles,
el conocimiento y la creencia de esto se ha mantenido en injusticia y
separado de la obra interna del poder y la vida de Cristo en el corazón,
y cuando es mantenido así, no puede salvar a nadie.
Pero el que experimenta la luz y la vida de Cristo revelada en él,
y se une a Dios de esta manera, experimenta la obra de regeneración, santificación,
justificación, vida y redención,
y de esta manera llega a cosechar el beneficio interno y
bendito fruto de todo lo que Cristo hizo externamente.
En verdad, el que es uno con Cristo en Espíritu,
no puede excluirse (ni es excluido por Dios) de la ventaja de todas
y cada una de las cosas que Cristo hizo en Su cuerpo de carne.

De hecho, de esto se trata el asunto principal:
Ser testigos por una experiencia viva de la salvación obrada en el corazón;
experimentar el eterno poder y el brazo del Señor asiendo el alma para salvarla.
Y no sólo para salvarla,
sino para obrar y efectuar en ella la salvación tan verdaderamente
en sustancia como la experimentó en sombra el antiguo Israel.
Porque así como ellos fueron testigos de Moisés y Josué externamente,
así el israelita verdadero, el israelita interior,
el israelita espiritual debe experimentar eso que es la sustancia de estos, es decir,
al Hijo de Dios revelado internamente.
Ahora bien,
ellos no fueron salvados externamente por una creencia vacía y externa
de que Moisés y Josué habían sido enviados por Dios para salvarlos,
sino por seguirlos en fe y obediencia a lo que era requerido por Dios.
De la misma manera es dado Cristo al Israel interior, para liderarlo y comandarlo,
Quien aparece al alma angustiada y esclavizada en Egipto,
la saca de Egipto y la guía hacia la buena tierra y la introduce en ella.

Bien, en la medida que el alma siga y crezca en las apariciones de Cristo
y obedezca Su voz en el pacto de vida santo y puro,
en esa misma medida será obrada la redención del alma.
Pero en la medida que la incredulidad y la desobediencia se levanten,
el corazón se endurezca en cualquier momento contra Su voz y consejo,
y el oído se abra a la tentación del enemigo,
en esa misma medida la redención retrocederá y la
angustia y el cautiverio regresarán. Esto es testificado,
conocido y experimentado por cada verdadero viajero hacia Sión. Por tanto,
el requerimiento principal es permanecer en la experiencia del poder del Redentor,
a la espera de Sus movimientos y apariciones, y en la fe y obediencia de los mismos.
Porque el pecado reúne fuerza y es dado a luz al dejarlo
entrar y darle paso a los movimientos de este.
Así también, la santidad y la justicia son dadas a luz y ganan terreno en el corazón,
al estar este atento y rendido a las agitaciones
y movimientos del Espíritu Santo de Dios.
Por tanto,
es de enorme necesidad que todo verdadero viajero
llegue al entendimiento y distinción de estas cosas,
y que su corazón sea guardado con toda diligencia,
pues del corazón mana tanto la vida como la muerte.
¡Muy feliz es aquel que experimenta el flujo de muerte detenido y el flujo de vida abierto!
¡Muy felices son aquellos cuyos espíritus están desnudos y abiertos delante del Señor
en busca de que la vida brote y mane según el tiempo y voluntad de Dios!

¡Oh,
qué precioso estado experimentar la cautividad llevada a cautiverio
por la vida y el poder de la vida reinando sobre ella!
Hay, verdaderamente,
una liberación tan real experimentada internamente por los que
esperan en el Señor y son fieles a la guía de Su Santo Espíritu,
como jamás fue experimentada por los judíos que seguían externamente
a Moisés y a Josué. Cristo es tan verdaderamente sanador de Su
pueblo en esta ministración de vida por medio de Su Santo Espíritu,
como jamás fue sanador de personas externamente en los días de Su carne.
Tales sanidades, junto con los otros milagros que hizo entonces,
no eran más que sombras de lo que obraría y realizaría
internamente en el día de Su Espíritu y santo poder.
Ahora,
¿quedará o podría Él (para los que fielmente esperan en Él) quedar
corto en la sustancia de la que testificó en sombras?
¡Definitivamente no!
Es la intención de Su corazón (y no fallará en realizarlo) salvar hasta lo sumo
a todos los que vengan al Padre por Él y permanezcan en Su pacto santo,
puro, justo y vivo.
Esta es la destreza del cristianismo:
Permanecer en Él. Sólo aquí se experimenta la virtud
viva y el poder puro que lo vence todo,
y el que nada puede vencer.

=== Unas Pocas Palabras con Respecto a la Semilla de Verdad

Pregunta: ¿Qué es la Semilla de verdad?

Respuesta: Es la luz, es la que reprende y manifiesta el pecado.
"`...porque la luz es lo que manifiesta todo.`"
Por esto Pablo dice: "`Despiértate, tú que duermes,
y levántate de los muertos`" (Ef. 5:13-14). Si no
fuera por la luz que pone de manifiesto el pecado,
no habría manera de despertarse del sueño y levantarse de la muerte.
¡Qué preciosa es esa luz!

Pregunta: ¿Cómo se puede discernir la Semilla de verdad?

Respuesta: Mediante la penetración de su naturaleza vivificante,
la cual se revela a sí misma en sus apariciones y operaciones.
Pues ella aparece y obra vívidamente, poderosamente y efectivamente en el corazón,
y no como la razón del hombre, ni como los movimientos de su mente,
los cuales él recoge en su parte intelectual.

Desde la caída, la razón del hombre es corrupta,
oscura e impura y está en la mano y bajo el poder del maligno.
Su naturaleza es esconder y cubrir el pecado, no descubrirlo.
Ahora bien, la luz de la ley, la que devela el pecado,
no se levanta en la razón del hombre.
¿Quién puede sacar la luz limpia y pura de la ley de la sucia e impura razón del hombre?
La luz ciertamente puede brillar en la oscuridad,
pero no es parte de ella porque es de otra naturaleza y origen.
Proviene del Espíritu de Dios y es dada al hombre en Su amor hacia él,
para sacarlo de sus caminos oscuros y de su espíritu,
y llevarlo al Espíritu puro y al camino de santidad.
Pues la luz que devela el pecado es totalmente santa y pura,
como la fuente de la que proviene.
Un hombre que está familiarizado tanto con la razón como con la luz,
puede distinguir la naturaleza y operaciones de ambas.
Pero hay una gran diferencia entre la Verdad sostenida en la parte
racional del hombre y la Verdad sostenida en Su propia semilla.
Es de poco efecto en una, y poderosa en la otra.
En los movimientos vivificadores puros de la vida,
la diferencia es claramente percibida y sostenida.
Por tanto, es nuestro consejo para todos los hombres,
que se vuelvan de toda mortalidad y vengan a experimentar
el manantial de vida que obra en el interior de ellos,
brotando en ellos para darles vida.
Los hombres deben esperar tener sus entendimientos
abiertos y mantenerlos así por medio de esta vida,
para que puedan recibir,
retener y no perder la capacidad de entender las cosas del reino de Dios.

Pregunta: ¿Cómo se puede comprar y poseer esta semilla o perla?

Respuesta: Muriendo a la propia sabiduría y voluntad del hombre; no hay otra forma.
La luz es totalmente contraria al hombre mientras este permanezca separado de Dios.
Ella opera contra el espíritu del hombre, sus pensamientos, sus deseos, su razón,
su entendimiento, es decir, contra todo lo que es de él. Por lo tanto,
el hombre no debe consultarle a ninguno de estos,
sino preferir la demostración pequeña y pura de la
luz del Espíritu de Cristo por encima de todo,
y estar dispuesto a desprenderse de todo lo suyo para siempre.
¡Oh, dura es esta palabra;
¿quién la puede oír?! ¡Ciertamente nadie excepto los que han sido enseñados y
han aprendido del Padre pueden llegar a rendirse y seguir la luz del Hijo!

Me atrevo a afirmar enfáticamente lo siguiente como una verdad permanente,
la cual ha sido sellada en mí por constante experiencia:
Ningún hombre puede estar de acuerdo con la luz y obedecerla,
a menos que se niegue a sí mismo y tome la cruz contra su propia sabiduría y voluntad.
Esta cruz es la cruz de Cristo, la cruz que es poder de Dios para salvación del alma.
Aquel que la toma cada día y espera en el Señor en ella,
experimentará el poder del Señor Jesucristo para redención de su alma.
Es más, será capaz de decir con verdadero entendimiento: "`Esta es luz en verdad,
vida en verdad, poder en verdad.
Ese poderoso brazo que me ha salvado del pecado y rompe las trampas,
estratagemas y fuerza del enemigo delante de mí (liberándome
cada día cuando nadie más puede,
y cuando mi propia fuerza y sabiduría son como nada).
Sé que es Cristo, el poder y la sabiduría viva de Dios revelada en mí,
Aquel que no le dará Su gloria a otro.
Porque Él es el Señor Dios de puro poder y vida para siempre,
y fuera de Él no hay Salvador.`"

=== Cómo Engendra y Mantiene la Semilla la Vida en el Corazón

El Señor Dios (Quien está lleno de compasión eterna hacia la humanidad en general,
pero más especialmente hacia aquellos en quienes Él ha engendrado
un sentido de anhelo en pos de Él) ha escogido una semilla
o manantial de vida interior para que aparezca en el hombre,
y rompa las cadenas de su cautiverio y lo saque de
debajo del poder y miseria de la muerte.

Muchos son los que han sido abrumados con miseria,
cuyos espíritus se han derretido y fracasado ante la falta de conocimiento de su Dios.
Muchos han experimentado el sentido de vida (que fue anteriormente
edificado en ellos) romperse y caer devastado,
su comunión con Dios consumida en sus ruinas,
y sus almas listas para perecer por completo y ser devoradas por el enemigo a cada momento.
Muchos han experimentado todas sus esperanzas cortadas
y sus ojos cerrados a toda forma de alivio.
Luego, yo digo, después de esto, en la tierna misericordia del Señor,
han sentido la Semilla de vida revelada en sus corazones,
y poco a poco han hallado sus corazones reunidos en esta Semilla donde reina la vida,
y donde la fuerza y dominio de la muerte están rotos en todos aquellos
que son conducidos por el llamado y guía del Espíritu del Señor.

Ahora, después de la revelación de esta Semilla,
ganar consciencia y experiencia de la misma, y el vuelco de la mente hacia ella,
lo más importante y necesario para la redención del alma
es esperar a estar más y más familiarizada con ella,
para que en Sus agitaciones,
movimientos y conducción el alma esté lista a ser reunida en ella y guiada por ella.
Pues aunque este don es todo vida, al principio no es más que una semilla,
y la aparición del Señor en el alma es en esa muy pequeña semilla, baja y débil,
difícil de ser discernida y fácil de ser despreciada y pasada por alto.
Usualmente se espera una mayor y más innegable aparición, pero esta no es la forma.
No, el alma debe llegar, primero que nada,
a sujetarse y a humillarse bajo esta pequeña aparición,
y conforme la Semilla obtenga ventaja y crezca más y más en el corazón,
la aparición del Señor será más grande y más plena ahí. Pero buscar una mayor aparición
antes de que la Semilla sea conocida y recibida en Su aparición más pequeña (y por consiguiente,
antes de que la vasija esté preparada para una mayor aparición) no es la manera de Dios,
sino más bien un engaño del enemigo.
Porque el enemigo desea destruir al alma y cortarla del Señor para siempre,
lo cual hará con toda certeza si puede evitar que la Semilla
crezca y que el alma se una y crezca en ella.

Por tanto, estén atentos a sentir el sabor de la vida en sus corazones día a día,
y a experimentar la guía y llamado de la vida que son apropiados para sus estados.
Pues en este sabor y en esta invitación se levanta la luz verdadera,
la que conduce al camino de vida.
Luego,
estén atentos contra los razonamientos y argumentos
que levantará el enemigo en sus mentes,
quien se esforzará para hacerlos jueces sobre estas cosas.
Porque la luz, la que se levanta en el sabor y en los movimientos del Espíritu,
es su Rey (aun en esta pequeña aparición), y Él no debe ser juzgado por la mente,
pensamientos y razonamientos del hombre, sino que más bien, Él debe juzgarlo todo.
Consideren además,
¿son ustedes (en su oscuridad y con su mente carnal) aptos para
ser jueces con respecto a la luz que se levanta en ustedes?
O, ¿no es la luz, en su más baja y débil aparición,
la designada y preparada por el Señor para juzgarlos y hacer
que se inclinen en temor y temblor delante de ella?
Entonces sus coronas (en su máxima exaltación) serán
aptas para ser tiradas a los pies de Él.

Por tanto, consideren dónde están,
y anhelen que el Señor les revele eso que es apropiado para ustedes en la actualidad.
Inclinen su espíritu bajo Su presente voluntad y presente manifestación en ustedes,
estén contentos de que sea pequeña y baja,
de recibir instrucciones pequeñas y bajas de Dios y de caminar en la senda de
quebrantamiento y humildad delante del Señor. Pues esta es Su manera de prepararlos
y de hacerlos avanzar hacia el alto y glorioso poder de Su vida.
Mi alma está segura de que nadie entrará o permanecerá en Su reino,
a menos que se vuelva pequeño,
pobre y desnudo y sea conducido por el pequeño niño engendrado por Dios.
Porque el Señor no responderá de ninguna manera a la sabiduría del hombre ni a sus expectativas,
más bien las confundirá y dirigirá al alma por la senda
que el ojo de la sabiduría del hombre no puede ver.
El que no discute, sino cree,
por temporadas sentirá progreso y entenderá el crecimiento
de la vida desarrollado en el corazón,
mediante aquellas mismas cosas que anteriormente parecían darle a la muerte la ventaja.

Por tanto, vigilen contra sus propios entendimientos y todas sus operaciones,
si alguna vez desean vida.
Porque sus entendimientos seguirán traicionándolos,
ya sea manteniéndolos alejados del camino,
o sacándolos de él cada vez que estén atentos a dicho entendimiento.
Y noten lo siguiente: Eso que Dios siembra y hace brotar en ustedes es una planta tierna,
no una mente enterada.
El juicio verdadero y correcto sólo se da en la comprensión de
esa planta y no en el entendimiento o comprensión de sus mentes.
Sí,
esa delicada planta (a la cual la sabiduría de ustedes estará muy
propensa a despreciar y pasar por alto) tendrá que derribar y llevar
a nada sus entendimientos y crecer en lugar de ellos,
si es que sus almas son hechas alguna vez una morada para la vida.

Por tanto, sumérjanse en el sentimiento, moren en la experiencia,
esperen el sabor de la Semilla de vida, los toques y persuasiones de esta.
Caminen en esto hacia la tierra de vida, sepárense de todo,
dejen atrás aquello que se opone al sabor de la vida
y entren en lo que sea que el sabor de vida disfruta.
En la medida que sean conducidos hacia esto y se sujeten a ello, así gustarán al Señor,
sentirán la dulzura de Su ungüento, la paz de Su naturaleza,
el gozo de los comienzos de Su reino en sus corazones y
la eliminación de sus iniquidades por causa de Su nombre.
Pues aunque el enemigo coloque una carga sobre ustedes,
los llene tanto como le sea posible con su suciedad y luego los acuse de todo, aún así,
el Señor considera la Semilla que Él ha sembrado en ustedes y el
deseo que Él ha labrado en sus corazones de ser unidos a ella.
Él sabe cuán débiles son ustedes en esta hora de oscuridad y cautiverio,
y la intención de Su corazón es liberarlos de todo esto y no condenarlos por ello.

Pero, ¡oh, tengan cuidado de limitar al Señor,
exigiendo que les dé el tipo de claridad o luz que el entendimiento natural juzga necesario!
Más bien,
conténtense con la luz que se levanta en la experiencia de Su sabor
y que brilla en el interior de sus espíritus cuando Él los llama.
Sujétense e inclínense bajo la luz de esta invitación,
aunque siempre sea contra la luz del entendimiento y razonamiento natural.
La verdadera claridad de la luz es un estado hacia el que ustedes deben crecer,
pero antes de llegar a ella, sus entendimientos deben ser oscurecidos,
confundidos y llevados a nada.
Por tanto, consideren cuidadosamente lo siguiente:

La primera obra del Señor es, con frecuencia,
confundir el conocimiento y entendimiento de la criatura,
especialmente en aquellas que han estado empapadas de la sabiduría y experiencia natural.
Pues si el Señor no las siguiera de cerca con oscuridad y confusión,
rápidamente empezarían a acumular conocimiento de nuevo en el viejo almacén,
crecerían sabias según la carne y nunca aprenderían la vida del Espíritu.
En esto el Señor no desea que la guía de Su Espíritu
sea manifiesta y clara de acuerdo a la carne,
ni para el entendimiento carnal.
En realidad, si fuera manifiesta de esta manera,
¿no bebería precisamente de ella la parte carnal?
Así, el hombre viviría otra vez, pero la Semilla no,
pues la Semilla gana su vida (y su forma y perfección)
en el hombre por medio de la muerte del hombre,
es decir, mediante la caza, azotes y quebrantamiento de su sabiduría, conocimiento,
razonamiento y comprensión. Precisamente así,
el hombre se convierte en un tonto o en un niño incapaz de saber algo, retener algo,
realizar algo o mantener su posición, excepto en la medida que sea nuevamente creado,
guiado, enseñado y preservado en el poder y por medio de la presencia de la vida.

=== Con Respecto a la Unidad Espiritual

Pregunta: ¿Qué es unidad espiritual?

Respuesta: La reunión de dos o más en la misma naturaleza espiritual,
reuniéndose en un único y mismo centro espiritual o manantial de vida.
Cuando los espíritus o las almas de las criaturas
son engendradas por un único poder en una única vida,
y se reúnen ahí en el corazón,
en tanto se reúnan de esta manera hay verdadera unidad entre ellas.

Pregunta: ¿En qué consiste esta unidad?

Respuesta: Consiste en la vida, en la naturaleza,
en el Espíritu en el que todas ellas son engendradas,
del Cual son formadas y dónde su reunión existe.
La unidad no consiste en alguna cosa externa,
ni en alguna cosa interna de naturaleza inferior,
sólo es hallada dentro de los límites y fronteras del mismo Espíritu.
Hacer una misma cosa, pensar una misma cosa, hablar una misma cosa no une,
sino únicamente, hacer, pensar o hablar en la misma vida.
Sí, y aunque las obras, pensamientos o palabras sean diversas,
si proceden de la misma semilla y naturaleza, allí es experimentada una verdadera unidad.

Pregunta: ¿Cómo se preserva la unidad?

Respuesta: Sólo permaneciendo en la única vida,
sólo manteniéndose en el poder y en la Semilla de donde brota y se encuentra la unidad.
Aquí, en el mismo centro espiritual,
se produce una unión y una comunión. Aquí los diversos y diferentes movimientos
de los varios miembros del cuerpo (que provienen de la vida y Espíritu
del cuerpo) son conocidos y reconocidos por la misma vida.
Mantener un conocimiento externo (o creencia con respecto a las cosas) no une,
ni tampoco mantener una conformación externa basada en acciones,
pues esto puede ser sostenido y hecho por otra parte en el hombre y en otra naturaleza,
sino permanecer y actuar en aquello que unió al principio.
En esto no hay causa ni espacio para la división,
y el que permanezca dentro de estos límites sólo puede hallarse en la unidad.

Pregunta: ¿Cómo se interrumpe la unidad?

Respuesta: Al interponerse algo de una naturaleza o espíritu diferente a la vida.
Cuando algo de la parte terrenal o sensual se sitúa entre el alma y la vida,
interrumpe tanto la unidad del alma con la vida misma,
como la unidad del alma con la vida que está operando en otros.
En cualquier cosa del espíritu del hombre, de la sabiduría del hombre,
de la voluntad del hombre que no se incline ni se sujete, y por tanto,
no emerja en y bajo la autoridad y guía de la vida,
hay algo de la naturaleza de división siempre.
De hecho,
el conocimiento mismo de la verdad expresado por
la sabiduría del hombre y en su propia voluntad,
fuera de los movimientos y poder de la vida, frena la vida e interrumpe la unidad.
Pues la vida en otros no puede unirse en espíritu con esto,
aunque reconozca las palabras como ciertas.

Pregunta: ¿Cómo se puede recuperar la unidad si en algún momento se pierde?

Respuesta: Sólo en el Señor está la recuperación de Israel,
de cualquier medida de pérdida, de cualquier tipo y en cualquier momento.
Sólo Él puede enseñar a retirarse y a ser hallado en donde la unidad está y permanece,
y donde la división no puede entrar.
Esta es la manera de restaurar la unidad de Israel cuando
se experimenta alguna medida de carencia de la misma:
Cada quien (en su caso particular) debe regresar
a la Semilla de vida a través de la ayuda del Señor,
para que ahí experimente un lavamiento de lo que se haya
corrompido y un nuevo engendramiento en el poder de la vida.
A partir de esto la verdadera y duradera unidad brotará rápidamente,
para regocijo de todos los corazones que conocen la dulzura
de ella y no pueden sino desearla natural y fervorosamente.

Por tanto,
la manera de recuperar la unidad no es mediante el esfuerzo de
reunir a muchos en la misma comprensión con respecto a cosas,
ni tampoco por el esfuerzo de llevar a todos a la misma práctica,
sino al ser atraídos hacia ese Espíritu en el que consiste la unidad,
el cual la manifestará en las vasijas que estén llenas y ordenadas por
Él. En este Espíritu deben esperar a diario el conocimiento nuevo y vivo,
y el ordenamiento de sus vidas y prácticas en la luz.
De esta manera,
la vida será sentida y el nombre del Señor alabado en todas las tiendas de Jacob.
Ahí habrá un solo corazón, una sola alma, un solo espíritu, una sola mente,
un solo camino y poder de vida.
Y el Señor será reconocido en lo que Él ya ha forjado en cada corazón,
y los corazones esperarán con contentamiento que
Él los llene de lo que haga falta en cualquiera.

Así el Dios vivo (el Dios de eterna y tierna compasión para
Israel) llenará las vasijas que son Su herencia de Su vida,
y hará que la paz y el amor de Su santa naturaleza y Espíritu desciendan sobre sus moradas,
y que Su vida brote poderosamente en ellos en dirección
a Su verdad viva y hacia unos y otros.

¡Esfuércense todos por sobresalir en ternura y longanimidad,
en ser guardados de duros y malos pensamientos unos contra otros,
y de interpretaciones severas con respecto a cualquier
cosa en unos y otros! ¡Esto es indigno de ser hallado,
de un israelita a un egipcio, pero mucho más vergonzoso e inexcusable,
de un hermano a otro! ¡Cuánta debilidad debe pasar por alto el Señor en nosotros!
¡Cuán listo está Él para interpretar bien lo concerniente a Sus discípulos que
permita una buena interpretación! "`El espíritu,`" dice Él,
"`está dispuesto, pero la carne es débil.`"
Cuando todos ellos se esparcieron tras Su muerte, Él no los reprendió después,
sino que dulcemente los volvió a reunir.
¡Oh, queridos amigos, ¿hemos recibido la misma vida de dulzura?
¡Produzcamos los mismos frutos dulces,
estando listos a disculpar y a recibir lo que nos lleve a la disculpa de otro
en cualquier caso dudoso! ¡Donde haya cualquier manifestación maligna,
esperen, sí,
esperen para superarla con bien! ¡No gastemos la fuerza
de nuestros espíritus quejándonos de otros debido al mal,
más bien vigilemos y miremos hacia donde la misericordia y la virtud sanadora se levantarán!
