== Capítulo XV. Cómo Discernir las Enseñanzas de Cristo

Desde mi infancia experimenté aflicción, lloro y búsqueda del Señor,
además de mucha pesadumbre y dolor de espíritu por causa de mi consciencia de la falta
de Él. Nunca estuve contento con la forma de religión en la que fui educado,
más bien (por causa de algo proveniente de Dios que se agitaba entonces en mí)
encontré grandes defectos en ella y fui atraído y conducido por el Espíritu de
Dios a atravesarla y a buscar más allá. Yo andaba en busca del lugar de reposo,
la verdadera vida de mi alma, el poder y la presencia del Señor,
la misma demostración de Su Espíritu (con respecto a la verdad
y al camino de Dios) que fue experimentada en los días de los apóstoles.
Sin embargo, el anhelo de esto y no reunirme con ello causó indecible angustia,
miseria y aflicción en mi corazón,
tanta que mi condición no pudo ser escondida dentro de mi
propio pecho y mi pena estalló a la vista de otros.

Al fin,
la misericordia eterna de Dios se compadeció de mí
y me mostró el lugar de reposo del alma.
He sentido el eterno brazo recogiéndome y dándome
una medida de lo que yo había buscado por tanto tiempo.
Así que ahora mi corazón está satisfecho con respecto
a la religión y a las cosas del reino de Dios,
al ser enseñado por Él a cómo conocer la Perla y cómo llegar
a heredarla y a disfrutarla también. De esta manera,
he tenido una gran experiencia del amor, misericordia, sabiduría, bondad,
poder y justicia del Señor. A pesar de todos los
enemigos de mi alma sigo sintiendo Su presencia,
vida y poder para Su alabanza,
lo cual obra en mí y me capacita para poner la esperanza
en Él y esperar en Él. Ahora bien,
en amor y ternura de corazón a otros,
está en mi corazón responder una o dos preguntas acerca del fundamento sobre
el que descansa la seguridad y la satisfacción que Dios le ha dado a mi alma.
No es mi deseo afligir o molestar a nadie,
sólo ser útil al exponer lo que el Señor ha demostrado y escrito en mi corazón.

[.discourse-part]
Pregunta: Puede que alguien se pregunte, cómo llegué yo a conocer al Espíritu de Dios,
Su iglesia y las Escrituras de los santos hombres,
que fueron escritas por la inspiración y guía del Santo Espíritu de Dios.
Puede que se pregunte,
cómo es que discierno los movimientos y la atracción de Su Espíritu en mí,
de los movimientos, sugerencias y tentaciones del espíritu maligno.
Y cómo es que me siento satisfecho de estar en el camino eterno
de la verdad y la vida sin salirme o desviarme de él.

[.discourse-part]
Respuesta: Esta es la manera que conozco: Recibir, unirme,
permanecer y crecer en la Semilla santa que el Padre de los espíritus
sembró en mí. Hay una Semilla elegida a la que es imposible engañar,
dicha Semilla la sembró el Padre y hace que crezca en el corazón de los
que la reciben (cuyo terreno es labrado y preparado por Él para ella).
Yo he sentido esta Semilla que proviene del Padre,
esta cosa santa y pura que no tiene comparación en virtud y excelencia.
Nada tiene Su naturaleza además de ella.
Nada manifiesta al Padre sino ella.
El corazón es cambiado, renovado y restaurado a la imagen santa sólo por esta Semilla.

En esta Semilla no hay engaño. Ningún engaño ha salido nunca de ella,
ningún engaño ha entrado alguna vez en ella, ni puede hacerlo.
Desde el día que la conozco, he sentido preservación por parte de ella,
en tanto mi corazón se ha mantenido para ella.
Mi ojo nunca vio mal en ella, mi oído nunca oyó mal en ella,
mi corazón nunca entendió mal en ella, todo lo contrario,
en ella he sentido que se me ha dado, y que por medio de Dios se ha mantenido en mí,
un ojo que ve, un oído que oye y un corazón que entiende las cosas de Su reino.
Aquí ha sido ministrada la entrada al reino eterno,
donde Dios revela por Su Espíritu los misterios de Su reino (del que todos
están excluidos salvo la Semilla y aquellos nacidos de ella).
Y cuando en algún momento en mis viajes, mediante cualquier tentación o engaño,
el enemigo se ha logrado meter entre mi alma y esta Semilla en algún grado,
en igual medida ha venido sobre mi alma oscuridad, pérdida, dudas, temores, luchas, etc.

[.discourse-part]
Pregunta: Pero, ¿cómo conozco yo esta Semilla?

[.discourse-part]
Respuesta: Mediante Su naturaleza, Sus propiedades,
las manifestaciones de Sí misma en mi corazón. Ella tiene esa luz,
esa vida y ese poder en sí misma que nunca encontré en ningún otro lugar.
Ella hiere la cabeza de la serpiente en Su tiempo
y por eso sé que es la "`semilla de la mujer.`"
Rompe en pedazos (a través de la sujeción a ella) lo que está en contra de Dios
y levanta Su naturaleza santa en mí. Así me lleva a la imagen misma de Su Hijo,
para que lo que yo lea en las Escrituras con respecto a la naturaleza,
justicia y obra de salvación de Cristo,
también lo encuentre formado y manando de mi propio corazón,
según soy recogido y moldeado en esta Semilla.

En ella experimento, conozco,
entiendo y me familiarizo con la sustancia de aquello que
todos los tipos y figuras de la ley expusieron en sombra.
En ella me encuentro con la circuncisión no hecha por manos externas,
el bautismo que es sin agua externa, la cena del Señor que es sin pan o vino externos.
En ella conozco al verdadero judío, cuya naturaleza, espíritu,
obras y caminos son todos de Dios, en y a través de Su Hijo Jesucristo.
En ella debo confesar que no dudo con respecto a las cosas de Dios,
pues en la luz y unción de esta Semilla veo tanto
el misterio de iniquidad como el misterio de bondad,
y los caminos y operaciones de cada espíritu, tanto interna como externamente.
Veo mi unidad con Uno (a través de la tierna misericordia, bondad,
amor y poder del Señor, todo lo cual es revelado aquí) y mi separación del otro.

Esta es la verdadera manera de certeza y satisfacción que es de Dios,
y que se mantendrá cuando todas las varias formas de invención de los hombres
fallen en lo que les prometen a los hombres y caigan ante los ojos de ellos.
Porque esta Semilla y nacimiento de Dios (y sólo estos)
deben ser aceptados y reinar en el día de Su poder.
Y ahora es el día de Su poder en unos, y pronto será el día de Su poder en otros.
Pues la oscuridad o la muerte no prevalecerá en su deseo
de llevar la vida del Hijo resucitado de nuevo a la tumba,
sino que Él cabalgará conquistando y para conquistar, sometiendo y para someter,
reinando y para reinar,
hasta que haya llevado todas las cosas bajo el dominio del poder del Padre.

=== La Manera de Conocer los Movimientos, Doctrinas y Enseñanzas del Espíritu de Cristo

[.discourse-part]
Pregunta: ¿Cómo puede un hombre discernir los movimientos,
doctrinas y enseñanzas del Espíritu de Cristo internamente, de los movimientos,
apariciones y operaciones engañosos del espíritu contrario?
Y con respecto a las doctrinas que otros enseñan,
¿cómo puede saber un hombre si están hablando a partir de
Cristo o si están hablando a partir de sí mismos?

[.discourse-part]
Respuesta: Esto es de gran importancia, sin ninguna duda.
El que es capaz de hacer una distinción tendrá que haber recibido primero algo de Dios.
Tendrá que haber nacido de la sabiduría que viene de lo alto.
Tendrá que haber recibido el espíritu de discernimiento proveniente de Dios.
Tendrá que haber recibido algo del oído de la oveja, el santo entendimiento,
por medio del cual pueda distinguir las cosas espirituales; entre lo puro y lo impuro,
entre el imitador de las cosas de Dios, y el que es en verdad de Dios.
Hay una balanza del santuario,
designada para pesar las cosas espirituales y las apariencias.
Sólo por medio de esta balanza son discernidas y distinguidas
verdadera y correctamente todas las cosas.
Esta balanza está en el santuario, en el lugar santo y celestial en Cristo Jesús,
donde el verdadero peso de las cosas espirituales es dado y discernido.
Pero aquel que pesa sin esta, el que pesa mediante su propio juicio y entendimiento,
por su propia comprensión e imaginación, pesa mediante lo que es incierto,
cambiante y falible.

¡Oh, si los hombres fueran humildes, tiernos,
mansos y conscientes de su incapacidad de juzgar a partir de sí mismos!
Entonces podrían ver la necesidad de este don de Dios, y esperar en Él hasta recibirlo,
siendo mientras tanto, como un niño destetado,
sin entrometerse en las cosas demasiado altas para ellos,
sino manteniéndose y permaneciendo humilde,
en temor y sujeción a eso que el Señor ya ha hecho manifiesto en ellos.
Pues, ¿existe un hombre a quien Dios, en Su tierna misericordia y bondad,
no le haya hecho ya algo manifiesto de Sí mismo?
¿Hay alguien que, mediante la luz del Espíritu de Dios en su consciencia,
no conozca algo malo que debe dejar de hacer y algo bueno que debe hacer?
Ahora bien, este es el camino de Dios y la obra en la que el hombre debe ser ejercitado:
Experimentar su mente reunida en Aquello que enseña esto y recibir poder
del Señor para dejar de hacer lo malo y aprender a hacer lo bueno.
Pues es así como el Espíritu del Señor les enseña y les demanda a los hombres, a saber,
internamente, en sus partes más recónditas,
vivificándolos y alentándolos secretamente en alguna medida,
y dándoles un sentido de su pecado,
muerte y separación de Él. Porque donde hay alguna
visión del pecado y alguna consciencia de su carga,
hay también algo de vida, algo de luz, algunos pequeños movimientos de la vida,
sin la cual esta consciencia no podría ser.

Noten ahora: ¿No están aquí las persuasiones del Padre?
¿No están aquí las enseñanzas del Padre, aunque en una pequeña medida, con todo,
verdaderas y vivas?
¿No es dado aquí un pequeño discernimiento entre lo precioso y lo vil,
entre lo que es de Dios y lo que es contra Él? Pues sí,
aquí está el don de discernimiento, aunque en una medida pobre, humilde, pequeña y débil.
El hombre que recibe esto recibe los inicios del don,
por medio del cual es capaz de discernir y distinguir acerca de las cosas espirituales,
hasta donde se extiendan la luz y la habilidad del don en él.

Esta es la obra del hombre (y en esto radica su seguridad), llegar a este lugar,
permanecer ahí y crecer ahí. No debe juzgar fuera de esto,
ni juzgar más allá de lo que esta luz juzga en él con respecto a las cosas de Dios.
Debe mantenerse dentro de los límites del juicio que tiene proveniente del Señor,
sin atender a los sutiles mecanismos del enemigo,
que posteriormente se esforzará en nublar su mente y engañarlo
con una falsa apariencia de razonamientos sabios y disputas,
de su propia cuenta o de otros hombres, para hacerlo creer lo contrario.
Así que, conservando el terreno que ha ganado, debe esperar más de esta luz,
más de esta vida y más de esta virtud,
a fin de que su alma crezca y se incremente en ello, su ojo se fortalezca y vea más allá,
su oído oiga más,
su corazón abrace más de las instrucciones y direcciones
del Espíritu del Señor hacia y en el camino del reino.

Por tanto, el hombre que desee encontrar y recibir de Dios el don de discernimiento,
deberá ocuparse de la manifestación de la luz de
Dios presente en su corazón proveniente de Su Espíritu.
Abrazarla,
estar de acuerdo con ella y tener cuidado de los razonamientos de la mente
contra las convicciones y demostraciones del Espíritu de Dios.
Deberá recibir el amor de la verdad, aún la más pequeña aparición de ella,
acerca de las cosas menos importantes y más insignificantes,
y rendirse fielmente al Señor allí sin murmuración,
discusión o consulta a carne y sangre.
El que es fiel a la luz del Espíritu (y al discernimiento
que viene por ella) en lo pequeño,
recibirá más y tendrá la luz y el discernimiento del Señor
incrementados en concordancia a lo que requiera su necesidad.
Pero el que permanece discutiendo y desea tener todo
su camino despejado antes de dar un paso en él,
está lejos de llegar a ser ese niño que el Padre puede enseñar.

Esta fue, en efecto, la respuesta que Cristo le dio a esto en los días de Su carne,
cuando hubo grandes disputas con respecto a Su doctrina,
sobre cómo saber si era o no de Dios.
¿Cómo resolvió Él esta pregunta?
Dijo: "`El que quiera hacer la voluntad de Dios, conocerá si la doctrina es de Dios,
o si yo hablo por mi propia cuenta`" (Juan 7:17).
¿Desean ustedes conocer la doctrina del Hijo?
¿Desean ustedes conocer si es en efecto la doctrina del Hijo,
la doctrina del que viene del Padre?
¡"`Sí,`" dirá con entusiasmo el corazón recto,
"`ojalá yo pudiera saber si lo que se levanta y se abre en mi corazón
es del Espíritu de Dios o de la raíz de engaño en mí!`" Entonces,
esta es la manera: Haga la voluntad del Padre.

[.discourse-part]
Objeción: ¿Hacer la voluntad del Padre?
Pero, ¿qué clase de respuesta es esta?
¡Toda la discusión es acerca de la voluntad del Padre! ¿Cómo puedo
hacer la voluntad del Padre (la que se supone que el Hijo debe
enseñarme) antes de primero conocer la doctrina del Hijo?

[.discourse-part]
Respuesta: Es cierto, la doctrina del Hijo es la voluntad del Padre,
y usted no puede hacer la voluntad del Padre excepto cuando reciba la doctrina del Hijo.
Pero tome nota: En su mente hay discusiones acerca de algo de la doctrina del Hijo,
si es Su doctrina o no.
Hay disputas dentro de usted referentes a los movimientos, obras y actividades internas,
cuyo origen usted desea conocer fervientemente.
Entonces, la cuestión aquí es cómo puede usted llegar a esto, es decir,
cómo puede llegar a cierto conocimiento satisfactorio de estas cosas.
La manera no es metiéndose en razonamientos y controversias
acerca de cosas de las que usted tiene dudas,
sino entrando a esa luz en la cual y por la cual estas cosas son manifestadas.
Esto es, obedeciendo al Padre en eso que Él ya ha hecho manifiesto,
pues en esa luz (para los que creen en ella) y en obediencia a ella (aunque sea
muy poca o la manifestación pequeña) el Padre revelará aun más. Él hará que el
corazón y la mente sean sensibles a lo que es de Él y a lo que es del enemigo,
hasta donde sea necesario que sepan en ese momento.
Pues un juicio sabio y absoluto de todas las cosas no es necesario para un bebé,
tan sólo suficiente sentido para conocer el pecho y recibir de
él la leche con la que debe ser alimentado para poder crecer.
Esto es suficiente en su presente estado.
Sin embargo, si en algún momento necesitara fuerza para resistir al enemigo,
el Señor la revelará en el corazón,
y la sacará de la boca de los bebés para el perfeccionamiento de Su alabanza.

Así que, piense y aprenda el camino,
usted que es de corazón sencillo y desea verdaderamente al Señor,
así como la pureza y poder de Su reino.
Tenga cuidado del camino equivocado; tenga cuidado del camino del hombre,
el que resulta de consultar su propia sabiduría y pesar
las cosas en la balanza de su propia razón y entendimiento.
En este camino el hombre puede pesar las escrituras que fueron escritas
en épocas anteriores y las apariciones de Dios en esta época,
y equivocarse en corazón,
mente y juicio en relación a ambas durante todos sus días. Pero el que
espera en el Señor en temor y obediencia a lo que ya está manifestado,
y no desea conocimiento de Dios en su propia voluntad, tiempo o manera,
sino en los del Señor (Quien conoce perfectamente
el estado de cada uno y lo que es adecuado para él),
conocerá en el tiempo del Señor sobre la doctrina en la que su corazón desea ser instruido.
Mientras tanto,
el Señor lo alimentará con la comida necesaria y lo vestirá con el vestido necesario.
Es más,
nada le faltará al que se inclina delante del Señor en lo que ya está manifestado,
ni al que espera más manifestaciones y apariciones
del Señor. Pero el cazador sagaz en busca de conocimiento,
el que se adelanta a la guía del Señor y va más allá de las guías y enseñanzas de Él,
este es del primer nacimiento, el cual está excluido del reino y sus misterios.
Este proviene del despreciado,
del que mataría al heredero con tal de que la herencia sea suya.
Sin embargo, la herencia está señalada y dada a otro, esto es,
a la naturaleza del Cordero, al Espíritu del Cordero, a la inocencia del Cordero,
al nacimiento de sabiduría celestial,
el nacimiento que es una cosa tonta y necia a los
ojos del hombre y para nada digno de la herencia.
Pero al Padre le place dar el reino y herencia de vida eterna a estos.

Déjenme hablar un poco más claramente, y acercar esto un poco más al corazón,
si me lo permiten.
Le ha complacido al Padre en este día de Su amor y poder,
reunir un pequeño rebaño fuera del mundo (y fuera de todas las
profesiones mundanas de adoración y religión) para Sí mismo.
Él ha reunido este rebaño por medio de algo pobre, pequeño y humilde en sus corazones,
ejercitándolos de este modo en caminos pobres,
insignificantes y despreciables para los ojos del mundo
y para todas las profesiones de la sabiduría del hombre.
Mediante esta pequeña y baja Semilla, y con respecto a ella,
el Señor les testifica a otros a través de aquellos que Él ha reunido.
Y dicho testimonio da evidencia de sí mismo a todo el que espera en Dios un oído para oír.

Ahora bien,
cuando nosotros les contemos a los hombres de la Semilla divina dada por Dios,
en la que su religión debe comenzar, de la que debe crecer y de la que ellos deben nacer,
muchos asentirán y serán atraídos hasta el punto
de esperar internamente por esta y en esta.
Sin embargo, cuando la Semilla comience a agitarse y a moverse en ellos,
con frecuencia es en tal forma, y teniendo que ver con tales cosas bajas,
insignificantes y despreciables a sus ojos,
que estarán muy propensos a despreciarla y a entrar en disputas contra ella,
y así perder la entrada.
En cambio, se llenan de dudas acerca del líder y Sus movimientos,
se confunden y se enredan en sus mentes y se detienen desde el mismo principio.
Así, aunque deseen mucho y esperen mucho,
todo se vuelve poco debido a que el enemigo ha poseído
sus mentes con algún artificio de su sutileza,
como si las cosas hechas manifiestas por la Semilla fueran pequeñas y de poca importancia.
Lo que les hace falta (piensan ellos), es una manifestación poderosa de la vida,
la luz clara, etc.,
y por eso sus mentes son tomadas con expectativas
de cosas grandes y deseos en pos de cosas sublimes,
y pasan por alto la manera por la que estas cosas tienen que ser experimentadas y obtenidas.

Porque el Señor en su infinita sabiduría,
escogió estas cosas despreciables por las cuales
ejercitar y guiar Su rebaño. Ahora amigos,
ustedes que desean vida de Dios,
¡tengan cuidado de no rechazar los principios de Su vida y la redención de sus
almas al despreciar y pasar por alto el día de las cosas pequeñas! ¿Por qué no
habría de elegir Dios guiarlos por el camino en el que Él ha conducido al resto
de Su rebaño? ¿Por qué no habría usted de llegar a negar también las costumbres
y vanidades de este mundo (y entrar a lo que es sencillo y llano) y permanecer
en la voluntad y vida de Dios fuera de estas cosas?
¿Acaso no son los caminos,
costumbres y vanidades de este mundo del espíritu del mundo y no del Padre?
¿No provienen de la parte corrupta?
¿No son de la parte corrupta?
¿No complacen la parte corrupta?
¿No deben ser dejadas atrás por el que se interna en la Semilla,
es uno con la Semilla y vive en la Semilla?
¿Por qué quedarse atascados en estas cosas?
¿Por qué discutir sobre estas cosas?
¡Oh, sientan las persuasiones del Padre, primero fuera del mundo,
primero fuera de lo que no es de Él, sino del mundo,
para que así pueda llevarlos más y más lejos hasta el reino y poder eternos,
el cual es un viaje de muchos días más allá del lugar donde están atascados ahora!

Así que piensen y recuerden lo siguiente:
En los días de Cristo y sus apóstoles Dios escogió lo necio y lo débil,
y las cosas que no eran,
para esconder la senda de la vida y los misterios de Su reino del ojo sabio y escrutador
del hombre en aquellos días. ¿Por qué no habría Él de escoger lo mismo hoy?
¿Por qué no habría Él de revelarles cosas a los niños y no a lo sabio de esta era y
generación? ¿Por qué no habría de ser para Su gloria que ahora también se diga:
"`¿Dónde está el sabio?
¿Dónde está el escriba (dónde está el erudito)?
¿Dónde está el disputador de este siglo?`"
¿Puede alguno de ellos descubrir o discernir lo que Dios les revela a Sus pequeños? ¡No,
no!
Ellos se han levantado demasiado alto, por encima de esta pequeña, baja, tierna,
mansa y sensible Semilla, en la fe de la cual y en obediencia a la cual,
las enseñanzas de Dios son recibidas y Su vida y poder experimentados.
Pero por causa de la riqueza, sabiduría y conocimiento ya ganados fuera de esta Semilla,
la entrada a la verdad pura y viva (la que limpia la mente y la mantiene limpia,
la vivifica y la mantiene viva) les parece excesivamente difícil.

Como la semilla del reino es pequeña (como un grano de mostaza),
la más pequeña de las semillas, ¿por qué no habría de ser su aparición también pequeña,
es decir, en cosas bajas, débiles y despreciables a los ojos y sabiduría del hombre?
Y sin embargo,
el poder de la cruz (que derriba y mata lo corruptible) y la resurrección
de la vida pueden ser experimentadas y sentidas en estas.
"`Porque lo insensato de Dios es más sabio que los hombres,
y lo débil de Dios es más fuerte que los hombres.`"
El Señor sabe lo que hace al guiar a Sus niños por esta
senda despreciable y mediante estos ejercicios despreciables,
lo cual todos los sabios, altos,
altivos y ambiciosos según la carne pueden fácilmente pasar por alto y menospreciar,
y ante lo cual difícilmente se inclinarán y se someterán.

Dios es el mismo que siempre fue;
sigue apareciendo según la manera de Su propia sabiduría y fuera de la del hombre.
El que vaya a participar de la sabiduría de Dios
tendrá que negar y mantenerse fuera de la propia.
Los toques, los llamados, las enseñanzas, bendiciones, amor, paz, gozo, dulzura, etc.,
del Señor son derramadas, sentidas y disfrutadas por el alma en la nueva creación,
en la nueva consciencia, en la negación y salida de lo viejo.
