== Capítulo XVI. Las Cartas de Isaac Penington / Escritas entre 1658 y 1671

[.letter-heading]
A Su Padre, Sir Isaac Pennington^
footnote:[El Padre de Isaac Penington (Sir Isaac Pennington, Padre.
1584-1661) fue un conocido político Inglés y puritano Congregacionalista,
establecido en la Cámara de los Comunes de 1640 a
1653 y Alcalde de Londres de 1642 a 1643.
Fue miembro del tribunal que condenó a Charles I de traición y lo ejecutó.
Después se convirtió en un prominente miembro del gobierno de Oliver Cromwell.
Con la Restauración de Charles II en 1660,
Pennington padre fue juzgado por alta traición y encarcelado en la Torre de Londres,
donde murió en espera de la ejecución, el 16 de diciembre de 1661.
(Isaac Penington Jr. eliminó una "`n`" de su nombre,
quizás para que no fuera confundido con su padre.)]

[.salutation]
¡Ah, querido Padre!

¿Por qué me causa tanto dolor y llanto ante el Señor con sus duras e injustas cargas?
¿Cuántas veces he declarado solemnemente,
que nunca hubo ningún deseo o intento en mí de arrastrarlo
a esta forma de profesión religiosa?
Todo lo que hay en mi alma es que tenga el verdadero conocimiento de Cristo,
que en verdad oiga Sus palabras y las haga,
que no establezca su propia imaginación o la de otros hombres,
ni invente razonamientos en lugar de los dichos de Cristo.

Ahora, yo no estoy por formas u opiniones, sino sólo por Cristo, la sustancia,
el poder vivo de Dios en el corazón. Sin embargo,
debido a que usted tropieza en estas cosas y por prejuicio rechaza
el testimonio vivo de Dios en cuanto a Cristo la Roca (al construir
sobre lo que ha imaginado en relación con el Salvador),
en amor y compasión a su alma, no puedo sino decirle algunas cosas.
Pues quién sabe si Dios, finalmente,
pueda darle arrepentimiento para el reconocimiento
de la verdad y para repudiar el camino del error.

Usted establece tres razones por las que no puede creer que este camino sea de Dios.

[.discourse-part]
1+++.+++ El camino de Dios es un camino de amor, paz y unidad.

[.discourse-part]
Respuesta:
Si usted tuviera ese ojo que puede ver las cosas de Dios y se aplicara a ver con él,
vería la paz, el amor y la unidad entre esta gente de la que otros hombres sólo hablan.
Sin embargo, si usted toma las cosas por el informe que dan los enemigos,
tanto de Dios como de ellos, de seguro oirá y creerá bastante mal.
Porque esta gente, los llamados Cuáqueros,
no tiene guerra contra nada sino injusticia y con injusticia no pueden tener paz,
ni siquiera en sus relaciones más queridas.
Ellos aman las almas de sus enemigos y no piensan que haya
dolor o peligro demasiado grande para la salvación de ellas.
Al ser perseguidos, bendicen; al ser injuriados, ruegan y oran por sus perseguidores.
Están unidos a todo lo que es de Dios,
pero no pueden estar en unidad con la simiente de la serpiente.
Ellos conocen la "`generación de víboras`" en esta época presente,
y pueden atestiguar contra ellos bajo sus varias capas pintadas,
tan libremente como Cristo y sus apóstoles lo hicieron contra los escribas y fariseos.
Porque el espíritu de los escribas y fariseos se encuentra ahora en el mundo,
al igual que el Espíritu de Cristo y sus apóstoles.
Estos no pueden dejar de luchar, cada uno con sus propias armas.
Uno con sus cepos, azotes, multas, prisiones, etc.,
y el otro con la armadura espiritual de Cristo.
Así, uno lucha contra carne y sangre, lucha contra la criatura e hiere el cuerpo;
el otro ama a la criatura,
busca su salvación y sólo combate contra el poder
de las tinieblas que gobierna a la criatura.
Ahora, ¿cuáles de estos son los ministros de Cristo?
¿Los que incitan al juez a afligir el cuerpo,
o los que usan la espada del Espíritu para que la
tristeza que es según Dios produzca arrepentimiento?

Esta paz, amor y unidad se alcanzan, no por sus propios esfuerzos,
sino al recibirlos de arriba.
En efecto, toda nuestra religión radica en recibir un don, sin el cual no somos nada,
no podemos hacer nada y en el que nada es demasiado difícil para nosotros.
Sí, manteniéndonos en ese don de Dios podemos hacer todas las cosas,
podemos creer todas las cosas, podemos sufrir todas las cosas.
Nunca hubo una generación más débil en sí misma, más necia,
más ridícula para la sabiduría carnal,
ni más expuesta a los sufrimientos provenientes del mundo y de los profesantes mundanos.
Sin embargo, al mantenernos fieles al que nos ha llamado,
a veces sentimos la fuerza y la sabiduría,
tal como los más celosos en los caminos de la religión
mundana no tienen oído para oír el relato.

[.discourse-part]
2+++.+++ El camino de Dios es un camino de humildad.

[.discourse-part]
Respuesta: Si ellos no hubieran sido quebrantados y humillados por Dios,
nunca habrían entrado en este camino,
el cual es un camino que aborrece la arrogancia y la parte carnal del hombre.
Esta no es una humildad voluntaria,
sino una humildad que se opone y rompe la voluntad del hombre constantemente.
Usted juzga a distancia y con lo que no debe juzgar, sino con lo que debe ser juzgado.

[.discourse-part]
3+++.+++ Dios es un Dios de orden, no de confusión.

[.discourse-part]
Respuesta: ¡Bendito sea el Señor,
que ha recuperado parte del orden de la iglesia verdadera a favor
de nosotros y nos ha librado de la confusión del anticristo!
Nosotros experimentamos un orden en la luz, un orden en el Espíritu,
un orden en Cristo la verdad, pero eso que el hombre llama orden en su sabiduría,
no es más que el orden del anticristo, el cual es confusión para Dios.
Tener el espíritu del hombre hablando y el Espíritu de Dios obstaculizado
es el orden anticristiano de todas las congregaciones e iglesias.
Tener el espíritu del hombre detenido y el Espíritu de Dios hablando,
es el orden de la iglesia de Cristo.
Conocemos este orden y nos regocijamos al descubrir que se levanta
en nosotros eso que nos enseña a "`dejar del hombre,`" de modo
que la voz del hombre no es "`estimada`" en nada.
(Isa.
2:22) Pero la voz del Dios vivo es oída, conocida,
amada y obedecida por aquello que Él ha vivificado en nosotros y ha hecho vivir para Él.

La última parte de su carta consiste en acusaciones muy duras e injustas,
mezcladas con amargas expresiones que pasaré por alto.
Sólo confieso que es un poco difícil para una parte de mí,
que mi propio padre deba tratar conmigo así.

Acerca de no encontrar consuelo en mí y desearme un mayor consuelo en mi hijo,
debo decir lo siguiente.
Hay una parte en mí que Dios ha golpeado y está destruyendo,
y yo mismo no tengo consuelo aquí,
ni esta es muy capaz de dar consuelo a nadie más.
Si yo estuviera en alguna manera formal de religión,
podría ser un consuelo para mi padre (pues usted podría estar satisfecho con eso,
o al menos soportarlo).
Sin embargo,
debido a que el Señor se ha apoderado de mi corazón por el poder de Su Verdad
y no puedo inclinarme más que ante Él (ni siquiera ante mi más querido padre),
ahora no soy un consuelo.
Estoy seguro que en todos mis días he tenido poco
consuelo al ver el rumbo de la religión de mi padre,
del que siempre podría dar testimonio que no era de Dios (sí,
mi querida y difunta madre solía lamentarlo conmigo).
Muchas veces he derramado mi alma delante del Señor. ¡Oiga mis palabras, padre,
oiga mis palabras! ¡Penetre en la naturaleza de las cosas! ¡No ponga sombras
en lugar de la verdad! ¡Espere el don! ¡Reciba el verdadero amor,
la verdadera paz, la verdadera unidad,
la verdadera humildad (la cual no reside en la voluntad de la criatura,
todo lo contrario,
la destruye) y pronto nos conoceremos y tendremos consuelo verdadero uno en el otro!

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 14, del mes 12, de 1658

[.letter-heading]
A Thomas Ellwood

[.salutation]
¡Querido Thomas!

Grande ha sido la bondad del Señor para contigo al sacarte de ese
camino de vanidad y de muerte (en el que corrías hacia la destrucción),
para darte un nombre vivo y una herencia de vida entre Su pueblo,
lo que sin duda será el fin de tu fe en Él y obediencia
a Él. No dejes que sea cosa ligera a tus ojos,
que Él te valore digno de padecer entre sus corderos escogidos,
para hacer tu corona más pesada y tu herencia más completa.
¡Ojalá que ese ojo y ese corazón se mantenga abierto en ti,
el que conoce el valor de estas cosas! ¡Ojalá que te mantengas cerca de
la experiencia de la vida y seas puro en tu espíritu en medio de tus sufrimientos,
para que puedas cosechar el beneficio de ellos!
Este es un breve saludo de mi amor por ti,
que desea tu fuerza y establecimiento en el poder de Dios,
y el absoluto debilitamiento de ti, como ti mismo.
Mi estima es para ti, con aprecio a Thomas Goodyare y al resto de los Amigos^
footnote:[Cada vez que la palabra "`Amigos`" se escribe con mayúscula en estas cartas,
Penington se refiere a los miembros de la Sociedad de los Amigos (Cuáqueros).]
prisioneros.

Permanezco tuyo en la Verdad, en la que el Señor mi Dios me preserve solo y fiel.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Desde la cárcel de Aylesbury, día 14, del mes 12, 1660

[.letter-heading]
A un Padre Desconocido

[.salutation]
Querido amigo,

No tengo mucha libertad de escribir en la actualidad,
al estar retirado en espíritu y llorando a mi Dios para que la
poderosa manifestación de Su vida pura sea cada vez más perfecta,
tanto en mí como en otros.
Sin embargo, el espíritu de su carta me atrae con tanta fuerza,
que no puedo quedarme en silencio total.
Por tanto, en la rectitud, temor y ternura de mi corazón le respondo.

Hay una Semilla pura de vida en el corazón de donde brota todo lo bueno.
A esta debe prestarle atención en usted mismo.
También debe esperar en el Señor para ser enseñado y habilitado
por Él para alcanzar esa Semilla en sus hijos.
De esta manera usted puede ser un instrumento en las manos
del Señor para llevarlos a ese temor de Él,
que es aceptable tanto para Él como beneficioso para ellos.
Por lo tanto,
esté atento a Su guía en su corazón y espere estar familiarizado con Su voz allí. Así,
cuando sus hijos le hagan preguntas de esta naturaleza: Qué es Dios, o dónde habita,
o si Él puede verlos en la oscuridad, no las rechace; no,
espere sentir algo de Dios levantado en usted capaz de juzgar
si la pregunta es planteada en sensibilidad o en vanidad.
Esto puede darle la ventaja de despertar el bien y alcanzar lo que debe ser levantado,
tanto en jóvenes como en adultos, para vivir para alabanza de Aquel que lo levanta.
Tenga cuidado de un juicio según la carne,
más bien espere sentir la Semilla levantada en usted
que juzga con juicio justo en cada caso particular.
Esté quieto y en silencio,
excepto cuando sepa claramente que la Semilla (y no usted) está juzgando.

En cuanto a sus hijos,
sienta diariamente la necesidad de instrucción proveniente
del Todopoderoso para gobernarlos y dirigirlos,
y espere cada día recibirla de Él. Lo que reciba de Él delo con temor,
esperando a que Él lo obre en sus corazones.
Porque Él es un Padre,
y tiene ternura y da verdadera sabiduría para cada
condición de Su pueblo que espera en Él.

Tal vez usted espera de mí una regla externa,
pero no tengo ninguna regla excepto la vida interior.
Esta vida no se conoce mediante el conocimiento externo,
sino que es dada a conocer todos los días como a mi Padre le agrada.
No puedo dirigirlo a ninguna otra regla,
salvo esperar que esa vida sea revelada en usted cada día,
de acuerdo con su necesidad diaria en cada situación.
Lo siguiente se lo digo en el amor de mi corazón:
¡Espere, sí,
espere el verdadero discernimiento que es dado a la verdadera Semilla
(que usted experimentará conforme es levantada y gana dominio),
para que lo equivocado no juzgue en usted al tener
una apariencia externa de sabiduría y razón.

Respire anhelantemente delante del Señor para que su corazón sea puro y su juicio
establecido directamente por la Semilla de vida dentro de usted,
y para que sus hijos sean guiados y criados también en la consciencia de la misma Semilla.
En cuanto a la oración, ellos no necesitarán que les sea enseñada externamente.
Si un verdadero sentido de la Semilla es encendido en ellos (aún tan jóvenes),
de ese sentido surgirán respiraciones anhelantes por el que lo engendró,
apropiadas a su estado actual.
Esto hará que ese sentido y vida en ellos crezca y se incremente.

Así, en la sencillez de mi corazón le he contestado,
de acuerdo al impulso y libertad que encontré allí y que no me atrevo a exceder.
Yo, su amigo sincero, aunque exteriormente desconocido.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 20, del mes 3, de 1665

[.letter-heading]
Para Aquel que le Envió un Documento de Richard Baxter

[.salutation]
Querido amigo,

A quien a menudo recuerdo con amor y corazón suave, deseando en Dios,
que disfrute de Su presencia y vida pura en este mundo,
la que Él juzgue conveniente para usted, y que después de esta vida,
su alma se siente en descanso y paz con Él para siempre.

He recibido de usted un documento de Richard Baxter, que me envió, creo, en amor,
y en amor estoy obligado a regresarle mi sentido del mismo.
Me parece muy útil e importante hasta donde llega, pero tiene un gran defecto,
que no dirige a los pecadores a esa Semilla de vida y poder,
en la que y a través de la cual pueden hacer lo que él les exhorte a hacer.
Porque, ¿cómo pueden llegar ellos a una verdadera conciencia o arrepentimiento,
o a unirse en pacto con Dios a través de Cristo,
hasta que conozcan y reciban algo de Dios en donde esto pueda ser hecho?
Oh, querido amigo mío, deseo que él,
usted y todos los que en alguna medida se vuelvan de este mundo y deseen la vida eterna,
puedan conocer la instrucción de la vida,
y sentir ese don de Dios en el cual Él es conocido, amado y unido en pacto.
De esta manera usted puede experimentar un comienzo puro,
un crecimiento puro y continuar hacia la perfección,
y no tener meras nociones concernientes a cosas establecidas en el entendimiento terrenal,
las cuales fácilmente se pudren y se contaminan.

Cualquier cosa que los hombres puedan decir o pensar de mí,
no tengo ninguna otra religión ahora que no haya tenido desde el principio,
sólo que ahora tengo más clara dirección y guía de esa Semilla de vida,
en y por la cual le plació al Señor darme vida entonces.
Y sé (y experimento diariamente en mi corazón) que esta es, ni más ni menos,
que la luz del día eterno en el cual el hombre renovado debe caminar, y ni más ni menos,
que la vida del Hijo (a quien Dios dio en rescate por los pecadores),
que puede vivificar al hombre para que lo haga.
Y sólo Cristo, por Su vida revelada en el alma y Su sangre derramada allí para lavarla,
puede salvar al pobre pecador del pecado, de la ira y de la miseria.
Mi esperanza no está en lo que he hecho, hago o pueda hacer,
sino en lo que Él ha hecho sin mí y hace también en mí.

Esto describe mi amor hacia usted,
sacado a la luz en este momento por la expresión externa del suyo al enviar ese documento;
quien sigue siendo (desde mi primer contacto) y ha sido siempre un amigo y devoto suyo.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Chalfonte de Pedro, día 19, del mes 6, de 1665

[.letter-heading]
Para Su Esposa

[.signed-section-context-open.centered]
(Escrita por motivo de su cuarto encarcelamiento)

[.salutation]
Mi querido amor verdadero,

Apenas tengo libertad para darme cuenta de lo que ha sucedido,
incluso en mis propios pensamientos; sin embargo,
estoy satisfecho en mi propio corazón que el Señor, quien es bueno,
ha ordenado las cosas de esta manera y que hará lo que le plazca.
¿Por qué debería murmurar o encontrar falla el razonamiento carnalmente sabio?

¡Oh,
guarde silencio delante del Señor toda carne en mi interior! ¡No moleste a mi
alma mientras espera en mi Dios saber qué está obrando en mí y por mí,
y a qué puedan conducir estos crueles sucesos!

Una cosa he deseado del Señor, que yo sea Suyo,
perfectamente administrado por Él para que no conozca nada sino a Él,
y que no disfrute de nada aparte de Su vida y dirección. Por tanto,
debo renunciar y ser separado incluso de ti, mi más querido y noble amor,
o no podré ser feliz en mi propia alma o disfrutar de ti como deseo.

Encuentro mi corazón profundamente deseoso y respirando anhelantemente
tras el poder puro del Señor para que reine en mí. Sin embargo,
no me atrevo a elegir por mí mismo,
sino que ruego ser enseñado a esperar y a estar dispuesto
a beber lo que falta de la copa de sufrimiento,
tanto interna como externamente, hasta que el Señor tenga a bien quitarla de mis labios.

Oh, querida, di poco sobre mí. No abogues mi causa,
sino mantente quieta en tu propio espíritu y espera
lo que el Señor vaya a hacer por mí. Así,
todas mis oraciones, las cuales en la ternura de mi alma he levantado a menudo por ti,
tendrán su pleno efecto en ti.
Mi amada, sé mi verdadera compañera de yugo,
útil para atraer mi corazón hacia el Señor y alejarlo de todo excepto
de lo que es santificado por la presencia y guía de Su vida.

[.signed-section-closing]
Siento y sabes que soy, muy cariñosamente tuyo.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 1, del mes 7, de 1665

[.letter-heading]
A un Amigo en Londres

[.signed-section-context-open.centered]
(Escrito en ocasión de la plaga, 1665)

[.salutation]
¡Oh amigo!

Temible es el Señor, esto es conocido y sentido ahora más allá de lo que pueda ser dicho.
¿Teme su corazón delante de Él? ¿Está dispuesto a sujetarse
a Él? ¿Anhela Su fortaleza con el fin de confiar en Él,
usted y su familia?
¡Oh, que pueda ser ayudado diariamente para clamar ante Él! ¡Que Él,
quien es tierno y capaz de preservar,
tenga misericordia de usted cuando Sus flechas vuelen alrededor!

Retírese, retírese interiormente y espere sentir Su vida,
para que su alma se encuentre fuera de los razonamientos y pensamientos de su mente,
pero dentro de aquello que los fija en un lugar más profundo.
Aquí el Señor se conoce y se adora, en aquello que es de Él, engendrado por Él,
formado por Él, preservado por él, cerrado y abierto por Él a Su placer.
Así,
viviendo en la experiencia y en el puro temor del Señor (no entrometiéndose
a juzgar a otros o justificándose a sí mismo,
sino a la espera de la aparición de Él en usted,
quien es el justificador y la justificación),
usted será habilitado por el Señor en Su tiempo para
conducir a sus hijos y familia en la misma experiencia,
de modo que todos juntos, usted y ellos, disfruten la misma preservación que viene de Él.

Y si su corazón es recto delante del Señor y su alma
está despierta y guardada en Su temor,
encontrará algo de donde salir, y algo donde entrar, y al Señor atrayéndolo y guiándolo.
Y este golpe tan terrible para otros, y no completamente sin temor para usted,
resultará de gran ventaja en su favor,
al atraerlo más hacia un sentido y conocimiento del Único infinito,
y sacarlo de sus pensamientos y conocimiento terrenales, los cuales no ayudarán ahora.

[.signed-section-closing]
Su amigo,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 8, del mes 7, de 1665

[.letter-heading]
A Elizabeth Walmsley

[.salutation]
Querida amiga,

Mi corazón se derritió sobremanera dentro de mí al leer tus preciosas y tiernas líneas.
En verdad estaba muy abrumado, y varias veces me incliné a interrumpir la lectura,
porque la frescura y la fuerza de la vida en tus palabras
fluyeron sobre mí. Y dije una y otra vez en mi corazón:
'`es la voz misma de una hija de mi Padre,`' cuyo sonido
alcanzó y refrescó profundamente mi alma.
Y mi corazón dice esto: "`Bendito sea mi Dios por sus tiernas misericordias hacia ti,
en visitarte, guiarte y preservarte hasta este día,
y por enseñar a Su Semilla a hablar así en ti.`"
¡Oh deja que Su alabanza viva y abunde en tu pecho para siempre!
Y en el fluir y manar de esta vida,
acuérdate de mí en el trono de la misericordia de mi Padre,
por la que vivo y tengo mi única esperanza ante Él.

¡Qué la misericordia,
bendición y la presencia pura de mi Dios llenen tu
alma y descansen sobre ti para siempre! ¡Amén!

Recuérdale mi amor a tu hermana, cuyo bienestar interior y prosperidad deseo, es decir,
que ella pueda ser una contigo en la Semilla y Vida de Dios.

Soy tu Amigo no fingido y querido amante de la Semilla pura de vida en ti.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Cárcel de Aylesbury, día 19, del mes 8, de 1665

[.letter-heading]
A Sus Amigos en Horton e Inmediaciones

[.salutation]
Mis Amigos,

Ha habido un día nublado y oscuro,
en el que la iglesia y edificio de Dios ha sido devastado,
y Su santa ciudad (de acuerdo con Su decreto y propósito)
hollada bajo el pie de los gentiles.
Todo este tiempo Su iglesia ha sido como una viuda desolada, llorando en el desierto.
A pesar de todo, Dios no ha dejado a Su pueblo durante esta época,
porque siempre ha habido respiraciones anhelantes
y movimientos de vida en y desde la Semilla preciosa.
Sin embargo, aunque había verdaderos deseos y anhelos en pos de la verdadera iglesia,
en medio de estos deseos el enemigo atacó,
y animó a hombres a ir más allá de donde habían sido verdaderamente guiados.
Así, leyendo en las Escrituras acerca de un estado de iglesia, mandatos de iglesia, etc.,
pensaron que era su deber seguir edificando.
De este modo,
se han metido en muchas cosas en las cuales no han sido aceptados por el Señor (aunque,
en sus respiraciones y deseos verdaderos, fueron aceptados).
Y, ¿cuál ha sido el resultado de lo edificado por el hombre?
¡Oh, la Semilla pura ha sido sepultada en ellos,
y ellos han sido como un sepulcro para Ella, y sus propias imaginaciones,
conocimiento carnal y forma de adoración son de gran estima!

¡Oh Señor mi Dios,
te suplico que levantes de nuevo la vida pura y aquellas
respiraciones anhelantes y puras que han sido ahogadas,
perdidas y enterradas en estas construcciones!

Ahora, queridos amigos, solo el Señor edificó Su iglesia al principio.
Él también arrasó lo edificado y llevó Su templo vivo fuera del caparazón a un desierto;
y solo el Señor puede sacar del desierto a Su iglesia otra vez (apoyándose en su Amado),
en su estado edificado.
Ah, queridos amigos, todo debe ser disperso, todas las reuniones,
todo lo edificado que no es del Señor debe ser disperso, para que Su reunión,
Su edificio sea conocido y exaltado en la tierra.
Así pues, deseo que no retengan nada en este día del Señor (pues es así, de hecho),
contra la luz y el poder del Señor. El Señor puede, y mantendrá Su obra,
por débil y de poca estima que sea ante el ojo del hombre,
pero el hombre no podrá mantener sus obras,
por altas y fuertes que sean ante sus propios ojos.

Y ya que mi espíritu está en este momento inesperadamente
abierto en amor y en vida hacia ustedes,
voy a mencionar una o dos grandes trampas en las que veo a los profesantes enredados,
para que ustedes puedan esperar en el Señor y escapar del mal y del peligro de ellas.

Primera: Ellos ven demasiado el tiempo externo y las cosas externas,
y sus expectativas son en demasía, de este modo.
¡Oh, no permitan que esto sea así en ustedes, sino esperen el día interior,
donde las cosas de Dios son forjadas en el corazón.

¡Ay del que haya tropezado en la aparición viva de
la preciosa verdad de Dios en este nuestro día,
y en su propia sabiduría haya exaltado lo que él debería haber dejado caer! ¡Oh,
que ninguno de ustedes (a quienes he amado cariñosamente y todavía amo,
y a quienes he buscado verdaderamente en el Señor y aún busco) jamás muestren
semejantes ejemplos y tristes espectáculos de lo que ahora escribo en un sentido
vivo! ¡Que esa Semilla que ha llorado y es oprimida entre ustedes pueda vivir,
y se levante en el poder de la vida sobre lo que la ha afligido y oprimido!
Porque en verdad siento entre ustedes una sabiduría
y un conocimiento que no es de la Semilla,
que más bien la oprimen.
¡Oh,
qué atrevimiento de palabra me da el Señor para ustedes!
¡En verdad estoy deshecho de preocupación por ustedes!
Y en la fuerza de ese amor que busca en sus pechos,
deseo que la cosa abominable entre ustedes pueda ser descubierta y purgada,
de manera que lo que es en verdad de Dios brote, viva y florezca en medio de ustedes.

Segunda:
En lo que los profesantes se equivocan gravemente
tiene que ver con orar en el nombre de Cristo,
en cuyo Nombre el que pide recibe,
y fuera de ese Nombre no existe el derecho de pedirle al Padre.
Ellos piensan que orar en el nombre de Cristo consiste
en el uso de algunas palabras externas,
tales como: "`Haz esto por amor de Tu Hijo;`" o "`Te suplicamos en el nombre de Cristo.`"
¡Pero hay muchos que no conocen al Padre y aún así utilizan tales palabras!
Y hay otros que son enseñados por el Padre a orar,
oran en el Hijo y no son guiados a usar tales palabras.
El Nombre en el que está la petición y la aceptación es vivo,
y el que ora en el mover del Espíritu y en el poder y virtud de la vida del Hijo,
ora en el Nombre.
Sólo esta voz es reconocida por el Padre, no la otra,
que ha aprendido en su propia voluntad,
tiempo y espíritu a usar las palabras relacionadas con el Hijo.

¡Ah amigos,
ojalá ustedes puedan viajar hacia la verdad y encontrarse
con la sustancia infalible de las cosas,
para que vivan y no mueran!
Entonces verán cuánto se ha equivocado el hombre y sigue equivocándose, sí, es decir,
el hombre en ustedes.
Y verán que sólo esa Semilla y los que han nacido de Ella,
conocen la verdad viva y caminan en la senda viva, donde no hay error ni engaño,
sino una perfecta preservación de ellos.
Allí, en la Semilla, deseo conocerlos y abrazarlos,
donde podemos unirnos y conocernos unos a otros, en el nacimiento y vida espirituales,
inseparablemente para siempre.

Sigo siendo su amigo encarcelado,
según la sabiduría de Dios y en Su complacencia pura y temor,
aunque la sabiduría del hombre podría haber evitado fácilmente estos lazos.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Cárcel de Aylesbury, día 22, del mes 8, de 1665

[.letter-heading]
Para los Amigos de la Verdad En y Cerca de los Dos Chalfonts

[.salutation]
Queridos amigos.

Estoy separado de ustedes en cuanto a la presencia corporal,
pero no puedo olvidarlos porque están escritos en mi corazón,
y no puedo sino solo desear su paz y bienestar como para mi propia alma.

Y este es mi presente clamor por ustedes: ¡Qué puedan experimentar el aliento de vida,
esa vida que en un primer momento los vivificó y que todavía vivifica!
Este aliento de vida tiene poder sobre la muerte y al ser sentido por ustedes,
doblegará la muerte en ustedes y sentirán la Semilla
levantando Su cabeza sobre lo que la oprime.
¿Por qué debería ser el nacimiento real un cautivo en alguno de ustedes?
¿Por qué debería cualquiera de ustedes estar de parto y no dar a luz?
¿Por qué el pecado debería tener dominio en alguno de ustedes,
en lugar de que la gracia reine en su vida y poder en todos?
¡Oh,
si pudieran ser vivificados! ¡Si pudieran recibir
ayuda! ¡Si fueran llevados a la verdadera sumisión,
la que engendra el verdadero dominio!
De hecho, clamo por mi propia alma y por las de ustedes también,
que en una virtud y poder de la vida,
podamos ser entretejidos y servirle al Señor nuestro Dios en perfecta unidad de espíritu.

¡Padre, sopla sobre la carne en todos nosotros, sécala en las raíces,
permite que todo lo nacido de ella muera en nosotros y que su vientre llegue a ser estéril,
para que ya no lleve más fruto para muerte e injusticia.
Permite que Tu Semilla pura viva en nosotros y que el vientre que
ha pasado demasiado tiempo estéril abunde en fruto para Ti,
para que pueda ser una viña de tu propio plantío, riego y abono,
produciendo frutos santos, puros y agradables a Tu paladar! ¡Padre,
que nunca te arrepientas del amor, del favor y de la misericordia que nos has mostrado,
al reunirnos fuera del mundo y de en medio de muchas formas de profesión!

Mis amigos, ¿qué les diré? ¡Que el Señor los mantenga vivos y conscientes,
caminen y vivan con Él,
tanto en privado como en sus asambleas! ¡Sean serios en sus espíritus para que
puedan sentir el peso de Su Semilla brotando en ustedes y descansando sobre ustedes,
para balancear sus corazones hacia Él! ¡Dejen que los pensamientos,
deseos y preocupaciones terrenales que comen como una gangrena,
se mantengan afuera por el poder de esa vida que tienen,
en la medida que permanecen en pacto con Aquel que los ha reunido
mediante Su luz pura que brilla dentro de ustedes! ¡Oh,
si todos moraran allí y no retrocedieran hacia la naturaleza terrenal,
donde el enemigo está al acecho para enredar y atrapar
sus mentes y llevarlos a una pérdida!

Sientan mi corazón de amor y tierno cuidado por ustedes en la vivificante vida de Dios.
Que el Señor Dios los guarde para bien y perfeccione Su obra en ustedes,
que atraiga sus corazones más y más cerca de Él hasta que sean tragados por Él,
y encuentren sus corazones aptos y bienvenidos en el seno de su Amado.
Ahí podrán sentarse en el descanso y gozar de Su plenitud para siempre.
Este es el bendito fin del amor del Señor para con ustedes
y de todos los esfuerzos fieles que han sido por ustedes.

Cuando ustedes estaban sentados juntos y esperando en el Señor,
estas cosas brotaron en mi corazón hacia ustedes.
Y si ustedes prueban alguna dulzura o frescura en ellas, inclínense ante la Fuente,
y sean conscientes de Sus alabanzas brotando en medio de ustedes.
Su amigo y hermano en la Verdad,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Desde mi lugar de confinamiento en Aylesbury

[.signed-section-context-close]
Día 20, del mes 4, de 1666

[.letter-heading]
Para el Conde de Bridgewater^
footnote:[El Conde de Bridgewater fue el hombre principalmente
responsable de varios de los largos encarcelamientos de Isaac Penington.
Debido a que Penington no se inclinó ante él,
ni se dirigió a él como "`Mi Señor,`" ni se refirió a sí mismo como "`su
humilde servidor,`" el Conde de Bridgewater adquirió órdenes militares
para tener a Penington detenido y encarcelado en varias ocasiones.
En total, Isaac Penington pasó cerca de cinco años en la cárcel,
por lo general en Aylesbury, aunque una vez en Reading.]^

[.salutation]
Amigo,

Es el deseo de mi corazón caminar con Dios en el verdadero temor de Su Nombre,
y en amor verdadero y buena voluntad para con todos
los hombres todos mis días aquí en la tierra.
Con este fin espero en Dios día y noche,
para conocer Su voluntad y recibir de Él instrucción incuestionable
respecto a lo que es aceptable delante de Sus ojos.
Después de que Él haya manifestado Su placer en alguna cosa,
espero en Él fuerza para llevarla a cabo, y cuando la ha forjado en mí,
mi alma lo bendice por ello.
Si este es un camino correcto, no debo ser condenado en este, pero si no lo es,
y usted conoce un camino mejor, muéstremelo en amor, mansedumbre y ternura,
tal como yo estaría dispuesto a hacerle saber, por su bien,
lo que el Señor me ha mostrado.
Sin embargo, estoy plenamente convencido de que Dios es más alto que el hombre,
y que Su voluntad y Sus leyes deben ser establecidas y obedecidas en primer lugar,
y las del hombre solo en segundo lugar,
y en debida subordinación a la voluntad y leyes de Dios.

Ahora amigo,
dedíquese a hacer lo que es correcto y noble y a lo que
es realmente justificable ante los ojos de Dios,
para que pueda rendirle una cuenta aceptable cuando Él lo llame.
Lo que usted me ha hecho no me ha hecho su enemigo, más bien,
en medio de ello deseo su bienestar y que en su posición
y acciones se conduzca de manera tal,
que no provoque a Dios en contra suya en este mundo, ni en el mundo venidero.

¿No me ha afligido lo suficiente sin causa?
¿Quiere que me incline ante usted aun cuando el Señor
no me haya dado la libertad de hacerlo?
Si yo le diera títulos y honores externos, ¿no le haría más mal que bien?
¡Desista y sea pobre en espíritu delante del Señor!
¡Hónrelo en su corazón y en sus caminos,
y espere la verdadera nobleza y honor que son de Él! Tiene poco
tiempo para estar aquí en el mundo y luego comienza la eternidad.
Lo que ha sembrado aquí, debe cosecharlo entonces.
¡Siembre, no para su propia voluntad ni sabiduría, sino para el Espíritu de Dios,
y conozca la guía de Aquel que es el único capaz de conducir al hombre correctamente!
En realidad,
debería estar sujeto en su propio corazón a esa Semilla que le ha ofendido en otros,
esa que da testimonio de Dios y está en contra de los pensamientos,
los caminos y las obras del hombre corrupto.
¡Ojalá pueda sentir la Semilla de vida de Dios y conocer el buen fruto producido por
ella! ¡Ojalá que la naturaleza maligna con su obra maligna sean cortadas en usted,
para que su alma pueda escapar de la ira y de la miseria
que acompañan las obras y a los que hacen iniquidad!

Le he enviado en amor el folleto adjunto.
Léalo con temor y humildad, alzando su corazón al Señor que da entendimiento,
para que sea una bendición para usted,
porque fue escrito en el amor verdadero y es de una naturaleza sanadora y guiadora.
Le he escrito anteriormente,
pero mi camino ha sido tan restringido que no he encontrado fácil acceso a usted,
y cómo o si esto llegará a su mano no lo sé. Pero esto sinceramente le digo:
He sentido la naturaleza del Cordero bajo mis sufrimientos por su causa,
para los cuales no le he dado ninguna razón,
ni para que comenzaran ni para que continúen. Y si puede
llevar esto al tribunal del Testigo de Dios en su corazón,
entonces este tratará fielmente con usted,
culpando lo que Dios culpa y justificando lo que Él justifica.
Y aunque el Señor mira y defenderá la causa de Sus inocentes, aún así no deseo que sufra,
ni por parte de Dios, ni por parte del hombre, ni por mi causa.
Más bien, deseo que pueda ser guiado y preservado en aquello que será descanso dulce,
paz y seguridad para todos los que están protegidos por ello.

Esta es la suma de lo que tengo que decir por ahora,
quien ha escrito esto con el único fin de que (en los movimientos del verdadero amor
hacia usted) experimente el poder de Dios formándose en su corazón como debe ser,
y produciendo los frutos de justicia en usted.
Mi deseo es que Él lo haga parte de la simiente de los benditos,
que herede la bendición y que encuentre la naturaleza
terrenal consumida y llevada a nada en usted.
Pues la maldición pertenece a la naturaleza terrenal y esta debe sentir la maldición,
en la medida que Dios traiga sus juicios justos a
los corazones y a las cabezas de los transgresores.
Y sabiendo que hay un Día en el que Dios hace que los transgresores rindan cuentas,
le advierto con ternura que considere sus caminos y haga las paces con Él,
para que no sea irremediablemente y eternamente miserable,
sino que sea transformado por Su vida y naturaleza.

Y amigo, sepa esto con certeza:
La religión aceptable para Dios no es la hecha o
la elegida por el hombre (ni por el Papa,
ni por cualquier otro hombre), sino solo la que es de Él. Ahora,
¿qué será de ese hombre cuya religión y culto son repugnantes para Dios?
¿Dónde estará él, o qué explicación será capaz de dar cuando comparezca ante Dios?

No es frecuente que usted reciba un trato tan honesto como este.
Estas cosas tienen mucho que ver con usted; espere en Dios Su luz verdadera,
para que no sea engañado sobre ellas, pues de ese modo,
su pérdida sería grande e irreparable.

Soy su amigo en estas cosas y le he escrito con amor
verdadero y deseoso del bienestar de su alma.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Desde la cárcel Aylesbury, día 24, del mes 6, de 1666

[.letter-heading]
Para Elizabeth Walmsley, Giles de Chalfont

[.salutation]
Querida amiga,

Mis pensamientos de ti me agradan.
De hecho, estoy conmovido con el sentido del amor del Señor hacia ti,
como para mi propia alma.

¿Qué éramos para que el Señor extendiera su brazo hacia nosotros y nos recogiera?
Y,
¿qué somos para que el Señor diariamente nos recuerde
en el fluir de Sus amorosas bondades y misericordias?
¡Oh, Su piedad, Su compasión! ¿No eres capaz de decir lo mismo también? Estimada amiga,
mi deseo es que el poder y las bendiciones de la vida desciendan
sobre ti y que sientas a tu Dios cerca,
que tu corazón esté presto a dejarlo entrar,
y cerrado contra todo lo que es de una naturaleza contraria a la Suya.
¡Oh, que conozcas esa muerte pasando sobre ti y perfeccionada en ti,
la cual prepara para y deja entrar la plenitud de Su vida pura y sin mancha!

Te encomiendo mi amor para tu hermana y para todos los Amigos cuando tengas la oportunidad,
quienes respiran con gran anhelo tras el Señor y desean caminar en rectitud
de corazón con Él. Soy tu amigo en el afecto que es de la Verdad.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Aylesbury, día 20, del mes 4, de 1666

[.letter-heading]
Para un Destinatario Desconocido

[.salutation]
Amigo,

La vasija o la naturaleza creada, envenenada por el pecado y la muerte,
no puede ser redimida por nada excepto por la vida
y el poder de Dios revelados en la vasija.
Esta vida, esta paz, este poder, esta justicia, esta salvación es el Señor Jesucristo.
El que experimenta algo de esto, experimenta algo de Cristo,
y al ser unido y participar de esto,
participa de algo de Su redención. Porque no es por un conocimiento externo,
sino por una virtud interna y la vida espiritual recibida de Cristo y mantenida en Cristo,
que los que son salvos, son salvos.
Para mí esto es lo que vale, y por lo que he estado dispuesto a desprenderme de todo,
y a viajar cada día hacia esta posesión adquirida.
Y en dichos viajes el Padre de vida y tierna misericordia se complace en ayudarme.

Es el deseo de mi alma que te unas a esta luz, a esta vida,
a este poder que es de Cristo y donde Él es y aparece.
Y si a Él le place,
estoy dispuesto a ser un instrumento en Su mano para la realización de esto en ti.
No es mi deseo sacar a la luz nuevos conceptos en ti,
sino que esperes en el Señor que Él levante Su verdad viva y poderosa en ti,
la única en donde el camino nuevo y vivo es revelado.

Yo soy un gusano, soy pobre, no soy nada, menos que nada en mí mismo.
Soy más débil de lo que puedo expresar o de lo que puedas imaginar.
Sin embargo, en medio de todo esto la vida, el poder,
la justicia y la presencia de Cristo es mi refrigerio, paz, alegría y corona.
A lo que yo te invito es sustancia, sustancia eterna,
la cual conocerás y reconocerás en espíritu que es así,
cuando lo que puede ver en la Verdad sea creado y levantado en ti.
¡Espera en el Señor, teme delante de Él,
ora por Su temor con respiraciones anhelantes y honestas
(las cuales no son de tu propia naturaleza,
sino engendradas por Él)! Ora para que Él te saque de la
sabiduría que enreda y te introduzca en esa inocencia,
sencillez y preciosa semejanza de niño en la que el Padre aparece al alma,
para romper los vínculos y las trampas de la iniquidad.

Tu verdadero y amoroso amigo,
que desea la correcta guía y felicidad de tu alma por medio del Señor Jesucristo
(quien es el único Pastor y Guía hábil) así como de la mía.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Cárcel de Aylesbury, día 20, del mes 10, de 1666

[.letter-heading]
A los Amigos en la Verdad En y Cerca de los Dos Chalfonts

[.salutation]
Queridos amigos,

Como un padre vigila a sus hijos,
así deseo yo sentir al Señor vigilando mi alma continuamente, pues en Su amor, cuidado,
consejo sabio y tierno, está mi seguridad, vida y paz.
Nunca me he arrepentido de esperarlo o de oírlo,
pero si en algún momento he oído algo más y he confundido Su voz,
y en lugar de Su verdad pura he alojado la apariencia
engañosa del enemigo (lo cual es muy fácil hacer),
ese grave error ha resultado en pérdida y dolor para mi alma.

Ahora mis amigos,
el deseo de mi corazón es que ustedes conozcan y escuchen la voz del Preservador.
Así serán preservados y guardados de la voz del extraño
que los aparta de la Semilla pura de vida.
Porque hay algo cerca de ustedes que los observa para engañarlos.
¡Qué el Dios de mi vida, gozo,
paz y esperanza vele sobre sus almas y los libre de las ventajas
que el enemigo pueda tener en cualquier momento contra ustedes!
La Semilla que Dios ha sembrado en ustedes es pura y preciosa.
¡Qué Ella sea hallada viviendo en ustedes y ustedes permaneciendo en Ella!
¡Qué en ningún momento ninguna otra semilla usurpe Su autoridad,
para que ustedes puedan conocer la autoridad y la verdad pura de Dios y se afirmen ahí,
en el dominio puro sobre todo lo que está en contra de Él! Porque
en la Semilla de vida (que ustedes han conocido y recibido en medida)
está el dominio y cuando ustedes son preservados en este,
hay dominio sobre lo impuro y el engañoso.

Queridos amigos, mi deseo es que esa parte en ustedes que se adelanta para juzgar,
aprobar o desaprobar sea sometida, y que esperen el peso del juicio de la Semilla.
¡No juzguen, oh, no juzguen antes de que la luz del día brille en ustedes y dé el juicio!
Más bien permanezcan y caminen en temor y humildad,
en ternura de espíritu y silencio de la carne,
para que el Señor no los entregue a un sentido y
juicio equivocados para dolor de sus almas.
Cuiden su propio estado y la experiencia de vida en sus propias vasijas,
eso los mantendrá puros,
preciosos y castos ante los ojos del Señor. No se entrometan en hablar de los demás,
lo cual carcome la vida interior y puede exaltar sus espíritus
fuera de lugar y por encima del apropiado crecimiento de ustedes.
Sean como el niño destetado, sencillo, desnudo, manso, humilde, tierno,
fácil de guiar y sujeto al Padre.
De esta manera crecerán en lo que es de Dios y serán preservados
de eso que persigue la vida pura para traicionarla y destruirla.
Me intereso por ustedes,
mi clamor ante el Señor es por ustedes y estoy excesivamente
sediento de su preservación y crecimiento en lo que es puro.

Que el Señor Dios de mis misericordias,
esperanza y vida cuide de ustedes para bien y mantenga
sus corazones en vigilancia pura y simple,
para que el enemigo no irrumpa sobre ustedes mediante alguna artimaña sutil.
Que no sean seducidos o apartados del Señor por ninguna tentación,
sino que conozcan la pura, eterna e imperecedera morada, y habiten y permanezcan ahí,
para el gozo de sus propias almas y el regocijo de los corazones de todos
lo que se han esforzado por ustedes en el Espíritu del Señor.

De su hermano y compañero en la fe, paciencia y aflicciones de la Semilla,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Cárcel de Aylesbury, 25 del mes 11, de 1666

[.letter-heading]
Para los Amigos Fieles de la Verdad En y Cerca de los Dos Chalfonts

[.salutation]
Queridos amigos,

¿Han gustado ustedes en alguna medida,
un verdadero sentido o experiencia de lo que Él Señor ha hecho por ustedes?
¿Han experimentado sus espíritus suavizados e inclinados
delante de Él por obra del Espíritu con alabanzas a Su nombre?
De hecho, mi petición al Señor por ustedes,
es que Él se plazca en mantenerlos verdaderamente conscientes de
lo que Él ya es para ustedes y de lo que Él ya ha hecho por ustedes.
Oro que Él los visite aún más, incremente la vida en ustedes, haga que la fe abunde,
les conceda habitar en Su poder y que siempre permanezcan en Su Semilla.
¡Oh, que ustedes puedan experimentar continuamente esa Semilla como la esperanza, la paz,
el gozo, la vida y la fuerza de ustedes,
para que así le den más y más gracias a Él según
sientan Su vida pura levantándose en ustedes,
y de igual manera, la muerte y la tumba sucumbiendo!

¡Ay,
mis amigos! ¿Podemos olvidar alguna vez el estado perdido y miserable en el que estábamos
cuando la misericordia del Señor y Su poder de lo alto nos visitó? ¡Oh,
la oscuridad de ese día, la miseria y la profunda angustia de ese día,
lo cual algunas de sus almas sentían! ¿Acaso no sabían lo que era estar
sin Dios y encontrarse expuestos a los furiosos asaltos del enemigo?
¿Acaso no hubo un día o un momento en que sintieran su debilidad,
y no supieran dónde refugiarse para mantenerse fuera del dolor, la tentación,
los pensamientos vanos y la imaginación? ¿No lo lamentaban?
¿No clamaban y languidecían en sus iniquidades día y noche?
¿Acaso no hay entre ustedes algunos que no hayan conocido
este estado y sentido algo de lo que ahora relato?
Estoy seguro de que hay algunos en la tierra que pueden testificar esto al máximo,
pero sus bocas y corazones están llenos ahora del sentido de la bondad del Señor,
de Su gran salvación y de profundas y elevadas alabanzas a Su Nombre.

Mis queridos amigos, sé a quienes les hablo, es decir, al sensato, al diligente, al fiel,
¿hay alguno de ustedes que no pueda testificar (en la presencia de Dios)
que a menudo ha sentido el brazo y el poder de Su salvación? De hecho,
¿no sienten diariamente al Señor ministrándoles Su salvación? ¿No son vencidos
sus enemigos todos los días por la fe que Él les ha dado en Su poder?
¿Acaso no puedo decirles, dónde está ahora la fuerza del tentador?
¿No han sentido a la simiente de la mujer herir la cabeza de la serpiente?
¿Acaso no pueden decir, en el temor del Señor: "`¿Dónde están aquellas tentaciones,
lujurias, pensamientos vanos e imaginaciones,
por las que en otro tiempo fui vencido y de las que estuve dominado?`"
Puedo hablarles de esta manera porque sé, con certeza, que el poder del Señor Dios,
así como es levantado en algunos de ustedes,
dispersa estas cosas y da dominio sobre ellas.
Porque la vida y su poder son dados como un baluarte
y un arma de guerra contra la iniquidad y su poder,
y donde esta vida es recibida y su poder conocido, se opone,
guerrea y lucha hasta vencerlo.

Esto es lo que da la victoria y vence: La fe en la Semilla.
La Semilla es sentida,
el alma es unida a ella y le es dada al alma fe en ella y a partir de ella.
Entonces la fe se convierte en el líder, en el poderoso director del alma,
y vence sus trampas y a sus enemigos por ella; y cuando esta los ha vencido,
son verdaderamente vencidos.
Después de esto, el alma se recuesta en paz, habita en paz,
se alimenta de la comida viva en los verdes pastos de la vida.
Entonces Jerusalén, el edificio o la vida en el corazón,
se convierte en una habitación tranquila donde Dios y el
alma habitan dulcemente juntos y nada tiene poder para perturbar,
molestar o provocar miedo.
¿Por qué? ¡Porque el Señor Dios de poder está presente allí, despliega Sus alas allí,
y es una columna de nube de día y una columna de fuego de noche! Él ha levantado Su
gloriosa vida en ese corazón y también ha extendido una defensa sobre Su gloria,
con la que el alma está tan cercada y defendida que siente que
las murallas de esta ciudad son salvación y sus puertas alabanza.

¡Alma mía, sigue adelante! ¡Oh, queridos amigos,
ustedes también sigan adelante hacia la plenitud de la gloria de este estado!
No hay otra cosa que desear y esperar.
Esta es su porción, tanto aquí en este mundo como para siempre.
Por lo tanto, esperen en la Semilla de esta vida;
esperen conocer una mayor unión con ella y un crecimiento en ella.
Entréguense a la Semilla para que ella pueda extenderse y cubrirlos.
¡Qué el Señor Dios de la vida,
la revele diariamente y la manifieste cada vez más en ustedes y a ustedes!

Por tanto, sientan (en espíritu) la meta del llamamiento de lo alto, de Dios,
en Cristo Jesús. Miren diariamente Al que los mantiene vivos y frescos,
para que ninguno de ustedes se vuelva perezoso, soñoliento,
negligente o infiel en relación con el gran talento que Dios ha puesto en sus manos.
No permitan que un velo sea puesto sobre sus corazones de nuevo,
ni que el aire se espese, ni que la naturaleza terrenal cubra la Semilla,
para que el que tiene poder en esa tierra y sobre ese aire, no los cautive,
oprima y enrede, ni los haga volverse de Dios otra vez.
Clamen al Señor que mantenga el ojo abierto,
el corazón sencillo y el alma en el verdadero sentido y experiencia,
para que la voz celestial que los sacó de la tierra pueda ser oída diariamente,
instruyéndolos y uniéndolos cada vez más en Aquel que es su vida.
Por tanto, ustedes que temen al Señor,
aman Su nombre y han probado Su bondad y poderosa salvación: ¡Odien el mal!
Todo aquello que Su luz ha puesto de manifiesto y de lo que los ha sacado:
¡Tengan cuidado de nunca participar de ello otra vez! ¡No presten oído al tentador,
sino oren al Padre que puedan discernir sus tentaciones!
¡Nunca consulten o razonen con su enemigo,
sino que en todo esperen experimentar el movimiento, la guía,
vivificación y dulce y pura conducción celestial del Espíritu de su Padre!

Así, pues, esperen en esta pequeña cosa, en esta luz de Dios en ustedes,
hacia la que fueron dirigidos y vueltos en un principio,
la que descubre todas las tinieblas del enemigo,
todos sus engaños y artimañas y guarda la mente de aquellos que son sostenidos por ella.
Permitan que sus mentes sean vueltas a esta luz y que continúen viviendo en ella,
y el poder y la gloria de la vida eterna aparecerán diariamente más y más en ustedes.
Sí, fluirá e irrumpirá sobre ustedes hasta llenar sus vasijas con su virtud,
y hacer que en sus corazones abunden el gozo delante
del Señor y las acciones de gracias a Él.

¡Qué el Dios de las tiernas misericordias y eternas
compasiones haga que Su amor se extienda hacia ustedes,
para que sean alimentados con el alimento vivo,
y para que eso que pudiera invalidar y destruir Su obra encuentre
oposición! ¡Qué ustedes sientan que la obra continua a diario,
y que es poderosamente preservada por Él,
hasta que sea terminada y esté puesta la piedra superior!
Entonces sus almas en el verdadero y pleno sentido de la vida clamarán: "`Gracia,
gracia al que puso el cimiento, levantó, defendió y continuó el edificio, y por fin,
lo ha perfeccionado.`"
De esta manera, todo lo que han experimentado ahora en cierta medida,
lo experimentarán en plenitud,
y verán que todas las promesas de Dios son de una naturaleza preciosa,
y "`sí y amén`" de Dios para la Semilla.

¡Qué la vida, la presencia y el poder del Señor sean con ustedes en esta Semilla,
en sus respiraciones tras ella, en su unión a ella, en su permanencia y espera en Él,
en ella! ¡Qué el Señor Dios les conceda anhelo por ella, unirse a ella,
permanecer siempre y esperar en Él en ella,
y nunca escuchar ni salir en pos de un espíritu ni
sabiduría contrarios! ¡Qué Él los guarde en la sencillez,
mansedumbre, humildad y espíritu tierno que es en Cristo Jesús,
para la alabanza de Su propio nombre y la preservación
y gozo de sus corazones delante de Él para siempre,
amén!

Escrito en el tierno afecto y movimiento de la vida pura,
desde el lugar de mi confinamiento en Aylesbury.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 1, del mes 3, de 1667

[.letter-heading]
A Mis Queridos Hijos J. J. y M. P.

[.salutation]
Mis queridos hijos,

Hay dos cosas que deseo especialmente en referencia a su aprendizaje: Una es,
que puedan aprender a conocer y a oír la voz del Testigo de Dios en ustedes.
Hay algo en ustedes que va a enseñarles cómo hacer lo bueno y cómo evitar lo malo,
si sus mentes se vuelven a eso.
Ese algo les testificará cuando ustedes hagan lo bueno y
testificará en contra de ustedes cuando hagan lo malo.
Ahora bien, que aprendan a conocer, a oír, a temer y a obedecer esto,
es el principal objetivo del aprendizaje en el que deseo encontrarlos.
Cuando su amo o cualquier persona de la familia, los vuelva a este Testigo,
o les recuerde de este Testigo,
o los reprenda por no prestar oídos u obedecer a este Testigo, ¡oh,
ámenlos y bendigan a Dios por ellos en esto!
Recuerden esto, que el que escucha la reprensión es sabio,
pero el que odia o menosprecia la corrección es necio.
Ese es el espíritu de las tinieblas,
el que desea complacerse a sí mismo en sus caminos oscuros,
y por eso no ama la luz que manifiesta sus caminos y los reprende.
El espíritu necio es el que aborrece la corrección de la luz,
y sigue sus caminos y placeres vanos e insensatos contra los que testifica la luz.
Por lo tanto, presten atención al Testigo de Dios en sus corazones,
el cual les descubre estas cosas y los saca de ellas cuando lo oyen, y lleguen a conocer,
a temer y a amar al Señor Dios por su instrucción y testimonio.

El camino de la juventud es vano e insensato, y contamina la mente.
Hijos míos, esperen la limpieza.
Estén atentos a lo que limpia el camino necio de los hijos,
lo cual es la luz que descubre y testifica en contra de sus necedades,
temperamentos vanos, y tentaciones de sus mentes y los saca de ellas.
Aprendan a llevar el yugo en sus tiernos años. Hay una mente vana en ustedes
y hay algo que desea alimentar y satisfacer esa mente vana.
Pero hay algo cerca de ustedes y designado por Dios para enyugarla.
No le den lugar a la vanidad,
porque será motivo de dolor y miseria para ustedes después. ¡Tomen ese yugo sobre ustedes,
el que mantiene sometida la mente vana!
Así entonces, no sólo serán mis hijos,
sino también discípulos de Cristo e hijos del Altísimo.
Esto es lo primero que deseo que se apliquen a aprender principalmente.

La siguiente cosa (que fluirá también de la primera)
es que aprendan a comportarse como buenos hijos,
tanto en la familia como hacia las personas de fuera, de manera mansa, modesta, humilde,
gentil, cariñosa, tierna y respetuosa.
Eviten toda actitud o postura ruda, grosera, atrevida e inapropiada hacia todos.
Honren a su madre y a mí como Dios enseña y requiere,
y cariñosamente únanse entre sí en la relación natural, que es de Dios,
en la que son amados,
teniendo una gran porción de afecto natural y amabilidad unos con otros.

Con los criados, llévense muy cariñosamente, dulcemente, mansamente y gentilmente,
de modo que ninguno tenga motivo de queja contra ustedes,
sino que todos vean su humildad y se inclinen a amarlos.
Con los desconocidos, condúzcanse con cautela, respetuosamente, de manera sobria,
sumisa y comportamiento humilde.
No discutan ni hablen mucho, pues no es apropiado para su edad y lugar.
Más bien, observen lo bueno en los demás y aprendan de aquellos que son buenos.
Miren también cómo evitar el mal tal como lo observan en cualquiera que sea malo.
De esta manera su tiempo será usado en beneficio
y sentirán la bendición de Dios y de sus padres,
así se mantendrán fuera de los males propios de su edad y carácter natural,
y en los que los otros jóvenes (que no son cuidadosos
ni vigilantes) están comúnmente enredados.
Piensen en estas cosas, hijos míos, porque ustedes le darán cuenta a Dios,
que a través de mí los instruye, que soy su padre encarcelado.
Me aflige mucho cuando escucho de algún mal con respecto a ustedes.
Esto es más inquietante y doloroso para mí que mi encarcelamiento,
o cualquier otra cosa que sufra o pueda sufrir del hombre.

Recuerden está única cosa,
que como padre los amonesto y les encargo que tomen nota y observen:
No se desafíen unos a otros o se quejen unos de otros,
por lo malo que observen unos de otros.
Sino más bien, primero tomen nota de lo malo en sí mismos.
Si por la luz verdadera encuentran sus propios corazones limpios de ello,
bendigan a Dios quien lo ha hecho,
y manténganse hacia Su luz y testigo en ustedes por medio de lo cual Él lo hizo,
y miren que no sean vencidos por eso en el futuro.
Pero si son culpables del mismo mal, o han hecho últimamente lo mismo,
o es probable que lo hagan de repente, entonces, ¡oh,
absténganse de acusar o culpar a otro!
Esperen en Él en el temor de Dios y oren a Él para
que sean librados y se mantengan fuera de eso.
Luego, en tierna compasión,
amor y mansedumbre adviertan a su hermano o hermana de su mal y
vigilen para ser útiles para preservarlos o restaurarlos.
Oren a Dios para que los dirija cómo ser útiles para ellos.
Porque es el espíritu y la naturaleza del mal los que están listos para acusar a otros,
y aun cuando eso nunca haya sido tan malo ni culpable, se excusará,
pondrá la culpa sobre los demás o recordará alguna otra falla de otro,
cuando debería ser sensible y estar avergonzado de lo suyo.

Queridos hijos, si ustedes inclinan sus mentes para aprender estas cosas,
el Señor los ayudará en ellas, se convertirá en su maestro,
guía y protector y derramará sus bendiciones sobre ustedes.
En esto serán un consuelo para mí y su madre, y un honor a Su Verdad.
Que Él me dé instrucciones sabias y paternales para enseñarles más. Pero si son descuidados,
necios, vanos y siguen sus propias mentes y lo que se levante ahí del malvado,
afligirán mi corazón y provocarán a Dios en su contra, a traer el mal sobre ustedes,
tanto en este mundo como para siempre.

Por lo tanto, hijos, tengan en cuenta lo que está cerca de ustedes:
La luz de Dios que descubre lo malo y lo bueno.
Su Testigo (que observa todo lo que hacen) está cerca.
Sí, Él está en esa luz y con ese Testigo.
Por tanto, sepan que están en la presencia en todo momento de un Dios santo y justo,
que odia lo que es vano y malo,
y ama lo que es bueno y justo delante de Él. Él ha
señalado un día y establecido un tiempo en el que,
o bien los recompensará con paz,
gozo y eterna felicidad si han sido buenos y hecho lo que es bueno, o con miseria,
destrucción y dolor insoportable tanto del alma como del cuerpo,
si han sido malos y hecho lo que es malo.
Bien sabe Dios cuántas instrucciones han oído de los amigos en la Verdad y de sus padres,
y en cuántas reuniones han estado en donde se les ha enseñado y advertido de estas cosas.
Así que si le dan la espalda a Su luz y no escuchan sus amonestaciones,
sino que son vanos, holgazanes, insensatos, temerarios,
pendencieros y hacen lo incorrecto y luego lo cubren con mentiras (y son tan malos,
si no peores, que los niños que nunca fueron enseñados e instruidos así), entonces,
en Su justo juicio y doloroso desagrado,
Dios puede separarlos de Su luz y entregarlos al espíritu tenebroso
y oscuro (de quien viene toda esta iniquidad) para sembrar aquí
en el pecado y sufrir las llamas del fuego eterno en la otra vida.
Porque esta es la recompensa del espíritu de las tinieblas y también,
la recompensa de todos los que están persuadidos por él de ser de su naturaleza,
lo escuchan y le permiten trabajar a través de ellos.

¡Hijos míos,
ocúpense de la Verdad de Dios en ustedes! Él les permitirá
ver y entender la verdad de lo que ahora escribo,
y que en amor paternal y tierno cuidado les escribo estas cosas.
¡Están advertidos del gran peligro de descuidar el tiempo
de la visitación de la luz y del Testigo de Dios en ustedes!
No sigan en los malos caminos del espíritu tenebroso y torcido,
quien los tentará al mal y les impedirá acercarse a Dios mientras lo escuchen.
Por tanto, no sean necios como para ser conducidos por él a la destrucción,
por el camino malo y las malas obras que llevan a eso;
sino sean sabios al atender la luz y seguirla fuera de lo que es malo,
hacia todo lo que es bueno para salvación de sus almas.

Deseo que los Amigos de la familia^
footnote:[El resto de esta carta no está dirigido a sus hijos,
sino a otros Amigos que vivían en su casa, y a Gulielma,
su hijastra y después la esposa de William Penn.]
velen sobre ellos en estos aspectos, y que cuando encuentren ocasión justa,
pongan en sus mentes algunas de estas cosas en el temor y sabiduría de Dios,
con ternura y delicadeza.
Pero tengan cuidado de recriminarlos o exasperarlos,
para que no se endurezcan de esta manera y el mal se levante y se fortalezca en ellos.
Mi querida G. +++[+++sin duda, su hijastra, Gulielma, después esposa de William Penn] y Amigos,
velen sobre sus propios corazones y caminos para que puedan ser de ejemplo para ellos,
para que así no solo lean estas cosas de mis escritos,
sino también en su actitud hacia ellos y hacia los demás. Que el Señor bendiga su vigilancia,
cuidado y empeño en ello,
para que yo pueda escuchar buena referencia de ellos y ser
consolado en la misericordia y bondad del Señor hacia ellos.

Su padre que les desea bien y que les vaya bien tanto aquí como en el más allá.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 10, del mes 3, de 1667

[.letter-heading]
A los Amigos en Chalfont en Buckinghamshire

[.salutation]
¡Oh amigos!

¡Aliméntense del árbol de la vida! ¡Aliméntense de la medida de vida y de su poder puro
que Dios ha revelado y manifestado en ustedes! ¿Conocen ustedes su comida?
¿Recuerdan el sabor y el gusto de ella?
Entonces manténganse en la misma y no se inmiscuyan en lo que parece muy
codiciable para el otro ojo y para alcanzar la sabiduría. ¡Permanezcan
en la simplicidad que está en Cristo,
en la verdad desnuda que han sentido allí! Ahí serán
capaces de conocer y distinguir su comida,
la cual tiene varios nombres en la Escritura, pero todos son la misma cosa: Pan, leche,
agua, vino, la carne y sangre de Él que bajó del cielo.
(Juan 6:51). Es la misma,
sólo que es dada más suave o más fuerte según la capacidad del que la recibe,
y así le han dado diferentes nombres a ella en concordancia.

¡Manténganse fuera de esa sabiduría que no conoce la sustancia,
porque esta sabiduría es la que también tropieza con los nombres!
Pero guarden la Semilla de vida, guarden la Semilla del reino,
aliméntense de lo que era desde el principio.
¿No es esta comida de verdad, bebida de verdad, carne de verdad y sangre de verdad?
El Señor los ha traído a la ministración de vida y poder,
en la que las cosas son conocidas por encima y más allá de simples nombres,
en la que la vida es revelada y sentida más allá de lo que las palabras puedan expresar.
¡Moren en sus habitaciones y aliméntense de la comida que Dios lleva a sus habitaciones,
la cual es pura, viva,
espiritual y hará que sus almas y espíritus vivan cada vez más en y para Dios!
No se sobresalten o perturben por la sabiduría de la carne,
sino experimenten lo que se fija y se establece en el poder puro.

¡Qué el Señor Dios los preserve y les dé poder para vigilar
contra todo lo que es contrario a Él en cualquiera de ustedes,
y experimenten la victoria y el dominio sobre ello!

Esto brotó para ustedes en la buena voluntad de su Padre,
de la vida y del amor de su hermano en la Verdad,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Cárcel Aylesbury, día 8, del mes 5, de 1667

[.letter-heading]
Para George Fox

[.salutation]
Estimado G. F.,

Siento la tierna misericordia del Señor y una parte de ese quebrantamiento,
temor y humildad que durante mucho tiempo he esperado
y respirado con anhelo en pos de ello.
Siento la unidad y la fuerza del cuerpo.
¡Oh, bendito sea el Señor, quien me ha preparado,
restaurado y levantado mi vida del sepulcro!
Siento una gran estima y amor por ti, a quien el Señor ha elegido, ungido y honrado,
y por tus hermanos y compañeros en la obra del Señor.

Estimado George Fox, ruego tu amor,
te suplico tus oraciones en la fe y seguridad de que el Señor te oye,
para que yo sea aún más quebrantado, más lleno del temor del Señor,
más pobre y humilde delante del Señor,
y camine en perfecta humildad y ternura de espíritu delante de Él todos mis días.

Estimado George Fox,
tú puedes sentir mis deseos y necesidades más plenamente
que mi propio corazón. Ayúdame en el tierno amor,
para que yo sienta establecimiento y estabilidad en la verdad,
y experimente la separación perfecta y dominio en
el Señor sobre todo lo que es contrario a Él.

Suplico tus oraciones por mi familia,
que el nombre del Señor sea exaltado y Su verdad florezca en ella.
Estimado G. F., de hecho mi alma anhela el puro,
pleno e imperturbable reino de la Vida en mí.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Cárcel de Aylesbury, día 15, del mes 5, de 1667

[.letter-heading]
A los Amigos de los Dos Chalfonts

[.salutation]
Queridos amigos,

¡Oh, los tesoros de la sabiduría y del conocimiento, las riquezas del amor,
la misericordia, la vida,
el poder y la gracia de nuestro Dios que son atesorados por el alma en el Señor Jesús!
Estos son dispensados gratuitamente y dados por Él a los que vienen a Él,
esperan en Él, permanecen en Él y se rinden fielmente a la ley de Su vida,
aquellos cuyo deleite es ser hallados en sujeción
y obediencia a la luz y demandas de Su Espíritu.

¡Sientan, mis amigos, oh sientan su porción y permanezcan en donde la herencia se conoce,
se recibe y se disfruta!
Porque no se conoce a Cristo verdadera y sensatamente,
excepto por una medida de Su vida experimentada en el corazón,
por medio de la cual el corazón es hecho capaz de entender las cosas del reino.
El alma sin Él está muerta,
pero por la vivificación de Su Espíritu llega a la consciencia
la capacidad de comprender las cosas de Dios.
La vida le da sentir, ver, gustar, oír y oler las cosas celestiales,
por medio de tales sentidos es capaz de discernirlas y distinguirlas de las cosas terrenales.
A partir de esta medida de vida, la capacidad se incrementa y los sentidos se fortalecen;
ven más, sienten más, gustan más, escuchan más, huelen más. Ahora,
cuando los sentidos crecen y se fortalecen, viene establecimiento y estabilidad,
seguridad y satisfacción. Entonces el alma está asegurada
y establecida acerca de las cosas de Dios en la fe,
y la fe da seguridad al entendimiento.
De esta manera,
las dudas y disputas en la mente vuelan y el alma vive en la demostración cierta,
y en el fresco sentido y poder de la vida.
Diariamente experimenta (en el corazón y alma) que la Palabra eterna y
el poder de vida son lo que es testificado de ellos en la Escritura.
Reconoce la carne y la sangre del Cordero, el agua y el vino del reino,
el pan que baja del cielo,
y los distingue de todas las otras cosas al alimentarse diariamente de ellos en espíritu.
¿Qué corazón puede concebir la justicia, la santidad, la paz,
el gozo y la fuerza de la vida que son experimentados aquí?

Amigos, no hay obstáculos en la Fuente.
Dios es la plenitud y Su delicia es vaciarse en los corazones de Sus hijos,
y lo hace conforme se abre paso en ellos y conforme
ellos son capaces de beber Su virtud viva.
Por lo tanto, donde el alma se ensancha, donde los sentidos se fortalecen,
donde la boca se abre a lo ancho (y el Señor Dios está listo
para derramar sus riquezas) ¿qué le impide al alma ser llenada?
Y siendo llenada,
¡cuán natural es que rebose e irrumpa internamente en admiración
y profundo sentido espiritual con respecto a lo que no puede pronunciar!
Clama diciendo: "`¡Oh, la plenitud! ¡Oh, la profundidad, altura,
anchura y longitud del amor! ¡Oh, la compasión, la misericordia,
la ternura de nuestro Padre!`" ¡Cuánto se ha compadecido,
cuánto ha perdonado más allá de lo que el corazón podía creer! ¡Cuánto ha ayudado
en la hora de la aflicción! ¡Cuánto ha conquistado y dispersado a los enemigos,
que en su incredulidad,
el corazón estaba a menudo dispuesto a decir que eran invencibles,
pensando que un día moriría a manos de uno de sus enemigos poderosos,
codiciosos y corruptos! ¡Cuánto le ha puesto fin Él a las dudas, temores,
conflictos y problemas con los que la mente estaba abrumada
y alterada! ¡Ahora Él extiende la paz como un río;
ahora Él saca el alma de la cisterna a verdes pastos;
ahora ella se alimenta de la frescura de la vida y se satisface
y bebe del río del placer de Dios y se deleita!
Y canta alabanzas al Cordero y al que está sentado en el trono diciendo: "`¡Gloria,
gloria! ¡Vida, poder, dominio y majestad sean a Su Nombre para siempre,
sobre todos los poderes de las tinieblas y sobre todos los enemigos del alma!`"

Ahora, mis queridos amigos, ustedes saben algo de esto y conocen el camino hacia esto.
¡Sean fieles, sean fieles! ¡Continúen, continúen!
Que nada los detenga,
sino esperen y sigan diariamente la palpable guía
de esa medida de vida que Dios ha puesto en ustedes.
Pues la medida es una con la plenitud,
y la plenitud corre todos los días hacia ella y la llena,
para que esta corra en ustedes y los llene.
¡Que ustedes sean ensanchados en sus propios corazones,
como el corazón del Señor se ensancha hacia ustedes! ¡Este es el día de amor,
de misericordia, de compasión,
de la obra de su tierna mano! ¡Este es el día de sabiduría,
de poder y de bondad de nuestro Dios manifestado abundantemente en Jesucristo!
¿Por qué habría de detenerse el fluir en alguno de nosotros?
¡Que el Señor quite eso que se interpone en el camino!
Porque en la fiel espera del poder que es levantado, el Señor lo eliminará, sí,
el Señor lo eliminará,
y el crecimiento en Su verdad y poder será experimentado por los que esperan en Él.

Amigos, no se desanimen a causa de los enemigos de sus almas.
¿Están turbados con pensamientos, temores, dudas, imaginaciones, razonamientos,
etc.? ¿Todavía ven mucho en ustedes que no está sometido al poder de la vida?
¡No teman! ¡No se fijen en eso, para que no se desanimen,
más bien miren hacia Él! Miren hacia el poder que
está sobre toda la fuerza de esas cosas.
Esperen el descenso del poder sobre ustedes.
Permanezcan en la fe de la ayuda del Señor esperando
con paciencia hasta que el Señor se levante,
y verán si Su brazo no dispersa lo que el de ustedes no pudo.
Así que permanezcan quietos delante de Él, y en quietud crean en su Nombre.
No entren en las persuasiones del enemigo, aunque ellas llenen el alma,
porque hay algo en lo que no pueden entrar y de donde brotarán en ustedes la paciencia,
la fe y la esperanza, aun en medio de todo lo que puedan hacer.

Por tanto, sumérjanse en esto,
y estén ocultos en la mala hora hasta que las tentaciones pasen,
se quiebre la fuerza del tentador y el brazo del Señor que lo quebró sea revelado.
Entonces verán que el enemigo levantó nada más que un mar de problemas para sus almas,
sólo para hundirse a sí mismo en él. ¡El Señor echará en ese mar
el caballo y su jinete que pisoteó al Justo dentro de ustedes,
y ustedes estarán en la orilla y cantarán el canto de Moisés Al que lo ahogó
y los libró de él! Y a su debido tiempo también cantarán el canto del Cordero,
cuando Su vida brote en ustedes en Su dominio puro,
triunfando sobre la muerte y sobre todo lo que es contrario a Dios,
tanto dentro como fuera.

Ahora, amigos, en una espera atenta y rendición al Señor,
y en el ejercicio diario de la cruz llevando a la
muerte en ustedes lo que no es de la vida,
esta obra continuará a diario.
Ustedes sentirán del Señor eso que los ayudará, aliviará, refrescará y satisfará,
algo que ni la lengua ni las palabras pueden pronunciar.
Que el Señor Dios sople sobre ustedes,
los preserve y los llene de Su vida y Espíritu Santo,
para el crecimiento y regocijo de sus almas en Él,
quien es nuestro bendito Padre y Redentor misericordioso.

Y luego,
en cuanto a lo que nos pueda suceder externamente en este estado confuso de cosas,
¿no confiaremos en nuestro Padre tierno y descansaremos satisfechos en Su voluntad?
¿No estamos grabados en Su corazón y en las palmas de Sus manos?
¿Puede Él olvidarnos en algo que hace?
¿Nos dañará algo?
¿Vendrá algo entre nosotros y nuestra vida,
entre nosotros y Su amor y tierno cuidado sobre nosotros?
Aunque la higuera no florezca, ni en las vides haya frutos;
aunque falte el producto del olivo y los campos no produzcan alimento;
aunque las ovejas sean quitadas de la majada y no haya vacas en los corrales; con todo,
¿no debemos alegrarnos en Jehová y gozarnos en el Dios de nuestra salvación?
Aunque la tierra sea removida y se traspasen los montes al corazón del mar;
aunque bramen y se turben sus aguas y tiemblen los montes a causa de su braveza,
¿no hay un río cuyas corrientes alegran la ciudad de Dios?
¿No es el gozo, la virtud, la vida,
el dulce frescor de este río experimentado en el lugar santo del tabernáculo del Altísimo?
Y el que provee alimento interior para el hombre interior, vestido interior,
refrigerio interior ¿no proveerá lo que es suficiente para lo exterior?
Sí. ¿No sostendrá Él nuestra mente y será nuestra fuerza, porción, armadura, roca, paz,
alegría y satisfacción plena en todas las condiciones?
Porque no es la circunstancia la que hace a alguien desgraciado,
sino la falta de Él en la circunstancia.

Él es la sustancia de todo, la virtud de todo, la vida de todo, el poder de todo.
Él nutre, Él preserva,
Él sostiene (haciendo uso de la creación o sin la creación) como le place.
El que lo tiene a Él, el que está con Él, el que está en Él, no puede estar desprovisto.
Ahora consideren, ¿el espíritu de este mundo tiene contentamiento en todo lo que goza?
No, está intranquilo, está insatisfecho.
Pero, ¿puede la tribulación, angustia, persecución, hambre, desnudez,
peligro o espada interponerse entre el amor del Padre al hijo, o en el descanso,
contentamiento y deleite del hijo en Su amor?
Y, ¿no se tragan el amor, la paz,
la alegría y el verdadero descanso toda la amargura y tristeza de la condición externa?

La semilla (la verdadera naturaleza y nacimiento) no solo tiene la promesa de vida eterna,
sino que además tiene lo necesario para la vasija
(en donde habita) en esta vida también. Por tanto,
habiten en eso para lo cual es la promesa, y vivan en la promesa.
Sí, vivan en eso que no puede perder la promesa,
sino que experimenta la presencia y el poder del Padre en todo y sobre todo.
El Justo vive por Su fe, y el que está unido al Justo vive por la fe del Justo,
y no se preocupa más que los lirios, sino que le deja a Él el cuidado de todo,
a quien correctamente le pertenece.
Él es el que nutre, viste,
preserva y hace que los lirios del campo crezcan y florezcan en belleza y gloria.
Y, ¿no vestirá, alimentará y cuidará Él mucho más a Sus propios lirios,
los lirios celestiales, los lirios de su propio jardín?

No miremos hacia afuera como el mundo, ni juzguemos,
ni temamos según la apariencia de las cosas, según la manera del mundo.
Más bien,
santifiquemos al Señor de los ejércitos en nuestros
corazones y que Él sea nuestro temor y pavor.
Y Él nos será un escondite en las tormentas y tempestades
que vienen densas sobre la tierra.

Por tanto, mis queridos amigos, retirémonos y vivamos en la paz que Dios sopla,
y descansemos en la paciencia y quietud del Cordero día y noche,
que nada puede desgastar ni perturbar.
Que el Señor Dios en Su tierna misericordia y por
Su amor profundo y gratuito hacia nosotros,
guíe nuestros corazones cada día más y más en el viaje y hacia la posesión. Porque cada
alma puede heredar y poseer (a pesar de todos sus enemigos) lo que haya recorrido,
y todos los días puede recorrer más y más en lo que aún queda por delante.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Cárcel de Aylesbury, días 2 y 3, del mes 6, de 1667

[.letter-heading]
Para un Destinatario Desconocido

[.salutation]
Querido amigo,

Tú has tenido el camino de salvación fielmente testificado para ti,
y has llegado a la experiencia de la sustancia, es decir,
a la experiencia de eso mediante lo cual el Padre engendra
vida y manifiesta Su amor y paz en y para el alma.
Ahora ¿qué queda?
Mira al Señor para que guíe tus pies en este camino
y te preserve de eso que oscurece y aleja del camino.
De esta manera puedes continuar en tu viaje de forma segura
y llegar a la herencia y disfrutar lo que tu alma anhela.

Hay vida, paz, gozo, justicia, salud, salvación, poder de redención en la Semilla,
y sin embargo, tu alma tiene escasez y no goza de estas cosas.
Bueno, ¿cómo puedes llegar a gozar de ellas?
No hay otra manera sino uniéndose a la Semilla, conociendo la Semilla,
oyendo la voz de la Semilla, aprendiendo y sujetándose a la Semilla.
"`Aprendan de mí y lleven mi yugo sobre ustedes,`" dice Cristo,
"`y hallarán descanso para sus almas.`"
¿Deseas experimentar el descanso de tu alma en Cristo?
Debes conocer la voz de la Semilla, oírla, aprender de Él todos los días,
convertirte en Su discípulo.
Debes tomar de Su naturaleza lo que es contrario a tu naturaleza,
y cuando tu naturaleza esté acabada y la de Él se alce en ti, encontrarás todo fácil.
Encontrarás fácil todo lo que es de la vida, y difícil la transgresión y la incredulidad.
De hecho, cuando la naturaleza de la Semilla crezca en ti,
encontrarás que es muy difícil y antinatural desconfiar del Señor o escuchar a Su enemigo.
Y entonces ese lugar de morada (al cual Satanás trae pensamientos,
sugerencias y razonamientos oscuros) será cambiado
por el lugar de morada que es de lo alto,
en donde hay luz, vida, paz, satisfacción, salud,
salvación y regocijo del alma delante del Señor.

Ahora, no digas:
"`¿Quién hará esto por mí?`" Sino sabe que el brazo
del Señor es poderoso y lleva a cabo cosas poderosas,
y este Brazo ha sido revelado en ti y está trabajando para ti.
¡Oh, si pudieras confiar! (¿Por qué no puedes?
¿No ha sido sembrada una semilla de fe en ti?) ¡Si pudieras entrar y permanecer en el
camino donde Sus operaciones fuertes y poderosas son experimentadas y hechas manifiestas!
¡Si pudieras encontrar la capacidad de vigilar contra lo que daña y angustia tu alma!
Porque las sugerencias tenebrosas del enemigo trabajan
de acuerdo con la naturaleza de ellas,
y si las dejas sobre ti, ¿cómo no te van a oscurecer, afligir y dejarte perplejo?

Por lo tanto, en la mala hora, huye de todas las cosas que surgen así en ti.
Permanece quieto y siente tu ancla,
hasta que Su luz que "`pone de manifiesto`" se levante en ti y te aclare todas las cosas.
No pienses en el largo tiempo de tinieblas,
sino mantente vigilante para que tu corazón esté
libre de tus propios pensamientos y creencias,
hasta que Él traiga algo que puedas recibir de forma segura.
Así que dile a tus pensamientos y creencias (que son según la sugerencia del poder oscuro,
en el momento de tus tinieblas): "`¡Váyanse de mí!`" Y si eso no sucede,
mira al Señor para que les hable y los mantenga fuera,
si no han entrado todavía. Y si Él no lo hace inmediatamente o por un largo tiempo,
no murmures o pienses mucho, sino espera hasta que lo haga.
Sí,
aunque estos pensamientos se impongan sobre ti violentamente
y parezcan haber entrado en tu mente,
deja que sean extraños para ti.
No los recibas, no los creas, no los conozcas ni los reconozcas, y a pesar de todo,
tu corazón permanecerá casto ante los ojos del Señor,
aunque te parezca que te han contaminado.

Mire al Padre para que aprendas de Él estas cosas.
Y a medida que le seas fiel en esto,
te darás cuenta de que tus tinieblas se reducen y
su fuerza será cada vez más quebrantada en ti.
Y no sólo sentirás y gustarás un poco del Señor de vez en cuando,
sino que también llegarás a poseer,
a heredar y a regocijarte delante del Señor en tu porción.

Soy tu amigo en la verdad que no cambia,
sino que es pura y nos preserva puros para siempre.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Desde la cárcel de Aylesbury, día 28, del mes 7, de 1667

[.letter-heading]
A Su Hermano

[.salutation]
Querido hermano,

Esta mañana cuando salí a caminar algo fresco y vivo surgió en mi corazón para ti,
después de lo cual y sin razonar volví inmediatamente para escribirte.
Ahora, si el Señor lo hace útil para ti tendrás motivo para bendecir Su Nombre,
y yo también bendeciré Su Nombre,
porque deseo de todo corazón la vida y el bienestar de tu alma en el Dios vivo,
y que evites todas las trampas que el enemigo pone para
traicionar y mantener tu alma en muerte y esclavitud.
Lo que se levantó en mí fue lo siguiente:

Dios dio a algunos ser apóstoles, a otros profetas, etc., para la obra del ministerio,
para la edificación del cuerpo, para el perfeccionamiento de los santos.
Este fue el don de Dios (en misericordia y amor) para ellos en aquel día,
y ellos tenían que caminar como es digno de este don y ser agradecidos por ello.

Ahora, en estos días el Señor les ha dado dones a algunos para esta misma obra,
de la cual el cuerpo tiene necesidad y debe esperar en el Señor sobre el uso de Su don,
en temor y humildad.
Y nota, hermano, que en cada época los ministros de Dios han sido menospreciados.
Moisés y todos los profetas fueron despreciados en su día. "`¿Qué?`" decían ellos:
"`¿Ha hablado Dios solo por Moisés? ¿No ha hablado también por nosotros?`"
Los apóstoles fueron despreciados en sus días por aquellos
que no se mantenían en la unción que enseña todas las cosas:
"`El que a vosotros desprecia,`" dijo Cristo,
"`me desprecia a mí.`" El que los desprecia en su obra de reunir
y edificar desprecia Al que los envió. Ellos eran vasijas de barro,
de presencia insignificante y muy propensos a ser despreciados.
Todavía es fácil despreciar a los mensajeros y siervos de Dios,
pero el que verdadera y justamente los estime, deberá mantenerse abajo,
vivir en el temor puro y en la consciencia de la vida,
para que pueda ser enseñado por Dios a hacerlo.
Es un asunto fácil tener objeciones contra ellos,
pero ver a través de todos los prejuicios y objeciones la vida pura y preciosa en ellos,
el don, el Espíritu y el poder del Señor,
requiere un verdadero ojo y un corazón abierto al Señor.

¡Ah, hermano!
Esta es una trampa en la que muchos han sido atrapados en edades anteriores,
y en esta edad.
Porque es fácil caer en ella, pero sostenerse fuera de esta trampa no es fácil,
sino solo por el poder y la misericordia del Señor. Querido hermano,
cuando estoy en la consciencia pura ante el Señor y mi espíritu
es abierto por Él y tú eres presentado delante de mí,
puedo rogarle fervientemente al Señor que abra tus
ojos y te dé una verdadera visión de tu estado.
Suplico que Él pueda hacer que tu espíritu se incline ante Él,
y que conozcas y honres lo que es de Él y que nada te impida
(por ningún medio del enemigo) recibir lo que Él,
con tierno amor y misericordia, te ofrece.

Y así, querido hermano, atiende este consejo que recién surge en mi corazón:
¡Escoge a algunos de los fieles de los siervos del Señor y abre tu corazón a ellos!
De hecho, hermano, he tenido durante mucho tiempo un profundo sentido de peligro hacia ti.
¡Que el Señor lo impida para que tu alma viva para Él y no muera a Él! Hay una sabiduría
y una voluntad cerca de ti que te destruirá a menos que el Señor la destruya en ti.

¡Si sólo pudieras llegar a esperar correctamente el movimiento de Su Espíritu,
y aprendieras a ser guardado por Él en eso que conoce Su llamado!
Entonces tendrías hambre y sed de la justicia de Su reino,
anhelarías reunirte y congregarte con Su pueblo,
sentirías que ellos están vivos y tu vida se refrescaría con ellos.
Porque Dios está con Su pueblo y ellos no se reúnen sin Él,
sino que Su presencia está en medio de ellos,
haciendo que Su vida fluya en cada vasija que está abierta
a Él y que crezca más y más en dominio en ellos.
Hermano, estoy satisfecho en mi corazón de que no solo mi amor te habla ahora,
sino mi vida también. ¡Ojalá pudieras oír, sentir, temer e inclinarte delante del Señor!
Entonces Él, a su debido tiempo, te levantaría en Su vida y poder entre Su pueblo,
purificándote y preservándote para siempre puro y vivo para Él.

El deseo de mi corazón ante el Señor por ti es,
que Él abra y mantenga abierto en ti el ojo que ve,
el oído que oye y el corazón que entiende Su verdad,
y que le impida al enemigo levantar otra cosa en ti en lugar de la Semilla de vida.

Grande ha sido la sutileza y profundo ha sido el desvío de la verdad.
Muchos que parecen ser verdaderos judíos no lo son,
sino que se han desviado del Espíritu, vida y poder,
mediante lo cual fueron al principio convencidos y dirigidos.
En estos,
el enemigo ha levantado un asiento de prejuicios y fortalezas
contra el ministerio y poder del Dios vivo.
Pero los que son de la Semilla verdadera bendicen
al Señor al contemplar Su verdadera obra,
mientras otros la desprecian al tener sus expectativas en algo más.

¡Oh, hermano, hay una altivez en algunos,
que se atribuyen el juzgar más allá de su crecimiento y capacidad!
Pero hay un temor en los corazones de otros, para que nada en ellos se levante, o juzgue,
o sea algo más allá o además de la Verdad pura.
Este temor enseña al alma a honrar y a preferir a aquellos a quienes el Señor ha preferido,
mientras que la altivez solo tiene acusaciones y alegatos contra ellos.
Uno de estos experimentará el cuidado de Dios; el otro es dejado por Dios para que caiga.

Querido hermano, deseo que no perezcas,
sino que experimentes la continuación de la obra de salvación en ti.
¡Ojalá que avances por el camino puro, santo,
vivo y poderoso y recibas la corona de fidelidad a la verdad!
Hermano, gime al Señor. Teme ante Él. Conversa y consulta con los que permanecen fieles,
y ellos pueden ayudarte a ver (a través de la guía,
presencia y poder del Espíritu del Señor en ellos) lo que tú no puedes ver.
Recuerda este consejo, porque necesitas de la ayuda que el Señor,
en su tierna misericordia, ha provisto; y tú no puedes estar a salvo sin esta.

Soy tu querido hermano según una unidad natural,
pero anhelo una unidad contigo en la vida pura.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Cárcel de Aylesbury, día 7, del mes 8, de 1667

[.letter-heading]
A un Destinatario Desconocido

[.salutation]
Mi querido amigo,

El camino de la redención es:
Esperar para experimentar la aparición de la luz del Espíritu en el corazón,
y a su más mínima o menor aparición, volverse de la oscuridad hacia ella.
¡Oh, siente el brazo redentor en tu propio corazón y conoce el amor que lo extiende!
Ten cuidado de ser prejuiciado en contra de Sus visitas internas,
porque hay algo cerca de ti que te oscurecerá y mantendrá la Semilla de vida en esclavitud.
Sé que en ti está eso que jadea tras Dios y no está satisfecho,
algo que tiene sed de las aguas vivas.
El Espíritu del Señor dice: "`Vengan, vengan a la fuente de la vida eterna;
beban y vivan.`"

Oh, Señor mi Dios, revela a las almas sedientas qué las retiene de las aguas vivas,
para que no trabajen y gasten sus fuerzas en vano,
en los deberes y ordenanzas inventados por el hombre.
Porque estos pueden arrullar al dormido en el presente,
pero nunca podrán acallar el clamor de la semilla viva, ni satisfacer el alma jamás.

Amigo mío, conozco tu trampa.
Hay una edificación en tu sabiduría terrenal,
un conocimiento que mantienes en tu comprensión,
que no es de la luz de la que brota el verdadero conocimiento,
y en la única en la que este se sostiene.
Debes llegar a experimentar la demolición de esta edificación,
la confusión y dispersión de este conocimiento,
para que el verdadero heredero pueda brotar en ti.
Debes sentir al bebé levantarse,
a quien Dios le revela los misterios de Su reino que Él
oculta a los profesantes y maestros sabios en esta edad,
como lo ha hecho en todas las edades.
Tú eres muy sabio,
pero debes venderlo todo y convertirte en un necio si deseas
las riquezas y los tesoros eternos del reino.

Si deseas acercarte y encontrar acceso a Dios en oración,
debes esperar sentir al verdadero nacimiento orar,
y tener cuidado de presentar las peticiones en tu
propia sabiduría y según tu propia voluntad.
Porque tales son las oraciones del hijo falso o del nacimiento fingido,
de la semilla equivocada, a la cual el Padre no conoce ni considera.
Pero nuestra religión es:
Experimentar lo que Dios engendra y mantiene vivo en nuestros corazones,
y ser enseñados por Él a conocerlo,
a adorarlo y a vivir para Él mediante la dirección y poder de su Espíritu.
En esta religión tenemos el consuelo y las apariciones de su Espíritu,
que están más allá de todas las disputas y cuestiones de la sabiduría del hombre.
De hecho, están más allá de las disputas de nuestros propios corazones también,
siendo demostradas y manifestadas a nuestros espíritus en un principio superior.

Encontré mi corazón atraído en gran amor para escribirte estas cosas.
Mi alma ofrece respiraciones de anhelo al Señor mi Dios,
para que seas atraído a la verdadera unidad y comunión con la fuente de vida eterna,
y para que no seas descarriado del precioso disfrute de Dios aquí,
ni de la salvación de tu alma para siempre.
El camino de la vida es vivo y tus pies deben ser
guiados en él y andar fielmente en él hasta el final,
si deseas sentarte en el eterno reposo y paz de Dios.

Llevo mucho tiempo desolado y en gran duelo ante mi Dios,
y sé cómo compadecerme y llorar por las almas errantes,
aunque no puedo sino regocijarme en este gran día de salvación
y poderosa visitación del Espíritu de Dios,
en el que Él ha buscado y reunido a muchos en el redil de su descanso puro.
El Señor se ha convertido en un Pastor vivo para
muchos y todos los días les ministra Su vida a ellos.
Él está buscando a muchos más. Felices los que conocen y se vuelven
al sonido de la voz del Pastor cuando Él los llama.

Sigo siendo tu verdadero, total, fiel y amoroso amigo,
en el amor y la buena voluntad del Señor que deseo para tu alma como para la mía.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
A un Destinatario Desconocido

[.salutation]
Querido amigo,

Permíteme decirte algunas palabras, no sólo de lo que he sentido en mi corazón,
sino también de lo que he leído en las Escrituras de verdad.

Después de la apostasía el evangelio debe ser predicado de esta manera:
"`Temed a Dios y dadle gloria, porque ha llegado la hora de su juicio,
y adorad al que hizo los cielos y la tierra.`"
Apocalipsis 14:7. Si conoces al Predicador que predicó esto,
si has oído esto predicado en tu corazón,
si te has encontrado con el temor que el Espíritu enseña y da,
si has experimentado la hora del juicio de Dios y
el hacha ha sido puesta en la raíz del árbol,
si has sido enseñado por el Hijo a adorar al Padre en Espíritu y verdad,
entonces te has encontrado sin ninguna duda con el evangelio eterno.
Y si Dios requiere de ti y te ayuda por Su Espíritu y poder a predicar esto a los demás,
entonces eres un predicador del evangelio eterno y ministro capaz del Nuevo Pacto,
no de la letra, sino del Espíritu.
Sin embargo,
te ruego que tengas cuidado de predicar tus propias
conclusiones y concepciones sobre la letra,
como muchos lo hacen hoy.
Porque esto queda corto de la verdadera predicación.
¡Qué estas cosas sean de mucho peso para ti!
Debes aprender la forma correcta de buscar y entender las Escrituras,
debes saber cómo ha revelado el Padre al Hijo en este día
y cómo llegar a Él para recibir la vida de Él. Porque muchos,
por ignorancia, han errado en este asunto y han corrido adelante en su propia voluntad,
sabiduría, y comprensión de las cosas.

Amigo, el Dios que hizo brillar la luz en este mundo externo,
ha juzgado necesario hacer que la luz de Su Espíritu brille interiormente
en el corazón. Únicamente esto da el conocimiento de las Escrituras y
el verdadero significado y discernimiento de las cosas internas y espirituales.
Sí, por esta luz se conoce al Hijo y se siente su sangre purificadora.
Sin esta luz las Escrituras no manifiestan las cosas espirituales,
pero en la luz las Escrituras son un registro y testimonio claro y fiel de ellas.

¡Ten cuidado de cómo lees y entiendes las Escrituras!
¿En qué luz y en qué espíritu estás leyendo?
Porque es fácil errar,
y sin la presencia y guía del Espíritu de Dios no se puede caminar con seguridad.
Realmente es una gran presunción en cualquier hombre,
leer las Escrituras audazmente y sin temor y reverencia hacia Quien las escribió,
o poner alguno de sus propios significados y concepciones sobre las palabras de Dios.
Pero esto es difícil de evitar en el hombre que lee en la libertad de su propio espíritu,
sin la luz del Espíritu de Dios que es el límite y el yugo de los
verdaderos lectores y de los que entienden las Escrituras.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 4, del mes 4, de 1668

[.letter-heading]
A una Pareja a Punto de Casarse

[.salutation]
Queridos amigos.

Ustedes están emprendiendo algo grande y pesado,
y tienen necesidad de la guía y consejo del Señor
en esto para que sea hecho en la unidad de Su vida,
y así Amigos en la Verdad puedan sentir que es de Dios y encuentren satisfacción en ello.

Amigos, la parte donde yacen los afectos se adelantará en las cosas de esta naturaleza,
a menos que sea atada.
Esto puede fácilmente persuadir la mente a juzgar
que tales cosas son correctas y del Señor,
cuando en realidad no lo son.
Ahora bien, si no son del Señor, sino sólo de la parte afectiva,
los Amigos no pueden tener unidad con esto, ni resultará en una bendición para ustedes,
sino que lo encontrarán ser un daño en sus condiciones
y una carga sobre sus espíritus después,
y los frutos y los efectos de esto no serán buenos, sino malos.
Entonces, tal vez, desearán haber esperado más cuidadosa y sinceramente en el Señor,
y haber tomado más tiempo y consultado más con los Amigos.

El Señor, mediante Su providencia, les ha dado un poco de tiempo de respiro.
¡Oh, retírense en Él,
humíllense delante de Él y pídanle consejo por Su buen Espíritu para su bien!
Oren para que si esto no es del Señor,
Su poder (siendo esperado por ustedes) suelte sus afectos al respecto,
pero si es del Señor y es llevado delante de los Amigos,
y consejo y recomendación de ellos son buscados en el temor del Señor,
entonces ellos tendrán unidad con esto y con alegría expresarán su solidaridad.
Esto será una fuerza para ustedes contra el tentador más tarde.

En el amor verdadero a ustedes y en firmeza de corazón, de su amigo en la verdad,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 4, del mes 3, de 1668

[.letter-heading]
A un Destinatario Desconocido

[.salutation]
¡Oh amigo!

¿Aparecerá el Señor poderosamente en la tierra e Israel no lo conocerá? ¿Los
profesantes de esta época no entenderán más de la aparición de Cristo en el Espíritu,
que lo que entendieron los judíos de Su aparición en la carne?
¿Tropezarán con la misma piedra de tropiezo?
Sí, la misma piedra de tropiezo está puesta para que la sabiduría del hombre se tropiece,
como en todas las generaciones.
Y no hay manera de evitar el tropiezo,
sino al salir de esa sabiduría hacia la sencillez de un bebé,
la que da entrada a la sabiduría pura y celestial.
Me atrevo a afirmar lo siguiente,
como en la presencia de Dios y en Su puro temor (habiendo
recibido el sentido de esto de Él):
Que los que hoy se oponen a la aparición de Cristo en Espíritu
(debido a su gran conocimiento y sabiduría de la letra),
también se habrían opuesto y negado la aparición
de Él en la carne si hubieran vivido en ese tiempo.
Porque la sabiduría que los judíos reunieron de la letra no reveló a Cristo en sus días,
sino solo el Padre, y lo mismo debe revelarlo en este día.

¡Oh,
si usted pudiera experimentar la revelación pura
del Padre a su corazón! ¡Espere un nuevo corazón,
un nuevo oído, un nuevo ojo!
Espere experimentar al Puro en usted y a que Él cambie su mente,
para que todas las cosas se vuelvan nuevas para usted.
Las Escrituras deben ser nuevas (ellas son así, en realidad, cuando Dios las abre),
nuevos deberes, nuevas ordenanzas, nuevas gracias, nuevas experiencias;
debe haber una nueva iglesia, edificio del Espíritu, donde Dios y su alma moren juntos.
Y usted podrá decir en presencia del Señor: "`¡Esta es la ciudad,
el edificio propio de Dios, cuyo fundamento fue puesto con zafiros,
cuyos muros son salvación y sus puertas alabanza!`"

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 12, del mes 3, de 1669

[.letter-heading]
A Catherine Pordage

[.salutation]
Amiga,

Tu estado y condición han estado conmigo prácticamente, desde la última vez que te vi.
Soy consciente de cuán duro es para ti rendirte para
ser alcanzada por la semilla y el poder de la vida,
y cuán rápido y fácilmente tu oído y corazón se abren a otro.
Esta palabra de consejo para ti ha estado en mi corazón desde esta mañana:
Siéntate y considera el costo de arar tu campo y de buscar
el tesoro escondido de la sabiduría pura y verdadera,
y considera seriamente si puedes venderlo todo por ella,
tanto las riquezas internas como externas.
Entonces, si pones la mano en el arado, no mirarás atrás en pos de algo más,
interna o externamente,
sino que estarás contenta y satisfecha sólo con la
perla de la verdadera sabiduría y vida.

Ahora bien, si realmente estás dispuesta a hacer esto ante los ojos de Dios,
debes rendirte para seguir al Señor por medio de la guía de Su Espíritu,
salir de todos los caminos de tu propia sabiduría y conocimiento,
y de todas las cosas en las que tienes una vida y deleite fuera
de Él. No debes intentar determinar en qué tienes una vida,
sino que el Señor debe escudriñar tu corazón. Él pronto te mostrará
(si tu corazón está desnudo y abierto delante de Él,
dispuesto a oír y a aprender de Él) algo en tu corazón, algo en tus caminos,
algo en tus palabras, pensamientos, etc., que es contrario a Su vida pura y Espíritu,
entonces eso debe ser negado y entregado de inmediato.
Luego tal vez, el Señor pronto te descubra otro amante,
que ha tenido más de tu corazón de lo que has sido consciente.
Y así, debes separarte de uno tras otro, hasta que te hayas separado de todos.
Pero si no los entregas uno a uno al Señor, aunque pusieras tu mano en el arado,
mirarías hacia atrás en algún momento u otro.
Pronto la sabiduría que aleja del Señor cegaría tu ojo,
engañaría tu mente y te sacaría de la simplicidad y desnudez de la verdad a una imagen,
para que en lugar de la misma verdad pura creas y abraces una mentira.

El Señor te ha alcanzado y está dispuesto a escudriñar tu corazón,
a descubrir al engañador y enemigo en sus lugares más secretos de acecho.
Pero cuando el Señor lo haya descubierto,
debes entregarlo al golpe de Dios y no permitirle
que encuentre un refugio en tu mente para salvarse.
Porque él es muy sutil y torcerá y entretejerá todo
tipo de formas para engañarte y salvarse,
y aún no estás familiarizada ni eres capaz de discernir sus artimañas.

Debes salir del espíritu de este mundo si quieres permanecer en el Espíritu de Dios,
y debes salir del amor de las cosas de este mundo,
si quieres salir del espíritu de este mundo.
Porque el espíritu de este mundo se aloja y vive en el amor a las cosas de este mundo
y no puedes tocar las cosas inmundas sin tocar también algo del espíritu inmundo.
Por lo tanto, Juan dijo desde un verdadero y profundo entendimiento: "`No améis al mundo,
ni las cosas que están en el mundo`" (si amas las cosas del mundo, amas al mundo),
porque "`si alguno ama al mundo, El amor del Padre no está en él.`"

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 11, del mes 1, de 1670

[.letter-heading]
A Thomas Walmsley

[.salutation]
Querido amigo,

Hay algo en mi corazón esta mañana que quiero escribirte
en el mismo amor con el que he escrito antes,
el cual siento puro, de Dios y no fingido hacia ti y hacia todos los hombres.
Es lo siguiente: Toda religión verdadera tiene una raíz verdadera, pero esa religión,
profesión, adoración, fe, esperanza, paz, seguridad, etc.,
que no crece de la verdadera raíz, no es verdad.

Esta raíz verdadera está cerca y debe ser experimentada
cerca llevando la rama y haciendo que produzca fruto.
No es suficiente oír de Cristo o leer de Cristo,
sino que debo experimentarlo como mi raíz, mi vida, mi fundamento.
Debo experimentar mi alma injertada en Él por Aquel que tiene poder para injertar.
Debo sentir el arrepentimiento que me ha dado Él, la fe que me ha dado Él,
y al Padre revelado y dado a conocer por Él,
mediante el resplandor puro de Su luz en mi corazón. Dios que hizo que
la luz resplandeciera de las tinieblas hace que resplandezca en mi corazón,
para que en Él y por medio de Él yo llegue a conocer, no sólo al Hijo,
sino también al Padre.
Por tanto, yo debo salir de la oscuridad, del pecado,
de las contaminaciones del espíritu de este mundo,
y entrar en la comunión pura y santa de los vivos,
mediante Su santa guía y dirección. Debo experimentar todas mis oraciones,
todos mis consuelos, toda mi disposición,
toda mi habilidad para hacer y sufrir por Dios y por el testimonio de Su verdad,
que se levantan de esta santa y pura raíz de vida.
Esta raíz da diariamente fuerza contra el pecado y la muerte a todos los
que esperan en Él en verdadera humildad y sujeción pura de alma y espíritu.
En esto hay un indescriptible consuelo y satisfacción dados por Él al alma,
que todos los razonamientos de los hombres y las artimañas de Satanás no pueden desanimar.
Porque Aquel que dio esto lo preserva y lo mantiene sobre toda fuerza que pueda asaltarlo.

¡Amigo, te suplico que vengas, sí, ven a la raíz verdadera! ¡Ven a Cristo en verdad!
No descanses en un conocimiento externo, sino ven a la vida interior,
a la vida oculta y recibe vida de Aquel que es la vida.
Luego, aprende a permanecer y a vivir para Dios en la vida de Su Hijo.
Porque la muerte y la destrucción, la corrupción y la vanidad,
pueden hablar de la fama de Cristo (quien es la sabiduría de Dios),
pero no pueden conocer o descubrir el lugar donde esta sabiduría es revelada.
No pueden acercarse al temor verdadero y puro que Dios pone en los corazones de los Suyos.
Este es el principio de la verdadera sabiduría que limpia de tinieblas
e impureza los corazones de aquellos a quienes se les da.
Porque la luz expulsa la oscuridad, la vida expulsa la muerte,
la pureza expulsa la impureza, Cristo, donde es recibido, ata y echa al hombre fuerte,
al tomar posesión del corazón. Y si algún hombre está verdadera y realmente en Cristo,
llega a experimentar la nueva creación, es decir,
que las cosas viejas pasaron y que todas las cosas son hechas nuevas.

Cristo es fiel en toda Su casa ("`cuya casa somos nosotros,`" dice el apóstol,
"`si retenemos firmes hasta el fin la confianza y el gloriarnos en la esperanza.`"
Hebreos 3: 6). Él es fiel como Hijo, quien viene en el nombre y autoridad del Padre,
para hacer todo lo que se deba hacer en el corazón. Él es fiel en descubrir lo
que es contrario a Dios allí y fiel en comprometer Su poder contra eso.
¿Acaso no prevalecerá Su poder?
Y donde esto prevalece,
y el beneplácito de la bondad de Dios y la obra de la fe se cumplen con poder,
¿no es allí glorificado el nombre del Señor Jesucristo?
Lee 2 Tesalonicenses 1: 11-12 y considéralo.
¿Venció Cristo al diablo en ese cuerpo de Su carne,
y no lo vencerá en el corazón de Sus hijos por el poder de Su Espíritu?
Por lo tanto,
espera sentir el Espíritu y el poder de Cristo salvándote de lo que nada más puede salvarte,
y derribando en ti bajo Sus pies lo que nada más puede derribar.

Este es el verdadero deseo que tiene mi alma,
tras la eterna salvación y satisfacción de la tuya.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 28, del mes 1, de 1670

[.letter-heading]
A la Viuda Hemmings

[.salutation]
Mi querida amiga,

A quien verdaderamente amo, y cuya prosperidad en la verdad deseo sinceramente.
Debido a que encuentro que tu mente está muy ocupada en una cosa, es decir,
recibiendo pan y vino en memoria de la muerte de Cristo,
tengo en mi corazón decirte algo en este momento.
Tal vez el Señor pueda abrir tu mente y dejarte entrar en un sentido verdadero de esto.

Hay una cena (o un cenar con Cristo) más allá del pan y del vino externo,
que Él prometió a los que oyeran Su voz, abrieran la puerta y lo dejaran entrar.
(Apocalipsis 3:20) Ahora,
esta es la cena con la que mi corazón desea que estés familiarizada y de la que participes.
En la medida que la conozcas y participes de ella,
la llamarás el "`banquete de los manjares suculentos y de los vinos refinados.`"
(Isa.
25:5) Cristo dijo:
"`No beberé más de este fruto de la vid hasta que
lo beba de nuevo en el reino de mi Padre.`"
¿Qué vino,
qué fruto de la vid es el que Cristo bebe de nuevo
con sus discípulos en el reino de su Padre?
¿No es ese vino el que Él y ellos beben ahora juntos cuando Él cena con ellos?
¡Oh, qué el Señor te dé entendimiento, para que puedas llegar a la sustancia,
experimentar la sustancia y heredar la sustancia para siempre!

"`Por tanto, amados míos, huid de la idolatría,`" dijo el apóstol.
(1 Corintios 10:14) ¿A qué idolatría se refiere?
"`Como a sensatos os hablo juzgad lo que digo.
La copa de bendición que bendecimos, ¿no es la comunión de la sangre de Cristo?
El pan que partimos, ¿no es la comunión del cuerpo de Cristo?`"
(Versículos 15-16) Con respecto a la copa y al pan externos,
¿no habrían podido ellos encontrarse fácilmente en idolatría? Pero los que conocían,
discernían y se ocupaban del cuerpo y de la sangre en verdad,
no se encontraron en idolatría. "`Siendo uno solo el pan, nosotros con ser muchos,
somos un cuerpo; pues todos participamos de aquel mismo pan.`"
(Versículo 17) ¡Oh, profundo, profundo, en verdad!
El pan que desciende del cielo, es el pan que le da vida al alma.
A menos que comamos la carne del Hijo del hombre y bebamos Su sangre,
no tenemos vida en nosotros.
Pero si comemos Su carne y bebemos Su sangre, llegamos a ser una carne con Él,
hueso de Su hueso.
Efectivamente, llegamos a ser del mismo pan con Él, y así, del único cuerpo, del pan vivo.

Mi querida amiga, el Señor te dé entendimiento,
abra tu corazón y te haga crecer en unión y experiencia con Su verdad,
para que al crecer en la verdad llegues a entenderla
cada vez más y a estar familiarizada con ella.

[.signed-section-closing]
Soy tu amigo no fingido en la verdad que es pura,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Cárcel de Reading, día 3, del mes 6, de 1670

[.letter-heading]
A un Destinatario Desconocido

[.salutation]
Amigo,

El Señor Dios del cielo y de la tierra, que examina el corazón y prueba los pensamientos,
sabe que nosotros (los que somos llamados Cuáqueros) no tenemos cosas
secretas o principios escondidos entre nosotros para ganar a la gente.
Nosotros mismos hemos sido conquistados por la sencillez y claridad
de la verdad como es en Cristo Jesús y andamos en ella,
así que el único deseo de nuestros corazones es traer a los hombres aquí,
donde puedan tener la demostración del Espíritu de Dios,
y oigan al verdadero testigo hablando la verdad en sus propias consciencias.

En verdad fue un gran motivo de satisfacción para nuestros
corazones cuando el Señor nos volvió a Su verdad,
que no encontramos que fuera algo nuevo,
sino más bien lo que habíamos presenciado y experimentado en los
días de nuestra anterior profesión. Porque todas las oraciones,
conocimiento, entendimiento de las Escrituras, fe, amor, celo, mansedumbre, paciencia,
humildad y todo lo que teníamos en aquellos días
que nos era querido y precioso a los ojos de Dios,
venía del Espíritu de vida,
de esta Semilla de vida que Dios nos ha manifestado ahora más claramente,
y hacia la que ha vuelto nuestras mentes.
¡Oh, que los que aún hablan contra ella, la conozcan,
así como el Señor nos ha dado conocerla!
Ciertamente, entonces no podrían pensar o hablar tan duramente de ella como lo hacen.
Porque Cristo era en verdad el Hijo de Dios en Su aparición en la carne,
sin importar lo que los hombres sabios y profesantes de aquella época juzgaran y hablaran
de Él. Ahora tenemos la aparición y manifestación del mismo Cristo en el interior,
es decir, la misma virtud, vida y poder que aparecieron en aquel cuerpo de carne,
sin importar lo que los profesantes de este siglo piensen o hablen al respecto.
De hecho, ellos no pasarán como inocentes delante del Señor,
sino profundamente culpables por levantarse contra ella.

Hubo una preciosa aparición de Dios entre aquellos que eran llamados Puritanos,
antes de que hubiera un rompimiento entre ellos al caer en varias
formas de adoración. Entre ellos había gran sinceridad,
amor, ternura y unidad en lo que era verdadero.
Se ocupaban de la obra de Dios en sí mismos y eran sensibles
a la gracia y verdad en los corazones los unos de los otros.
Ahora, era bueno desear conocer la verdadera adoración,
pero los que tenían este deseo no estaban familiarizados con el Espíritu del Señor,
ni esperaron correctamente en Él para ser conducidos por Él a la verdadera adoración,
sino que siguieron las comprensiones e ideas de sus propias mentes sobre las Escrituras.
Ahora bien, si estos hubieran conocido al verdadero Líder,
nunca se habrían extraviado ni habrían sido disgregados del estado Puritano.
Pues si el Espíritu de Dios hubiera sido el Líder de ellos,
¿se habrían alejado de la verdad, de la vida, del amor,
para entrar a un estado estéril y muerto comparado con eso?
Es cierto que en muchos de ellos había sinceridad y sencillez,
pero esa sinceridad y sencillez fueron traicionadas
y atraídas a buscar lo vivo entre lo muerto,
entre formas, costumbres y cultos muertos.

Porque aunque llevaban alguna medida de vida con ellos en sus formas externas,
las formas crecieron gradualmente y la vida y el poder decrecieron,
y fueron absorbidos por una alta estima a sus diversas formas y por disputas sobre ellas.
Pero ellos mismos perdieron lo que eran interiormente para Dios y lo que habían
recibido interiormente de Dios en los días de su celo y ternura anterior.
¡Ojalá pudieran ellos ver esto! ¡Ojalá pudieran regresar a su estado Puritano,
a la consciencia que tenían entonces, al amor y ternura que estaba en ellos,
a la experiencia de la Semilla de vida que sentían y que entonces trabajaba en ellos!
Aunque no la conocían con claridad,
con todo amaban lo que unía sus mentes a Dios y lo que les daba la capacidad de orar,
abrían las Escrituras y las cosas de Dios y calentaban sus corazones en alguna medida.
¡Ojalá estuvieran allí de nuevo! ¡Pronto podrían llegar más lejos.
¡Ojalá conocieran su estado,
tal como es conocido en la luz del Señor y por el Espíritu del Señor!
Que el Señor abra el verdadero ojo en ellos y les dé ver con dicho ojo.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
La cárcel de Reading, día 19, del mes 7, de 1670

[.letter-heading]
A Nathaniel Stonar

[.salutation]
Querido amigo,

Hay una gran disputa entre nosotros y los profesantes acerca de la regla,^
footnote:[Como se mencionó anteriormente,
la palabra __regla__ se usa para referirse a aquello que gobierna,
rige o tiene verdadera autoridad en la vida del creyente.]
la cual dicen ellos, son las Escrituras.
Ahora bien,
desde lo profundo del amor en mi corazón hacia ellos y desde mi deseo de su bien,
yo podría desear realmente que las Escrituras (correctamente
entendidas por ellos) fueran su regla,
y no sus propios razonamientos, ideas y comprensiones sobre las Escrituras.
Pero si así fuera,
tendrían que admitir que el Espíritu de vida (que es la verdad que vive en el corazón,
y la ley escrita por el dedo de Dios en el interior) está más cerca y es más
poderoso que las palabras o descripciones externas de estas cosas en las Escrituras.
En realidad, hay una medida de vida para ser recibida,
el Espíritu de vida para ser recibido; hay un pozo de vida de donde brota la vida pura,
para ser recibida y disfrutada por aquellos que crean verdadera y correctamente.

El Señor, en el estado del evangelio, ha prometido estar presente con Su pueblo,
no como un caminante por una noche,
sino más bien para habitar en ellos y caminar en ellos.
Sí, si ellos son tentados y están en peligro de errar,
oirán una voz detrás de ellos diciendo: "`Este es el camino, andad en él.`" (Isa.
30:21) ¿No admitirán ellos que esto sea una regla así como las Escrituras?
De hecho,
¿no es esta una dirección más completa para el corazón de
la que el hombre pueda escoger para sí mismo de las Escrituras?
Realmente, este testimonio es verdadero,
el cual brota ahora en mi corazón hacia ti y dice:
El Señor ha derramado Su Espíritu sobre sus hijos e hijas,
en y mediante esta preciosa dispensación de la verdad
y de la Semilla pura que es tan despreciada.
El Espíritu que dio las palabras es mayor que las palabras.
Por lo tanto,
no podemos dejar de apreciarlo más y de ponerlo más alto en nuestros
corazones y pensamientos que las palabras que testifican de Él,
aunque las palabras también sean muy dulces y preciosas a nuestro paladar.

Había una medida y una regla a las que habían llegado los
verdaderos ministros de Cristo y los gentiles creyentes,
y por las que debían caminar.
Véase 2 Corintios 10:13,15 "`...sino conforme a la regla que Dios
nos ha dado por medida,`" y "`...conforme a nuestra regla.`"
Filipenses 3:16, "`Pero en aquello a que hemos llegado, sigamos una misma regla,
sintamos una misma cosa.`"
Gálatas 6:15-16, "`Porque en Cristo Jesús, ni la circuncisión vale nada,
ni la incircuncisión, sino una nueva criatura, y todos los que andan según esta regla,
la paz sea con ellos y la misericordia.`"
Ahora considera qué era esa regla.
¡Ojalá que la conozcas y camines por ella,
como lo hicieron los que habían recibido el Espíritu de Dios!
Porque estoy seguro en mi corazón de que si tú recibes
el Espíritu de Dios y vives y caminas en eso,
no podrás satisfacer los deseos de la carne,
sino que encontrarás tu corazón abierto a un verdadero sentido,
entendimiento y uso correcto de las Escrituras.
Porque las Escrituras del Nuevo Testamento fueron escritas a los santos de antaño,
y por lo tanto, no pueden ser verdadera o correctamente entendidas o usadas,
excepto cuando los hombres entren en su espíritu y estado.

Estas cosas son de gran peso e importancia.
Que el Señor abra y guíe tu corazón a una verdadera
satisfacción en esto y en otras cosas también,
desde la manifestación de Su propio Espíritu.
Entonces serás verdaderamente capaz de decir como en Su presencia:
"`Ahora creo y entiendo las cosas, no porque este o aquel hombre lo hayan dicho,
sino porque el Señor, que es el Maestro en verdad,
ha enseñado y asegurado mi corazón concerniente a la verdad misma, como es en Jesús,
la cual siento que es cierta por Su virtud viva y poderosa operación en y sobre mi corazón.`"

Este es mi deseo por ti,
que soy un verdadero y sincero amigo de tu alma y
que de ninguna manera desea que seas engañado.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
La cárcel de Reading, día 24, del mes 7, de 1670

[.letter-heading]
A la Viuda Hemmings

[.salutation]
Querida amiga,

Desde la última vez que te vi,
he tenido muchos pensamientos profundos y serios en mi corazón acerca de ti,
un sentido de tu estado ante el Señor y anhelos de corazón para ti.
Soy consciente de que el Espíritu del Señor está luchando contigo, y en cierta medida,
abriendo tu corazón hacia Él y a Su verdad.
Siento que hay una gran lucha contra Él y muchas
fortalezas de sabiduría y razonamientos en ti,
los cuales deben ser derribados antes de que la Verdad pueda surgir en tu corazón,
ejercer Su poder en ti y tener pleno dominio en ti.

Esta mañana cuando desperté tres cosas surgieron en mí,
las cuales fervientemente deseé en mi corazón para ti.
Una era, que pudieras ser guiada por el Espíritu Santo de Dios al pacto nuevo y vivo,
donde Cristo es revelado y el alma es unida a Él como su Señor y Rey,
en un vínculo de unión indisoluble.
La segunda era,
que cada día pudieras ser enseñada por Dios y aprendieras de Él en este pacto santo,
nuevo, puro y eterno.
Y la tercera, que pudieras ser leal y fiel a Dios,
para obedecerlo y seguirlo en todo lo que Él te enseñe y requiera de ti.

Si estuvieras en este estado, encontrarías dulzura y descanso, paz y poder,
la justicia de nuestro Señor Jesucristo y la vida eterna reveladas en tu propio corazón,
y con gozo sacarías agua de los pozos de la salvación.

Ahora bien,
si llegas a experimentar la aparición de Cristo en
espíritu y estás dispuesta a convertirte en Su discípula,
hay tres cosas en las que tu corazón debe aplicarse
para aprender de Él. Estas tres cosas son,
efectivamente, la suma del evangelio o de lo que es enseñado en y por el evangelio.

La primera es: Temer a Dios.
Este es el principio de la verdadera sabiduría celestial,
así como la perfección y el fin de la misma.
Porque la verdadera sabiduría no sólo introduce en el temor del Señor,
sino que edifica en el temor, e incluso, perfecciona en el temor; como dice el apóstol:
"`Perfeccionando la santidad en el temor del Señor.`" Ahora,
este no es el temor que el hombre puede alcanzar por medio de lo que haga, sino más bien,
el temor del nuevo pacto que Dios pone en el corazón de sus hijos
a medida que los aviva y los lleva hasta dicho pacto.
Este es tal temor, que aquellos en quienes se coloca no pueden apartarse del Señor,
ni aquellos que permanecen en él pueden equivocar el camino de la vida y de la santidad.
Porque todo pecado y transgresión,
toda rebelión contra el Señor y aflicción y entristecimiento
de Su Espíritu están fuera de este temor.
¡Oh, qué puedas recibir este temor del Señor y crecer todos los días en él!

La segunda (que depende y fluye de la anterior) es:
Darle gloria a Dios al discernir Su vida y poder,
y al experimentar la virtud de Su Espíritu y Su gracia obrando todas las cosas en ti.
De esta manera, toda la gloria se le atribuye a Él en todo lo que eres,
haces o puedes hacer.
Pues en el día del Evangelio ninguna carne puede
gloriarse ante la presencia de nuestro Dios,
porque solo el Señor es exaltado en los espíritus de Sus hijos en ese día. En efecto,
cuando cada uno entra en el temor del nuevo pacto la presencia del Señor está allí,
habitando en medio del corazón, Dios se encuentra trabajando en todas las cosas,
produciendo la Semilla de vida y abatiendo el pecado,
la muerte y la corrupción. Los que están aquí experimentan
su propia pobreza y nadedad en sí mismos,
y ven que la manera de llegar a ser fuertes en Cristo
es siendo débiles en sí mismos primero,
y así cuando son fuertes en Él, el que es la fuerza de ellos es glorificado y admirado,
y el yo no tiene reputación o valor por los siglos de los siglos.

La tercera es: Que aprendas a adorar a Dios en espíritu y en verdad.
¡Oh, esta adoración es verdaderamente preciosa!
Este es el único tipo de adoración que Dios busca y considera entre los
muchos tipos de adoradores que aparecen en este día. Esta adoración fue
declarada por Cristo y enseñada por Sus discípulos,
pero ha sido en gran medida abandonada.
Muchos la han buscado, sin embargo, nadie ha podido encontrarla nunca,
excepto cuando hayan aprendido del Padre a regresar a la unción,
y así ser reunidos en Su Espíritu donde el nombre de Cristo es conocido.
Y en verdad, nadie sabe ni puede adorar en el nombre de Cristo aparte de esto.

Ha habido grandes errores acerca de la adoración y de las reuniones.
Estas no han sido en el nombre ni en el poder de nuestro Señor Jesucristo,
sino solo en una profesión externa de Su nombre y en una
imitación de cosas sin la verdadera vida y poder.
Pero, ¿qué es esa adoración y religión ante los ojos del Señor?

Para que puedas entrar en este estado y aprender
todas estas lecciones del Señor en el nuevo pacto,
hay una cosa indispensable para ti:
Conocer la hora del juicio de Dios en tu propio corazón y postrarte bajo dicho juicio.
Amiga,
cuida las palabras que brotan ahora de mi corazón para ti (pues mi corazón está
abierto para ti en el verdadero amor y en el sentido puro que es de Dios).
Si llegas a conocer al Espíritu de Dios, lo recibes y lo sientes obrar en ti,
y Su luz pura resplandece desde la fuente de la vida,
tendrás un sentido y discernimiento más rápidos que los
que surgen de las palabras escritas o de los pensamientos.
El Señor te mostrará el camino más rápidamente de lo que
puede hacerlo un pensamiento que surja en ti.
El Señor te mostrará el mal, en el sentido puro de la nueva naturaleza,
más rápidamente de lo que te toma pensar o considerar cualquier cosa.
¡Esto es en verdad necesario!
Porque el pecado se aloja internamente en la naturaleza maligna y obra,
no tanto por una ley conocida colocada en la mente, sino mediante una naturaleza secreta.
Y si esa naturaleza no es encarada y resistida por otra naturaleza,
nunca podrá ser vencida.
Porque es por Su juicio establecido en el corazón
que Dios vence y somete el pecado para siempre,
pues el juicio de Dios es más fuerte que el pecado
y lo derribará en el momento que se reciba Su juicio.
Al ser sometido, la vida y la justicia, es decir, la vida justa,
Espíritu y poder del Señor Jesús internamente revelados,
serán los más prominentes y reinarán sobre el pecado.
Entonces sabrás lo que es ser rey y sacerdote para Dios
e ir a la fuente donde se lavan los sacerdotes de Dios,
y a la sangre rociada en tu oreja derecha, pulgar y dedo del pie,
de acuerdo al tipo y sombra bajo la ley.

Puede que estas palabras sean difíciles para ti en el presente,
pero si llegas a esperar en el Espíritu Santo de Dios,
experimentas Su aparición en tu corazón,
aprendes de Él a conocer lo que es bueno y malo en tus palabras, caminos, adoración, sí,
y en tu propio corazón y pensamientos,
y también aprendes a escoger el bien y a rechazar el mal,
ellas llegarán a ser cada vez más fáciles y claras.
Encontrarás que Cristo (interiormente revelado en espíritu)
es muy apropiadamente llamado la Palabra de Dios,
es decir, la palabra injertada que es capaz de salvar el alma.
Porque Él es rápido y poderoso, y más cortante que cualquier espada de dos filos,
capaz de cortar todo lo que aparezca o se levante
en el corazón para resistir u oponerse a Su obra.

Esto es de uno que deambuló mucho en el vasto desierto,
a la deriva del Pastor y Obispo del alma.
Yo estaba muy afligido, agitado por las tempestades y desconsolado.
Pero al fin, en tierna misericordia,
le plació al Señor visitarme y mediante Su brazo extendido unirme a Su
propio rebaño. Aquí me he encontrado con el monte santo de Dios y Su ciudad,
la Jerusalén celestial, y con los espíritus de los justos,
y con Dios el juez de todo lo que surge en el corazón. He hallado a Cristo el mediador,
y el nuevo pacto, en el cual y por el cual intercede,
y la sangre rociada que les habla cosas buenas a las almas que son rociadas con ella.
Sí, de hecho, aquí están todas las buenas cosas reunidas y disfrutadas,
que fueron dadas en sombra bajo la ley.
Y aquí están las preciosas promesas cumplidas,
que nos hacen partícipes de la naturaleza divina.

¿Qué diré? El Señor sabe que no hablo estas cosas con jactancia,
o para elevarme sobre otros en mis pensamientos,
sino más bien en ternura y humildad de corazón, como delante del Señor, por tu bien.
Y ahora,
este es mi deseo y mi oración al Señor y el trabajo
ferviente de mi alma en Su vida y espíritu:
Que los que aún están dispersos del resto del redil; es decir,
que el resto de las ovejas de la casa de Israel que todavía están
perdidas y dispersas arriba y abajo en sus propias comprensiones,
concepciones, diversas reuniones, formas de adoración,
semejanzas e imitaciones de las cosas sin la verdadera vida y poder,
no se reúnan en todo eso, sino en la misma vida, poder y reposo,
en lo cual Dios se ha complacido en Su gran misericordia reunirnos.

¡Qué el Señor te dé la consciencia y el sabor de estas cosas,
para que así puedas animarte para esperar en el Señor y ser introducida
a la luz de los vivos! ¡Qué vivas y camines con Él,
quien es, habita y camina con los Suyos en la luz! ¡Oh, casa de Jacob, ven ahora,
andemos en la luz del Señor y subamos a Sión,
el monte santo de Dios y a la nueva Jerusalén,
para que Él nos enseñe de Sus caminos y aprendamos allí de Él a caminar en Sus sendas!
Porque, ciertamente,
este es el lugar de la sabiduría y del verdadero entendimiento
que nadie conoce sino los que son enseñados por Dios.

Te escribo en la verdadera amistad y tierno amor hacia tu alma,
de su amigo en verdad y sinceridad,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 26, del mes 8, de 1670

[.letter-heading]
A un Destinatario Desconocido

[.salutation]
Amigo,

Los profesantes del cristianismo conocen desde hace mucho tiempo
el nombre de Cristo y lo que la Escritura relata sobre Él,
¡pero si pudieran conocer a Cristo mismo, y lo recibieran en sus vasijas,
y sintieran la vida de Él fluyendo hacia ellos!
Entonces, verdaderamente conocerían a Cristo según el Espíritu,
cuyo conocimiento da vida, pero el conocimiento literal mata.
Porque el que tiene al Hijo,
el que está en verdadera unión con Él y verdaderamente transformado por Él,
de manera que llega a ser una sola naturaleza y espíritu con Él, este tiene vida.
Pero el que no tiene al Hijo no tiene la vida del Hijo, ni la libertad del Hijo,
sino que está en la muerte del pecado y a servicio del pecado.

Las instrucciones del Espíritu Santo de Dios en las Escrituras
son sumamente importantes y preciosas en sí mismas,
y bendito el que es hallado en la práctica y observación de ellas.
El deseo de mi corazón desde mi niñez ha sido, y todavía lo es,
ser hallado caminando con el Señor según lo que allí
se enseña y se prescribe a los hijos de Dios,
en las varias edades y generaciones precedentes.
Estas cosas fueron escritas y son útiles para nuestra instrucción también,
al ser leídas por nosotros y atendidas en la luz
que da el verdadero entendimiento de ellas.

No obstante, a pesar de que este era mi deseo, perdí el camino para alcanzarlo,
pues yo pensaba que por tener las instrucciones de la Escritura en mi mente,
aplicarme a la estricta observación de ellas, orar por el Espíritu de Dios y por ayuda,
podía obtener lo que deseaba.
En verdad el Señor fue misericordioso conmigo y me ayudó en gran medida,
pero a menudo sentía las tentaciones y las tinieblas del enemigo más cerca
de mí que las Escrituras y en muchos casos no sabía qué hacer,
ni cómo resolver esto con ellas.

Por fin el Señor me afligió mucho y me llevó a una consciencia
más plena de mi falta de su Espíritu y poder.
Él rompió toda mi religión en pedazos para que yo fuera como Babilonia,
porque en una hora el juicio y la desolación vinieron sobre
mí. Apocalipsis 18:10. No sabía qué hacer sin el Señor,
ni de qué manera acercarme a Él. Pero el Señor me
estaba preparando para ese día de misericordia,
el cual desde Su tierna bondad ha despuntado sobre mí.

Ahora el ojo que Él ha abierto en mí ve que el evangelio es un
ministerio del Espíritu y del poder del Señor Jesucristo.
Veo que la persona que desea ser Su discípulo debe volverse a Su Espíritu
y recibir la luz directa y el resplandor de Su Espíritu en su vasija.
Debe experimentar la ley de la vida, la ley santa del nuevo pacto,
y no comprenderla externamente en la mente,
sino escrita internamente en su corazón por el dedo del Espíritu de Dios.
Al estar escrita en su corazón,
esta ley tiene poder sobre el corazón y hace que la persona obedezca.
Aquí no puede dejar de cumplir las santas direcciones de las Escrituras,
porque dicha persona permanece en aquello de donde las Escrituras vinieron y
en lo que le revela la sustancia de ellas y las hace vivas y poderosas en ella.
Porque de hecho,
la ley del pecado y de la muerte tiene poder sobre el hombre mientras vive,
pero cuando este se encuentra con lo que mata el
pecado y la muerte en él y lo vivifica para Dios,
recibe vida en abundancia en y por medio del Señor Jesucristo.
Entonces los frutos de la vida se vuelven fáciles y naturales para él,
y los frutos y los caminos del pecado,
la incredulidad y la desobediencia se vuelven antinaturales.

Aquí el yugo es fácil y ligera la carga,
y ninguno de los mandamientos de nuestro Señor Jesucristo es gravoso.
Pero cuando los mandamientos son simplemente tomados de
la letra y no se experimenta al Espíritu conduciendo,
vivificando y habilitando el cumplimiento de ellos, ¡cuán pesados,
cuán duros son! ¡Cuán imposible creer correctamente, esperar correctamente,
orar correctamente, caminar correctamente, vigilar correctamente sobre el corazón,
luchar contra los enemigos, las lujurias y las corrupciones correctamente!
Por otra parte, ¡cuán agradable es el camino de vida en el pacto de vida,
en el poder y virtud de la vida, cuando es ministrado desde el Espíritu de nuestro Dios!
Aquí Dios es alabado,
la victoria sobre Sus enemigos experimentada y la
paz con Él disfrutada en la Semilla pura de la vida.
¡Bendito sea el nombre de nuestro Dios para siempre!
Porque la letra o la descripción de las cosas no es el camino; pero la vida es el camino,
el Espíritu es el camino, el poder es el camino,
la verdad como está en Jesús es el camino,
la que nadie puede conocer verdadera y correctamente,
excepto cuando son injertados y formados en Él y Él formado en ellos.
Esto sólo se obtiene, se experimenta y se conserva en la unión,
comunión y obediencia del alma al Espíritu de Dios
y poder interiormente revelados y manifestados.

Esto lo escribo en la desnudez de mi corazón,
como a la vista del Señor y en la verdad de la amistad hacia ti.

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 27, del mes 9, de 1670

[.letter-heading]
Para la Viuda Hemmings

[.salutation]
Amiga,

En la medida que uno llega a alguna experiencia o
toque de la verdad del Espíritu Santo de Dios,
las dudas y los escrúpulos con respecto a la oración pueden muy bien surgir en la mente,
ya que este deber ha sido realizado y practicado
por mucho tiempo desde la mente y naturaleza carnal,
y no en la guía, voluntad y extensión del Espíritu Santo y poder de Dios.
Los que dudan en este asunto no estarán satisfechos hasta
que el Señor abra sus espíritus y se los manifieste a ellos.
Sin embargo, esto es más cierto: Toda oración,
toda verdadera oración a Dios es en Su Espíritu Santo y desde Su Espíritu Santo,
y la que es de otra manera no es aceptada por el Padre.
De hecho, la promesa es para la oración en fe y para la oración en el Espíritu Santo,
no para la oración del nacimiento, voluntad o sabiduría carnal.
Por lo tanto, la gran preocupación en la oración debe ser,
que lo que es de Dios ore al Padre en las vivificaciones
y movimientos de Su propio Espíritu,
porque los muertos no pueden alabar a Dios, ni pueden realmente orar a Dios.

Ahora bien, al abstenerse de la oración no puede haber paz,
porque estamos destinados a orar continuamente.
Tampoco se hallará paz orando de manera formal, sin vida, es decir,
sin el Espíritu de Dios (que da la capacidad de orar y hace la intercesión).
Porque es manifiesto que la oración no está en el tiempo,
voluntad o poder de la criatura, pues es un don de Dios,
y la habilidad se aloja en Su Espíritu.
La oración no está en nosotros, a menos que sea dada por Su Espíritu, en el cual,
por tanto, se debe esperar hasta que se mueva y sople en nosotros,
y nos dé la capacidad de invocar al Padre en el nombre del Hijo y a través de Su vida.

Ahora en cuanto a tus preguntas,
contestaré con claridad en la medida que el Señor se complazca en abrir mi corazón.

En cuanto a la primera:
Cuando la criatura encuentra respiraciones de anhelo hacia el Padre
que provienen de una verdadera consciencia de sus necesidades,
éstas no deben ser detenidas, sino que deben ser ofrecidas en aquello de donde vinieron.
Porque no hay verdadera consciencia de la condición de uno, o de las necesidades de uno,
a menos que esta provenga del Espíritu del Señor. Es el Señor quien da esta consciencia,
para que el alma sienta su necesidad de Él y clame a Él. Todos los suspiros
y gemidos que se le ofrecen de esta manera son aceptados por Él,
y prevalecen con Él para bien hacia esa alma.

Ahora, el alma debe orar en particular por la aparición del Espíritu y poder de Dios.
Y si dicha alma ya ha saboreado algo de ella,
debe orar por más del Espíritu y que pueda distinguir
las peticiones que se levantan en el corazón,
si provienen del Espíritu Santo y la voluntad de Dios,
o de la naturaleza y voluntad carnal.
Porque el nacimiento equivocado también desea el reino, y aspira poseer el reino,
orar por el reino y luchar por el reino, pero ora mal y se esfuerza mal,
y así nunca lo conseguirá, porque el reino está designado y dado a otro.

En cuanto a la segunda: Aquellos que no conocen ni son partícipes sensibles del Espíritu,
y sin embargo, sienten su falta del Mismo y deseos verdaderos tras Él,
deben ofrecer esos deseos a Dios.
Y si se mantienen hacia lo que engendra esos deseos,
no serán por mucho tiempo ignorantes del Espíritu de Dios,
sino que encontrarán que Dios está más dispuesto a darlo,
que la disposición que tiene un padre de darles las cosas necesarias a sus hijos.
Pero en cuanto a aquellos que han orado por mucho
tiempo por el Espíritu y aún no lo han recibido,
tienen justa causa para cuestionar la naturaleza y el fundamento de sus oraciones,
ya que Dios está muy dispuesto a dar el Espíritu a Sus hijos.
Porque, ¿pide un niño pan a su padre durante muchos años y no lo recibe?
¡Oh, considera esto!
Si el niño pide el Espíritu de manera correcta,
es imposible que no reciba una medida de Él procedente del Padre,
tanto como sea necesario para su estado actual.
Dios requiere que Sus hijos realicen todo para Él en y con Su Espíritu,
sabiendo que no pueden hacer nada correcto sin Él. Dios ciertamente
no requerirá deberes de ellos mientras retenga al Espíritu,
sin el cual no pueden realizar aceptablemente dichos deberes.

En cuanto a la tercera:
El mero entendimiento de que todas las necesidades del alma
provienen del Padre no es motivo suficiente de oración,
porque el nacimiento incorrecto puede orar, y a menudo lo hace, con tal entendimiento.
Más bien,
es la verdadera consciencia de dichas necesidades
lo que se constituye en fundamento suficiente,
si el corazón y la mente se mantienen dentro de los límites de
la consciencia y no ofrecen más de lo que surge allí. ¡Oh,
qué todo aquel que tiene una verdadera experiencia de Dios
lo espere para saborear esa pequeña cosa que surge de Él,
de entre la multitud de sus propios pensamientos,
palabras y deseos que provienen de otra raíz, es decir, de la carne,
la cual no es de valor ni de provecho para con el Señor. Mas el nacimiento de vida,
las respiraciones reales de Su propia vida en el niño más pobre y débil,
siempre son de estima y prevalecen con el Padre!

En cuanto a la cuarta: Es cierto que la oración es de Dios y es un deber.
Aunque no toda oración es así,
sino sólo aquella que está dentro de los límites del verdadero Espíritu y poder:
"`orando siempre en el Espíritu Santo.`"
La oración pura, las respiraciones puras del hijo de Dios, las del verdadero nacimiento,
siempre están dentro del límite que Dios ha prescrito.
Por lo tanto,
"`velad en oración,`" vela en la preparación que hace Dios del
corazón por medio del movimiento y la virtud de Su buen Espíritu,
y ofrece las respiraciones que entonces se levantan.
Espera para distinguir entre los deseos que surgen de la parte
carnal y los deseos que surgen de la parte espiritual y celestial.
Porque la primera naturaleza es terrenal,
pero la segunda naturaleza (la naturaleza que es del segundo Adán,
el Espíritu vivificante) es pura y celestial,
y así son todos los deseos y respiraciones que brotan de esa naturaleza en la vasija.
Conforme entres en la naturaleza y en el Espíritu del que procede la naturaleza,
verdaderamente distinguirás lo referente a la oración, a la fe,
al amor y a todas las demás cosas espirituales,
y conocerás Al que es verdad y no mentira, y preserva de todo error y engaño.

Parece que también estás preocupada por algunos otros
deberes además de la oración. Ciertamente,
toda carne debe estar en silencio delante de Él. Desgraciadamente,
¿qué espacio hay para Su Espíritu y poder cuando hay tal cantidad de pensamientos,
obras y razonamientos, y tal ruido de carne en muchos corazones y espíritus?
¡Bienaventurado el que experimenta su carne en silencio y que llega
a un fin de su propia voluntad y de su propio correr!

¡Qué el Señor levante en ti lo que es de Él,
y así guíe y ordene tu corazón para que puedas respirar y clamar en pos de Él,
y ser escuchada y satisfecha por Él!

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 28, del mes 9, de 1670

[.letter-heading]
A Elizabeth Stonar

[.salutation]
Querida amiga,

Soy consciente de que el Señor te ha visitado con Su poder,
alcanzando tu corazón en la demostración de Su propio Espíritu,
y que tu corazón ha respondido y dicho: "`Ciertamente esta es la verdad de Dios.`"
Ahora, en la misma medida que Dios te ha alcanzado, así te corresponde confesarlo a Él,
confesar Su verdad y a Su pueblo delante de los hombres
y rendirte en obediencia y sujeción de espíritu al Señor.

¡Qué el Señor te guíe, te compadezca y te ayude en tus dificultades, dudas y temores,
tanto en lo referente a ti misma como en lo referente a tu madre!
Dios es mi testigo, a quien sirvo en mi espíritu en el evangelio de su Hijo,
que lo único que he procurado ha sido tu bien, y esto no de mí mismo tampoco,
sino en la guía y persuasión de Su Espíritu Santo.
Yo le hice a tu esposo una advertencia en amor verdadero y tierno,
aunque sabía muy bien que sería muy difícil para su espíritu en su estado actual,
y que por decirle la verdad,
cuán grande enemigo podría llegar a ser él contra mí. Yo no lo hice imprudentemente,
sino con pesadez de espíritu delante del Señor,
y deseo sinceramente que él no se engañe en su corazón con respecto a su propio estado,
sino que verdaderamente lo conozca tal como es.

Hay una luz, la cual ilumina el alma, o de otro modo, esta permanece en tinieblas.
"`Ustedes eran tinieblas,`" dijo el apóstol,
"`pero ahora son luz en el Señor.`" Ahora bien,
ningún hombre puede llegar a ser luz en el Señor a menos que su naturaleza
y espíritu sean renovados y transformados de tinieblas a luz.
Ahora la pregunta es, ¿qué es esta luz y dónde se encuentra?
¿Son las Escrituras esta luz, o dan testimonio de esta luz?
Si ellas solo dan testimonio de esta luz,
entonces la luz misma debe venir y el alma debe ser iluminada por ella.
El que viene a esta luz, es iluminado por ella y camina en su brillo puro,
se convierte en un hijo de la luz.
Pero el que no es iluminado ni cambiado por ella, es todavía un hijo de las tinieblas,
sin importar lo que aprenda, profese o practique imitando las Escrituras.
Esto es importante.

¡Oh, ven y no te apegues a tus propios caminos,
ni tengas prejuicios contra lo que Dios le ha enseñado a los demás!
Sino deja que las cosas sean examinadas equitativamente,
para que todas las cosas sean probadas y lo que es bueno se mantenga firme.
Porque la verdad nunca perderá terreno al ser juzgada,
pero las tinieblas tienen miedo de la luz,
porque tienen una consciencia secreta de que no puede permanecer delante de ella.

[.signed-section-closing]
De tu verdadero y sincero amigo de tu alma,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 16, del mes 12, de 1670

[.letter-heading]
A un Destinatario Desconocido

[.salutation]
Amigo,

El enemigo enciende una gran angustia en la mente al despertar
un deseo fervoroso y una sensación de aparente necesidad de saber.
Pues se levantan pensamientos como: "`¿Qué haré para saber si esto es de Dios o no?
Porque si es de Dios, debe obedecerse, y si no es de Dios, debe resistirse.
Pero, ¿qué haré si no puedo discernir qué es?
Necesariamente caeré en la desobediencia al Espíritu de Dios,
o en las trampas del enemigo.`"
De esta manera,
el enemigo levanta pensamientos en la parte racional que son irrefutables allí. Pero,
¿qué si fuera mejor para usted en estos momentos estar a oscuras sobre estas cosas?
¿Puede ser eso posible?
Sí puede serlo, en muchos aspectos.
Porque hay algo más que se puede levantar y actuar
en usted si le fuera dado conocimiento claro y celestial.
Porque incluso lo que usted recibe de Dios puede ser centrado en el yo.
De este modo,
usted puede perder el camino del conocimiento verdadero
y nunca aprender a estar satisfecho en cada estado,
ni a conocer el camino puro y los movimientos de la vida.

En realidad, este no es el camino del conocimiento del hijo.
En su lugar, el hijo conoce en rendición y sujeción de su propio conocimiento.
Y si apareciera una necesidad muy grande de conocimiento, y sin embargo,
el conocimiento no le fuera dado,
entonces esta se hundirá en temor y humildad en la voluntad de la Semilla pura.
Allí brota algo (desconocido para la sabiduría natural ni a la manera
de la sabiduría del hombre) que preserva y sostiene al hijo en tal estado.
Este es un gran misterio, sin embargo,
es perceptiblemente experimentado por los verdaderos viajeros en este día.

Por tanto,
retírese de todas las necesidades que son acorde a la comprensión de la mente racional,
y juzgue necesario sólo lo que Dios le entrega en Su sabiduría eterna y amor.
Cuando usted llegue a esto, llegará a su descanso, y mientras permanezca ahí,
permanecerá en el verdadero descanso de su alma y aprenderá
la preciosa lección de estar contento en cada estado.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
A un Destinatario Desconocido

[.salutation]
Amigo,

¿Qué es Pablo?
¿Qué es Apolos?
¿Qué es Cefas?
Es una y la misma vida pura y palabra de poder que brota en todos los hermanos santos,
a quienes Dios ha santificado y preparado para dar el sonido de su santa trompeta.
Es el mismo Señor quien da el sonido verdadero y cierto,
y grande es la compañía de aquellos a quienes Él
ha escogido y enviado para darlo a conocer.
Estos no pueden ser despreciados en su mensaje sin despreciar Al que los envió.

¡Oh, tenga cuidado de esa naturaleza y espíritu en usted que desea y busca una señal!
Es la generación malvada y adúltera la que busca una señal. Pero usted,
espere encontrarse con Él internamente,
con quien cambia el corazón y renueva la mente para Dios.
Conozca a Aquel que enseña a amar al Señor Dios con todo el corazón, alma,
mente y espíritu,
para que la verdadera vida que viene de Él y está en Él sea experimentada.

Ahora, en cuanto a ser como uno de nosotros, usted debe ser formado por el Señor,
siendo interiormente cambiado y renovado por el Espíritu y el poder del Señor,
antes de que pueda experimentar verdadera unidad con nosotros.
Si siente la Semilla de verdad en su propio corazón,
y en esa Semilla nos conoce y nos reconoce,
y así viene entre nosotros y se une a nosotros en la verdad,
y se mantiene fiel a la Semilla, nunca estará en peligro de dejarnos.
Pero los que se apartan de la Semilla en sus propios
corazones se apartarán de nosotros pronto y fácilmente.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
A un Destinatario Desconocido

[.salutation]
Amigo,

Escuche una palabra de consejo que tengo en mi corazón para usted,
porque puede serle de gran utilidad, si el Señor abre su espíritu y hace que se absorba.
Es la siguiente:

Espere en el Señor, para que pueda sentir de Él el límite correcto para la mente,
al leer las Escrituras.
Pues la mente del hombre está ocupada y activa,
dispuesta a correr más allá de sus límites,
adivinando los significados del Espíritu de Dios e imaginando por sí misma,
a menos que el Señor la limite.
Por tanto,
lea con temor y espere para que pueda distinguir entre las cosas del reino
que Dios le revela y sus propias comprensiones acerca de ellas.
Porque las primeras deben ser siempre abrazadas por usted,
y las segundas deben ser siempre desechadas.
Espere siempre el tiempo de Dios.
No presuma entender una cosa antes que Él le dé la comprensión de ella.
Sólo Él es capaz de preservar el verdadero sentido y conocimiento en usted,
y usted debe aprender a vivir dependiendo de Él para su
conocimiento y nunca se "`apoye en su propia prudencia.`"
Poco sabe usted lo que nos ha costado tener nuestra propia comprensión y sabiduría derribadas,
y cuán manifiestamente (mediante este Espíritu) nos abre el Señor las Escrituras (sí,
las cosas mismas de las que hablan las Escrituras),
desde que Él nos enseñó a negar nuestro propio entendimiento
y a apoyarnos en Su Espíritu y sabiduría.

El Señor lo guíe mediante Su Espíritu seguro e infalible, en el camino de vida, seguro,
infalible y eterno, para que por el resplandor de Su luz, Espíritu y poder en usted,
pueda ver la luz y gozar de vida.
Porque aun si comprendiera todas las palabras,
descripciones y testimonios de las Escrituras, una cosa es entender las palabras,
los testimonios y las descripciones, y otra cosa es entender, conocer, gozar,
poseer y vivir en lo que las palabras describen y de lo que dan testimonio.

Y amigo, si usted quiere ser un judío interno,
y conocer y comprender las leyes de la vida, las leyes del nuevo pacto,
deberá leerlas en las tablas donde Dios las escribe bajo el nuevo pacto.
De hecho, al leer en la letra,
usted puede leer los testimonios concernientes al Espíritu y a Su ministerio,
pero deberá leer en el Espíritu,
si desea llegar a entender alguna vez la letra correctamente.
El fin de las palabras es llevar a los hombres al conocimiento
de las cosas más allá de lo que las palabras pueden expresar.
Por tanto, aprenda del Señor a hacer un uso correcto de las Escrituras, el cual es,
estimándolas en su lugar y apreciando por encima
de ellas lo que está por encima de ellas.
La "`vida eterna,`" el Espíritu, el poder, la fuente de aguas vivas,
el pozo eterno y puro, están por encima de las palabras concerniente a ello.
El creyente debe experimentar esto en sí mismo, y de esto, él sacará agua con gozo.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
Para el Amigo de Francis Fines

[.salutation]
Amigo,

Después de un profundo ejercicio de espíritu con respecto a usted,
y bajo un gran dolor de corazón por usted, sentí una obligación de amor,
forzándome a poner frente a usted las siguientes consideraciones de mi parte.

Me siento satisfecho en el Espíritu de Dios,
que lo que le escribí en la última carta que le envié es la suma y sustancia de la verdadera
religión. La suma y la sustancia no se basan en tener una noción de la justicia de Cristo,
sino en experimentar el poder de la vida eterna,
recibirlo y ser cambiado por él. Donde está Cristo, está Su justicia.
El que tiene al Hijo tiene vida y justicia,
pero el que no tiene al Hijo no tiene vida ni justicia.
Donde no está Cristo no está Su justicia,
sino únicamente una noción de ella proveniente de las comprensiones formadas
por la sabiduría del hombre (la sabiduría que debe ser destruida),
a partir de las Escrituras.
Mi deseo es que su conocimiento, su posición, su fe, no estén ahí,
sino más bien en la verdad y en la vida misma.

Cristo fue ungido y enviado por Dios como Salvador, para destruir las obras del diablo,
para derribar toda regla y autoridad contrarias a Dios en el hombre;
porque Su obra es en el corazón. Allí Él vivifica, allí Él se levanta,
allí Él lleva a la muerte lo que tiene que morir al levantar la Semilla inmortal,
y al traer a la criatura a sujeción a Ella.
Ahora, experimentar el poder que hace esto, y experimentar esto forjado por ese poder,
va mucho más allá de toda conversación sobre justificación y justicia.
Aquí deseo que usted llegue, fuera de la conversación, fuera del conocimiento externo,
que entre a la cosa misma y a la verdad del conocimiento nuevo y vivo.

Hay un poder en Cristo para hacer morir y vencer
el pecado desde la misma raíz. Sin embargo,
no es vencido, excepto en la revelación de este poder.
El alma no es justificada, excepto en y por la obra de este poder.
Por lo tanto, la justificación no es la primera cosa,
sino el poder de vida revelado en Cristo,
en y por medio del cual el alma es tanto justificada como
santificada mediante la obra de la fe que proviene del poder.
Aquí la salvación es sentida cerca por los que verdaderamente temen al Señor,
y la gloria habita en la tierra que Él ha redimido.
Ahí la misericordia y la verdad se encuentran, y la justicia y la paz se besan.
Sí, ahí la verdad brota de la tierra y la justicia mira desde el cielo.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
A la Señora Conway

[.salutation]
Querida amiga,

Mientras recientemente estaba retirado en espíritu y esperando en el Señor,
teniendo un sentimiento sobre mí de su larga, dolorosa y profunda aflicción y angustia,
surgió una escritura en mi corazón que pongo delante de usted, a saber, Hebreos 12:
5-7. Le ruego que pida una Biblia y oiga la lectura, antes de proceder a lo que sigue.

Oh, amiga mía, le ha placido al Señor en Su tierna misericordia,
visitarnos y volver nuestras mentes del mundo y de nosotros mismos hacia Él,
y engendrar y nutrir lo que es puro y vivo de Sí mismo en nosotros.
Sin embargo,
al principio permanece algo (y quizás por mucho tiempo)
que debe ser escudriñado por la luz del Señor,
y derribado y sometido por Su mano que disciplina.
Porque cuando, efectivamente,
algo de la santa voluntad es formado en el día de poder de Dios,
y el alma (en alguna medida) es engendrada y llevada
a vivir para Dios en la sabiduría celestial,
aún así no es eliminada inmediatamente toda la voluntad y la sabiduría terrenal.
De hecho, hay cosas ocultas de la vieja naturaleza y espíritu que aún permanecen,
cosas que no son visibles, tal vez porque se hunden en su raíz para poder salvar su vida.
El hombre no puede descubrir tales cosas en su propio corazón,
sino hasta que el Señor se las revela.
Pero, ¿cómo las descubre el Señor? Oh, considere,
que Su "`fuego está en Sión y su horno en Jerusalén.`" Al arrojarnos al
horno de aflicción el fuego nos escudriña. Las aflicciones profundas,
dolorosas y angustiosas que desgarran y rompen las partes muy internas,
dejan al descubierto tanto la semilla como la paja,
de modo que el oro puede ser purificado y la escoria consumida.
Luego, por fin,
el estado de quietud es experimentado y el fruto apacible de justicia es producido
por la naturaleza escrutadora y consumidora y la operación del fuego.

¡Oh,
qué su alma sea probada para victoria sobre todo lo que no es de la vida pura en usted!
¡Espere sentir la Semilla pura (o la medida de vida en usted) y muera en ella experimentando
la muerte a todo lo que no es de la Semilla en usted! ¡Oh,
si usted pudiera experimentar la vida, la sanidad, el refrigerio,
el sostén y el consuelo de Dios para su vida en la Semilla,
y en ningún otro lugar! ¡Qué el Señor la guíe todos
los días y mantenga su mente hacia Él,
mirando hacia el lugar santo donde surge Su vida
y poder en su corazón! ¡Mire hacia Él y la ayuda,
la compasión,
la salvación se levantarán en el tiempo de Él! Pero no se
levantarán de algo que usted pueda hacer o pensar.
La fe brotará, la paciencia le será dada,
y serán experimentados la esperanza en el tierno
Padre de misericordia y un espíritu manso y tranquilo.
La naturaleza del Cordero brotará y se abrirá en usted desde Su preciosa Semilla,
y sobresaldrá en naturaleza, tipo, grado y virtud más allá de toda la fe, paciencia,
esperanza, mansedumbre, etc., que usted o cualquier otro pudiera alcanzar de otra manera.

¡Oh, no mire su dolor o tristeza, por grande que sea!
Más bien, mire desde ellos, mire lejos de ellos, mire más allá de ellos al Libertador,
cuyo poder está sobre ellos y cuyo Espíritu amoroso,
sabio y tierno es capaz de hacerle bien por medio de ellos.
Y si las aflicciones externas obran un mayor peso de gloria,
¡qué no harán las aflicciones internas por los humildes,
quebrantados y fielmente ejercitados delante del Señor por ellas!

Si usted quiere recibir el reino que no puede ser sacudido,
debe esperar a que se descubra en usted el que puede ser sacudido.
Este debe ser removido de su lugar y los cielos enrollados como un rollo,
por el terriblemente levantamiento del Señor para sacudir la tierra.
Y mientras el Señor hace esto,
Él la esconderá en el hueco de su mano (mientras su mente permanece retirada en la Semilla),
y en estos tiempos angustiosos y tristes,
interiormente formará los nuevos cielos y la nueva tierra donde mora la justicia.
¡El Señor la guíe día a día en el camino recto, y guarde su mente sobria en Él,
en lo que le suceda! ¡Siga como una discípula,
aprendiendo la justicia y la santidad de Él,
quien enseña a negar y a despojarse de la impiedad y de la injusticia, y a conocer,
abrazar y a vestirse de la novedad de Su vida y de la santidad y justicia de ella!

El Señor Dios de mi vida esté con usted preservando y ordenando su corazón.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
A un Destinatario Desconocido

[.salutation]
Amigo,

Es por la infinita misericordia y compasión del Señor
que Su amor puro nos visita a cualquiera de nosotros,
y es sólo por Su preservación que permanecemos.
Si Él en cualquier momento nos dejara, incluso por un instante, ¿qué sería de nosotros?
¿Acaso existe una persona que no Lo provoque a partir?
Que ella arroje la primera piedra al que cae.

En la verdad misma, en el poder vivo y en la virtud no hay ofensa.
Sin embargo,
en la parte que no está perfectamente redimida todavía
hay lugar para que la tentación trabaje,
y pueda ser cogida en una trampa.
¡Qué el que está firme, tenga cuidado de no caer,
y con corazón compasivo llore y espere la restauración del que está caído!
Eso que es tan propenso a ofenderse, es lo mismo que cae.
¡Oh, no razone con altivez contra cualquiera que se desvíe del Guía puro!
Más bien tema,
no sea que la parte incrédula y de sabiduría carnal se levante en usted también. ¡Oh,
usted debe llegar a conocer la debilidad de la criatura cuando
la vida se retira! ¡Debe conocer la fuerza del enemigo en esa hora
y que solamente la gracia gratuita y la misericordia pueden preservar!
Sabiendo esto, se asombrará de que algunos permanezcan, en lugar de que algunos caigan.

Cuando las fuentes puras de la vida se abren en el corazón,
el enemigo busca inmediatamente su oportunidad de entrar,
y muchas veces encuentra entrada poco después,
porque el alma le teme poco o poco sospecha de él,
al haber experimentado recientemente una fuerza tan poderosa e invencible.
Sin embargo,
¡cuán a menudo entra el enemigo hiriendo la vida
hasta el piso! ¡Qué no haría él con la criatura,
si el Señor misericordiosamente no ayudara!

¡Oh, grande es el misterio de la piedad, angosto el camino de la vida; largo,
duro y peligroso el viaje a la tierra de reposo!
Es fácil frustrarse, es fácil hacerse a un lado en cualquier momento,
es fácil perder la gloriosa presencia del Señor,
a menos que la defensa alrededor de ella sea mantenida arriba por Su brazo Todopoderoso.
¡Ah, vuélvase de la sabiduría carnal y de los razonamientos al río puro de vida!
Espere allí hasta tener juzgado en usted eso que ha sido ofendido,
no sea que se fortalezca y lo aleje de la vida.

Lo que sigue es en amor para usted: Retírese de esa parte que mira hacia afuera,
y sienta la virtud interior de eso que puede restaurarlo y conservarlo.

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
A la Viuda Hemmings

[.salutation]
Mi querida amiga,

A quien siempre he amado verdadera y fielmente delante de los ojos del Señor,
y a quien mi amor en el Señor continúa.

Desde que oí de tu enfermedad y debilidad por el señor M. S.,
he tenido un profundo deseo de verte y he estado considerando cómo hacerlo,
pero por ahora no puedo hacerlo con alguna facilidad,
como mi amigo T. E. (el portador de esta carta) puede informarte
más. Pero el deseo de mi corazón para con el Dios de mi vida,
es que Él te visite en Su tierna compasión,
y te guíe y te ayude a mantener tu mente en Él, en Su más preciosa verdad, de la cual,
Él no sólo te ha dado gustarla, sino también completo sentido y experiencia muchas veces.

¡Oh, mi querida amiga,
qué nada se interponga entre tu alma y la verdad de Dios! ¡Qué tu consuelo,
paz y gozo sean plenos y puedas recostar tu cabeza quietamente en el seno
de Aquel que te ama y acepta los deseos sinceros de tu corazón hacia Él!
No le prestes atención a las tentaciones ni a las acusaciones,
ni a los muchos ruidos que el enemigo hará en ti y contra ti,
sino espera experimentar la verdad y la vida brotando en tu corazón desde el pozo santo,
y a escuchar la voz tranquila del Espíritu del Señor,
porque Él te dará testimonio de Su amor hacia ti y hablará paz.

¡Qué la tierna compasión de mi Padre celestial te alivie y te recoja internamente,
y te preserve donde el enemigo no pueda irrumpir en ti!
No mires tus pecados, ni siquiera los cometidos desde que has conocido la verdad.
Más bien espera sentir algo internamente, en lo cual Dios aparece, sopla, reúne,
recibe y tranquiliza los temores, las dudas, los problemas,
las tentaciones y las acusaciones.
¡Qué el Señor Dios de mi vida y Sus tiernas misericordias (que Él ha asegurado a mi
alma en el pacto eterno) te dé una paz sólida y consuelo en el Hijo de Su amor,
a través de la medida de Su gracia y verdad brotando
en tu corazón y afirmando tu mente en Él.

¡Oh, experimenta la Semilla y la fe que brota de ella!
Porque esto da victoria sobre el enemigo y sobre
todas sus misteriosas operaciones en el corazón.

[.signed-section-closing]
Tu amigo, en el más verdadero y sincero amor,

[.signed-section-signature]
I+++.+++ P.

[.letter-heading]
Para Catherine Pordage

[.salutation]
Amiga,

En la verdad del corazón y amor tierno hacia usted,
está en mí contestarle los pasajes principales de su carta, tan brevemente como pueda.

No ha sido mi deseo ni sacarla ni introducirla en la estima de las personas.
¡Qué el Señor la guíe en el juicio verdadero y le impida juzgar,
excepto hasta donde la luz se levante en usted que lo hace a uno capaz de juzgar!
Porque he conocido a muchos que han hablado muy gloriosamente de las Escrituras,
explicando cosas incluso hasta la admiración, y quienes a pesar de todo,
han estado fuera del Espíritu de verdad.
Estos han brillado con la luz y la vida de un espíritu equivocado,
aunque ellos mismos no saben que es así.

Es mejor que uno sienta su renuencia y que espere que el Señor lo prepare,
que pensar que se está listo,
y que al realizar su propia búsqueda se juzgue a sí mismo como tal.
Porque en varios casos me he creído listo,
asumiendo que si el Señor me hubiera mostrado Su voluntad, yo habría obedecido.
Sin embargo, encontré que era de otra manera,
cuando el Señor vino a poner la ley de Su Espíritu de vida sobre mí.

Ahora bien, de esto estoy seguro,
de que hay algo en usted que no está dispuesto a ser empobrecido,
y yo no puedo decir con respecto a usted, que aún esté dispuesta a separarse de eso.
Mientras eso esté, estará obrando en un misterio de engaño, escondido de su corazón,
lo cual usted no tiene posibilidad de discernir.
Pues sólo es discernido cuando se levanta la Semilla, y la luz pura brilla en usted.
Es muy posible que usted piense mejor de sí misma de lo que realmente es el caso,
porque le es difícil (en su estado presente) saber qué y cómo está
ante los ojos del Señor. Pues hay grandes y sutiles operaciones
del enemigo en su mente que están en contra de la verdad de Dios,
que usted no discierne ni evita.
Más bien, usted prefiere abrazar estas cosas como si fueran verdaderas y preciosas.

Le he escrito con gran franqueza y le ruego que esté dispuesta a tener la herida abierta,
según la necesidad de la condición de su alma, para que sea examinada a fondo,
y todo lo que sea para juicio sea juzgado y destruido.
De esta manera su alma será eternamente salvada por el Médico eterno,
quien es sabio y hábil en ministrar tanto juicio
como misericordia a todos de acuerdo a su necesidad.

[.signed-section-closing]
Su amigo verdadero, fiel y sincero en amor y ternura,

[.signed-section-signature]
I+++.+++ P.

[.signed-section-context-close]
Día 25, del mes 1, de 1671
